DynAdjust: dynadjust/dnageoid/bicubic_interpolation.hpp File Reference
bicubic_interpolation.hpp File Reference
Functions
template<class T>
void bcucof (T y[], T y1[], T y2[], T y12[], T c[4][4])
template<class T>
bool bcuint (T y[], T y1[], T y2[], T y12[], T &D1, T &D2, const T *longIncrement, const T *latIncrement, T *interpolant)
Variables
const int wt [16][16]
Function Documentation
bcucof()
template<class T> void bcucof (T y[], T y1[], T y2[], T y12[], T c[4][4])
Definition at line 71 of file bicubic_interpolation.hpp.
{
    int l(0), k(0), j(0), i(0);
    T xx(0.), cl[16], x[16];
    for (i=0; i<4; i++)         // Pack a temporary vector x.
    {
        x[i] = y[i];
        x[i+4] = y1[i];
        x[i+8] = y2[i];
        x[i+12] = y12[i];
    }
    for (i=0; i<16; i++)        // Matrix multiply by the stored table.
    {
        xx = 0.0;
        for (k=0; k<16; k++)
            xx += wt[i][k] * x[k];
        cl[i] = xx;
    }
    l = 0;
    for (i=0; i<4; i++)         // Unpack the result into the output table.
    {
        for (j=0; j<4; j++)
            c[i][j] = cl[l++];
    }
}
References wt.
Referenced by bcuint().
bcuint()
template<class T> bool bcuint (T y[], T y1[], T y2[], T y12[], T & D1, T & D2, const T * longIncrement, const T * latIncrement, T * interpolant)
Definition at line 108 of file bicubic_interpolation.hpp.
{
    //double double_type(1);
    //float float_type(1);
    //if ((typeid(D1) != typeid(double_type)) &&    // not a double
    //  (typeid(D1) != typeid(float_type)))     // and not a float... crash!
    //{
    //  throw runtime_error("Not a floating point type");
    //}
    int i;
    T t = D1 / *longIncrement;
    T u = D2 / *latIncrement;
    T c[4][4];
    bcucof(y, y1, y2, y12, c);
    *interpolant = 0.0;
    for (i=3; i>=0; i--)
        *interpolant = t * (*interpolant) + ((((c[i][3] * u) + c[i][2]) * u) + c[i][1]) * u + c[i][0];
    //  *ansy2= t * (*ansy2) + (3.0 * c[i][3] * u + 2.0 * c[i][2]) * u + c[i][1];
    //  *ansy1 = u * (*ansy1) + (3.0 * c[3][i] * t + 2.0 *  c[2][i]) * t + c[1][i];
    //}
    //*ansy1 /= D1;
    //*ansy2 /= D2;
    return true;
}
References bcucof().
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::InterpolateNvalue_BiCubic().
Variable Documentation
wt
const int wt[16][16]
Initial value:
=   {
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,
    -3,0,0,3,0,0,0,0,-2,0,0,-1,0,0,0,0,
    2,0,0,-2,0,0,0,0,1,0,0,1,0,0,0,0,
    0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,
    0,0,0,0,-3,0,0,3,0,0,0,0,-2,0,0,-1,
    0,0,0,0,2,0,0,-2,0,0,0,0,1,0,0,1,
    -3,3,0,0,-2,-1,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,-3,3,0,0,-2,-1,0,0,
    9,-9,9,-9,6,3,-3,-6,6,-6,-3,3,4,2,1,2,
    -6,6,-6,6,-4,-2,2,4,-3,3,3,-3,-2,-1,-1,-2,
    2,-2,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,2,-2,0,0,1,1,0,0,
    -6,6,-6,6,-3,-3,3,3,-4,4,2,-2,-2,-2,-1,-1,
    4,-4,4,-4,2,2,-2,-2,2,-2,-2,2,1,1,1,1
}
Definition at line 45 of file bicubic_interpolation.hpp.
{
    1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,
    -3,0,0,3,0,0,0,0,-2,0,0,-1,0,0,0,0,
    2,0,0,-2,0,0,0,0,1,0,0,1,0,0,0,0,
    0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,
    0,0,0,0,-3,0,0,3,0,0,0,0,-2,0,0,-1,
    0,0,0,0,2,0,0,-2,0,0,0,0,1,0,0,1,
    -3,3,0,0,-2,-1,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,-3,3,0,0,-2,-1,0,0,
    9,-9,9,-9,6,3,-3,-6,6,-6,-3,3,4,2,1,2,
    -6,6,-6,6,-4,-2,2,4,-3,3,3,-3,-2,-1,-1,-2,
    2,-2,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,2,-2,0,0,1,1,0,0,
    -6,6,-6,6,-3,-3,3,3,-4,4,2,-2,-2,-2,-1,-1,
    4,-4,4,-4,2,2,-2,-2,2,-2,-2,2,1,1,1,1
};
Referenced by bcucof().