DynAdjust: dynadjust::iostreams::dna_io_bst Class Reference
dynadjust::iostreams::dna_io_bst Class Reference
#include <dnaiobst.hpp>
Public Member Functions
dna_io_bst (void)
dna_io_bst (const dna_io_bst &bst)
virtual ~dna_io_bst (void)
dna_io_bst & operator= (const dna_io_bst &rhs)
UINT16 create_stn_input_file_meta (vifm_t &vinput_file_meta, input_file_meta_t **input_file_meta)
void load_bst_file_meta (const std::string &bst_filename, binary_file_meta_t &bst_meta)
UINT32 load_bst_file (const std::string &bst_filename, pvstn_t vbinary_stn, binary_file_meta_t &bst_meta)
void write_bst_file (const std::string &bst_filename, pvstn_t vbinary_stn, binary_file_meta_t &bst_meta)
bool write_bst_file (const std::string &bst_filename, vdnaStnPtr *vStations, pvstring vUnusedStns, binary_file_meta_t &bst_meta, bool flagUnused)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 41 of file dnaiobst.hpp.
Constructor & Destructor Documentation
dna_io_bst() [1/2]
dynadjust::iostreams::dna_io_bst::dna_io_bst (void) inline
Definition at line 44 of file dnaiobst.hpp.
{};
Referenced by dna_io_bst(), and operator=().
dna_io_bst() [2/2]
dynadjust::iostreams::dna_io_bst::dna_io_bst (const dna_io_bst & bst) inline
Definition at line 45 of file dnaiobst.hpp.
: dna_io_base(bst) {};
References dynadjust::iostreams::dna_io_base::dna_io_base(), and dna_io_bst().
~dna_io_bst()
virtual dynadjust::iostreams::dna_io_bst::~dna_io_bst (void) inline virtual
Definition at line 46 of file dnaiobst.hpp.
{};
Member Function Documentation
operator=()
dna_io_bst & dynadjust::iostreams::dna_io_bst::operator= (const dna_io_bst & rhs)
References dna_io_bst().
create_stn_input_file_meta()
UINT16 dynadjust::iostreams::dna_io_bst::create_stn_input_file_meta (vifm_t & vinput_file_meta, input_file_meta_t ** input_file_meta)
Definition at line 29 of file dnaiobst.cpp.
{
    UINT16 stn_file_count(0);
    std::stringstream ss;
    ss << "create_stn_input_file_meta(): An error was encountered when creating " << std::endl <<
        "  the binary station file metadata." << std::endl;
    // Determine how many station files were supplied
    try {
        for_each(vinput_file_meta.begin(), vinput_file_meta.end(),
            [&stn_file_count] (input_file_meta_t& ifm) {
                if (ifm.datatype == stn_data || ifm.datatype == stn_msr_data)
                    stn_file_count++;
        });
        if (*input_file_meta != NULL)
            delete [] *input_file_meta;
        (*input_file_meta) = new input_file_meta_t[stn_file_count];
        stn_file_count = 0;
        for_each(vinput_file_meta.begin(), vinput_file_meta.end(),
            [&stn_file_count, &input_file_meta] (input_file_meta_t& ifm) {
                if (ifm.datatype == stn_data || ifm.datatype == stn_msr_data)
                {
                    (*input_file_meta)[stn_file_count] = ifm;
                    stn_file_count++;
                }
        });
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return stn_file_count;
}
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseBst().
load_bst_file_meta()
void dynadjust::iostreams::dna_io_bst::load_bst_file_meta (const std::string & bst_filename, binary_file_meta_t & bst_meta)
Definition at line 67 of file dnaiobst.cpp.
{
    std::ifstream bst_file;
    std::stringstream ss;
    ss << "load_bst_file(): An error was encountered when opening " << bst_filename << "." << std::endl;
    try {
        // open binary stations file.  Throws runtime_error on failure.
        file_opener(bst_file, bst_filename, std::ios::in | std::ios::binary, binary, true);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "load_bst_file(): An error was encountered when reading from " << bst_filename << "." << std::endl;
    try {
        // read the file information
        readFileInfo(bst_file);
        // read the metadata
        readFileMetadata(bst_file, bst_meta);
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    bst_file.close();
}
References binary, file_opener(), load_bst_file_meta(), dynadjust::iostreams::dna_io_base::readFileInfo(), and dynadjust::iostreams::dna_io_base::readFileMetadata().
Referenced by load_bst_file_meta(), LoadBinaryMeta(), main(), PrepareImportSegmentedData(), and dynadjust::networkadjust::dna_adjust::SetDefaultReferenceFrame().
load_bst_file()
UINT32 dynadjust::iostreams::dna_io_bst::load_bst_file (const std::string & bst_filename, pvstn_t vbinary_stn, binary_file_meta_t & bst_meta)
Definition at line 111 of file dnaiobst.cpp.
{
    std::ifstream bst_file;
    std::stringstream ss;
    ss << "load_bst_file(): An error was encountered when opening " << bst_filename << "." << std::endl;
    try {
        // open binary stations file.  Throws runtime_error on failure.
        file_opener(bst_file, bst_filename, std::ios::in | std::ios::binary, binary, true);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    station_t stationRecord;
    UINT32 stn;
    ss.str("");
    ss << "load_bst_file(): An error was encountered when reading from " << bst_filename << "." << std::endl;
    try {
        // read the file information
        readFileInfo(bst_file);
        // read the metadata
        readFileMetadata(bst_file, bst_meta);
        // read the bms data
        vbinary_stn->reserve(bst_meta.binCount);
        for (stn=0; stn<bst_meta.binCount; stn++)
        {
            bst_file.read(reinterpret_cast<char *>(&stationRecord), sizeof(station_t));
            vbinary_stn->push_back(stationRecord);
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    bst_file.close();
    return bst_meta.binCount;
}
References binary, binary_file_meta::binCount, file_opener(), load_bst_file(), dynadjust::iostreams::dna_io_base::readFileInfo(), and dynadjust::iostreams::dna_io_base::readFileMetadata().
Referenced by load_bst_file(), dynadjust::dynamlinterop::dna_import::LoadBinaryFiles(), dynadjust::networkplot::dna_plot::LoadBinaryFiles(), dynadjust::networksegment::dna_segment::LoadBinaryFiles(), dynadjust::geoidinterpolation::dna_geoid_interpolation::LoadBinaryStationFile(), dynadjust::referenceframe::dna_reftran::LoadBinaryStationFile(), dynadjust::networkadjust::dna_adjust::LoadNetworkFiles(), and dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations().
write_bst_file() [1/2]
void dynadjust::iostreams::dna_io_bst::write_bst_file (const std::string & bst_filename, pvstn_t vbinary_stn, binary_file_meta_t & bst_meta)
Definition at line 167 of file dnaiobst.cpp.
{
    std::ofstream bst_file;
    std::stringstream ss;
    ss << "write_bst_file(): An error was encountered when opening " << bst_filename << "." << std::endl;
    try {
        // open binary stations file.  Throws runtime_error on failure.
        file_opener(bst_file, bst_filename,
            std::ios::out | std::ios::binary, binary);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_bst_file(): An error was encountered when writing to " << bst_filename << "." << std::endl;
    try {
        // write version
        writeFileInfo(bst_file);
        // write the metadata
        writeFileMetadata(bst_file, bst_meta);
        // write the bst data
        it_vstn_t _it_stn(vbinary_stn->begin());
        for (; _it_stn!=vbinary_stn->end(); ++_it_stn)
            bst_file.write(reinterpret_cast<char *>(&(*_it_stn)), sizeof(station_t));
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    bst_file.close();
}
References binary, file_opener(), write_bst_file(), dynadjust::iostreams::dna_io_base::writeFileInfo(), and dynadjust::iostreams::dna_io_base::writeFileMetadata().
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseBst(), dynadjust::networkadjust::dna_adjust::UpdateBinaryFiles(), write_bst_file(), write_bst_file(), dynadjust::geoidinterpolation::dna_geoid_interpolation::WriteBinaryStationFile(), and dynadjust::referenceframe::dna_reftran::WriteBinaryStationFile().
write_bst_file() [2/2]
bool dynadjust::iostreams::dna_io_bst::write_bst_file (const std::string & bst_filename, vdnaStnPtr * vStations, pvstring vUnusedStns, binary_file_meta_t & bst_meta, bool flagUnused)
Definition at line 216 of file dnaiobst.cpp.
{
    std::ofstream bst_file;
    std::stringstream ss;
    ss << "write_bst_file(): An error was encountered when opening " << bst_filename << "." << std::endl;
    try {
        // open binary stations file.  Throws runtime_error on failure.
        file_opener(bst_file, bst_filename,
            std::ios::out | std::ios::binary, binary);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_bst_file(): An error was encountered when writing to " << bst_filename << "." << std::endl;
    _it_vdnastnptr _it_stn;
    try {
        // write version
        writeFileInfo(bst_file);
        // write the metadata
        writeFileMetadata(bst_file, bst_meta);
        // write the bst data
        if (flagUnused)
        {
            std::sort(vUnusedStns->begin(), vUnusedStns->end());
            for (_it_stn=vStations->begin(); _it_stn!=vStations->end(); _it_stn++)
            {
                if (binary_search(vUnusedStns->begin(), vUnusedStns->end(), _it_stn->get()->GetName()))
                {
                    _it_stn->get()->SetStationUnused();
                    _it_stn->get()->WriteBinaryStn(&bst_file, TRUE);
                }
                else
                    _it_stn->get()->WriteBinaryStn(&bst_file);
            }
        }
        else
            for (_it_stn=vStations->begin(); _it_stn!=vStations->end(); _it_stn++)
                _it_stn->get()->WriteBinaryStn(&bst_file);
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    bst_file.close();
    return true;
}
References binary, file_opener(), TRUE, write_bst_file(), dynadjust::iostreams::dna_io_base::writeFileInfo(), and dynadjust::iostreams::dna_io_base::writeFileMetadata().
The documentation for this class was generated from the following files:
include/io/dnaiobst.hpp
include/io/dnaiobst.cpp