DynAdjust: dynadjust::measurements::CDnaHeightDifference Class Reference
dynadjust::measurements::CDnaHeightDifference Class Reference
#include <dnaheightdifference.hpp>
Public Member Functions
CDnaHeightDifference (void)
virtual ~CDnaHeightDifference (void)
bool operator== (const CDnaHeightDifference &rhs) const
bool operator< (const CDnaHeightDifference &rhs) const
std::string GetTarget () const
double GetValue () const
double GetStdDev () const
void SetTarget (const std::string &str)
void SetValue (const std::string &str)
void SetStdDev (const std::string &str)
virtual UINT32 CalcBinaryRecordCount () const
virtual void WriteBinaryMsr (std::ofstream *binary_stream, PUINT32 msrIndex) const
virtual UINT32 SetMeasurementRec (const vstn_t &binaryStn, it_vmsr_t &it_msr, it_vdbid_t &dbidmap)
virtual void WriteDynaMLMsr (std::ofstream *dynaml_stream, const std::string &comment, bool) const
virtual void WriteDNAMsr (std::ofstream *dna_stream, const dna_msr_fields &dmw, const dna_msr_fields &dml, bool) const
virtual void SimulateMsr (vdnaStnPtr *vStations, const CDnaEllipsoid *ellipsoid)
Public Member Functions inherited from dynadjust::measurements::CDnaHeight
CDnaHeight (void)
virtual ~CDnaHeight (void)
bool operator== (const CDnaHeight &rhs) const
bool operator< (const CDnaHeight &rhs) const
Public Member Functions inherited from dynadjust::measurements::CDnaMeasurement
CDnaMeasurement ()
virtual ~CDnaMeasurement ()
CDnaMeasurement (CDnaMeasurement &&m)
CDnaMeasurement & operator= (CDnaMeasurement &&rhs)
std::string GetType () const
char GetTypeC () const
bool GetIgnore () const
bool NotIgnored () const
std::string GetFirst () const
MEASUREMENT_STATIONS GetMsrStnCount () const
std::string GetEpsg () const
std::string GetSource () const
bool GetInsufficient () const
void SetType (const std::string &str)
void SetIgnore (const bool bval)
void SetFirst (const std::string &str)
void SetEpsg (const std::string &e)
void SetSource (const std::string &source)
void SetInsufficient (const bool bval)
void SetMsrIndex (const UINT32 &order)
void SetStn1Index (const UINT32 &order)
void SetStn2Index (const UINT32 &order)
void SetStn3Index (const UINT32 &order)
UINT32 GetMsrIndex () const
UINT32 GetStn1Index () const
UINT32 GetStn2Index () const
UINT32 GetStn3Index () const
double GetMeasAdj () const
double GetMeasCorr () const
double GetMeasAdjPrec () const
double GetResidualPrec () const
double GetPreAdjCorr () const
virtual void PopulateMsr (pvstn_t, uint32_uint32_map *, vUINT32 *, const UINT32 &, const CDnaDatum *, math::matrix_2d *, math::matrix_2d *)
virtual UINT32 GetClusterID () const
virtual std::string GetCoordType () const
virtual float GetInstrHeight () const
virtual double GetVscale () const
virtual double GetPscale () const
virtual double GetLscale () const
virtual double GetHscale () const
virtual std::string GetTarget2 () const
virtual float GetTargetHeight () const
virtual UINT32 GetTotal () const
virtual std::string GetReferenceFrame () const
std::string GetEpoch () const
virtual std::vector< CDnaGpsBaseline > * GetBaselines_ptr ()
virtual std::vector< CDnaDirection > * GetDirections_ptr ()
virtual std::vector< CDnaGpsPoint > * GetPoints_ptr ()
virtual std::vector< CDnaCovariance > * GetCovariances_ptr ()
virtual void AddDirection (const CDnaMeasurement *)
virtual void AddGpsBaseline (const CDnaMeasurement *)
virtual void AddGpsPoint (const CDnaMeasurement *)
virtual void AddGpsCovariance (const CDnaCovariance *)
virtual void AddPointCovariance (const CDnaCovariance *)
virtual void ReserveDirectionsCount (const UINT32 &)
virtual void ReserveGpsBaselinesCount (const UINT32 &)
virtual void ReserveGpsPointsCount (const UINT32 &)
virtual void ReserveGpsCovariancesCount (const UINT32 &)
virtual void ResizeGpsCovariancesCount (const UINT32 &)
virtual void SetRecordedTotal (const UINT32 &)
virtual void SetNonIgnoredDirns (const UINT32 &)
virtual void SetClusterID (const UINT32 &)
virtual void SetCoordType (const std::string &)
virtual void SetHscale (const std::string &)
virtual void SetHscale (const double &)
virtual void SetInstrumentHeight (const std::string &)
virtual void SetReferenceFrame (const std::string &)
void SetEpoch (const std::string &epoch)
virtual void SetLscale (const std::string &)
virtual void SetLscale (const double &)
virtual void SetPscale (const std::string &)
virtual void SetPscale (const double &)
virtual void SetSigmaXX (const std::string &)
virtual void SetSigmaXY (const std::string &)
virtual void SetSigmaXZ (const std::string &)
virtual void SetSigmaYY (const std::string &)
virtual void SetSigmaYZ (const std::string &)
virtual void SetSigmaZZ (const std::string &)
virtual void SetTarget2 (const std::string &)
virtual void SetTargetHeight (const std::string &)
virtual void SetTotal (const std::string &)
virtual void SetVscale (const std::string &)
virtual void SetVscale (const double &)
virtual void SetX (const std::string &)
virtual void SetY (const std::string &)
virtual void SetZ (const std::string &)
virtual void SetXAxis (const double &)
virtual void SetYAxis (const double &)
virtual void SetZAxis (const double &)
virtual void SetSigmaXX (const double &)
virtual void SetSigmaXY (const double &)
virtual void SetSigmaXZ (const double &)
virtual void SetSigmaYY (const double &)
virtual void SetSigmaYZ (const double &)
virtual void SetSigmaZZ (const double &)
virtual void SetTotal (const UINT32 &)
virtual void PreferGMeasurements ()
void SetMeasurementDBID (const std::string &str)
void SetClusterDBID (const std::string &str)
void SetClusterDBID (const UINT32 &u, bool s)
UINT32 GetClusterDBID ()
bool GetClusterDBIDset ()
void SetDatabaseMap (const msr_database_id_map &dbidmap)
virtual void SetDatabaseMaps (it_vdbid_t &it_dbidmap)
virtual void SerialiseDatabaseMap (std::ofstream *os)
Public Attributes
std::string m_strTarget
double m_dValue
double m_dStdDev
Public Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strFirst
MEASUREMENT_STATIONS m_MSmeasurementStations
Additional Inherited Members
Protected Member Functions inherited from dynadjust::measurements::CDnaMeasurement
void coutMeasurement (std::ostream &os) const
Protected Attributes inherited from dynadjust::measurements::CDnaHeight
double m_dValue
double m_dStdDev
Protected Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strType
bool m_bIgnore
UINT32 m_lmeasurementIndex
UINT32 m_lstn1Index
UINT32 m_lstn2Index
UINT32 m_lstn3Index
double m_measAdj
double m_measCorr
double m_measAdjPrec
double m_residualPrec
double m_preAdjCorr
std::string m_epsgCode
std::string m_sourceFile
std::string m_epoch
msr_database_id_map m_msr_db_map
bool m_bInsufficient
Detailed Description
Definition at line 37 of file dnaheightdifference.hpp.
Constructor & Destructor Documentation
CDnaHeightDifference()
dynadjust::measurements::CDnaHeightDifference::CDnaHeightDifference (void)
Definition at line 32 of file dnaheightdifference.cpp.
    : m_strTarget("")
    , m_dValue(0.)
    , m_dStdDev(0.)
{
    m_strType = "L";       // default is Slope distance, but could also be 'C' or 'E' or 'M'
    m_MSmeasurementStations = TWO_STATION;
}
References m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, and TWO_STATION.
Referenced by operator<(), and operator==().
~CDnaHeightDifference()
dynadjust::measurements::CDnaHeightDifference::~CDnaHeightDifference (void) virtual
Definition at line 42 of file dnaheightdifference.cpp.
{
}
Member Function Documentation
operator==()
bool dynadjust::measurements::CDnaHeightDifference::operator== (const CDnaHeightDifference & rhs) const
Definition at line 48 of file dnaheightdifference.cpp.
{
    return (
        m_strFirst == rhs.m_strFirst &&
        m_strTarget == rhs.m_strTarget &&
        m_strType == rhs.m_strType &&
        m_bIgnore == rhs.m_bIgnore &&
        m_dValue == rhs.m_dValue &&
        m_dStdDev == rhs.m_dStdDev &&
        m_epoch == rhs.m_epoch
        );
}
References CDnaHeightDifference(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, and dynadjust::measurements::CDnaMeasurement::m_strType.
operator<()
bool dynadjust::measurements::CDnaHeightDifference::operator< (const CDnaHeightDifference & rhs) const
Definition at line 62 of file dnaheightdifference.cpp.
{
    if (m_strFirst == rhs.m_strFirst) {
        if (m_strType == rhs.m_strType) {  // don't think this is needed
            if (m_bIgnore == rhs.m_bIgnore) {
                if (m_epoch == rhs.m_epoch) {
                    if (m_strTarget == rhs.m_strTarget) {
                        if (m_dValue == rhs.m_dValue)
                            return m_dStdDev < rhs.m_dStdDev;
                        else
                            return m_dValue < rhs.m_dValue; }
                    else
                        return m_strTarget < rhs.m_strTarget; }
                else
                    return m_epoch < rhs.m_epoch; }
            else
                return m_bIgnore < rhs.m_bIgnore; }
        else
            return m_strType < rhs.m_strType; }
    else
        return m_strFirst < rhs.m_strFirst;
}
References CDnaHeightDifference(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, and dynadjust::measurements::CDnaMeasurement::m_strType.
GetTarget()
std::string dynadjust::measurements::CDnaHeightDifference::GetTarget () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 57 of file dnaheightdifference.hpp.
{ return m_strTarget; }
References m_strTarget.
GetValue()
double dynadjust::measurements::CDnaHeightDifference::GetValue () const inline virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 58 of file dnaheightdifference.hpp.
{ return m_dValue; }
References m_dValue.
GetStdDev()
double dynadjust::measurements::CDnaHeightDifference::GetStdDev () const inline virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 59 of file dnaheightdifference.hpp.
{ return m_dStdDev; }
References m_dStdDev.
SetTarget()
void dynadjust::measurements::CDnaHeightDifference::SetTarget (const std::string & str) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 61 of file dnaheightdifference.hpp.
{ m_strTarget = trimstr(str); }
References m_strTarget, and trimstr().
SetValue()
void dynadjust::measurements::CDnaHeightDifference::SetValue (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 254 of file dnaheightdifference.cpp.
{
    DoubleFromString(m_dValue, trimstr(str));
}
References DoubleFromString(), m_dValue, and trimstr().
SetStdDev()
void dynadjust::measurements::CDnaHeightDifference::SetStdDev (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 259 of file dnaheightdifference.cpp.
{
    DoubleFromString(m_dStdDev, trimstr(str));
}
References DoubleFromString(), m_dStdDev, and trimstr().
CalcBinaryRecordCount()
virtual UINT32 dynadjust::measurements::CDnaHeightDifference::CalcBinaryRecordCount () const inline virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 66 of file dnaheightdifference.hpp.
{ return 1; }
WriteBinaryMsr()
void dynadjust::measurements::CDnaHeightDifference::WriteBinaryMsr (std::ofstream * binary_stream, PUINT32 msrIndex) const virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 230 of file dnaheightdifference.cpp.
{
    measurement_t measRecord;
    measRecord.measType = GetTypeC();
    measRecord.measStart = xMeas;
    measRecord.ignore = m_bIgnore;
    measRecord.station1 = m_lstn1Index;
    measRecord.station2 = m_lstn2Index;
    measRecord.measAdj = m_measAdj;
    measRecord.measCorr = m_measCorr;
    measRecord.measAdjPrec = m_measAdjPrec;
    measRecord.residualPrec = m_residualPrec;
    measRecord.preAdjCorr = m_preAdjCorr;
    measRecord.term1 = m_dValue;
    measRecord.term2 = m_dStdDev * m_dStdDev; // convert to variance
    measRecord.measurementStations = m_MSmeasurementStations;
    measRecord.fileOrder = ((*msrIndex)++);
    snprintf(measRecord.epoch, sizeof(measRecord.epoch), "%s", m_epoch.substr(0, STN_EPOCH_WIDTH).c_str());
    binary_stream->write(reinterpret_cast<char *>(&measRecord), sizeof(measurement_t));
}
References dynadjust::measurements::msr_t::epoch, dynadjust::measurements::msr_t::fileOrder, dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::msr_t::ignore, dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::msr_t::measAdj, dynadjust::measurements::msr_t::measAdjPrec, dynadjust::measurements::msr_t::measCorr, dynadjust::measurements::msr_t::measStart, dynadjust::measurements::msr_t::measType, dynadjust::measurements::msr_t::measurementStations, dynadjust::measurements::msr_t::preAdjCorr, dynadjust::measurements::msr_t::residualPrec, dynadjust::measurements::msr_t::station1, dynadjust::measurements::msr_t::station2, STN_EPOCH_WIDTH(), dynadjust::measurements::msr_t::term1, dynadjust::measurements::msr_t::term2, and xMeas.
SetMeasurementRec()
UINT32 dynadjust::measurements::CDnaHeightDifference::SetMeasurementRec (const vstn_t & binaryStn, it_vmsr_t & it_msr, it_vdbid_t & dbidmap) virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 199 of file dnaheightdifference.cpp.
{
    m_bIgnore = it_msr->ignore;
    m_MSmeasurementStations = (MEASUREMENT_STATIONS)it_msr->measurementStations;
    m_strType = it_msr->measType;
    // first station
    m_lstn1Index = it_msr->station1;
    m_strFirst = binaryStn.at(it_msr->station1).stationName;
    // target station
    m_lstn2Index = it_msr->station2;
    m_strTarget = binaryStn.at(it_msr->station2).stationName;
    m_measAdj = it_msr->measAdj;
    m_measCorr = it_msr->measCorr;
    m_measAdjPrec = it_msr->measAdjPrec;
    m_residualPrec = it_msr->residualPrec;
    m_preAdjCorr = it_msr->preAdjCorr;
    m_dValue = it_msr->term1;
    m_dStdDev = sqrt(it_msr->term2);
    m_epoch = it_msr->epoch;
    CDnaMeasurement::SetDatabaseMap(*dbidmap);
    return 0;
}
References dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, and dynadjust::measurements::CDnaMeasurement::SetDatabaseMap().
WriteDynaMLMsr()
void dynadjust::measurements::CDnaHeightDifference::WriteDynaMLMsr (std::ofstream * dynaml_stream, const std::string & comment, bool) const virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 86 of file dnaheightdifference.cpp.
{
    if (comment.empty())
        *dynaml_stream << "  <!-- Type " << measurement_name<char, std::string>(GetTypeC()) << " -->" << std::endl;
    else
        *dynaml_stream << "  <!-- " << comment << " -->" << std::endl;
    *dynaml_stream << "  <DnaMeasurement>" << std::endl;
    *dynaml_stream << "    <Type>" << m_strType << "</Type>" << std::endl;
    // Source file from which the measurement came
    *dynaml_stream << "    <Source>" << m_sourceFile << "</Source>" << std::endl;
    if (m_bIgnore)
        *dynaml_stream << "    <Ignore>*</Ignore>" << std::endl;
    else
        *dynaml_stream << "    <Ignore/>" << std::endl;
    if (m_epoch.empty())
        *dynaml_stream << "    <Epoch/>" << std::endl;
    else
        *dynaml_stream << "    <Epoch>" << m_epoch << "</Epoch>" << std::endl;
    *dynaml_stream << "    <First>" << m_strFirst << "</First>" << std::endl;
    *dynaml_stream << "    <Second>" << m_strTarget << "</Second>" << std::endl;
    *dynaml_stream << "    <Value>" << std::fixed << std::setprecision(4) << m_dValue << "</Value>" << std::endl;
    *dynaml_stream << "    <StdDev>" << std::fixed << std::setprecision(6) << m_dStdDev << "</StdDev>" << std::endl;
    if (m_msr_db_map.is_msr_id_set)
        *dynaml_stream << "    <MeasurementID>" << m_msr_db_map.msr_id << "</MeasurementID>" << std::endl;
    *dynaml_stream << "  </DnaMeasurement>" << std::endl;
}
References dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_sourceFile, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, and dynadjust::measurements::measurement_name().
WriteDNAMsr()
void dynadjust::measurements::CDnaHeightDifference::WriteDNAMsr (std::ofstream * dna_stream, const dna_msr_fields & dmw, const dna_msr_fields & dml, bool) const virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 119 of file dnaheightdifference.cpp.
{
    *dna_stream << std::setw(dmw.msr_type) << m_strType;
    if (m_bIgnore)
        *dna_stream << std::setw(dmw.msr_ignore) << "*";
    else
        *dna_stream << std::setw(dmw.msr_ignore) << " ";
    *dna_stream << std::left << std::setw(dmw.msr_inst) << m_strFirst;
    *dna_stream << std::left << std::setw(dmw.msr_targ1) << m_strTarget;
    *dna_stream << std::setw(dmw.msr_targ2) << " ";
    *dna_stream << std::right << std::setw(dmw.msr_linear) << std::fixed << std::setprecision(4) << m_dValue; // linear measurement value
    *dna_stream << std::setw(dmw.msr_ang_d + dmw.msr_ang_m + dmw.msr_ang_s) << " ";
    UINT32 m_stdDevPrec(3); // note change from 6 decimal places to 3
    *dna_stream << std::setw(dmw.msr_stddev) << StringFromTW(m_dStdDev, dmw.msr_stddev, m_stdDevPrec);
    //*dna_stream << std::setw(dmw.msr_stddev) << std::fixed << std::setprecision(6) << m_dStdDev;
    *dna_stream << std::setw(dml.msr_gps_epoch - dml.msr_inst_ht) << " ";
    *dna_stream << std::setw(dmw.msr_gps_epoch) << m_epoch;
    if (m_msr_db_map.is_msr_id_set)
        *dna_stream << std::setw(dmw.msr_id_msr) << m_msr_db_map.msr_id;
    *dna_stream << std::endl;
}
References dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, dna_msr_fields::msr_ang_d, dna_msr_fields::msr_ang_m, dna_msr_fields::msr_ang_s, dna_msr_fields::msr_gps_epoch, dna_msr_fields::msr_id_msr, dna_msr_fields::msr_ignore, dna_msr_fields::msr_inst, dna_msr_fields::msr_inst_ht, dna_msr_fields::msr_linear, dna_msr_fields::msr_stddev, dna_msr_fields::msr_targ1, dna_msr_fields::msr_targ2, dna_msr_fields::msr_type, and StringFromTW().
SimulateMsr()
void dynadjust::measurements::CDnaHeightDifference::SimulateMsr (vdnaStnPtr * vStations, const CDnaEllipsoid * ellipsoid) virtual
Reimplemented from dynadjust::measurements::CDnaHeight.
Definition at line 147 of file dnaheightdifference.cpp.
{
    // Zn is the z coordinate element of the point on the z-axis
    // which intersects with the the normal at the given Latitude
    double h1, h2, nu1, Zn1, nu2, Zn2;
    // calculated height
    m_dValue = EllipsoidHeightDifference<double>(
        vStations->at(m_lstn1Index).get()->GetXAxis(),
        vStations->at(m_lstn1Index).get()->GetYAxis(),
        vStations->at(m_lstn1Index).get()->GetZAxis(),
        vStations->at(m_lstn2Index).get()->GetXAxis(),
        vStations->at(m_lstn2Index).get()->GetYAxis(),
        vStations->at(m_lstn2Index).get()->GetZAxis(),
        vStations->at(m_lstn1Index).get()->GetcurrentLatitude(),
        vStations->at(m_lstn2Index).get()->GetcurrentLatitude(),
        &h1, &h2, &nu1, &Zn1, &nu2, &Zn2, ellipsoid);
    double distance = GreatCircleDistance<double>(
        vStations->at(m_lstn1Index).get()->GetcurrentLatitude(),
        vStations->at(m_lstn1Index).get()->GetcurrentLongitude(),
        vStations->at(m_lstn2Index).get()->GetcurrentLatitude(),
        vStations->at(m_lstn2Index).get()->GetcurrentLongitude());
    m_dStdDev = 3.0 * sqrt(distance / 1000.0) / 100.0;
    m_epoch = "01.10.1985";
    // N value available?
    if (fabs(vStations->at(m_lstn1Index).get()->GetgeoidSep()) > PRECISION_1E4 ||
        fabs(vStations->at(m_lstn2Index).get()->GetgeoidSep()) > PRECISION_1E4)
    {
        // reduce to orthometric height difference
        m_preAdjCorr = vStations->at(m_lstn2Index).get()->GetgeoidSep() - vStations->at(m_lstn1Index).get()->GetgeoidSep();
        m_dValue -= m_preAdjCorr;
    }
    // TODO - add option to perturb all measurements and standard deviations by a small (random) amount
    //      - Below is an example of how this might be achieved
    //
    //m_dStdDev = static_cast<double>(stdev(rng)) * sqrt(distance / 1000.0) / 100.0;
    //
    //double whichway = static_cast<double>(pertu(rng));
    //if (whichway > 0.5)
    //  m_dValue -= static_cast<double>(pertu(rng))/10.0;
    //else
    //  m_dValue += static_cast<double>(pertu(rng))/10.0;
}
References EllipsoidHeightDifference(), GreatCircleDistance(), m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, and PRECISION_1E4().
Member Data Documentation
m_strTarget
std::string dynadjust::measurements::CDnaHeightDifference::m_strTarget
Definition at line 74 of file dnaheightdifference.hpp.
Referenced by CDnaHeightDifference(), GetTarget(), operator<(), operator==(), SetMeasurementRec(), SetTarget(), WriteDNAMsr(), and WriteDynaMLMsr().
m_dValue
double dynadjust::measurements::CDnaHeightDifference::m_dValue
Definition at line 75 of file dnaheightdifference.hpp.
Referenced by CDnaHeightDifference(), GetValue(), operator<(), operator==(), SetMeasurementRec(), SetValue(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_dStdDev
double dynadjust::measurements::CDnaHeightDifference::m_dStdDev
Definition at line 76 of file dnaheightdifference.hpp.
Referenced by CDnaHeightDifference(), GetStdDev(), operator<(), operator==(), SetMeasurementRec(), SetStdDev(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
The documentation for this class was generated from the following files:
include/measurement_types/dnaheightdifference.hpp
include/measurement_types/dnaheightdifference.cpp