DynAdjust: dynadjust::measurements::CAStationList Class Reference
dynadjust::measurements::CAStationList Class Reference
#include <dnastation.hpp>
Public Member Functions
CAStationList ()
CAStationList (bool validStation)
virtual ~CAStationList ()
CAStationList (const CAStationList &&s)
CAStationList & operator= (CAStationList &&rhs)
CAStationList * handle ()
void SetInvalid ()
void SetValid ()
bool IsInvalid ()
bool IsValid ()
UINT32 GetAvailMsrCount () const
UINT32 GetAssocMsrCount () const
UINT32 GetAMLStnIndex () const
UINT16 Validity () const
UINT32 * GetAvailMsrCountPtr ()
UINT32 * GetAssocMsrCountPtr ()
UINT32 * GetAMLStnIndexPtr ()
UINT16 * ValidityPtr ()
void DecrementAvailMsrCount ()
void DecrementMsrCount ()
void IncrementMsrCount ()
void IncrementMsrCount (const UINT32 &increment)
void InitAssocMsrCount ()
void SetAvailMsrCount (const UINT32 &availMsrCount)
void SetAssocMsrCount (const UINT32 &assocMsrCount)
void SetAMLStnIndex (const UINT32 &amlStnIndex)
Protected Attributes
UINT32 availMsrCount_
UINT32 assocMsrCount_
UINT32 amlStnIndex_
UINT16 validStation_
Private Member Functions
CAStationList (const CAStationList &)
CAStationList & operator= (const CAStationList &rhs)
Detailed Description
Definition at line 89 of file dnastation.hpp.
Constructor & Destructor Documentation
CAStationList() [1/4]
dynadjust::measurements::CAStationList::CAStationList ()
Definition at line 46 of file dnastation.cpp.
    : availMsrCount_ (0)
    , assocMsrCount_ (0)
    , amlStnIndex_ (0)
    , validStation_(VALID_STATION)
{
}
References amlStnIndex_, assocMsrCount_, availMsrCount_, VALID_STATION, and validStation_.
Referenced by CAStationList(), CAStationList(), handle(), operator=(), and operator=().
CAStationList() [2/4]
dynadjust::measurements::CAStationList::CAStationList (bool validStation)
Definition at line 54 of file dnastation.cpp.
    : availMsrCount_ (0)
    , assocMsrCount_ (0)
    , amlStnIndex_ (0)
    , validStation_(validStation ? VALID_STATION : INVALID_STATION)
{
}
References amlStnIndex_, assocMsrCount_, availMsrCount_, INVALID_STATION, VALID_STATION, and validStation_.
~CAStationList()
dynadjust::measurements::CAStationList::~CAStationList () virtual
Definition at line 62 of file dnastation.cpp.
{
}
CAStationList() [3/4]
dynadjust::measurements::CAStationList::CAStationList (const CAStationList && s)
Definition at line 68 of file dnastation.cpp.
{
    availMsrCount_ = s.availMsrCount_;
    assocMsrCount_ = s.assocMsrCount_;
    amlStnIndex_ = s.amlStnIndex_;
    validStation_ = s.validStation_;
}
References amlStnIndex_, assocMsrCount_, availMsrCount_, CAStationList(), and validStation_.
CAStationList() [4/4]
dynadjust::measurements::CAStationList::CAStationList (const CAStationList &) private
References CAStationList().
Member Function Documentation
operator=() [1/2]
CAStationList & dynadjust::measurements::CAStationList::operator= (CAStationList && rhs)
Definition at line 78 of file dnastation.cpp.
{
    // check for assignment to self!
    if (this == &rhs)
        return *this;
    availMsrCount_ = rhs.availMsrCount_;
    assocMsrCount_ = rhs.assocMsrCount_;
    amlStnIndex_ = rhs.amlStnIndex_;
    validStation_ = rhs.validStation_;
    return *this;
}
References amlStnIndex_, assocMsrCount_, availMsrCount_, CAStationList(), and validStation_.
operator=() [2/2]
CAStationList & dynadjust::measurements::CAStationList::operator= (const CAStationList & rhs) private
References CAStationList().
handle()
CAStationList * dynadjust::measurements::CAStationList::handle () inline
Definition at line 108 of file dnastation.hpp.
{ return this; }
References CAStationList().
SetInvalid()
void dynadjust::measurements::CAStationList::SetInvalid () inline
Definition at line 110 of file dnastation.hpp.
{ validStation_ = FALSE; }
References FALSE, and validStation_.
SetValid()
void dynadjust::measurements::CAStationList::SetValid () inline
Definition at line 111 of file dnastation.hpp.
{ validStation_ = TRUE; }
References TRUE, and validStation_.
Referenced by dynadjust::dynamlinterop::dna_import::CompleteASLDirections(), dynadjust::dynamlinterop::dna_import::CompleteASLGpsBaselines(), dynadjust::dynamlinterop::dna_import::CompleteASLGpsPoints(), and dynadjust::dynamlinterop::dna_import::CompleteAssociationLists().
IsInvalid()
bool dynadjust::measurements::CAStationList::IsInvalid () inline
Definition at line 113 of file dnastation.hpp.
{ return validStation_ == INVALID_STATION; }
References INVALID_STATION, and validStation_.
IsValid()
bool dynadjust::measurements::CAStationList::IsValid () inline
Definition at line 114 of file dnastation.hpp.
{ return validStation_ == VALID_STATION; }
References VALID_STATION, and validStation_.
GetAvailMsrCount()
UINT32 dynadjust::measurements::CAStationList::GetAvailMsrCount () const inline
Definition at line 116 of file dnastation.hpp.
{ return availMsrCount_; }
References availMsrCount_.
GetAssocMsrCount()
UINT32 dynadjust::measurements::CAStationList::GetAssocMsrCount () const inline
Definition at line 117 of file dnastation.hpp.
{ return assocMsrCount_; }
References assocMsrCount_.
Referenced by dynadjust::dynamlinterop::dna_import::CompleteASLDirections(), dynadjust::dynamlinterop::dna_import::CompleteASLGpsBaselines(), dynadjust::dynamlinterop::dna_import::CompleteASLGpsPoints(), and dynadjust::dynamlinterop::dna_import::CompleteAssociationLists().
GetAMLStnIndex()
UINT32 dynadjust::measurements::CAStationList::GetAMLStnIndex () const inline
Definition at line 118 of file dnastation.hpp.
{ return amlStnIndex_; }
References amlStnIndex_.
Referenced by dynadjust::dynamlinterop::dna_import::CompleteASLDirections(), dynadjust::dynamlinterop::dna_import::CompleteASLGpsBaselines(), dynadjust::dynamlinterop::dna_import::CompleteASLGpsPoints(), and dynadjust::dynamlinterop::dna_import::CompleteAssociationLists().
Validity()
UINT16 dynadjust::measurements::CAStationList::Validity () const inline
Definition at line 119 of file dnastation.hpp.
{ return validStation_; }
References validStation_.
GetAvailMsrCountPtr()
UINT32 * dynadjust::measurements::CAStationList::GetAvailMsrCountPtr () inline
Definition at line 120 of file dnastation.hpp.
{ return &availMsrCount_; }
References availMsrCount_.
GetAssocMsrCountPtr()
UINT32 * dynadjust::measurements::CAStationList::GetAssocMsrCountPtr () inline
Definition at line 121 of file dnastation.hpp.
{ return &assocMsrCount_; }
References assocMsrCount_.
Referenced by operator<<(), and operator>>().
GetAMLStnIndexPtr()
UINT32 * dynadjust::measurements::CAStationList::GetAMLStnIndexPtr () inline
Definition at line 122 of file dnastation.hpp.
{ return &amlStnIndex_; }
References amlStnIndex_.
Referenced by operator<<(), and operator>>().
ValidityPtr()
UINT16 * dynadjust::measurements::CAStationList::ValidityPtr () inline
Definition at line 123 of file dnastation.hpp.
{ return &validStation_; }
References validStation_.
Referenced by operator<<(), and operator>>().
DecrementAvailMsrCount()
void dynadjust::measurements::CAStationList::DecrementAvailMsrCount () inline
Definition at line 125 of file dnastation.hpp.
{
        if (availMsrCount_ > 0)
            --availMsrCount_;
    }
References availMsrCount_.
DecrementMsrCount()
void dynadjust::measurements::CAStationList::DecrementMsrCount () inline
Definition at line 129 of file dnastation.hpp.
{
        if (assocMsrCount_ > 0)
            --assocMsrCount_;
        if (availMsrCount_ > 0)
            --availMsrCount_;
    }
References assocMsrCount_, and availMsrCount_.
IncrementMsrCount() [1/2]
void dynadjust::measurements::CAStationList::IncrementMsrCount () inline
Definition at line 136 of file dnastation.hpp.
{ ++assocMsrCount_; }
References assocMsrCount_.
Referenced by dynadjust::dynamlinterop::dna_import::CompleteASLGpsPoints(), and dynadjust::dynamlinterop::dna_import::CompleteAssociationLists().
IncrementMsrCount() [2/2]
void dynadjust::measurements::CAStationList::IncrementMsrCount (const UINT32 & increment) inline
Definition at line 137 of file dnastation.hpp.
{ assocMsrCount_ += increment; }
References assocMsrCount_.
InitAssocMsrCount()
void dynadjust::measurements::CAStationList::InitAssocMsrCount () inline
Definition at line 139 of file dnastation.hpp.
{ assocMsrCount_ = 0; }
References assocMsrCount_.
SetAvailMsrCount()
void dynadjust::measurements::CAStationList::SetAvailMsrCount (const UINT32 & availMsrCount) inline
Definition at line 140 of file dnastation.hpp.
{ availMsrCount_ = availMsrCount; }
References availMsrCount_.
SetAssocMsrCount()
void dynadjust::measurements::CAStationList::SetAssocMsrCount (const UINT32 & assocMsrCount) inline
Definition at line 141 of file dnastation.hpp.
{ assocMsrCount_ = assocMsrCount; }
References assocMsrCount_.
SetAMLStnIndex()
void dynadjust::measurements::CAStationList::SetAMLStnIndex (const UINT32 & amlStnIndex) inline
Definition at line 142 of file dnastation.hpp.
{ amlStnIndex_ = amlStnIndex; }
References amlStnIndex_.
Member Data Documentation
availMsrCount_
UINT32 dynadjust::measurements::CAStationList::availMsrCount_ protected
Definition at line 145 of file dnastation.hpp.
Referenced by CAStationList(), CAStationList(), CAStationList(), DecrementAvailMsrCount(), DecrementMsrCount(), GetAvailMsrCount(), GetAvailMsrCountPtr(), operator=(), and SetAvailMsrCount().
assocMsrCount_
UINT32 dynadjust::measurements::CAStationList::assocMsrCount_ protected
Definition at line 146 of file dnastation.hpp.
Referenced by CAStationList(), CAStationList(), CAStationList(), DecrementMsrCount(), GetAssocMsrCount(), GetAssocMsrCountPtr(), IncrementMsrCount(), IncrementMsrCount(), InitAssocMsrCount(), operator=(), and SetAssocMsrCount().
amlStnIndex_
UINT32 dynadjust::measurements::CAStationList::amlStnIndex_ protected
Definition at line 147 of file dnastation.hpp.
Referenced by CAStationList(), CAStationList(), CAStationList(), GetAMLStnIndex(), GetAMLStnIndexPtr(), operator=(), and SetAMLStnIndex().
validStation_
UINT16 dynadjust::measurements::CAStationList::validStation_ protected
Definition at line 148 of file dnastation.hpp.
Referenced by CAStationList(), CAStationList(), CAStationList(), IsInvalid(), IsValid(), operator=(), SetInvalid(), SetValid(), Validity(), and ValidityPtr().
The documentation for this class was generated from the following files:
include/measurement_types/dnastation.hpp
include/measurement_types/dnastation.cpp