DynAdjust: protected_var< T > Class Template Reference
protected_var< T > Class Template Reference
#include <dnathreading.hpp>
Public Member Functions
protected_var (const protected_var &v)
protected_var ()
virtual ~protected_var ()
void write (const T &var)
T read () const
Private Member Functions
protected_var (const protected_var &pv, const boost::mutex::scoped_lock &lock)
Private Attributes
T var_
boost::mutex var_mutex
Detailed Description
template<typename T>
class protected_var< T >
Definition at line 393 of file dnathreading.hpp.
Constructor & Destructor Documentation
protected_var() [1/3]
template<typename T> protected_var< T >::protected_var (const protected_var< T > & v) inline
Definition at line 396 of file dnathreading.hpp.
        :  protected_var(v, boost::mutex::scoped_lock(v.var_mutex)) {}
References protected_var(), and var_mutex.
Referenced by protected_var(), and protected_var().
protected_var() [2/3]
template<typename T> protected_var< T >::protected_var () inline
Definition at line 399 of file dnathreading.hpp.
{}
~protected_var()
template<typename T> virtual protected_var< T >::~protected_var () inline virtual
Definition at line 400 of file dnathreading.hpp.
{}
protected_var() [3/3]
template<typename T> protected_var< T >::protected_var (const protected_var< T > & pv, const boost::mutex::scoped_lock & lock) inline private
Definition at line 413 of file dnathreading.hpp.
        :  var_(pv.var_) {}
References protected_var(), and var_.
Member Function Documentation
write()
template<typename T> void protected_var< T >::write (const T & var) inline
Definition at line 402 of file dnathreading.hpp.
{
        boost::lock_guard<boost::mutex> lock(var_mutex);
        var_ = var;
    }
References var_, and var_mutex.
read()
template<typename T> T protected_var< T >::read () const inline
Definition at line 407 of file dnathreading.hpp.
{
        boost::lock_guard<boost::mutex> lock(var_mutex);
        return var_;
    }
References var_, and var_mutex.
Member Data Documentation
var_
template<typename T> T protected_var< T >::var_ private
Definition at line 418 of file dnathreading.hpp.
Referenced by protected_var(), read(), and write().
var_mutex
template<typename T> boost::mutex protected_var< T >::var_mutex mutable private
Definition at line 419 of file dnathreading.hpp.
Referenced by protected_var(), read(), and write().
The documentation for this class was generated from the following file:
include/thread/dnathreading.hpp