DynAdjust: dynadjust::measurements::CDnaAngle Class Reference
dynadjust::measurements::CDnaAngle Class Reference
#include <dnaangle.hpp>
Public Member Functions
CDnaAngle (void)
virtual ~CDnaAngle (void)
bool operator== (const CDnaAngle &rhs) const
bool operator< (const CDnaAngle &rhs) const
std::string GetTarget () const
std::string GetTarget2 () const
double GetValue () const
double GetStdDev () const
void SetTarget (const std::string &str)
void SetTarget2 (const std::string &str)
void SetValue (const std::string &str)
void SetStdDev (const std::string &str)
virtual UINT32 CalcBinaryRecordCount () const
virtual void WriteBinaryMsr (std::ofstream *binary_stream, PUINT32 msrIndex) const
virtual UINT32 SetMeasurementRec (const vstn_t &binaryStn, it_vmsr_t &it_msr, it_vdbid_t &dbidmap)
virtual void WriteDynaMLMsr (std::ofstream *dynaml_stream, const std::string &comment, bool) const
virtual void WriteDNAMsr (std::ofstream *dna_stream, const dna_msr_fields &dmw, const dna_msr_fields &dml, bool) const
virtual void SimulateMsr (vdnaStnPtr *vStations, const CDnaEllipsoid *ellipsoid)
Public Member Functions inherited from dynadjust::measurements::CDnaMeasurement
CDnaMeasurement ()
virtual ~CDnaMeasurement ()
CDnaMeasurement (CDnaMeasurement &&m)
CDnaMeasurement & operator= (CDnaMeasurement &&rhs)
std::string GetType () const
char GetTypeC () const
bool GetIgnore () const
bool NotIgnored () const
std::string GetFirst () const
MEASUREMENT_STATIONS GetMsrStnCount () const
std::string GetEpsg () const
std::string GetSource () const
bool GetInsufficient () const
void SetType (const std::string &str)
void SetIgnore (const bool bval)
void SetFirst (const std::string &str)
void SetEpsg (const std::string &e)
void SetSource (const std::string &source)
void SetInsufficient (const bool bval)
void SetMsrIndex (const UINT32 &order)
void SetStn1Index (const UINT32 &order)
void SetStn2Index (const UINT32 &order)
void SetStn3Index (const UINT32 &order)
UINT32 GetMsrIndex () const
UINT32 GetStn1Index () const
UINT32 GetStn2Index () const
UINT32 GetStn3Index () const
double GetMeasAdj () const
double GetMeasCorr () const
double GetMeasAdjPrec () const
double GetResidualPrec () const
double GetPreAdjCorr () const
virtual void PopulateMsr (pvstn_t, uint32_uint32_map *, vUINT32 *, const UINT32 &, const CDnaDatum *, math::matrix_2d *, math::matrix_2d *)
virtual UINT32 GetClusterID () const
virtual std::string GetCoordType () const
virtual float GetInstrHeight () const
virtual double GetVscale () const
virtual double GetPscale () const
virtual double GetLscale () const
virtual double GetHscale () const
virtual float GetTargetHeight () const
virtual UINT32 GetTotal () const
virtual std::string GetReferenceFrame () const
std::string GetEpoch () const
virtual std::vector< CDnaGpsBaseline > * GetBaselines_ptr ()
virtual std::vector< CDnaDirection > * GetDirections_ptr ()
virtual std::vector< CDnaGpsPoint > * GetPoints_ptr ()
virtual std::vector< CDnaCovariance > * GetCovariances_ptr ()
virtual void AddDirection (const CDnaMeasurement *)
virtual void AddGpsBaseline (const CDnaMeasurement *)
virtual void AddGpsPoint (const CDnaMeasurement *)
virtual void AddGpsCovariance (const CDnaCovariance *)
virtual void AddPointCovariance (const CDnaCovariance *)
virtual void ReserveDirectionsCount (const UINT32 &)
virtual void ReserveGpsBaselinesCount (const UINT32 &)
virtual void ReserveGpsPointsCount (const UINT32 &)
virtual void ReserveGpsCovariancesCount (const UINT32 &)
virtual void ResizeGpsCovariancesCount (const UINT32 &)
virtual void SetRecordedTotal (const UINT32 &)
virtual void SetNonIgnoredDirns (const UINT32 &)
virtual void SetClusterID (const UINT32 &)
virtual void SetCoordType (const std::string &)
virtual void SetHscale (const std::string &)
virtual void SetHscale (const double &)
virtual void SetInstrumentHeight (const std::string &)
virtual void SetReferenceFrame (const std::string &)
void SetEpoch (const std::string &epoch)
virtual void SetLscale (const std::string &)
virtual void SetLscale (const double &)
virtual void SetPscale (const std::string &)
virtual void SetPscale (const double &)
virtual void SetSigmaXX (const std::string &)
virtual void SetSigmaXY (const std::string &)
virtual void SetSigmaXZ (const std::string &)
virtual void SetSigmaYY (const std::string &)
virtual void SetSigmaYZ (const std::string &)
virtual void SetSigmaZZ (const std::string &)
virtual void SetTargetHeight (const std::string &)
virtual void SetTotal (const std::string &)
virtual void SetVscale (const std::string &)
virtual void SetVscale (const double &)
virtual void SetX (const std::string &)
virtual void SetY (const std::string &)
virtual void SetZ (const std::string &)
virtual void SetXAxis (const double &)
virtual void SetYAxis (const double &)
virtual void SetZAxis (const double &)
virtual void SetSigmaXX (const double &)
virtual void SetSigmaXY (const double &)
virtual void SetSigmaXZ (const double &)
virtual void SetSigmaYY (const double &)
virtual void SetSigmaYZ (const double &)
virtual void SetSigmaZZ (const double &)
virtual void SetTotal (const UINT32 &)
virtual void PreferGMeasurements ()
void SetMeasurementDBID (const std::string &str)
void SetClusterDBID (const std::string &str)
void SetClusterDBID (const UINT32 &u, bool s)
UINT32 GetClusterDBID ()
bool GetClusterDBIDset ()
void SetDatabaseMap (const msr_database_id_map &dbidmap)
virtual void SetDatabaseMaps (it_vdbid_t &it_dbidmap)
virtual void SerialiseDatabaseMap (std::ofstream *os)
Protected Attributes
std::string m_strTarget
std::string m_strTarget2
double m_drValue
double m_dStdDev
Protected Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strType
bool m_bIgnore
UINT32 m_lmeasurementIndex
UINT32 m_lstn1Index
UINT32 m_lstn2Index
UINT32 m_lstn3Index
double m_measAdj
double m_measCorr
double m_measAdjPrec
double m_residualPrec
double m_preAdjCorr
std::string m_epsgCode
std::string m_sourceFile
std::string m_epoch
msr_database_id_map m_msr_db_map
bool m_bInsufficient
Additional Inherited Members
Public Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strFirst
MEASUREMENT_STATIONS m_MSmeasurementStations
Protected Member Functions inherited from dynadjust::measurements::CDnaMeasurement
void coutMeasurement (std::ostream &os) const
Detailed Description
Definition at line 38 of file dnaangle.hpp.
Constructor & Destructor Documentation
CDnaAngle()
dynadjust::measurements::CDnaAngle::CDnaAngle (void)
Definition at line 28 of file dnaangle.cpp.
    : m_strTarget("")
    , m_strTarget2("")
    , m_drValue(0.)
    , m_dStdDev(0.)
{
    // from abstract class
    m_strType = "A";
    m_MSmeasurementStations = THREE_STATION;
}
References m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, m_strTarget, m_strTarget2, dynadjust::measurements::CDnaMeasurement::m_strType, and THREE_STATION.
Referenced by operator<(), and operator==().
~CDnaAngle()
dynadjust::measurements::CDnaAngle::~CDnaAngle (void) virtual
Definition at line 39 of file dnaangle.cpp.
{
}
Member Function Documentation
operator==()
bool dynadjust::measurements::CDnaAngle::operator== (const CDnaAngle & rhs) const
Definition at line 44 of file dnaangle.cpp.
{
    return (
        m_strFirst == rhs.m_strFirst &&
        m_strType == rhs.m_strType &&
        m_bIgnore == rhs.m_bIgnore &&
        m_strTarget == rhs.m_strTarget &&
        m_strTarget2 == rhs.m_strTarget2 &&
        m_drValue == rhs.m_drValue &&
        m_dStdDev == rhs.m_dStdDev &&
        m_epoch == rhs.m_epoch
        );
}
References CDnaAngle(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, m_strTarget2, and dynadjust::measurements::CDnaMeasurement::m_strType.
operator<()
bool dynadjust::measurements::CDnaAngle::operator< (const CDnaAngle & rhs) const
Definition at line 58 of file dnaangle.cpp.
{
    if (m_strFirst == rhs.m_strFirst) {
        if (m_strTarget == rhs.m_strTarget) {
            if (m_strTarget2 == rhs.m_strTarget2) {
                if (m_bIgnore == rhs.m_bIgnore) {
                    if (m_epoch == rhs.m_epoch) {
                        if (m_drValue == rhs.m_drValue)
                            return m_dStdDev < rhs.m_dStdDev;
                        else
                            return m_drValue < rhs.m_drValue; }
                    else
                        return m_epoch < rhs.m_epoch; }
                else
                    return m_bIgnore < rhs.m_bIgnore; }
            else
                return m_strTarget2 < rhs.m_strTarget2; }
        else
            return m_strTarget < rhs.m_strTarget; }
    else
        return m_strFirst < rhs.m_strFirst;
}
References CDnaAngle(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, and m_strTarget2.
GetTarget()
std::string dynadjust::measurements::CDnaAngle::GetTarget () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 57 of file dnaangle.hpp.
{ return m_strTarget; }
References m_strTarget.
GetTarget2()
std::string dynadjust::measurements::CDnaAngle::GetTarget2 () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 58 of file dnaangle.hpp.
{ return m_strTarget2; }
References m_strTarget2.
GetValue()
double dynadjust::measurements::CDnaAngle::GetValue () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 59 of file dnaangle.hpp.
{ return m_drValue; }
References m_drValue.
GetStdDev()
double dynadjust::measurements::CDnaAngle::GetStdDev () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 60 of file dnaangle.hpp.
{ return m_dStdDev; }
References m_dStdDev.
SetTarget()
void dynadjust::measurements::CDnaAngle::SetTarget (const std::string & str) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 62 of file dnaangle.hpp.
{ m_strTarget = trimstr(str); }
References m_strTarget, and trimstr().
SetTarget2()
void dynadjust::measurements::CDnaAngle::SetTarget2 (const std::string & str) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 63 of file dnaangle.hpp.
{ m_strTarget2 = trimstr(str); }
References m_strTarget2, and trimstr().
SetValue()
void dynadjust::measurements::CDnaAngle::SetValue (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 283 of file dnaangle.cpp.
{
    // convert to radians
    RadFromDmsString(&m_drValue, trimstr(str));
}
References m_drValue, RadFromDmsString(), and trimstr().
SetStdDev()
void dynadjust::measurements::CDnaAngle::SetStdDev (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 289 of file dnaangle.cpp.
{
    // convert seconds to radians
    RadFromSecondsString(&m_dStdDev, trimstr(str));
}
References m_dStdDev, RadFromSecondsString(), and trimstr().
CalcBinaryRecordCount()
virtual UINT32 dynadjust::measurements::CDnaAngle::CalcBinaryRecordCount () const inline virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 68 of file dnaangle.hpp.
{ return 1; }
WriteBinaryMsr()
void dynadjust::measurements::CDnaAngle::WriteBinaryMsr (std::ofstream * binary_stream, PUINT32 msrIndex) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 259 of file dnaangle.cpp.
{
    measurement_t measRecord;
    measRecord.measType = GetTypeC();
    measRecord.measStart = xMeas;
    measRecord.ignore = m_bIgnore;
    measRecord.station1 = m_lstn1Index;
    measRecord.station2 = m_lstn2Index;
    measRecord.station3 = m_lstn3Index;
    measRecord.measAdj = m_measAdj;
    measRecord.measCorr = m_measCorr;
    measRecord.measAdjPrec = m_measAdjPrec;
    measRecord.residualPrec = m_residualPrec;
    measRecord.preAdjCorr = m_preAdjCorr;
    measRecord.term1 = m_drValue;
    measRecord.term2 = m_dStdDev * m_dStdDev;    // convert to variance
    measRecord.measurementStations = m_MSmeasurementStations;
    measRecord.fileOrder = ((*msrIndex)++);
    snprintf(measRecord.epoch, sizeof(measRecord.epoch), "%s", m_epoch.substr(0, STN_EPOCH_WIDTH).c_str());
    binary_stream->write(reinterpret_cast<char *>(&measRecord), sizeof(measurement_t));
}
References dynadjust::measurements::msr_t::epoch, dynadjust::measurements::msr_t::fileOrder, dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::msr_t::ignore, dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_lstn3Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::msr_t::measAdj, dynadjust::measurements::msr_t::measAdjPrec, dynadjust::measurements::msr_t::measCorr, dynadjust::measurements::msr_t::measStart, dynadjust::measurements::msr_t::measType, dynadjust::measurements::msr_t::measurementStations, dynadjust::measurements::msr_t::preAdjCorr, dynadjust::measurements::msr_t::residualPrec, dynadjust::measurements::msr_t::station1, dynadjust::measurements::msr_t::station2, dynadjust::measurements::msr_t::station3, STN_EPOCH_WIDTH(), dynadjust::measurements::msr_t::term1, dynadjust::measurements::msr_t::term2, and xMeas.
SetMeasurementRec()
UINT32 dynadjust::measurements::CDnaAngle::SetMeasurementRec (const vstn_t & binaryStn, it_vmsr_t & it_msr, it_vdbid_t & dbidmap) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 226 of file dnaangle.cpp.
{
    m_strType = it_msr->measType;
    m_bIgnore = it_msr->ignore;
    m_MSmeasurementStations = (MEASUREMENT_STATIONS)it_msr->measurementStations;
    // first station
    m_lstn1Index = it_msr->station1;
    m_strFirst = binaryStn.at(it_msr->station1).stationName;
    // target station
    m_lstn2Index = it_msr->station2;
    m_strTarget = binaryStn.at(it_msr->station2).stationName;
    // target2 station
    m_lstn3Index = it_msr->station3;
    m_strTarget2 = binaryStn.at(it_msr->station3).stationName;
    m_measAdj = it_msr->measAdj;
    m_measCorr = it_msr->measCorr;
    m_measAdjPrec = it_msr->measAdjPrec;
    m_residualPrec = it_msr->residualPrec;
    m_preAdjCorr = it_msr->preAdjCorr;
    m_drValue = it_msr->term1;
    m_dStdDev = sqrt(it_msr->term2);
    m_epoch = it_msr->epoch;
    CDnaMeasurement::SetDatabaseMap(*dbidmap);
    return 0;
}
References dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_lstn3Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, m_strTarget2, dynadjust::measurements::CDnaMeasurement::m_strType, and dynadjust::measurements::CDnaMeasurement::SetDatabaseMap().
WriteDynaMLMsr()
void dynadjust::measurements::CDnaAngle::WriteDynaMLMsr (std::ofstream * dynaml_stream, const std::string & comment, bool) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 82 of file dnaangle.cpp.
{
    if (comment.empty())
        *dynaml_stream << "  <!-- Type " << measurement_name<char, std::string>(GetTypeC()) << " -->" << std::endl;
    else
        *dynaml_stream << "  <!-- " << comment << " -->" << std::endl;
    *dynaml_stream << "  <DnaMeasurement>" << std::endl;
    *dynaml_stream << "    <Type>" << m_strType << "</Type>" << std::endl;
    // Source file from which the measurement came
    *dynaml_stream << "    <Source>" << m_sourceFile << "</Source>" << std::endl;
    if (m_bIgnore)
        *dynaml_stream << "    <Ignore>*</Ignore>" << std::endl;
    else
        *dynaml_stream << "    <Ignore/>" << std::endl;
    if (m_epoch.empty())
        *dynaml_stream << "    <Epoch/>" << std::endl;
    else
        *dynaml_stream << "    <Epoch>" << m_epoch << "</Epoch>" << std::endl;
    *dynaml_stream << "    <First>" << m_strFirst << "</First>" << std::endl;
    *dynaml_stream << "    <Second>" << m_strTarget << "</Second>" << std::endl;
    *dynaml_stream << "    <Third>" << m_strTarget2 << "</Third>" << std::endl;
    *dynaml_stream << "    <Value>" << std::setprecision(8) << std::fixed << RadtoDms(m_drValue) << "</Value>" << std::endl;
    *dynaml_stream << "    <StdDev>" << std::scientific << std::setprecision(6) << Seconds(m_dStdDev) << "</StdDev>" << std::endl;
    if (m_msr_db_map.is_msr_id_set)
        *dynaml_stream << "    <MeasurementID>" << m_msr_db_map.msr_id << "</MeasurementID>" << std::endl;
    *dynaml_stream << "  </DnaMeasurement>" << std::endl;
}
References dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_sourceFile, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, m_strTarget2, dynadjust::measurements::CDnaMeasurement::m_strType, dynadjust::measurements::measurement_name(), RadtoDms(), and Seconds().
WriteDNAMsr()
void dynadjust::measurements::CDnaAngle::WriteDNAMsr (std::ofstream * dna_stream, const dna_msr_fields & dmw, const dna_msr_fields & dml, bool) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 116 of file dnaangle.cpp.
{
    *dna_stream << std::setw(dmw.msr_type) << m_strType;
    if (m_bIgnore)
        *dna_stream << std::setw(dmw.msr_ignore) << "*";
    else
        *dna_stream << std::setw(dmw.msr_ignore) << " ";
    *dna_stream << std::left << std::setw(dmw.msr_inst) << m_strFirst;
    *dna_stream << std::left << std::setw(dmw.msr_targ1) << m_strTarget;
    *dna_stream << std::left << std::setw(dmw.msr_targ2) << m_strTarget2;
    *dna_stream << std::setw(dmw.msr_linear) << " ";  // linear measurement value
    *dna_stream << std::setw(dmw.msr_ang_d + dmw.msr_ang_m + dmw.msr_ang_s) <<
        std::right << FormatDnaDmsString(RadtoDms(m_drValue), 8);
    UINT32 m_stdDevPrec(3);
    *dna_stream << std::setw(dmw.msr_stddev) << StringFromTW(Seconds(m_dStdDev), dmw.msr_stddev, m_stdDevPrec);
    //*dna_stream << std::setw(dmw.msr_stddev) << std::fixed << std::setprecision(3) << Seconds(m_dStdDev);
    *dna_stream << std::setw(dml.msr_gps_epoch - dml.msr_inst_ht) << " ";
    *dna_stream << std::setw(dmw.msr_gps_epoch) << m_epoch;
    if (m_msr_db_map.is_msr_id_set)
        *dna_stream << std::setw(dmw.msr_id_msr) << m_msr_db_map.msr_id;
    *dna_stream << std::endl;
}
References FormatDnaDmsString(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, m_strTarget2, dynadjust::measurements::CDnaMeasurement::m_strType, dna_msr_fields::msr_ang_d, dna_msr_fields::msr_ang_m, dna_msr_fields::msr_ang_s, dna_msr_fields::msr_gps_epoch, dna_msr_fields::msr_id_msr, dna_msr_fields::msr_ignore, dna_msr_fields::msr_inst, dna_msr_fields::msr_inst_ht, dna_msr_fields::msr_linear, dna_msr_fields::msr_stddev, dna_msr_fields::msr_targ1, dna_msr_fields::msr_targ2, dna_msr_fields::msr_type, RadtoDms(), Seconds(), and StringFromTW().
SimulateMsr()
void dynadjust::measurements::CDnaAngle::SimulateMsr (vdnaStnPtr * vStations, const CDnaEllipsoid * ellipsoid) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 144 of file dnaangle.cpp.
{
    _it_vdnastnptr stn1_it(vStations->begin() + m_lstn1Index);
    _it_vdnastnptr stn2_it(vStations->begin() + m_lstn2Index);
    _it_vdnastnptr stn3_it(vStations->begin() + m_lstn3Index);
    double direction12, direction13;
    // calculated angle
    m_drValue = HorizontalAngle(
        stn1_it->get()->GetXAxis(),
        stn1_it->get()->GetYAxis(),
        stn1_it->get()->GetZAxis(),
        stn2_it->get()->GetXAxis(),
        stn2_it->get()->GetYAxis(),
        stn2_it->get()->GetZAxis(),
        stn3_it->get()->GetXAxis(),
        stn3_it->get()->GetYAxis(),
        stn3_it->get()->GetZAxis(),
        stn1_it->get()->GetcurrentLatitude(),
        stn1_it->get()->GetcurrentLongitude(),
        &direction12, &direction13);
    // Deflections available?
    if (fabs(stn1_it->get()->GetverticalDef()) > E4_SEC_DEFLECTION || fabs(stn1_it->get()->GetmeridianDef()) > E4_SEC_DEFLECTION)
    {
        // Angles (observed or derived from directions) must be corrected for deflection
        // of the vertical via "Laplace correction".  This correction requires zenith
        // distance (zenith12, zenith13) and geodetic azimuth (direction12, direction13),
        // both of which must be computed from coordinates.
        // 1. Compute zenith distance 1 -> 2
        double zenith12(ZenithDistance<double>(
            stn1_it->get()->GetXAxis(),
            stn1_it->get()->GetYAxis(),
            stn1_it->get()->GetZAxis(),
            stn2_it->get()->GetXAxis(),
            stn2_it->get()->GetYAxis(),
            stn2_it->get()->GetZAxis(),
            stn1_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentLongitude(),
            stn2_it->get()->GetcurrentLatitude(),
            stn2_it->get()->GetcurrentLongitude(),
            0.0,                                    // instrument height
            0.0));                                  // target height
        // 2. Compute zenith distance 1 -> 3
        double zenith13(ZenithDistance<double>(
            stn1_it->get()->GetXAxis(),
            stn1_it->get()->GetYAxis(),
            stn1_it->get()->GetZAxis(),
            stn3_it->get()->GetXAxis(),
            stn3_it->get()->GetYAxis(),
            stn3_it->get()->GetZAxis(),
            stn1_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentLongitude(),
            stn3_it->get()->GetcurrentLatitude(),
            stn3_it->get()->GetcurrentLongitude(),
            0.0,                                    // instrument height
            0.0));                                  // target height
        // 3. Laplace correction 1 -> 2 -> 3
        m_preAdjCorr = HzAngleDeflectionCorrection<double>(
            direction12,                            // geodetic azimuth 1 -> 2
            zenith12,                               // zenith distance 1 -> 2
            direction13,                            // geodetic azimuth 1 -> 3
            zenith13,                               // zenith distance 1 -> 3
            stn1_it->get()->GetverticalDef(),       // deflection in prime vertical
            stn1_it->get()->GetmeridianDef());      // deflection in prime meridian
        // 4. apply deflection correction
        m_drValue += m_preAdjCorr;
    }
    // compute standard deviation in radians
    m_dStdDev = SecondstoRadians(0.01);
    m_epoch = "01.10.1985";
}
References E4_SEC_DEFLECTION(), HorizontalAngle(), HzAngleDeflectionCorrection(), m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_lstn3Index, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, SecondstoRadians(), and ZenithDistance().
Member Data Documentation
m_strTarget
std::string dynadjust::measurements::CDnaAngle::m_strTarget protected
Definition at line 76 of file dnaangle.hpp.
Referenced by CDnaAngle(), GetTarget(), operator<(), operator==(), SetMeasurementRec(), SetTarget(), WriteDNAMsr(), and WriteDynaMLMsr().
m_strTarget2
std::string dynadjust::measurements::CDnaAngle::m_strTarget2 protected
Definition at line 77 of file dnaangle.hpp.
Referenced by CDnaAngle(), GetTarget2(), operator<(), operator==(), SetMeasurementRec(), SetTarget2(), WriteDNAMsr(), and WriteDynaMLMsr().
m_drValue
double dynadjust::measurements::CDnaAngle::m_drValue protected
Definition at line 78 of file dnaangle.hpp.
Referenced by CDnaAngle(), GetValue(), operator<(), operator==(), SetMeasurementRec(), SetValue(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_dStdDev
double dynadjust::measurements::CDnaAngle::m_dStdDev protected
Definition at line 79 of file dnaangle.hpp.
Referenced by CDnaAngle(), GetStdDev(), operator<(), operator==(), SetMeasurementRec(), SetStdDev(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
The documentation for this class was generated from the following files:
include/measurement_types/dnaangle.hpp
include/measurement_types/dnaangle.cpp