DynAdjust: DnaStation_pimpl Class Reference
DnaStation_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void Name (const ::std::string &)
virtual void Constraints (const ::std::string &)
virtual void Type (const ::std::string &)
virtual void StationCoord ()
virtual void Description (const ::std::string &)
virtual void post_DnaStation ()
Public Member Functions inherited from DnaStation_pskel
void InitfileEpsg (std::string &fileEpsg)
void InitfileEpoch (std::string &fileEpoch)
void InitparentStnVector (vdnaStnPtr *pStns)
void SetDefaultReferenceFrame (std::string &referenceframe, bool overridereferenceframe)
void SetDefaultEpoch (std::string &epoch)
std::string Name ()
std::string Constraints ()
std::string Type ()
std::string Description ()
StationCoord_pskel & Coordinates ()
void Name_parser (::xml_schema::string_pskel &)
void Constraints_parser (::xml_schema::string_pskel &)
void Type_parser (::xml_schema::string_pskel &)
void StationCoord_parser (::StationCoord_pskel &)
void Description_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::StationCoord_pskel &, ::xml_schema::string_pskel &)
DnaStation_pskel ()
Additional Inherited Members
Protected Member Functions inherited from DnaStation_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes inherited from DnaStation_pskel
::xml_schema::string_pskel * Name_parser_
::xml_schema::string_pskel * Constraints_parser_
::xml_schema::string_pskel * Type_parser_
::StationCoord_pskel * StationCoord_parser_
::xml_schema::string_pskel * Description_parser_
vdnaStnPtr * _vParentStns
dnaStnPtr _dnaCurrentStn
std::string _fileEpoch
std::string _fileEpsg
std::string _epoch
std::string _referenceframe
bool _overridereferenceframe
Detailed Description
Definition at line 107 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void DnaStation_pimpl::pre () virtual
Definition at line 870 of file dnaparser_pimpl.cxx.
{
    std::string frame, epoch;
    if (_overridereferenceframe)
        frame = _referenceframe;
    else
        frame = datumFromEpsgString(_fileEpsg);
    if (_overridereferenceframe)
        epoch = _epoch;
    else
        epoch = _fileEpoch;
    _dnaCurrentStn.reset(new CDnaStation(frame, epoch));
    _dnaCurrentStn->SetfileOrder(g_fileOrder++);
}
References DnaStation_pskel::_dnaCurrentStn, DnaStation_pskel::_epoch, DnaStation_pskel::_fileEpoch, DnaStation_pskel::_fileEpsg, DnaStation_pskel::_overridereferenceframe, DnaStation_pskel::_referenceframe, dynadjust::epsg::datumFromEpsgString(), and g_fileOrder.
Name()
void DnaStation_pimpl::Name (const ::std::string & Name) virtual
Reimplemented from DnaStation_pskel.
Definition at line 888 of file dnaparser_pimpl.cxx.
{
    if (Name.empty())
        throw XMLInteropException("DnaStation \"Name\" element cannot be empty.", 0);
    _dnaCurrentStn->SetName(Name);
}
References DnaStation_pskel::_dnaCurrentStn, and Name().
Referenced by Name().
Constraints()
void DnaStation_pimpl::Constraints (const ::std::string & Constraints) virtual
Reimplemented from DnaStation_pskel.
Definition at line 896 of file dnaparser_pimpl.cxx.
{
    if (Constraints.empty())
        _dnaCurrentStn->SetConstraints("FFF");
    else
        _dnaCurrentStn->SetConstraints(Constraints);
    g_parsestn_tally.addstation(Constraints);
}
References DnaStation_pskel::_dnaCurrentStn, Constraints(), and g_parsestn_tally.
Referenced by Constraints().
Type()
void DnaStation_pimpl::Type (const ::std::string & Type) virtual
Reimplemented from DnaStation_pskel.
Definition at line 906 of file dnaparser_pimpl.cxx.
{
    _dnaCurrentStn->SetCoordType(Type);
}
References DnaStation_pskel::_dnaCurrentStn, and Type().
Referenced by Type().
StationCoord()
void DnaStation_pimpl::StationCoord () virtual
Reimplemented from DnaStation_pskel.
Definition at line 911 of file dnaparser_pimpl.cxx.
{
}
Description()
void DnaStation_pimpl::Description (const ::std::string & Description) virtual
Reimplemented from DnaStation_pskel.
Definition at line 915 of file dnaparser_pimpl.cxx.
{
    _dnaCurrentStn->SetDescription(
        findandreplace((const ::std::string&)Description, (const ::std::string&)"&", (const ::std::string&)"and"));
}
References DnaStation_pskel::_dnaCurrentStn, Description(), and findandreplace().
Referenced by Description().
post_DnaStation()
void DnaStation_pimpl::post_DnaStation () virtual
Reimplemented from DnaStation_pskel.
Definition at line 921 of file dnaparser_pimpl.cxx.
{
    _vParentStns->push_back(_dnaCurrentStn);
}
References DnaStation_pskel::_dnaCurrentStn, and DnaStation_pskel::_vParentStns.
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx