DynAdjust: dynadjust::exception::XMLInteropException Class Reference
dynadjust::exception::XMLInteropException Class Reference
#include <dnaexception.hpp>
Public Member Functions
XMLInteropException (const std::string &what, const UINT32 &line_no)
virtual const char * what () const throw ()
virtual ~XMLInteropException () throw ()
Private Attributes
std::string what_
UINT32 line_no_
Detailed Description
Definition at line 83 of file dnaexception.hpp.
Constructor & Destructor Documentation
XMLInteropException()
dynadjust::exception::XMLInteropException::XMLInteropException (const std::string & what, const UINT32 & line_no) inline explicit
Definition at line 86 of file dnaexception.hpp.
        : what_(what), line_no_(line_no) {}
References line_no_, what(), and what_.
~XMLInteropException()
virtual dynadjust::exception::XMLInteropException::~XMLInteropException () throw () inline virtual
Definition at line 89 of file dnaexception.hpp.
{}
Member Function Documentation
what()
virtual const char * dynadjust::exception::XMLInteropException::what () const throw () inline virtual
Definition at line 88 of file dnaexception.hpp.
{ return what_.c_str(); }
References what_.
Referenced by ImportContiguousNetwork(), ImportDataFiles(), ImportSegmentedBlock(), main(), dna_import_thread::operator()(), SearchForSimilarMeasurements(), dynadjust::dynamlinterop::dna_import::SerialiseDynaMLSepfromMemory(), and XMLInteropException().
Member Data Documentation
what_
std::string dynadjust::exception::XMLInteropException::what_ private
Definition at line 92 of file dnaexception.hpp.
Referenced by what(), and XMLInteropException().
line_no_
UINT32 dynadjust::exception::XMLInteropException::line_no_ private
Definition at line 93 of file dnaexception.hpp.
Referenced by XMLInteropException().
The documentation for this class was generated from the following file:
include/exception/dnaexception.hpp