DynAdjust: DnaMeasurement_pimpl Class Reference
DnaMeasurement_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void Type (const ::std::string &)
virtual void Ignore (const ::std::string &)
virtual void First (const ::std::string &)
virtual void Second (const ::std::string &)
virtual void Third (const ::std::string &)
virtual void Value (const ::std::string &)
virtual void StdDev (const ::std::string &)
virtual void InstHeight (const ::std::string &)
virtual void TargHeight (const ::std::string &)
virtual void Total (const ::std::string &)
virtual void Directions ()
virtual void Vscale (const ::std::string &)
virtual void Epoch (const ::std::string &)
virtual void ReferenceFrame (const ::std::string &)
virtual void GPSBaseline ()
virtual void Hscale (const ::std::string &)
virtual void Lscale (const ::std::string &)
virtual void Pscale (const ::std::string &)
virtual void Clusterpoint ()
virtual void Coords (const ::std::string &)
virtual void Source (const ::std::string &)
virtual void MeasurementDBID (const ::std::string &)
virtual void ClusterDBID (const ::std::string &)
virtual void post_DnaMeasurement ()
Public Member Functions inherited from DnaMeasurement_pskel
void InitfileEpsg (std::string &fileEpsg)
void InitfileEpoch (std::string &fileEpoch)
void SetDefaultReferenceFrame (std::string &referenceframe, bool overridereferenceframe)
void SetDefaultEpoch (std::string &epoch)
void InitparentMsrVector (vdnaMsrPtr *pMsrs)
void InitparentMsrCounter (PUINT32 pMsrCounter)
void InitparentClusterID (PUINT32 pclusterID)
std::string Type ()
std::string First ()
std::string Second ()
std::string Third ()
vdnaMsrPtr & MeasurementList ()
std::string Source ()
std::string MeasurementDBID ()
std::string ClusterDBID ()
void Type_parser (::xml_schema::string_pskel &)
void Ignore_parser (::xml_schema::string_pskel &)
void First_parser (::xml_schema::string_pskel &)
void Second_parser (::xml_schema::string_pskel &)
void Third_parser (::xml_schema::string_pskel &)
void Value_parser (::xml_schema::string_pskel &)
void StdDev_parser (::xml_schema::string_pskel &)
void InstHeight_parser (::xml_schema::string_pskel &)
void TargHeight_parser (::xml_schema::string_pskel &)
void Total_parser (::xml_schema::string_pskel &)
void Directions_parser (::Directions_pskel &)
void Vscale_parser (::xml_schema::string_pskel &)
void Epoch_parser (::xml_schema::string_pskel &)
void ReferenceFrame_parser (::xml_schema::string_pskel &)
void GPSBaseline_parser (::GPSBaseline_pskel &)
void Hscale_parser (::xml_schema::string_pskel &)
void Lscale_parser (::xml_schema::string_pskel &)
void Pscale_parser (::xml_schema::string_pskel &)
void Clusterpoint_parser (::Clusterpoint_pskel &)
void Coords_parser (::xml_schema::string_pskel &)
void Source_parser (::xml_schema::string_pskel &)
void MeasurementDBID_parser (::xml_schema::string_pskel &)
void ClusterDBID_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::Directions_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::GPSBaseline_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::Clusterpoint_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, bool preferSingleXasG=false)
DnaMeasurement_pskel ()
Additional Inherited Members
Protected Member Functions inherited from DnaMeasurement_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
virtual bool _attribute_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes inherited from DnaMeasurement_pskel
::xml_schema::string_pskel * Type_parser_
::xml_schema::string_pskel * Ignore_parser_
::xml_schema::string_pskel * First_parser_
::xml_schema::string_pskel * Second_parser_
::xml_schema::string_pskel * Third_parser_
::xml_schema::string_pskel * Value_parser_
::xml_schema::string_pskel * StdDev_parser_
::xml_schema::string_pskel * InstHeight_parser_
::xml_schema::string_pskel * TargHeight_parser_
::xml_schema::string_pskel * Total_parser_
::Directions_pskel * Directions_parser_
::xml_schema::string_pskel * Vscale_parser_
::xml_schema::string_pskel * Epoch_parser_
::xml_schema::string_pskel * ReferenceFrame_parser_
::GPSBaseline_pskel * GPSBaseline_parser_
::xml_schema::string_pskel * Hscale_parser_
::xml_schema::string_pskel * Lscale_parser_
::xml_schema::string_pskel * Pscale_parser_
::Clusterpoint_pskel * Clusterpoint_parser_
::xml_schema::string_pskel * Coords_parser_
::xml_schema::string_pskel * Source_parser_
::xml_schema::string_pskel * MeasurementDBID_parser_
::xml_schema::string_pskel * ClusterDBID_parser_
vdnaMsrPtr * _vParentMsrs
dnaMsrPtr _dnaCurrentMsr
PUINT32 _pMeasurementCount
PUINT32 _pclusterID
std::string _fileEpoch
std::string _fileEpsg
std::string _epoch
std::string _referenceframe
bool _EpochTagSupplied
bool _ReferenceframeTagSupplied
bool _overridereferenceframe
bool _preferSingleXasG
UINT32 _total
Detailed Description
Definition at line 77 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void DnaMeasurement_pimpl::pre () virtual
Definition at line 209 of file dnaparser_pimpl.cxx.
{
    _dnaCurrentMsr.reset();
    // Initialise flags that will track whether Reference frame has been supplied
    _ReferenceframeTagSupplied = false;
    _EpochTagSupplied = false;
}
References DnaMeasurement_pskel::_dnaCurrentMsr, DnaMeasurement_pskel::_EpochTagSupplied, and DnaMeasurement_pskel::_ReferenceframeTagSupplied.
Type()
void DnaMeasurement_pimpl::Type (const ::std::string & Type) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 219 of file dnaparser_pimpl.cxx.
{
    if (Type.empty())
        throw XMLInteropException("\"Type\" element cannot be empty.", 0);
    std::string frame, epoch;
    if (_ReferenceframeTagSupplied || _overridereferenceframe)
        frame = _referenceframe;
    else
        frame = datumFromEpsgString(_fileEpsg);
    if (_EpochTagSupplied || _overridereferenceframe)
        epoch = _epoch;
    else
        epoch = _fileEpoch;
    char cType = (Type.c_str())[0];
    switch (cType) {
    case 'A': // Horizontal angle
        g_parsemsr_tally.A++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaAngle);
        break;
    case 'B': // Geodetic azimuth
        g_parsemsr_tally.B++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaAzimuth);
        break;
    case 'C': // Chord dist
        g_parsemsr_tally.C++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaDistance);
        break;
    case 'D': // Direction set
        g_parsemsr_tally.D++;
        _dnaCurrentMsr.reset(new CDnaDirectionSet(++(*(_pclusterID))));
        break;
    case 'E': // Ellipsoid arc
        g_parsemsr_tally.E++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaDistance);
        break;
    case 'G': // GPS Baseline (treat as single-baseline cluster)
    case 'X': // GPS Baseline cluster
        _dnaCurrentMsr.reset(new CDnaGpsBaselineCluster(++(*(_pclusterID)), frame, epoch));
        break;
    case 'H': // Orthometric height
        g_parsemsr_tally.H++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaHeight);
        break;
    case 'I': // Astronomic latitude
        g_parsemsr_tally.I++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaCoordinate);
        break;
    case 'J': // Astronomic longitude
        g_parsemsr_tally.J++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaCoordinate);
        break;
    case 'K': // Astronomic azimuth
        g_parsemsr_tally.K++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaAzimuth);
        break;
    case 'L': // Level difference
        g_parsemsr_tally.L++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaHeightDifference);
        break;
    case 'M': // MSL arc
        g_parsemsr_tally.M++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaDistance);
        break;
    case 'P': // Geodetic latitude
        g_parsemsr_tally.P++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaCoordinate);
        break;
    case 'Q': // Geodetic longitude
        g_parsemsr_tally.Q++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaCoordinate);
        break;
    case 'R': // Ellipsoidal height
        g_parsemsr_tally.R++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaHeight);
        break;
    case 'S': // Slope distance
        g_parsemsr_tally.S++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaDistance);
        break;
    case 'V': // Zenith distance
        g_parsemsr_tally.V++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaDirection);
        break;
    case 'Y': // GPS point cluster
        _dnaCurrentMsr.reset(new CDnaGpsPointCluster(++(*(_pclusterID)), _referenceframe, _epoch));
        break;
    case 'Z': // Vertical angle
        g_parsemsr_tally.Z++;
        *(_pMeasurementCount) += 1;
        _dnaCurrentMsr.reset(new CDnaDirection);
        break;
    default:
        std::stringstream ss;
        ss << "Unknown measurement type: " << Type;
        throw XMLInteropException(ss.str(), 0);
    }
    _dnaCurrentMsr->SetType(Type);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, DnaMeasurement_pskel::_epoch, DnaMeasurement_pskel::_EpochTagSupplied, DnaMeasurement_pskel::_fileEpoch, DnaMeasurement_pskel::_fileEpsg, DnaMeasurement_pskel::_overridereferenceframe, DnaMeasurement_pskel::_pclusterID, DnaMeasurement_pskel::_pMeasurementCount, DnaMeasurement_pskel::_referenceframe, DnaMeasurement_pskel::_ReferenceframeTagSupplied, dynadjust::epsg::datumFromEpsgString(), g_parsemsr_tally, and Type().
Referenced by Type().
Ignore()
void DnaMeasurement_pimpl::Ignore (const ::std::string & Ignore) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 337 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (Ignore.empty())
        _dnaCurrentMsr->SetIgnore(false);
    else
    {
        _dnaCurrentMsr->SetIgnore(true);
        g_parsemsr_tally.ignored++;
    }
}
References DnaMeasurement_pskel::_dnaCurrentMsr, g_parsemsr_tally, and Ignore().
Referenced by Ignore().
First()
void DnaMeasurement_pimpl::First (const ::std::string & First) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 351 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (First.empty())
        throw XMLInteropException("\"First\" element cannot be empty.", 0);
    _dnaCurrentMsr->SetFirst(First);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and First().
Referenced by First().
Second()
void DnaMeasurement_pimpl::Second (const ::std::string & Second) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 361 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    switch (_dnaCurrentMsr->GetTypeC()) {
    case 'A': // Horizontal angle
    case 'B': // Geodetic azimuth
    case 'K': // Astronomic azimuth
    case 'C': // Chord dist
    case 'E': // Ellipsoid arc
    case 'M': // MSL arc
    case 'S': // Slope distance
    case 'D': // Direction set
    case 'G': // GPS Baseline
    case 'L': // Level difference
    case 'V': // Zenith distance
    case 'Z': // Vertical angle
    case 'X': // GPS Baseline cluster
        if (Second.empty())
        {
            std::stringstream ss;
            ss << "\"Second\" element cannot be empty for measurement type " << _dnaCurrentMsr->GetTypeC() <<
                " (first station: " << _dnaCurrentMsr->GetFirst() << ").";
            throw XMLInteropException(ss.str(), 0);
        }
        _dnaCurrentMsr->SetTarget(Second);
    }
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Second().
Referenced by Second().
Third()
void DnaMeasurement_pimpl::Third (const ::std::string & Third) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 391 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    switch (_dnaCurrentMsr->GetTypeC()) {
    case 'A': // Horizontal angle
        if (Third.empty())
        {
            std::stringstream ss;
            ss << "\"Third\" element cannot be empty for measurement type " << _dnaCurrentMsr->GetTypeC() <<
                " (first station: " << _dnaCurrentMsr->GetFirst() << ").";
            throw XMLInteropException(ss.str(), 0);
        }
    }
    _dnaCurrentMsr->SetTarget2(Third);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Third().
Referenced by Third().
Value()
void DnaMeasurement_pimpl::Value (const ::std::string & Value) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 410 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    switch (_dnaCurrentMsr->GetTypeC()) {
    case 'A': // Horizontal angle
    case 'B': // Geodetic azimuth
    case 'K': // Astronomic azimuth
    case 'C': // Chord dist
    case 'E': // Ellipsoid arc
    case 'M': // MSL arc
    case 'S': // Slope distance
    case 'D': // Direction set
    case 'H': // Orthometric height
    case 'R': // Ellipsoidal height
    case 'I': // Astronomic latitude
    case 'J': // Astronomic longitude
    case 'P': // Geodetic latitude
    case 'Q': // Geodetic longitude
    case 'L': // Level difference
    case 'V': // Zenith distance
    case 'Z': // Vertical angle
        if (Value.empty())
        {
            std::stringstream ss;
            ss << "\"Value\" element cannot be empty for measurement type " << _dnaCurrentMsr->GetTypeC() <<
                " (first station: " << _dnaCurrentMsr->GetFirst() << ").";
            throw XMLInteropException(ss.str(), 0);
        }
    }
    _dnaCurrentMsr->SetValue(Value);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Value().
Referenced by Value().
StdDev()
void DnaMeasurement_pimpl::StdDev (const ::std::string & StdDev) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 445 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    switch (_dnaCurrentMsr->GetTypeC()) {
    case 'A': // Horizontal angle
    case 'B': // Geodetic azimuth
    case 'K': // Astronomic azimuth
    case 'C': // Chord dist
    case 'E': // Ellipsoid arc
    case 'M': // MSL arc
    case 'S': // Slope distance
    case 'D': // Direction set
    case 'H': // Orthometric height
    case 'R': // Ellipsoidal height
    case 'I': // Astronomic latitude
    case 'J': // Astronomic longitude
    case 'P': // Geodetic latitude
    case 'Q': // Geodetic longitude
    case 'L': // Level difference
    case 'V': // Zenith distance
    case 'Z': // Vertical angle
        if (StdDev.empty())
        {
            std::stringstream ss;
            ss << "\"StdDev\" element cannot be empty for " << _dnaCurrentMsr->GetTypeC() << " measurements (first station: " << _dnaCurrentMsr->GetFirst() << ").";
            throw XMLInteropException(ss.str(), 0);
        }
        if (DoubleFromString<double>(StdDev) < PRECISION_1E25)
        {
            std::stringstream ss;
            ss << "\"StdDev\" element cannot contain a zero or negative value for " << _dnaCurrentMsr->GetTypeC() << " measurements (first station: " << _dnaCurrentMsr->GetFirst() << ").";
            throw XMLInteropException(ss.str(), 0);
        }
    }
    _dnaCurrentMsr->SetStdDev(StdDev);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, DoubleFromString(), PRECISION_1E25(), and StdDev().
Referenced by StdDev().
InstHeight()
void DnaMeasurement_pimpl::InstHeight (const ::std::string & InstHeight) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 487 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    // Instrument and target heights only make sense for
    // slope distances, vertical angles and zenith distances.
    // Don't need instrument height for all other types.
    switch (_dnaCurrentMsr->GetTypeC()) {
    case 'S':
    case 'V':
    case 'Z':
        _dnaCurrentMsr->SetInstrumentHeight(InstHeight);
        break;
    }
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and InstHeight().
Referenced by InstHeight().
TargHeight()
void DnaMeasurement_pimpl::TargHeight (const ::std::string & TargHeight) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 504 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    // Instrument and target heights only make sense for
    // slope distances, vertical angles and zenith distances.
    // Don't need instrument height for all other types.
    switch (_dnaCurrentMsr->GetTypeC()) {
    case 'S':
    case 'V':
    case 'Z':
        _dnaCurrentMsr->SetTargetHeight(TargHeight);
        break;
    }
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and TargHeight().
Referenced by TargHeight().
Total()
void DnaMeasurement_pimpl::Total (const ::std::string & Total) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 521 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    switch (_dnaCurrentMsr->GetTypeC()) {
    case 'D': // Direction set
    case 'G': // Single Baseline (treat as a single-baseline cluster)
    case 'X': // GPS Baseline cluster
    case 'Y': // GPS point cluster
        if (Total.empty())
            throw XMLInteropException("\"Total\" element cannot be empty.", 0);
    }
    _dnaCurrentMsr->SetTotal(Total);
    const UINT32 measCount(LongFromString<UINT32>(Total));
    _total = measCount;
    switch (_dnaCurrentMsr->GetTypeC())
    {
    case 'X': // GPS Baseline cluster
        if (measCount < 2)
            if (_preferSingleXasG)
                _dnaCurrentMsr->SetType("G");
    }
}
References DnaMeasurement_pskel::_dnaCurrentMsr, DnaMeasurement_pskel::_preferSingleXasG, DnaMeasurement_pskel::_total, LongFromString(), and Total().
Referenced by Total().
Directions()
void DnaMeasurement_pimpl::Directions () virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 549 of file dnaparser_pimpl.cxx.
{
}
Vscale()
void DnaMeasurement_pimpl::Vscale (const ::std::string & Vscale) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 553 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (Vscale.empty())
        _dnaCurrentMsr->SetVscale("1");
    else
        _dnaCurrentMsr->SetVscale(Vscale);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Vscale().
Referenced by Vscale().
Epoch()
void DnaMeasurement_pimpl::Epoch (const ::std::string & Epoch) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 564 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    try
    {
        // Override the reference frame with the user specified frame?
        if (_overridereferenceframe)
        {
            _dnaCurrentMsr->SetEpoch(_epoch);
            return;
        }
        if (Epoch.empty())
            // Do nothing - use default epoch
            return;
        _dnaCurrentMsr->SetEpoch(Epoch);
        _EpochTagSupplied = true;
    }
    catch (const std::runtime_error& e) {
        std::stringstream ss("");
        ss << e.what();
        ss << "    - Measurement type: " << _dnaCurrentMsr->GetType() << std::endl <<
            "    - From:             " << _dnaCurrentMsr->GetFirst() << std::endl <<
            "    - To:               " << _dnaCurrentMsr->GetTarget() << std::endl <<
            "    - Reference frame:  " << _dnaCurrentMsr->GetReferenceFrame() << std::endl <<
            "    - Epoch:            " << Epoch << std::endl;
        throw XMLInteropException(ss.str(), 0);
    }
}
References DnaMeasurement_pskel::_dnaCurrentMsr, DnaMeasurement_pskel::_epoch, DnaMeasurement_pskel::_EpochTagSupplied, DnaMeasurement_pskel::_overridereferenceframe, and Epoch().
Referenced by Epoch().
ReferenceFrame()
void DnaMeasurement_pimpl::ReferenceFrame (const ::std::string & ReferenceFrame) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 597 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    try
    {
        // Set the reference frame found for this measurement
        _dnaCurrentMsr->SetReferenceFrame(ReferenceFrame);
        // Override the reference frame with the user specified frame?
        if (_overridereferenceframe)
        {
            _dnaCurrentMsr->SetReferenceFrame(_referenceframe);
            return;
        }
        // Was no frame supplied?  If so, do nothing (use default reference frame)
        if (ReferenceFrame.empty())
            return;
        // Set the reference frame found for this measurement
        _dnaCurrentMsr->SetReferenceFrame(ReferenceFrame);
        _ReferenceframeTagSupplied = true;
    }
    catch (const std::runtime_error& e) {
        std::stringstream ss("");
        ss << e.what();
        ss << "    - Measurement type: " << _dnaCurrentMsr->GetType() << std::endl <<
            "    - From:             " << _dnaCurrentMsr->GetFirst() << std::endl <<
            "    - To:               " << _dnaCurrentMsr->GetTarget() << std::endl <<
            "    - Reference frame:  " << ReferenceFrame << std::endl <<
            "    - Epoch:            " << _dnaCurrentMsr->GetEpoch() << std::endl;
        throw XMLInteropException(ss.str(), 0);
    }
}
References DnaMeasurement_pskel::_dnaCurrentMsr, DnaMeasurement_pskel::_overridereferenceframe, DnaMeasurement_pskel::_referenceframe, DnaMeasurement_pskel::_ReferenceframeTagSupplied, and ReferenceFrame().
Referenced by ReferenceFrame().
GPSBaseline()
void DnaMeasurement_pimpl::GPSBaseline () virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 634 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
}
References DnaMeasurement_pskel::_dnaCurrentMsr.
Hscale()
void DnaMeasurement_pimpl::Hscale (const ::std::string & Hscale) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 641 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (Hscale.empty())
        _dnaCurrentMsr->SetHscale("1");
    else
        _dnaCurrentMsr->SetHscale(Hscale);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Hscale().
Referenced by Hscale().
Lscale()
void DnaMeasurement_pimpl::Lscale (const ::std::string & Lscale) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 653 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (Lscale.empty())
        _dnaCurrentMsr->SetLscale("1");
    else
        _dnaCurrentMsr->SetLscale(Lscale);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Lscale().
Referenced by Lscale().
Pscale()
void DnaMeasurement_pimpl::Pscale (const ::std::string & Pscale) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 665 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (Pscale.empty())
        _dnaCurrentMsr->SetPscale("1");
    else
        _dnaCurrentMsr->SetPscale(Pscale);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Pscale().
Referenced by Pscale().
Clusterpoint()
void DnaMeasurement_pimpl::Clusterpoint () virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 677 of file dnaparser_pimpl.cxx.
{
}
Coords()
void DnaMeasurement_pimpl::Coords (const ::std::string & Coords) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 681 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    _dnaCurrentMsr->SetCoordType(Coords);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Coords().
Referenced by Coords().
Source()
void DnaMeasurement_pimpl::Source (const ::std::string & Source) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 690 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (Source.empty())
        _dnaCurrentMsr->SetSource("");
    else
        _dnaCurrentMsr->SetSource(Source);
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and Source().
Referenced by Source().
MeasurementDBID()
void DnaMeasurement_pimpl::MeasurementDBID (const ::std::string & MeasurementID) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 702 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (MeasurementID.empty())
        _dnaCurrentMsr->SetMeasurementDBID("");
    else
        _dnaCurrentMsr->SetMeasurementDBID(MeasurementID);
}
References DnaMeasurement_pskel::_dnaCurrentMsr.
ClusterDBID()
void DnaMeasurement_pimpl::ClusterDBID (const ::std::string & ClusterID) virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 714 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    if (ClusterID.empty())
        _dnaCurrentMsr->SetClusterDBID("");
    else
        _dnaCurrentMsr->SetClusterDBID(ClusterID);
}
References DnaMeasurement_pskel::_dnaCurrentMsr.
post_DnaMeasurement()
void DnaMeasurement_pimpl::post_DnaMeasurement () virtual
Reimplemented from DnaMeasurement_pskel.
Definition at line 726 of file dnaparser_pimpl.cxx.
{
    if (!_dnaCurrentMsr)
        throw XMLInteropException("\"Type\" element must be the first element within \"DnaMeasurement\".", 0);
    UINT32 total, found;
    // Is the direction set empty and ignored?
    // If so, do nothing (an invalid measurement).
    switch (_dnaCurrentMsr->GetTypeC())
    {
    case 'D':
        total = _dnaCurrentMsr->GetTotal();
        if (total == 0 && _dnaCurrentMsr->GetIgnore())
            return;
        break;
    }
    // Now that the measurement has completed, capture all essential elements
    _vParentMsrs->push_back(_dnaCurrentMsr);
    // set "First" to be that of the first in the set
    switch (_dnaCurrentMsr->GetTypeC())
    {
    case 'D':
        total = _dnaCurrentMsr->GetTotal();
        found = static_cast<UINT32>(_dnaCurrentMsr->GetDirections_ptr()->size());
        if (total != found)
        {
            std::stringstream ss, ss2;
            ss <<
                "<Directions>...</Directions>',  total of " << total << " element(s)" << std::endl <<
                "  - found " << found << " <Directions> in the set. '";
            ss2 << " ~ <Total>" << total << "</Total>";
            throw ::xsd::cxx::parser::expected_element< char >(
                ss.str(), ss2.str());
        }
        found = 0;
        // Test for non-ignored measurements
        for_each(_dnaCurrentMsr->GetDirections_ptr()->begin(),
            _dnaCurrentMsr->GetDirections_ptr()->end(),
            [this, &found](CDnaDirection& d) {
                if (d.NotIgnored())
                    found++;
            });
        if (found == 0 && _dnaCurrentMsr->NotIgnored())
        {
            std::stringstream ss, ss2;
            ss <<
                "<Directions>...</Directions>',  total of " << total << " element(s)" << std::endl <<
                "  - There aren't any non-ignored directions in the set. ";
            ss2 << " ~ <Total>" << total << "</Total>";
            throw ::xsd::cxx::parser::expected_element< char >(
                ss.str(), ss2.str());
        }
        _dnaCurrentMsr->SetNonIgnoredDirns(found);
        // Okay, capture all the elements for this direction set
        for_each(_dnaCurrentMsr->GetDirections_ptr()->begin(),
            _dnaCurrentMsr->GetDirections_ptr()->end(),
            [this](CDnaDirection& d) {
                d.SetType(_dnaCurrentMsr->GetType());
                d.SetFirst(_dnaCurrentMsr->GetFirst());
                // This is a target direction, so set zero recorded total so as to
                // distinguish this direction from the RO, for which the recorded
                // total will be the number of target directions
                d.SetRecordedTotal(0);
            });
        break;
    case 'G':
    case 'X':
        total = _dnaCurrentMsr->GetTotal();
        found = static_cast<UINT32>(_dnaCurrentMsr->GetBaselines_ptr()->size());
        if (total != found)
        {
            std::stringstream ss, ss2;
            ss <<
                "<GPSBaseline>...</GPSBaseline>',  total of " << total << " element(s)" << std::endl <<
                "  - found " << found << " <GPSBaseline> in the set. '";
            ss2 << " ~ <Total>" << total << "</Total>";
            throw ::xsd::cxx::parser::expected_element< char >(
                ss.str(), ss2.str());
        }
        // Okay, capture all the elements for this baseline (cluster)
        for_each(_dnaCurrentMsr->GetBaselines_ptr()->begin(),
            _dnaCurrentMsr->GetBaselines_ptr()->end(),
            [this](CDnaGpsBaseline& b) {
                b.SetIgnore(_dnaCurrentMsr->GetIgnore());
                b.SetRecordedTotal(_dnaCurrentMsr->GetTotal());
                b.SetPscale(_dnaCurrentMsr->GetPscale());
                b.SetLscale(_dnaCurrentMsr->GetLscale());
                b.SetHscale(_dnaCurrentMsr->GetHscale());
                b.SetVscale(_dnaCurrentMsr->GetVscale());
            });
        break;
    case 'Y':
        total = _dnaCurrentMsr->GetTotal();
        found = static_cast<UINT32>(_dnaCurrentMsr->GetPoints_ptr()->size());
        if (total != found)
        {
            std::stringstream ss, ss2;
            ss <<
                "<Clusterpoint>...</Clusterpoint>',  total of " << total << " element(s)" << std::endl <<
                "  - found " << found << " <Clusterpoint> in the set. '";
            ss2 << " ~ <Total>" << total << "</Total>";
            throw ::xsd::cxx::parser::expected_element< char >(
                ss.str(), ss2.str());
        }
        // Okay, capture all the elements for this point cluster
        for_each(_dnaCurrentMsr->GetPoints_ptr()->begin(),
            _dnaCurrentMsr->GetPoints_ptr()->end(),
            [this](CDnaGpsPoint& p) {
                p.SetIgnore(_dnaCurrentMsr->GetIgnore());
                p.SetCoordType(_dnaCurrentMsr->GetCoordType());
                p.SetRecordedTotal(_dnaCurrentMsr->GetTotal());
                p.SetPscale(_dnaCurrentMsr->GetPscale());
                p.SetLscale(_dnaCurrentMsr->GetLscale());
                p.SetHscale(_dnaCurrentMsr->GetHscale());
                p.SetVscale(_dnaCurrentMsr->GetVscale());
            });
        break;
    }
}
References DnaMeasurement_pskel::_dnaCurrentMsr, and DnaMeasurement_pskel::_vParentMsrs.
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx