DynAdjust: referenceframe_pimpl Class Reference
referenceframe_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void post_type (std::string &referenceframe, std::string &fileEpsg, bool userspecifiedreferenceframe, bool firstFile)
const std::string str ()
Protected Attributes
std::string _referenceframe
bool _overridereferenceframe
Detailed Description
Definition at line 242 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void referenceframe_pimpl::pre () virtual
Definition at line 1366 of file dnaparser_pimpl.cxx.
{
}
post_type()
void referenceframe_pimpl::post_type (std::string & referenceframe, std::string & fileEpsg, bool userspecifiedreferenceframe, bool firstFile) virtual
Reimplemented from referenceframe_pskel.
Definition at line 1377 of file dnaparser_pimpl.cxx.
{
    // 1. Get the DnaXmlFormat referenceframe attribute value from the file
    _referenceframe = trimstr(post_string());
    // But, is this attribute value an empty string?  As long as a default value
    // is specified in DynaML.xsd, this value will never be empty, unless the user
    // has inadvertently set in the xml file, e.g.:
    //  <DnaXmlFormat referenceframe="" >
    // Check anyway ...
    if (_referenceframe.empty())
        // If the file doesn't contain reference frame, set
        // to the default reference frame passed from import
        _referenceframe = referenceframe;
    try {
        // Capture epsg code for the file
        fileEpsg = epsgStringFromName<std::string>(_referenceframe);
    }
    catch (std::runtime_error& e) {
        std::stringstream ss("");
        ss << e.what() << std::endl;
        throw XMLInteropException(ss.str(), 0);
    }
    if (!userspecifiedreferenceframe)
    {
        // No frame supplied. Set the datum from the first file.
        // If the datum field is blank in the first file, the default will be used.
        if (firstFile)
            referenceframe = _referenceframe;
    }
}
References _referenceframe, dynadjust::epsg::epsgStringFromName(), and trimstr().
str()
const std::string referenceframe_pimpl::str () inline
Definition at line 249 of file dnaparser_pimpl.hxx.
{ return _referenceframe; }
References _referenceframe.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
Member Data Documentation
_referenceframe
std::string referenceframe_pimpl::_referenceframe protected
Definition at line 252 of file dnaparser_pimpl.hxx.
Referenced by post_type(), and str().
_overridereferenceframe
bool referenceframe_pimpl::_overridereferenceframe protected
Definition at line 253 of file dnaparser_pimpl.hxx.
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx