DynAdjust: StationCoord_pimpl Class Reference
StationCoord_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void Name (const ::std::string &)
virtual void XAxis (const ::std::string &)
virtual void YAxis (const ::std::string &)
virtual void Height (const ::std::string &)
virtual void GeoidModel ()
virtual void HemisphereZone (const ::std::string &)
virtual void post_StationCoord ()
Public Member Functions inherited from StationCoord_pskel
virtual void Height ()
void Name_parser (::xml_schema::string_pskel &)
void XAxis_parser (::xml_schema::string_pskel &)
void YAxis_parser (::xml_schema::string_pskel &)
void Height_parser (::Height_pskel &)
void HemisphereZone_parser (::xml_schema::string_pskel &)
void GeoidModel_parser (::GeoidModel_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::Height_pskel &, ::xml_schema::string_pskel &, ::GeoidModel_pskel &)
StationCoord_pskel ()
void InitparentStn (dnaStnPtr pStn)
Additional Inherited Members
Protected Member Functions inherited from StationCoord_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes inherited from StationCoord_pskel
::xml_schema::string_pskel * Name_parser_
::xml_schema::string_pskel * XAxis_parser_
::xml_schema::string_pskel * YAxis_parser_
::Height_pskel * Height_parser_
::xml_schema::string_pskel * HemisphereZone_parser_
::GeoidModel_pskel * GeoidModel_parser_
dnaStnPtr _parent_dnaStn
Detailed Description
Definition at line 211 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void StationCoord_pimpl::pre () virtual
Definition at line 1286 of file dnaparser_pimpl.cxx.
{
}
Name()
void StationCoord_pimpl::Name (const ::std::string &) virtual
Reimplemented from StationCoord_pskel.
Definition at line 1290 of file dnaparser_pimpl.cxx.
{
    //_parent_dnaStn->SetName(Name);
}
XAxis()
void StationCoord_pimpl::XAxis (const ::std::string & XAxis) virtual
Reimplemented from StationCoord_pskel.
Definition at line 1295 of file dnaparser_pimpl.cxx.
{
    _parent_dnaStn->SetXAxis(XAxis);
}
References StationCoord_pskel::_parent_dnaStn, and XAxis().
Referenced by XAxis().
YAxis()
void StationCoord_pimpl::YAxis (const ::std::string & YAxis) virtual
Reimplemented from StationCoord_pskel.
Definition at line 1300 of file dnaparser_pimpl.cxx.
{
    _parent_dnaStn->SetYAxis(YAxis);
}
References StationCoord_pskel::_parent_dnaStn, and YAxis().
Referenced by YAxis().
Height()
void StationCoord_pimpl::Height (const ::std::string & Height) virtual
Definition at line 1305 of file dnaparser_pimpl.cxx.
{
    _parent_dnaStn->SetHeight(Height);
}
References StationCoord_pskel::_parent_dnaStn, and Height().
Referenced by Height().
GeoidModel()
void StationCoord_pimpl::GeoidModel () virtual
Reimplemented from StationCoord_pskel.
Definition at line 1315 of file dnaparser_pimpl.cxx.
{
}
HemisphereZone()
void StationCoord_pimpl::HemisphereZone (const ::std::string & HemisphereZone) virtual
Reimplemented from StationCoord_pskel.
Definition at line 1310 of file dnaparser_pimpl.cxx.
{
    _parent_dnaStn->SetHemisphereZone(HemisphereZone);
}
References StationCoord_pskel::_parent_dnaStn, and HemisphereZone().
Referenced by HemisphereZone().
post_StationCoord()
void StationCoord_pimpl::post_StationCoord () virtual
Reimplemented from StationCoord_pskel.
Definition at line 1347 of file dnaparser_pimpl.cxx.
{
}
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx