DynAdjust: PointCovariance_pskel Class Reference
PointCovariance_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void m11 (const ::std::string &)
virtual void m12 (const ::std::string &)
virtual void m13 (const ::std::string &)
virtual void m21 (const ::std::string &)
virtual void m22 (const ::std::string &)
virtual void m23 (const ::std::string &)
virtual void m31 (const ::std::string &)
virtual void m32 (const ::std::string &)
virtual void m33 (const ::std::string &)
virtual void post_PointCovariance ()
void m11_parser (::xml_schema::string_pskel &)
void m12_parser (::xml_schema::string_pskel &)
void m13_parser (::xml_schema::string_pskel &)
void m21_parser (::xml_schema::string_pskel &)
void m22_parser (::xml_schema::string_pskel &)
void m23_parser (::xml_schema::string_pskel &)
void m31_parser (::xml_schema::string_pskel &)
void m32_parser (::xml_schema::string_pskel &)
void m33_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &)
PointCovariance_pskel ()
void InitparentGpsPoint (dnaMsrPtr pGpsPoint)
Protected Member Functions
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * m11_parser_
::xml_schema::string_pskel * m12_parser_
::xml_schema::string_pskel * m13_parser_
::xml_schema::string_pskel * m21_parser_
::xml_schema::string_pskel * m22_parser_
::xml_schema::string_pskel * m23_parser_
::xml_schema::string_pskel * m31_parser_
::xml_schema::string_pskel * m32_parser_
::xml_schema::string_pskel * m33_parser_
dnaCovariancePtr _dnaPointCovariance
dnaMsrPtr _parent_dnaGpsPoint
Detailed Description
Definition at line 1061 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
PointCovariance_pskel()
PointCovariance_pskel::PointCovariance_pskel ()
Definition at line 757 of file dnaparser_pskel.cxx.
    : m11_parser_ (0),
    m12_parser_ (0),
    m13_parser_ (0),
    m21_parser_ (0),
    m22_parser_ (0),
    m23_parser_ (0),
    m31_parser_ (0),
    m32_parser_ (0),
    m33_parser_ (0)
{
}
References m11_parser_, m12_parser_, m13_parser_, m21_parser_, m22_parser_, m23_parser_, m31_parser_, m32_parser_, and m33_parser_.
Member Function Documentation
m11()
void PointCovariance_pskel::m11 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2722 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m12()
void PointCovariance_pskel::m12 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2726 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m13()
void PointCovariance_pskel::m13 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2730 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m21()
void PointCovariance_pskel::m21 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2734 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m22()
void PointCovariance_pskel::m22 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2738 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m23()
void PointCovariance_pskel::m23 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2742 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m31()
void PointCovariance_pskel::m31 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2746 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m32()
void PointCovariance_pskel::m32 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2750 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m33()
void PointCovariance_pskel::m33 (const ::std::string &) virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2754 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
post_PointCovariance()
void PointCovariance_pskel::post_PointCovariance () virtual
Reimplemented in PointCovariance_pimpl.
Definition at line 2758 of file dnaparser_pskel.cxx.
{
}
m11_parser()
void PointCovariance_pskel::m11_parser (::xml_schema::string_pskel & p)
Definition at line 691 of file dnaparser_pskel.cxx.
{
    this->m11_parser_ = &p;
}
References m11_parser_.
m12_parser()
void PointCovariance_pskel::m12_parser (::xml_schema::string_pskel & p)
Definition at line 696 of file dnaparser_pskel.cxx.
{
    this->m12_parser_ = &p;
}
References m12_parser_.
m13_parser()
void PointCovariance_pskel::m13_parser (::xml_schema::string_pskel & p)
Definition at line 701 of file dnaparser_pskel.cxx.
{
    this->m13_parser_ = &p;
}
References m13_parser_.
m21_parser()
void PointCovariance_pskel::m21_parser (::xml_schema::string_pskel & p)
Definition at line 706 of file dnaparser_pskel.cxx.
{
    this->m21_parser_ = &p;
}
References m21_parser_.
m22_parser()
void PointCovariance_pskel::m22_parser (::xml_schema::string_pskel & p)
Definition at line 711 of file dnaparser_pskel.cxx.
{
    this->m22_parser_ = &p;
}
References m22_parser_.
m23_parser()
void PointCovariance_pskel::m23_parser (::xml_schema::string_pskel & p)
Definition at line 716 of file dnaparser_pskel.cxx.
{
    this->m23_parser_ = &p;
}
References m23_parser_.
m31_parser()
void PointCovariance_pskel::m31_parser (::xml_schema::string_pskel & p)
Definition at line 721 of file dnaparser_pskel.cxx.
{
    this->m31_parser_ = &p;
}
References m31_parser_.
m32_parser()
void PointCovariance_pskel::m32_parser (::xml_schema::string_pskel & p)
Definition at line 726 of file dnaparser_pskel.cxx.
{
    this->m32_parser_ = &p;
}
References m32_parser_.
m33_parser()
void PointCovariance_pskel::m33_parser (::xml_schema::string_pskel & p)
Definition at line 731 of file dnaparser_pskel.cxx.
{
    this->m33_parser_ = &p;
}
References m33_parser_.
parsers()
void PointCovariance_pskel::parsers (::xml_schema::string_pskel & m11, ::xml_schema::string_pskel & m12, ::xml_schema::string_pskel & m13, ::xml_schema::string_pskel & m21, ::xml_schema::string_pskel & m22, ::xml_schema::string_pskel & m23, ::xml_schema::string_pskel & m31, ::xml_schema::string_pskel & m32, ::xml_schema::string_pskel & m33)
Definition at line 736 of file dnaparser_pskel.cxx.
{
    this->m11_parser_ = &m11;
    this->m12_parser_ = &m12;
    this->m13_parser_ = &m13;
    this->m21_parser_ = &m21;
    this->m22_parser_ = &m22;
    this->m23_parser_ = &m23;
    this->m31_parser_ = &m31;
    this->m32_parser_ = &m32;
    this->m33_parser_ = &m33;
}
References m11(), m11_parser_, m12(), m12_parser_, m13(), m13_parser_, m21(), m21_parser_, m22(), m22_parser_, m23(), m23_parser_, m31(), m31_parser_, m32(), m32_parser_, m33(), and m33_parser_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
InitparentGpsPoint()
void PointCovariance_pskel::InitparentGpsPoint (dnaMsrPtr pGpsPoint) inline
Definition at line 1107 of file dnaparser_pskel.hxx.
    {
        _parent_dnaGpsPoint = pGpsPoint;
    }
References _parent_dnaGpsPoint.
_start_element_impl()
bool PointCovariance_pskel::_start_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string * t) protected virtual
Definition at line 2762 of file dnaparser_pskel.cxx.
{
    XSD_UNUSED (t);
    if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
        return true;
    if (n == "m11" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m11_parser_;
        if (this->m11_parser_)
            this->m11_parser_->pre ();
        return true;
    }
    if (n == "m12" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m12_parser_;
        if (this->m12_parser_)
            this->m12_parser_->pre ();
        return true;
    }
    if (n == "m13" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m13_parser_;
        if (this->m13_parser_)
            this->m13_parser_->pre ();
        return true;
    }
    if (n == "m21" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m21_parser_;
        if (this->m21_parser_)
            this->m21_parser_->pre ();
        return true;
    }
    if (n == "m22" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m22_parser_;
        if (this->m22_parser_)
            this->m22_parser_->pre ();
        return true;
    }
    if (n == "m23" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m23_parser_;
        if (this->m23_parser_)
            this->m23_parser_->pre ();
        return true;
    }
    if (n == "m31" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m31_parser_;
        if (this->m31_parser_)
            this->m31_parser_->pre ();
        return true;
    }
    if (n == "m32" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m32_parser_;
        if (this->m32_parser_)
            this->m32_parser_->pre ();
        return true;
    }
    if (n == "m33" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m33_parser_;
        if (this->m33_parser_)
            this->m33_parser_->pre ();
        return true;
    }
    return false;
}
References m11_parser_, m12_parser_, m13_parser_, m21_parser_, m22_parser_, m23_parser_, m31_parser_, m32_parser_, and m33_parser_.
_end_element_impl()
bool PointCovariance_pskel::_end_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n) protected virtual
Definition at line 2864 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
        return true;
    if (n == "m11" && ns.empty ())
    {
        if (this->m11_parser_)
            this->m11 (this->m11_parser_->post_string ());
        return true;
    }
    if (n == "m12" && ns.empty ())
    {
        if (this->m12_parser_)
            this->m12 (this->m12_parser_->post_string ());
        return true;
    }
    if (n == "m13" && ns.empty ())
    {
        if (this->m13_parser_)
            this->m13 (this->m13_parser_->post_string ());
        return true;
    }
    if (n == "m21" && ns.empty ())
    {
        if (this->m21_parser_)
            this->m21 (this->m21_parser_->post_string ());
        return true;
    }
    if (n == "m22" && ns.empty ())
    {
        if (this->m22_parser_)
            this->m22 (this->m22_parser_->post_string ());
        return true;
    }
    if (n == "m23" && ns.empty ())
    {
        if (this->m23_parser_)
            this->m23 (this->m23_parser_->post_string ());
        return true;
    }
    if (n == "m31" && ns.empty ())
    {
        if (this->m31_parser_)
            this->m31 (this->m31_parser_->post_string ());
        return true;
    }
    if (n == "m32" && ns.empty ())
    {
        if (this->m32_parser_)
            this->m32 (this->m32_parser_->post_string ());
        return true;
    }
    if (n == "m33" && ns.empty ())
    {
        if (this->m33_parser_)
            this->m33 (this->m33_parser_->post_string ());
        return true;
    }
    return false;
}
References m11(), m11_parser_, m12(), m12_parser_, m13(), m13_parser_, m21(), m21_parser_, m22(), m22_parser_, m23(), m23_parser_, m31(), m31_parser_, m32(), m32_parser_, m33(), and m33_parser_.
Member Data Documentation
m11_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m11_parser_ protected
Definition at line 1126 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m11_parser(), parsers(), and PointCovariance_pskel().
m12_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m12_parser_ protected
Definition at line 1127 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m12_parser(), parsers(), and PointCovariance_pskel().
m13_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m13_parser_ protected
Definition at line 1128 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m13_parser(), parsers(), and PointCovariance_pskel().
m21_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m21_parser_ protected
Definition at line 1129 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m21_parser(), parsers(), and PointCovariance_pskel().
m22_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m22_parser_ protected
Definition at line 1130 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m22_parser(), parsers(), and PointCovariance_pskel().
m23_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m23_parser_ protected
Definition at line 1131 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m23_parser(), parsers(), and PointCovariance_pskel().
m31_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m31_parser_ protected
Definition at line 1132 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m31_parser(), parsers(), and PointCovariance_pskel().
m32_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m32_parser_ protected
Definition at line 1133 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m32_parser(), parsers(), and PointCovariance_pskel().
m33_parser_
::xml_schema::string_pskel* PointCovariance_pskel::m33_parser_ protected
Definition at line 1134 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), m33_parser(), parsers(), and PointCovariance_pskel().
_dnaPointCovariance
dnaCovariancePtr PointCovariance_pskel::_dnaPointCovariance protected
Definition at line 1136 of file dnaparser_pskel.hxx.
Referenced by PointCovariance_pimpl::m11(), PointCovariance_pimpl::m12(), PointCovariance_pimpl::m13(), PointCovariance_pimpl::m21(), PointCovariance_pimpl::m22(), PointCovariance_pimpl::m23(), PointCovariance_pimpl::m31(), PointCovariance_pimpl::m32(), PointCovariance_pimpl::m33(), PointCovariance_pimpl::post_PointCovariance(), and PointCovariance_pimpl::pre().
_parent_dnaGpsPoint
dnaMsrPtr PointCovariance_pskel::_parent_dnaGpsPoint protected
Definition at line 1137 of file dnaparser_pskel.hxx.
Referenced by InitparentGpsPoint(), PointCovariance_pimpl::post_PointCovariance(), and PointCovariance_pimpl::pre().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx