DynAdjust: dynadjust::iostreams::dna_io_aml Class Reference
dynadjust::iostreams::dna_io_aml Class Reference
#include <dnaioaml.hpp>
Public Member Functions
dna_io_aml (void)
dna_io_aml (const dna_io_aml &aml)
virtual ~dna_io_aml (void)
dna_io_aml & operator= (const dna_io_aml &rhs)
void load_aml_file (const std::string &aml_filename, v_aml_pair *vbinary_aml, pvmsr_t bmsRecords)
void write_aml_file (const std::string &aml_filename, pvUINT32 vbinary_aml)
void write_aml_file_txt (const std::string &bms_filename, const std::string &aml_filename, pvUINT32 vbinary_aml, const pvASLPtr vAssocStnList, vdnaStnPtr *vStations)
void create_msr_to_stn_tally (const pvASLPtr vAssocStnList, v_aml_pair &vAssocMsrList, vmsrtally &stnmsrTally, vmsr_t &bmsBinaryRecords)
void write_msr_to_stn (std::ostream &os, pvstn_t bstBinaryRecords, pvUINT32 vStationList, vmsrtally &v_stnmsrTally, MsrTally *parsemsrTally)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 38 of file dnaioaml.hpp.
Constructor & Destructor Documentation
dna_io_aml() [1/2]
dynadjust::iostreams::dna_io_aml::dna_io_aml (void) inline
Definition at line 41 of file dnaioaml.hpp.
{};
Referenced by dna_io_aml(), and operator=().
dna_io_aml() [2/2]
dynadjust::iostreams::dna_io_aml::dna_io_aml (const dna_io_aml & aml) inline
Definition at line 42 of file dnaioaml.hpp.
: dna_io_base(aml) {};
References dna_io_aml(), and dynadjust::iostreams::dna_io_base::dna_io_base().
~dna_io_aml()
virtual dynadjust::iostreams::dna_io_aml::~dna_io_aml (void) inline virtual
Definition at line 43 of file dnaioaml.hpp.
{};
Member Function Documentation
operator=()
dna_io_aml & dynadjust::iostreams::dna_io_aml::operator= (const dna_io_aml & rhs)
References dna_io_aml().
load_aml_file()
void dynadjust::iostreams::dna_io_aml::load_aml_file (const std::string & aml_filename, v_aml_pair * vbinary_aml, pvmsr_t bmsRecords)
Definition at line 30 of file dnaioaml.cpp.
{
    std::ifstream aml_file;
    std::stringstream ss;
    ss << "load_aml_file(): An error was encountered when opening " << aml_filename << "." << std::endl;
    try {
        // open stations aml file.  Throws runtime_error on failure.
        file_opener(aml_file, aml_filename, std::ios::in | std::ios::binary, binary, true);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "load_aml_file(): An error was encountered when reading from " << aml_filename << "." << std::endl;
    UINT32 msrValue;
    try {
        // read the file information
        readFileInfo(aml_file);
        // Get number of records and resize AML vector
        aml_file.read(reinterpret_cast<char *>(&msrValue), sizeof(UINT32));
        vbinary_aml->clear();
        vbinary_aml->resize(msrValue);
        it_aml_pair _it_aml;
        for (_it_aml = vbinary_aml->begin();
            _it_aml != vbinary_aml->end();
            ++_it_aml)
        {
            aml_file.read(reinterpret_cast<char *>(&msrValue), sizeof(UINT32));
            // Ignored measurements are retained in the AML, so consume them!
            _it_aml->bmsr_index = msrValue;
            if (bmsRecords->at(msrValue).ignore)
                _it_aml->consume();
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    aml_file.close();
}
References binary, file_opener(), and dynadjust::iostreams::dna_io_base::readFileInfo().
Referenced by dynadjust::networkadjust::dna_adjust::CreateMsrToStnTally(), dynadjust::networksegment::dna_segment::LoadAssociationFiles(), and dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations().
write_aml_file()
void dynadjust::iostreams::dna_io_aml::write_aml_file (const std::string & aml_filename, pvUINT32 vbinary_aml)
Definition at line 92 of file dnaioaml.cpp.
{
    std::ofstream aml_file;
    std::stringstream ss;
    ss << "write_aml_file(): An error was encountered when opening " << aml_filename << "." << std::endl;
    try {
        // create binary aml file.  Throws runtime_error on failure.
        file_opener(aml_file, aml_filename,
            std::ios::out | std::ios::binary, binary);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_aml_file(): An error was encountered when writing to " << aml_filename << "." << std::endl;
    // Calculate number of measurement records and write to binary file
    UINT32 amlCount(static_cast<UINT32>(vbinary_aml->size()));
    it_vUINT32 _it_aml;
    try {
        // write the file information
        writeFileInfo(aml_file);
        // write the data
        aml_file.write(reinterpret_cast<char *>(&amlCount), sizeof(UINT32));
        for (_it_aml = vbinary_aml->begin();
            _it_aml != vbinary_aml->end();
            ++_it_aml)
        {
            aml_file.write(reinterpret_cast<char *>(&(*_it_aml)), sizeof(UINT32));
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    aml_file.close();
}
References binary, file_opener(), and dynadjust::iostreams::dna_io_base::writeFileInfo().
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseAml().
write_aml_file_txt()
void dynadjust::iostreams::dna_io_aml::write_aml_file_txt (const std::string & bms_filename, const std::string & aml_filename, pvUINT32 vbinary_aml, const pvASLPtr vAssocStnList, vdnaStnPtr * vStations)
Definition at line 252 of file dnaioaml.cpp.
{
    vmsr_t binaryMsrRecords;
    std::stringstream ss;
    ss << "write_aml_file(): An error was encountered when opening " << bms_filename << "." << std::endl;
    binary_file_meta_t bms_meta;
    try {
        dna_io_bms bms;
        // Load binary stations data.  Throws runtime_error on failure.
        bms.load_bms_file(bms_filename, &binaryMsrRecords, bms_meta);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    std::ofstream aml_file;
    ss.str("");
    ss << "write_aml_file(): An error was encountered when opening " << aml_filename << "." << std::endl;
    try {
        // create binary aml file.  Throws runtime_error on failure.
        file_opener(aml_file, aml_filename,
            std::ios::out | std::ios::binary, binary);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_aml_file(): An error was encountered when writing to " << aml_filename << "." << std::endl;
    // Write number of measurement records to file
    std::stringstream ss_aml;
    ss_aml << vbinary_aml->size() << " records";
    aml_file << std::left << std::setw(HEADER_18) << ss_aml.str();
    aml_file << std::left << std::setw(MSR) << "Msr index";
    aml_file << std::left << std::setw(MSR) << "Msr type";
    aml_file << std::left << std::setw(MSR) << "Cluster";
    aml_file << std::left << std::setw(MSR) << "Ignored msr?" << std::endl;
    it_vUINT32_const _it_aml(vbinary_aml->begin());
    UINT32 stn_index(0);
    UINT32 nextAMLStationIndex(vAssocStnList->at(stn_index)->GetAMLStnIndex() + vAssocStnList->at(stn_index)->GetAssocMsrCount());
    UINT32 currAMLStationIndex(0);
    vUINT32 msrIndices;
    it_vUINT32 _it_msr;
    try {
        do
        {
            if (stn_index >= vAssocStnList->size())
                break;
            if (_it_aml >= vbinary_aml->end())
                break;
            // Is the curent station not connected to any measurements?
            if (vAssocStnList->at(stn_index)->GetAssocMsrCount() == 0)
            {
                // Get the index of the next station in the AML
                ++stn_index;
                nextAMLStationIndex = vAssocStnList->at(stn_index)->GetAMLStnIndex() + vAssocStnList->at(stn_index)->GetAssocMsrCount();
                continue;
            }
            // Has a new station index been reached?
            if (currAMLStationIndex == nextAMLStationIndex)
            {
                // Get the index of the next station in the AML
                ++stn_index;
                nextAMLStationIndex = vAssocStnList->at(stn_index)->GetAMLStnIndex() + vAssocStnList->at(stn_index)->GetAssocMsrCount();
                continue;
            }
            // At this point, the current station is connected to measurements.
            // However, such measurements may be ignored, in which case a station
            // may be unused.
            // Print station name
            aml_file << std::setw(HEADER_18) << std::left << vStations->at(stn_index)->GetName();
            // print the bmsr index
            // For clusters, this will be the index of the first binary element
            aml_file << std::setw(MSR) << std::left << *_it_aml;
            GetMsrIndices<UINT32>(binaryMsrRecords, *_it_aml, msrIndices);
            ss_aml.str("");
            ss_aml << binaryMsrRecords.at(*_it_aml).measType;
            for (_it_msr=msrIndices.begin(); _it_msr!=msrIndices.end(); ++_it_msr)
            {
                if (stn_index == binaryMsrRecords.at(*_it_msr).station1)
                {
                    // All measurements have a first station
                    ss_aml << std::left << " (First)";
                    aml_file << std::setw(MSR) << std::left << ss_aml.str();
                    ss_aml.str("");
                    switch (binaryMsrRecords.at(*_it_msr).measType)
                    {
                    case 'D': // Direction set
                    case 'X': // GPS Baseline cluster
                    case 'Y': // GPS point cluster
                        ss_aml << std::setw(MSR) << std::left << binaryMsrRecords.at(*_it_msr).clusterID;
                        break;
                    default:
                        ss_aml << std::setw(MSR) << std::left << " ";
                        break;
                    }
                    continue;
                }
                if (MsrTally::Stations(binaryMsrRecords.at(*_it_msr).measType) >= TWO_STATION)
                {
                    // Measurements which have a second or third station
                    switch (binaryMsrRecords.at(*_it_msr).measType)
                    {
                    case 'D': // Direction set
                        if (stn_index == binaryMsrRecords.at(*_it_msr).station2)
{
                            if (binaryMsrRecords.at(*_it_msr).vectorCount1 > 0)
                                ss_aml << std::left << " (Second)";
                            else
                                ss_aml << std::left << " (Target)";
                        }
                        aml_file << std::setw(MSR) << std::left << ss_aml.str();
                        ss_aml.str("");
                        ss_aml << std::setw(MSR) << std::left << binaryMsrRecords.at(*_it_msr).clusterID;
                        break;
                    case 'B': // Geodetic azimuth
                    case 'C': // Chord dist
                    case 'E': // Ellipsoid arc
                    case 'G': // GPS Baseline (treat as single-baseline cluster)
                    case 'K': // Astronomic azimuth
                    case 'L': // Level difference
                    case 'M': // MSL arc
                    case 'S': // Slope distance
                    case 'V': // Zenith distance
                    case 'Z': // Vertical angle
                        if (stn_index == binaryMsrRecords.at(*_it_msr).station2)
                            ss_aml << std::left << " (Second)";
                        aml_file << std::setw(MSR) << std::left << ss_aml.str();
                        ss_aml.str("");
                        ss_aml << std::setw(MSR) << std::left << " ";
                        break;
                    case 'X': // GPS Baseline cluster
                        if (stn_index == binaryMsrRecords.at(*_it_msr).station2)
                            ss_aml << std::left << " (Second)";
                        aml_file << std::setw(MSR) << std::left << ss_aml.str();
                        ss_aml.str("");
                        ss_aml << std::setw(MSR) << std::left << binaryMsrRecords.at(*_it_msr).clusterID;
                        break;
                    case 'A': // Horizontal angle
                        if (stn_index == binaryMsrRecords.at(*_it_msr).station2)
                            ss_aml << std::left << " (Second)";
                        else if (stn_index == binaryMsrRecords.at(*_it_msr).station3)
                            ss_aml << std::left << " (Third)";
                        aml_file << std::setw(MSR) << std::left << ss_aml.str();
                        ss_aml.str("");
                        ss_aml << std::setw(MSR) << std::left << " ";
                        break;
                    }
                }
            }
            aml_file << std::setw(MSR) << std::left << ss_aml.str();
            if (binaryMsrRecords.at(*_it_aml).ignore)
                aml_file << std::setw(MSR) << std::left << "*" << std::endl; // Ignored
            else
                aml_file << std::setw(MSR) << std::left << " " << std::endl;
            // Move to the next AML record
            if (++_it_aml == vbinary_aml->end())
                break;
            ++currAMLStationIndex;
        // has the end of the AML been reached?
        } while (_it_aml != vbinary_aml->end());
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    aml_file.close();
}
References binary, file_opener(), GetMsrIndices(), HEADER_18(), dynadjust::iostreams::dna_io_bms::load_bms_file(), MSR(), dynadjust::measurements::MsrTally::Stations(), and TWO_STATION.
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseAmlTextFile().
create_msr_to_stn_tally()
void dynadjust::iostreams::dna_io_aml::create_msr_to_stn_tally (const pvASLPtr vAssocStnList, v_aml_pair & vAssocMsrList, vmsrtally & stnmsrTally, vmsr_t & bmsBinaryRecords)
Definition at line 146 of file dnaioaml.cpp.
{
    stnmsrTally.clear();
    stnmsrTally.resize(vAssocStnList->size());
    vASLPtr::iterator _it_asl;
    UINT32 i, m, amlIndex, msrCount;
    for (_it_asl=vAssocStnList->begin(), i=0; _it_asl!=vAssocStnList->end(); ++_it_asl, ++i)
    {
        msrCount = _it_asl->get()->GetAssocMsrCount();
        for (m=0; m<msrCount; ++m)
        {
            amlIndex = _it_asl->get()->GetAMLStnIndex() + m;
            if (bmsBinaryRecords.at(vAssocMsrList.at(amlIndex).bmsr_index).ignore)
                continue;
            stnmsrTally.at(i).IncrementMsrType(bmsBinaryRecords.at(vAssocMsrList.at(amlIndex).bmsr_index).measType);
        }
        stnmsrTally.at(i).TotalCount();
    }
}
Referenced by dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations().
write_msr_to_stn()
void dynadjust::iostreams::dna_io_aml::write_msr_to_stn (std::ostream & os, pvstn_t bstBinaryRecords, pvUINT32 vStationList, vmsrtally & v_stnmsrTally, MsrTally * parsemsrTally)
Definition at line 174 of file dnaioaml.cpp.
{
    // Print measurement to station summary header
    std::string header("MEASUREMENT TO STATIONS ");
    MsrToStnSummaryHeader(os, header);
    it_vUINT32 _it_stn(vStationList->begin());
    UINT32 msrRedundancies(0);
    vstring stationRedundantMsrs;
    // Print measurements to each station and the total count for each station
    for (_it_stn=vStationList->begin(); _it_stn != vStationList->end(); ++_it_stn)
    {
        v_stnmsrTally.at(*_it_stn).coutSummaryMsrToStn(os, bstBinaryRecords->at(*_it_stn).stationName);
        // Test for possible redundancies
        if ((v_stnmsrTally.at(*_it_stn).MeasurementCount('G') ||
            v_stnmsrTally.at(*_it_stn).MeasurementCount('X') ||
            v_stnmsrTally.at(*_it_stn).MeasurementCount('Y'))
            &&
            (v_stnmsrTally.at(*_it_stn).MeasurementCount('P') ||
            v_stnmsrTally.at(*_it_stn).MeasurementCount('Q') ||
            v_stnmsrTally.at(*_it_stn).MeasurementCount('R') ||
            v_stnmsrTally.at(*_it_stn).MeasurementCount('H') ||
            v_stnmsrTally.at(*_it_stn).MeasurementCount('I') ||
            v_stnmsrTally.at(*_it_stn).MeasurementCount('J')))
        {
            msrRedundancies++;
            stationRedundantMsrs.push_back(bstBinaryRecords->at(*_it_stn).stationName);
        }
    }
    // Print "the bottom line"
    MsrToStnSummaryHeaderLine(os);
    // Print the total count per measurement
    parsemsrTally->coutSummaryMsrToStn(os, "Totals");
    os << std::endl << std::endl;
    if (msrRedundancies > 0)
    {
        os << "WARNING: " << msrRedundancies;
        if (msrRedundancies == 1)
            os << " station was";
        else
            os << " stations were";
        os << " found to have GNSS measurements and absolute terrestrial measurements:" << std::endl << std::endl;
        // Print header
        os << std::setw(STATION) << std::left << "Station" << std::setw(30) << "Measurement types" << "Count" << std::endl;
        os << "------------------------------------------------------------" << std::endl;
        // Print measurements to each station and the total count for each station
        for (_it_stn=vStationList->begin(); _it_stn != vStationList->end(); ++_it_stn)
        {
            // Test for possible redundancies
            if ((v_stnmsrTally.at(*_it_stn).MeasurementCount('G') ||
                v_stnmsrTally.at(*_it_stn).MeasurementCount('X') ||
                v_stnmsrTally.at(*_it_stn).MeasurementCount('Y'))
                &&
                (v_stnmsrTally.at(*_it_stn).MeasurementCount('P') ||
                v_stnmsrTally.at(*_it_stn).MeasurementCount('Q') ||
                v_stnmsrTally.at(*_it_stn).MeasurementCount('R') ||
                v_stnmsrTally.at(*_it_stn).MeasurementCount('H') ||
                v_stnmsrTally.at(*_it_stn).MeasurementCount('I') ||
                v_stnmsrTally.at(*_it_stn).MeasurementCount('J')))
            {
                v_stnmsrTally.at(*_it_stn).coutSummaryMsrToStn_Compressed(os, bstBinaryRecords->at(*_it_stn).stationName);
            }
        }
    }
}
References dynadjust::measurements::MsrTally::coutSummaryMsrToStn(), dynadjust::measurements::MsrToStnSummaryHeader(), dynadjust::measurements::MsrToStnSummaryHeaderLine(), and STATION().
Referenced by dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations().
The documentation for this class was generated from the following files:
include/io/dnaioaml.hpp
include/io/dnaioaml.cpp