DynAdjust: CompareStnName_CDnaStn< S, T > Class Template Reference
CompareStnName_CDnaStn< S, T > Class Template Reference
#include <dnatemplatefuncs.hpp>
Public Member Functions
bool operator() (const boost::shared_ptr< S > lhs, const boost::shared_ptr< S > rhs)
bool operator() (const T lhs, const boost::shared_ptr< S > rhs)
bool operator() (const boost::shared_ptr< S > lhs, const T rhs)
Private Member Functions
bool keyLess (const T &k1, const T &k2) const
Detailed Description
template<typename S, typename T>
class CompareStnName_CDnaStn< S, T >
Definition at line 1447 of file dnatemplatefuncs.hpp.
Member Function Documentation
operator()() [1/3]
template<typename S, typename T> bool CompareStnName_CDnaStn< S, T >::operator() (const boost::shared_ptr< S > lhs, const boost::shared_ptr< S > rhs) inline
Definition at line 1450 of file dnatemplatefuncs.hpp.
{
        if (lhs.get()->GetName() == rhs.get()->GetName())
            return (lhs.get()->GetfileOrder() < rhs.get()->GetfileOrder());
        return keyLess(lhs.get()->GetName(), rhs.get()->GetName());
    }
References keyLess().
operator()() [2/3]
template<typename S, typename T> bool CompareStnName_CDnaStn< S, T >::operator() (const T lhs, const boost::shared_ptr< S > rhs) inline
Definition at line 1456 of file dnatemplatefuncs.hpp.
{
        return keyLess(lhs, rhs.get()->GetName());
    }
References keyLess().
operator()() [3/3]
template<typename S, typename T> bool CompareStnName_CDnaStn< S, T >::operator() (const boost::shared_ptr< S > lhs, const T rhs) inline
Definition at line 1460 of file dnatemplatefuncs.hpp.
{
        return keyLess(lhs.get()->GetName(), rhs);
    }
References keyLess().
keyLess()
template<typename S, typename T> bool CompareStnName_CDnaStn< S, T >::keyLess (const T & k1, const T & k2) const inline private
Definition at line 1466 of file dnatemplatefuncs.hpp.
{
        return k1 < k2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this class was generated from the following file:
include/functions/dnatemplatefuncs.hpp