DynAdjust: dynadjust::measurements::CDnaDistance Class Reference
dynadjust::measurements::CDnaDistance Class Reference
#include <dnadistance.hpp>
Public Member Functions
CDnaDistance (void)
virtual ~CDnaDistance (void)
bool operator== (const CDnaDistance &rhs) const
bool operator< (const CDnaDistance &rhs) const
std::string GetTarget () const
double GetValue () const
double GetStdDev () const
float GetInstrHeight () const
float GetTargetHeight () const
void SetTarget (const std::string &str)
void SetValue (const std::string &str)
void SetStdDev (const std::string &str)
void SetInstrumentHeight (const std::string &str)
void SetTargetHeight (const std::string &str)
virtual UINT32 CalcBinaryRecordCount () const
virtual void WriteBinaryMsr (std::ofstream *binary_stream, PUINT32 msrIndex) const
virtual UINT32 SetMeasurementRec (const vstn_t &binaryStn, it_vmsr_t &it_msr, it_vdbid_t &dbidmap)
virtual void WriteDynaMLMsr (std::ofstream *dynaml_stream, const std::string &comment, bool) const
virtual void WriteDNAMsr (std::ofstream *dna_stream, const dna_msr_fields &dmw, const dna_msr_fields &dml, bool) const
virtual void SimulateMsr (vdnaStnPtr *vStations, const CDnaEllipsoid *ellipsoid)
Public Member Functions inherited from dynadjust::measurements::CDnaMeasurement
CDnaMeasurement ()
virtual ~CDnaMeasurement ()
CDnaMeasurement (CDnaMeasurement &&m)
CDnaMeasurement & operator= (CDnaMeasurement &&rhs)
std::string GetType () const
char GetTypeC () const
bool GetIgnore () const
bool NotIgnored () const
std::string GetFirst () const
MEASUREMENT_STATIONS GetMsrStnCount () const
std::string GetEpsg () const
std::string GetSource () const
bool GetInsufficient () const
void SetType (const std::string &str)
void SetIgnore (const bool bval)
void SetFirst (const std::string &str)
void SetEpsg (const std::string &e)
void SetSource (const std::string &source)
void SetInsufficient (const bool bval)
void SetMsrIndex (const UINT32 &order)
void SetStn1Index (const UINT32 &order)
void SetStn2Index (const UINT32 &order)
void SetStn3Index (const UINT32 &order)
UINT32 GetMsrIndex () const
UINT32 GetStn1Index () const
UINT32 GetStn2Index () const
UINT32 GetStn3Index () const
double GetMeasAdj () const
double GetMeasCorr () const
double GetMeasAdjPrec () const
double GetResidualPrec () const
double GetPreAdjCorr () const
virtual void PopulateMsr (pvstn_t, uint32_uint32_map *, vUINT32 *, const UINT32 &, const CDnaDatum *, math::matrix_2d *, math::matrix_2d *)
virtual UINT32 GetClusterID () const
virtual std::string GetCoordType () const
virtual double GetVscale () const
virtual double GetPscale () const
virtual double GetLscale () const
virtual double GetHscale () const
virtual std::string GetTarget2 () const
virtual UINT32 GetTotal () const
virtual std::string GetReferenceFrame () const
std::string GetEpoch () const
virtual std::vector< CDnaGpsBaseline > * GetBaselines_ptr ()
virtual std::vector< CDnaDirection > * GetDirections_ptr ()
virtual std::vector< CDnaGpsPoint > * GetPoints_ptr ()
virtual std::vector< CDnaCovariance > * GetCovariances_ptr ()
virtual void AddDirection (const CDnaMeasurement *)
virtual void AddGpsBaseline (const CDnaMeasurement *)
virtual void AddGpsPoint (const CDnaMeasurement *)
virtual void AddGpsCovariance (const CDnaCovariance *)
virtual void AddPointCovariance (const CDnaCovariance *)
virtual void ReserveDirectionsCount (const UINT32 &)
virtual void ReserveGpsBaselinesCount (const UINT32 &)
virtual void ReserveGpsPointsCount (const UINT32 &)
virtual void ReserveGpsCovariancesCount (const UINT32 &)
virtual void ResizeGpsCovariancesCount (const UINT32 &)
virtual void SetRecordedTotal (const UINT32 &)
virtual void SetNonIgnoredDirns (const UINT32 &)
virtual void SetClusterID (const UINT32 &)
virtual void SetCoordType (const std::string &)
virtual void SetHscale (const std::string &)
virtual void SetHscale (const double &)
virtual void SetReferenceFrame (const std::string &)
void SetEpoch (const std::string &epoch)
virtual void SetLscale (const std::string &)
virtual void SetLscale (const double &)
virtual void SetPscale (const std::string &)
virtual void SetPscale (const double &)
virtual void SetSigmaXX (const std::string &)
virtual void SetSigmaXY (const std::string &)
virtual void SetSigmaXZ (const std::string &)
virtual void SetSigmaYY (const std::string &)
virtual void SetSigmaYZ (const std::string &)
virtual void SetSigmaZZ (const std::string &)
virtual void SetTarget2 (const std::string &)
virtual void SetTotal (const std::string &)
virtual void SetVscale (const std::string &)
virtual void SetVscale (const double &)
virtual void SetX (const std::string &)
virtual void SetY (const std::string &)
virtual void SetZ (const std::string &)
virtual void SetXAxis (const double &)
virtual void SetYAxis (const double &)
virtual void SetZAxis (const double &)
virtual void SetSigmaXX (const double &)
virtual void SetSigmaXY (const double &)
virtual void SetSigmaXZ (const double &)
virtual void SetSigmaYY (const double &)
virtual void SetSigmaYZ (const double &)
virtual void SetSigmaZZ (const double &)
virtual void SetTotal (const UINT32 &)
virtual void PreferGMeasurements ()
void SetMeasurementDBID (const std::string &str)
void SetClusterDBID (const std::string &str)
void SetClusterDBID (const UINT32 &u, bool s)
UINT32 GetClusterDBID ()
bool GetClusterDBIDset ()
void SetDatabaseMap (const msr_database_id_map &dbidmap)
virtual void SetDatabaseMaps (it_vdbid_t &it_dbidmap)
virtual void SerialiseDatabaseMap (std::ofstream *os)
Protected Attributes
std::string m_strTarget
double m_dValue
double m_dStdDev
float m_fInstHeight
float m_fTargHeight
Protected Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strType
bool m_bIgnore
UINT32 m_lmeasurementIndex
UINT32 m_lstn1Index
UINT32 m_lstn2Index
UINT32 m_lstn3Index
double m_measAdj
double m_measCorr
double m_measAdjPrec
double m_residualPrec
double m_preAdjCorr
std::string m_epsgCode
std::string m_sourceFile
std::string m_epoch
msr_database_id_map m_msr_db_map
bool m_bInsufficient
Additional Inherited Members
Public Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strFirst
MEASUREMENT_STATIONS m_MSmeasurementStations
Protected Member Functions inherited from dynadjust::measurements::CDnaMeasurement
void coutMeasurement (std::ostream &os) const
Detailed Description
Definition at line 37 of file dnadistance.hpp.
Constructor & Destructor Documentation
CDnaDistance()
dynadjust::measurements::CDnaDistance::CDnaDistance (void)
Definition at line 28 of file dnadistance.cpp.
    : m_strTarget("")
    , m_dValue(0.)
    , m_dStdDev(0.)
    , m_fInstHeight(0.)
    , m_fTargHeight(0.)
{
    m_strType = "S";       // default is Slope distance, but could also be 'C' or 'E' or 'M'
    m_MSmeasurementStations = TWO_STATION;
}
References m_dStdDev, m_dValue, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, and TWO_STATION.
Referenced by operator<(), and operator==().
~CDnaDistance()
dynadjust::measurements::CDnaDistance::~CDnaDistance (void) virtual
Definition at line 40 of file dnadistance.cpp.
{
}
Member Function Documentation
operator==()
bool dynadjust::measurements::CDnaDistance::operator== (const CDnaDistance & rhs) const
Definition at line 46 of file dnadistance.cpp.
{
    return (
        m_strFirst == rhs.m_strFirst &&
        m_bIgnore == rhs.m_bIgnore &&
        m_strTarget == rhs.m_strTarget &&
        m_dValue == rhs.m_dValue &&
        m_dStdDev == rhs.m_dStdDev &&
        m_strType == rhs.m_strType &&
        m_fInstHeight == rhs.m_fInstHeight &&
        m_fTargHeight == rhs.m_fTargHeight &&
        m_epoch == rhs.m_epoch
        );
}
References CDnaDistance(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, and dynadjust::measurements::CDnaMeasurement::m_strType.
operator<()
bool dynadjust::measurements::CDnaDistance::operator< (const CDnaDistance & rhs) const
Definition at line 62 of file dnadistance.cpp.
{
    if (m_strFirst == rhs.m_strFirst) {
        if (m_strType == rhs.m_strType) {  // could be C, E, M, S
            if (m_bIgnore == rhs.m_bIgnore) {
                if (m_epoch == rhs.m_epoch) {
                    if (m_strTarget == rhs.m_strTarget) {
                        if (m_dValue == rhs.m_dValue) {
                            if (m_dStdDev == rhs.m_dStdDev) {
                                if (m_fInstHeight == rhs.m_fInstHeight)
                                    return m_fTargHeight < rhs.m_fTargHeight;
                                else
                                    return m_fInstHeight < rhs.m_fInstHeight; }
                            else
                                return m_dStdDev < rhs.m_dStdDev; }
                        else
                            return m_dValue < rhs.m_dValue; }
                    else
                        return m_strTarget < rhs.m_strTarget; }
                else
                    return m_epoch < rhs.m_epoch; }
            else
                return m_bIgnore < rhs.m_bIgnore; }
        else
            return m_strType < rhs.m_strType; }
    else
        return m_strFirst < rhs.m_strFirst;
}
References CDnaDistance(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, and dynadjust::measurements::CDnaMeasurement::m_strType.
GetTarget()
std::string dynadjust::measurements::CDnaDistance::GetTarget () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 56 of file dnadistance.hpp.
{ return m_strTarget; }
References m_strTarget.
GetValue()
double dynadjust::measurements::CDnaDistance::GetValue () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 57 of file dnadistance.hpp.
{ return m_dValue; }
References m_dValue.
GetStdDev()
double dynadjust::measurements::CDnaDistance::GetStdDev () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 58 of file dnadistance.hpp.
{ return m_dStdDev; }
References m_dStdDev.
GetInstrHeight()
float dynadjust::measurements::CDnaDistance::GetInstrHeight () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 59 of file dnadistance.hpp.
{ return m_fInstHeight; }
References m_fInstHeight.
GetTargetHeight()
float dynadjust::measurements::CDnaDistance::GetTargetHeight () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 60 of file dnadistance.hpp.
{ return m_fTargHeight; }
References m_fTargHeight.
SetTarget()
void dynadjust::measurements::CDnaDistance::SetTarget (const std::string & str) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 63 of file dnadistance.hpp.
{ m_strTarget = trimstr(str); }
References m_strTarget, and trimstr().
SetValue()
void dynadjust::measurements::CDnaDistance::SetValue (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 319 of file dnadistance.cpp.
{
    DoubleFromString(m_dValue, trimstr(str));
}
References DoubleFromString(), m_dValue, and trimstr().
SetStdDev()
void dynadjust::measurements::CDnaDistance::SetStdDev (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 324 of file dnadistance.cpp.
{
    DoubleFromString(m_dStdDev, trimstr(str));
}
References DoubleFromString(), m_dStdDev, and trimstr().
SetInstrumentHeight()
void dynadjust::measurements::CDnaDistance::SetInstrumentHeight (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 334 of file dnadistance.cpp.
{
    FloatFromString(m_fInstHeight, trimstr(str));
}
References FloatFromString(), m_fInstHeight, and trimstr().
SetTargetHeight()
void dynadjust::measurements::CDnaDistance::SetTargetHeight (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 339 of file dnadistance.cpp.
{
    DoubleFromString(m_fTargHeight, trimstr(str));
}
References DoubleFromString(), m_fTargHeight, and trimstr().
CalcBinaryRecordCount()
virtual UINT32 dynadjust::measurements::CDnaDistance::CalcBinaryRecordCount () const inline virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 69 of file dnadistance.hpp.
{ return 1; }
WriteBinaryMsr()
void dynadjust::measurements::CDnaDistance::WriteBinaryMsr (std::ofstream * binary_stream, PUINT32 msrIndex) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 293 of file dnadistance.cpp.
{
    measurement_t measRecord;
    measRecord.measType = GetTypeC();
    measRecord.measStart = xMeas;
    measRecord.ignore = m_bIgnore;
    measRecord.station1 = m_lstn1Index;
    measRecord.station2 = m_lstn2Index;
    measRecord.measAdj = m_measAdj;
    measRecord.measCorr = m_measCorr;
    measRecord.measAdjPrec = m_measAdjPrec;
    measRecord.residualPrec = m_residualPrec;
    measRecord.preAdjCorr = m_preAdjCorr;
    measRecord.term1 = m_dValue;
    measRecord.term2 = m_dStdDev * m_dStdDev; // convert to variance
    measRecord.term3 = m_fInstHeight;
    measRecord.term4 = m_fTargHeight;
    measRecord.measurementStations = m_MSmeasurementStations;
    measRecord.fileOrder = ((*msrIndex)++);
    snprintf(measRecord.epoch, sizeof(measRecord.epoch), "%s", m_epoch.substr(0, STN_EPOCH_WIDTH).c_str());
    binary_stream->write(reinterpret_cast<char *>(&measRecord), sizeof(measurement_t));
}
References dynadjust::measurements::msr_t::epoch, dynadjust::measurements::msr_t::fileOrder, dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::msr_t::ignore, dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::msr_t::measAdj, dynadjust::measurements::msr_t::measAdjPrec, dynadjust::measurements::msr_t::measCorr, dynadjust::measurements::msr_t::measStart, dynadjust::measurements::msr_t::measType, dynadjust::measurements::msr_t::measurementStations, dynadjust::measurements::msr_t::preAdjCorr, dynadjust::measurements::msr_t::residualPrec, dynadjust::measurements::msr_t::station1, dynadjust::measurements::msr_t::station2, STN_EPOCH_WIDTH(), dynadjust::measurements::msr_t::term1, dynadjust::measurements::msr_t::term2, dynadjust::measurements::msr_t::term3, dynadjust::measurements::msr_t::term4, and xMeas.
SetMeasurementRec()
UINT32 dynadjust::measurements::CDnaDistance::SetMeasurementRec (const vstn_t & binaryStn, it_vmsr_t & it_msr, it_vdbid_t & dbidmap) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 255 of file dnadistance.cpp.
{
    m_bIgnore = it_msr->ignore;
    m_MSmeasurementStations = (MEASUREMENT_STATIONS)it_msr->measurementStations;
    m_strType = it_msr->measType;
    // first station
    m_lstn1Index = it_msr->station1;
    m_strFirst = binaryStn.at(it_msr->station1).stationName;
    if (GetTypeC() == 'S')      // slope distance
    {
        // inst and targ heights
        m_fInstHeight = static_cast<float> (it_msr->term3);
        m_fTargHeight = static_cast<float> (it_msr->term4);
    }
    // target station
    m_lstn2Index = it_msr->station2;
    m_strTarget = binaryStn.at(it_msr->station2).stationName;
    m_measAdj = it_msr->measAdj;
    m_measCorr = it_msr->measCorr;
    m_measAdjPrec = it_msr->measAdjPrec;
    m_residualPrec = it_msr->residualPrec;
    m_preAdjCorr = it_msr->preAdjCorr;
    m_dValue = it_msr->term1;
    m_dStdDev = sqrt(it_msr->term2);
    m_epoch = it_msr->epoch;
    CDnaMeasurement::SetDatabaseMap(*dbidmap);
    return 0;
}
References dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, and dynadjust::measurements::CDnaMeasurement::SetDatabaseMap().
WriteDynaMLMsr()
void dynadjust::measurements::CDnaDistance::WriteDynaMLMsr (std::ofstream * dynaml_stream, const std::string & comment, bool) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 92 of file dnadistance.cpp.
{
    if (comment.empty())
        *dynaml_stream << "  <!-- Type " << measurement_name<char, std::string>(GetTypeC()) << " -->" << std::endl;
    else
        *dynaml_stream << "  <!-- " << comment << " -->" << std::endl;
    *dynaml_stream << "  <DnaMeasurement>" << std::endl;
    *dynaml_stream << "    <Type>" << m_strType << "</Type>" << std::endl;
    // Source file from which the measurement came
    *dynaml_stream << "    <Source>" << m_sourceFile << "</Source>" << std::endl;
    if (m_bIgnore)
        *dynaml_stream << "    <Ignore>*</Ignore>" << std::endl;
    else
        *dynaml_stream << "    <Ignore/>" << std::endl;
    if (m_epoch.empty())
        *dynaml_stream << "    <Epoch/>" << std::endl;
    else
        *dynaml_stream << "    <Epoch>" << m_epoch << "</Epoch>" << std::endl;
    *dynaml_stream << "    <First>" << m_strFirst << "</First>" << std::endl;
    *dynaml_stream << "    <Second>" << m_strTarget << "</Second>" << std::endl;
    *dynaml_stream << "    <Value>" << std::fixed << std::setprecision(4) << m_dValue << "</Value>" << std::endl;
    *dynaml_stream << "    <StdDev>" << std::fixed << std::setprecision(4) << m_dStdDev << "</StdDev>" << std::endl;
    switch (GetTypeC())
    {
    case 'S':
        *dynaml_stream << "    <InstHeight>" << std::fixed << std::setprecision(3) << m_fInstHeight << "</InstHeight>" << std::endl;
        *dynaml_stream << "    <TargHeight>" << std::fixed << std::setprecision(3) << m_fTargHeight << "</TargHeight>" << std::endl;
        break;
    }
    if (m_msr_db_map.is_msr_id_set)
        *dynaml_stream << "    <MeasurementID>" << m_msr_db_map.msr_id << "</MeasurementID>" << std::endl;
    *dynaml_stream << "  </DnaMeasurement>" << std::endl;
}
References dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_sourceFile, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, and dynadjust::measurements::measurement_name().
WriteDNAMsr()
void dynadjust::measurements::CDnaDistance::WriteDNAMsr (std::ofstream * dna_stream, const dna_msr_fields & dmw, const dna_msr_fields & dml, bool) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 133 of file dnadistance.cpp.
{
    *dna_stream << std::setw(dmw.msr_type) << m_strType;
    if (m_bIgnore)
        *dna_stream << std::setw(dmw.msr_ignore) << "*";
    else
        *dna_stream << std::setw(dmw.msr_ignore) << " ";
    *dna_stream << std::left << std::setw(dmw.msr_inst) << m_strFirst;
    *dna_stream << std::left << std::setw(dmw.msr_targ1) << m_strTarget;
    *dna_stream << std::setw(dmw.msr_targ2) << " ";
    *dna_stream << std::right << std::setw(dmw.msr_linear) << std::fixed << std::setprecision(4) << m_dValue;
    *dna_stream << std::setw(dmw.msr_ang_d + dmw.msr_ang_m + dmw.msr_ang_s) << " ";
    UINT32 m_stdDevPrec(3);
    *dna_stream << std::setw(dmw.msr_stddev) << StringFromTW(m_dStdDev, dmw.msr_stddev, m_stdDevPrec);
    //*dna_stream << std::setw(dmw.msr_stddev) << std::fixed << std::setprecision(3) << m_dStdDev;
    // database id width
    UINT32 width(dml.msr_gps_epoch - dml.msr_inst_ht);
    // Slope distance
    switch (GetTypeC())
    {
    case 'S':
        *dna_stream << std::setw(dmw.msr_inst_ht) << std::fixed << std::setprecision(3) << m_fInstHeight;
        *dna_stream << std::setw(dmw.msr_targ_ht) << std::fixed << std::setprecision(3) << m_fTargHeight;
        width = dml.msr_gps_epoch - dml.msr_targ_ht - dmw.msr_targ_ht;
        break;
    }
    *dna_stream << std::setw(width) << " ";
    *dna_stream << std::setw(dmw.msr_gps_epoch) << m_epoch;
    if (m_msr_db_map.is_msr_id_set)
        *dna_stream << std::setw(dmw.msr_id_msr) << m_msr_db_map.msr_id;
    *dna_stream << std::endl;
}
References dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, dna_msr_fields::msr_ang_d, dna_msr_fields::msr_ang_m, dna_msr_fields::msr_ang_s, dna_msr_fields::msr_gps_epoch, dna_msr_fields::msr_id_msr, dna_msr_fields::msr_ignore, dna_msr_fields::msr_inst, dna_msr_fields::msr_inst_ht, dna_msr_fields::msr_linear, dna_msr_fields::msr_stddev, dna_msr_fields::msr_targ1, dna_msr_fields::msr_targ2, dna_msr_fields::msr_targ_ht, dna_msr_fields::msr_type, and StringFromTW().
SimulateMsr()
void dynadjust::measurements::CDnaDistance::SimulateMsr (vdnaStnPtr * vStations, const CDnaEllipsoid * ellipsoid) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 174 of file dnadistance.cpp.
{
    double dX, dY, dZ;
    double dXih, dYih, dZih, dXth, dYth, dZth;
    _it_vdnastnptr stn1_it(vStations->begin() + m_lstn1Index);
    _it_vdnastnptr stn2_it(vStations->begin() + m_lstn2Index);
    m_fInstHeight = float(0.000);
    m_fTargHeight = float(0.000);
    switch (GetTypeC())
    {
    case 'S':
        CartesianElementsFromInstrumentHeight<double>(m_fInstHeight,              // instrument height
            &dXih, &dYih, &dZih,
            stn1_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentLongitude());
        CartesianElementsFromInstrumentHeight<double>(m_fTargHeight,              // target height
            &dXth, &dYth, &dZth,
            stn1_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentLongitude());
        dX = (stn2_it->get()->GetXAxis() - stn1_it->get()->GetXAxis() + dXth - dXih);
        dY = (stn2_it->get()->GetYAxis() - stn1_it->get()->GetYAxis() + dYth - dYih);
        dZ = (stn2_it->get()->GetZAxis() - stn1_it->get()->GetZAxis() + dZth - dZih);
        m_dValue = magnitude(dX, dY, dZ);
        break;
    case 'C':
        m_dValue = EllipsoidChordDistance<double>(
            stn1_it->get()->GetXAxis(),
            stn1_it->get()->GetYAxis(),
            stn1_it->get()->GetZAxis(),
            stn2_it->get()->GetXAxis(),
            stn2_it->get()->GetYAxis(),
            stn2_it->get()->GetZAxis(),
            stn1_it->get()->GetcurrentLatitude(),
            stn2_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentHeight(),
            stn2_it->get()->GetcurrentHeight(),
            &dX, &dY, &dZ, ellipsoid);
        break;
    case 'E':
        m_dValue = EllipsoidArcDistance<double>(
            stn1_it->get()->GetXAxis(),
            stn1_it->get()->GetYAxis(),
            stn1_it->get()->GetZAxis(),
            stn2_it->get()->GetXAxis(),
            stn2_it->get()->GetYAxis(),
            stn2_it->get()->GetZAxis(),
            stn1_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentLongitude(),
            stn2_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentHeight(),
            stn2_it->get()->GetcurrentHeight(),
            ellipsoid);
        break;
    case 'M':
        m_dValue = MSLArcDistance<double>(
            stn1_it->get()->GetXAxis(),
            stn1_it->get()->GetYAxis(),
            stn1_it->get()->GetZAxis(),
            stn2_it->get()->GetXAxis(),
            stn2_it->get()->GetYAxis(),
            stn2_it->get()->GetZAxis(),
            stn1_it->get()->GetcurrentLatitude(),
            stn2_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentHeight(),
            stn2_it->get()->GetcurrentHeight(),
            stn1_it->get()->GetgeoidSep(),
            stn2_it->get()->GetgeoidSep(),
            ellipsoid);
        break;
    }
    m_dStdDev = 3.0 * sqrt(m_dValue / 1000.0) / 100.0;
    m_epoch = "01.10.1985";
}
References CartesianElementsFromInstrumentHeight(), EllipsoidArcDistance(), EllipsoidChordDistance(), dynadjust::measurements::CDnaMeasurement::GetTypeC(), m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, magnitude(), and MSLArcDistance().
Member Data Documentation
m_strTarget
std::string dynadjust::measurements::CDnaDistance::m_strTarget protected
Definition at line 77 of file dnadistance.hpp.
Referenced by CDnaDistance(), GetTarget(), operator<(), operator==(), SetMeasurementRec(), SetTarget(), WriteDNAMsr(), and WriteDynaMLMsr().
m_dValue
double dynadjust::measurements::CDnaDistance::m_dValue protected
Definition at line 78 of file dnadistance.hpp.
Referenced by CDnaDistance(), GetValue(), operator<(), operator==(), SetMeasurementRec(), SetValue(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_dStdDev
double dynadjust::measurements::CDnaDistance::m_dStdDev protected
Definition at line 79 of file dnadistance.hpp.
Referenced by CDnaDistance(), GetStdDev(), operator<(), operator==(), SetMeasurementRec(), SetStdDev(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_fInstHeight
float dynadjust::measurements::CDnaDistance::m_fInstHeight protected
Definition at line 80 of file dnadistance.hpp.
Referenced by CDnaDistance(), GetInstrHeight(), operator<(), operator==(), SetInstrumentHeight(), SetMeasurementRec(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_fTargHeight
float dynadjust::measurements::CDnaDistance::m_fTargHeight protected
Definition at line 81 of file dnadistance.hpp.
Referenced by CDnaDistance(), GetTargetHeight(), operator<(), operator==(), SetMeasurementRec(), SetTargetHeight(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
The documentation for this class was generated from the following files:
include/measurement_types/dnadistance.hpp
include/measurement_types/dnadistance.cpp