DynAdjust: dynadjust::exception::RefTranException Class Reference
dynadjust::exception::RefTranException Class Reference
#include <dnaexception.hpp>
Public Member Functions
RefTranException (const std::string &what, size_t exception_type=REFTRAN_EXCEPTION_RAISED)
virtual const char * what () const throw ()
virtual const size_t exception_type () const throw ()
virtual ~RefTranException () throw ()
Private Attributes
std::string what_
size_t exception_type_
Detailed Description
Definition at line 170 of file dnaexception.hpp.
Constructor & Destructor Documentation
RefTranException()
dynadjust::exception::RefTranException::RefTranException (const std::string & what, size_t exception_type = REFTRAN_EXCEPTION_RAISED) inline explicit
Definition at line 173 of file dnaexception.hpp.
        : what_(what)
        , exception_type_(exception_type) {}
References exception_type(), exception_type_, REFTRAN_EXCEPTION_RAISED, what(), and what_.
~RefTranException()
virtual dynadjust::exception::RefTranException::~RefTranException () throw () inline virtual
Definition at line 178 of file dnaexception.hpp.
{}
Member Function Documentation
what()
virtual const char * dynadjust::exception::RefTranException::what () const throw () inline virtual
Definition at line 176 of file dnaexception.hpp.
{ return what_.c_str(); }
References what_.
Referenced by dynadjust::referenceframe::dna_reftran::ApplyMeasurementFrameSubstitutions(), dynadjust::referenceframe::dna_reftran::ApplyStationFrameSubstitutions(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), RefTranException(), and dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel().
exception_type()
virtual const size_t dynadjust::exception::RefTranException::exception_type () const throw () inline virtual
Definition at line 177 of file dnaexception.hpp.
{ return exception_type_; }
References exception_type_.
Referenced by dynadjust::referenceframe::dna_reftran::ApplyMeasurementFrameSubstitutions(), dynadjust::referenceframe::dna_reftran::ApplyStationFrameSubstitutions(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), RefTranException(), and dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel().
Member Data Documentation
what_
std::string dynadjust::exception::RefTranException::what_ private
Definition at line 181 of file dnaexception.hpp.
Referenced by RefTranException(), and what().
exception_type_
size_t dynadjust::exception::RefTranException::exception_type_ private
Definition at line 182 of file dnaexception.hpp.
Referenced by exception_type(), and RefTranException().
The documentation for this class was generated from the following file:
include/exception/dnaexception.hpp