DynAdjust: GeoidModel_pskel Class Reference
GeoidModel_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void NValue (const ::std::string &)
virtual void DeflPM (const ::std::string &)
virtual void DeflPV (const ::std::string &)
virtual void post_GeoidModel ()
void NValue_parser (::xml_schema::string_pskel &)
void DeflPM_parser (::xml_schema::string_pskel &)
void DeflPV_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &)
GeoidModel_pskel ()
Protected Member Functions
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * NValue_parser_
::xml_schema::string_pskel * DeflPM_parser_
::xml_schema::string_pskel * DeflPV_parser_
Detailed Description
Definition at line 1202 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
GeoidModel_pskel()
GeoidModel_pskel::GeoidModel_pskel ()
Definition at line 855 of file dnaparser_pskel.cxx.
    : NValue_parser_ (0),
    DeflPM_parser_ (0),
    DeflPV_parser_ (0)
{
}
References DeflPM_parser_, DeflPV_parser_, and NValue_parser_.
Member Function Documentation
NValue()
void GeoidModel_pskel::NValue (const ::std::string &) virtual
Reimplemented in GeoidModel_pimpl.
Definition at line 3097 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
DeflPM()
void GeoidModel_pskel::DeflPM (const ::std::string &) virtual
Reimplemented in GeoidModel_pimpl.
Definition at line 3101 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
DeflPV()
void GeoidModel_pskel::DeflPV (const ::std::string &) virtual
Reimplemented in GeoidModel_pimpl.
Definition at line 3105 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
post_GeoidModel()
void GeoidModel_pskel::post_GeoidModel () virtual
Reimplemented in GeoidModel_pimpl.
Definition at line 3109 of file dnaparser_pskel.cxx.
{
}
NValue_parser()
void GeoidModel_pskel::NValue_parser (::xml_schema::string_pskel & p)
Definition at line 831 of file dnaparser_pskel.cxx.
{
    this->NValue_parser_ = &p;
}
References NValue_parser_.
DeflPM_parser()
void GeoidModel_pskel::DeflPM_parser (::xml_schema::string_pskel & p)
Definition at line 836 of file dnaparser_pskel.cxx.
{
    this->DeflPM_parser_ = &p;
}
References DeflPM_parser_.
DeflPV_parser()
void GeoidModel_pskel::DeflPV_parser (::xml_schema::string_pskel & p)
Definition at line 841 of file dnaparser_pskel.cxx.
{
    this->DeflPV_parser_ = &p;
}
References DeflPV_parser_.
parsers()
void GeoidModel_pskel::parsers (::xml_schema::string_pskel & NValue, ::xml_schema::string_pskel & DeflPM, ::xml_schema::string_pskel & DeflPV)
Definition at line 846 of file dnaparser_pskel.cxx.
{
    this->NValue_parser_ = &NValue;
    this->DeflPM_parser_ = &DeflPM;
    this->DeflPV_parser_ = &DeflPV;
}
References DeflPM(), DeflPM_parser_, DeflPV(), DeflPV_parser_, NValue(), and NValue_parser_.
_start_element_impl()
bool GeoidModel_pskel::_start_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string * t) protected virtual
Definition at line 3113 of file dnaparser_pskel.cxx.
{
    XSD_UNUSED (t);
    if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
        return true;
    if (n == "NValue" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->NValue_parser_;
        if (this->NValue_parser_)
            this->NValue_parser_->pre ();
        return true;
    }
    if (n == "DeflPM" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->DeflPM_parser_;
        if (this->DeflPM_parser_)
            this->DeflPM_parser_->pre ();
        return true;
    }
    if (n == "DeflPV" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->DeflPV_parser_;
        if (this->DeflPV_parser_)
            this->DeflPV_parser_->pre ();
        return true;
    }
    return false;
}
References DeflPM_parser_, DeflPV_parser_, and NValue_parser_.
_end_element_impl()
bool GeoidModel_pskel::_end_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n) protected virtual
Definition at line 3155 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
        return true;
    if (n == "NValue" && ns.empty ())
    {
        if (this->NValue_parser_)
            this->NValue (this->NValue_parser_->post_string ());
        return true;
    }
    if (n == "DeflPM" && ns.empty ())
    {
        if (this->DeflPM_parser_)
            this->DeflPM (this->DeflPM_parser_->post_string ());
        return true;
    }
    if (n == "DeflPV" && ns.empty ())
    {
        if (this->DeflPV_parser_)
            this->DeflPV (this->DeflPV_parser_->post_string ());
        return true;
    }
    return false;
}
References DeflPM(), DeflPM_parser_, DeflPV(), DeflPV_parser_, NValue(), and NValue_parser_.
Member Data Documentation
NValue_parser_
::xml_schema::string_pskel* GeoidModel_pskel::NValue_parser_ protected
Definition at line 1238 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GeoidModel_pskel(), NValue_parser(), and parsers().
DeflPM_parser_
::xml_schema::string_pskel* GeoidModel_pskel::DeflPM_parser_ protected
Definition at line 1239 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DeflPM_parser(), GeoidModel_pskel(), and parsers().
DeflPV_parser_
::xml_schema::string_pskel* GeoidModel_pskel::DeflPV_parser_ protected
Definition at line 1240 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DeflPV_parser(), GeoidModel_pskel(), and parsers().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx