DynAdjust: ComparePairSecond< T > Class Template Reference
ComparePairSecond< T > Class Template Reference
#include <dnatemplatefuncs.hpp>
Public Member Functions
bool operator() (const std::pair< T, T > &lhs, const std::pair< T, T > &rhs) const
bool operator() (const std::pair< T, T > &lhs, const T &rhs)
bool operator() (const T &lhs, const std::pair< T, T > &rhs)
Private Member Functions
bool pair_secondless (const T &s1, const T &s2) const
Detailed Description
template<typename T>
class ComparePairSecond< T >
Definition at line 1821 of file dnatemplatefuncs.hpp.
Member Function Documentation
operator()() [1/3]
template<typename T> bool ComparePairSecond< T >::operator() (const std::pair< T, T > & lhs, const std::pair< T, T > & rhs) const inline
Definition at line 1824 of file dnatemplatefuncs.hpp.
{
        return pair_secondless(lhs.second, rhs.second);
    }
References pair_secondless().
operator()() [2/3]
template<typename T> bool ComparePairSecond< T >::operator() (const std::pair< T, T > & lhs, const T & rhs) inline
Definition at line 1827 of file dnatemplatefuncs.hpp.
{
        return pair_secondless(lhs.second, rhs);
    }
References pair_secondless().
operator()() [3/3]
template<typename T> bool ComparePairSecond< T >::operator() (const T & lhs, const std::pair< T, T > & rhs) inline
Definition at line 1830 of file dnatemplatefuncs.hpp.
{
        return pair_secondless(lhs, rhs.second);
    }
References pair_secondless().
pair_secondless()
template<typename T> bool ComparePairSecond< T >::pair_secondless (const T & s1, const T & s2) const inline private
Definition at line 1834 of file dnatemplatefuncs.hpp.
{
        return s1 < s2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this class was generated from the following file:
include/functions/dnatemplatefuncs.hpp