DynAdjust: CInputCoords Class Reference
CInputCoords Class Reference
#include <InputCoords.h>
Public Types
enum { IDD = IDD_INPUT_COORD }
Public Member Functions
CInputCoords (CWnd *pParent=NULL)
virtual ~CInputCoords ()
double GetLatitudeInput () const
double GetLongitudeInput () const
int GetDMS () const
void SetNValue (const double &d)
void SetPMeridian (const double &d)
void SetPVertical (const double &d)
void SetSuccess (bool b)
afx_msg void OnEnKillfocusLat ()
afx_msg void OnEnSetfocusLat ()
afx_msg void OnEnKillfocusLong ()
afx_msg void OnEnSetfocusLong ()
afx_msg void OnBnClickedInterpolate ()
afx_msg void OnBnClickedDmmss ()
afx_msg void OnBnClickedDdddd ()
afx_msg LRESULT OnUpdateInterpolationResults (WPARAM wParam, LPARAM lParam=0)
afx_msg void OnBnClickedEllipsOrtho2 ()
afx_msg void OnBnClickedOrthoEllips2 ()
Public Attributes
CString m_strHeight
CString m_strLatitude
CString m_strLongitude
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX)
virtual BOOL OnInitDialog ()
CString AddSymbology (CString strNumber, bool bLatisPosSouth, int iFlag)
Protected Attributes
int m_iDMS
int m_iEllipsoidtoOrthoRadio
double m_lfLatitude
double m_lfLongitude
double m_lfHeight
double m_lfHeight2
double m_lfNvalue
double m_lfPmeridian
double m_lfPvertical
bool m_bInterpolateSuccess
Detailed Description
Definition at line 17 of file InputCoords.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
IDD
Definition at line 36 of file InputCoords.h.
{ IDD = IDD_INPUT_COORD };
Constructor & Destructor Documentation
CInputCoords()
CInputCoords::CInputCoords (CWnd * pParent = NULL)
Definition at line 14 of file InputCoords.cpp.
    : CDialog(CInputCoords::IDD, pParent)
    , m_strLatitude(_T("-12.3056"))
    , m_strLongitude(_T("130.5031"))
    , m_strHeight(_T("0"))
    , m_lfLatitude(-12.3056)
    , m_lfLongitude(130.5031)
    , m_lfHeight(0.)
    , m_iDMS(DMS)
    , m_iEllipsoidtoOrthoRadio(0)
    , m_bInterpolateSuccess(false)
{
}
References CInputCoords(), DMS, IDD, m_bInterpolateSuccess, m_iDMS, m_iEllipsoidtoOrthoRadio, m_lfHeight, m_lfLatitude, m_lfLongitude, m_strHeight, m_strLatitude, and m_strLongitude.
Referenced by CInputCoords(), and OnInitDialog().
~CInputCoords()
CInputCoords::~CInputCoords () virtual
Definition at line 32 of file InputCoords.cpp.
{
}
Member Function Documentation
GetLatitudeInput()
double CInputCoords::GetLatitudeInput () const inline
Definition at line 25 of file InputCoords.h.
{ return m_lfLatitude; }
References m_lfLatitude.
GetLongitudeInput()
double CInputCoords::GetLongitudeInput () const inline
Definition at line 26 of file InputCoords.h.
{ return m_lfLongitude; }
References m_lfLongitude.
GetDMS()
int CInputCoords::GetDMS () const inline
Definition at line 27 of file InputCoords.h.
{ return m_iDMS; }
References m_iDMS.
SetNValue()
void CInputCoords::SetNValue (const double & d) inline
Definition at line 29 of file InputCoords.h.
{ m_lfNvalue = d; }
References m_lfNvalue.
SetPMeridian()
void CInputCoords::SetPMeridian (const double & d) inline
Definition at line 30 of file InputCoords.h.
{ m_lfPmeridian = d; }
References m_lfPmeridian.
SetPVertical()
void CInputCoords::SetPVertical (const double & d) inline
Definition at line 31 of file InputCoords.h.
{ m_lfPvertical = d; }
References m_lfPvertical.
SetSuccess()
void CInputCoords::SetSuccess (bool b) inline
Definition at line 33 of file InputCoords.h.
{ m_bInterpolateSuccess = b; }
References m_bInterpolateSuccess.
DoDataExchange()
void CInputCoords::DoDataExchange (CDataExchange * pDX) protected virtual
Definition at line 36 of file InputCoords.cpp.
{
    CDialog::DoDataExchange(pDX);
    int ht = 0;
    DDX_Text(pDX, IDC_LAT, m_strLatitude);
    DDX_Text(pDX, IDC_LONG, m_strLongitude);
    DDX_Text(pDX, IDC_HT1, m_strHeight);
    DDX_Radio(pDX, IDC_DMMSS, m_iDMS);
    DDX_Radio(pDX, IDC_ELLIPS_ORTHO2, ht);
}
References IDC_DMMSS, IDC_ELLIPS_ORTHO2, IDC_HT1, IDC_LAT, IDC_LONG, m_iDMS, m_strHeight, m_strLatitude, and m_strLongitude.
OnInitDialog()
BOOL CInputCoords::OnInitDialog () protected virtual
Definition at line 65 of file InputCoords.cpp.
{
    CDialog::OnInitDialog();
    OnEnKillfocusLong();
    GotoDlgCtrl(GetDlgItem(IDC_LAT));
    GetDlgItem(IDC_HT1_LABEL)->SetWindowText("Height (h):");
    GetDlgItem(IDC_HT2_LABEL)->SetWindowText("Height (H):");
    CString title;
    title.LoadString(IDS_TT_INTERPOLATE_POINT_TITLE);
    SetWindowText(title);
    return TRUE;
}
References CInputCoords(), IDC_HT1_LABEL, IDC_HT2_LABEL, IDC_LAT, IDS_TT_INTERPOLATE_POINT_TITLE, OnEnKillfocusLong(), OnInitDialog(), and TRUE.
Referenced by OnInitDialog().
AddSymbology()
CString CInputCoords::AddSymbology (CString strNumber, bool bLatisPosSouth, int iFlag) protected
Definition at line 144 of file InputCoords.cpp.
{
    int precision, decimal;
    CString strBuf;
    strBuf = strNumber;
    decimal = strNumber.Find('.');
    //iFlag: (1) Lat/East Input, (2) Long/North Input, (3) Lat/East Output, (4) Long/North Output
    precision = strBuf.GetLength() - decimal - 1;
    if (m_iDMS == DMS)
    {
        // Add symbols for degrees minutes and seconds
        if (decimal > -1)
        {
            // found a decimal point!
            if (decimal == 0)               // decimal point at start, ie >>   .0123
            {
                strBuf.Insert(decimal, '0');
                decimal++;
            }
            strBuf.SetAt(decimal, ' ');
            strBuf.Insert(decimal, '');
            // add zero after "tens" minute or "tens" second value
            if ((iFlag == 1 || iFlag == 2) && (precision == 1 || precision == 3) )
            {
                strBuf += "0";
                precision++;
            }
            if (precision > 1)                      // add minute symbol
                strBuf.Insert((decimal+4), "\' ");
            if (precision > 3)
                strBuf.Insert((decimal+8), '"');
            if (precision > 4)
            {
                strBuf.SetAt((decimal+8), '.');
                strBuf += "\"";
            }
        }
        else
            strBuf += "";      // couldn't find a decimal point
    }
    else
    {
        // must be decimal degrees format...simply truncate value at required precision
        if (decimal == 0)
        {
            strBuf.Insert(decimal, '0');
            decimal++;
        }
        strBuf = strBuf.Mid(0, decimal + precision + 1);
        strBuf += "";
    }
    if (iFlag < 3 || iFlag > 2)
    {
        // Show North and South notation
        if (strNumber[0] == '-' || strNumber[0] == 's' || strNumber[0] == 'S' ||
            strNumber[0] == 'w' || strNumber[0] == 'W')
        {
            if (iFlag == 1 || iFlag == 3)   // input/output latitude
                strBuf.SetAt(0, 'S');
            else                            // input/output longitude
                strBuf.SetAt(0, 'W');
        }
        else
        {
            if (iFlag == 1 || iFlag == 3)
                strBuf = "N" + strBuf;
            else
                strBuf = "E" + strBuf;
        }
        strBuf = strBuf.Mid(0, 1) + " " + strBuf.Mid(1);
    }
    return strBuf;
}
References DMS, and m_iDMS.
Referenced by OnEnKillfocusLat(), OnEnKillfocusLong(), and OnUpdateInterpolationResults().
OnEnKillfocusLat()
void CInputCoords::OnEnKillfocusLat ()
Definition at line 83 of file InputCoords.cpp.
{
    GetDlgItem(IDC_LAT)->GetWindowText(m_strLatitude);
    m_strLatitude.Trim();
    if (m_strLatitude.IsEmpty())
        m_strLatitude = "0.";
    m_lfLatitude = atof(m_strLatitude);
    GetDlgItem(IDC_LAT)->SetWindowText(AddSymbology(m_strLatitude, true, 1));
}
References AddSymbology(), IDC_LAT, m_lfLatitude, and m_strLatitude.
Referenced by OnBnClickedDdddd(), and OnBnClickedDmmss().
OnEnSetfocusLat()
void CInputCoords::OnEnSetfocusLat ()
Definition at line 96 of file InputCoords.cpp.
{
    GetDlgItem(IDC_LAT)->SetWindowText(m_strLatitude);
    ((CEdit*)GetDlgItem(IDC_LAT))->SetSel(0, -1, FALSE);
}
References FALSE, IDC_LAT, and m_strLatitude.
Referenced by OnBnClickedDdddd(), OnBnClickedDmmss(), and OnBnClickedInterpolate().
OnEnKillfocusLong()
void CInputCoords::OnEnKillfocusLong ()
Definition at line 103 of file InputCoords.cpp.
{
    GetDlgItem(IDC_LONG)->GetWindowText(m_strLongitude);
    m_strLongitude.Trim();
    if (m_strLongitude.IsEmpty())
        m_strLongitude = "0.";
    m_lfLongitude = atof(m_strLongitude);
    GetDlgItem(IDC_LONG)->SetWindowText(AddSymbology(m_strLongitude, true, 2));
}
References AddSymbology(), IDC_LONG, m_lfLongitude, and m_strLongitude.
Referenced by OnBnClickedDdddd(), OnBnClickedDmmss(), and OnInitDialog().
OnEnSetfocusLong()
void CInputCoords::OnEnSetfocusLong ()
Definition at line 116 of file InputCoords.cpp.
{
    GetDlgItem(IDC_LONG)->SetWindowText(m_strLongitude);
    ((CEdit*)GetDlgItem(IDC_LONG))->SetSel(0, -1, FALSE);
}
References FALSE, IDC_LONG, and m_strLongitude.
Referenced by OnBnClickedDdddd(), and OnBnClickedDmmss().
OnBnClickedInterpolate()
void CInputCoords::OnBnClickedInterpolate ()
Definition at line 123 of file InputCoords.cpp.
{
    if (GetFocus()->GetDlgCtrlID() == IDC_LAT)
        GetDlgItem(IDC_LAT)->GetWindowText(m_strLatitude);
    if (GetFocus()->GetDlgCtrlID() == IDC_LONG)
        GetDlgItem(IDC_LONG)->GetWindowText(m_strLongitude);
    m_bInterpolateSuccess = false;
    m_lfLatitude = atof(m_strLatitude);
    m_lfLongitude = atof(m_strLongitude);
    GetDlgItem(IDC_HT1)->GetWindowText(m_strHeight);
    m_lfHeight = atof(m_strHeight);
    AfxGetMainWnd()->SendMessage(IDM_INTERACTIVE_INTERPOLATE, 0, 0);
    OnEnSetfocusLat();
    GotoDlgCtrl(GetDlgItem(IDC_LAT));
}
References IDC_HT1, IDC_LAT, IDC_LONG, IDM_INTERACTIVE_INTERPOLATE, m_bInterpolateSuccess, m_lfHeight, m_lfLatitude, m_lfLongitude, m_strHeight, m_strLatitude, m_strLongitude, and OnEnSetfocusLat().
OnBnClickedDmmss()
void CInputCoords::OnBnClickedDmmss ()
Definition at line 234 of file InputCoords.cpp.
{
    m_iDMS = DMS;
    OnEnSetfocusLat();
    OnEnKillfocusLat();
    OnEnSetfocusLong();
    OnEnKillfocusLong();
    GotoDlgCtrl(GetDlgItem(IDC_LAT));
}
References DMS, IDC_LAT, m_iDMS, OnEnKillfocusLat(), OnEnKillfocusLong(), OnEnSetfocusLat(), and OnEnSetfocusLong().
OnBnClickedDdddd()
void CInputCoords::OnBnClickedDdddd ()
Definition at line 244 of file InputCoords.cpp.
{
    m_iDMS = DDEG;
    OnEnSetfocusLat();
    OnEnKillfocusLat();
    OnEnSetfocusLong();
    OnEnKillfocusLong();
    GotoDlgCtrl(GetDlgItem(IDC_LAT));
}
References DDEG, IDC_LAT, m_iDMS, OnEnKillfocusLat(), OnEnKillfocusLong(), OnEnSetfocusLat(), and OnEnSetfocusLong().
OnUpdateInterpolationResults()
LRESULT CInputCoords::OnUpdateInterpolationResults (WPARAM wParam, LPARAM lParam = 0)
Definition at line 255 of file InputCoords.cpp.
{
    char buf[50];
    sprintf(buf, "%.3f", m_lfNvalue);
    GetDlgItem(IDC_N_VALUE)->SetWindowText(buf);
    sprintf(buf, "%.3f", m_lfPmeridian);
    GetDlgItem(IDC_DEFL_PMERIDIAN)->SetWindowText(buf);
    sprintf(buf, "%.3f", m_lfPvertical);
    GetDlgItem(IDC_DEFL_PVERTICAL)->SetWindowText(buf);
    // convert to decimal degrees
    if (m_iDMS == DMS)
    {
        m_lfLatitude = DmstoDeg(m_lfLatitude);
        m_lfLongitude = DmstoDeg(m_lfLongitude);
    }
    // Astronomic longitude
    m_lfLongitude +=  m_lfPvertical / 3600. / cos(Radians(m_lfLatitude));
    // Astronomic latitude correction
    m_lfLatitude += m_lfPmeridian / 3600.;
    if (m_iDMS == DMS)
    {
        m_lfLatitude = DegtoDms(m_lfLatitude);
        m_lfLongitude = DegtoDms(m_lfLongitude);
    }
    sprintf(buf, "%.9f", m_lfLatitude);
    GetDlgItem(IDC_LAT_OUT)->SetWindowText(AddSymbology(buf, true, 1));
    sprintf(buf, "%.9f", m_lfLongitude);
    GetDlgItem(IDC_LONG_OUT)->SetWindowText(AddSymbology(buf, true, 2));
    // Height
    if (m_iEllipsoidtoOrthoRadio == 0)
        m_lfHeight2 = m_lfHeight - m_lfNvalue;           // H = h - N
    else
        m_lfHeight2 = m_lfHeight + m_lfNvalue;           // h = H + N
    sprintf(buf, "%.3f", m_lfHeight2);
    GetDlgItem(IDC_HT2)->SetWindowText(buf);
    m_bInterpolateSuccess = true;
    return 0;
}
References AddSymbology(), DegtoDms(), DMS, DmstoDeg(), IDC_DEFL_PMERIDIAN, IDC_DEFL_PVERTICAL, IDC_HT2, IDC_LAT_OUT, IDC_LONG_OUT, IDC_N_VALUE, m_bInterpolateSuccess, m_iDMS, m_iEllipsoidtoOrthoRadio, m_lfHeight, m_lfHeight2, m_lfLatitude, m_lfLongitude, m_lfNvalue, m_lfPmeridian, m_lfPvertical, and Radians().
OnBnClickedEllipsOrtho2()
void CInputCoords::OnBnClickedEllipsOrtho2 ()
Definition at line 305 of file InputCoords.cpp.
{
    m_iEllipsoidtoOrthoRadio = 0;
    GetDlgItem(IDC_HT1_LABEL)->SetWindowText("Height (h):");
    GetDlgItem(IDC_HT2_LABEL)->SetWindowText("Height (H):");
    if (m_bInterpolateSuccess)
    {
        m_lfHeight2 = m_lfHeight - m_lfNvalue;
        char cbuf[16];
        sprintf(cbuf, "%.3f", m_lfHeight2);
        GetDlgItem(IDC_HT2)->SetWindowText(cbuf);
    }
}
References IDC_HT1_LABEL, IDC_HT2, IDC_HT2_LABEL, m_bInterpolateSuccess, m_iEllipsoidtoOrthoRadio, m_lfHeight, m_lfHeight2, and m_lfNvalue.
OnBnClickedOrthoEllips2()
void CInputCoords::OnBnClickedOrthoEllips2 ()
Definition at line 322 of file InputCoords.cpp.
{
    m_iEllipsoidtoOrthoRadio = 1;
    GetDlgItem(IDC_HT1_LABEL)->SetWindowText("Height (H):");
    GetDlgItem(IDC_HT2_LABEL)->SetWindowText("Height (h):");
    if (m_bInterpolateSuccess)
    {
        m_lfHeight2 = m_lfHeight + m_lfNvalue;
        char cbuf[16];
        sprintf(cbuf, "%.3f", m_lfHeight2);
        GetDlgItem(IDC_HT2)->SetWindowText(cbuf);
    }
}
References IDC_HT1_LABEL, IDC_HT2, IDC_HT2_LABEL, m_bInterpolateSuccess, m_iEllipsoidtoOrthoRadio, m_lfHeight, m_lfHeight2, and m_lfNvalue.
Member Data Documentation
m_iDMS
int CInputCoords::m_iDMS protected
Definition at line 43 of file InputCoords.h.
Referenced by AddSymbology(), CInputCoords(), DoDataExchange(), GetDMS(), OnBnClickedDdddd(), OnBnClickedDmmss(), and OnUpdateInterpolationResults().
m_iEllipsoidtoOrthoRadio
int CInputCoords::m_iEllipsoidtoOrthoRadio protected
Definition at line 44 of file InputCoords.h.
Referenced by CInputCoords(), OnBnClickedEllipsOrtho2(), OnBnClickedOrthoEllips2(), and OnUpdateInterpolationResults().
m_lfLatitude
double CInputCoords::m_lfLatitude protected
Definition at line 45 of file InputCoords.h.
Referenced by CInputCoords(), GetLatitudeInput(), OnBnClickedInterpolate(), OnEnKillfocusLat(), and OnUpdateInterpolationResults().
m_lfLongitude
double CInputCoords::m_lfLongitude protected
Definition at line 46 of file InputCoords.h.
Referenced by CInputCoords(), GetLongitudeInput(), OnBnClickedInterpolate(), OnEnKillfocusLong(), and OnUpdateInterpolationResults().
m_lfHeight
double CInputCoords::m_lfHeight protected
Definition at line 47 of file InputCoords.h.
Referenced by CInputCoords(), OnBnClickedEllipsOrtho2(), OnBnClickedInterpolate(), OnBnClickedOrthoEllips2(), and OnUpdateInterpolationResults().
m_lfHeight2
double CInputCoords::m_lfHeight2 protected
Definition at line 48 of file InputCoords.h.
Referenced by OnBnClickedEllipsOrtho2(), OnBnClickedOrthoEllips2(), and OnUpdateInterpolationResults().
m_lfNvalue
double CInputCoords::m_lfNvalue protected
Definition at line 49 of file InputCoords.h.
Referenced by OnBnClickedEllipsOrtho2(), OnBnClickedOrthoEllips2(), OnUpdateInterpolationResults(), and SetNValue().
m_lfPmeridian
double CInputCoords::m_lfPmeridian protected
Definition at line 50 of file InputCoords.h.
Referenced by OnUpdateInterpolationResults(), and SetPMeridian().
m_lfPvertical
double CInputCoords::m_lfPvertical protected
Definition at line 51 of file InputCoords.h.
Referenced by OnUpdateInterpolationResults(), and SetPVertical().
m_bInterpolateSuccess
bool CInputCoords::m_bInterpolateSuccess protected
Definition at line 53 of file InputCoords.h.
Referenced by CInputCoords(), OnBnClickedEllipsOrtho2(), OnBnClickedInterpolate(), OnBnClickedOrthoEllips2(), OnUpdateInterpolationResults(), and SetSuccess().
m_strHeight
CString CInputCoords::m_strHeight
Definition at line 57 of file InputCoords.h.
Referenced by CInputCoords(), DoDataExchange(), and OnBnClickedInterpolate().
m_strLatitude
CString CInputCoords::m_strLatitude
Definition at line 58 of file InputCoords.h.
Referenced by CInputCoords(), DoDataExchange(), OnBnClickedInterpolate(), OnEnKillfocusLat(), and OnEnSetfocusLat().
m_strLongitude
CString CInputCoords::m_strLongitude
Definition at line 59 of file InputCoords.h.
Referenced by CInputCoords(), DoDataExchange(), OnBnClickedInterpolate(), OnEnKillfocusLong(), and OnEnSetfocusLong().
The documentation for this class was generated from the following files:
dynadjust/dnageoidint/InputCoords.h
dynadjust/dnageoidint/InputCoords.cpp