DynAdjust: dynadjust::measurements::CDnaDirection Class Reference
dynadjust::measurements::CDnaDirection Class Reference
#include <dnadirection.hpp>
Public Member Functions
CDnaDirection (void)
virtual ~CDnaDirection (void)
CDnaDirection (CDnaDirection &&d)
CDnaDirection & operator= (CDnaDirection &&rhs)
bool operator== (const CDnaDirection &rhs) const
bool operator< (const CDnaDirection &rhs) const
std::string GetTarget () const
double GetValue () const
double GetStdDev () const
float GetInstrHeight () const
float GetTargetHeight () const
void SetRecordedTotal (const UINT32 &l)
void SetClusterID (const UINT32 &id)
void SetTarget (const std::string &str)
void SetValue (const std::string &str)
void SetStdDev (const std::string &str)
void SetInstrumentHeight (const std::string &str)
void SetTargetHeight (const std::string &str)
virtual UINT32 CalcBinaryRecordCount () const
virtual void WriteBinaryMsr (std::ofstream *binary_stream, PUINT32 msrIndex) const
virtual UINT32 SetMeasurementRec (const vstn_t &binaryStn, it_vmsr_t &it_msr, it_vdbid_t &dbidmap)
virtual void WriteDynaMLMsr (std::ofstream *dynaml_stream, const std::string &comment, bool bSubMeasurement=false) const
virtual void WriteDNAMsr (std::ofstream *dna_stream, const dna_msr_fields &dmw, const dna_msr_fields &dml, bool bSubMeasurement=false) const
virtual void SimulateMsr (vdnaStnPtr *vStations, const CDnaEllipsoid *ellipsoid)
Public Member Functions inherited from dynadjust::measurements::CDnaMeasurement
CDnaMeasurement ()
virtual ~CDnaMeasurement ()
CDnaMeasurement (CDnaMeasurement &&m)
CDnaMeasurement & operator= (CDnaMeasurement &&rhs)
std::string GetType () const
char GetTypeC () const
bool GetIgnore () const
bool NotIgnored () const
std::string GetFirst () const
MEASUREMENT_STATIONS GetMsrStnCount () const
std::string GetEpsg () const
std::string GetSource () const
bool GetInsufficient () const
void SetType (const std::string &str)
void SetIgnore (const bool bval)
void SetFirst (const std::string &str)
void SetEpsg (const std::string &e)
void SetSource (const std::string &source)
void SetInsufficient (const bool bval)
void SetMsrIndex (const UINT32 &order)
void SetStn1Index (const UINT32 &order)
void SetStn2Index (const UINT32 &order)
void SetStn3Index (const UINT32 &order)
UINT32 GetMsrIndex () const
UINT32 GetStn1Index () const
UINT32 GetStn2Index () const
UINT32 GetStn3Index () const
double GetMeasAdj () const
double GetMeasCorr () const
double GetMeasAdjPrec () const
double GetResidualPrec () const
double GetPreAdjCorr () const
virtual void PopulateMsr (pvstn_t, uint32_uint32_map *, vUINT32 *, const UINT32 &, const CDnaDatum *, math::matrix_2d *, math::matrix_2d *)
virtual UINT32 GetClusterID () const
virtual std::string GetCoordType () const
virtual double GetVscale () const
virtual double GetPscale () const
virtual double GetLscale () const
virtual double GetHscale () const
virtual std::string GetTarget2 () const
virtual UINT32 GetTotal () const
virtual std::string GetReferenceFrame () const
std::string GetEpoch () const
virtual std::vector< CDnaGpsBaseline > * GetBaselines_ptr ()
virtual std::vector< CDnaDirection > * GetDirections_ptr ()
virtual std::vector< CDnaGpsPoint > * GetPoints_ptr ()
virtual std::vector< CDnaCovariance > * GetCovariances_ptr ()
virtual void AddDirection (const CDnaMeasurement *)
virtual void AddGpsBaseline (const CDnaMeasurement *)
virtual void AddGpsPoint (const CDnaMeasurement *)
virtual void AddGpsCovariance (const CDnaCovariance *)
virtual void AddPointCovariance (const CDnaCovariance *)
virtual void ReserveDirectionsCount (const UINT32 &)
virtual void ReserveGpsBaselinesCount (const UINT32 &)
virtual void ReserveGpsPointsCount (const UINT32 &)
virtual void ReserveGpsCovariancesCount (const UINT32 &)
virtual void ResizeGpsCovariancesCount (const UINT32 &)
virtual void SetNonIgnoredDirns (const UINT32 &)
virtual void SetCoordType (const std::string &)
virtual void SetHscale (const std::string &)
virtual void SetHscale (const double &)
virtual void SetReferenceFrame (const std::string &)
void SetEpoch (const std::string &epoch)
virtual void SetLscale (const std::string &)
virtual void SetLscale (const double &)
virtual void SetPscale (const std::string &)
virtual void SetPscale (const double &)
virtual void SetSigmaXX (const std::string &)
virtual void SetSigmaXY (const std::string &)
virtual void SetSigmaXZ (const std::string &)
virtual void SetSigmaYY (const std::string &)
virtual void SetSigmaYZ (const std::string &)
virtual void SetSigmaZZ (const std::string &)
virtual void SetTarget2 (const std::string &)
virtual void SetTotal (const std::string &)
virtual void SetVscale (const std::string &)
virtual void SetVscale (const double &)
virtual void SetX (const std::string &)
virtual void SetY (const std::string &)
virtual void SetZ (const std::string &)
virtual void SetXAxis (const double &)
virtual void SetYAxis (const double &)
virtual void SetZAxis (const double &)
virtual void SetSigmaXX (const double &)
virtual void SetSigmaXY (const double &)
virtual void SetSigmaXZ (const double &)
virtual void SetSigmaYY (const double &)
virtual void SetSigmaYZ (const double &)
virtual void SetSigmaZZ (const double &)
virtual void SetTotal (const UINT32 &)
virtual void PreferGMeasurements ()
void SetMeasurementDBID (const std::string &str)
void SetClusterDBID (const std::string &str)
void SetClusterDBID (const UINT32 &u, bool s)
UINT32 GetClusterDBID ()
bool GetClusterDBIDset ()
void SetDatabaseMap (const msr_database_id_map &dbidmap)
virtual void SetDatabaseMaps (it_vdbid_t &it_dbidmap)
virtual void SerialiseDatabaseMap (std::ofstream *os)
Public Attributes
std::string m_strTarget
Public Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strFirst
MEASUREMENT_STATIONS m_MSmeasurementStations
Protected Attributes
double m_drValue
double m_dStdDev
float m_fInstHeight
float m_fTargHeight
UINT32 m_lRecordedTotal
UINT32 m_lsetID
Protected Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strType
bool m_bIgnore
UINT32 m_lmeasurementIndex
UINT32 m_lstn1Index
UINT32 m_lstn2Index
UINT32 m_lstn3Index
double m_measAdj
double m_measCorr
double m_measAdjPrec
double m_residualPrec
double m_preAdjCorr
std::string m_epsgCode
std::string m_sourceFile
std::string m_epoch
msr_database_id_map m_msr_db_map
bool m_bInsufficient
Additional Inherited Members
Protected Member Functions inherited from dynadjust::measurements::CDnaMeasurement
void coutMeasurement (std::ostream &os) const
Detailed Description
Definition at line 39 of file dnadirection.hpp.
Constructor & Destructor Documentation
CDnaDirection() [1/2]
dynadjust::measurements::CDnaDirection::CDnaDirection (void)
Definition at line 31 of file dnadirection.cpp.
    : m_strTarget("")
    , m_drValue(0.)
    , m_dStdDev(0.)
    , m_fInstHeight(0.)
    , m_fTargHeight(0.)
    , m_lRecordedTotal(0)
    , m_lsetID(0)
{
    m_strType = "D";
    m_MSmeasurementStations = TWO_STATION;
}
References m_drValue, m_dStdDev, m_fInstHeight, m_fTargHeight, m_lRecordedTotal, m_lsetID, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, and TWO_STATION.
Referenced by CDnaDirection(), operator<(), operator=(), and operator==().
~CDnaDirection()
dynadjust::measurements::CDnaDirection::~CDnaDirection (void) virtual
Definition at line 44 of file dnadirection.cpp.
{
}
CDnaDirection() [2/2]
dynadjust::measurements::CDnaDirection::CDnaDirection (CDnaDirection && d)
Definition at line 49 of file dnadirection.cpp.
{
    m_strFirst = d.m_strFirst;
    m_bIgnore = d.m_bIgnore;
    m_bInsufficient = d.m_bInsufficient;
    m_strTarget = d.m_strTarget;
    m_drValue = d.m_drValue;
    m_dStdDev = d.m_dStdDev;
    m_fInstHeight = d.m_fInstHeight;
    m_fTargHeight = d.m_fTargHeight;
    m_lRecordedTotal = d.m_lRecordedTotal;
    m_lsetID = d.m_lsetID;
    m_MSmeasurementStations = d.m_MSmeasurementStations;
    m_strType = "D";
    m_msr_db_map = d.m_msr_db_map;
    m_epoch = d.m_epoch;
}
References CDnaDirection(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, dynadjust::measurements::CDnaMeasurement::m_bInsufficient, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, m_lRecordedTotal, m_lsetID, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, and dynadjust::measurements::CDnaMeasurement::m_strType.
Member Function Documentation
operator=()
CDnaDirection & dynadjust::measurements::CDnaDirection::operator= (CDnaDirection && rhs)
Definition at line 71 of file dnadirection.cpp.
{
    // check for assignment to self!
    if (this == &rhs)
        return *this;
    CDnaMeasurement::operator=(std::move(rhs));
    m_bInsufficient = rhs.m_bInsufficient;
    m_strTarget = rhs.m_strTarget;
    m_drValue = rhs.m_drValue;
    m_dStdDev = rhs.m_dStdDev;
    m_fInstHeight = rhs.m_fInstHeight;
    m_fTargHeight = rhs.m_fTargHeight;
    m_lRecordedTotal = rhs.m_lRecordedTotal;
    m_lsetID = rhs.m_lsetID;
    m_MSmeasurementStations = rhs.m_MSmeasurementStations;
    m_msr_db_map = rhs.m_msr_db_map;
    return *this;
}
References CDnaDirection(), dynadjust::measurements::CDnaMeasurement::m_bInsufficient, m_drValue, m_dStdDev, m_fInstHeight, m_fTargHeight, m_lRecordedTotal, m_lsetID, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, m_strTarget, and dynadjust::measurements::CDnaMeasurement::operator=().
operator==()
bool dynadjust::measurements::CDnaDirection::operator== (const CDnaDirection & rhs) const
Definition at line 153 of file dnadirection.cpp.
{
    return (
        m_strFirst == rhs.m_strFirst &&
        m_bIgnore == rhs.m_bIgnore &&
        m_strTarget == rhs.m_strTarget &&
        m_drValue == rhs.m_drValue &&
        m_dStdDev == rhs.m_dStdDev &&
        m_strType == rhs.m_strType &&
        m_fInstHeight == rhs.m_fInstHeight &&
        m_fTargHeight == rhs.m_fTargHeight &&
        m_epoch == rhs.m_epoch
        );
}
References CDnaDirection(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, and dynadjust::measurements::CDnaMeasurement::m_strType.
operator<()
bool dynadjust::measurements::CDnaDirection::operator< (const CDnaDirection & rhs) const
Definition at line 169 of file dnadirection.cpp.
{
    if (m_strFirst == rhs.m_strFirst) {
        if (m_strType == rhs.m_strType) { // could be B, D, V, Z
            if (m_bIgnore == rhs.m_bIgnore) {
                if (m_epoch == rhs.m_epoch) {
                    if (m_strTarget == rhs.m_strTarget) {
                        if (m_drValue == rhs.m_drValue) {
                            if (m_dStdDev == rhs.m_dStdDev) {
                                if (m_fInstHeight == rhs.m_fInstHeight)
                                    return m_fTargHeight < rhs.m_fTargHeight;
                                else
                                    return m_fInstHeight < rhs.m_fInstHeight; }
                            else
                                return m_dStdDev < rhs.m_dStdDev; }
                        else
                            return m_drValue < rhs.m_drValue; }
                    else
                        return m_strTarget < rhs.m_strTarget; }
                else
                    return m_epoch < rhs.m_epoch; }
            else
                return m_bIgnore < rhs.m_bIgnore; }
        else
            return m_strType < rhs.m_strType; }
    else
        return m_strFirst < rhs.m_strFirst;
}
References CDnaDirection(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, and dynadjust::measurements::CDnaMeasurement::m_strType.
GetTarget()
std::string dynadjust::measurements::CDnaDirection::GetTarget () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 63 of file dnadirection.hpp.
{ return m_strTarget; }
References m_strTarget.
Referenced by FindMsrsConnectedToStns_D< U >::operator()().
GetValue()
double dynadjust::measurements::CDnaDirection::GetValue () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 64 of file dnadirection.hpp.
{ return m_drValue; }
References m_drValue.
GetStdDev()
double dynadjust::measurements::CDnaDirection::GetStdDev () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 65 of file dnadirection.hpp.
{ return m_dStdDev; }
References m_dStdDev.
GetInstrHeight()
float dynadjust::measurements::CDnaDirection::GetInstrHeight () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 66 of file dnadirection.hpp.
{ return m_fInstHeight; }
References m_fInstHeight.
GetTargetHeight()
float dynadjust::measurements::CDnaDirection::GetTargetHeight () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 67 of file dnadirection.hpp.
{ return m_fTargHeight; }
References m_fTargHeight.
SetRecordedTotal()
void dynadjust::measurements::CDnaDirection::SetRecordedTotal (const UINT32 & l) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 69 of file dnadirection.hpp.
{ m_lRecordedTotal = l; }
References m_lRecordedTotal.
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNAMSRDirections().
SetClusterID()
void dynadjust::measurements::CDnaDirection::SetClusterID (const UINT32 & id) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 70 of file dnadirection.hpp.
{ m_lsetID = id; }
References m_lsetID.
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNAMSRDirections().
SetTarget()
void dynadjust::measurements::CDnaDirection::SetTarget (const std::string & str) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 71 of file dnadirection.hpp.
{ m_strTarget = trimstr(str); }
References m_strTarget, and trimstr().
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNAMSRDirections().
SetValue()
void dynadjust::measurements::CDnaDirection::SetValue (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 661 of file dnadirection.cpp.
{
    RadFromDmsString(&m_drValue, trimstr(str));
}
References m_drValue, RadFromDmsString(), and trimstr().
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNAMSRDirections().
SetStdDev()
void dynadjust::measurements::CDnaDirection::SetStdDev (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 666 of file dnadirection.cpp.
{
    // convert seconds to radians
    RadFromSecondsString(&m_dStdDev, trimstr(str));
}
References m_dStdDev, RadFromSecondsString(), and trimstr().
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNAMSRDirections().
SetInstrumentHeight()
void dynadjust::measurements::CDnaDirection::SetInstrumentHeight (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 677 of file dnadirection.cpp.
{
    FloatFromString<float>(m_fInstHeight, trimstr(str));
}
References FloatFromString(), m_fInstHeight, and trimstr().
SetTargetHeight()
void dynadjust::measurements::CDnaDirection::SetTargetHeight (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 682 of file dnadirection.cpp.
{
    FloatFromString<float>(m_fTargHeight, trimstr(str));
}
References FloatFromString(), m_fTargHeight, and trimstr().
CalcBinaryRecordCount()
virtual UINT32 dynadjust::measurements::CDnaDirection::CalcBinaryRecordCount () const inline virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 77 of file dnadirection.hpp.
{ return 1; }
WriteBinaryMsr()
void dynadjust::measurements::CDnaDirection::WriteBinaryMsr (std::ofstream * binary_stream, PUINT32 msrIndex) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 609 of file dnadirection.cpp.
{
    measurement_t measRecord;
    measRecord.measType = GetTypeC();
    if (m_strType == "D")
        measRecord.measStart = yMeas;
    else
        measRecord.measStart = xMeas;
    measRecord.ignore = m_bIgnore;
    measRecord.station1 = m_lstn1Index;
    measRecord.station2 = m_lstn2Index;
    measRecord.measAdj = m_measAdj;
    measRecord.measCorr = m_measCorr;
    measRecord.measAdjPrec = m_measAdjPrec;
    measRecord.residualPrec = m_residualPrec;
    measRecord.preAdjCorr = m_preAdjCorr;
    measRecord.term1 = m_drValue;
    measRecord.term2 = m_dStdDev * m_dStdDev;    // convert to variance
    measRecord.term3 = m_fInstHeight;
    measRecord.term4 = m_fTargHeight;
    measRecord.clusterID = m_lsetID;
    // number of Directions in the parent cluster including the first
    measRecord.vectorCount1 = m_lRecordedTotal;
    measRecord.measurementStations = m_MSmeasurementStations;
    measRecord.fileOrder = ((*msrIndex)++);
    snprintf(measRecord.epoch, sizeof(measRecord.epoch), "%s", m_epoch.substr(0, STN_EPOCH_WIDTH).c_str());
    binary_stream->write(reinterpret_cast<char *>(&measRecord), sizeof(measurement_t));
}
References dynadjust::measurements::msr_t::clusterID, dynadjust::measurements::msr_t::epoch, dynadjust::measurements::msr_t::fileOrder, dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::msr_t::ignore, dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, m_lRecordedTotal, m_lsetID, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::CDnaMeasurement::m_strType, dynadjust::measurements::msr_t::measAdj, dynadjust::measurements::msr_t::measAdjPrec, dynadjust::measurements::msr_t::measCorr, dynadjust::measurements::msr_t::measStart, dynadjust::measurements::msr_t::measType, dynadjust::measurements::msr_t::measurementStations, dynadjust::measurements::msr_t::preAdjCorr, dynadjust::measurements::msr_t::residualPrec, dynadjust::measurements::msr_t::station1, dynadjust::measurements::msr_t::station2, STN_EPOCH_WIDTH(), dynadjust::measurements::msr_t::term1, dynadjust::measurements::msr_t::term2, dynadjust::measurements::msr_t::term3, dynadjust::measurements::msr_t::term4, dynadjust::measurements::msr_t::vectorCount1, xMeas, and yMeas.
SetMeasurementRec()
UINT32 dynadjust::measurements::CDnaDirection::SetMeasurementRec (const vstn_t & binaryStn, it_vmsr_t & it_msr, it_vdbid_t & dbidmap) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 568 of file dnadirection.cpp.
{
    m_bIgnore = it_msr->ignore;
    m_lsetID = it_msr->clusterID;
    m_MSmeasurementStations = (MEASUREMENT_STATIONS)it_msr->measurementStations;
    // it_msr holds the full number of measurement blocks, which is
    // the numberofdirections in the vector plus one for the RO
    m_lRecordedTotal = it_msr->vectorCount1;
    if (it_msr->measType != 'D')        // not part of a DnaDirectionSet (e.g. vertical angle, zenith distance)
    {
        m_strType = it_msr->measType;
        // first station
        m_lstn1Index = it_msr->station1;
        m_strFirst = binaryStn.at(it_msr->station1).stationName;
        // inst and targ heights
        m_fInstHeight = static_cast<float> (it_msr->term3);
        m_fTargHeight = static_cast<float> (it_msr->term4);
    }
    // target station
    m_lstn2Index = it_msr->station2;
    m_strTarget = binaryStn.at(it_msr->station2).stationName;
    m_measAdj = it_msr->measAdj;
    m_measCorr = it_msr->measCorr;
    m_measAdjPrec = it_msr->measAdjPrec;
    m_residualPrec = it_msr->residualPrec;
    m_preAdjCorr = it_msr->preAdjCorr;
    m_drValue = it_msr->term1;
    m_dStdDev = sqrt(it_msr->term2);
    m_epoch = it_msr->epoch;
    CDnaMeasurement::SetDatabaseMap(*dbidmap);
    return 0;
}
References dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, m_lRecordedTotal, m_lsetID, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, and dynadjust::measurements::CDnaMeasurement::SetDatabaseMap().
WriteDynaMLMsr()
void dynadjust::measurements::CDnaDirection::WriteDynaMLMsr (std::ofstream * dynaml_stream, const std::string & comment, bool bSubMeasurement = false) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 199 of file dnadirection.cpp.
{
    if (bSubMeasurement)
    {
        // Direction set
        *dynaml_stream << "    <Directions>" << std::endl;
        if (m_bIgnore)
            *dynaml_stream << "      <Ignore>*</Ignore>" << std::endl;
        else
            *dynaml_stream << "      <Ignore/>" << std::endl;
        *dynaml_stream << "      <Target>" << m_strTarget << "</Target>" << std::endl;
        *dynaml_stream << "      <Value>" << std::setprecision(8) << std::fixed
            << RadtoDms(m_drValue) << "</Value>" << std::endl;
        *dynaml_stream << "      <StdDev>" << std::scientific << std::setprecision(6) << Seconds(m_dStdDev) << "</StdDev>" << std::endl;
        if (m_msr_db_map.is_msr_id_set)
            *dynaml_stream << "      <MeasurementID>" << m_msr_db_map.msr_id << "</MeasurementID>" << std::endl;
        *dynaml_stream << "    </Directions>" << std::endl;
    }
    else
    {
        // Zenith distance, vertical angle
        if (comment.empty())
            *dynaml_stream << "  <!-- Type " << measurement_name<char, std::string>(GetTypeC()) << " -->" << std::endl;
        else
            *dynaml_stream << "  <!-- " << comment << " -->" << std::endl;
        *dynaml_stream << "  <DnaMeasurement>" << std::endl;
        *dynaml_stream << "    <Type>" << m_strType << "</Type>" << std::endl;
        // Source file from which the measurement came
        *dynaml_stream << "    <Source>" << m_sourceFile << "</Source>" << std::endl;
        if (m_bIgnore)
            *dynaml_stream << "    <Ignore>*</Ignore>" << std::endl;
        else
            *dynaml_stream << "    <Ignore/>" << std::endl;
        if (m_epoch.empty())
            *dynaml_stream << "    <Epoch/>" << std::endl;
        else
            *dynaml_stream << "    <Epoch>" << m_epoch << "</Epoch>" << std::endl;
        *dynaml_stream << "    <First>" << m_strFirst << "</First>" << std::endl;
        *dynaml_stream << "    <Second>" << m_strTarget << "</Second>" << std::endl;
        *dynaml_stream << "    <Value>" << std::setprecision(8) << std::fixed
            << RadtoDms(m_drValue) << "</Value>" << std::endl;
        *dynaml_stream << "    <StdDev>" << std::scientific << std::setprecision(6) << Seconds(m_dStdDev) << "</StdDev>" << std::endl;
        // Zenith distance, vertical angle
        switch (GetTypeC())
        {
        case 'Z':
        case 'V':
            *dynaml_stream << "    <InstHeight>" << std::fixed << std::setprecision(3) << m_fInstHeight << "</InstHeight>" << std::endl;
            *dynaml_stream << "    <TargHeight>" << std::fixed << std::setprecision(3) << m_fTargHeight << "</TargHeight>" << std::endl;
            break;
        }
        if (m_msr_db_map.is_msr_id_set)
            *dynaml_stream << "    <MeasurementID>" << m_msr_db_map.msr_id << "</MeasurementID>" << std::endl;
        *dynaml_stream << "  </DnaMeasurement>" << std::endl;
    }
}
References dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_sourceFile, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, dynadjust::measurements::measurement_name(), RadtoDms(), and Seconds().
WriteDNAMsr()
void dynadjust::measurements::CDnaDirection::WriteDNAMsr (std::ofstream * dna_stream, const dna_msr_fields & dmw, const dna_msr_fields & dml, bool bSubMeasurement = false) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 264 of file dnadirection.cpp.
{
    *dna_stream << std::setw(dmw.msr_type) << m_strType;
    if (m_bIgnore)
        *dna_stream << std::setw(dmw.msr_ignore) << "*";
    else
        *dna_stream << std::setw(dmw.msr_ignore) << " ";
    // database id width
    UINT32 width(dml.msr_id_msr - dml.msr_stddev - dmw.msr_stddev);
    if (bSubMeasurement)
    {
        // Direction set
        *dna_stream << std::left << std::setw(dmw.msr_inst) << " ";
        *dna_stream << std::setw(dmw.msr_targ1) << " ";
        *dna_stream << std::left << std::setw(dmw.msr_targ2) << m_strTarget;
        *dna_stream << std::setw(dmw.msr_linear) << " ";  // linear measurement value
        *dna_stream << std::setw(dmw.msr_ang_d + dmw.msr_ang_m + dmw.msr_ang_s) <<
            std::right << FormatDnaDmsString(RadtoDms(m_drValue), 8);
        UINT32 m_stdDevPrec(3);
        *dna_stream << std::setw(dmw.msr_stddev) << StringFromTW(Seconds(m_dStdDev), dmw.msr_stddev, m_stdDevPrec);
        //*dna_stream << std::setw(dmw.msr_stddev) << std::fixed << std::setprecision(3) << Seconds(m_dStdDev);
    }
    else
    {
        // Azimuth, zenith distance, vertical angle
        *dna_stream << std::left << std::setw(dmw.msr_inst) << m_strFirst;
        *dna_stream << std::left << std::setw(dmw.msr_targ1) << m_strTarget;
        *dna_stream << std::setw(dmw.msr_targ2) << " ";
        *dna_stream << std::setw(dmw.msr_linear) << " ";  // linear measurement value
        *dna_stream << std::setw(dmw.msr_ang_d + dmw.msr_ang_m + dmw.msr_ang_s) <<
            std::right << FormatDnaDmsString(RadtoDms(m_drValue), 8);
        UINT32 m_stdDevPrec(3);
        *dna_stream << std::setw(dmw.msr_stddev) << StringFromTW(Seconds(m_dStdDev), dmw.msr_stddev, m_stdDevPrec);
        //*dna_stream << std::setw(dmw.msr_stddev) << std::fixed << std::setprecision(3) << Seconds(m_dStdDev);
        width = dml.msr_gps_epoch - dml.msr_inst_ht;
        // Zenith distance, vertical angle
        switch (GetTypeC())
        {
        case 'Z':
        case 'V':
            *dna_stream << std::setw(dmw.msr_inst_ht) << std::fixed << std::setprecision(3) << m_fInstHeight;
            *dna_stream << std::setw(dmw.msr_targ_ht) << std::fixed << std::setprecision(3) << m_fTargHeight;
            width = dml.msr_gps_epoch - dml.msr_targ_ht - dmw.msr_targ_ht;
            break;
        }
        *dna_stream << std::setw(width) << " ";
        *dna_stream << std::setw(dmw.msr_gps_epoch) << m_epoch;
        width = 0;
    }
    if (m_msr_db_map.is_msr_id_set)
    {
        if (width)
            *dna_stream << std::setw(width) << " ";
        *dna_stream << std::setw(dmw.msr_id_msr) << m_msr_db_map.msr_id;
        if (bSubMeasurement)
            if (m_msr_db_map.is_cls_id_set)
                *dna_stream << std::setw(dmw.msr_id_cluster) << m_msr_db_map.cluster_id;
    }
    *dna_stream << std::endl;
}
References FormatDnaDmsString(), dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_strFirst, m_strTarget, dynadjust::measurements::CDnaMeasurement::m_strType, dna_msr_fields::msr_ang_d, dna_msr_fields::msr_ang_m, dna_msr_fields::msr_ang_s, dna_msr_fields::msr_gps_epoch, dna_msr_fields::msr_id_cluster, dna_msr_fields::msr_id_msr, dna_msr_fields::msr_ignore, dna_msr_fields::msr_inst, dna_msr_fields::msr_inst_ht, dna_msr_fields::msr_linear, dna_msr_fields::msr_stddev, dna_msr_fields::msr_targ1, dna_msr_fields::msr_targ2, dna_msr_fields::msr_targ_ht, dna_msr_fields::msr_type, RadtoDms(), Seconds(), and StringFromTW().
SimulateMsr()
void dynadjust::measurements::CDnaDirection::SimulateMsr (vdnaStnPtr * vStations, const CDnaEllipsoid * ellipsoid) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 334 of file dnadirection.cpp.
{
    _it_vdnastnptr stn1_it(vStations->begin() + m_lstn1Index);
    _it_vdnastnptr stn2_it(vStations->begin() + m_lstn2Index);
    double zenithDistance;
    double direction;
    direction = Direction(
        stn1_it->get()->GetXAxis(),
        stn1_it->get()->GetYAxis(),
        stn1_it->get()->GetZAxis(),
        stn2_it->get()->GetXAxis(),
        stn2_it->get()->GetYAxis(),
        stn2_it->get()->GetZAxis(),
        stn1_it->get()->GetcurrentLatitude(),
        stn1_it->get()->GetcurrentLongitude());
    switch (GetTypeC())
    {
    // direction
    case 'D':
        // assign direction
        m_drValue = direction;
        // Deflections available?
        if (fabs(stn1_it->get()->GetverticalDef()) > E4_SEC_DEFLECTION || fabs(stn1_it->get()->GetmeridianDef()) > E4_SEC_DEFLECTION)
        {
            // 1. compute zenith distance
            zenithDistance = ZenithDistance<double>(
                stn1_it->get()->GetXAxis(),
                stn1_it->get()->GetYAxis(),
                stn1_it->get()->GetZAxis(),
                stn2_it->get()->GetXAxis(),
                stn2_it->get()->GetYAxis(),
                stn2_it->get()->GetZAxis(),
                stn1_it->get()->GetcurrentLatitude(),
                stn1_it->get()->GetcurrentLongitude(),
                stn2_it->get()->GetcurrentLatitude(),
                stn2_it->get()->GetcurrentLongitude(),
                0.0,
                0.0);
            // 2. Compute deflection
            m_preAdjCorr = DirectionDeflectionCorrection<double>(
                m_drValue,
                zenithDistance,
                stn1_it->get()->GetverticalDef(),           // deflection in prime vertical
                stn1_it->get()->GetmeridianDef());          // deflection in prime meridian
            // 3. apply deflection correction
            m_drValue += m_preAdjCorr;
        }
        break;
    // geodetic azimuth
    case 'B':
        // assign direction
        m_drValue = direction;
        m_epoch = "01.10.1985";
        break;
    // astronomic azimuth
    case 'K':
        // assign direction
        m_drValue = direction;
        // Deflections available?
        if (fabs(stn1_it->get()->GetverticalDef()) > E4_SEC_DEFLECTION || fabs(stn1_it->get()->GetmeridianDef()) > E4_SEC_DEFLECTION)
        {
            // 1. compute zenith distance
            zenithDistance = ZenithDistance<double>(
                stn1_it->get()->GetXAxis(),
                stn1_it->get()->GetYAxis(),
                stn1_it->get()->GetZAxis(),
                stn2_it->get()->GetXAxis(),
                stn2_it->get()->GetYAxis(),
                stn2_it->get()->GetZAxis(),
                stn1_it->get()->GetcurrentLatitude(),
                stn1_it->get()->GetcurrentLongitude(),
                stn2_it->get()->GetcurrentLatitude(),
                stn2_it->get()->GetcurrentLongitude(),
                0.0,
                0.0);
            // 2. Compute correction
            m_preAdjCorr = LaplaceCorrection<double>(      // Laplace correction
                m_drValue,                                 // geodetic azimuth
                zenithDistance,                             // zenith distance
                stn1_it->get()->GetverticalDef(),           // deflection in prime vertical
                stn1_it->get()->GetmeridianDef(),           // deflection in prime meridian
                stn1_it->get()->GetcurrentLatitude());
            // 3. apply deflection correction
            m_drValue += m_preAdjCorr;
        }
        m_epoch = "01.10.1985";
        break;
    // vertical angle
    case 'Z':
        m_fInstHeight = float(1.650);
        m_fTargHeight = float(1.651);
        // compute vertical angle
        m_drValue = VerticalAngle<double>(
            stn1_it->get()->GetXAxis(),
            stn1_it->get()->GetYAxis(),
            stn1_it->get()->GetZAxis(),
            stn2_it->get()->GetXAxis(),
            stn2_it->get()->GetYAxis(),
            stn2_it->get()->GetZAxis(),
            stn1_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentLongitude(),
            stn2_it->get()->GetcurrentLatitude(),
            stn2_it->get()->GetcurrentLongitude(),
            m_fInstHeight,
            m_fTargHeight);
        // Deflections available?
        if (fabs(stn1_it->get()->GetverticalDef()) > E4_SEC_DEFLECTION || fabs(stn1_it->get()->GetmeridianDef()) > E4_SEC_DEFLECTION)
        {
            // 1. compute bearing from estimated coordinates
            // see above
            // 2. Compute correction
            m_preAdjCorr = ZenithDeflectionCorrection<double>(    // Correction to vertical angle for deflection of vertical
                direction,                                      // geodetic azimuth
                stn1_it->get()->GetverticalDef(),               // deflection in prime vertical
                stn1_it->get()->GetmeridianDef());              // deflection in prime meridian
            // 3. apply deflection correction (in reverse
            // to get the simulated observation)
            m_drValue += m_preAdjCorr;
        }
        m_epoch = "01.10.1985";
        break;
    // zenith distance
    case 'V':
        m_fInstHeight = float(1.650);
        m_fTargHeight = float(1.651);
        // compute zenith distance
        m_drValue = ZenithDistance<double>(
            stn1_it->get()->GetXAxis(),
            stn1_it->get()->GetYAxis(),
            stn1_it->get()->GetZAxis(),
            stn2_it->get()->GetXAxis(),
            stn2_it->get()->GetYAxis(),
            stn2_it->get()->GetZAxis(),
            stn1_it->get()->GetcurrentLatitude(),
            stn1_it->get()->GetcurrentLongitude(),
            stn2_it->get()->GetcurrentLatitude(),
            stn2_it->get()->GetcurrentLongitude(),
            m_fInstHeight,
            m_fTargHeight);
        // Deflections available?
        if (fabs(stn1_it->get()->GetverticalDef()) > E4_SEC_DEFLECTION || fabs(stn1_it->get()->GetmeridianDef()) > E4_SEC_DEFLECTION)
        {
            // 1. compute bearing from estimated coordinates
            // see above
            // 2. Compute correction
            m_preAdjCorr = ZenithDeflectionCorrection<double>(    // Correction to zenith distance for deflection of vertical
                direction,                                      // geodetic azimuth
                stn1_it->get()->GetverticalDef(),               // deflection in prime vertical
                stn1_it->get()->GetmeridianDef());              // deflection in prime meridian
            // 3. apply deflection correction (in reverse
            // to get the simulated observation)
            m_drValue -= m_preAdjCorr;
        }
    }
    m_dStdDev = SecondstoRadians(0.010);
    m_epoch = "01.10.1985";
}
References Direction(), DirectionDeflectionCorrection(), E4_SEC_DEFLECTION(), dynadjust::measurements::CDnaMeasurement::GetTypeC(), LaplaceCorrection(), m_drValue, m_dStdDev, dynadjust::measurements::CDnaMeasurement::m_epoch, m_fInstHeight, m_fTargHeight, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_lstn2Index, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, SecondstoRadians(), VerticalAngle(), ZenithDeflectionCorrection(), and ZenithDistance().
Member Data Documentation
m_strTarget
std::string dynadjust::measurements::CDnaDirection::m_strTarget
Definition at line 87 of file dnadirection.hpp.
Referenced by dynadjust::measurements::CDnaAzimuth::CDnaAzimuth(), CDnaDirection(), CDnaDirection(), GetTarget(), operator<(), operator=(), dynadjust::measurements::CDnaAzimuth::operator==(), operator==(), SetMeasurementRec(), SetTarget(), WriteDNAMsr(), and WriteDynaMLMsr().
m_drValue
double dynadjust::measurements::CDnaDirection::m_drValue protected
Definition at line 90 of file dnadirection.hpp.
Referenced by dynadjust::measurements::CDnaAzimuth::CDnaAzimuth(), CDnaDirection(), CDnaDirection(), GetValue(), operator<(), operator=(), dynadjust::measurements::CDnaAzimuth::operator==(), operator==(), SetMeasurementRec(), SetValue(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_dStdDev
double dynadjust::measurements::CDnaDirection::m_dStdDev protected
Definition at line 91 of file dnadirection.hpp.
Referenced by dynadjust::measurements::CDnaAzimuth::CDnaAzimuth(), CDnaDirection(), CDnaDirection(), GetStdDev(), operator<(), operator=(), dynadjust::measurements::CDnaAzimuth::operator==(), operator==(), SetMeasurementRec(), SetStdDev(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_fInstHeight
float dynadjust::measurements::CDnaDirection::m_fInstHeight protected
Definition at line 92 of file dnadirection.hpp.
Referenced by dynadjust::measurements::CDnaAzimuth::CDnaAzimuth(), CDnaDirection(), CDnaDirection(), GetInstrHeight(), operator<(), operator=(), operator==(), SetInstrumentHeight(), SetMeasurementRec(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_fTargHeight
float dynadjust::measurements::CDnaDirection::m_fTargHeight protected
Definition at line 93 of file dnadirection.hpp.
Referenced by dynadjust::measurements::CDnaAzimuth::CDnaAzimuth(), CDnaDirection(), CDnaDirection(), GetTargetHeight(), operator<(), operator=(), operator==(), SetMeasurementRec(), SetTargetHeight(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_lRecordedTotal
UINT32 dynadjust::measurements::CDnaDirection::m_lRecordedTotal protected
Definition at line 94 of file dnadirection.hpp.
Referenced by dynadjust::measurements::CDnaAzimuth::CDnaAzimuth(), CDnaDirection(), CDnaDirection(), operator=(), SetMeasurementRec(), SetRecordedTotal(), and WriteBinaryMsr().
m_lsetID
UINT32 dynadjust::measurements::CDnaDirection::m_lsetID protected
Definition at line 95 of file dnadirection.hpp.
Referenced by dynadjust::measurements::CDnaAzimuth::CDnaAzimuth(), CDnaDirection(), CDnaDirection(), operator=(), SetClusterID(), SetMeasurementRec(), and WriteBinaryMsr().
The documentation for this class was generated from the following files:
include/measurement_types/dnadirection.hpp
include/measurement_types/dnadirection.cpp