DynAdjust: dynadjust::exception::NetGeoidException Class Reference
dynadjust::exception::NetGeoidException Class Reference
#include <dnaexception.hpp>
Public Member Functions
NetGeoidException (const std::string &what, const int &error_no, const UINT32 &line_no=0)
virtual const char * what () const throw ()
virtual ~NetGeoidException () throw ()
int error_no () const
UINT32 line_no () const
Private Attributes
std::string what_
int error_no_
UINT32 line_no_
Detailed Description
Definition at line 152 of file dnaexception.hpp.
Constructor & Destructor Documentation
NetGeoidException()
dynadjust::exception::NetGeoidException::NetGeoidException (const std::string & what, const int & error_no, const UINT32 & line_no = 0) inline explicit
Definition at line 155 of file dnaexception.hpp.
        : what_(what), error_no_(error_no), line_no_(line_no) {}
References error_no(), error_no_, line_no(), line_no_, what(), and what_.
~NetGeoidException()
virtual dynadjust::exception::NetGeoidException::~NetGeoidException () throw () inline virtual
Definition at line 158 of file dnaexception.hpp.
{}
Member Function Documentation
what()
virtual const char * dynadjust::exception::NetGeoidException::what () const throw () inline virtual
Definition at line 157 of file dnaexception.hpp.
{ return what_.c_str(); }
References what_.
Referenced by CreateGridFile(), CdnageoidintDlg::CreateGridIndex(), createGridIndex(), CreateNTv2Grid(), ExportNTv2GridToAscii(), ExportNTv2GridToBinary(), InterpolateGridBinaryStationFile(), InterpolateGridPoint(), InterpolateGridPointFile(), NetGeoidException(), CdnageoidintDlg::OnFileInterpolate(), CdnageoidintDlg::OnInterpolateInputCoords(), CdnageoidintDlg::OnTransform(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessCsvFile(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessDatFile(), and reportGridProperties().
error_no()
int dynadjust::exception::NetGeoidException::error_no () const inline
Definition at line 160 of file dnaexception.hpp.
{ return error_no_; }
References error_no_.
Referenced by CreateGridFile(), CdnageoidintDlg::CreateGridIndex(), NetGeoidException(), CdnageoidintDlg::OnFileInterpolate(), CdnageoidintDlg::OnInterpolateInputCoords(), and CdnageoidintDlg::OnTransform().
line_no()
UINT32 dynadjust::exception::NetGeoidException::line_no () const inline
Definition at line 161 of file dnaexception.hpp.
{ return line_no_; }
References line_no_.
Referenced by NetGeoidException().
Member Data Documentation
what_
std::string dynadjust::exception::NetGeoidException::what_ private
Definition at line 164 of file dnaexception.hpp.
Referenced by NetGeoidException(), and what().
error_no_
int dynadjust::exception::NetGeoidException::error_no_ private
Definition at line 165 of file dnaexception.hpp.
Referenced by error_no(), and NetGeoidException().
line_no_
UINT32 dynadjust::exception::NetGeoidException::line_no_ private
Definition at line 166 of file dnaexception.hpp.
Referenced by line_no(), and NetGeoidException().
The documentation for this class was generated from the following file:
include/exception/dnaexception.hpp