DynAdjust: dynadjust::iostreams::dna_io_base Class Reference
dynadjust::iostreams::dna_io_base Class Reference
#include <dnaiobase.hpp>
Public Member Functions
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Protected Member Functions
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 64 of file dnaiobase.hpp.
Constructor & Destructor Documentation
dna_io_base() [1/2]
dynadjust::iostreams::dna_io_base::dna_io_base (void)
Definition at line 34 of file dnaiobase.cpp.
    : m_strVersion(__FILE_VERSION__)
    , m_strDate("")
    , m_strApp("DNA" + std::string(__SHORT_VERSION__))
{
}
References __FILE_VERSION__, __SHORT_VERSION__, m_strApp, m_strDate, and m_strVersion.
Referenced by dynadjust::iostreams::dna_io_adj::dna_io_adj(), dynadjust::iostreams::dna_io_aml::dna_io_aml(), dynadjust::iostreams::dna_io_asl::dna_io_asl(), dna_io_base(), dynadjust::iostreams::dna_io_bms::dna_io_bms(), dynadjust::iostreams::dna_io_bst::dna_io_bst(), dynadjust::iostreams::dna_io_dna::dna_io_dna(), dynadjust::iostreams::dna_io_map::dna_io_map(), dynadjust::iostreams::dna_io_scalar::dna_io_scalar(), dynadjust::iostreams::dna_io_seg::dna_io_seg(), dynadjust::iostreams::dna_io_tbu::dna_io_tbu(), dynadjust::iostreams::dna_io_tpb::dna_io_tpb(), and operator=().
dna_io_base() [2/2]
dynadjust::iostreams::dna_io_base::dna_io_base (const dna_io_base & newFile)
Definition at line 42 of file dnaiobase.cpp.
    : m_strVersion(newFile.m_strVersion)
    , m_strDate(newFile.m_strDate)
    , m_strApp(newFile.m_strApp)
{
}
References dna_io_base(), m_strApp, m_strDate, and m_strVersion.
~dna_io_base()
dynadjust::iostreams::dna_io_base::~dna_io_base (void) virtual
Definition at line 50 of file dnaiobase.cpp.
{
}
Member Function Documentation
operator=()
dna_io_base & dynadjust::iostreams::dna_io_base::operator= (const dna_io_base & rhs)
Definition at line 55 of file dnaiobase.cpp.
{
    // check for assignment to self!
    if (this == &rhs)
        return *this;
    m_strVersion = rhs.m_strVersion;
    m_strDate = rhs.m_strDate;
    m_strApp = rhs.m_strApp;
    return *this;
}
References dna_io_base(), m_strApp, m_strDate, and m_strVersion.
getVersion()
std::string dynadjust::iostreams::dna_io_base::getVersion () const inline
Definition at line 73 of file dnaiobase.hpp.
{ return m_strVersion; }
References m_strVersion.
setVersion()
void dynadjust::iostreams::dna_io_base::setVersion (const std::string & version) inline
Definition at line 74 of file dnaiobase.hpp.
{ m_strVersion = version; }
References m_strVersion.
writeFileInfo()
void dynadjust::iostreams::dna_io_base::writeFileInfo (std::ofstream & file_stream)
Definition at line 68 of file dnaiobase.cpp.
{
    writeVersion(file_stream);
    writeDate(file_stream);
    writeApp(file_stream);
}
References writeApp(), writeDate(), and writeVersion().
Referenced by dynadjust::iostreams::dna_io_aml::write_aml_file(), dynadjust::iostreams::dna_io_asl::write_asl_file(), dynadjust::iostreams::dna_io_bms::write_bms_file(), dynadjust::iostreams::dna_io_bms::write_bms_file(), dynadjust::iostreams::dna_io_bst::write_bst_file(), dynadjust::iostreams::dna_io_bst::write_bst_file(), and dynadjust::iostreams::dna_io_map::write_map_file().
readFileInfo()
void dynadjust::iostreams::dna_io_base::readFileInfo (std::ifstream & file_stream)
Definition at line 76 of file dnaiobase.cpp.
{
    readVersion(file_stream);
    readDate(file_stream);
    readApp(file_stream);
}
References readApp(), readDate(), and readVersion().
Referenced by dynadjust::iostreams::dna_io_aml::load_aml_file(), dynadjust::iostreams::dna_io_asl::load_asl_file(), dynadjust::iostreams::dna_io_bms::load_bms_file(), dynadjust::iostreams::dna_io_bms::load_bms_file_meta(), dynadjust::iostreams::dna_io_bst::load_bst_file(), dynadjust::iostreams::dna_io_bst::load_bst_file_meta(), and dynadjust::iostreams::dna_io_map::load_map_file().
writeFileMetadata()
void dynadjust::iostreams::dna_io_base::writeFileMetadata (std::ofstream & file_stream, binary_file_meta_t & file_meta)
Definition at line 84 of file dnaiobase.cpp.
{
    // Write the metadata
    file_stream.write(reinterpret_cast<char *>(&file_meta.binCount), sizeof(UINT32));
    file_stream.write(reinterpret_cast<char *>(&file_meta.reduced), sizeof(bool));
    file_stream.write(reinterpret_cast<char *>(file_meta.modifiedBy), MOD_NAME_WIDTH);
    // Write the epsg code and epoch
    file_stream.write(reinterpret_cast<char *>(file_meta.epsgCode), STN_EPSG_WIDTH);
    file_stream.write(reinterpret_cast<char *>(file_meta.epoch), STN_EPOCH_WIDTH);
    file_stream.write(reinterpret_cast<char*>(&file_meta.reftran), sizeof(bool));
    file_stream.write(reinterpret_cast<char*>(&file_meta.geoid), sizeof(bool));
    // Write file count and file meta
    file_stream.write(reinterpret_cast<char *>(&file_meta.inputFileCount), sizeof(UINT16));
    for (UINT16 i(0); i<file_meta.inputFileCount; ++i)
    {
        file_stream.write(reinterpret_cast<char *>(file_meta.inputFileMeta[i].filename), FILE_NAME_WIDTH);
        file_stream.write(reinterpret_cast<char *>(file_meta.inputFileMeta[i].epsgCode), STN_EPSG_WIDTH);
        file_stream.write(reinterpret_cast<char *>(file_meta.inputFileMeta[i].epoch), STN_EPOCH_WIDTH);
        file_stream.write(reinterpret_cast<char *>(&file_meta.inputFileMeta[i].filetype), sizeof(UINT16));
        file_stream.write(reinterpret_cast<char *>(&file_meta.inputFileMeta[i].datatype), sizeof(UINT16));
    }
}
References binary_file_meta::binCount, input_file_meta::datatype, binary_file_meta::epoch, input_file_meta::epoch, binary_file_meta::epsgCode, input_file_meta::epsgCode, FILE_NAME_WIDTH(), input_file_meta::filename, input_file_meta::filetype, binary_file_meta::geoid, binary_file_meta::inputFileCount, binary_file_meta::inputFileMeta, MOD_NAME_WIDTH(), binary_file_meta::modifiedBy, binary_file_meta::reduced, binary_file_meta::reftran, STN_EPOCH_WIDTH(), and STN_EPSG_WIDTH().
Referenced by dynadjust::iostreams::dna_io_bms::write_bms_file(), dynadjust::iostreams::dna_io_bms::write_bms_file(), dynadjust::iostreams::dna_io_bst::write_bst_file(), and dynadjust::iostreams::dna_io_bst::write_bst_file().
readFileMetadata()
void dynadjust::iostreams::dna_io_base::readFileMetadata (std::ifstream & file_stream, binary_file_meta_t & file_meta)
Definition at line 111 of file dnaiobase.cpp.
{
    // Read the metadata
    file_stream.read(reinterpret_cast<char *>(&file_meta.binCount), sizeof(UINT32));
    file_stream.read(reinterpret_cast<char *>(&file_meta.reduced), sizeof(bool));
    file_stream.read(reinterpret_cast<char *>(file_meta.modifiedBy), MOD_NAME_WIDTH);
    // Read the epsg code and epoch
    file_stream.read(reinterpret_cast<char *>(file_meta.epsgCode), STN_EPSG_WIDTH);
    file_stream.read(reinterpret_cast<char *>(file_meta.epoch), STN_EPOCH_WIDTH);
    file_stream.read(reinterpret_cast<char*>(&file_meta.reftran), sizeof(bool));
    file_stream.read(reinterpret_cast<char*>(&file_meta.geoid), sizeof(bool));
    // Read file count and file meta
    file_stream.read(reinterpret_cast<char *>(&file_meta.inputFileCount), sizeof(UINT16));
    if (file_meta.inputFileMeta != NULL)
        delete []file_meta.inputFileMeta;
    file_meta.inputFileMeta = new input_file_meta_t[file_meta.inputFileCount];
    for (UINT16 i(0); i<file_meta.inputFileCount; ++i)
    {
        file_stream.read(reinterpret_cast<char *>(file_meta.inputFileMeta[i].filename), FILE_NAME_WIDTH);
        file_stream.read(reinterpret_cast<char *>(file_meta.inputFileMeta[i].epsgCode), STN_EPSG_WIDTH);
        file_stream.read(reinterpret_cast<char *>(file_meta.inputFileMeta[i].epoch), STN_EPOCH_WIDTH);
        file_stream.read(reinterpret_cast<char *>(&file_meta.inputFileMeta[i].filetype), sizeof(UINT16));
        file_stream.read(reinterpret_cast<char *>(&file_meta.inputFileMeta[i].datatype), sizeof(UINT16));
    }
}
References binary_file_meta::binCount, input_file_meta::datatype, binary_file_meta::epoch, input_file_meta::epoch, binary_file_meta::epsgCode, input_file_meta::epsgCode, FILE_NAME_WIDTH(), input_file_meta::filename, input_file_meta::filetype, binary_file_meta::geoid, binary_file_meta::inputFileCount, binary_file_meta::inputFileMeta, MOD_NAME_WIDTH(), binary_file_meta::modifiedBy, binary_file_meta::reduced, binary_file_meta::reftran, STN_EPOCH_WIDTH(), and STN_EPSG_WIDTH().
Referenced by dynadjust::iostreams::dna_io_bms::load_bms_file(), dynadjust::iostreams::dna_io_bms::load_bms_file_meta(), dynadjust::iostreams::dna_io_bst::load_bst_file(), and dynadjust::iostreams::dna_io_bst::load_bst_file_meta().
writeVersion()
void dynadjust::iostreams::dna_io_base::writeVersion (std::ofstream & file_stream) protected
Definition at line 143 of file dnaiobase.cpp.
{
    char versionField[identifier_field_width+1];
    // write version field name
    versionField[identifier_field_width] = '\0';
    file_stream.write(const_cast<char *>(version_header), identifier_field_width);
    // write version, with safeguard against overwriting by substr
    snprintf(versionField, sizeof(versionField), "%*s", identifier_field_width, m_strVersion.substr(0, identifier_field_width).c_str());
    file_stream.write(reinterpret_cast<char *>(versionField), identifier_field_width);
}
References dynadjust::iostreams::identifier_field_width(), m_strVersion, and dynadjust::iostreams::version_header.
Referenced by writeFileInfo().
readVersion()
void dynadjust::iostreams::dna_io_base::readVersion (std::ifstream & file_stream) protected
Definition at line 158 of file dnaiobase.cpp.
{
    char versionField[identifier_field_width+1];
    // read version field name
    versionField[identifier_field_width] = '\0';
    file_stream.read(reinterpret_cast<char *>(versionField), identifier_field_width);
    // read version
    file_stream.read(reinterpret_cast<char *>(versionField), identifier_field_width);
    m_strVersion = versionField;
    m_strVersion = trimstr(m_strVersion);
}
References dynadjust::iostreams::identifier_field_width(), m_strVersion, and trimstr().
Referenced by readFileInfo().
writeDate()
void dynadjust::iostreams::dna_io_base::writeDate (std::ofstream & file_stream) protected
Definition at line 173 of file dnaiobase.cpp.
{
    char dateField[identifier_field_width+1];
    // Form date string
    boost::gregorian::date today(boost::gregorian::day_clock::local_day());
    std::stringstream date_string;
    date_string << std::right << to_iso_extended_string(today);
    m_strDate = date_string.str();
    // write creation date field name
    dateField[identifier_field_width] = '\0';
    file_stream.write(const_cast<char *>(create_date_header), identifier_field_width);
    // write creation date, with safeguard against overwriting by substr
    snprintf(dateField, sizeof(dateField), "%*s", identifier_field_width, m_strDate.substr(0, identifier_field_width).c_str());
    file_stream.write(reinterpret_cast<char *>(dateField), identifier_field_width);
}
References dynadjust::iostreams::create_date_header, dynadjust::iostreams::identifier_field_width(), and m_strDate.
Referenced by writeFileInfo().
readDate()
void dynadjust::iostreams::dna_io_base::readDate (std::ifstream & file_stream) protected
Definition at line 194 of file dnaiobase.cpp.
{
    char dateField[identifier_field_width+1];
    // read creation date field name
    dateField[identifier_field_width] = '\0';
    file_stream.read(reinterpret_cast<char *>(dateField), identifier_field_width);
    // read creation date
    file_stream.read(reinterpret_cast<char *>(dateField), identifier_field_width);
    m_strDate = dateField;
    m_strDate = trimstr(m_strDate);
}
References dynadjust::iostreams::identifier_field_width(), m_strDate, and trimstr().
Referenced by readFileInfo().
writeApp()
void dynadjust::iostreams::dna_io_base::writeApp (std::ofstream & file_stream) protected
Definition at line 209 of file dnaiobase.cpp.
{
    char appField[identifier_field_width+1];
    // write application field name
    appField[identifier_field_width] = '\0';
    file_stream.write(const_cast<char *>(create_by_header), identifier_field_width);
    // write application, with safeguard against overwriting by substr
    snprintf(appField, sizeof(appField), "%*s", identifier_field_width, m_strApp.substr(0, identifier_field_width).c_str());
    file_stream.write(reinterpret_cast<char *>(appField), identifier_field_width);
}
References dynadjust::iostreams::create_by_header, dynadjust::iostreams::identifier_field_width(), and m_strApp.
Referenced by writeFileInfo().
readApp()
void dynadjust::iostreams::dna_io_base::readApp (std::ifstream & file_stream) protected
Definition at line 224 of file dnaiobase.cpp.
{
    char appField[identifier_field_width+1];
    // read application field name
    appField[identifier_field_width] = '\0';
    file_stream.read(reinterpret_cast<char *>(appField), identifier_field_width);
    // read application
    file_stream.read(reinterpret_cast<char *>(appField), identifier_field_width);
    m_strApp = appField;
    m_strApp = trimstr(m_strApp);
}
References dynadjust::iostreams::identifier_field_width(), m_strApp, and trimstr().
Referenced by readFileInfo().
Member Data Documentation
m_strVersion
std::string dynadjust::iostreams::dna_io_base::m_strVersion protected
Definition at line 91 of file dnaiobase.hpp.
Referenced by dna_io_base(), dna_io_base(), getVersion(), operator=(), readVersion(), setVersion(), and writeVersion().
m_strDate
std::string dynadjust::iostreams::dna_io_base::m_strDate protected
Definition at line 92 of file dnaiobase.hpp.
Referenced by dna_io_base(), dna_io_base(), operator=(), readDate(), and writeDate().
m_strApp
std::string dynadjust::iostreams::dna_io_base::m_strApp protected
Definition at line 93 of file dnaiobase.hpp.
Referenced by dna_io_base(), dna_io_base(), operator=(), readApp(), and writeApp().
The documentation for this class was generated from the following files:
include/io/dnaiobase.hpp
include/io/dnaiobase.cpp