DynAdjust: ComparePairFirst< T > Class Template Reference
ComparePairFirst< T > Class Template Reference
#include <dnatemplatefuncs.hpp>
Public Member Functions
bool operator() (const std::pair< T, T > &lhs, const std::pair< T, T > &rhs) const
bool operator() (const std::pair< T, T > &lhs, const T &rhs)
bool operator() (const T &lhs, const std::pair< T, T > &rhs)
Private Member Functions
bool pair_firstless (const T &s1, const T &s2) const
Detailed Description
template<typename T>
class ComparePairFirst< T >
Definition at line 1840 of file dnatemplatefuncs.hpp.
Member Function Documentation
operator()() [1/3]
template<typename T> bool ComparePairFirst< T >::operator() (const std::pair< T, T > & lhs, const std::pair< T, T > & rhs) const inline
Definition at line 1843 of file dnatemplatefuncs.hpp.
{
        return pair_firstless(lhs.first, rhs.first);
    }
References pair_firstless().
operator()() [2/3]
template<typename T> bool ComparePairFirst< T >::operator() (const std::pair< T, T > & lhs, const T & rhs) inline
Definition at line 1846 of file dnatemplatefuncs.hpp.
{
        return pair_firstless(lhs.first, rhs);
    }
References pair_firstless().
operator()() [3/3]
template<typename T> bool ComparePairFirst< T >::operator() (const T & lhs, const std::pair< T, T > & rhs) inline
Definition at line 1849 of file dnatemplatefuncs.hpp.
{
        return pair_firstless(lhs, rhs.first);
    }
References pair_firstless().
pair_firstless()
template<typename T> bool ComparePairFirst< T >::pair_firstless (const T & s1, const T & s2) const inline private
Definition at line 1853 of file dnatemplatefuncs.hpp.
{
        return s1 < s2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this class was generated from the following file:
include/functions/dnatemplatefuncs.hpp