DynAdjust: Directions_pimpl Class Reference
Directions_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void Ignore (const ::std::string &)
virtual void Target (const ::std::string &)
virtual void Value (const ::std::string &)
virtual void StdDev (const ::std::string &)
virtual void MeasurementDBID (const ::std::string &)
virtual void post_Directions (const UINT32 &)
Public Member Functions inherited from Directions_pskel
void Ignore_parser (::xml_schema::string_pskel &)
void Target_parser (::xml_schema::string_pskel &)
void Value_parser (::xml_schema::string_pskel &)
void StdDev_parser (::xml_schema::string_pskel &)
void MeasurementDBID_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &)
Directions_pskel ()
void InitparentDirnSet (dnaMsrPtr pDirectionSet)
void InitparentMsrCounter (PUINT32 pMsrCounter)
Protected Attributes
std::string _Ignore
std::string _Target
std::string _Value
std::string _StdDev
Protected Attributes inherited from Directions_pskel
::xml_schema::string_pskel * Ignore_parser_
::xml_schema::string_pskel * Target_parser_
::xml_schema::string_pskel * Value_parser_
::xml_schema::string_pskel * StdDev_parser_
::xml_schema::string_pskel * MeasurementDBID_parser_
dnaMsrPtr _dnaDirection
dnaMsrPtr _parent_dnaDirectionSet
PUINT32 _pMeasurementCount
Additional Inherited Members
Protected Member Functions inherited from Directions_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Detailed Description
Definition at line 58 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void Directions_pimpl::pre () virtual
Definition at line 121 of file dnaparser_pimpl.cxx.
{
    _dnaDirection.reset(new CDnaDirection);
    _dnaDirection->SetClusterID(_parent_dnaDirectionSet->GetClusterID());
    _dnaDirection->SetClusterDBID(
        _parent_dnaDirectionSet->GetClusterDBID(),
        _parent_dnaDirectionSet->GetClusterDBIDset());
}
References Directions_pskel::_dnaDirection, and Directions_pskel::_parent_dnaDirectionSet.
Ignore()
void Directions_pimpl::Ignore (const ::std::string & Ignore) virtual
Reimplemented from Directions_pskel.
Definition at line 131 of file dnaparser_pimpl.cxx.
{
    if (Ignore.empty())
        _dnaDirection->SetIgnore(false);
    else
        _dnaDirection->SetIgnore(true);
}
References Directions_pskel::_dnaDirection, and Ignore().
Referenced by Ignore().
Target()
void Directions_pimpl::Target (const ::std::string & Target) virtual
Reimplemented from Directions_pskel.
Definition at line 139 of file dnaparser_pimpl.cxx.
{
    _dnaDirection->SetTarget(Target);
}
References Directions_pskel::_dnaDirection, and Target().
Referenced by Target().
Value()
void Directions_pimpl::Value (const ::std::string & Value) virtual
Reimplemented from Directions_pskel.
Definition at line 144 of file dnaparser_pimpl.cxx.
{
    _dnaDirection->SetValue(Value);
    //if (_dnaDirection->NotIgnored())
    //{
        // increment measurement counter
        *(_pMeasurementCount) += 1;
    //}
}
References Directions_pskel::_dnaDirection, Directions_pskel::_pMeasurementCount, and Value().
Referenced by Value().
StdDev()
void Directions_pimpl::StdDev (const ::std::string & StdDev) virtual
Reimplemented from Directions_pskel.
Definition at line 155 of file dnaparser_pimpl.cxx.
{
    _dnaDirection->SetStdDev(StdDev);
}
References Directions_pskel::_dnaDirection, and StdDev().
Referenced by StdDev().
MeasurementDBID()
void Directions_pimpl::MeasurementDBID (const ::std::string & MeasurementID) virtual
Reimplemented from Directions_pskel.
Definition at line 162 of file dnaparser_pimpl.cxx.
{
    _dnaDirection->SetMeasurementDBID(MeasurementID);
}
References Directions_pskel::_dnaDirection.
post_Directions()
void Directions_pimpl::post_Directions (const UINT32 & total) virtual
Reimplemented from Directions_pskel.
Definition at line 168 of file dnaparser_pimpl.cxx.
{
    if (!_parent_dnaDirectionSet)
        return;
    // Is the parent ignored? Add it to the ignored set
    if (_parent_dnaDirectionSet->GetIgnore())
    {
        _parent_dnaDirectionSet->AddDirection(_dnaDirection.get());
        return;
    }
    // Is the parent not ignored, and the direction not ignored? Add it to the set
    if (_dnaDirection->NotIgnored())
    {
        _parent_dnaDirectionSet->AddDirection(_dnaDirection.get());
        return;
    }
    // At this point, the parent is not ignored, but a sub direction is.
    // Test if this ignored sub direction will lead to a false direction
    UINT32 t = _parent_dnaDirectionSet->GetTotal() - 1;
    if (t == 0)
    {
        std::stringstream ss, ss2;
        ss <<
            "<Directions>...</Directions>',  total of " << total << " element(s)" << std::endl <<
            "  - found 0 <Directions>, or there aren't any non-ignored directions in the set. '";
        ss2 << " ~ <Total>" << total << "</Total>";
        throw ::xsd::cxx::parser::expected_element< char >(
            ss.str(), ss2.str());
    }
    _parent_dnaDirectionSet->AddDirection(_dnaDirection.get());
}
References Directions_pskel::_dnaDirection, and Directions_pskel::_parent_dnaDirectionSet.
Member Data Documentation
_Ignore
std::string Directions_pimpl::_Ignore protected
Definition at line 70 of file dnaparser_pimpl.hxx.
_Target
std::string Directions_pimpl::_Target protected
Definition at line 71 of file dnaparser_pimpl.hxx.
_Value
std::string Directions_pimpl::_Value protected
Definition at line 72 of file dnaparser_pimpl.hxx.
_StdDev
std::string Directions_pimpl::_StdDev protected
Definition at line 73 of file dnaparser_pimpl.hxx.
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx