DynAdjust: dynadjust::datum_parameters::CDnaDatum Class Reference
dynadjust::datum_parameters::CDnaDatum Class Reference
#include <dnadatum.hpp>
Public Member Functions
CDnaDatum (void)
CDnaDatum (const UINT32 &epsgCode)
CDnaDatum (const UINT32 &epsgCode, const boost::gregorian::date &epoch)
CDnaDatum (const std::string &epsgCode, const std::string &epoch)
virtual ~CDnaDatum (void)
CDnaDatum & operator= (const CDnaDatum &rhs)
bool operator== (const CDnaDatum &rhs) const
CDnaEllipsoid GetEllipsoid () const
const CDnaEllipsoid * GetEllipsoidRef () const
std::string GetName () const
std::string GetEpsgCode_s () const
std::string GetEpoch_s () const
UINT32 GetEpsgCode_i () const
boost::gregorian::date GetEpoch () const
DATUM_TYPE GetType () const
bool isStatic () const
bool isDynamic () const
void SetEpoch (const boost::gregorian::date &epoch)
void SetEpoch (const std::string &epoch)
void SetDatum (const UINT32 &epsgCode)
void SetDatum (const UINT32 &epsgCode, const boost::gregorian::date &epoch)
void SetDatum (const std::string &epsgCode)
void SetDatumFromName (const std::string &datumName, const std::string &epoch)
void SetDatumFromEpsg (const std::string &epsgCode, const std::string &epoch)
Private Member Functions
CDnaDatum (const CDnaDatum &newDatum)
void initialiseDatumFromEpsgCode ()
Private Attributes
UINT32 epsgCode_
CDnaEllipsoid ellipsoid_
boost::gregorian::date epoch_
DATUM_TYPE datumType_
std::string datumName_
Detailed Description
Definition at line 50 of file dnadatum.hpp.
Constructor & Destructor Documentation
CDnaDatum() [1/5]
dynadjust::datum_parameters::CDnaDatum::CDnaDatum (void)
Definition at line 32 of file dnadatum.cpp.
    : epsgCode_(DEFAULT_EPSG_U)
    , epoch_(boost::gregorian::date(2020, 1, 1))
    , datumType_(STATIC_DATUM)
    , datumName_(DEFAULT_DATUM)
{
    ellipsoid_.SetEllipsoid(epsgCode_);
}
References datumName_, datumType_, DEFAULT_DATUM(), DEFAULT_EPSG_U(), ellipsoid_, epoch_, epsgCode_, and STATIC_DATUM.
Referenced by CDnaDatum(), operator=(), and operator==().
CDnaDatum() [2/5]
dynadjust::datum_parameters::CDnaDatum::CDnaDatum (const UINT32 & epsgCode)
Definition at line 42 of file dnadatum.cpp.
{
    // Set datum with default epoch of today
    SetDatum(epsgCode);
}
References SetDatum().
CDnaDatum() [3/5]
dynadjust::datum_parameters::CDnaDatum::CDnaDatum (const UINT32 & epsgCode, const boost::gregorian::date & epoch)
Definition at line 48 of file dnadatum.cpp.
{
    SetDatum(epsgCode, epoch);
}
References SetDatum().
CDnaDatum() [4/5]
dynadjust::datum_parameters::CDnaDatum::CDnaDatum (const std::string & epsgCode, const std::string & epoch)
Definition at line 53 of file dnadatum.cpp.
{
    SetDatumFromEpsg(epsgCode, epoch);
}
References SetDatumFromEpsg().
~CDnaDatum()
virtual dynadjust::datum_parameters::CDnaDatum::~CDnaDatum (void) inline virtual
Definition at line 58 of file dnadatum.hpp.
{}
CDnaDatum() [5/5]
dynadjust::datum_parameters::CDnaDatum::CDnaDatum (const CDnaDatum & newDatum) private
References CDnaDatum().
Member Function Documentation
operator=()
CDnaDatum & dynadjust::datum_parameters::CDnaDatum::operator= (const CDnaDatum & rhs)
Definition at line 75 of file dnadatum.cpp.
{
    if (this == &rhs)   // check for assignment to self!
        return *this;
    epsgCode_ = rhs.epsgCode_;
    ellipsoid_ = rhs.ellipsoid_;
    epoch_ = rhs.epoch_;
    datumType_ = rhs.datumType_;
    datumName_ = rhs.datumName_;
    return *this;
}
References CDnaDatum(), datumName_, datumType_, ellipsoid_, epoch_, and epsgCode_.
operator==()
bool dynadjust::datum_parameters::CDnaDatum::operator== (const CDnaDatum & rhs) const
Definition at line 89 of file dnadatum.cpp.
{
    return (
        epsgCode_ == rhs.epsgCode_ &&
        ellipsoid_ == rhs.ellipsoid_ &&
        epoch_ == rhs.epoch_ &&
        datumType_ == rhs.datumType_
        );
}
References CDnaDatum(), datumType_, ellipsoid_, epoch_, and epsgCode_.
GetEllipsoid()
CDnaEllipsoid dynadjust::datum_parameters::CDnaDatum::GetEllipsoid () const inline
Definition at line 75 of file dnadatum.hpp.
{ return ellipsoid_; }
References ellipsoid_.
GetEllipsoidRef()
const CDnaEllipsoid * dynadjust::datum_parameters::CDnaDatum::GetEllipsoidRef () const inline
Definition at line 76 of file dnadatum.hpp.
{ return &ellipsoid_; }
References ellipsoid_.
Referenced by dynadjust::referenceframe::dna_reftran::TransformMeasurement_GX(), dynadjust::referenceframe::dna_reftran::TransformMeasurement_Y(), and dynadjust::referenceframe::dna_reftran::TransformStation().
GetName()
std::string dynadjust::datum_parameters::CDnaDatum::GetName () const inline
Definition at line 78 of file dnadatum.hpp.
{ return datumName_; }
References datumName_.
Referenced by dynadjust::referenceframe::dna_reftran::DetermineElapsedTime(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), main(), dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), dynadjust::iostreams::dna_io_snx::parse_sinex_stn(), dynadjust::measurements::CDnaGpsPoint::PopulateMsr(), dynadjust::measurements::CDnaGpsPointCluster::PopulateMsr(), dynadjust::referenceframe::dna_reftran::TransformDynamic(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformStation(), dynadjust::iostreams::dna_io_dna::write_msr_header(), dynadjust::iostreams::dna_io_dna::write_msr_header(), dynadjust::iostreams::dna_io_dna::write_stn_file(), dynadjust::iostreams::dna_io_dna::write_stn_header(), and dynadjust::iostreams::dna_io_dna::write_stn_header().
GetEpsgCode_s()
std::string dynadjust::datum_parameters::CDnaDatum::GetEpsgCode_s () const
Definition at line 135 of file dnadatum.cpp.
{
    char epsgCode[8];
    snprintf(epsgCode, sizeof(epsgCode), "%d", epsgCode_);
    return std::string(epsgCode);
}
References epsgCode_.
Referenced by dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), dynadjust::iostreams::dna_io_snx::parse_sinex_stn(), dynadjust::measurements::CDnaGpsPoint::PopulateMsr(), and dynadjust::measurements::CDnaGpsPointCluster::PopulateMsr().
GetEpoch_s()
std::string dynadjust::datum_parameters::CDnaDatum::GetEpoch_s () const
Definition at line 126 of file dnadatum.cpp.
{
    if (isEpsgWGS84Ensemble(epsgCode_) && isTimeImmemorial(epoch_))
        return "";
    else if (isTimeImmemorial(epoch_))
        return "";
    return stringFromDate<boost::gregorian::date>(epoch_);
}
References epoch_, epsgCode_, dynadjust::epsg::isEpsgWGS84Ensemble(), isTimeImmemorial(), and stringFromDate().
Referenced by dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), main(), dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), dynadjust::measurements::CDnaGpsPoint::PopulateMsr(), dynadjust::measurements::CDnaGpsPointCluster::PopulateMsr(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformStation(), dynadjust::iostreams::dna_io_dna::write_msr_header(), dynadjust::iostreams::dna_io_dna::write_msr_header(), dynadjust::iostreams::dna_io_dna::write_stn_file(), dynadjust::iostreams::dna_io_dna::write_stn_header(), and dynadjust::iostreams::dna_io_dna::write_stn_header().
GetEpsgCode_i()
UINT32 dynadjust::datum_parameters::CDnaDatum::GetEpsgCode_i () const inline
Definition at line 81 of file dnadatum.hpp.
{ return epsgCode_; }
References epsgCode_.
Referenced by dynadjust::referenceframe::dna_reftran::ObtainHelmertParameters(), dynadjust::referenceframe::dna_reftran::TransformDynamic(), and dynadjust::referenceframe::dna_reftran::TransformFrames_PlateMotionModel().
GetEpoch()
boost::gregorian::date dynadjust::datum_parameters::CDnaDatum::GetEpoch () const inline
Definition at line 82 of file dnadatum.hpp.
{ return epoch_; }
References epoch_.
Referenced by dynadjust::referenceframe::dna_reftran::DetermineElapsedTime(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::iostreams::dna_io_snx::serialise_meta(), dynadjust::iostreams::dna_io_snx::serialise_solution_estimates(), dynadjust::referenceframe::dna_reftran::TransformDynamic(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_PlateMotionModel(), and dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel().
GetType()
DATUM_TYPE dynadjust::datum_parameters::CDnaDatum::GetType () const inline
Definition at line 83 of file dnadatum.hpp.
{ return datumType_; }
References datumType_.
isStatic()
bool dynadjust::datum_parameters::CDnaDatum::isStatic () const inline
Definition at line 84 of file dnadatum.hpp.
{ return datumType_ == STATIC_DATUM; }
References datumType_, and STATIC_DATUM.
Referenced by dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), and dynadjust::referenceframe::dna_reftran::Transform().
isDynamic()
bool dynadjust::datum_parameters::CDnaDatum::isDynamic () const inline
Definition at line 85 of file dnadatum.hpp.
{ return datumType_ == DYNAMIC_DATUM; }
References datumType_, and DYNAMIC_DATUM.
Referenced by dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::referenceframe::dna_reftran::ObtainHelmertParameters(), dynadjust::referenceframe::dna_reftran::Transform(), and dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel().
SetEpoch() [1/2]
void dynadjust::datum_parameters::CDnaDatum::SetEpoch (const boost::gregorian::date & epoch) inline
Definition at line 87 of file dnadatum.hpp.
{ epoch_ = epoch; }
References epoch_.
Referenced by dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::iostreams::dna_io_snx::parse_sinex_header(), dynadjust::iostreams::dna_io_snx::parse_sinex_stn(), SetDatumFromEpsg(), and SetDatumFromName().
SetEpoch() [2/2]
void dynadjust::datum_parameters::CDnaDatum::SetEpoch (const std::string & epoch)
Definition at line 172 of file dnadatum.cpp.
{
    // Parse epoch
    if (epoch.empty())
    {
        if (isEpsgWGS84Ensemble(epsgCode_))
            epoch_ = timeImmemorial<boost::gregorian::date>();
        else
            epoch_ = dateFromString<boost::gregorian::date>(referenceepochFromEpsgCode(epsgCode_));
    }
    else
        epoch_ = dateFromString<boost::gregorian::date>(epoch);
}
References dateFromString(), epoch_, epsgCode_, dynadjust::epsg::isEpsgWGS84Ensemble(), dynadjust::epsg::referenceepochFromEpsgCode(), and timeImmemorial().
SetDatum() [1/3]
void dynadjust::datum_parameters::CDnaDatum::SetDatum (const UINT32 & epsgCode)
Definition at line 142 of file dnadatum.cpp.
{
    epsgCode_ = epsgCode;
    epoch_ = dateFromString<boost::gregorian::date>(referenceepochFromEpsgCode(epsgCode_));
    // set datum parameters using epsg code
    initialiseDatumFromEpsgCode();
}
References dateFromString(), epoch_, epsgCode_, initialiseDatumFromEpsgCode(), and dynadjust::epsg::referenceepochFromEpsgCode().
Referenced by CDnaDatum(), CDnaDatum(), SetDatum(), dynadjust::referenceframe::dna_reftran::TransformMeasurementRecords(), and dynadjust::referenceframe::dna_reftran::TransformStationRecords().
SetDatum() [2/3]
void dynadjust::datum_parameters::CDnaDatum::SetDatum (const UINT32 & epsgCode, const boost::gregorian::date & epoch)
Definition at line 151 of file dnadatum.cpp.
{
    epsgCode_ = epsgCode;
    epoch_ = epoch;
    // set datum parameters using epsg code
    initialiseDatumFromEpsgCode();
}
References epoch_, epsgCode_, and initialiseDatumFromEpsgCode().
SetDatum() [3/3]
void dynadjust::datum_parameters::CDnaDatum::SetDatum (const std::string & epsgCode)
Definition at line 160 of file dnadatum.cpp.
{
    // Reuse
    SetDatum(LongFromString<UINT32>(trimstr(epsgCode)));
}
References LongFromString(), SetDatum(), and trimstr().
SetDatumFromName()
void dynadjust::datum_parameters::CDnaDatum::SetDatumFromName (const std::string & datumName, const std::string & epoch)
Definition at line 192 of file dnadatum.cpp.
{
    // Get epsg code
    epsgCode_ = epsgCodeFromName<UINT32, std::string>(datumName);
    // Parse epoch
    SetEpoch(epoch);
    // set datum parameters using epsg code
    initialiseDatumFromEpsgCode();
}
References epsgCode_, dynadjust::epsg::epsgCodeFromName(), initialiseDatumFromEpsgCode(), and SetEpoch().
Referenced by main(), processFile(), and processGNSSMeasurement().
SetDatumFromEpsg()
void dynadjust::datum_parameters::CDnaDatum::SetDatumFromEpsg (const std::string & epsgCode, const std::string & epoch)
Definition at line 204 of file dnadatum.cpp.
{
    // Get epsg code
    epsgCode_ = LongFromString<UINT32>(trimstr(epsgCode));
    // Check valid epsg code (throws an exception on unknown code)
    validateEpsgCode(epsgCode_);
    // Parse epoch
    SetEpoch(epoch);
    // set datum parameters using epsg code
    initialiseDatumFromEpsgCode();
}
References epsgCode_, initialiseDatumFromEpsgCode(), LongFromString(), SetEpoch(), trimstr(), and dynadjust::epsg::validateEpsgCode().
Referenced by CDnaDatum(), dynadjust::referenceframe::dna_reftran::TransformMeasurementRecords(), and dynadjust::referenceframe::dna_reftran::TransformStationRecords().
initialiseDatumFromEpsgCode()
void dynadjust::datum_parameters::CDnaDatum::initialiseDatumFromEpsgCode () private
Definition at line 108 of file dnadatum.cpp.
{
    // Initialise ellipsoid using epsg code and set epoch if static
    ellipsoid_.SetEllipsoid(epsgCode_);
    // datum type?
    if (isEpsgDatumStatic(epsgCode_))
        datumType_ = STATIC_DATUM;
    else
        datumType_ = DYNAMIC_DATUM;
    // Set name
    datumName_ = datumFromEpsgCode<std::string, UINT32>(epsgCode_);
}
References dynadjust::epsg::datumFromEpsgCode(), datumName_, datumType_, DYNAMIC_DATUM, ellipsoid_, epsgCode_, dynadjust::epsg::isEpsgDatumStatic(), and STATIC_DATUM.
Referenced by SetDatum(), SetDatum(), SetDatumFromEpsg(), and SetDatumFromName().
Member Data Documentation
epsgCode_
UINT32 dynadjust::datum_parameters::CDnaDatum::epsgCode_ private
Definition at line 104 of file dnadatum.hpp.
Referenced by CDnaDatum(), GetEpoch_s(), GetEpsgCode_i(), GetEpsgCode_s(), initialiseDatumFromEpsgCode(), operator=(), operator==(), SetDatum(), SetDatum(), SetDatumFromEpsg(), SetDatumFromName(), and SetEpoch().
ellipsoid_
CDnaEllipsoid dynadjust::datum_parameters::CDnaDatum::ellipsoid_ private
Definition at line 105 of file dnadatum.hpp.
Referenced by CDnaDatum(), GetEllipsoid(), GetEllipsoidRef(), initialiseDatumFromEpsgCode(), operator=(), and operator==().
epoch_
boost::gregorian::date dynadjust::datum_parameters::CDnaDatum::epoch_ private
Definition at line 106 of file dnadatum.hpp.
Referenced by CDnaDatum(), GetEpoch(), GetEpoch_s(), operator=(), operator==(), SetDatum(), SetDatum(), SetEpoch(), and SetEpoch().
datumType_
DATUM_TYPE dynadjust::datum_parameters::CDnaDatum::datumType_ private
Definition at line 107 of file dnadatum.hpp.
Referenced by CDnaDatum(), GetType(), initialiseDatumFromEpsgCode(), isDynamic(), isStatic(), operator=(), and operator==().
datumName_
std::string dynadjust::datum_parameters::CDnaDatum::datumName_ private
Definition at line 108 of file dnadatum.hpp.
Referenced by CDnaDatum(), GetName(), initialiseDatumFromEpsgCode(), and operator=().
The documentation for this class was generated from the following files:
include/parameters/dnadatum.hpp
include/parameters/dnadatum.cpp