DynAdjust: CdnageoidintDlg Class Reference
CdnageoidintDlg Class Reference
#include <dnageoidintDlg.h>
Public Types
enum { IDD = IDD_DNAGEOIDINT_DIALOG }
Public Member Functions
void OnUpdateControls ()
void OnBrowseForFolder ()
int DetermineFileType (const char *cType)
void PrintLogFileMessage (const char *szMessage)
void OnAbout ()
CdnageoidintDlg (CWnd *pParent=NULL)
~CdnageoidintDlg ()
afx_msg void OnFileCreateausgeoid ()
afx_msg void OnFileInterpolate ()
afx_msg LRESULT OnInterpolateInputCoords (WPARAM wParam, LPARAM lParam=0)
afx_msg void OnBnClickedViewLog ()
afx_msg void OnFileSelectausgeoid ()
afx_msg void OnBnClickedInterpolatePoint ()
Public Attributes
int m_intDataFileOpened
int m_intFolderOpened
int m_intGridOpened
char m_selectedDirectory [MAX_PATH]
T_user tUserSettings
FILE * m_fLogFile
bool m_bLogFileOpened
dna_geoid_interpolation m_dnaGeoid
CString m_strDataFile
CString m_strAusGeoidDatFile
BOOL m_intDirRecurse
BOOL m_intDirCheckBox
int m_intEllipsoidtoOrthoRadio
int m_intDmsFlagRadio
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX)
virtual BOOL OnInitDialog ()
afx_msg void OnPaint ()
afx_msg HCURSOR OnQueryDragIcon ()
afx_msg void OnOpenGridFile ()
afx_msg void OnOpenInputData ()
afx_msg void OnClickDirectoryCheckBox ()
afx_msg void OnClickRecurseDirectory ()
afx_msg void OnEllipsOrtho ()
afx_msg void OnOrthoEllips ()
afx_msg void OnFileDdmmss ()
afx_msg void OnTransform ()
afx_msg LRESULT OnSetMessageString (WPARAM wParam, LPARAM lParam=0L, int iPaneIndex=0)
Protected Attributes
HICON m_hIcon
CStatusBar m_statusBar
CInputCoords * m_InputCoordDlg
geoid_point agCoord_
Private Member Functions
void OpenLogFile (void)
void CloseLogFile (void)
void GetSystemDate (char *cBuf, const char *format)
void DeleteLogFile (void)
void CreateGridIndex (void)
Detailed Description
Definition at line 21 of file dnageoidintDlg.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
IDD
Definition at line 47 of file dnageoidintDlg.h.
{ IDD = IDD_DNAGEOIDINT_DIALOG };
Constructor & Destructor Documentation
CdnageoidintDlg()
CdnageoidintDlg::CdnageoidintDlg (CWnd * pParent = NULL)
Definition at line 96 of file dnageoidintDlg.cpp.
    : CDialogEx(CdnageoidintDlg::IDD, pParent)
    , m_fLogFile(NULL)
    , m_bLogFileOpened(false)
    //, m_strDataFile("d:\\my_documents\\geodesy\\ausgeoid\\winter32\\input")
    , m_intDirRecurse(FALSE)
    , m_intDirCheckBox(FALSE)
    , m_intGridOpened(FALSE)
    , m_intDataFileOpened(FALSE)
    , m_intFolderOpened(FALSE)
    , m_intEllipsoidtoOrthoRadio(0)
    , m_intDmsFlagRadio(DMS)        // dd.mmssss
{
    tUserSettings.GridFile = "";
    m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);
    m_InputCoordDlg = NULL;
}
References CdnageoidintDlg(), DMS, FALSE, IDD, IDR_MAINFRAME, m_bLogFileOpened, m_fLogFile, m_hIcon, m_InputCoordDlg, m_intDataFileOpened, m_intDirCheckBox, m_intDirRecurse, m_intDmsFlagRadio, m_intEllipsoidtoOrthoRadio, m_intFolderOpened, m_intGridOpened, and tUserSettings.
Referenced by CdnageoidintDlg().
~CdnageoidintDlg()
CdnageoidintDlg::~CdnageoidintDlg ()
Definition at line 116 of file dnageoidintDlg.cpp.
{
    CloseLogFile();
    if (m_InputCoordDlg != NULL)
        delete m_InputCoordDlg;
    //DeleteLogFile();
}
References CloseLogFile(), and m_InputCoordDlg.
Member Function Documentation
OnUpdateControls()
void CdnageoidintDlg::OnUpdateControls ()
Definition at line 284 of file dnageoidintDlg.cpp.
{
    if (m_intGridOpened)
    {
        GetMenu()->EnableMenuItem(ID_FILE_INTERPOLATE, MF_ENABLED);
        GetDlgItem(IDC_INTERPOLATE_POINT)->EnableWindow(TRUE);
        GetDlgItem(IDC_ST_OPENBOX)->EnableWindow(TRUE);
        GetDlgItem(IDC_INPUT_FILE)->EnableWindow(TRUE);
        GetDlgItem(IDC_OPEN_DATA)->EnableWindow(TRUE);
        //GetDlgItem(IDC_CHECK_DIR)->EnableWindow(TRUE);
        m_intDirRecurse = FALSE;
        // Update status bar
        if(m_intDirCheckBox)
            OnSetMessageString(IDS_TT_DIRMESSAGE);
        else
            OnSetMessageString(IDS_TT_FILEMESSAGE);
        if (m_intDataFileOpened || m_intFolderOpened)
        {
            // Update status bar
            OnSetMessageString(IDS_TT_COMPUTEMESSAGE);
            //GetDlgItem(IDC_ST_HTBOX)->EnableWindow(TRUE);
        }
        GetDlgItem(IDC_ELLIPS_ORTHO)->EnableWindow(TRUE);
        GetDlgItem(IDC_ORTHO_ELLIPS)->EnableWindow(TRUE);
        GetDlgItem(IDC_TRANSFORM)->EnableWindow(TRUE);
        GetDlgItem(IDC_VIEW_LOG)->EnableWindow(TRUE);
        GetDlgItem(IDC_DDMMSS)->EnableWindow(TRUE);
        GetDlgItem(IDC_DDDDDD)->EnableWindow(TRUE);
    }
    else
    {
        GetMenu()->EnableMenuItem(ID_FILE_INTERPOLATE, MF_GRAYED);
        GetDlgItem(IDC_INTERPOLATE_POINT)->EnableWindow(FALSE);
        GetDlgItem(IDC_ST_OPENBOX)->EnableWindow(FALSE);
        GetDlgItem(IDC_INPUT_FILE)->EnableWindow(FALSE);
        GetDlgItem(IDC_OPEN_DATA)->EnableWindow(FALSE);
        //GetDlgItem(IDC_CHECK_DIR)->EnableWindow(FALSE);
        //GetDlgItem(IDC_CHECK_RECURSE)->EnableWindow(FALSE);
        //GetDlgItem(IDC_ST_HTBOX)->EnableWindow(FALSE);
        GetDlgItem(IDC_ELLIPS_ORTHO)->EnableWindow(FALSE);
        GetDlgItem(IDC_ORTHO_ELLIPS)->EnableWindow(FALSE);
        GetDlgItem(IDC_TRANSFORM)->EnableWindow(FALSE);
        GetDlgItem(IDC_VIEW_LOG)->EnableWindow(FALSE);
        GetDlgItem(IDC_DDMMSS)->EnableWindow(FALSE);
        GetDlgItem(IDC_DDDDDD)->EnableWindow(FALSE);
    }
    UpdateData(FALSE);
}
References FALSE, ID_FILE_INTERPOLATE, IDC_DDDDDD, IDC_DDMMSS, IDC_ELLIPS_ORTHO, IDC_INPUT_FILE, IDC_INTERPOLATE_POINT, IDC_OPEN_DATA, IDC_ORTHO_ELLIPS, IDC_ST_OPENBOX, IDC_TRANSFORM, IDC_VIEW_LOG, IDS_TT_COMPUTEMESSAGE, IDS_TT_DIRMESSAGE, IDS_TT_FILEMESSAGE, m_intDataFileOpened, m_intDirCheckBox, m_intDirRecurse, m_intFolderOpened, m_intGridOpened, OnSetMessageString(), and TRUE.
Referenced by OnInitDialog(), OnOpenGridFile(), and OnOpenInputData().
OnBrowseForFolder()
void CdnageoidintDlg::OnBrowseForFolder ()
Definition at line 468 of file dnageoidintDlg.cpp.
{
    LPITEMIDLIST pidlSelected = NULL;
    BROWSEINFO bi = {0};
    LPMALLOC pMalloc = NULL;
    SHGetMalloc(&pMalloc);
    if (pMalloc != NULL)
    {
        ZeroMemory(&bi, sizeof(bi));
        bi.hwndOwner = NULL;
        bi.pidlRoot = 0;
        bi.pszDisplayName = 0;
        bi.lpszTitle = "Select a folder below, then click OK.";
        bi.ulFlags = BIF_RETURNONLYFSDIRS | BIF_STATUSTEXT;
        bi.lpfn = BrowseCallbackProc;
        bi.lParam = 0;
        pidlSelected = SHBrowseForFolder(&bi);
        if(pidlSelected)
        {
            SHGetPathFromIDList(pidlSelected, m_selectedDirectory);
            m_strDataFile = m_selectedDirectory;
            m_intFolderOpened = TRUE;
            m_intDataFileOpened = FALSE;
        }
        pMalloc->Free(pidlSelected);
        pMalloc->Release();
    }
}
References BrowseCallbackProc(), FALSE, m_intDataFileOpened, m_intFolderOpened, m_selectedDirectory, m_strDataFile, and TRUE.
Referenced by OnOpenInputData().
DetermineFileType()
int CdnageoidintDlg::DetermineFileType (const char * cType)
Definition at line 394 of file dnageoidintDlg.cpp.
{
    // case insensitive
    if (boost::iequals(cType, ASC))      // asc "ASCII" file
        return TYPE_ASC;
    else if (boost::iequals(cType, GSB)) // gsb "Binary" file
        return TYPE_GSB;
    else if (boost::iequals(cType, TXT) ||   // dat/txt/prn file
             boost::iequals(cType, DAT) ||   // ..
             boost::iequals(cType, PRN)) // ..
        return TYPE_DAT;
    else if (boost::iequals(cType, CSV)) // csv file
        return TYPE_CSV;
    else
        return -1;                  // Unsupported filetype
}
References ASC, CSV, DAT, GSB, PRN, TXT, TYPE_ASC, TYPE_CSV, TYPE_DAT, and TYPE_GSB.
Referenced by OnOpenInputData().
PrintLogFileMessage()
void CdnageoidintDlg::PrintLogFileMessage (const char * szMessage)
Definition at line 943 of file dnageoidintDlg.cpp.
{
    if (!m_bLogFileOpened)
        return;
    fprintf_s(m_fLogFile, "%s", szMessage);
    fflush(m_fLogFile);
}
References m_bLogFileOpened, and m_fLogFile.
Referenced by CreateGridFile(), CreateGridIndex(), OnFileCreateausgeoid(), OnFileInterpolate(), OnInterpolateInputCoords(), OnTransform(), and OpenLogFile().
OnAbout()
void CdnageoidintDlg::OnAbout ()
Definition at line 159 of file dnageoidintDlg.cpp.
{
    CAboutDlg dlgAbout;
    dlgAbout.DoModal();
}
DoDataExchange()
void CdnageoidintDlg::DoDataExchange (CDataExchange * pDX) protected virtual
Definition at line 124 of file dnageoidintDlg.cpp.
{
    CDialogEx::DoDataExchange(pDX);
    DDX_Text(pDX, IDC_GRIDFILE, tUserSettings.GridFile);
    DDX_Text(pDX, IDC_INPUT_FILE, m_strDataFile);
    DDX_Radio(pDX, IDC_ELLIPS_ORTHO, m_intEllipsoidtoOrthoRadio);
    DDX_Radio(pDX, IDC_DDMMSS, m_intDmsFlagRadio);
}
References IDC_DDMMSS, IDC_ELLIPS_ORTHO, IDC_GRIDFILE, IDC_INPUT_FILE, m_intDmsFlagRadio, m_intEllipsoidtoOrthoRadio, m_strDataFile, and tUserSettings.
OnInitDialog()
BOOL CdnageoidintDlg::OnInitDialog () protected virtual
Definition at line 168 of file dnageoidintDlg.cpp.
{
    CDialogEx::OnInitDialog();
    // Set the icon for this dialog.  The framework does this automatically
    //  when the application's main window is not a dialog
    SetIcon(m_hIcon, TRUE);          // Set big icon
    SetIcon(m_hIcon, FALSE);        // Set small icon
    OpenLogFile();
    // Create status bar at the bottom of the dialog window
    if (m_statusBar.Create(this))
    {
        m_statusBar.SetIndicators(lpIDArray, sizeof(lpIDArray)/sizeof(UINT));
        // Make a sunken or recessed border around the first pane
        m_statusBar.SetPaneInfo(0, IDS_TT_IDLEMESSAGE, SBPS_STRETCH, NULL );
        m_statusBar.SetPaneInfo(1, IDS_TT_PROGRESS, SBPS_NOBORDERS, 85);
        m_statusBar.SetPaneStyle(0, SBPS_NOBORDERS | SBPS_STRETCH);
        // We need to resize the dialog to make room for control bars.
        // First, figure out how big the control bars are.
        CRect rcClientStart;
        CRect rcClientNow;
        GetClientRect(rcClientStart);
        RepositionBars(AFX_IDW_CONTROLBAR_FIRST, AFX_IDW_CONTROLBAR_LAST,
                       0, reposQuery, rcClientNow);
        // Now move all the controls so they are in the same relative
        // position within the remaining client area as they would be
        // with no control bars.
        CPoint ptOffset(rcClientNow.left - rcClientStart.left,
                        rcClientNow.top - rcClientStart.top);
        CRect  rcChild;
        CWnd* pwndChild = GetWindow(GW_CHILD);
        while (pwndChild)
        {
            pwndChild->GetWindowRect(rcChild);
            ScreenToClient(rcChild);
            rcChild.OffsetRect(ptOffset);
            pwndChild->MoveWindow(rcChild, FALSE);
            pwndChild = pwndChild->GetNextWindow();
        }
        // Adjust the dialog window dimensions
        CRect rcWindow;
        GetWindowRect(rcWindow);
        rcWindow.right += rcClientStart.Width() - rcClientNow.Width();
        rcWindow.bottom += rcClientStart.Height() - rcClientNow.Height();
        MoveWindow(rcWindow, FALSE);
        // And position the control bars
        RepositionBars(AFX_IDW_CONTROLBAR_FIRST, AFX_IDW_CONTROLBAR_LAST, 0);
        // Finally, center the dialog on the screen
        CenterWindow();
    }
    else
    {
        TRACE0("Failed to create statusbar.\n");
    }
    long l;
    CFileProc fp;
    if (tUserSettings.GridFile.CompareNoCase(noGridSpecified) == 0)
        m_intGridOpened = FALSE;
    else if (fp.Exists(tUserSettings.GridFile, &l))
        CreateGridIndex();
    else
        m_intGridOpened = FALSE;
    OnUpdateControls();
    return TRUE;  // return TRUE  unless you set the focus to a control
}
References CreateGridIndex(), CFileProc::Exists(), FALSE, IDS_TT_IDLEMESSAGE, IDS_TT_PROGRESS, lpIDArray, m_hIcon, m_intGridOpened, m_statusBar, noGridSpecified, OnUpdateControls(), OpenLogFile(), TRUE, and tUserSettings.
OnPaint()
void CdnageoidintDlg::OnPaint () protected
Definition at line 252 of file dnageoidintDlg.cpp.
{
    if (IsIconic())
    {
        CPaintDC dc(this); // device context for painting
        SendMessage(WM_ICONERASEBKGND, reinterpret_cast<WPARAM>(dc.GetSafeHdc()), 0);
        // Center icon in client rectangle
        int cxIcon = GetSystemMetrics(SM_CXICON);
        int cyIcon = GetSystemMetrics(SM_CYICON);
        CRect rect;
        GetClientRect(&rect);
        int x = (rect.Width() - cxIcon + 1) / 2;
        int y = (rect.Height() - cyIcon + 1) / 2;
        // Draw the icon
        dc.DrawIcon(x, y, m_hIcon);
    }
    else
    {
        CDialogEx::OnPaint();
    }
}
References m_hIcon.
OnQueryDragIcon()
HCURSOR CdnageoidintDlg::OnQueryDragIcon () protected
Definition at line 279 of file dnageoidintDlg.cpp.
{
    return static_cast<HCURSOR>(m_hIcon);
}
References m_hIcon.
OnOpenGridFile()
void CdnageoidintDlg::OnOpenGridFile () protected
Definition at line 342 of file dnageoidintDlg.cpp.
{
    CFileDialog cfOpenFileDlg (TRUE, NULL, NULL, OFN_HIDEREADONLY | OFN_OVERWRITEPROMPT, GRIDFILE_FILTER);
    if (cfOpenFileDlg.DoModal () == IDOK)
    {
        tUserSettings.GridFile = cfOpenFileDlg.GetPathName();
        tUserSettings.GridType = CFileProc::GetExt(tUserSettings.GridFile);
        CreateGridIndex();
    }
    if (tUserSettings.GridFile.IsEmpty())
    {
        m_intGridOpened = FALSE;
        m_intDataFileOpened = FALSE;
    }
    OnUpdateControls();
}
References CreateGridIndex(), FALSE, CFileProc::GetExt(), GRIDFILE_FILTER, m_intDataFileOpened, m_intGridOpened, OnUpdateControls(), TRUE, and tUserSettings.
Referenced by OnFileSelectausgeoid().
OnOpenInputData()
void CdnageoidintDlg::OnOpenInputData () protected
Definition at line 413 of file dnageoidintDlg.cpp.
{
    UpdateData(TRUE);
    int iExt = 0;
    char szExt[4] = "TXT";
    char szFile[MAX_FILEPATH] = "";
    if (!m_strDataFile.IsEmpty())
    {
        sprintf(szFile, "%s", CFileProc::GetName(m_strDataFile, NULL).GetString());
        int i = DetermineFileType(CFileProc::GetExt(m_strDataFile));
        switch (i)
        {
        case TYPE_DAT:
            iExt = 1;
            sprintf(szExt, "TXT");
            break;
        case TYPE_CSV:
            iExt = 2;
            sprintf(szExt, "CSV");
            break;
        }
    }
    CString strFolder = CFileProc::GetFolder(m_strDataFile);
    // show File Open dialog
    CFileProc f;
    CString file = f.FileOpenSave(TRUE, FALSE, strFolder, szFile, SELECT_INPUT_FILE, szExt, INPUTDATA_FILTER, iExt);
    if (file.IsEmpty()) // user pressed cancel
        return;
    switch (m_intDirCheckBox)
    {
    case 0:
        m_strDataFile = file;
        m_intDataFileOpened = TRUE;
        m_intFolderOpened = FALSE;
        OnUpdateControls();
        break;
    case 1:
        // show Browse for Folder dialog
        OnBrowseForFolder();
        OnUpdateControls();
        break;
    default:
        TRACE0("Error retrieving checkbox status.");
        break;
    }
}
References DetermineFileType(), FALSE, CFileProc::FileOpenSave(), CFileProc::GetExt(), CFileProc::GetFolder(), CFileProc::GetName(), INPUTDATA_FILTER, m_intDataFileOpened, m_intDirCheckBox, m_intFolderOpened, m_strDataFile, MAX_FILEPATH, OnBrowseForFolder(), OnUpdateControls(), SELECT_INPUT_FILE, TRUE, TYPE_CSV, and TYPE_DAT.
OnClickDirectoryCheckBox()
void CdnageoidintDlg::OnClickDirectoryCheckBox () protected
Definition at line 503 of file dnageoidintDlg.cpp.
{
    UpdateData(TRUE);
    switch (m_intDirCheckBox)
    {
    case 0:
        GetDlgItem(IDC_CHECK_RECURSE)->EnableWindow(FALSE);
        if (!m_intDataFileOpened && !m_intFolderOpened)
            OnSetMessageString(IDS_TT_FILEMESSAGE);
        if (m_intFolderOpened)
        {
            m_intFolderOpened = FALSE;
            m_strDataFile = "";
        }
        break;
    case 1:
        GetDlgItem(IDC_CHECK_RECURSE)->EnableWindow(TRUE);
        if (!m_intDataFileOpened && !m_intFolderOpened)
        {
            if (m_intDirRecurse)
                OnSetMessageString(IDS_TT_RECURSEMESSAGE);
            else
                OnSetMessageString(IDS_TT_DIRMESSAGE);
        }
        if (m_intDataFileOpened)
        {
            m_intDataFileOpened = FALSE;
            m_strDataFile = "";
        }
        break;
    default:
        TRACE0("Error retrieving checkbox status.");
        break;
    }
    UpdateData(FALSE);
}
References FALSE, IDC_CHECK_RECURSE, IDS_TT_DIRMESSAGE, IDS_TT_FILEMESSAGE, IDS_TT_RECURSEMESSAGE, m_intDataFileOpened, m_intDirCheckBox, m_intDirRecurse, m_intFolderOpened, m_strDataFile, OnSetMessageString(), and TRUE.
OnClickRecurseDirectory()
void CdnageoidintDlg::OnClickRecurseDirectory () protected
Definition at line 544 of file dnageoidintDlg.cpp.
{
    UpdateData(TRUE);
    if (!m_intDataFileOpened && !m_intFolderOpened)
    {
        if (m_intDirRecurse)
            OnSetMessageString(IDS_TT_RECURSEMESSAGE);
        else
            OnSetMessageString(IDS_TT_DIRMESSAGE);
    }
    // TRACE1("Directory checkbox status: %d\n", m_intDirRecurse);
}
References IDS_TT_DIRMESSAGE, IDS_TT_RECURSEMESSAGE, m_intDataFileOpened, m_intDirRecurse, m_intFolderOpened, OnSetMessageString(), and TRUE.
OnEllipsOrtho()
void CdnageoidintDlg::OnEllipsOrtho () protected
Definition at line 559 of file dnageoidintDlg.cpp.
{
    UpdateData(TRUE);
}
References TRUE.
OnOrthoEllips()
void CdnageoidintDlg::OnOrthoEllips () protected
Definition at line 565 of file dnageoidintDlg.cpp.
{
    UpdateData(TRUE);
}
References TRUE.
OnFileDdmmss()
void CdnageoidintDlg::OnFileDdmmss () protected
Definition at line 571 of file dnageoidintDlg.cpp.
{
    UpdateData(TRUE);
}
References TRUE.
OnTransform()
void CdnageoidintDlg::OnTransform () protected
Definition at line 577 of file dnageoidintDlg.cpp.
{
    char chDirectory[MAX_PATH], *ext;
    char chFilename[MAX_PATH];
    char chFilenameOut[MAX_PATH];
    int i;
    CString msg;
    if (!m_intDataFileOpened && !m_intFolderOpened)
        return;
    UpdateData(TRUE);
    CFileProc fileProc;
    // open grid file
    try {
        m_dnaGeoid.CreateGridIndex((char*)((LPCTSTR)tUserSettings.GridFile), (char*)((LPCTSTR)tUserSettings.GridType));
    }
    catch (const NetGeoidException& e) {
        PrintLogFileMessage(e.what());
        PrintLogFileMessage("\n\n");
        MessageBox(e.what(), m_dnaGeoid.ErrorCaption(e.error_no()).c_str(), MB_OK | MB_ICONEXCLAMATION);
        return;
    }
    tUserSettings.GridFileStatus = 0;
    strcpy(chDirectory, m_strDataFile);
    std::vector<std::string> file_type_array;
    file_type_array.push_back("dat");
    file_type_array.push_back("csv");
    // create the list of files to process
    if (m_intFolderOpened)
        fileProc.BuildFileArray(chDirectory, file_type_array, (int)file_type_array.size());       // working with a directory
    else
    {
        // working with a single file
        i = m_strDataFile.ReverseFind('\\');
        if (i != -1)
        {
            strcpy(chFilename, m_strDataFile.Mid(i+1));
            strcpy(chDirectory, m_strDataFile.Mid(0, i));
        }
        else
            return;         // invalid file
        fileProc.EnterSingleFile(chFilename);
    }
    if (m_intEllipsoidtoOrthoRadio == 0)
        PrintLogFileMessage("Converting ellipsoidal heights to orthometric\n\n");
    else
        PrintLogFileMessage("Converting orthometric heights to ellipsoidal\n\n");
    char message[200];
    sprintf(message, "%d file(s) to be processed\n\n", fileProc.m_intNumFiles);
    PrintLogFileMessage(message);
    // no file to transform
    if (fileProc.m_fIndex == NULL)
        MessageBox("No *.dat or *.csv files were found in the specified directory.\n", "Warning", MB_OK | MB_ICONWARNING);
    else
    {
        // display the hourglass cursor
        BeginWaitCursor();
        PrintLogFileMessage("Transforming files...\n\n");
        for (i=0; i<fileProc.m_intNumFiles; i++)
        {
            msg = "Transforming file ";
            msg += fileProc.m_fIndex[i].chfilename;
            strcpy(chFilename, chDirectory);
            strcat(chFilename, "\\");
            strcat(chFilename, fileProc.m_fIndex[i].chfilename);
            m_statusBar.SetPaneText(0, msg, TRUE);
            sprintf(message, "%s\n", chFilename);
            PrintLogFileMessage(message);
            strcpy(chFilenameOut, chFilename);
            if ((ext = strrchr(chFilenameOut, '.')) == NULL)
                sprintf(chFilenameOut, "%s_out", chFilename);
            else
            {
                char extension[4];
                strcpy(extension, ext+1);
                chFilenameOut[ext-chFilenameOut] = '\0';
                sprintf(chFilenameOut, "%s_out.%s", chFilenameOut, extension);
            }
            try {
                m_dnaGeoid.FileTransformation(chFilename, chFilenameOut, BICUBIC, !m_intEllipsoidtoOrthoRadio, m_intDmsFlagRadio, false);
            }
            catch (const NetGeoidException& e) {
                PrintLogFileMessage(e.what());
                PrintLogFileMessage("\n\n");
                MessageBox(e.what(), m_dnaGeoid.ErrorCaption(e.error_no()).c_str(), MB_OK | MB_ICONEXCLAMATION);
                return;
            }
        }
        PrintLogFileMessage("\nDone!\n\n");
        // restore the default (arrow) cursor
        EndWaitCursor();
        OnSetMessageString(IDS_TT_FILEMESSAGE);
        MessageBox("All files were successfully transformed.\n\nView the log file for details.\n", "Transformation complete",
            MB_OK | MB_ICONINFORMATION);
    }
}
References BICUBIC, CFileProc::BuildFileArray(), _fileindex::chfilename, CFileProc::EnterSingleFile(), dynadjust::exception::NetGeoidException::error_no(), IDS_TT_FILEMESSAGE, m_dnaGeoid, CFileProc::m_fIndex, m_intDataFileOpened, m_intDmsFlagRadio, m_intEllipsoidtoOrthoRadio, m_intFolderOpened, CFileProc::m_intNumFiles, m_statusBar, m_strDataFile, OnSetMessageString(), PrintLogFileMessage(), TRUE, tUserSettings, and dynadjust::exception::NetGeoidException::what().
OnSetMessageString()
LRESULT CdnageoidintDlg::OnSetMessageString (WPARAM wParam, LPARAM lParam = 0L, int iPaneIndex = 0) protected
Definition at line 696 of file dnageoidintDlg.cpp.
{
    UINT    nIDMsg = (UINT)wParam;
    CString strMsg;
    if (nIDMsg)
    {
        if (strMsg.LoadString(nIDMsg) != 0)
            m_statusBar.SetPaneText(iPaneIndex, strMsg, TRUE);
        else
            TRACE1("Warning: no message line prompt for ID %x%04X\n", nIDMsg);
    }
    return nIDMsg;
}
References m_statusBar, and TRUE.
Referenced by OnClickDirectoryCheckBox(), OnClickRecurseDirectory(), OnTransform(), and OnUpdateControls().
OnFileCreateausgeoid()
void CdnageoidintDlg::OnFileCreateausgeoid ()
Definition at line 712 of file dnageoidintDlg.cpp.
{
    CFileDialog cfOpenFileDlg (TRUE, NULL, NULL, OFN_HIDEREADONLY | OFN_OVERWRITEPROMPT, AUSGEOIDDATA_FILTER);
    // show File Open dialog
    if (cfOpenFileDlg.DoModal () != IDOK)
        return;
    // Back up old settings
    T_user  currentSettings;
    currentSettings = tUserSettings;
    BeginWaitCursor();
    m_strAusGeoidDatFile = cfOpenFileDlg.GetPathName();
    tUserSettings.GridFile = m_strAusGeoidDatFile + ".gsb";
    tUserSettings.GridType = "gsb";
    CString strbuf;
    strbuf.Format("Creating NTv2 grid file from %s... ", m_strAusGeoidDatFile);
    PrintLogFileMessage(strbuf);
    // set up progress bar
    RECT rc;
    BOOL FileProgCreated;
    m_statusBar.GetItemRect(1, &rc);
    CProgressCtrl *FileProgress = new CProgressCtrl;
    if (FileProgress->Create(WS_CHILD | WS_VISIBLE | PBS_SMOOTH, rc, &m_statusBar, 0))
    {
        FileProgCreated = TRUE;
        FileProgress->SetRange(0, 100);
    }
    m_statusBar.SetPaneStyle(1, SBPS_NORMAL);
    CreatingGrid = TRUE;
    AfxBeginThread(CreateGridFile, (void*)this, THREAD_PRIORITY_NORMAL);
    if (FileProgCreated)
    {
        int file_progress;
        CFileProc fp;
        while (CreatingGrid)
        {
            Sleep(100);
            file_progress = m_dnaGeoid.ReturnFileProgress();
            FileProgress->SetPos(file_progress);
            if (file_progress < 0.0)
                strbuf.Format("Checking %s...", fp.GetName(m_strAusGeoidDatFile, 0));
            else
                strbuf.Format("Creating %s...", fp.GetName(tUserSettings.GridFile, 0));
            m_statusBar.SetPaneText(0, strbuf, TRUE);
            UpdateWindow();
        }
        delete FileProgress;
    }
    m_statusBar.SetPaneText(0, "Done.", TRUE);
    EndWaitCursor();
    PrintLogFileMessage("Done\n\n");
    strbuf.Format("Successfully created %s!\n\n", tUserSettings.GridFile);
    PrintLogFileMessage(strbuf);
    // Restore old settings
    tUserSettings = currentSettings;
}
References AUSGEOIDDATA_FILTER, CreateGridFile(), CreatingGrid, CFileProc::GetName(), m_dnaGeoid, m_statusBar, m_strAusGeoidDatFile, PrintLogFileMessage(), TRUE, and tUserSettings.
OnFileInterpolate()
void CdnageoidintDlg::OnFileInterpolate ()
Definition at line 781 of file dnageoidintDlg.cpp.
{
    if (tUserSettings.GridFile.CompareNoCase(noGridSpecified) == 0)
    {
        MessageBox("A grid file has not been selected.\n\nClick Browse to select a NTv2 geoid grid file.", "No grid file", MB_OK | MB_ICONEXCLAMATION);
        return;
    }
    if (m_InputCoordDlg == NULL)
    {
        m_InputCoordDlg = new CInputCoords();
        if(!m_InputCoordDlg->Create(IDD_INPUT_COORD, this))   //Create failed.
            return;
    }
    m_InputCoordDlg->ShowWindow(SW_SHOW);
    if (m_intGridOpened == FALSE && agCoord_.cVar.IO_Status != 0)
    {
        try {
            m_dnaGeoid.CreateGridIndex((char*)((LPCTSTR)tUserSettings.GridFile), (char*)((LPCTSTR)tUserSettings.GridType));
            m_InputCoordDlg->SetSuccess(true);
        }
        catch (const NetGeoidException& e) {
            tUserSettings.GridFileStatus = agCoord_.cVar.IO_Status;
            PrintLogFileMessage(e.what());
            PrintLogFileMessage("\n\n");
            MessageBox(e.what(), m_dnaGeoid.ErrorCaption(e.error_no()).c_str(), MB_OK | MB_ICONEXCLAMATION);
            m_InputCoordDlg->SetSuccess(false);
            return;
        }
    }
}
References agCoord_, dynadjust::exception::NetGeoidException::error_no(), FALSE, IDD_INPUT_COORD, m_dnaGeoid, m_InputCoordDlg, m_intGridOpened, noGridSpecified, PrintLogFileMessage(), tUserSettings, and dynadjust::exception::NetGeoidException::what().
Referenced by OnBnClickedInterpolatePoint().
OnInterpolateInputCoords()
LRESULT CdnageoidintDlg::OnInterpolateInputCoords (WPARAM wParam, LPARAM lParam = 0)
Definition at line 817 of file dnageoidintDlg.cpp.
{
    if (m_intGridOpened == FALSE)
    {
        MessageBox("A grid file has not been selected.\n\nClick Browse to select a NTv2 geoid grid file.", "No grid file", MB_OK | MB_ICONEXCLAMATION);
        return 0;
    }
    if (m_InputCoordDlg == NULL)
        return 0;
    char message[200];
    switch (m_InputCoordDlg->GetDMS())
    {
    case DMS:
        agCoord_.cVar.dLatitude = DmstoDeg(m_InputCoordDlg->GetLatitudeInput());
        agCoord_.cVar.dLongitude = DmstoDeg(m_InputCoordDlg->GetLongitudeInput());
        break;
    //case DMIN:
    //  agCoord_.cVar.dLatitude = DmintoDeg(m_InputCoordDlg->GetLatitudeInput());
    //  agCoord_.cVar.dLongitude = DmintoDeg(m_InputCoordDlg->GetLongitudeInput());
    //  break;
    case DDEG:
        agCoord_.cVar.dLatitude = m_InputCoordDlg->GetLatitudeInput();   // S 12 14' 55.92960"
        agCoord_.cVar.dLongitude = m_InputCoordDlg->GetLongitudeInput(); // E 142 03' 36.18000"
        break;
    }
    try {
        m_dnaGeoid.BiCubicTransformation(&agCoord_);
        m_InputCoordDlg->SetSuccess(true);
    }
    catch (const NetGeoidException& e) {
        PrintLogFileMessage(e.what());
        PrintLogFileMessage("\n\n");
        if (agCoord_.cVar.IO_Status == ERR_FINDSUBGRID_OUTSIDE ||
            agCoord_.cVar.IO_Status == ERR_PT_OUTSIDE_GRID)
        {
            // 13:  Point is outside limits of the grid
            std::stringstream ss;
            ss << ">>  " << std::fixed << std::setprecision(9) << agCoord_.cVar.dLatitude << ", " << std::fixed << std::setprecision(9) << agCoord_.cVar.dLongitude << std::endl << std::endl;
            PrintLogFileMessage(ss.str().c_str());
        }
        MessageBox(e.what(), m_dnaGeoid.ErrorCaption(e.error_no()).c_str(), MB_OK | MB_ICONEXCLAMATION);
        m_InputCoordDlg->SetSuccess(false);
        return 0;
    }
    m_InputCoordDlg->SetNValue(agCoord_.gVar.dN_value);
    m_InputCoordDlg->SetPMeridian(agCoord_.gVar.dDefl_meridian);
    m_InputCoordDlg->SetPVertical(agCoord_.gVar.dDefl_primev);
    m_InputCoordDlg->SendMessage(IDM_UPDATE_INTERPOLATION_RESULTS, 0, 0);
    sprintf(message, "Latitude:%12.7f, Longitude:%12.7f, N:%12.4f, dPm:%10.4f, dPv:%10f\n",
        agCoord_.cVar.dLatitude, agCoord_.cVar.dLongitude,
        agCoord_.gVar.dN_value, agCoord_.gVar.dDefl_meridian, agCoord_.gVar.dDefl_primev);
    PrintLogFileMessage(message);
    return 0;
}
References agCoord_, DDEG, DMS, DmstoDeg(), ERR_FINDSUBGRID_OUTSIDE, ERR_PT_OUTSIDE_GRID, dynadjust::exception::NetGeoidException::error_no(), FALSE, IDM_UPDATE_INTERPOLATION_RESULTS, m_dnaGeoid, m_InputCoordDlg, m_intGridOpened, PrintLogFileMessage(), and dynadjust::exception::NetGeoidException::what().
OnBnClickedViewLog()
void CdnageoidintDlg::OnBnClickedViewLog ()
Definition at line 883 of file dnageoidintDlg.cpp.
{
    fclose(m_fLogFile);
    CFileProc fp;
    fp.Copy(tUserSettings.LogFile, fp.GetFolder(tUserSettings.LogFile));
    fp.View(fp.m_strDestinationFile, "notepad.exe");
    if (fopen_s(&m_fLogFile, tUserSettings.LogFile, "a") != 0)
        m_bLogFileOpened = false;
    else
        m_bLogFileOpened = true;
}
References CFileProc::Copy(), CFileProc::GetFolder(), m_bLogFileOpened, m_fLogFile, CFileProc::m_strDestinationFile, tUserSettings, and CFileProc::View().
OpenLogFile()
void CdnageoidintDlg::OpenLogFile (void) private
Definition at line 897 of file dnageoidintDlg.cpp.
{
    if (fopen_s(&m_fLogFile, tUserSettings.LogFile, "w") != 0)
    {
        m_bLogFileOpened = false;
        return;
    }
    else
        m_bLogFileOpened = true;
    PrintLogFileMessage("//////////////  AusGeoid-Interpolation Log File  //////////////\n\n");
    // get system date
    char cBuf[50];
    char message[250];
    CString strHeader;
    GetSystemDate(cBuf, DATE_LONG);
    sprintf(message, "Date:  %s\n\n\n", cBuf);
    PrintLogFileMessage(message);
}
References DATE_LONG, GetSystemDate(), m_bLogFileOpened, m_fLogFile, PrintLogFileMessage(), and tUserSettings.
Referenced by OnInitDialog().
CloseLogFile()
void CdnageoidintDlg::CloseLogFile (void) private
Definition at line 936 of file dnageoidintDlg.cpp.
{
    fclose(m_fLogFile);
    m_bLogFileOpened = false;
}
References m_bLogFileOpened, and m_fLogFile.
Referenced by ~CdnageoidintDlg().
GetSystemDate()
void CdnageoidintDlg::GetSystemDate (char * cBuf, const char * format) private
Definition at line 926 of file dnageoidintDlg.cpp.
{
    struct tm *today;
    time_t ltime;
    time(&ltime);
    today = localtime(&ltime);
    strftime(cBuf, 100, format, today);
}
Referenced by OpenLogFile().
DeleteLogFile()
void CdnageoidintDlg::DeleteLogFile (void) private
Definition at line 951 of file dnageoidintDlg.cpp.
{
    CFileProc fileProc;
    std::vector<std::string> file_type_array;
    file_type_array.push_back("log");
    char chDirectory[MAX_PATH];
    char chFilename[MAX_PATH];
    strcpy(chDirectory, fileProc.GetFolder(tUserSettings.LogFile));
    fileProc.BuildFileArray(chDirectory, file_type_array, (int)file_type_array.size());
    for (int i=0; i<fileProc.m_intNumFiles; i++)
    {
        strcpy(chFilename, chDirectory);
        strcat(chFilename, "\\");
        strcat(chFilename, fileProc.m_fIndex[i].chfilename);
        fileProc.Delete(chFilename);
    }
}
References CFileProc::BuildFileArray(), _fileindex::chfilename, CFileProc::Delete(), CFileProc::GetFolder(), CFileProc::m_fIndex, CFileProc::m_intNumFiles, and tUserSettings.
CreateGridIndex()
void CdnageoidintDlg::CreateGridIndex (void) private
Definition at line 363 of file dnageoidintDlg.cpp.
{
    // open grid file
    try {
        m_dnaGeoid.CreateGridIndex((char*)((LPCTSTR)tUserSettings.GridFile), (char*)((LPCTSTR)tUserSettings.GridType));
        char version[21];
        m_dnaGeoid.ReportGridVersion(version);
        std::stringstream ss;
        ss << "Opened Grid file  " << std::left << tUserSettings.GridFile << ", Version " << version << std::endl << std::endl;
        PrintLogFileMessage(ss.str().c_str());
    }
    catch (const NetGeoidException& e) {
        PrintLogFileMessage(e.what());
        PrintLogFileMessage("\n\n");
        MessageBox(e.what(), m_dnaGeoid.ErrorCaption(e.error_no()).c_str(), MB_OK | MB_ICONEXCLAMATION);
        m_intGridOpened = FALSE;
        return;
    }
    m_intGridOpened = TRUE;
}
References dynadjust::exception::NetGeoidException::error_no(), FALSE, m_dnaGeoid, m_intGridOpened, PrintLogFileMessage(), TRUE, tUserSettings, and dynadjust::exception::NetGeoidException::what().
Referenced by OnInitDialog(), and OnOpenGridFile().
OnFileSelectausgeoid()
void CdnageoidintDlg::OnFileSelectausgeoid ()
Definition at line 972 of file dnageoidintDlg.cpp.
{
    OnOpenGridFile();
}
References OnOpenGridFile().
OnBnClickedInterpolatePoint()
void CdnageoidintDlg::OnBnClickedInterpolatePoint ()
Definition at line 977 of file dnageoidintDlg.cpp.
{
    OnFileInterpolate();
}
References OnFileInterpolate().
Member Data Documentation
m_intDataFileOpened
int CdnageoidintDlg::m_intDataFileOpened
Definition at line 25 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), OnBrowseForFolder(), OnClickDirectoryCheckBox(), OnClickRecurseDirectory(), OnOpenGridFile(), OnOpenInputData(), OnTransform(), and OnUpdateControls().
m_intFolderOpened
int CdnageoidintDlg::m_intFolderOpened
Definition at line 26 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), OnBrowseForFolder(), OnClickDirectoryCheckBox(), OnClickRecurseDirectory(), OnOpenInputData(), OnTransform(), and OnUpdateControls().
m_intGridOpened
int CdnageoidintDlg::m_intGridOpened
Definition at line 27 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), CreateGridIndex(), OnFileInterpolate(), OnInitDialog(), OnInterpolateInputCoords(), OnOpenGridFile(), and OnUpdateControls().
m_selectedDirectory
char CdnageoidintDlg::m_selectedDirectory[MAX_PATH]
Definition at line 28 of file dnageoidintDlg.h.
Referenced by OnBrowseForFolder().
tUserSettings
T_user CdnageoidintDlg::tUserSettings
Definition at line 36 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), CreateGridFile(), CreateGridIndex(), DeleteLogFile(), DoDataExchange(), CdnageoidintApp::InitInstance(), OnBnClickedViewLog(), OnFileCreateausgeoid(), OnFileInterpolate(), OnInitDialog(), OnOpenGridFile(), OnTransform(), and OpenLogFile().
m_fLogFile
FILE* CdnageoidintDlg::m_fLogFile
Definition at line 37 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), CloseLogFile(), OnBnClickedViewLog(), OpenLogFile(), and PrintLogFileMessage().
m_bLogFileOpened
bool CdnageoidintDlg::m_bLogFileOpened
Definition at line 38 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), CloseLogFile(), OnBnClickedViewLog(), OpenLogFile(), and PrintLogFileMessage().
m_dnaGeoid
dna_geoid_interpolation CdnageoidintDlg::m_dnaGeoid
Definition at line 41 of file dnageoidintDlg.h.
Referenced by CreateGridFile(), CreateGridIndex(), OnFileCreateausgeoid(), OnFileInterpolate(), OnInterpolateInputCoords(), and OnTransform().
m_strDataFile
CString CdnageoidintDlg::m_strDataFile
Definition at line 48 of file dnageoidintDlg.h.
Referenced by DoDataExchange(), OnBrowseForFolder(), OnClickDirectoryCheckBox(), OnOpenInputData(), and OnTransform().
m_strAusGeoidDatFile
CString CdnageoidintDlg::m_strAusGeoidDatFile
Definition at line 49 of file dnageoidintDlg.h.
Referenced by CreateGridFile(), and OnFileCreateausgeoid().
m_intDirRecurse
BOOL CdnageoidintDlg::m_intDirRecurse
Definition at line 50 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), OnClickDirectoryCheckBox(), OnClickRecurseDirectory(), and OnUpdateControls().
m_intDirCheckBox
BOOL CdnageoidintDlg::m_intDirCheckBox
Definition at line 51 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), OnClickDirectoryCheckBox(), OnOpenInputData(), and OnUpdateControls().
m_intEllipsoidtoOrthoRadio
int CdnageoidintDlg::m_intEllipsoidtoOrthoRadio
Definition at line 52 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), DoDataExchange(), and OnTransform().
m_intDmsFlagRadio
int CdnageoidintDlg::m_intDmsFlagRadio
Definition at line 53 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), DoDataExchange(), and OnTransform().
m_hIcon
HICON CdnageoidintDlg::m_hIcon protected
Definition at line 61 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), OnInitDialog(), OnPaint(), and OnQueryDragIcon().
m_statusBar
CStatusBar CdnageoidintDlg::m_statusBar protected
Definition at line 63 of file dnageoidintDlg.h.
Referenced by OnFileCreateausgeoid(), OnInitDialog(), OnSetMessageString(), and OnTransform().
m_InputCoordDlg
CInputCoords* CdnageoidintDlg::m_InputCoordDlg protected
Definition at line 65 of file dnageoidintDlg.h.
Referenced by CdnageoidintDlg(), OnFileInterpolate(), OnInterpolateInputCoords(), and ~CdnageoidintDlg().
agCoord_
geoid_point CdnageoidintDlg::agCoord_ protected
Definition at line 67 of file dnageoidintDlg.h.
Referenced by OnFileInterpolate(), and OnInterpolateInputCoords().
The documentation for this class was generated from the following files:
dynadjust/dnageoidint/dnageoidintDlg.h
dynadjust/dnageoidint/dnageoidintDlg.cpp