DynAdjust: StationCoord_pskel Class Reference
StationCoord_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void Name (const ::std::string &)
virtual void XAxis (const ::std::string &)
virtual void YAxis (const ::std::string &)
virtual void Height ()
virtual void HemisphereZone (const ::std::string &)
virtual void GeoidModel ()
virtual void post_StationCoord ()
void Name_parser (::xml_schema::string_pskel &)
void XAxis_parser (::xml_schema::string_pskel &)
void YAxis_parser (::xml_schema::string_pskel &)
void Height_parser (::Height_pskel &)
void HemisphereZone_parser (::xml_schema::string_pskel &)
void GeoidModel_parser (::GeoidModel_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::Height_pskel &, ::xml_schema::string_pskel &, ::GeoidModel_pskel &)
StationCoord_pskel ()
void InitparentStn (dnaStnPtr pStn)
Protected Member Functions
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * Name_parser_
::xml_schema::string_pskel * XAxis_parser_
::xml_schema::string_pskel * YAxis_parser_
::Height_pskel * Height_parser_
::xml_schema::string_pskel * HemisphereZone_parser_
::GeoidModel_pskel * GeoidModel_parser_
dnaStnPtr _parent_dnaStn
Detailed Description
Definition at line 1140 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
StationCoord_pskel()
StationCoord_pskel::StationCoord_pskel ()
Definition at line 818 of file dnaparser_pskel.cxx.
    : Name_parser_ (0),
    XAxis_parser_ (0),
    YAxis_parser_ (0),
    Height_parser_ (0),
    HemisphereZone_parser_ (0),
    GeoidModel_parser_ (0)
{
}
References GeoidModel_parser_, Height_parser_, HemisphereZone_parser_, Name_parser_, XAxis_parser_, and YAxis_parser_.
Member Function Documentation
Name()
void StationCoord_pskel::Name (const ::std::string &) virtual
Reimplemented in StationCoord_pimpl.
Definition at line 2948 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
XAxis()
void StationCoord_pskel::XAxis (const ::std::string &) virtual
Reimplemented in StationCoord_pimpl.
Definition at line 2952 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
YAxis()
void StationCoord_pskel::YAxis (const ::std::string &) virtual
Reimplemented in StationCoord_pimpl.
Definition at line 2956 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Height()
void StationCoord_pskel::Height () virtual
Definition at line 2960 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
HemisphereZone()
void StationCoord_pskel::HemisphereZone (const ::std::string &) virtual
Reimplemented in StationCoord_pimpl.
Definition at line 2964 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
GeoidModel()
void StationCoord_pskel::GeoidModel () virtual
Reimplemented in StationCoord_pimpl.
Definition at line 2968 of file dnaparser_pskel.cxx.
{
}
Referenced by parsers().
post_StationCoord()
void StationCoord_pskel::post_StationCoord () virtual
Reimplemented in StationCoord_pimpl.
Definition at line 2972 of file dnaparser_pskel.cxx.
{
}
Name_parser()
void StationCoord_pskel::Name_parser (::xml_schema::string_pskel & p)
Definition at line 773 of file dnaparser_pskel.cxx.
{
    this->Name_parser_ = &p;
}
References Name_parser_.
XAxis_parser()
void StationCoord_pskel::XAxis_parser (::xml_schema::string_pskel & p)
Definition at line 778 of file dnaparser_pskel.cxx.
{
    this->XAxis_parser_ = &p;
}
References XAxis_parser_.
YAxis_parser()
void StationCoord_pskel::YAxis_parser (::xml_schema::string_pskel & p)
Definition at line 783 of file dnaparser_pskel.cxx.
{
    this->YAxis_parser_ = &p;
}
References YAxis_parser_.
Height_parser()
void StationCoord_pskel::Height_parser (::Height_pskel & p)
Definition at line 788 of file dnaparser_pskel.cxx.
{
    this->Height_parser_ = &p;
}
References Height_parser_.
HemisphereZone_parser()
void StationCoord_pskel::HemisphereZone_parser (::xml_schema::string_pskel & p)
Definition at line 793 of file dnaparser_pskel.cxx.
{
    this->HemisphereZone_parser_ = &p;
}
References HemisphereZone_parser_.
GeoidModel_parser()
void StationCoord_pskel::GeoidModel_parser (::GeoidModel_pskel & p)
Definition at line 798 of file dnaparser_pskel.cxx.
{
    this->GeoidModel_parser_ = &p;
}
References GeoidModel_parser_.
parsers()
void StationCoord_pskel::parsers (::xml_schema::string_pskel & Name, ::xml_schema::string_pskel & XAxis, ::xml_schema::string_pskel & YAxis, ::Height_pskel & Height, ::xml_schema::string_pskel & HemisphereZone, ::GeoidModel_pskel & GeoidModel)
Definition at line 803 of file dnaparser_pskel.cxx.
{
    this->Name_parser_ = &Name;
    this->XAxis_parser_ = &XAxis;
    this->YAxis_parser_ = &YAxis;
    this->Height_parser_ = &Height;
    this->HemisphereZone_parser_ = &HemisphereZone;
    this->GeoidModel_parser_ = &GeoidModel;
}
References GeoidModel(), GeoidModel_parser_, Height(), Height_parser_, HemisphereZone(), HemisphereZone_parser_, Name(), Name_parser_, XAxis(), XAxis_parser_, YAxis(), and YAxis_parser_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
InitparentStn()
void StationCoord_pskel::InitparentStn (dnaStnPtr pStn) inline
Definition at line 1177 of file dnaparser_pskel.hxx.
{   _parent_dnaStn = pStn; }
References _parent_dnaStn.
_start_element_impl()
bool StationCoord_pskel::_start_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string * t) protected virtual
Definition at line 2976 of file dnaparser_pskel.cxx.
{
    XSD_UNUSED (t);
    if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
        return true;
    if (n == "Name" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Name_parser_;
        if (this->Name_parser_)
            this->Name_parser_->pre ();
        return true;
    }
    if (n == "XAxis" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->XAxis_parser_;
        if (this->XAxis_parser_)
            this->XAxis_parser_->pre ();
        return true;
    }
    if (n == "YAxis" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->YAxis_parser_;
        if (this->YAxis_parser_)
            this->YAxis_parser_->pre ();
        return true;
    }
    if (n == "Height" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Height_parser_;
        if (this->Height_parser_)
        {
            // Initialise
            this->Height_parser_->InitparentStn(_parent_dnaStn);
            this->Height_parser_->pre ();
        }
        return true;
    }
    if (n == "HemisphereZone" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->HemisphereZone_parser_;
        if (this->HemisphereZone_parser_)
            this->HemisphereZone_parser_->pre ();
        return true;
    }
    return false;
}
References _parent_dnaStn, Height_parser_, HemisphereZone_parser_, Name_parser_, XAxis_parser_, and YAxis_parser_.
_end_element_impl()
bool StationCoord_pskel::_end_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n) protected virtual
Definition at line 3042 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
        return true;
    if (n == "Name" && ns.empty ())
    {
        if (this->Name_parser_)
            this->Name (this->Name_parser_->post_string ());
        return true;
    }
    if (n == "XAxis" && ns.empty ())
    {
        if (this->XAxis_parser_)
            this->XAxis (this->XAxis_parser_->post_string ());
        return true;
    }
    if (n == "YAxis" && ns.empty ())
    {
        if (this->YAxis_parser_)
            this->YAxis (this->YAxis_parser_->post_string ());
        return true;
    }
    if (n == "Height" && ns.empty ())
    {
        if (this->Height_parser_)
        {
            this->Height_parser_->post_Height ();
            this->Height ();
        }
        return true;
    }
    if (n == "HemisphereZone" && ns.empty ())
    {
        if (this->HemisphereZone_parser_)
            this->HemisphereZone (this->HemisphereZone_parser_->post_string ());
        return true;
    }
    return false;
}
References Height(), Height_parser_, HemisphereZone(), HemisphereZone_parser_, Name(), Name_parser_, XAxis(), XAxis_parser_, YAxis(), and YAxis_parser_.
Member Data Documentation
Name_parser_
::xml_schema::string_pskel* StationCoord_pskel::Name_parser_ protected
Definition at line 1192 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Name_parser(), parsers(), and StationCoord_pskel().
XAxis_parser_
::xml_schema::string_pskel* StationCoord_pskel::XAxis_parser_ protected
Definition at line 1193 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), parsers(), StationCoord_pskel(), and XAxis_parser().
YAxis_parser_
::xml_schema::string_pskel* StationCoord_pskel::YAxis_parser_ protected
Definition at line 1194 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), parsers(), StationCoord_pskel(), and YAxis_parser().
Height_parser_
::Height_pskel* StationCoord_pskel::Height_parser_ protected
Definition at line 1195 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Height_parser(), parsers(), and StationCoord_pskel().
HemisphereZone_parser_
::xml_schema::string_pskel* StationCoord_pskel::HemisphereZone_parser_ protected
Definition at line 1196 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), HemisphereZone_parser(), parsers(), and StationCoord_pskel().
GeoidModel_parser_
::GeoidModel_pskel* StationCoord_pskel::GeoidModel_parser_ protected
Definition at line 1197 of file dnaparser_pskel.hxx.
Referenced by GeoidModel_parser(), parsers(), and StationCoord_pskel().
_parent_dnaStn
dnaStnPtr StationCoord_pskel::_parent_dnaStn protected
Definition at line 1199 of file dnaparser_pskel.hxx.
Referenced by _start_element_impl(), StationCoord_pimpl::Height(), StationCoord_pimpl::HemisphereZone(), InitparentStn(), StationCoord_pimpl::XAxis(), and StationCoord_pimpl::YAxis().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx