DynAdjust: DnaMeasurement_pskel Class Reference
DnaMeasurement_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void Type (const ::std::string &)
virtual void Ignore (const ::std::string &)
virtual void First (const ::std::string &)
virtual void Second (const ::std::string &)
virtual void Third (const ::std::string &)
virtual void Value (const ::std::string &)
virtual void StdDev (const ::std::string &)
virtual void InstHeight (const ::std::string &)
virtual void TargHeight (const ::std::string &)
virtual void Total (const ::std::string &)
virtual void Directions ()
virtual void Vscale (const ::std::string &)
virtual void Epoch (const ::std::string &)
virtual void ReferenceFrame (const ::std::string &)
virtual void GPSBaseline ()
virtual void Hscale (const ::std::string &)
virtual void Lscale (const ::std::string &)
virtual void Pscale (const ::std::string &)
virtual void Clusterpoint ()
virtual void Coords (const ::std::string &)
virtual void Source (const ::std::string &)
virtual void MeasurementDBID (const ::std::string &)
virtual void ClusterDBID (const ::std::string &)
virtual void post_DnaMeasurement ()
void InitfileEpsg (std::string &fileEpsg)
void InitfileEpoch (std::string &fileEpoch)
void SetDefaultReferenceFrame (std::string &referenceframe, bool overridereferenceframe)
void SetDefaultEpoch (std::string &epoch)
void InitparentMsrVector (vdnaMsrPtr *pMsrs)
void InitparentMsrCounter (PUINT32 pMsrCounter)
void InitparentClusterID (PUINT32 pclusterID)
std::string Type ()
std::string First ()
std::string Second ()
std::string Third ()
vdnaMsrPtr & MeasurementList ()
std::string Source ()
std::string MeasurementDBID ()
std::string ClusterDBID ()
void Type_parser (::xml_schema::string_pskel &)
void Ignore_parser (::xml_schema::string_pskel &)
void First_parser (::xml_schema::string_pskel &)
void Second_parser (::xml_schema::string_pskel &)
void Third_parser (::xml_schema::string_pskel &)
void Value_parser (::xml_schema::string_pskel &)
void StdDev_parser (::xml_schema::string_pskel &)
void InstHeight_parser (::xml_schema::string_pskel &)
void TargHeight_parser (::xml_schema::string_pskel &)
void Total_parser (::xml_schema::string_pskel &)
void Directions_parser (::Directions_pskel &)
void Vscale_parser (::xml_schema::string_pskel &)
void Epoch_parser (::xml_schema::string_pskel &)
void ReferenceFrame_parser (::xml_schema::string_pskel &)
void GPSBaseline_parser (::GPSBaseline_pskel &)
void Hscale_parser (::xml_schema::string_pskel &)
void Lscale_parser (::xml_schema::string_pskel &)
void Pscale_parser (::xml_schema::string_pskel &)
void Clusterpoint_parser (::Clusterpoint_pskel &)
void Coords_parser (::xml_schema::string_pskel &)
void Source_parser (::xml_schema::string_pskel &)
void MeasurementDBID_parser (::xml_schema::string_pskel &)
void ClusterDBID_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::Directions_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::GPSBaseline_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::Clusterpoint_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, bool preferSingleXasG=false)
DnaMeasurement_pskel ()
Protected Member Functions
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
virtual bool _attribute_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * Type_parser_
::xml_schema::string_pskel * Ignore_parser_
::xml_schema::string_pskel * First_parser_
::xml_schema::string_pskel * Second_parser_
::xml_schema::string_pskel * Third_parser_
::xml_schema::string_pskel * Value_parser_
::xml_schema::string_pskel * StdDev_parser_
::xml_schema::string_pskel * InstHeight_parser_
::xml_schema::string_pskel * TargHeight_parser_
::xml_schema::string_pskel * Total_parser_
::Directions_pskel * Directions_parser_
::xml_schema::string_pskel * Vscale_parser_
::xml_schema::string_pskel * Epoch_parser_
::xml_schema::string_pskel * ReferenceFrame_parser_
::GPSBaseline_pskel * GPSBaseline_parser_
::xml_schema::string_pskel * Hscale_parser_
::xml_schema::string_pskel * Lscale_parser_
::xml_schema::string_pskel * Pscale_parser_
::Clusterpoint_pskel * Clusterpoint_parser_
::xml_schema::string_pskel * Coords_parser_
::xml_schema::string_pskel * Source_parser_
::xml_schema::string_pskel * MeasurementDBID_parser_
::xml_schema::string_pskel * ClusterDBID_parser_
vdnaMsrPtr * _vParentMsrs
dnaMsrPtr _dnaCurrentMsr
PUINT32 _pMeasurementCount
PUINT32 _pclusterID
std::string _fileEpoch
std::string _fileEpsg
std::string _epoch
std::string _referenceframe
bool _EpochTagSupplied
bool _ReferenceframeTagSupplied
bool _overridereferenceframe
bool _preferSingleXasG
UINT32 _total
Detailed Description
Definition at line 449 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
DnaMeasurement_pskel()
DnaMeasurement_pskel::DnaMeasurement_pskel ()
Definition at line 361 of file dnaparser_pskel.cxx.
    : Type_parser_ (0),
    Ignore_parser_ (0),
    First_parser_ (0),
    Second_parser_ (0),
    Third_parser_ (0),
    Value_parser_ (0),
    StdDev_parser_ (0),
    InstHeight_parser_ (0),
    TargHeight_parser_ (0),
    Total_parser_ (0),
    Directions_parser_ (0),
    Vscale_parser_ (0),
    Epoch_parser_ (0),
    ReferenceFrame_parser_ (0),
    GPSBaseline_parser_ (0),
    Hscale_parser_ (0),
    Lscale_parser_ (0),
    Pscale_parser_ (0),
    Clusterpoint_parser_ (0),
    Coords_parser_ (0),
    Source_parser_ (0),
    MeasurementDBID_parser_ (0),
    ClusterDBID_parser_ (0),
    _preferSingleXasG(false)
{
}
References _preferSingleXasG, ClusterDBID_parser_, Clusterpoint_parser_, Coords_parser_, Directions_parser_, Epoch_parser_, First_parser_, GPSBaseline_parser_, Hscale_parser_, Ignore_parser_, InstHeight_parser_, Lscale_parser_, MeasurementDBID_parser_, Pscale_parser_, ReferenceFrame_parser_, Second_parser_, Source_parser_, StdDev_parser_, TargHeight_parser_, Third_parser_, Total_parser_, Type_parser_, Value_parser_, and Vscale_parser_.
Member Function Documentation
Type() [1/2]
void DnaMeasurement_pskel::Type (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1279 of file dnaparser_pskel.cxx.
{
}
Referenced by parsers().
Ignore()
void DnaMeasurement_pskel::Ignore (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1283 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
First() [1/2]
void DnaMeasurement_pskel::First (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1287 of file dnaparser_pskel.cxx.
{
}
Referenced by parsers().
Second() [1/2]
void DnaMeasurement_pskel::Second (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1291 of file dnaparser_pskel.cxx.
{
}
Referenced by parsers().
Third() [1/2]
void DnaMeasurement_pskel::Third (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1295 of file dnaparser_pskel.cxx.
{
}
Referenced by parsers().
Value()
void DnaMeasurement_pskel::Value (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1299 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
StdDev()
void DnaMeasurement_pskel::StdDev (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1303 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
InstHeight()
void DnaMeasurement_pskel::InstHeight (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1307 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
TargHeight()
void DnaMeasurement_pskel::TargHeight (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1311 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Total()
void DnaMeasurement_pskel::Total (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1315 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Directions()
void DnaMeasurement_pskel::Directions () virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1319 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Vscale()
void DnaMeasurement_pskel::Vscale (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1323 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Epoch()
void DnaMeasurement_pskel::Epoch (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1327 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
ReferenceFrame()
void DnaMeasurement_pskel::ReferenceFrame (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1331 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
GPSBaseline()
void DnaMeasurement_pskel::GPSBaseline () virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1335 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Hscale()
void DnaMeasurement_pskel::Hscale (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1339 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Lscale()
void DnaMeasurement_pskel::Lscale (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1343 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Pscale()
void DnaMeasurement_pskel::Pscale (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1347 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Clusterpoint()
void DnaMeasurement_pskel::Clusterpoint () virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1351 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Coords()
void DnaMeasurement_pskel::Coords (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1355 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Source() [1/2]
void DnaMeasurement_pskel::Source (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1359 of file dnaparser_pskel.cxx.
{
}
Referenced by parsers().
MeasurementDBID() [1/2]
void DnaMeasurement_pskel::MeasurementDBID (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1363 of file dnaparser_pskel.cxx.
{
}
Referenced by parsers().
ClusterDBID() [1/2]
void DnaMeasurement_pskel::ClusterDBID (const ::std::string &) virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1367 of file dnaparser_pskel.cxx.
{
}
Referenced by parsers().
post_DnaMeasurement()
void DnaMeasurement_pskel::post_DnaMeasurement () virtual
Reimplemented in DnaMeasurement_pimpl.
Definition at line 1371 of file dnaparser_pskel.cxx.
{
}
InitfileEpsg()
void DnaMeasurement_pskel::InitfileEpsg (std::string & fileEpsg) inline
Definition at line 484 of file dnaparser_pskel.hxx.
{
        _fileEpsg = fileEpsg;
    }
References _fileEpsg.
InitfileEpoch()
void DnaMeasurement_pskel::InitfileEpoch (std::string & fileEpoch) inline
Definition at line 488 of file dnaparser_pskel.hxx.
{
        _fileEpoch = fileEpoch;
    }
References _fileEpoch.
SetDefaultReferenceFrame()
void DnaMeasurement_pskel::SetDefaultReferenceFrame (std::string & referenceframe, bool overridereferenceframe) inline
Definition at line 492 of file dnaparser_pskel.hxx.
{
        _referenceframe = referenceframe;
        _overridereferenceframe = overridereferenceframe;
    }
References _overridereferenceframe, and _referenceframe.
SetDefaultEpoch()
void DnaMeasurement_pskel::SetDefaultEpoch (std::string & epoch) inline
Definition at line 497 of file dnaparser_pskel.hxx.
{
        _epoch = epoch;
    }
References _epoch.
InitparentMsrVector()
void DnaMeasurement_pskel::InitparentMsrVector (vdnaMsrPtr * pMsrs) inline
Definition at line 501 of file dnaparser_pskel.hxx.
{ _vParentMsrs = pMsrs; }
References _vParentMsrs.
InitparentMsrCounter()
void DnaMeasurement_pskel::InitparentMsrCounter (PUINT32 pMsrCounter) inline
Definition at line 502 of file dnaparser_pskel.hxx.
{ _pMeasurementCount = pMsrCounter; }
References _pMeasurementCount.
InitparentClusterID()
void DnaMeasurement_pskel::InitparentClusterID (PUINT32 pclusterID) inline
Definition at line 503 of file dnaparser_pskel.hxx.
{ _pclusterID = pclusterID; }
References _pclusterID.
Type() [2/2]
std::string DnaMeasurement_pskel::Type () inline
Definition at line 506 of file dnaparser_pskel.hxx.
    {
        return Type_parser_->post_string();
    }
References Type_parser_.
Referenced by _end_element_impl().
First() [2/2]
std::string DnaMeasurement_pskel::First () inline
Definition at line 511 of file dnaparser_pskel.hxx.
    {
        return First_parser_->post_string();
    }
References First_parser_.
Referenced by _end_element_impl().
Second() [2/2]
std::string DnaMeasurement_pskel::Second () inline
Definition at line 516 of file dnaparser_pskel.hxx.
    {
        return Second_parser_->post_string();
    }
References Second_parser_.
Referenced by _end_element_impl().
Third() [2/2]
std::string DnaMeasurement_pskel::Third () inline
Definition at line 521 of file dnaparser_pskel.hxx.
    {
        return Third_parser_->post_string();
    }
References Third_parser_.
Referenced by _end_element_impl().
MeasurementList()
vdnaMsrPtr & DnaMeasurement_pskel::MeasurementList () inline
Definition at line 526 of file dnaparser_pskel.hxx.
    {
        return *_vParentMsrs;
    }
References _vParentMsrs.
Source() [2/2]
std::string DnaMeasurement_pskel::Source () inline
Definition at line 531 of file dnaparser_pskel.hxx.
    {
        return Source_parser_->post_string();
    }
References Source_parser_.
Referenced by _end_element_impl().
MeasurementDBID() [2/2]
std::string DnaMeasurement_pskel::MeasurementDBID () inline
Definition at line 536 of file dnaparser_pskel.hxx.
    {
        return MeasurementDBID_parser_->post_string();
    }
References MeasurementDBID_parser_.
Referenced by _end_element_impl().
ClusterDBID() [2/2]
std::string DnaMeasurement_pskel::ClusterDBID () inline
Definition at line 541 of file dnaparser_pskel.hxx.
    {
        return ClusterDBID_parser_->post_string();
    }
References ClusterDBID_parser_.
Referenced by _end_element_impl().
Type_parser()
void DnaMeasurement_pskel::Type_parser (::xml_schema::string_pskel & p)
Definition at line 198 of file dnaparser_pskel.cxx.
{
    this->Type_parser_ = &p;
}
References Type_parser_.
Ignore_parser()
void DnaMeasurement_pskel::Ignore_parser (::xml_schema::string_pskel & p)
Definition at line 203 of file dnaparser_pskel.cxx.
{
    this->Ignore_parser_ = &p;
}
References Ignore_parser_.
First_parser()
void DnaMeasurement_pskel::First_parser (::xml_schema::string_pskel & p)
Definition at line 208 of file dnaparser_pskel.cxx.
{
    this->First_parser_ = &p;
}
References First_parser_.
Second_parser()
void DnaMeasurement_pskel::Second_parser (::xml_schema::string_pskel & p)
Definition at line 213 of file dnaparser_pskel.cxx.
{
    this->Second_parser_ = &p;
}
References Second_parser_.
Third_parser()
void DnaMeasurement_pskel::Third_parser (::xml_schema::string_pskel & p)
Definition at line 218 of file dnaparser_pskel.cxx.
{
    this->Third_parser_ = &p;
}
References Third_parser_.
Value_parser()
void DnaMeasurement_pskel::Value_parser (::xml_schema::string_pskel & p)
Definition at line 223 of file dnaparser_pskel.cxx.
{
    this->Value_parser_ = &p;
}
References Value_parser_.
StdDev_parser()
void DnaMeasurement_pskel::StdDev_parser (::xml_schema::string_pskel & p)
Definition at line 228 of file dnaparser_pskel.cxx.
{
    this->StdDev_parser_ = &p;
}
References StdDev_parser_.
InstHeight_parser()
void DnaMeasurement_pskel::InstHeight_parser (::xml_schema::string_pskel & p)
Definition at line 233 of file dnaparser_pskel.cxx.
{
    this->InstHeight_parser_ = &p;
}
References InstHeight_parser_.
TargHeight_parser()
void DnaMeasurement_pskel::TargHeight_parser (::xml_schema::string_pskel & p)
Definition at line 238 of file dnaparser_pskel.cxx.
{
    this->TargHeight_parser_ = &p;
}
References TargHeight_parser_.
Total_parser()
void DnaMeasurement_pskel::Total_parser (::xml_schema::string_pskel & p)
Definition at line 243 of file dnaparser_pskel.cxx.
{
    this->Total_parser_ = &p;
}
References Total_parser_.
Directions_parser()
void DnaMeasurement_pskel::Directions_parser (::Directions_pskel & p)
Definition at line 248 of file dnaparser_pskel.cxx.
{
    this->Directions_parser_ = &p;
}
References Directions_parser_.
Vscale_parser()
void DnaMeasurement_pskel::Vscale_parser (::xml_schema::string_pskel & p)
Definition at line 253 of file dnaparser_pskel.cxx.
{
    this->Vscale_parser_ = &p;
}
References Vscale_parser_.
Epoch_parser()
void DnaMeasurement_pskel::Epoch_parser (::xml_schema::string_pskel & p)
Definition at line 258 of file dnaparser_pskel.cxx.
{
    this->Epoch_parser_ = &p;
}
References Epoch_parser_.
ReferenceFrame_parser()
void DnaMeasurement_pskel::ReferenceFrame_parser (::xml_schema::string_pskel &)
GPSBaseline_parser()
void DnaMeasurement_pskel::GPSBaseline_parser (::GPSBaseline_pskel & p)
Definition at line 263 of file dnaparser_pskel.cxx.
{
    this->GPSBaseline_parser_ = &p;
}
References GPSBaseline_parser_.
Hscale_parser()
void DnaMeasurement_pskel::Hscale_parser (::xml_schema::string_pskel & p)
Definition at line 268 of file dnaparser_pskel.cxx.
{
    this->Hscale_parser_ = &p;
}
References Hscale_parser_.
Lscale_parser()
void DnaMeasurement_pskel::Lscale_parser (::xml_schema::string_pskel & p)
Definition at line 273 of file dnaparser_pskel.cxx.
{
    this->Lscale_parser_ = &p;
}
References Lscale_parser_.
Pscale_parser()
void DnaMeasurement_pskel::Pscale_parser (::xml_schema::string_pskel & p)
Definition at line 278 of file dnaparser_pskel.cxx.
{
    this->Pscale_parser_ = &p;
}
References Pscale_parser_.
Clusterpoint_parser()
void DnaMeasurement_pskel::Clusterpoint_parser (::Clusterpoint_pskel & p)
Definition at line 283 of file dnaparser_pskel.cxx.
{
    this->Clusterpoint_parser_ = &p;
}
References Clusterpoint_parser_.
Coords_parser()
void DnaMeasurement_pskel::Coords_parser (::xml_schema::string_pskel & p)
Definition at line 288 of file dnaparser_pskel.cxx.
{
    this->Coords_parser_ = &p;
}
References Coords_parser_.
Source_parser()
void DnaMeasurement_pskel::Source_parser (::xml_schema::string_pskel & p)
Definition at line 293 of file dnaparser_pskel.cxx.
{
    this->Source_parser_ = &p;
}
References Source_parser_.
MeasurementDBID_parser()
void DnaMeasurement_pskel::MeasurementDBID_parser (::xml_schema::string_pskel & p)
Definition at line 298 of file dnaparser_pskel.cxx.
{
    this->MeasurementDBID_parser_ = &p;
}
References MeasurementDBID_parser_.
ClusterDBID_parser()
void DnaMeasurement_pskel::ClusterDBID_parser (::xml_schema::string_pskel & p)
Definition at line 303 of file dnaparser_pskel.cxx.
{
    this->MeasurementDBID_parser_ = &p;
}
References MeasurementDBID_parser_.
parsers()
void DnaMeasurement_pskel::parsers (::xml_schema::string_pskel & Type, ::xml_schema::string_pskel & Ignore, ::xml_schema::string_pskel & First, ::xml_schema::string_pskel & Second, ::xml_schema::string_pskel & Third, ::xml_schema::string_pskel & Value, ::xml_schema::string_pskel & StdDev, ::xml_schema::string_pskel & InstHeight, ::xml_schema::string_pskel & TargHeight, ::xml_schema::string_pskel & Total, ::Directions_pskel & Directions, ::xml_schema::string_pskel & Vscale, ::xml_schema::string_pskel & Epoch, ::xml_schema::string_pskel & ReferenceFrame, ::GPSBaseline_pskel & GPSBaseline, ::xml_schema::string_pskel & Hscale, ::xml_schema::string_pskel & Lscale, ::xml_schema::string_pskel & Pscale, ::Clusterpoint_pskel & Clusterpoint, ::xml_schema::string_pskel & Coords, ::xml_schema::string_pskel & Source, ::xml_schema::string_pskel & MeasurementDBID, ::xml_schema::string_pskel & ClusterDBID, bool preferSingleXasG = false)
Definition at line 309 of file dnaparser_pskel.cxx.
{
    this->Type_parser_ = &Type;
    this->Ignore_parser_ = &Ignore;
    this->First_parser_ = &First;
    this->Second_parser_ = &Second;
    this->Third_parser_ = &Third;
    this->Value_parser_ = &Value;
    this->StdDev_parser_ = &StdDev;
    this->InstHeight_parser_ = &InstHeight;
    this->TargHeight_parser_ = &TargHeight;
    this->Total_parser_ = &Total;
    this->Directions_parser_ = &Directions;
    this->Vscale_parser_ = &Vscale;
    this->Epoch_parser_ = &Epoch;
    this->ReferenceFrame_parser_ = &ReferenceFrame;
    this->GPSBaseline_parser_ = &GPSBaseline;
    this->Hscale_parser_ = &Hscale;
    this->Lscale_parser_ = &Lscale;
    this->Pscale_parser_ = &Pscale;
    this->Clusterpoint_parser_ = &Clusterpoint;
    this->Coords_parser_ = &Coords;
    this->Source_parser_ = &Source;
    this->MeasurementDBID_parser_ = &MeasurementDBID;
    this->ClusterDBID_parser_ = &ClusterDBID;
    this->_preferSingleXasG = preferSingleXasG;
}
References _preferSingleXasG, ClusterDBID(), ClusterDBID_parser_, Clusterpoint(), Clusterpoint_parser_, Coords(), Coords_parser_, Directions(), Directions_parser_, Epoch(), Epoch_parser_, First(), First_parser_, GPSBaseline(), GPSBaseline_parser_, Hscale(), Hscale_parser_, Ignore(), Ignore_parser_, InstHeight(), InstHeight_parser_, Lscale(), Lscale_parser_, MeasurementDBID(), MeasurementDBID_parser_, Pscale(), Pscale_parser_, ReferenceFrame(), ReferenceFrame_parser_, Second(), Second_parser_, Source(), Source_parser_, StdDev(), StdDev_parser_, TargHeight(), TargHeight_parser_, Third(), Third_parser_, Total(), Total_parser_, Type(), Type_parser_, Value(), Value_parser_, Vscale(), and Vscale_parser_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
_start_element_impl()
bool DnaMeasurement_pskel::_start_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string * t) protected virtual
Definition at line 1375 of file dnaparser_pskel.cxx.
{
    XSD_UNUSED (t);
    if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
        return true;
    if (n == "Type" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Type_parser_;
        if (this->Type_parser_)
            this->Type_parser_->pre ();
        return true;
    }
    if (n == "Ignore" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Ignore_parser_;
        if (this->Ignore_parser_)
            this->Ignore_parser_->pre ();
        return true;
    }
    if (n == "First" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->First_parser_;
        if (this->First_parser_)
            this->First_parser_->pre ();
        return true;
    }
    if (n == "Second" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Second_parser_;
        if (this->Second_parser_)
            this->Second_parser_->pre ();
        return true;
    }
    if (n == "Third" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Third_parser_;
        if (this->Third_parser_)
            this->Third_parser_->pre ();
        return true;
    }
    if (n == "Value" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Value_parser_;
        if (this->Value_parser_)
            this->Value_parser_->pre ();
        return true;
    }
    if (n == "StdDev" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->StdDev_parser_;
        if (this->StdDev_parser_)
            this->StdDev_parser_->pre ();
        return true;
    }
    if (n == "InstHeight" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->InstHeight_parser_;
        if (this->InstHeight_parser_)
            this->InstHeight_parser_->pre ();
        return true;
    }
    if (n == "TargHeight" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->TargHeight_parser_;
        if (this->TargHeight_parser_)
            this->TargHeight_parser_->pre ();
        return true;
    }
    if (n == "Total" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Total_parser_;
        if (this->Total_parser_)
            this->Total_parser_->pre ();
        return true;
    }
    if (n == "Directions" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Directions_parser_;
        if (this->Directions_parser_)
        {
            this->Directions_parser_->InitparentMsrCounter(_pMeasurementCount);
            this->Directions_parser_->InitparentDirnSet(_dnaCurrentMsr);
            this->Directions_parser_->pre ();
        }
        return true;
    }
    if (n == "Vscale" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Vscale_parser_;
        if (this->Vscale_parser_)
            this->Vscale_parser_->pre ();
        return true;
    }
    if (n == "Epoch" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Epoch_parser_;
        if (this->Epoch_parser_)
            this->Epoch_parser_->pre ();
        return true;
    }
    if (n == "ReferenceFrame" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->ReferenceFrame_parser_;
        if (this->ReferenceFrame_parser_)
            this->ReferenceFrame_parser_->pre ();
        return true;
    }
    if (n == "GPSBaseline" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->GPSBaseline_parser_;
        if (this->GPSBaseline_parser_)
        {
            this->GPSBaseline_parser_->InitparentMsrCounter(_pMeasurementCount);
            this->GPSBaseline_parser_->InitparentGpsBaselineCluster(_dnaCurrentMsr);
            this->GPSBaseline_parser_->pre ();
        }
        return true;
    }
    if (n == "Hscale" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Hscale_parser_;
        if (this->Hscale_parser_)
            this->Hscale_parser_->pre ();
        return true;
    }
    if (n == "Lscale" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Lscale_parser_;
        if (this->Lscale_parser_)
            this->Lscale_parser_->pre ();
        return true;
    }
    if (n == "Pscale" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Pscale_parser_;
        if (this->Pscale_parser_)
            this->Pscale_parser_->pre ();
        return true;
    }
    if (n == "Clusterpoint" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Clusterpoint_parser_;
        if (this->Clusterpoint_parser_)
        {
            this->Clusterpoint_parser_->InitparentMsrCounter(_pMeasurementCount);
            this->Clusterpoint_parser_->InitparentGpsPointCluster(_dnaCurrentMsr);
            this->Clusterpoint_parser_->pre ();
        }
        return true;
    }
    if (n == "Coords" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Coords_parser_;
        if (this->Coords_parser_)
            this->Coords_parser_->pre ();
        return true;
    }
    if (n == "Source" && ns.empty())
    {
        this->::xml_schema::complex_content::context_.top().parser_ = this->Source_parser_;
        if (this->Source_parser_)
            this->Source_parser_->pre();
        return true;
    }
    if (n == "MeasurementID" && ns.empty())
    {
        this->::xml_schema::complex_content::context_.top().parser_ = this->MeasurementDBID_parser_;
        if (this->MeasurementDBID_parser_)
            this->MeasurementDBID_parser_->pre();
        return true;
    }
    if (n == "ClusterID" && ns.empty())
    {
        this->::xml_schema::complex_content::context_.top().parser_ = this->ClusterDBID_parser_;
        if (this->ClusterDBID_parser_)
            this->ClusterDBID_parser_->pre();
        return true;
    }
    return false;
}
References _dnaCurrentMsr, _pMeasurementCount, ClusterDBID_parser_, Clusterpoint_parser_, Coords_parser_, Directions_parser_, Epoch_parser_, First_parser_, GPSBaseline_parser_, Hscale_parser_, Ignore_parser_, InstHeight_parser_, Lscale_parser_, MeasurementDBID_parser_, Pscale_parser_, ReferenceFrame_parser_, Second_parser_, Source_parser_, StdDev_parser_, TargHeight_parser_, Third_parser_, Total_parser_, Type_parser_, Value_parser_, and Vscale_parser_.
_end_element_impl()
bool DnaMeasurement_pskel::_end_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n) protected virtual
Definition at line 1629 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
        return true;
    if (n == "Type" && ns.empty ())
    {
        if (this->Type_parser_)
            this->Type (this->Type_parser_->post_string ());
        return true;
    }
    if (n == "Ignore" && ns.empty ())
    {
        if (this->Ignore_parser_)
            this->Ignore (this->Ignore_parser_->post_string ());
        return true;
    }
    if (n == "First" && ns.empty ())
    {
        if (this->First_parser_)
            this->First (this->First_parser_->post_string ());
        return true;
    }
    if (n == "Second" && ns.empty ())
    {
        if (this->Second_parser_)
            this->Second (this->Second_parser_->post_string ());
        return true;
    }
    if (n == "Third" && ns.empty ())
    {
        if (this->Third_parser_)
            this->Third (this->Third_parser_->post_string ());
        return true;
    }
    if (n == "Value" && ns.empty ())
    {
        if (this->Value_parser_)
            this->Value (this->Value_parser_->post_string ());
        return true;
    }
    if (n == "StdDev" && ns.empty ())
    {
        if (this->StdDev_parser_)
            this->StdDev (this->StdDev_parser_->post_string ());
        return true;
    }
    if (n == "InstHeight" && ns.empty ())
    {
        if (this->InstHeight_parser_)
            this->InstHeight (this->InstHeight_parser_->post_string ());
        return true;
    }
    if (n == "TargHeight" && ns.empty ())
    {
        if (this->TargHeight_parser_)
            this->TargHeight (this->TargHeight_parser_->post_string ());
        return true;
    }
    if (n == "Total" && ns.empty ())
    {
        if (this->Total_parser_)
            this->Total (this->Total_parser_->post_string ());
        return true;
    }
    if (n == "Directions" && ns.empty ())
    {
        if (this->Directions_parser_)
        {
            this->Directions_parser_->post_Directions (_total);
            this->Directions ();
        }
        return true;
    }
    if (n == "Vscale" && ns.empty ())
    {
        if (this->Vscale_parser_)
            this->Vscale (this->Vscale_parser_->post_string ());
        return true;
    }
    if (n == "Epoch" && ns.empty ())
    {
        if (this->Epoch_parser_)
            this->Epoch (this->Epoch_parser_->post_string ());
        return true;
    }
    if (n == "ReferenceFrame" && ns.empty ())
    {
        if (this->ReferenceFrame_parser_)
            this->ReferenceFrame (this->ReferenceFrame_parser_->post_string ());
        return true;
    }
    if (n == "GPSBaseline" && ns.empty ())
    {
        if (this->GPSBaseline_parser_)
        {
            this->GPSBaseline_parser_->post_GPSBaseline ();
            this->GPSBaseline ();
        }
        return true;
    }
    if (n == "Hscale" && ns.empty ())
    {
        if (this->Hscale_parser_)
            this->Hscale (this->Hscale_parser_->post_string ());
        return true;
    }
    if (n == "Lscale" && ns.empty ())
    {
        if (this->Lscale_parser_)
            this->Lscale (this->Lscale_parser_->post_string ());
        return true;
    }
    if (n == "Pscale" && ns.empty ())
    {
        if (this->Pscale_parser_)
            this->Pscale (this->Pscale_parser_->post_string ());
        return true;
    }
    if (n == "Clusterpoint" && ns.empty ())
    {
        if (this->Clusterpoint_parser_)
        {
            this->Clusterpoint_parser_->post_Clusterpoint ();
            this->Clusterpoint ();
        }
        return true;
    }
    if (n == "Coords" && ns.empty ())
    {
        if (this->Coords_parser_)
            this->Coords (this->Coords_parser_->post_string ());
        return true;
    }
    if (n == "Source" && ns.empty())
    {
        if (this->Source_parser_)
            this->Source (this->Source_parser_->post_string());
        return true;
    }
    if (n == "MeasurementID" && ns.empty())
    {
        if (this->MeasurementDBID_parser_)
            this->MeasurementDBID (this->MeasurementDBID_parser_->post_string());
        return true;
    }
    if (n == "ClusterID" && ns.empty())
    {
        if (this->ClusterDBID_parser_)
            this->ClusterDBID (this->ClusterDBID_parser_->post_string());
        return true;
    }
    return false;
}
References _total, ClusterDBID(), ClusterDBID_parser_, Clusterpoint(), Clusterpoint_parser_, Coords(), Coords_parser_, Directions(), Directions_parser_, Epoch(), Epoch_parser_, First(), First_parser_, GPSBaseline(), GPSBaseline_parser_, Hscale(), Hscale_parser_, Ignore(), Ignore_parser_, InstHeight(), InstHeight_parser_, Lscale(), Lscale_parser_, MeasurementDBID(), MeasurementDBID_parser_, Pscale(), Pscale_parser_, ReferenceFrame(), ReferenceFrame_parser_, Second(), Second_parser_, Source(), Source_parser_, StdDev(), StdDev_parser_, TargHeight(), TargHeight_parser_, Third(), Third_parser_, Total(), Total_parser_, Type(), Type_parser_, Value(), Value_parser_, Vscale(), and Vscale_parser_.
_attribute_impl()
bool DnaMeasurement_pskel::_attribute_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string & v) protected virtual
Definition at line 1831 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_attribute_impl (ns, n, v))
        return true;
    //if (n == "epoch" && ns.empty ())
    //{
    //  if (this->epoch_parser_)
    //  {
    //      this->epoch_parser_->pre ();
    //      this->epoch_parser_->_pre_impl ();
    //      this->epoch_parser_->_characters (v);
    //      this->epoch_parser_->_post_impl ();
    //      this->epoch (this->epoch_parser_->post_string ());
    //  }
    //  return true;
    //}
    return false;
}
Member Data Documentation
Type_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Type_parser_ protected
Definition at line 620 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), Type(), and Type_parser().
Ignore_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Ignore_parser_ protected
Definition at line 621 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), Ignore_parser(), and parsers().
First_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::First_parser_ protected
Definition at line 622 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), First(), First_parser(), and parsers().
Second_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Second_parser_ protected
Definition at line 623 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), Second(), and Second_parser().
Third_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Third_parser_ protected
Definition at line 624 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), Third(), and Third_parser().
Value_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Value_parser_ protected
Definition at line 625 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), and Value_parser().
StdDev_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::StdDev_parser_ protected
Definition at line 626 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), and StdDev_parser().
InstHeight_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::InstHeight_parser_ protected
Definition at line 627 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), InstHeight_parser(), and parsers().
TargHeight_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::TargHeight_parser_ protected
Definition at line 628 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), and TargHeight_parser().
Total_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Total_parser_ protected
Definition at line 629 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), and Total_parser().
Directions_parser_
::Directions_pskel* DnaMeasurement_pskel::Directions_parser_ protected
Definition at line 630 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Directions_parser(), DnaMeasurement_pskel(), and parsers().
Vscale_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Vscale_parser_ protected
Definition at line 631 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), and Vscale_parser().
Epoch_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Epoch_parser_ protected
Definition at line 632 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), Epoch_parser(), and parsers().
ReferenceFrame_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::ReferenceFrame_parser_ protected
Definition at line 633 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), and parsers().
GPSBaseline_parser_
::GPSBaseline_pskel* DnaMeasurement_pskel::GPSBaseline_parser_ protected
Definition at line 634 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), GPSBaseline_parser(), and parsers().
Hscale_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Hscale_parser_ protected
Definition at line 635 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), Hscale_parser(), and parsers().
Lscale_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Lscale_parser_ protected
Definition at line 636 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), Lscale_parser(), and parsers().
Pscale_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Pscale_parser_ protected
Definition at line 637 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), and Pscale_parser().
Clusterpoint_parser_
::Clusterpoint_pskel* DnaMeasurement_pskel::Clusterpoint_parser_ protected
Definition at line 638 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_parser(), DnaMeasurement_pskel(), and parsers().
Coords_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Coords_parser_ protected
Definition at line 639 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Coords_parser(), DnaMeasurement_pskel(), and parsers().
Source_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::Source_parser_ protected
Definition at line 640 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), DnaMeasurement_pskel(), parsers(), Source(), and Source_parser().
MeasurementDBID_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::MeasurementDBID_parser_ protected
Definition at line 641 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), ClusterDBID_parser(), DnaMeasurement_pskel(), MeasurementDBID(), MeasurementDBID_parser(), and parsers().
ClusterDBID_parser_
::xml_schema::string_pskel* DnaMeasurement_pskel::ClusterDBID_parser_ protected
Definition at line 642 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), ClusterDBID(), DnaMeasurement_pskel(), and parsers().
_vParentMsrs
vdnaMsrPtr* DnaMeasurement_pskel::_vParentMsrs protected
Definition at line 645 of file dnaparser_pskel.hxx.
Referenced by InitparentMsrVector(), MeasurementList(), and DnaMeasurement_pimpl::post_DnaMeasurement().
_dnaCurrentMsr
dnaMsrPtr DnaMeasurement_pskel::_dnaCurrentMsr protected
Definition at line 646 of file dnaparser_pskel.hxx.
Referenced by _start_element_impl(), DnaMeasurement_pimpl::ClusterDBID(), DnaMeasurement_pimpl::Coords(), DnaMeasurement_pimpl::Epoch(), DnaMeasurement_pimpl::First(), DnaMeasurement_pimpl::GPSBaseline(), DnaMeasurement_pimpl::Hscale(), DnaMeasurement_pimpl::Ignore(), DnaMeasurement_pimpl::InstHeight(), DnaMeasurement_pimpl::Lscale(), DnaMeasurement_pimpl::MeasurementDBID(), DnaMeasurement_pimpl::post_DnaMeasurement(), DnaMeasurement_pimpl::pre(), DnaMeasurement_pimpl::Pscale(), DnaMeasurement_pimpl::ReferenceFrame(), DnaMeasurement_pimpl::Second(), DnaMeasurement_pimpl::Source(), DnaMeasurement_pimpl::StdDev(), DnaMeasurement_pimpl::TargHeight(), DnaMeasurement_pimpl::Third(), DnaMeasurement_pimpl::Total(), DnaMeasurement_pimpl::Type(), DnaMeasurement_pimpl::Value(), and DnaMeasurement_pimpl::Vscale().
_pMeasurementCount
PUINT32 DnaMeasurement_pskel::_pMeasurementCount protected
Definition at line 648 of file dnaparser_pskel.hxx.
Referenced by _start_element_impl(), InitparentMsrCounter(), and DnaMeasurement_pimpl::Type().
_pclusterID
PUINT32 DnaMeasurement_pskel::_pclusterID protected
Definition at line 649 of file dnaparser_pskel.hxx.
Referenced by InitparentClusterID(), and DnaMeasurement_pimpl::Type().
_fileEpoch
std::string DnaMeasurement_pskel::_fileEpoch protected
Definition at line 650 of file dnaparser_pskel.hxx.
Referenced by InitfileEpoch(), and DnaMeasurement_pimpl::Type().
_fileEpsg
std::string DnaMeasurement_pskel::_fileEpsg protected
Definition at line 651 of file dnaparser_pskel.hxx.
Referenced by InitfileEpsg(), and DnaMeasurement_pimpl::Type().
_epoch
std::string DnaMeasurement_pskel::_epoch protected
Definition at line 652 of file dnaparser_pskel.hxx.
Referenced by DnaMeasurement_pimpl::Epoch(), SetDefaultEpoch(), and DnaMeasurement_pimpl::Type().
_referenceframe
std::string DnaMeasurement_pskel::_referenceframe protected
Definition at line 653 of file dnaparser_pskel.hxx.
Referenced by DnaMeasurement_pimpl::ReferenceFrame(), SetDefaultReferenceFrame(), and DnaMeasurement_pimpl::Type().
_EpochTagSupplied
bool DnaMeasurement_pskel::_EpochTagSupplied protected
Definition at line 654 of file dnaparser_pskel.hxx.
Referenced by DnaMeasurement_pimpl::Epoch(), DnaMeasurement_pimpl::pre(), and DnaMeasurement_pimpl::Type().
_ReferenceframeTagSupplied
bool DnaMeasurement_pskel::_ReferenceframeTagSupplied protected
Definition at line 655 of file dnaparser_pskel.hxx.
Referenced by DnaMeasurement_pimpl::pre(), DnaMeasurement_pimpl::ReferenceFrame(), and DnaMeasurement_pimpl::Type().
_overridereferenceframe
bool DnaMeasurement_pskel::_overridereferenceframe protected
Definition at line 656 of file dnaparser_pskel.hxx.
Referenced by DnaMeasurement_pimpl::Epoch(), DnaMeasurement_pimpl::ReferenceFrame(), SetDefaultReferenceFrame(), and DnaMeasurement_pimpl::Type().
_preferSingleXasG
bool DnaMeasurement_pskel::_preferSingleXasG protected
Definition at line 658 of file dnaparser_pskel.hxx.
Referenced by DnaMeasurement_pskel(), parsers(), and DnaMeasurement_pimpl::Total().
_total
UINT32 DnaMeasurement_pskel::_total protected
Definition at line 660 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), and DnaMeasurement_pimpl::Total().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx