DynAdjust: Height_pskel Class Reference
Height_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void system (const ::std::string &)
virtual void post_Height ()
void system_parser (::xml_schema::string_pskel &)
void parsers (::system_pskel &)
Height_pskel ()
void InitparentStn (dnaStnPtr pStn)
Protected Member Functions
virtual bool _attribute_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * system_parser_
dnaStnPtr _parent_dnaStn
Detailed Description
Definition at line 1026 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
Height_pskel()
Height_pskel::Height_pskel ()
Definition at line 683 of file dnaparser_pskel.cxx.
    : system_parser_ (0)
{
}
References system_parser_.
Member Function Documentation
system()
void Height_pskel::system (const ::std::string &) virtual
Reimplemented in Height_pimpl.
Definition at line 2687 of file dnaparser_pskel.cxx.
{
}
Referenced by _attribute_impl(), and parsers().
post_Height()
void Height_pskel::post_Height () virtual
Reimplemented in Height_pimpl.
Definition at line 2691 of file dnaparser_pskel.cxx.
{
}
system_parser()
void Height_pskel::system_parser (::xml_schema::string_pskel & p)
Definition at line 673 of file dnaparser_pskel.cxx.
{
    this->system_parser_ = &p;
}
References system_parser_.
parsers()
void Height_pskel::parsers (::system_pskel & system)
Definition at line 678 of file dnaparser_pskel.cxx.
{
    this->system_parser_ = &system;
}
References system(), and system_parser_.
InitparentStn()
void Height_pskel::InitparentStn (dnaStnPtr pStn) inline
Definition at line 1047 of file dnaparser_pskel.hxx.
{   _parent_dnaStn = pStn; }
References _parent_dnaStn.
_attribute_impl()
bool Height_pskel::_attribute_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string & v) protected virtual
Definition at line 2695 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::string_pskel::_attribute_impl (ns, n, v))
        return true;
    if (n == "system" && ns.empty ())
    {
        if (this->system_parser_)
        {
            this->system_parser_->pre ();
            this->system_parser_->_pre_impl ();
            this->system_parser_->_characters (v);
            this->system_parser_->_post_impl ();
            this->system (this->system_parser_->post_string ());
        }
        return true;
    }
    return false;
}
References system(), and system_parser_.
Member Data Documentation
system_parser_
::xml_schema::string_pskel* Height_pskel::system_parser_ protected
Definition at line 1056 of file dnaparser_pskel.hxx.
Referenced by _attribute_impl(), Height_pskel(), parsers(), and system_parser().
_parent_dnaStn
dnaStnPtr Height_pskel::_parent_dnaStn protected
Definition at line 1058 of file dnaparser_pskel.hxx.
Referenced by InitparentStn(), Height_pimpl::post_Height(), and Height_pimpl::system().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx