DynAdjust: dynadjust::exception::NetMemoryException Class Reference
dynadjust::exception::NetMemoryException Class Reference
#include <dnaexception.hpp>
Public Member Functions
NetMemoryException (const std::string &what)
virtual const char * what () const throw ()
virtual ~NetMemoryException () throw ()
Private Attributes
std::string what_
Detailed Description
Definition at line 139 of file dnaexception.hpp.
Constructor & Destructor Documentation
NetMemoryException()
dynadjust::exception::NetMemoryException::NetMemoryException (const std::string & what) inline explicit
Definition at line 142 of file dnaexception.hpp.
        : what_(what) {}
References what(), and what_.
~NetMemoryException()
virtual dynadjust::exception::NetMemoryException::~NetMemoryException () throw () inline virtual
Definition at line 145 of file dnaexception.hpp.
{}
Member Function Documentation
what()
virtual const char * dynadjust::exception::NetMemoryException::what () const throw () inline virtual
Definition at line 144 of file dnaexception.hpp.
{ return what_.c_str(); }
References what_.
Referenced by NetMemoryException(), dynadjust::networkadjust::dna_adjust::PrepareAdjustment(), and dynadjust::networkadjust::dna_adjust::UpdateAdjustment().
Member Data Documentation
what_
std::string dynadjust::exception::NetMemoryException::what_ private
Definition at line 148 of file dnaexception.hpp.
Referenced by NetMemoryException(), and what().
The documentation for this class was generated from the following file:
include/exception/dnaexception.hpp