DynAdjust: dynadjust::iostreams::dna_io_scalar Class Reference
dynadjust::iostreams::dna_io_scalar Class Reference
#include <dnaioscalar.hpp>
Public Member Functions
dna_io_scalar (void)
dna_io_scalar (const dna_io_scalar &scl)
virtual ~dna_io_scalar (void)
dna_io_scalar & operator= (const dna_io_scalar &rhs)
void load_scalar_file (const std::string &map_filename, pvscl_t bslScaling)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 41 of file dnaioscalar.hpp.
Constructor & Destructor Documentation
dna_io_scalar() [1/2]
dynadjust::iostreams::dna_io_scalar::dna_io_scalar (void) inline
Definition at line 44 of file dnaioscalar.hpp.
{};
Referenced by dna_io_scalar(), and operator=().
dna_io_scalar() [2/2]
dynadjust::iostreams::dna_io_scalar::dna_io_scalar (const dna_io_scalar & scl) inline
Definition at line 45 of file dnaioscalar.hpp.
: dna_io_base(scl) {};
References dynadjust::iostreams::dna_io_base::dna_io_base(), and dna_io_scalar().
~dna_io_scalar()
virtual dynadjust::iostreams::dna_io_scalar::~dna_io_scalar (void) inline virtual
Definition at line 46 of file dnaioscalar.hpp.
{};
Member Function Documentation
operator=()
dna_io_scalar & dynadjust::iostreams::dna_io_scalar::operator= (const dna_io_scalar & rhs)
References dna_io_scalar().
load_scalar_file()
void dynadjust::iostreams::dna_io_scalar::load_scalar_file (const std::string & map_filename, pvscl_t bslScaling)
Definition at line 30 of file dnaioscalar.cpp.
{
    std::ifstream scalar_file;
    std::stringstream ss;
    ss << "load_scalar_file(): An error was encountered when opening " << scalar_filename << "." << std::endl;
    // The contents of the scalar file is as follows:
    //
    // --------------------------------------------------------------------------------
    // GNSS BASELINE VARIANCE MATRIX SCALAR FILE
    //
    // Scalar  count                      3
    // Station name width                 20
    // --------------------------------------------------------------------------------
    //
    // SCALARS
    //
    // Station 1            Station 2               v-scale    p-scale    l-scale    h-scale
    // -------------------- -------------------- ---------- ---------- ---------- ----------
    // 409601230            409601240                 100.0          1          1          1
    // 409601230            409601250                    10          2          2          5
    // 409601230            409601260                     1          3          3         10
    //
    try {
        // Load scalar file.  Throws runtime_error on failure.
        file_opener(scalar_file, scalar_filename,
            std::ios::in, ascii, true);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "load_scalar_file(): An error was encountered when reading from " << scalar_filename << "." << std::endl;
    bslScaling->clear();
    scalar_t bslScalars;
    std::string sBuf(""), tmp;
    UINT32 stationWidth(STATION), scalarCount(100);
    UINT32 line(0), position(0);
    try {
        // continue until "SCALARS" is found
        do
        {
            line++;
            getline(scalar_file, sBuf);
            if (boost::iequals(trimstr(sBuf), "SCALARS"))
                break;
            if (boost::iequals(trimstr(sBuf.substr(0, 16)), "Baseline count"))
            {
                scalarCount = boost::lexical_cast<UINT16, std::string>(trimstr(sBuf.substr(PRINT_VAR_PAD)));
                continue;
            }
            if (boost::iequals(trimstr(sBuf.substr(0, 18)), "Station name width"))
            {
                stationWidth = boost::lexical_cast<UINT16, std::string>(trimstr(sBuf.substr(PRINT_VAR_PAD)));
                continue;
            }
        }
        while (!boost::iequals(trimstr(sBuf), "SCALARS"));
        bslScaling->reserve(scalarCount);
        // Okay, now get the data
        while (!scalar_file.eof())
        {
            getline(scalar_file, sBuf);
            // blank or whitespace?
            if (trimstr(sBuf).empty())
                continue;
            if (trimstr(sBuf).length() < stationWidth+1)
                continue;
            if (boost::iequals(trimstr(sBuf.substr(0, 20)), "Station 1"))
                continue;
            if (boost::iequals(trimstr(sBuf.substr(0, 3)), "---"))
                continue;
            // Ignore lines with blank station name
            if (trimstr(sBuf.substr(0, stationWidth)).empty())
                continue;
            // Ignore lines with blank substitute name
            if (trimstr(sBuf.substr(stationWidth, stationWidth)).empty())
                continue;
            // initialise
            position = 0;
            bslScalars.station1 = "";
            bslScalars.station2 = "";
            bslScalars.v_scale = bslScalars.p_scale = bslScalars.l_scale = bslScalars.h_scale = 1.0;
            bslScalars.station1 = trimstr(sBuf.substr(0, stationWidth));
            position += stationWidth;
            bslScalars.station2 = trimstr(sBuf.substr(stationWidth, stationWidth));
            position += stationWidth;
            // v-scale present?
            if (sBuf.length() > position)
            {
                if ((tmp = trimstr(sBuf.substr(position, 10))).length() > 0)
                    bslScalars.v_scale = boost::lexical_cast<double, std::string>(tmp);
            }
            else
                continue;
            position += 10;
            // p-scale present?
            if (sBuf.length() > position)
            {
                if ((tmp = trimstr(sBuf.substr(position, 10))).length() > 0)
                    bslScalars.p_scale = boost::lexical_cast<double, std::string>(tmp);
            }
            else
                continue;
            position += 10;
            // l-scale present?
            if (sBuf.length() > position)
            {
                if ((tmp = trimstr(sBuf.substr(position, 10))).length() > 0)
                    bslScalars.l_scale = boost::lexical_cast<double, std::string>(tmp);
            }
            else
                continue;
            position += 10;
            // h-scale present?
            if (sBuf.length() > position)
            {
                if ((tmp = trimstr(sBuf.substr(position, 10))).length() > 0)
                    bslScalars.h_scale = boost::lexical_cast<double, std::string>(tmp);
            }
            else
                continue;
            bslScaling->push_back(bslScalars);
        }
    }
    catch (const std::ios_base::failure& f) {
        if (scalar_file.eof())
        {
            scalar_file.close();
            return;
        }
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        if (scalar_file.eof())
        {
            scalar_file.close();
            return;
        }
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        if (scalar_file.eof())
        {
            scalar_file.close();
            return;
        }
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    scalar_file.close();
}
References ascii, file_opener(), dynadjust::measurements::scl_t::h_scale, dynadjust::measurements::scl_t::l_scale, dynadjust::measurements::scl_t::p_scale, PRINT_VAR_PAD(), STATION(), dynadjust::measurements::scl_t::station1, dynadjust::measurements::scl_t::station2, trimstr(), and dynadjust::measurements::scl_t::v_scale.
Referenced by dynadjust::dynamlinterop::dna_import::EditGNSSMsrScalars().
The documentation for this class was generated from the following files:
include/io/dnaioscalar.hpp
include/io/dnaioscalar.cpp