DynAdjust: dynadjust::iostreams::dna_io_tbu Class Reference
dynadjust::iostreams::dna_io_tbu Class Reference
#include <dnaiotbu.hpp>
Public Member Functions
dna_io_tbu (void)
dna_io_tbu (const dna_io_tbu &tbu)
virtual ~dna_io_tbu (void)
dna_io_tbu & operator= (const dna_io_tbu &rhs)
void read_tbu_header (std::ifstream *ptr, std::string &version, INPUT_DATA_TYPE &idt)
void load_tbu_file (const std::string &tbu_filename, v_type_b_uncertainty &type_b_uncertainties, v_string_uint32_pair &vStnsMap)
void load_tbu_argument (const std::string &argument, type_b_uncertainty &type_b_uncertainties)
void identify_station_id (const std::string &stn_str, UINT32 &stn_id, v_string_uint32_pair &vStnsMap)
void validate_typeb_values (const std::string &argument, vstring &typeBUncertainties)
void assign_typeb_values_global (const vstring &typeBUncertainties, type_b_uncertainty &type_b)
void assign_typeb_values_local (const vstring &typeBUncertainties, type_b_uncertainty &type_b)
void reduce_uncertainties_global (type_b_uncertainty &type_b, matrix_2d &var_cart, stn_t &bstBinaryRecord)
void reduce_uncertainties_local (v_type_b_uncertainty &type_b, vstn_t &bstBinaryRecords)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 140 of file dnaiotbu.hpp.
Constructor & Destructor Documentation
dna_io_tbu() [1/2]
dynadjust::iostreams::dna_io_tbu::dna_io_tbu (void) inline
Definition at line 143 of file dnaiotbu.hpp.
{};
Referenced by dna_io_tbu(), and operator=().
dna_io_tbu() [2/2]
dynadjust::iostreams::dna_io_tbu::dna_io_tbu (const dna_io_tbu & tbu) inline
Definition at line 144 of file dnaiotbu.hpp.
: dna_io_base(tbu) {};
References dynadjust::iostreams::dna_io_base::dna_io_base(), and dna_io_tbu().
~dna_io_tbu()
virtual dynadjust::iostreams::dna_io_tbu::~dna_io_tbu (void) inline virtual
Definition at line 145 of file dnaiotbu.hpp.
{};
Member Function Documentation
operator=()
dna_io_tbu & dynadjust::iostreams::dna_io_tbu::operator= (const dna_io_tbu & rhs)
References dna_io_tbu().
read_tbu_header()
void dynadjust::iostreams::dna_io_tbu::read_tbu_header (std::ifstream * ptr, std::string & version, INPUT_DATA_TYPE & idt)
Definition at line 113 of file dnaiotbu.cpp.
{
    std::string sBuf;
    getline((*ptr), sBuf);
    sBuf = trimstr(sBuf);
    // Set the default version
    version = "1.00";
    // Attempt to get the file's version
    try {
        if (boost::iequals("!#=DNA", sBuf.substr(0, 6)))
            version = trimstr(sBuf.substr(6, 6));
    }
    catch (const std::runtime_error& e) {
        throw boost::enable_current_exception(std::runtime_error(e.what()));
    }
    std::string type;
    std::stringstream ssError;
    ssError << "  File type has not been provided in the header:" << std::endl <<
        "  " << sBuf << std::endl;
    if (sBuf.length() < 15)
        throw boost::enable_current_exception(std::runtime_error(ssError.str()));
    // Attempt to get the file's type
    try {
        type = trimstr(sBuf.substr(12, 3));
    }
    catch (const std::runtime_error& e) {
        ssError << "  " << e.what() << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ssError.str()));
    }
    // Check this is a Type B file
    if (boost::iequals(type, "tbu"))
        idt = tbu_data;
    else
    {
        idt = unknown;
        std::stringstream ssError;
        ssError << "  The supplied filetype '" << type << "' is not recognised:" << std::endl <<
            "  " << sBuf << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ssError.str()));
    }
}
References tbu_data, trimstr(), and unknown.
Referenced by load_tbu_file().
load_tbu_file()
void dynadjust::iostreams::dna_io_tbu::load_tbu_file (const std::string & tbu_filename, v_type_b_uncertainty & type_b_uncertainties, v_string_uint32_pair & vStnsMap)
Definition at line 200 of file dnaiotbu.cpp.
{
    // Type B uncertainty file structure is as follows.
    // Note - uncertainties are in metres, in the local reference frame (e,n,u)
    // and are given at 1 sigma (68%).
    //
    //   station id (20 chars)  east uncertainty (13) north uncertainty (13) up uncertainty (13)
    //      ...
    //   EOF
    std::ifstream tbu_file;
    std::stringstream ss;
    ss << "load_tbu_file(): An error was encountered when opening " << tbu_filename << "." << std::endl;
    INPUT_DATA_TYPE idt;
    std::string version;
    try {
        // open ascii plate boundaries file.  Throws runtime_error on failure.
        file_opener(tbu_file, tbu_filename, std::ios::in, ascii, true);
        // read header information
        read_tbu_header(&tbu_file, version, idt);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "load_tbu_file(): An error was encountered when reading from " << tbu_filename << "." << std::endl;
    UINT32 stn_id;
    std::string record, stn_str;
    vstring typeb_values;
    const UINT16 STDDEVn(STATION + STDDEV);
    const UINT16 STDDEVu(STATION + STDDEV + STDDEV);
    type_b_uncertainty typeBUncertainties;
    type_b_uncertainties.clear();
    try {
        typeb_values.resize(3);
        while (!tbu_file.eof())         // while EOF not found
        {
            typeb_values.at(0) = "";
            typeb_values.at(1) = "";
            typeb_values.at(2) = "";
            // get the plate identifier
            getline(tbu_file, record);
            // blank or whitespace?
            if (trimstr(record).empty())
                continue;
            // Ignore lines with comments
            if ((record.compare(0, 1, "*") == 0))
                continue;
            // obtain station name and unique ID
            stn_str = trimstr(record.substr(0, STATION));
            try {
                identify_station_id(stn_str, stn_id, vStnsMap);
            }
            catch (const std::runtime_error&) {
                // Can't find the station, ignore.
                continue;
            }
            typeBUncertainties.set_station_id(stn_id);
            // east uncertainty (may be blank)
            if (record.length() > STATION)
            {
                if (record.length() > STDDEVn)
                    typeb_values.at(0) = trimstr(record.substr(STATION, STDDEV));
                else
                    typeb_values.at(0) = trimstr(record.substr(STATION));
            }
            else
                // no uncertainties!
                continue;
            // north uncertainty (may be blank)
            if (record.length() > STDDEVn)
            {
                if (record.length() > STDDEVu)
                    typeb_values.at(1) = trimstr(record.substr(STDDEVn, STDDEV));
                else
                    typeb_values.at(1) = trimstr(record.substr(STDDEVn));
            }
            // up uncertainty (may be blank)
            if (record.length() > STDDEVu)
                typeb_values.at(2) = trimstr(record.substr(STDDEVu));
            try {
                // validate values. Throws on exception.  Print error and continue
                // to the next set of values
                validate_typeb_values(record, typeb_values);
            }
            catch (const std::runtime_error&) {
                continue;
            }
            // Assign the site-specific type b uncertainties
            assign_typeb_values_local(typeb_values, typeBUncertainties);
            // add to the list
            type_b_uncertainties.push_back(typeBUncertainties);
        }
        tbu_file.close();
    }
    catch (const std::ios_base::failure& f) {
        if (tbu_file.eof())
        {
            tbu_file.close();
            return;
        }
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        if (tbu_file.eof())
        {
            tbu_file.close();
            return;
        }
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return;
}
References ascii, assign_typeb_values_local(), file_opener(), identify_station_id(), read_tbu_header(), dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::set_station_id(), STATION(), STDDEV(), trimstr(), and validate_typeb_values().
Referenced by dynadjust::networkadjust::dna_adjust::InitialiseTypeBUncertainties().
load_tbu_argument()
void dynadjust::iostreams::dna_io_tbu::load_tbu_argument (const std::string & argument, type_b_uncertainty & type_b_uncertainties)
Definition at line 161 of file dnaiotbu.cpp.
{
    vstring typeBUncertainties;
    typeBUncertainties.resize(3);
    // Extract constraints from comma delimited string
    SplitDelimitedString<std::string>(
        argument,       // the comma delimited string
        std::string(","),                           // the delimiter
        &typeBUncertainties);                   // the respective values
    // validate values. Throws on exception
    validate_typeb_values(argument, typeBUncertainties);
    // Assign the type b uncertainties to be applied to all stations, except
    // when site-specific type b uncertainties have been loaded from a file
    assign_typeb_values_global(typeBUncertainties, type_b_uncertainties);
}
References assign_typeb_values_global(), SplitDelimitedString(), and validate_typeb_values().
Referenced by dynadjust::networkadjust::dna_adjust::InitialiseTypeBUncertainties().
identify_station_id()
void dynadjust::iostreams::dna_io_tbu::identify_station_id (const std::string & stn_str, UINT32 & stn_id, v_string_uint32_pair & vStnsMap)
Definition at line 181 of file dnaiotbu.cpp.
{
    it_pair_string_vUINT32 it_stnmap_range;
    std::stringstream ss;
    // find this station in the station map
    it_stnmap_range = equal_range(vStnsMap.begin(), vStnsMap.end(), stn_str, StationNameIDCompareName());
    if (it_stnmap_range.first == it_stnmap_range.second)
    {
        ss << "  Station '" << stn_str <<
            "' is not included in the network." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    stn_id = it_stnmap_range.first->second;
}
Referenced by load_tbu_file().
validate_typeb_values()
void dynadjust::iostreams::dna_io_tbu::validate_typeb_values (const std::string & argument, vstring & typeBUncertainties)
Definition at line 86 of file dnaiotbu.cpp.
{
    std::stringstream ss;
    if (typeBUncertainties.size() == 0)
    {
        ss << "  No Type b uncertainties provided:" << std::endl <<
            "    " << argument << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    UINT32 i(0), j;
    for (j = i; j < typeBUncertainties.size(); j++)
    {
        if (!is_floatingpoint<std::string>(typeBUncertainties.at(i)))
        {
            ss << "  Type b uncertainty '" << typeBUncertainties.at(i) <<
                "' is not a number:" << std::endl <<
                "    " << argument << std::endl;
            throw boost::enable_current_exception(std::runtime_error(ss.str()));
        }
        i++;
    }
}
References is_floatingpoint().
Referenced by load_tbu_argument(), and load_tbu_file().
assign_typeb_values_global()
void dynadjust::iostreams::dna_io_tbu::assign_typeb_values_global (const vstring & typeBUncertainties, type_b_uncertainty & type_b)
Definition at line 28 of file dnaiotbu.cpp.
{
    double e(0.), n(0.), u(0.);
    UINT32 i(0);
    std::stringstream ss;
    if (typeBUncertainties.size() > 2)
    {
        // 3 dimensions (east, north, up)
        if (!typeBUncertainties.at(i).empty())
            e = DoubleFromString<double>(typeBUncertainties.at(i));
        if (!typeBUncertainties.at(++i).empty())
            n = DoubleFromString<double>(typeBUncertainties.at(i));
        if (!typeBUncertainties.at(++i).empty())
            u = DoubleFromString<double>(typeBUncertainties.at(i));
    }
    else if (typeBUncertainties.size() > 1)
    {
        // 2 dimensions (east, north)
        if (!typeBUncertainties.at(i).empty())
            e = DoubleFromString<double>(typeBUncertainties.at(i));
        if (!typeBUncertainties.at(++i).empty())
            n = DoubleFromString<double>(typeBUncertainties.at(i));
    }
    else if (typeBUncertainties.size() > 0)
    {
        // 1 dimension (up)
        if (!typeBUncertainties.at(i).empty())
            u = DoubleFromString<double>(typeBUncertainties.at(i));
    }
    else {
        ss << "  No Type b uncertainties provided." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    // assign
    type_b.set_typeb_values_3d(e*e, n*n, u*u);
}
References DoubleFromString(), and dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::set_typeb_values_3d().
Referenced by load_tbu_argument().
assign_typeb_values_local()
void dynadjust::iostreams::dna_io_tbu::assign_typeb_values_local (const vstring & typeBUncertainties, type_b_uncertainty & type_b)
Definition at line 68 of file dnaiotbu.cpp.
{
    double e(0.), n(0.), u(0.);
    UINT32 i(0);
    // 3 dimensions (east, north, up)
    if (!typeBUncertainties.at(i).empty())
        e = DoubleFromString<double>(typeBUncertainties.at(i));
    if (!typeBUncertainties.at(++i).empty())
        n = DoubleFromString<double>(typeBUncertainties.at(i));
    if (!typeBUncertainties.at(++i).empty())
        u = DoubleFromString<double>(typeBUncertainties.at(i));
    // assign
    type_b.set_typeb_values_3d(e*e, n*n, u*u);
}
References DoubleFromString(), and dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::set_typeb_values_3d().
Referenced by load_tbu_file().
reduce_uncertainties_global()
void dynadjust::iostreams::dna_io_tbu::reduce_uncertainties_global (type_b_uncertainty & type_b, matrix_2d & var_cart, stn_t & bstBinaryRecord)
Definition at line 349 of file dnaiotbu.cpp.
{
    matrix_2d var_local(type_b.type_b);
    PropagateVariances_LocalCart<double>(var_local, var_cart,
        bstBinaryRecord.currentLatitude, bstBinaryRecord.currentLongitude, true);
}
References stn_t::currentLatitude, stn_t::currentLongitude, PropagateVariances_LocalCart(), and dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::type_b.
reduce_uncertainties_local()
void dynadjust::iostreams::dna_io_tbu::reduce_uncertainties_local (v_type_b_uncertainty & type_b, vstn_t & bstBinaryRecords)
Definition at line 358 of file dnaiotbu.cpp.
{
    it_vstn_t stn_it(bstBinaryRecords.begin());
    it_type_b_uncertainty _it_tbu;
    matrix_2d var_local;
    for (_it_tbu = type_b.begin(); _it_tbu != type_b.end(); ++_it_tbu)
    {
        var_local = _it_tbu->type_b;
        stn_it = bstBinaryRecords.begin() + _it_tbu->station_id;
        PropagateVariances_LocalCart<double>(var_local, _it_tbu->type_b,
            stn_it->currentLatitude, stn_it->currentLongitude, true);
    }
}
References PropagateVariances_LocalCart().
Referenced by dynadjust::networkadjust::dna_adjust::InitialiseTypeBUncertainties().
The documentation for this class was generated from the following files:
include/io/dnaiotbu.hpp
include/io/dnaiotbu.cpp