DynAdjust: dynadjust::datum_parameters::CDnaEllipsoid Class Reference
dynadjust::datum_parameters::CDnaEllipsoid Class Reference
#include <dnaellipsoid.hpp>
Public Member Functions
CDnaEllipsoid (void)
CDnaEllipsoid (const UINT32 &epsgCode)
CDnaEllipsoid (const std::string &epsgCode)
CDnaEllipsoid (const CDnaEllipsoid &newEllipsoid)
CDnaEllipsoid (const double &a, const double &inv_f)
virtual ~CDnaEllipsoid (void)
CDnaEllipsoid & operator= (const CDnaEllipsoid &rhs)
bool operator== (const CDnaEllipsoid &rhs) const
double GetE1 () const
double GetE2 () const
double GetE1sqd () const
double GetE2sqd () const
double GetSemiMajor () const
double GetSemiMinor () const
double GetInverseFlattening () const
double GetFlattening () const
void SetSemiMajor (const double &a)
void SetInverseFlattening (const double &inv_f)
void SetEllipsoid (const UINT32 &epsgCode)
Private Member Functions
void SetEllipsoidParams (const double &a, const double &inv_f)
void CalculateEllipsoidParams ()
Private Attributes
double m_dA
double m_dB
double m_dInv_f
double m_dF
double m_dEccen1
double m_dEccen1_sqd
double m_dEccen2
double m_dEccen2_sqd
UINT32 m_epsgCode
ELLIPSOID_TYPE m_ellipsoidType
Detailed Description
Definition at line 44 of file dnaellipsoid.hpp.
Constructor & Destructor Documentation
CDnaEllipsoid() [1/5]
dynadjust::datum_parameters::CDnaEllipsoid::CDnaEllipsoid (void)
Definition at line 32 of file dnaellipsoid.cpp.
    : m_epsgCode(DEFAULT_EPSG_U)
{
    // default to GRS80
    SetEllipsoid(m_epsgCode);
    CalculateEllipsoidParams();
}
References CalculateEllipsoidParams(), DEFAULT_EPSG_U(), m_epsgCode, and SetEllipsoid().
Referenced by CDnaEllipsoid(), operator=(), and operator==().
CDnaEllipsoid() [2/5]
dynadjust::datum_parameters::CDnaEllipsoid::CDnaEllipsoid (const UINT32 & epsgCode)
Definition at line 41 of file dnaellipsoid.cpp.
{
    SetEllipsoid(epsgCode);
    CalculateEllipsoidParams();
}
References CalculateEllipsoidParams(), and SetEllipsoid().
CDnaEllipsoid() [3/5]
dynadjust::datum_parameters::CDnaEllipsoid::CDnaEllipsoid (const std::string & epsgCode)
Definition at line 47 of file dnaellipsoid.cpp.
{
    UINT32 epsgCode_uint32 = LongFromString<UINT32>(trimstr(epsgCode));
    SetEllipsoid(epsgCode_uint32);
    CalculateEllipsoidParams();
}
References CalculateEllipsoidParams(), LongFromString(), SetEllipsoid(), and trimstr().
CDnaEllipsoid() [4/5]
dynadjust::datum_parameters::CDnaEllipsoid::CDnaEllipsoid (const CDnaEllipsoid & newEllipsoid)
Definition at line 54 of file dnaellipsoid.cpp.
{
    m_dA = newEllipsoid.m_dA;
    m_dInv_f = newEllipsoid.m_dInv_f;
    m_dB = newEllipsoid.m_dB;
    m_dF = newEllipsoid.m_dF;
    m_dEccen1 = newEllipsoid.m_dEccen1;
    m_dEccen2 = newEllipsoid.m_dEccen2;
    m_dEccen1_sqd = newEllipsoid.m_dEccen1_sqd;
    m_dEccen2_sqd = newEllipsoid.m_dEccen2_sqd;
    m_epsgCode = newEllipsoid.m_epsgCode;
    m_ellipsoidType = newEllipsoid.m_ellipsoidType;
}
References CDnaEllipsoid(), m_dA, m_dB, m_dEccen1, m_dEccen1_sqd, m_dEccen2, m_dEccen2_sqd, m_dF, m_dInv_f, m_ellipsoidType, and m_epsgCode.
CDnaEllipsoid() [5/5]
dynadjust::datum_parameters::CDnaEllipsoid::CDnaEllipsoid (const double & a, const double & inv_f)
Definition at line 70 of file dnaellipsoid.cpp.
{
    m_epsgCode = 0;
    m_ellipsoidType = USER_DEFINED_ELLIPSOID;
    SetEllipsoidParams(a, inv_f);
}
References m_ellipsoidType, m_epsgCode, SetEllipsoidParams(), and USER_DEFINED_ELLIPSOID.
~CDnaEllipsoid()
virtual dynadjust::datum_parameters::CDnaEllipsoid::~CDnaEllipsoid (void) inline virtual
Definition at line 57 of file dnaellipsoid.hpp.
{}
Member Function Documentation
operator=()
CDnaEllipsoid & dynadjust::datum_parameters::CDnaEllipsoid::operator= (const CDnaEllipsoid & rhs)
Definition at line 77 of file dnaellipsoid.cpp.
{
    if (this == &rhs)   // check for assignment to self!
        return *this;
    m_dA = rhs.m_dA;
    m_dB = rhs.m_dB;
    m_dInv_f = rhs.m_dInv_f;
    m_dF = rhs.m_dF;
    m_dEccen1 = rhs.m_dEccen1;
    m_dEccen2 = rhs.m_dEccen2;
    m_dEccen1_sqd = rhs.m_dEccen1_sqd;
    m_dEccen2_sqd = rhs.m_dEccen2_sqd;
    m_epsgCode = rhs.m_epsgCode;
    m_ellipsoidType = rhs.m_ellipsoidType;
    return *this;
}
References CDnaEllipsoid(), m_dA, m_dB, m_dEccen1, m_dEccen1_sqd, m_dEccen2, m_dEccen2_sqd, m_dF, m_dInv_f, m_ellipsoidType, and m_epsgCode.
operator==()
bool dynadjust::datum_parameters::CDnaEllipsoid::operator== (const CDnaEllipsoid & rhs) const
Definition at line 98 of file dnaellipsoid.cpp.
{
    return (
        m_dA == rhs.m_dA &&
        m_dInv_f == rhs.m_dInv_f &&
        m_epsgCode == rhs.m_epsgCode &&
        m_ellipsoidType == rhs.m_ellipsoidType
        );
}
References CDnaEllipsoid(), m_dA, m_dInv_f, m_ellipsoidType, and m_epsgCode.
GetE1()
double dynadjust::datum_parameters::CDnaEllipsoid::GetE1 () const inline
Definition at line 67 of file dnaellipsoid.hpp.
{ return m_dEccen1; }
References m_dEccen1.
GetE2()
double dynadjust::datum_parameters::CDnaEllipsoid::GetE2 () const inline
Definition at line 68 of file dnaellipsoid.hpp.
{ return m_dEccen2; }
References m_dEccen2.
Referenced by RobbinsReverse().
GetE1sqd()
double dynadjust::datum_parameters::CDnaEllipsoid::GetE1sqd () const inline
Definition at line 69 of file dnaellipsoid.hpp.
{ return m_dEccen1_sqd; }
References m_dEccen1_sqd.
Referenced by averageRadiusofCurvature(), CartToGeo_SimpleIteration(), EllipsoidChordDistance(), EllipsoidHeight(), FormCarttoGeoRotationMatrix(), GeoToCart(), GeoToGrid(), primeMeridian(), primeVertical(), primeVerticalandMeridian(), and RobbinsReverse().
GetE2sqd()
double dynadjust::datum_parameters::CDnaEllipsoid::GetE2sqd () const inline
Definition at line 70 of file dnaellipsoid.hpp.
{ return m_dEccen2_sqd; }
References m_dEccen2_sqd.
GetSemiMajor()
double dynadjust::datum_parameters::CDnaEllipsoid::GetSemiMajor () const inline
Definition at line 71 of file dnaellipsoid.hpp.
{ return m_dA; }
References m_dA.
Referenced by averageRadiusofCurvature(), CartToGeo(), CartToGeo_SimpleIteration(), CartToLat(), FormCarttoGeoRotationMatrix(), GeoToGrid(), primeMeridian(), primeVertical(), primeVerticalandMeridian(), dynadjust::measurements::CDnaStation::ReduceStations_LLH(), dynadjust::measurements::CDnaStation::ReduceStations_XYZ(), and VincentyDirect().
GetSemiMinor()
double dynadjust::datum_parameters::CDnaEllipsoid::GetSemiMinor () const inline
Definition at line 72 of file dnaellipsoid.hpp.
{ return m_dB; }
References m_dB.
Referenced by CartToGeo(), CartToLat(), and VincentyDirect().
GetInverseFlattening()
double dynadjust::datum_parameters::CDnaEllipsoid::GetInverseFlattening () const inline
Definition at line 73 of file dnaellipsoid.hpp.
{ return m_dInv_f; }
References m_dInv_f.
Referenced by dynadjust::measurements::CDnaStation::ReduceStations_LLH(), and dynadjust::measurements::CDnaStation::ReduceStations_XYZ().
GetFlattening()
double dynadjust::datum_parameters::CDnaEllipsoid::GetFlattening () const inline
Definition at line 74 of file dnaellipsoid.hpp.
{ return m_dF; }
References m_dF.
Referenced by CartToGeo_SimpleIteration(), and VincentyDirect().
SetSemiMajor()
void dynadjust::datum_parameters::CDnaEllipsoid::SetSemiMajor (const double & a) inline
Definition at line 75 of file dnaellipsoid.hpp.
{ m_dA = a; }
References m_dA.
SetInverseFlattening()
void dynadjust::datum_parameters::CDnaEllipsoid::SetInverseFlattening (const double & inv_f) inline
Definition at line 76 of file dnaellipsoid.hpp.
{ m_dInv_f = inv_f; }
References m_dInv_f.
SetEllipsoid()
void dynadjust::datum_parameters::CDnaEllipsoid::SetEllipsoid (const UINT32 & epsgCode)
Definition at line 108 of file dnaellipsoid.cpp.
{
    m_epsgCode = epsgCode;
    m_ellipsoidType = EPSG_DEFINED_ELLIPSOID;
    epsg_spheroid ellipsoid;
    spheroidFromEpsgCode<UINT32>(epsgCode, ellipsoid);
    SetEllipsoidParams(ellipsoid.semi_major_, ellipsoid.inv_flattening_);
}
References EPSG_DEFINED_ELLIPSOID, dynadjust::epsg::epsg_spheroid::inv_flattening_, m_ellipsoidType, m_epsgCode, dynadjust::epsg::epsg_spheroid::semi_major_, SetEllipsoidParams(), and dynadjust::epsg::spheroidFromEpsgCode().
Referenced by CDnaEllipsoid(), CDnaEllipsoid(), and CDnaEllipsoid().
SetEllipsoidParams()
void dynadjust::datum_parameters::CDnaEllipsoid::SetEllipsoidParams (const double & a, const double & inv_f) private
Definition at line 118 of file dnaellipsoid.cpp.
{
    m_dA = a;
    m_dInv_f = inv_f;
    CalculateEllipsoidParams();
}
References CalculateEllipsoidParams(), m_dA, and m_dInv_f.
Referenced by CDnaEllipsoid(), and SetEllipsoid().
CalculateEllipsoidParams()
void dynadjust::datum_parameters::CDnaEllipsoid::CalculateEllipsoidParams () private
Definition at line 125 of file dnaellipsoid.cpp.
{
    m_dB = m_dA * (1.0 - (1.0 / m_dInv_f));
    double dAsqd = m_dA * m_dA;
    double dBsqd = m_dB * m_dB;
    m_dEccen1_sqd = (dAsqd - dBsqd) / dAsqd;   // first ecc squared
    m_dEccen1 = sqrt(m_dEccen1_sqd);          // first ecc
    m_dEccen2_sqd = (dAsqd - dBsqd) / dBsqd;   // second ecc squared
    m_dEccen2 = sqrt(m_dEccen2_sqd);          // second ecc
    m_dF = 1.0 / m_dInv_f;
}
References m_dA, m_dB, m_dEccen1, m_dEccen1_sqd, m_dEccen2, m_dEccen2_sqd, m_dF, and m_dInv_f.
Referenced by CDnaEllipsoid(), CDnaEllipsoid(), CDnaEllipsoid(), and SetEllipsoidParams().
Member Data Documentation
m_dA
double dynadjust::datum_parameters::CDnaEllipsoid::m_dA private
Definition at line 84 of file dnaellipsoid.hpp.
Referenced by CalculateEllipsoidParams(), CDnaEllipsoid(), GetSemiMajor(), operator=(), operator==(), SetEllipsoidParams(), and SetSemiMajor().
m_dB
double dynadjust::datum_parameters::CDnaEllipsoid::m_dB private
Definition at line 85 of file dnaellipsoid.hpp.
Referenced by CalculateEllipsoidParams(), CDnaEllipsoid(), GetSemiMinor(), and operator=().
m_dInv_f
double dynadjust::datum_parameters::CDnaEllipsoid::m_dInv_f private
Definition at line 86 of file dnaellipsoid.hpp.
Referenced by CalculateEllipsoidParams(), CDnaEllipsoid(), GetInverseFlattening(), operator=(), operator==(), SetEllipsoidParams(), and SetInverseFlattening().
m_dF
double dynadjust::datum_parameters::CDnaEllipsoid::m_dF private
Definition at line 87 of file dnaellipsoid.hpp.
Referenced by CalculateEllipsoidParams(), CDnaEllipsoid(), GetFlattening(), and operator=().
m_dEccen1
double dynadjust::datum_parameters::CDnaEllipsoid::m_dEccen1 private
Definition at line 88 of file dnaellipsoid.hpp.
Referenced by CalculateEllipsoidParams(), CDnaEllipsoid(), GetE1(), and operator=().
m_dEccen1_sqd
double dynadjust::datum_parameters::CDnaEllipsoid::m_dEccen1_sqd private
Definition at line 89 of file dnaellipsoid.hpp.
Referenced by CalculateEllipsoidParams(), CDnaEllipsoid(), GetE1sqd(), and operator=().
m_dEccen2
double dynadjust::datum_parameters::CDnaEllipsoid::m_dEccen2 private
Definition at line 90 of file dnaellipsoid.hpp.
Referenced by CalculateEllipsoidParams(), CDnaEllipsoid(), GetE2(), and operator=().
m_dEccen2_sqd
double dynadjust::datum_parameters::CDnaEllipsoid::m_dEccen2_sqd private
Definition at line 91 of file dnaellipsoid.hpp.
Referenced by CalculateEllipsoidParams(), CDnaEllipsoid(), GetE2sqd(), and operator=().
m_epsgCode
UINT32 dynadjust::datum_parameters::CDnaEllipsoid::m_epsgCode private
Definition at line 95 of file dnaellipsoid.hpp.
Referenced by CDnaEllipsoid(), CDnaEllipsoid(), CDnaEllipsoid(), operator=(), operator==(), and SetEllipsoid().
m_ellipsoidType
ELLIPSOID_TYPE dynadjust::datum_parameters::CDnaEllipsoid::m_ellipsoidType private
Definition at line 96 of file dnaellipsoid.hpp.
Referenced by CDnaEllipsoid(), CDnaEllipsoid(), operator=(), operator==(), and SetEllipsoid().
The documentation for this class was generated from the following files:
include/parameters/dnaellipsoid.hpp
include/parameters/dnaellipsoid.cpp