DynAdjust: dynadjust::iostreams::dna_io_bms Class Reference
dynadjust::iostreams::dna_io_bms Class Reference
#include <dnaiobms.hpp>
Public Member Functions
dna_io_bms (void)
dna_io_bms (const dna_io_bms &bms)
virtual ~dna_io_bms (void)
dna_io_bms & operator= (const dna_io_bms &rhs)
UINT16 create_msr_input_file_meta (vifm_t &vinput_file_meta, input_file_meta_t **input_file_meta)
void load_bms_file_meta (const std::string &bms_filename, binary_file_meta_t &bms_meta)
UINT32 load_bms_file (const std::string &bms_filename, pvmsr_t vbinary_msr, binary_file_meta_t &bms_meta)
void write_bms_file (const std::string &bms_filename, pvmsr_t vbinary_msr, binary_file_meta_t &bms_meta)
void write_bms_file (const std::string &bms_filename, vdnaMsrPtr *vMeasurements, binary_file_meta_t &bms_meta)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 41 of file dnaiobms.hpp.
Constructor & Destructor Documentation
dna_io_bms() [1/2]
dynadjust::iostreams::dna_io_bms::dna_io_bms (void) inline
Definition at line 44 of file dnaiobms.hpp.
{};
Referenced by dna_io_bms(), and operator=().
dna_io_bms() [2/2]
dynadjust::iostreams::dna_io_bms::dna_io_bms (const dna_io_bms & bms) inline
Definition at line 45 of file dnaiobms.hpp.
: dna_io_base(bms) {};
References dynadjust::iostreams::dna_io_base::dna_io_base(), and dna_io_bms().
~dna_io_bms()
virtual dynadjust::iostreams::dna_io_bms::~dna_io_bms (void) inline virtual
Definition at line 46 of file dnaiobms.hpp.
{};
Member Function Documentation
operator=()
dna_io_bms & dynadjust::iostreams::dna_io_bms::operator= (const dna_io_bms & rhs)
References dna_io_bms().
create_msr_input_file_meta()
UINT16 dynadjust::iostreams::dna_io_bms::create_msr_input_file_meta (vifm_t & vinput_file_meta, input_file_meta_t ** input_file_meta)
Definition at line 29 of file dnaiobms.cpp.
{
    UINT16 msr_file_count(0);
    std::stringstream ss;
    ss << "create_msr_input_file_meta(): An error was encountered when creating " << std::endl <<
        "  the binary measurement file metadata." << std::endl;
    // Determine how many measurement files were supplied
    try {
        for_each(vinput_file_meta.begin(), vinput_file_meta.end(),
            [&msr_file_count] (input_file_meta_t& ifm) {
                if (ifm.datatype == msr_data || ifm.datatype == stn_msr_data)
                    msr_file_count++;
        });
        if (*input_file_meta != NULL)
            delete [] *input_file_meta;
        (*input_file_meta) = new input_file_meta_t[msr_file_count];
        msr_file_count = 0;
        for_each(vinput_file_meta.begin(), vinput_file_meta.end(),
            [&msr_file_count, &input_file_meta] (input_file_meta_t& ifm) {
                if (ifm.datatype == msr_data || ifm.datatype == stn_msr_data)
                {
                    (*input_file_meta)[msr_file_count] = ifm;
                    msr_file_count++;
                }
        });
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return msr_file_count;
}
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseBms().
load_bms_file_meta()
void dynadjust::iostreams::dna_io_bms::load_bms_file_meta (const std::string & bms_filename, binary_file_meta_t & bms_meta)
Definition at line 67 of file dnaiobms.cpp.
{
    std::ifstream bms_file;
    std::stringstream ss;
    ss << "load_bms_file(): An error was encountered when opening " << bms_filename << "." << std::endl;
    try {
        // open binary measurements file.  Throws runtime_error on failure.
        file_opener(bms_file, bms_filename, std::ios::in | std::ios::binary, binary, true);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "load_bms_file(): An error was encountered when reading from " << bms_filename << "." << std::endl;
    try {
        // read the file information
        readFileInfo(bms_file);
        // read the metadata
        readFileMetadata(bms_file, bms_meta);
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    bms_file.close();
}
References binary, file_opener(), load_bms_file_meta(), dynadjust::iostreams::dna_io_base::readFileInfo(), and dynadjust::iostreams::dna_io_base::readFileMetadata().
Referenced by load_bms_file_meta(), LoadBinaryMeta(), main(), and PrepareImportSegmentedData().
load_bms_file()
UINT32 dynadjust::iostreams::dna_io_bms::load_bms_file (const std::string & bms_filename, pvmsr_t vbinary_msr, binary_file_meta_t & bms_meta)
Definition at line 110 of file dnaiobms.cpp.
{
    std::ifstream bms_file;
    std::stringstream ss;
    ss << "load_bms_file(): An error was encountered when opening " << bms_filename << "." << std::endl;
    try {
        // open binary measurements file.  Throws runtime_error on failure.
        file_opener(bms_file, bms_filename, std::ios::in | std::ios::binary, binary, true);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    measurement_t measRecord;
    UINT32 msr;
    ss.str("");
    ss << "load_bms_file(): An error was encountered when reading from " << bms_filename << "." << std::endl;
    try {
        // read the file information
        readFileInfo(bms_file);
        // read the metadata
        readFileMetadata(bms_file, bms_meta);
        // read the bms data
        vbinary_msr->reserve(bms_meta.binCount);
        for (msr=0; msr<bms_meta.binCount; msr++)
        {
            bms_file.read(reinterpret_cast<char *>(&measRecord), sizeof(measurement_t));
            vbinary_msr->push_back(measRecord);
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    bms_file.close();
    return bms_meta.binCount;
}
References binary, binary_file_meta::binCount, file_opener(), load_bms_file(), dynadjust::iostreams::dna_io_base::readFileInfo(), and dynadjust::iostreams::dna_io_base::readFileMetadata().
Referenced by load_bms_file(), dynadjust::dynamlinterop::dna_import::LoadBinaryFiles(), dynadjust::networkplot::dna_plot::LoadBinaryFiles(), dynadjust::networksegment::dna_segment::LoadBinaryFiles(), dynadjust::referenceframe::dna_reftran::LoadBinaryMeasurementFile(), dynadjust::networkadjust::dna_adjust::LoadNetworkFiles(), dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations(), and dynadjust::iostreams::dna_io_aml::write_aml_file_txt().
write_bms_file() [1/2]
void dynadjust::iostreams::dna_io_bms::write_bms_file (const std::string & bms_filename, pvmsr_t vbinary_msr, binary_file_meta_t & bms_meta)
Definition at line 166 of file dnaiobms.cpp.
{
    std::ofstream bms_file;
    std::stringstream ss;
    ss << "write_bms_file(): An error was encountered when opening " << bms_filename << "." << std::endl;
    try {
        // open binary measurements file.  Throws runtime_error on failure.
        file_opener(bms_file, bms_filename,
            std::ios::out | std::ios::binary, binary);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_bms_file(): An error was encountered when writing to " << bms_filename << "." << std::endl;
    try {
        // write the file information
        writeFileInfo(bms_file);
        // write the metadata
        writeFileMetadata(bms_file, bms_meta);
        // write the bms data
        it_vmsr_t _it_msr(vbinary_msr->begin());
        for (_it_msr=vbinary_msr->begin(); _it_msr!=vbinary_msr->end(); ++_it_msr)
            bms_file.write(reinterpret_cast<char *>(&(*_it_msr)), sizeof(measurement_t));
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    bms_file.close();
}
References binary, file_opener(), write_bms_file(), dynadjust::iostreams::dna_io_base::writeFileInfo(), and dynadjust::iostreams::dna_io_base::writeFileMetadata().
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseBms(), dynadjust::networkadjust::dna_adjust::UpdateBinaryFiles(), write_bms_file(), write_bms_file(), and dynadjust::referenceframe::dna_reftran::WriteBinaryMeasurementFile().
write_bms_file() [2/2]
void dynadjust::iostreams::dna_io_bms::write_bms_file (const std::string & bms_filename, vdnaMsrPtr * vMeasurements, binary_file_meta_t & bms_meta)
Definition at line 215 of file dnaiobms.cpp.
{
    std::ofstream bms_file;
    std::stringstream ss;
    ss << "write_bms_file(): An error was encountered when opening " << bms_filename << "." << std::endl;
    try {
        // open binary measurements file.  Throws runtime_error on failure.
        file_opener(bms_file, bms_filename,
            std::ios::out | std::ios::binary, binary);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_bms_file(): An error was encountered when writing to " << bms_filename << "." << std::endl;
    _it_vdnamsrptr _it_msr;
    UINT32 msrIndex(0);
    try {
        // write the file information
        writeFileInfo(bms_file);
        // write the metadata
        writeFileMetadata(bms_file, bms_meta);
        // write the bms data
        for (_it_msr=vMeasurements->begin(); _it_msr!=vMeasurements->end(); ++_it_msr)
            _it_msr->get()->WriteBinaryMsr(&bms_file, &msrIndex);
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    bms_file.close();
}
References binary, file_opener(), write_bms_file(), dynadjust::iostreams::dna_io_base::writeFileInfo(), and dynadjust::iostreams::dna_io_base::writeFileMetadata().
The documentation for this class was generated from the following files:
include/io/dnaiobms.hpp
include/io/dnaiobms.cpp