DynAdjust: dynadjust::iostreams::dna_io_map Class Reference
dynadjust::iostreams::dna_io_map Class Reference
#include <dnaiomap.hpp>
Public Member Functions
dna_io_map (void)
dna_io_map (const dna_io_map &map)
virtual ~dna_io_map (void)
dna_io_map & operator= (const dna_io_map &rhs)
void load_map_file (const std::string &map_filename, pv_string_uint32_pair stnsMap)
void write_map_file (const std::string &map_filename, pv_string_uint32_pair stnsMap)
void write_map_file_txt (const std::string &map_filename, pv_string_uint32_pair stnsMap)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 38 of file dnaiomap.hpp.
Constructor & Destructor Documentation
dna_io_map() [1/2]
dynadjust::iostreams::dna_io_map::dna_io_map (void) inline
Definition at line 41 of file dnaiomap.hpp.
{};
Referenced by dna_io_map(), and operator=().
dna_io_map() [2/2]
dynadjust::iostreams::dna_io_map::dna_io_map (const dna_io_map & map) inline
Definition at line 42 of file dnaiomap.hpp.
: dna_io_base(map) {};
References dynadjust::iostreams::dna_io_base::dna_io_base(), and dna_io_map().
~dna_io_map()
virtual dynadjust::iostreams::dna_io_map::~dna_io_map (void) inline virtual
Definition at line 43 of file dnaiomap.hpp.
{};
Member Function Documentation
operator=()
dna_io_map & dynadjust::iostreams::dna_io_map::operator= (const dna_io_map & rhs)
References dna_io_map().
load_map_file()
void dynadjust::iostreams::dna_io_map::load_map_file (const std::string & map_filename, pv_string_uint32_pair stnsMap)
Definition at line 34 of file dnaiomap.cpp.
{
    std::ifstream map_file;
    std::stringstream ss;
    ss << "load_map_file(): An error was encountered when opening " << map_filename << "." << std::endl;
    try {
        // open stations map file.  Throws runtime_error on failure.
        file_opener(map_file, map_filename, std::ios::in | std::ios::binary, binary, true);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "load_map_file(): An error was encountered when reading from " << map_filename << "." << std::endl;
    stnsMap->clear();
    UINT32 mapsize;
    string_uint32_pair stnID;
    char stationName[STN_NAME_WIDTH]; // 56 characters
    try {
        // read the file information
        readFileInfo(map_file);
        // read the number of records
        map_file.read(reinterpret_cast<char *>(&mapsize), sizeof(UINT32));
        stnsMap->reserve(mapsize);
        // read the records
        for (UINT32 i=0; i<mapsize; i++)
        {
            map_file.read(const_cast<char *>(stationName), sizeof(stationName));
            stnID.first = stationName;
            map_file.read(reinterpret_cast<char *>(&stnID.second), sizeof(UINT32));
            stnsMap->push_back(stnID);
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    map_file.close();
    if (stnsMap->size() < mapsize)
        throw boost::enable_current_exception(
            std::runtime_error("load_map_file(): Could not allocate sufficient memory for the Station map."));
}
References binary, file_opener(), dynadjust::iostreams::dna_io_base::readFileInfo(), and STN_NAME_WIDTH().
Referenced by dynadjust::networkadjust::dna_adjust::LoadStationMap(), dynadjust::networkplot::dna_plot::LoadStationMap(), and dynadjust::networksegment::dna_segment::LoadStationMap().
write_map_file()
void dynadjust::iostreams::dna_io_map::write_map_file (const std::string & map_filename, pv_string_uint32_pair stnsMap)
Definition at line 96 of file dnaiomap.cpp.
{
    std::ofstream map_file;
    std::stringstream ss;
    ss << "write_map_file(): An error was encountered when opening " << map_filename << "." << std::endl;
    try {
        // Open station map file.  Throws runtime_error on failure.
        file_opener(map_file, map_filename,
            std::ios::out | std::ios::binary, binary);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_map_file(): An error was encountered when writing to " << map_filename << "." << std::endl;
    v_string_uint32_pair::const_iterator _it_stnmap(stnsMap->begin());
    UINT32 mapval(static_cast<UINT32>(stnsMap->size()));
    try {
        // write the file information
        writeFileInfo(map_file);
        // write the data
        map_file.write(reinterpret_cast<char *>(&mapval), sizeof(UINT32));
        char stationName[STN_NAME_WIDTH];
        memset(stationName, '\0', sizeof(stationName));
        for (; _it_stnmap!=stnsMap->end(); ++_it_stnmap)
        {
            strcpy(stationName, _it_stnmap->first.c_str());
            mapval = _it_stnmap->second;
            map_file.write(stationName, sizeof(stationName));
            map_file.write(reinterpret_cast<char *>(&mapval), sizeof(UINT32));
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    map_file.close();
}
References binary, file_opener(), STN_NAME_WIDTH(), and dynadjust::iostreams::dna_io_base::writeFileInfo().
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseMap().
write_map_file_txt()
void dynadjust::iostreams::dna_io_map::write_map_file_txt (const std::string & map_filename, pv_string_uint32_pair stnsMap)
Definition at line 152 of file dnaiomap.cpp.
{
    std::ofstream map_file;
    std::stringstream ss;
    ss << "write_map_file_txt(): An error was encountered when opening " << map_filename << "." << std::endl;
    try {
        // Create station map text file.  Throws runtime_error on failure.
        file_opener(map_file, map_filename);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_map_file_txt(): An error was encountered when writing to " << map_filename << "." << std::endl;
    try {
        std::stringstream ss_map;
        ss_map << stnsMap->size() << " stations";
        map_file << std::left << std::setw(STATION) << ss_map.str();
        map_file << std::setw(HEADER_20) << std::right << "Stn. index" << std::endl;
        v_string_uint32_pair::const_iterator _it_stnmap(stnsMap->begin());
        for (_it_stnmap=stnsMap->begin(); _it_stnmap!=stnsMap->end(); ++_it_stnmap)
        {
            map_file << std::setw(STATION) << std::left <<
                _it_stnmap->first.c_str() <<
                std::setw(HEADER_20) << std::right << _it_stnmap->second << std::endl;
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    map_file.close();
}
References file_opener(), HEADER_20(), and STATION().
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseMapTextFile().
The documentation for this class was generated from the following files:
include/io/dnaiomap.hpp
include/io/dnaiomap.cpp