DynAdjust: CdnageoidintApp Class Reference
CdnageoidintApp Class Reference
#include <dnageoidint.h>
Public Member Functions
CdnageoidintApp ()
~CdnageoidintApp ()
virtual BOOL InitInstance ()
Detailed Description
Definition at line 18 of file dnageoidint.h.
Constructor & Destructor Documentation
CdnageoidintApp()
CdnageoidintApp::CdnageoidintApp ()
Definition at line 159 of file dnageoidint.cpp.
{
    // support Restart Manager
    m_dwRestartManagerSupportFlags = AFX_RESTART_MANAGER_SUPPORT_RESTART;
}
References CdnageoidintApp().
Referenced by CdnageoidintApp().
~CdnageoidintApp()
CdnageoidintApp::~CdnageoidintApp ()
Definition at line 166 of file dnageoidint.cpp.
{
}
Member Function Documentation
InitInstance()
BOOL CdnageoidintApp::InitInstance () virtual
Definition at line 177 of file dnageoidint.cpp.
{
    // Is GeoidInt already running?
    if (AppIsAlreadyRunning())
        return FALSE;
    // InitCommonControlsEx() is required on Windows XP if an application
    // manifest specifies use of ComCtl32.dll version 6 or later to enable
    // visual styles.  Otherwise, any window creation will fail.
    INITCOMMONCONTROLSEX InitCtrls;
    InitCtrls.dwSize = sizeof(InitCtrls);
    // Set this to include all the common control classes you want to use
    // in your application.
    InitCtrls.dwICC = ICC_WIN95_CLASSES;
    InitCommonControlsEx(&InitCtrls);
    CWinApp::InitInstance();
    // Create the shell manager, in case the dialog contains
    // any shell tree view or shell list view controls.
    CShellManager *pShellManager = new CShellManager;
    // Standard initialization
    // If you are not using these features and wish to reduce the size
    // of your final executable, you should remove from the following
    // the specific initialization routines you do not need
    // Change the registry key under which our settings are stored
    CdnageoidintDlg dlg;
    m_pMainWnd = &dlg;
    CRegProc Registry;
    // Read grid file location from preferences file
    if (Registry.PreferencesFileExists())
    {
        Registry.GetTemporaryFileSettings(&dlg.tUserSettings);
    }
    else if (Registry.CreatePreferencesFile())
    {
        Registry.InitialiseSettings(&dlg.tUserSettings);
    }
    else
    {
        CString msg;
        msg.Format("Error: Unable to load user settings.\n\n");
        msg += "You may not have read/write access to\n" + Registry.GetPreferencesFolder() + ".";
        msg += "\n\nContact your local system administrator for assistance.";
        AfxMessageBox(msg);
    }
    INT_PTR nResponse = dlg.DoModal();
    if (nResponse == IDOK)
    {
        // Place code here to handle when the dialog is
        // dismissed with OK
    }
    else if (nResponse == IDCANCEL)
    {
        // Place code here to handle when the dialog is
        // dismissed with Cancel
    }
    Registry.SaveTemporaryFileSettings(&dlg.tUserSettings);
    // Delete the shell manager created above.
    if (pShellManager != NULL)
    {
        delete pShellManager;
    }
    // Since the dialog has been closed, return FALSE so that we exit the
    //  application, rather than start the application's message pump.
    return FALSE;
}
References AppIsAlreadyRunning(), CRegProc::CreatePreferencesFile(), FALSE, CRegProc::GetPreferencesFolder(), CRegProc::GetTemporaryFileSettings(), CRegProc::InitialiseSettings(), CRegProc::PreferencesFileExists(), CRegProc::SaveTemporaryFileSettings(), and CdnageoidintDlg::tUserSettings.
The documentation for this class was generated from the following files:
dynadjust/dnageoidint/dnageoidint.h
dynadjust/dnageoidint/dnageoidint.cpp