DynAdjust: GPSCovariance_pskel Class Reference
GPSCovariance_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void m11 (const ::std::string &)
virtual void m12 (const ::std::string &)
virtual void m13 (const ::std::string &)
virtual void m21 (const ::std::string &)
virtual void m22 (const ::std::string &)
virtual void m23 (const ::std::string &)
virtual void m31 (const ::std::string &)
virtual void m32 (const ::std::string &)
virtual void m33 (const ::std::string &)
virtual void post_GPSCovariance ()
void m11_parser (::xml_schema::string_pskel &)
void m12_parser (::xml_schema::string_pskel &)
void m13_parser (::xml_schema::string_pskel &)
void m21_parser (::xml_schema::string_pskel &)
void m22_parser (::xml_schema::string_pskel &)
void m23_parser (::xml_schema::string_pskel &)
void m31_parser (::xml_schema::string_pskel &)
void m32_parser (::xml_schema::string_pskel &)
void m33_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &)
GPSCovariance_pskel ()
void InitparentGpsBaseline (dnaMsrPtr pGpsBaseline)
Protected Member Functions
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * m11_parser_
::xml_schema::string_pskel * m12_parser_
::xml_schema::string_pskel * m13_parser_
::xml_schema::string_pskel * m21_parser_
::xml_schema::string_pskel * m22_parser_
::xml_schema::string_pskel * m23_parser_
::xml_schema::string_pskel * m31_parser_
::xml_schema::string_pskel * m32_parser_
::xml_schema::string_pskel * m33_parser_
dnaCovariancePtr _dnaGpsCovariance
dnaMsrPtr _parent_dnaGpsBaseline
Detailed Description
Definition at line 947 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
GPSCovariance_pskel()
GPSCovariance_pskel::GPSCovariance_pskel ()
Definition at line 657 of file dnaparser_pskel.cxx.
    : m11_parser_ (0),
    m12_parser_ (0),
    m13_parser_ (0),
    m21_parser_ (0),
    m22_parser_ (0),
    m23_parser_ (0),
    m31_parser_ (0),
    m32_parser_ (0),
    m33_parser_ (0)
{
}
References m11_parser_, m12_parser_, m13_parser_, m21_parser_, m22_parser_, m23_parser_, m31_parser_, m32_parser_, and m33_parser_.
Member Function Documentation
m11()
void GPSCovariance_pskel::m11 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2461 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m12()
void GPSCovariance_pskel::m12 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2465 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m13()
void GPSCovariance_pskel::m13 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2469 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m21()
void GPSCovariance_pskel::m21 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2473 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m22()
void GPSCovariance_pskel::m22 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2477 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m23()
void GPSCovariance_pskel::m23 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2481 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m31()
void GPSCovariance_pskel::m31 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2485 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m32()
void GPSCovariance_pskel::m32 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2489 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
m33()
void GPSCovariance_pskel::m33 (const ::std::string &) virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2493 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
post_GPSCovariance()
void GPSCovariance_pskel::post_GPSCovariance () virtual
Reimplemented in GPSCovariance_pimpl.
Definition at line 2497 of file dnaparser_pskel.cxx.
{
}
m11_parser()
void GPSCovariance_pskel::m11_parser (::xml_schema::string_pskel & p)
Definition at line 591 of file dnaparser_pskel.cxx.
{
    this->m11_parser_ = &p;
}
References m11_parser_.
m12_parser()
void GPSCovariance_pskel::m12_parser (::xml_schema::string_pskel & p)
Definition at line 596 of file dnaparser_pskel.cxx.
{
    this->m12_parser_ = &p;
}
References m12_parser_.
m13_parser()
void GPSCovariance_pskel::m13_parser (::xml_schema::string_pskel & p)
Definition at line 601 of file dnaparser_pskel.cxx.
{
    this->m13_parser_ = &p;
}
References m13_parser_.
m21_parser()
void GPSCovariance_pskel::m21_parser (::xml_schema::string_pskel & p)
Definition at line 606 of file dnaparser_pskel.cxx.
{
    this->m21_parser_ = &p;
}
References m21_parser_.
m22_parser()
void GPSCovariance_pskel::m22_parser (::xml_schema::string_pskel & p)
Definition at line 611 of file dnaparser_pskel.cxx.
{
    this->m22_parser_ = &p;
}
References m22_parser_.
m23_parser()
void GPSCovariance_pskel::m23_parser (::xml_schema::string_pskel & p)
Definition at line 616 of file dnaparser_pskel.cxx.
{
    this->m23_parser_ = &p;
}
References m23_parser_.
m31_parser()
void GPSCovariance_pskel::m31_parser (::xml_schema::string_pskel & p)
Definition at line 621 of file dnaparser_pskel.cxx.
{
    this->m31_parser_ = &p;
}
References m31_parser_.
m32_parser()
void GPSCovariance_pskel::m32_parser (::xml_schema::string_pskel & p)
Definition at line 626 of file dnaparser_pskel.cxx.
{
    this->m32_parser_ = &p;
}
References m32_parser_.
m33_parser()
void GPSCovariance_pskel::m33_parser (::xml_schema::string_pskel & p)
Definition at line 631 of file dnaparser_pskel.cxx.
{
    this->m33_parser_ = &p;
}
References m33_parser_.
parsers()
void GPSCovariance_pskel::parsers (::xml_schema::string_pskel & m11, ::xml_schema::string_pskel & m12, ::xml_schema::string_pskel & m13, ::xml_schema::string_pskel & m21, ::xml_schema::string_pskel & m22, ::xml_schema::string_pskel & m23, ::xml_schema::string_pskel & m31, ::xml_schema::string_pskel & m32, ::xml_schema::string_pskel & m33)
Definition at line 636 of file dnaparser_pskel.cxx.
{
    this->m11_parser_ = &m11;
    this->m12_parser_ = &m12;
    this->m13_parser_ = &m13;
    this->m21_parser_ = &m21;
    this->m22_parser_ = &m22;
    this->m23_parser_ = &m23;
    this->m31_parser_ = &m31;
    this->m32_parser_ = &m32;
    this->m33_parser_ = &m33;
}
References m11(), m11_parser_, m12(), m12_parser_, m13(), m13_parser_, m21(), m21_parser_, m22(), m22_parser_, m23(), m23_parser_, m31(), m31_parser_, m32(), m32_parser_, m33(), and m33_parser_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
InitparentGpsBaseline()
void GPSCovariance_pskel::InitparentGpsBaseline (dnaMsrPtr pGpsBaseline) inline
Definition at line 993 of file dnaparser_pskel.hxx.
    {
        _parent_dnaGpsBaseline = pGpsBaseline;
    }
References _parent_dnaGpsBaseline.
_start_element_impl()
bool GPSCovariance_pskel::_start_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string * t) protected virtual
Definition at line 2501 of file dnaparser_pskel.cxx.
{
    XSD_UNUSED (t);
    if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
        return true;
    if (n == "m11" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m11_parser_;
        if (this->m11_parser_)
            this->m11_parser_->pre ();
        return true;
    }
    if (n == "m12" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m12_parser_;
        if (this->m12_parser_)
            this->m12_parser_->pre ();
        return true;
    }
    if (n == "m13" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m13_parser_;
        if (this->m13_parser_)
            this->m13_parser_->pre ();
        return true;
    }
    if (n == "m21" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m21_parser_;
        if (this->m21_parser_)
            this->m21_parser_->pre ();
        return true;
    }
    if (n == "m22" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m22_parser_;
        if (this->m22_parser_)
            this->m22_parser_->pre ();
        return true;
    }
    if (n == "m23" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m23_parser_;
        if (this->m23_parser_)
            this->m23_parser_->pre ();
        return true;
    }
    if (n == "m31" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m31_parser_;
        if (this->m31_parser_)
            this->m31_parser_->pre ();
        return true;
    }
    if (n == "m32" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m32_parser_;
        if (this->m32_parser_)
            this->m32_parser_->pre ();
        return true;
    }
    if (n == "m33" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->m33_parser_;
        if (this->m33_parser_)
            this->m33_parser_->pre ();
        return true;
    }
    return false;
}
References m11_parser_, m12_parser_, m13_parser_, m21_parser_, m22_parser_, m23_parser_, m31_parser_, m32_parser_, and m33_parser_.
_end_element_impl()
bool GPSCovariance_pskel::_end_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n) protected virtual
Definition at line 2603 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
        return true;
    if (n == "m11" && ns.empty ())
    {
        if (this->m11_parser_)
            this->m11 (this->m11_parser_->post_string ());
        return true;
    }
    if (n == "m12" && ns.empty ())
    {
        if (this->m12_parser_)
            this->m12 (this->m12_parser_->post_string ());
        return true;
    }
    if (n == "m13" && ns.empty ())
    {
        if (this->m13_parser_)
            this->m13 (this->m13_parser_->post_string ());
        return true;
    }
    if (n == "m21" && ns.empty ())
    {
        if (this->m21_parser_)
            this->m21 (this->m21_parser_->post_string ());
        return true;
    }
    if (n == "m22" && ns.empty ())
    {
        if (this->m22_parser_)
            this->m22 (this->m22_parser_->post_string ());
        return true;
    }
    if (n == "m23" && ns.empty ())
    {
        if (this->m23_parser_)
            this->m23 (this->m23_parser_->post_string ());
        return true;
    }
    if (n == "m31" && ns.empty ())
    {
        if (this->m31_parser_)
            this->m31 (this->m31_parser_->post_string ());
        return true;
    }
    if (n == "m32" && ns.empty ())
    {
        if (this->m32_parser_)
            this->m32 (this->m32_parser_->post_string ());
        return true;
    }
    if (n == "m33" && ns.empty ())
    {
        if (this->m33_parser_)
            this->m33 (this->m33_parser_->post_string ());
        return true;
    }
    return false;
}
References m11(), m11_parser_, m12(), m12_parser_, m13(), m13_parser_, m21(), m21_parser_, m22(), m22_parser_, m23(), m23_parser_, m31(), m31_parser_, m32(), m32_parser_, m33(), and m33_parser_.
Member Data Documentation
m11_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m11_parser_ protected
Definition at line 1012 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m11_parser(), and parsers().
m12_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m12_parser_ protected
Definition at line 1013 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m12_parser(), and parsers().
m13_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m13_parser_ protected
Definition at line 1014 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m13_parser(), and parsers().
m21_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m21_parser_ protected
Definition at line 1015 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m21_parser(), and parsers().
m22_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m22_parser_ protected
Definition at line 1016 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m22_parser(), and parsers().
m23_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m23_parser_ protected
Definition at line 1017 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m23_parser(), and parsers().
m31_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m31_parser_ protected
Definition at line 1018 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m31_parser(), and parsers().
m32_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m32_parser_ protected
Definition at line 1019 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m32_parser(), and parsers().
m33_parser_
::xml_schema::string_pskel* GPSCovariance_pskel::m33_parser_ protected
Definition at line 1020 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSCovariance_pskel(), m33_parser(), and parsers().
_dnaGpsCovariance
dnaCovariancePtr GPSCovariance_pskel::_dnaGpsCovariance protected
Definition at line 1022 of file dnaparser_pskel.hxx.
Referenced by GPSCovariance_pimpl::m11(), GPSCovariance_pimpl::m12(), GPSCovariance_pimpl::m13(), GPSCovariance_pimpl::m21(), GPSCovariance_pimpl::m22(), GPSCovariance_pimpl::m23(), GPSCovariance_pimpl::m31(), GPSCovariance_pimpl::m32(), GPSCovariance_pimpl::m33(), GPSCovariance_pimpl::post_GPSCovariance(), and GPSCovariance_pimpl::pre().
_parent_dnaGpsBaseline
dnaMsrPtr GPSCovariance_pskel::_parent_dnaGpsBaseline protected
Definition at line 1023 of file dnaparser_pskel.hxx.
Referenced by InitparentGpsBaseline(), GPSCovariance_pimpl::post_GPSCovariance(), and GPSCovariance_pimpl::pre().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx