DynAdjust: dynadjust::iostreams::dna_io_adj Class Reference
dynadjust::iostreams::dna_io_adj Class Reference
#include <dnaioadj.hpp>
Public Member Functions
dna_io_adj (void)
dna_io_adj (const dna_io_adj &adj)
virtual ~dna_io_adj (void)
dna_io_adj & operator= (const dna_io_adj &rhs)
void print_stn_info_col_header (std::ostream &os, const std::string &stn_coord_types, const UINT16 &printStationCorrections=false)
void print_adj_stn_header (std::ostream &os)
void print_adj_stn_block_header (std::ostream &os, const UINT32 &block)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 38 of file dnaioadj.hpp.
Constructor & Destructor Documentation
dna_io_adj() [1/2]
dynadjust::iostreams::dna_io_adj::dna_io_adj (void) inline
Definition at line 41 of file dnaioadj.hpp.
{};
Referenced by dna_io_adj(), and operator=().
dna_io_adj() [2/2]
dynadjust::iostreams::dna_io_adj::dna_io_adj (const dna_io_adj & adj) inline
Definition at line 42 of file dnaioadj.hpp.
: dna_io_base(adj) {};
References dna_io_adj(), and dynadjust::iostreams::dna_io_base::dna_io_base().
~dna_io_adj()
virtual dynadjust::iostreams::dna_io_adj::~dna_io_adj (void) inline virtual
Definition at line 43 of file dnaioadj.hpp.
{};
Member Function Documentation
operator=()
dna_io_adj & dynadjust::iostreams::dna_io_adj::operator= (const dna_io_adj & rhs)
References dna_io_adj().
print_stn_info_col_header()
void dynadjust::iostreams::dna_io_adj::print_stn_info_col_header (std::ostream & os, const std::string & stn_coord_types, const UINT16 & printStationCorrections = false)
Definition at line 44 of file dnaioadj.cpp.
{
    os << std::setw(STATION) << std::left << "Station" << std::setw(CONSTRAINT) << std::left << "Const";
    _it_str_const it_s;
    UINT32 width(0);
    UINT32 j(STATION+CONSTRAINT);
    bool validType(true);
    for (it_s=stn_coord_types.begin(); it_s!=stn_coord_types.end(); ++it_s)
    {
        char c = it_s[0];
        validType = true;
        switch (c)
        {
        case 'P':
        case 'E':
            width = LAT_EAST;
            j += LAT_EAST;
            break;
        case 'L':
        case 'N':
            width = LON_NORTH;
            j += LON_NORTH;
            break;
        case 'H':
        case 'h':
            width = HEIGHT;
            j += HEIGHT;
            break;
        case 'z':
            width = ZONE;
            j += ZONE;
            break;
        case 'X':
        case 'Y':
        case 'Z':
            width = XYZ;
            j += XYZ;
            break;
        default:
            validType = false;
        }
        if (validType)
            os << std::right << std::setw(width) << CDnaStation::CoordinateName(c);
    }
    os << std::setw(PAD2) << " " <<
        std::right << std::setw(STDDEV) << "SD(e)" <<
        std::right << std::setw(STDDEV) << "SD(n)" <<
        std::right << std::setw(STDDEV) << "SD(up)";
    j += PAD2+STDDEV+STDDEV+STDDEV+PAD2+COMMENT;
    if (printStationCorrections)
    {
        os << std::setw(PAD2) << " " <<
            std::right << std::setw(HEIGHT) << "Corr(e)" <<
            std::right << std::setw(HEIGHT) << "Corr(n)" <<
            std::right << std::setw(HEIGHT) << "Corr(up)";
        j += PAD2+HEIGHT+HEIGHT+HEIGHT;
    }
    os << std::setw(PAD2) << " " << std::left << "Description" << std::endl;
    UINT32 i;
    for (i=0; i<j; ++i)
        os << "-";
    os << std::endl;
}
References COMMENT(), CONSTRAINT(), dynadjust::measurements::CDnaStation::CoordinateName(), HEIGHT(), LAT_EAST(), LON_NORTH(), PAD2(), STATION(), STDDEV(), XYZ(), and ZONE().
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjStations(), and dynadjust::networkadjust::dna_adjust::PrintAdjStationsUniqueList().
print_adj_stn_header()
void dynadjust::iostreams::dna_io_adj::print_adj_stn_header (std::ostream & os)
Definition at line 32 of file dnaioadj.cpp.
{
    os << std::endl << "Adjusted Coordinates" << std::endl <<
        "------------------------------------------" << std::endl << std::endl;
}
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjStations(), and dynadjust::networkadjust::dna_adjust::PrintAdjStationsUniqueList().
print_adj_stn_block_header()
void dynadjust::iostreams::dna_io_adj::print_adj_stn_block_header (std::ostream & os, const UINT32 & block)
Definition at line 38 of file dnaioadj.cpp.
{
    os << std::endl << "Adjusted Coordinates (Block " << block + 1 << ")" << std::endl <<
        "------------------------------------------" << std::endl << std::endl;
}
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjStations().
The documentation for this class was generated from the following files:
include/io/dnaioadj.hpp
include/io/dnaioadj.cpp