DynAdjust: dynadjust::measurements::CDnaStation Class Reference
dynadjust::measurements::CDnaStation Class Reference
#include <dnastation.hpp>
Public Member Functions
CDnaStation (const std::string &referenceframe, const std::string &epoch)
CDnaStation (const CDnaStation &)
CDnaStation (const std::string &strName, const std::string &strConstraints, const std::string &strType, const double &dXAxis, const double &dYAxis, const double &dZAxis, const double &dHeight, const std::string &strHemisphereZone, const std::string &strDescription, const std::string &strComment)
virtual ~CDnaStation ()
CDnaStation & operator= (const CDnaStation &rhs)
CDnaStation * clone () const
int CompareStationName (const std::string &s)
std::string GetName () const
std::string GetOriginalName () const
std::string GetConstraints () const
CONSTRAINT_TYPE GetConstraintType () const
std::string GetCoordType () const
double GetXAxis () const
double GetYAxis () const
double GetZAxis () const
double GetLatitude () const
double GetLongitude () const
double GetEasting () const
double GetNorthing () const
double GetHeight () const
std::string GetHemisphereZone () const
std::string GetDescription () const
std::string GetComment () const
double GetcurrentLatitude () const
double GetcurrentLongitude () const
double GetcurrentHeight () const
float GetgeoidSep () const
double GetmeridianDef () const
double GetverticalDef () const
UINT32 GetnameOrder () const
UINT32 GetZone () const
UINT32 GetfileOrder () const
bool IsUnused () const
bool IsNotUnused () const
_COORD_TYPE_ GetMyCoordTypeC () const
_HEIGHT_SYSTEM_ GetHeightSystemC (const std::string &sType) const
_HEIGHT_SYSTEM_ GetMyHeightSystemC () const
_HEIGHT_SYSTEM_ GetMyHeightSystem () const
void SetHeightSystem (const std::string &sType)
void SetHeightSystem (const _HEIGHT_SYSTEM_ &type_i)
void SetStationRec (const station_t &stationRecord)
void SetXAxis (const std::string &str)
void SetYAxis (const std::string &str)
void SetZAxis (const std::string &str)
void SetHeight (const std::string &str)
void SetCoordType (const std::string &sType)
void ReduceStations_LLH (const CDnaEllipsoid *m_eEllipsoid, const CDnaProjection *m_pProjection)
void ReduceStations_XYZ (const CDnaEllipsoid *m_eEllipsoid, const CDnaProjection *m_pProjection)
void SetXAxis_d (const double &dXAxis)
void SetYAxis_d (const double &dYAxis)
void SetZAxis_d (const double &dZAxis)
void SetXAxisStdDev_d (const double &dXAxisStdDev)
void SetYAxisStdDev_d (const double &dYAxisStdDev)
void SetZAxisStdDev_d (const double &dZAxisStdDev)
void SetHeight_d (const double &dHeight)
void SetcurrentHeight_d (const double &dHeight)
void SetName (const std::string &sName)
void SetOriginalName (const std::string &sName)
void SetOriginalName ()
void SetHemisphereZone (const std::string &sHemisphereZone)
void SetDescription (const std::string &sDescription)
void SetComment (const std::string &sComment)
void SetfileOrder (const UINT32 &order)
void SetnameOrder (const UINT32 &order)
void SetgeoidSep (const float &fgeoidSep)
void SetmeridianDef (const double &dmeridianDef)
void SetverticalDef (const double &dverticalDef)
void SetStationUnused ()
void SetStationUse (bool use)
void SetConstraints (const std::string &str)
void SetXAxisStdDev (const std::string &str)
void SetYAxisStdDev (const std::string &str)
void SetHeightStdDev (const std::string &str)
void PrepareStnData (double &lat_east_x, double &lon_north_y, double &ht_zone_z, std::string &hemisphereZone, std::string &coordinateType, UINT32 &LEX_precision, UINT32 &LNY_precision, UINT32 &HZ_precision, const CDnaEllipsoid *ellipsoid, const CDnaProjection *projection, bool writeCurrentEstimates)
void WriteBinaryStn (std::ofstream *binary_stream, const UINT16 bUnused=0)
void WriteDNAXMLStnCurrentEstimates (std::ofstream *dna_ofstream, const CDnaEllipsoid *ellipsoid, const CDnaProjection *projection, INPUT_FILE_TYPE t, const dna_stn_fields *dsw=0)
void WriteDNAXMLStnInitialEstimates (std::ofstream *dna_ofstream, const CDnaEllipsoid *ellipsoid, const CDnaProjection *projection, INPUT_FILE_TYPE t, const dna_stn_fields *dsw=0)
void WriteDNAXMLStn (std::ofstream *dna_ofstream, const CDnaEllipsoid *ellipsoid, const CDnaProjection *projection, const double &lat_east_x, const double &lon_north_y, const double &ht_zone_z, INPUT_FILE_TYPE t, const dna_stn_fields *dsw=0)
void WriteDNAStn (std::ofstream *dna_ofstream, const std::string &coordinateType, const double &lat_east_x, const double &lon_north_y, const double &ht_zone_z, std::string &hemisphereZone, const dna_stn_fields &dsw)
void WriteDynaMLStn (std::ofstream *xml_ofstream, const std::string &coordinateType, const double &lat_east_x, const double &lon_north_y, const double &ht_zone_z, std::string &hemisphereZone)
void WriteGeoidfile (std::ofstream *binary_stream)
std::string GetReferenceFrame () const
std::string GetEpoch () const
void SetReferenceFrame (const std::string &r)
void SetEpoch (const std::string &e)
void SetEpsg (const std::string &e)
Static Public Member Functions
static bool IsValidConstraint (const std::string &sConst)
static _COORD_TYPE_ GetCoordTypeC (const std::string &sType)
static std::string CoordinateName (const char &c)
Public Attributes
std::string m_strName
Protected Attributes
std::string m_strOriginalName
double m_dXAxis
double m_dYAxis
double m_dZAxis
double m_dHeight
double m_dStdDevX
double m_dStdDevY
double m_dStdDevZ
double m_dStdDevHt
std::string m_strConstraints
std::string m_strType
std::string m_strHemisphereZone
std::string m_strDescription
std::string m_strComment
char m_cLatConstraint
char m_cLonConstraint
char m_cHtConstraint
COORD_TYPE m_ctType
COORD_TYPE m_ctTypeSupplied
HEIGHT_SYSTEM m_htType
double m_dcurrentLatitude
double m_dcurrentLongitude
double m_dcurrentHeight
float m_fgeoidSep
double m_dmeridianDef
double m_dverticalDef
UINT32 m_lfileOrder
UINT32 m_lnameOrder
UINT32 m_zone
bool m_unusedStation
std::string m_referenceFrame
std::string m_epsgCode
std::string m_epoch
CONSTRAINT_TYPE m_constraintType
Friends
bool operator< (const CDnaStation &left, const CDnaStation &right)
bool operator< (const boost::shared_ptr< CDnaStation > &left, const boost::shared_ptr< CDnaStation > &right)
Detailed Description
Definition at line 155 of file dnastation.hpp.
Constructor & Destructor Documentation
CDnaStation() [1/3]
dynadjust::measurements::CDnaStation::CDnaStation (const std::string & referenceframe, const std::string & epoch)
Definition at line 107 of file dnastation.cpp.
    : m_strName(""), m_strOriginalName("")
    , m_dXAxis(0.), m_dYAxis(0.), m_dZAxis(0.), m_dHeight(0.)
    , m_dStdDevX(0.), m_dStdDevY(0.), m_dStdDevZ(0.), m_dStdDevHt(0.)
    , m_strConstraints("FFF"), m_strType(""), m_strHemisphereZone(""), m_strDescription(""), m_strComment("")
    , m_cLatConstraint('F'), m_cLonConstraint('F'), m_cHtConstraint('F')
    , m_ctType(LLH_type_i), m_ctTypeSupplied(LLH_type_i), m_htType(ORTHOMETRIC_type_i)
    , m_dcurrentLatitude(0.), m_dcurrentLongitude(0.), m_dcurrentHeight(0.)
    , m_fgeoidSep(0.), m_dmeridianDef(0.), m_dverticalDef(0.)
    , m_lfileOrder(0), m_lnameOrder(0)
    , m_zone(0), m_unusedStation(INVALID_STATION)
    , m_referenceFrame(referenceframe), m_epoch(epoch)
    , m_constraintType(free_3D)
{
    m_epsgCode = epsgStringFromName<std::string>(referenceframe);
}
References dynadjust::epsg::epsgStringFromName(), free_3D, INVALID_STATION, LLH_type_i, m_cHtConstraint, m_cLatConstraint, m_cLonConstraint, m_constraintType, m_ctType, m_ctTypeSupplied, m_dcurrentHeight, m_dcurrentLatitude, m_dcurrentLongitude, m_dHeight, m_dmeridianDef, m_dStdDevHt, m_dStdDevX, m_dStdDevY, m_dStdDevZ, m_dverticalDef, m_dXAxis, m_dYAxis, m_dZAxis, m_epoch, m_epsgCode, m_fgeoidSep, m_htType, m_lfileOrder, m_lnameOrder, m_referenceFrame, m_strComment, m_strConstraints, m_strDescription, m_strHemisphereZone, m_strName, m_strOriginalName, m_strType, m_unusedStation, m_zone, and ORTHOMETRIC_type_i.
Referenced by CDnaStation(), clone(), operator<, and operator=().
CDnaStation() [2/3]
dynadjust::measurements::CDnaStation::CDnaStation (const CDnaStation & newStation)
Definition at line 129 of file dnastation.cpp.
{
    m_strName = newStation.m_strName;
    m_strOriginalName = newStation.m_strOriginalName;
    m_strConstraints = newStation.m_strConstraints;
    m_strType = newStation.m_strType;
    m_dXAxis = newStation.m_dXAxis;
    m_dYAxis = newStation.m_dYAxis;
    m_dZAxis = newStation.m_dZAxis;
    m_dHeight = newStation.m_dHeight;
    m_dStdDevX = newStation.m_dStdDevX;
    m_dStdDevY = newStation.m_dStdDevY;
    m_dStdDevZ = newStation.m_dStdDevZ;
    m_dStdDevHt = newStation.m_dStdDevHt;
    m_strHemisphereZone = newStation.m_strHemisphereZone;
    m_strDescription = newStation.m_strDescription;
    m_cLatConstraint = newStation.m_cLatConstraint;
    m_cLonConstraint = newStation.m_cLonConstraint;
    m_cHtConstraint = newStation.m_cHtConstraint;
    m_strComment = newStation.m_strComment;
    m_ctTypeSupplied = newStation.m_ctTypeSupplied;
    m_ctType = newStation.m_ctType;
    m_htType = newStation.m_htType;
    m_dcurrentLatitude = newStation.m_dcurrentLatitude;
    m_dcurrentLongitude = newStation.m_dcurrentLongitude;
    m_dcurrentHeight = newStation.m_dcurrentHeight;
    m_fgeoidSep = newStation.m_fgeoidSep;
    m_dmeridianDef = newStation.m_dmeridianDef;
    m_dverticalDef = newStation.m_dverticalDef;
    m_lfileOrder = newStation.m_lfileOrder;
    m_lnameOrder = newStation.m_lnameOrder;
    m_zone = newStation.m_zone;
    m_unusedStation = newStation.m_unusedStation;
    m_referenceFrame = newStation.m_referenceFrame;
    m_epsgCode = newStation.m_epsgCode;
    m_epoch = newStation.m_epoch;
    m_constraintType = newStation.m_constraintType;
}
References CDnaStation(), m_cHtConstraint, m_cLatConstraint, m_cLonConstraint, m_constraintType, m_ctType, m_ctTypeSupplied, m_dcurrentHeight, m_dcurrentLatitude, m_dcurrentLongitude, m_dHeight, m_dmeridianDef, m_dStdDevHt, m_dStdDevX, m_dStdDevY, m_dStdDevZ, m_dverticalDef, m_dXAxis, m_dYAxis, m_dZAxis, m_epoch, m_epsgCode, m_fgeoidSep, m_htType, m_lfileOrder, m_lnameOrder, m_referenceFrame, m_strComment, m_strConstraints, m_strDescription, m_strHemisphereZone, m_strName, m_strOriginalName, m_strType, m_unusedStation, and m_zone.
CDnaStation() [3/3]
dynadjust::measurements::CDnaStation::CDnaStation (const std::string & strName, const std::string & strConstraints, const std::string & strType, const double & dXAxis, const double & dYAxis, const double & dZAxis, const double & dHeight, const std::string & strHemisphereZone, const std::string & strDescription, const std::string & strComment)
Definition at line 172 of file dnastation.cpp.
{
    m_strName = strName;
    m_strOriginalName = "";
    SetConstraints(strConstraints);
    SetCoordType(strType);
    m_dXAxis = dXAxis;
    m_dYAxis = dYAxis;
    m_dZAxis = dZAxis;
    m_dHeight = dHeight;
    m_dStdDevX = PRECISION_1E5;
    m_dStdDevY = PRECISION_1E5;
    m_dStdDevZ = PRECISION_1E5;
    m_dStdDevHt = PRECISION_1E4;
    if (strHemisphereZone.empty())
        m_zone = 0;
    else
        SetHemisphereZone(strHemisphereZone);
    m_strDescription = strDescription;
    m_strComment = strComment;
    m_unusedStation = INVALID_STATION;
    m_dcurrentLatitude = 0.;
    m_dcurrentLongitude = 0.;
    m_dcurrentHeight = 0.;
    m_fgeoidSep = 0.;
    m_dmeridianDef = 0.;
    m_dverticalDef = 0.;
    m_referenceFrame = DEFAULT_DATUM;
    m_epsgCode = DEFAULT_EPSG_S;
    m_epoch = "";
}
References DEFAULT_DATUM(), DEFAULT_EPSG_S(), INVALID_STATION, m_dcurrentHeight, m_dcurrentLatitude, m_dcurrentLongitude, m_dHeight, m_dmeridianDef, m_dStdDevHt, m_dStdDevX, m_dStdDevY, m_dStdDevZ, m_dverticalDef, m_dXAxis, m_dYAxis, m_dZAxis, m_epoch, m_epsgCode, m_fgeoidSep, m_referenceFrame, m_strComment, m_strDescription, m_strName, m_strOriginalName, m_unusedStation, m_zone, PRECISION_1E4(), PRECISION_1E5(), SetConstraints(), SetCoordType(), and SetHemisphereZone().
~CDnaStation()
dynadjust::measurements::CDnaStation::~CDnaStation () virtual
Definition at line 124 of file dnastation.cpp.
{
}
Member Function Documentation
operator=()
CDnaStation & dynadjust::measurements::CDnaStation::operator= (const CDnaStation & rhs)
Definition at line 215 of file dnastation.cpp.
{
    // check for assignment to self!
    if (this == &rhs)
        return *this;
    m_strName = rhs.m_strName;
    m_strConstraints = rhs.m_strConstraints;
    m_strType = rhs.m_strType;
    m_dXAxis = rhs.m_dXAxis;
    m_dYAxis = rhs.m_dYAxis;
    m_dZAxis = rhs.m_dZAxis;
    m_dHeight = rhs.m_dHeight;
    m_strHemisphereZone = rhs.m_strHemisphereZone;
    m_strDescription = rhs.m_strDescription;
    m_cLatConstraint = rhs.m_cLatConstraint;
    m_cLonConstraint = rhs.m_cLonConstraint;
    m_cHtConstraint = rhs.m_cHtConstraint;
    m_strComment = rhs.m_strComment;
    m_ctTypeSupplied = rhs.m_ctTypeSupplied;
    m_ctType = rhs.m_ctType;
    m_htType = rhs.m_htType;
    // measurement file extras
    m_dStdDevX = rhs.m_dStdDevX;
    m_dStdDevY = rhs.m_dStdDevY;
    m_dStdDevHt = rhs.m_dStdDevHt;
    m_dcurrentLatitude = rhs.m_dcurrentLatitude;
    m_dcurrentLongitude = rhs.m_dcurrentLongitude;
    m_dcurrentHeight = rhs.m_dcurrentHeight;
    m_fgeoidSep = rhs.m_fgeoidSep;
    m_dmeridianDef = rhs.m_dmeridianDef;
    m_dverticalDef = rhs.m_dverticalDef;
    m_lfileOrder = rhs.m_lfileOrder;
    m_lnameOrder = rhs.m_lnameOrder;
    m_zone = rhs.m_zone;
    m_unusedStation = rhs.m_unusedStation;
    m_referenceFrame = rhs.m_referenceFrame;
    m_epsgCode = rhs.m_epsgCode;
    m_epoch = rhs.m_epoch;
    m_constraintType = rhs.m_constraintType;
    return *this;
}
References CDnaStation(), m_cHtConstraint, m_cLatConstraint, m_cLonConstraint, m_constraintType, m_ctType, m_ctTypeSupplied, m_dcurrentHeight, m_dcurrentLatitude, m_dcurrentLongitude, m_dHeight, m_dmeridianDef, m_dStdDevHt, m_dStdDevX, m_dStdDevY, m_dverticalDef, m_dXAxis, m_dYAxis, m_dZAxis, m_epoch, m_epsgCode, m_fgeoidSep, m_htType, m_lfileOrder, m_lnameOrder, m_referenceFrame, m_strComment, m_strConstraints, m_strDescription, m_strHemisphereZone, m_strName, m_strType, m_unusedStation, and m_zone.
clone()
CDnaStation * dynadjust::measurements::CDnaStation::clone () const inline
Definition at line 165 of file dnastation.hpp.
{ return new CDnaStation(*this); }
References CDnaStation().
CompareStationName()
int dynadjust::measurements::CDnaStation::CompareStationName (const std::string & s) inline
Definition at line 172 of file dnastation.hpp.
{ return m_strName.compare(s); }
References m_strName.
GetName()
std::string dynadjust::measurements::CDnaStation::GetName () const inline
Definition at line 173 of file dnastation.hpp.
{ return m_strName; }
References m_strName.
GetOriginalName()
std::string dynadjust::measurements::CDnaStation::GetOriginalName () const inline
Definition at line 174 of file dnastation.hpp.
{ return m_strOriginalName; }
References m_strOriginalName.
GetConstraints()
std::string dynadjust::measurements::CDnaStation::GetConstraints () const inline
Definition at line 175 of file dnastation.hpp.
{ return m_strConstraints; }
References m_strConstraints.
GetConstraintType()
CONSTRAINT_TYPE dynadjust::measurements::CDnaStation::GetConstraintType () const inline
Definition at line 176 of file dnastation.hpp.
{ return m_constraintType; }
References m_constraintType.
GetCoordType()
std::string dynadjust::measurements::CDnaStation::GetCoordType () const inline
Definition at line 177 of file dnastation.hpp.
{ return m_strType; }
References m_strType.
GetXAxis()
double dynadjust::measurements::CDnaStation::GetXAxis () const inline
Definition at line 179 of file dnastation.hpp.
{ return m_dXAxis; }    // X, Easting, Latitude
References m_dXAxis.
GetYAxis()
double dynadjust::measurements::CDnaStation::GetYAxis () const inline
Definition at line 180 of file dnastation.hpp.
{ return m_dYAxis; }    // Y, Northing, Longitude
References m_dYAxis.
GetZAxis()
double dynadjust::measurements::CDnaStation::GetZAxis () const inline
Definition at line 181 of file dnastation.hpp.
{ return m_dZAxis; }    // Z
References m_dZAxis.
GetLatitude()
double dynadjust::measurements::CDnaStation::GetLatitude () const inline
Definition at line 182 of file dnastation.hpp.
{ return m_dXAxis; }
References m_dXAxis.
GetLongitude()
double dynadjust::measurements::CDnaStation::GetLongitude () const inline
Definition at line 183 of file dnastation.hpp.
{ return m_dYAxis; }
References m_dYAxis.
GetEasting()
double dynadjust::measurements::CDnaStation::GetEasting () const inline
Definition at line 184 of file dnastation.hpp.
{ return m_dXAxis; }
References m_dXAxis.
GetNorthing()
double dynadjust::measurements::CDnaStation::GetNorthing () const inline
Definition at line 185 of file dnastation.hpp.
{ return m_dYAxis; }
References m_dYAxis.
GetHeight()
double dynadjust::measurements::CDnaStation::GetHeight () const inline
Definition at line 186 of file dnastation.hpp.
{ return m_dHeight; }
References m_dHeight.
GetHemisphereZone()
std::string dynadjust::measurements::CDnaStation::GetHemisphereZone () const inline
Definition at line 187 of file dnastation.hpp.
{ return m_strHemisphereZone; }
References m_strHemisphereZone.
GetDescription()
std::string dynadjust::measurements::CDnaStation::GetDescription () const inline
Definition at line 188 of file dnastation.hpp.
{ return m_strDescription; }
References m_strDescription.
GetComment()
std::string dynadjust::measurements::CDnaStation::GetComment () const inline
Definition at line 189 of file dnastation.hpp.
{ return m_strComment; }
References m_strComment.
GetcurrentLatitude()
double dynadjust::measurements::CDnaStation::GetcurrentLatitude () const inline
Definition at line 191 of file dnastation.hpp.
{ return m_dcurrentLatitude; }
References m_dcurrentLatitude.
GetcurrentLongitude()
double dynadjust::measurements::CDnaStation::GetcurrentLongitude () const inline
Definition at line 192 of file dnastation.hpp.
{ return m_dcurrentLongitude; }
References m_dcurrentLongitude.
GetcurrentHeight()
double dynadjust::measurements::CDnaStation::GetcurrentHeight () const inline
Definition at line 193 of file dnastation.hpp.
{ return m_dcurrentHeight; }
References m_dcurrentHeight.
GetgeoidSep()
float dynadjust::measurements::CDnaStation::GetgeoidSep () const inline
Definition at line 194 of file dnastation.hpp.
{ return m_fgeoidSep; }
References m_fgeoidSep.
GetmeridianDef()
double dynadjust::measurements::CDnaStation::GetmeridianDef () const inline
Definition at line 195 of file dnastation.hpp.
{ return m_dmeridianDef; }
References m_dmeridianDef.
GetverticalDef()
double dynadjust::measurements::CDnaStation::GetverticalDef () const inline
Definition at line 196 of file dnastation.hpp.
{ return m_dverticalDef; }
References m_dverticalDef.
GetnameOrder()
UINT32 dynadjust::measurements::CDnaStation::GetnameOrder () const inline
Definition at line 197 of file dnastation.hpp.
{ return m_lnameOrder; }
References m_lnameOrder.
GetZone()
UINT32 dynadjust::measurements::CDnaStation::GetZone () const inline
Definition at line 198 of file dnastation.hpp.
{ return m_zone; }
References m_zone.
GetfileOrder()
UINT32 dynadjust::measurements::CDnaStation::GetfileOrder () const inline
Definition at line 200 of file dnastation.hpp.
{ return m_lfileOrder; }
References m_lfileOrder.
IsUnused()
bool dynadjust::measurements::CDnaStation::IsUnused () const inline
Definition at line 203 of file dnastation.hpp.
{ return m_unusedStation; }
References m_unusedStation.
IsNotUnused()
bool dynadjust::measurements::CDnaStation::IsNotUnused () const inline
Definition at line 204 of file dnastation.hpp.
{ return m_unusedStation == false; }
References m_unusedStation.
IsValidConstraint()
bool dynadjust::measurements::CDnaStation::IsValidConstraint (const std::string & sConst) static
Definition at line 441 of file dnastation.cpp.
{
    if (boost::iequals(sConst, "CCC"))
        return true;
    if (boost::iequals(sConst, "CCF"))
        return true;
    if (boost::iequals(sConst, "CFF"))
        return true;
    if (boost::iequals(sConst, "FFF"))
        return true;
    if (boost::iequals(sConst, "FFC"))
        return true;
    if (boost::iequals(sConst, "FCC"))
        return true;
    if (boost::iequals(sConst, "FCF"))
        return true;
    if (boost::iequals(sConst, "CFC"))
        return true;
    return false;
}
Referenced by dynadjust::networkadjust::dna_adjust::ApplyAdditionalConstraints().
GetCoordTypeC()
_COORD_TYPE_ dynadjust::measurements::CDnaStation::GetCoordTypeC (const std::string & sType) static
Definition at line 463 of file dnastation.cpp.
{
    // case insensitive
    if (boost::iequals(sType, XYZ_type))
        return XYZ_type_i;
    else if (boost::iequals(sType, UTM_type))
        return UTM_type_i;                // height is assumed to be orthometric
    else if (boost::iequals(sType, ENU_type))
        return ENU_type_i;
    // case sensitive
    else if (boost::equals(sType, LLh_type))
        return LLh_type_i;                // ellipsoid height
    // default
    else if (boost::equals(sType, LLH_type))
        return LLH_type_i;                    // orthometric height (default)
    // If this point is reached, sType is an unknown coordinate type, so throw!
    std::stringstream ss;
    ss << "  '" << sType << "' is not a recognised coordinate type." << std::endl;
    throw boost::enable_current_exception(std::runtime_error(ss.str()));
    return LLH_type_i;
}
References ENU_type(), ENU_type_i, LLH_type(), LLh_type(), LLH_type_i, LLh_type_i, UTM_type(), UTM_type_i, XYZ_type(), and XYZ_type_i.
Referenced by dynadjust::measurements::CDnaGpsPoint::GetMyCoordTypeC(), dynadjust::measurements::CDnaGpsPointCluster::GetMyCoordTypeC(), GetMyCoordTypeC(), dynadjust::referenceframe::dna_reftran::TransformMeasurement_Y(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_Y(), and dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_Y().
GetMyCoordTypeC()
_COORD_TYPE_ dynadjust::measurements::CDnaStation::GetMyCoordTypeC () const
Definition at line 490 of file dnastation.cpp.
{
    return GetCoordTypeC(m_strType);
}
References GetCoordTypeC(), and m_strType.
Referenced by SetCoordType(), and SetHeight().
GetHeightSystemC()
_HEIGHT_SYSTEM_ dynadjust::measurements::CDnaStation::GetHeightSystemC (const std::string & sType) const
Definition at line 496 of file dnastation.cpp.
{
    if (sType.compare(ELLIPSOIDAL_type) == 0)
        return ELLIPSOIDAL_type_i;
    return ORTHOMETRIC_type_i;        // default
}
References ELLIPSOIDAL_type(), ELLIPSOIDAL_type_i, and ORTHOMETRIC_type_i.
Referenced by SetHeightSystem().
GetMyHeightSystemC()
_HEIGHT_SYSTEM_ dynadjust::measurements::CDnaStation::GetMyHeightSystemC () const
Definition at line 504 of file dnastation.cpp.
{
    if (m_strType.compare(LLh_type) == 0)
        return ELLIPSOIDAL_type_i;
    return ORTHOMETRIC_type_i;    // default
}
References ELLIPSOIDAL_type_i, LLh_type(), m_strType, and ORTHOMETRIC_type_i.
GetMyHeightSystem()
_HEIGHT_SYSTEM_ dynadjust::measurements::CDnaStation::GetMyHeightSystem () const inline
Definition at line 211 of file dnastation.hpp.
{ return m_htType;  }
References m_htType.
SetHeightSystem() [1/2]
void dynadjust::measurements::CDnaStation::SetHeightSystem (const std::string & sType)
Definition at line 513 of file dnastation.cpp.
{
    SetHeightSystem(GetHeightSystemC(sType));
}
References GetHeightSystemC(), and SetHeightSystem().
Referenced by SetHeightSystem().
SetHeightSystem() [2/2]
void dynadjust::measurements::CDnaStation::SetHeightSystem (const _HEIGHT_SYSTEM_ & type_i)
References ReduceStations_LLH(), ReduceStations_XYZ(), SetCoordType(), SetHeight(), SetStationRec(), SetXAxis(), SetYAxis(), and SetZAxis().
SetStationRec()
void dynadjust::measurements::CDnaStation::SetStationRec (const station_t & stationRecord)
Definition at line 896 of file dnastation.cpp.
{
    SetName(stationRecord.stationName);
    SetOriginalName(stationRecord.stationNameOrig);
    SetConstraints(stationRecord.stationConst);
    SetCoordType(stationRecord.stationType);
    switch (stationRecord.suppliedStationType)
    {
    case UTM_type_i:
        m_ctTypeSupplied = UTM_type_i;
        break;
    case XYZ_type_i:
        m_ctTypeSupplied = XYZ_type_i;
        break;
    case ENU_type_i:
        m_ctTypeSupplied = ENU_type_i;
        break;
    case LLh_type_i:
        m_ctTypeSupplied = LLh_type_i;
        break;
    default:
    case LLH_type_i:
        m_ctTypeSupplied = LLH_type_i;
        break;
    }
    m_dXAxis = stationRecord.initialLatitude;
    m_dYAxis = stationRecord.initialLongitude;
    m_dHeight = stationRecord.initialHeight;
    m_dcurrentLatitude = stationRecord.currentLatitude;
    m_dcurrentLongitude = stationRecord.currentLongitude;
    m_dcurrentHeight = stationRecord.currentHeight;
    m_fgeoidSep = stationRecord.geoidSep;
    m_dmeridianDef = stationRecord.meridianDef;
    m_dverticalDef = stationRecord.verticalDef;
    m_zone = stationRecord.zone;
    if (stationRecord.initialLatitude < 0.)
        m_strHemisphereZone = "S";
    else
        m_strHemisphereZone = "N";
    char zone[3];
    snprintf(zone, sizeof(zone), "%d", m_zone);
    m_strHemisphereZone += zone;
    SetDescription(stationRecord.description);
    m_lfileOrder = stationRecord.fileOrder;
    m_lnameOrder = stationRecord.nameOrder;
    m_unusedStation = (stationRecord.unusedStation == VALID_STATION ? true : false);
    m_epoch = stationRecord.epoch;
    m_epsgCode = stationRecord.epsgCode;
    m_referenceFrame = datumFromEpsgCode<std::string, UINT32>(LongFromString<UINT32>(m_epsgCode));
}
References stn_t::currentHeight, stn_t::currentLatitude, stn_t::currentLongitude, dynadjust::epsg::datumFromEpsgCode(), stn_t::description, ENU_type_i, stn_t::epoch, stn_t::epsgCode, stn_t::fileOrder, stn_t::geoidSep, stn_t::initialHeight, stn_t::initialLatitude, stn_t::initialLongitude, LLH_type_i, LLh_type_i, LongFromString(), m_ctTypeSupplied, m_dcurrentHeight, m_dcurrentLatitude, m_dcurrentLongitude, m_dHeight, m_dmeridianDef, m_dverticalDef, m_dXAxis, m_dYAxis, m_epoch, m_epsgCode, m_fgeoidSep, m_lfileOrder, m_lnameOrder, m_referenceFrame, m_strHemisphereZone, m_unusedStation, m_zone, stn_t::meridianDef, stn_t::nameOrder, SetConstraints(), SetCoordType(), SetDescription(), SetName(), SetOriginalName(), stn_t::stationConst, stn_t::stationName, stn_t::stationNameOrig, stn_t::stationType, stn_t::suppliedStationType, stn_t::unusedStation, UTM_type_i, VALID_STATION, stn_t::verticalDef, XYZ_type_i, and stn_t::zone.
Referenced by SetHeightSystem().
SetXAxis()
void dynadjust::measurements::CDnaStation::SetXAxis (const std::string & str)
Definition at line 310 of file dnastation.cpp.
{
    switch (m_ctType)
    {
    case LLH_type_i:
    case LLh_type_i:
        FromDmsString(&m_dXAxis, trimstr(str));
        m_dXAxis = Radians(m_dXAxis);
        break;
    default:
        // All other types will be converted by dna_import::ReduceStations_LLH()
        DoubleFromString(m_dXAxis, trimstr(str));
    }
}
References DoubleFromString(), FromDmsString(), LLH_type_i, LLh_type_i, m_ctType, m_dXAxis, Radians(), and trimstr().
Referenced by SetHeightSystem().
SetYAxis()
void dynadjust::measurements::CDnaStation::SetYAxis (const std::string & str)
Definition at line 327 of file dnastation.cpp.
{
    switch (m_ctType)
    {
    case LLH_type_i:
    case LLh_type_i:
        FromDmsString(&m_dYAxis, trimstr(str));
        m_dYAxis = Radians(m_dYAxis);
        break;
    default:
        DoubleFromString(m_dYAxis, trimstr(str));
    }
}
References DoubleFromString(), FromDmsString(), LLH_type_i, LLh_type_i, m_ctType, m_dYAxis, Radians(), and trimstr().
Referenced by SetHeightSystem().
SetZAxis()
void dynadjust::measurements::CDnaStation::SetZAxis (const std::string & str)
Definition at line 343 of file dnastation.cpp.
{
    DoubleFromString(m_dZAxis, trimstr(str));
}
References DoubleFromString(), m_dZAxis, and trimstr().
Referenced by SetHeight(), and SetHeightSystem().
SetHeight()
void dynadjust::measurements::CDnaStation::SetHeight (const std::string & str)
Definition at line 350 of file dnastation.cpp.
{
    if (GetMyCoordTypeC() == XYZ_type_i)
        SetZAxis(str);
    else
        DoubleFromString(m_dHeight, trimstr(str));
}
References DoubleFromString(), GetMyCoordTypeC(), m_dHeight, SetZAxis(), trimstr(), and XYZ_type_i.
Referenced by SetHeightSystem().
SetCoordType()
void dynadjust::measurements::CDnaStation::SetCoordType (const std::string & sType)
Definition at line 304 of file dnastation.cpp.
{
    m_strType = trimstr(sType);
    m_ctTypeSupplied = m_ctType = GetMyCoordTypeC();
}
References GetMyCoordTypeC(), m_ctType, m_ctTypeSupplied, m_strType, and trimstr().
Referenced by CDnaStation(), SetHeightSystem(), and SetStationRec().
ReduceStations_LLH()
void dynadjust::measurements::CDnaStation::ReduceStations_LLH (const CDnaEllipsoid * m_eEllipsoid, const CDnaProjection * m_pProjection)
Definition at line 373 of file dnastation.cpp.
{
    switch (m_ctType)
    {
    case XYZ_type_i:
        // Convert from cartesian to geographic (radians)
        CartToGeo<double>(m_dXAxis, m_dYAxis, m_dZAxis, &m_dXAxis, &m_dYAxis, &m_dHeight, m_eEllipsoid);
        m_dZAxis= 0.;
        m_htType = ELLIPSOIDAL_type_i;
        // Force the current type to be geographic (ellipsoid height).
        // The user-supplied type is retained in m_ctTypeSupplied
        m_ctType = LLh_type_i;
        m_strType = LLh_type;
        break;
    case UTM_type_i:
        // Convert from projection to geographic (radians)
        GridToGeo<double, UINT32>(m_dXAxis, m_dYAxis, m_zone, &m_dXAxis, &m_dYAxis,
            m_eEllipsoid->GetSemiMajor(), m_eEllipsoid->GetInverseFlattening(),     // ellipsoid parameters
            m_pProjection->GetFalseEasting(), m_pProjection->GetFalseNorthing(), // projection parameters
            m_pProjection->GetCentralScaleFactor(), m_pProjection->GetLongCentralMeridianZone1(),
            m_pProjection->GetZoneWidth());
        // Force the current type to be geographic (orthometric height).
        // The user-supplied type is retained in m_ctTypeSupplied
        m_ctType = LLH_type_i;
        m_strType = LLH_type;
        break;
    default:
        break;
    }
}
References CartToGeo(), ELLIPSOIDAL_type_i, dynadjust::datum_parameters::CDnaProjection::GetCentralScaleFactor(), dynadjust::datum_parameters::CDnaProjection::GetFalseEasting(), dynadjust::datum_parameters::CDnaProjection::GetFalseNorthing(), dynadjust::datum_parameters::CDnaEllipsoid::GetInverseFlattening(), dynadjust::datum_parameters::CDnaProjection::GetLongCentralMeridianZone1(), dynadjust::datum_parameters::CDnaEllipsoid::GetSemiMajor(), dynadjust::datum_parameters::CDnaProjection::GetZoneWidth(), GridToGeo(), LLH_type(), LLh_type(), LLH_type_i, LLh_type_i, m_ctType, m_dHeight, m_dXAxis, m_dYAxis, m_dZAxis, m_htType, m_strType, m_zone, UTM_type_i, and XYZ_type_i.
Referenced by SetHeightSystem().
ReduceStations_XYZ()
void dynadjust::measurements::CDnaStation::ReduceStations_XYZ (const CDnaEllipsoid * m_eEllipsoid, const CDnaProjection * m_pProjection)
Definition at line 409 of file dnastation.cpp.
{
    switch (m_ctType)
    {
    case UTM_type_i:
        // Convert from projection to geographic (radians)
        GridToGeo<double, UINT32>(m_dXAxis, m_dYAxis, m_zone, &m_dXAxis, &m_dYAxis,
            m_eEllipsoid->GetSemiMajor(), m_eEllipsoid->GetInverseFlattening(), // ellipsoid parameters
            m_pProjection->GetFalseEasting(), m_pProjection->GetFalseNorthing(), // projection parameters
            m_pProjection->GetCentralScaleFactor(), m_pProjection->GetLongCentralMeridianZone1(),
            m_pProjection->GetZoneWidth());
        [[fallthrough]];
    case LLH_type_i:
    case LLh_type_i:
        m_dcurrentLatitude = m_dXAxis;
        m_dcurrentLongitude = m_dYAxis;
        m_dcurrentHeight = m_dHeight;
        if (m_ctType == LLH_type_i)
            m_dcurrentHeight += m_fgeoidSep;
        // Convert from geographic (radians) to cartesian
        // Assumes height is ellipsoidal
        GeoToCart<double>(m_dcurrentLatitude, m_dcurrentLongitude, m_dcurrentHeight, &m_dXAxis, &m_dYAxis, &m_dZAxis, m_eEllipsoid);
        break;
    default:
        break;
    }
    // Force the current type to be geographic.  The user-supplied type is retained in m_ctTypeSupplied
    m_ctType = XYZ_type_i;
    m_strType = XYZ_type;
}
References GeoToCart(), dynadjust::datum_parameters::CDnaProjection::GetCentralScaleFactor(), dynadjust::datum_parameters::CDnaProjection::GetFalseEasting(), dynadjust::datum_parameters::CDnaProjection::GetFalseNorthing(), dynadjust::datum_parameters::CDnaEllipsoid::GetInverseFlattening(), dynadjust::datum_parameters::CDnaProjection::GetLongCentralMeridianZone1(), dynadjust::datum_parameters::CDnaEllipsoid::GetSemiMajor(), dynadjust::datum_parameters::CDnaProjection::GetZoneWidth(), GridToGeo(), LLH_type_i, LLh_type_i, m_ctType, m_dcurrentHeight, m_dcurrentLatitude, m_dcurrentLongitude, m_dHeight, m_dXAxis, m_dYAxis, m_dZAxis, m_fgeoidSep, m_strType, m_zone, UTM_type_i, XYZ_type(), and XYZ_type_i.
Referenced by SetHeightSystem().
SetXAxis_d()
void dynadjust::measurements::CDnaStation::SetXAxis_d (const double & dXAxis) inline
Definition at line 227 of file dnastation.hpp.
{ m_dXAxis = dXAxis; }
References m_dXAxis.
SetYAxis_d()
void dynadjust::measurements::CDnaStation::SetYAxis_d (const double & dYAxis) inline
Definition at line 228 of file dnastation.hpp.
{ m_dYAxis = dYAxis; }
References m_dYAxis.
SetZAxis_d()
void dynadjust::measurements::CDnaStation::SetZAxis_d (const double & dZAxis) inline
Definition at line 229 of file dnastation.hpp.
{ m_dZAxis = dZAxis; }
References m_dZAxis.
SetXAxisStdDev_d()
void dynadjust::measurements::CDnaStation::SetXAxisStdDev_d (const double & dXAxisStdDev) inline
Definition at line 230 of file dnastation.hpp.
{ m_dStdDevX = dXAxisStdDev; }
References m_dStdDevX.
SetYAxisStdDev_d()
void dynadjust::measurements::CDnaStation::SetYAxisStdDev_d (const double & dYAxisStdDev) inline
Definition at line 231 of file dnastation.hpp.
{ m_dStdDevY = dYAxisStdDev; }
References m_dStdDevY.
SetZAxisStdDev_d()
void dynadjust::measurements::CDnaStation::SetZAxisStdDev_d (const double & dZAxisStdDev) inline
Definition at line 232 of file dnastation.hpp.
{ m_dStdDevZ = dZAxisStdDev; }
References m_dStdDevZ.
SetHeight_d()
void dynadjust::measurements::CDnaStation::SetHeight_d (const double & dHeight) inline
Definition at line 233 of file dnastation.hpp.
{ m_dHeight = dHeight; }
References m_dHeight.
SetcurrentHeight_d()
void dynadjust::measurements::CDnaStation::SetcurrentHeight_d (const double & dHeight) inline
Definition at line 234 of file dnastation.hpp.
{ m_dcurrentHeight = dHeight; }
References m_dcurrentHeight.
SetName()
void dynadjust::measurements::CDnaStation::SetName (const std::string & sName) inline
Definition at line 236 of file dnastation.hpp.
{ m_strName = trimstr(sName); }
References m_strName, and trimstr().
Referenced by SetStationRec().
SetOriginalName() [1/2]
void dynadjust::measurements::CDnaStation::SetOriginalName (const std::string & sName) inline
Definition at line 237 of file dnastation.hpp.
{ m_strOriginalName = trimstr(sName); }
References m_strOriginalName, and trimstr().
SetOriginalName() [2/2]
void dynadjust::measurements::CDnaStation::SetOriginalName () inline
Definition at line 238 of file dnastation.hpp.
{ m_strOriginalName = m_strName; }
References m_strName, and m_strOriginalName.
Referenced by SetStationRec().
SetHemisphereZone()
void dynadjust::measurements::CDnaStation::SetHemisphereZone (const std::string & sHemisphereZone)
Definition at line 359 of file dnastation.cpp.
{
    m_strHemisphereZone = trimstr(sHemisphereZone);
    if (m_strHemisphereZone.empty())
        return;
    if (isdigit(m_strHemisphereZone.substr(0).c_str()[0]))                   // is the first character a decimal digit?
        m_zone = LongFromString<UINT32>(m_strHemisphereZone.substr(0));      // extract zone from first position
    else
        m_zone = LongFromString<UINT32>(m_strHemisphereZone.substr(1));      // extract zone after hemisphere
}
References LongFromString(), m_strHemisphereZone, m_zone, and trimstr().
Referenced by CDnaStation().
SetDescription()
void dynadjust::measurements::CDnaStation::SetDescription (const std::string & sDescription) inline
Definition at line 240 of file dnastation.hpp.
{ m_strDescription = trimstr(sDescription); }
References m_strDescription, and trimstr().
Referenced by SetStationRec().
SetComment()
void dynadjust::measurements::CDnaStation::SetComment (const std::string & sComment) inline
Definition at line 241 of file dnastation.hpp.
{ m_strComment = trimstr(sComment); }
References m_strComment, and trimstr().
SetfileOrder()
void dynadjust::measurements::CDnaStation::SetfileOrder (const UINT32 & order) inline
Definition at line 243 of file dnastation.hpp.
{ m_lfileOrder = order; }
References m_lfileOrder.
SetnameOrder()
void dynadjust::measurements::CDnaStation::SetnameOrder (const UINT32 & order) inline
Definition at line 244 of file dnastation.hpp.
{ m_lnameOrder = order; }
References m_lnameOrder.
SetgeoidSep()
void dynadjust::measurements::CDnaStation::SetgeoidSep (const float & fgeoidSep) inline
Definition at line 246 of file dnastation.hpp.
{ m_fgeoidSep = fgeoidSep; }
References m_fgeoidSep.
SetmeridianDef()
void dynadjust::measurements::CDnaStation::SetmeridianDef (const double & dmeridianDef) inline
Definition at line 247 of file dnastation.hpp.
{ m_dmeridianDef = dmeridianDef; }
References m_dmeridianDef.
SetverticalDef()
void dynadjust::measurements::CDnaStation::SetverticalDef (const double & dverticalDef) inline
Definition at line 248 of file dnastation.hpp.
{ m_dverticalDef = dverticalDef; }
References m_dverticalDef.
SetStationUnused()
void dynadjust::measurements::CDnaStation::SetStationUnused () inline
Definition at line 250 of file dnastation.hpp.
{ m_unusedStation = true; }
References m_unusedStation.
SetStationUse()
void dynadjust::measurements::CDnaStation::SetStationUse (bool use) inline
Definition at line 251 of file dnastation.hpp.
{ m_unusedStation = use; }
References m_unusedStation.
SetConstraints()
void dynadjust::measurements::CDnaStation::SetConstraints (const std::string & str)
Definition at line 266 of file dnastation.cpp.
{
    // capture string, trim whitespace
    m_strConstraints = trimstr(sConstraints);
    // No string provided?  Fill with FFF
    if (sConstraints.empty())
        m_strConstraints = "FFF";
    // Greater than 3 characters?  Trim to 3 characters
    if (m_strConstraints.length() > 3)
        m_strConstraints = m_strConstraints.substr(0, 3);
    // Less than 3 characters?  Pad with 'F'
    if (m_strConstraints.length() < 3)
        m_strConstraints.append(size_t(3 - m_strConstraints.length()), 'F');
    m_cLatConstraint = (char)(*m_strConstraints.substr(0, 1).c_str());
    m_cLonConstraint = (char)(*m_strConstraints.substr(1, 1).c_str());
    m_cHtConstraint = (char)(*m_strConstraints.substr(2, 1).c_str());
    // Free in all 3 dimensions
    if (boost::iequals(m_strConstraints, "FFF"))
        m_constraintType = free_3D;
    // Constrained in all 3 dimensions
    else if (boost::iequals(m_strConstraints, "CCC"))
        m_constraintType = constrained_3D;
    // Horizontal or 2D adjustment
    else if (boost::iequals(m_strConstraints, "FFC"))
        m_constraintType = free_2D;
    // Vertical or 1D adjustment
    else if (boost::iequals(m_strConstraints, "CCF"))
        m_constraintType = free_1D;
    else
        m_constraintType = custom_constraint;
}
References constrained_3D, custom_constraint, free_1D, free_2D, free_3D, m_cHtConstraint, m_cLatConstraint, m_cLonConstraint, m_constraintType, m_strConstraints, and trimstr().
Referenced by CDnaStation(), and SetStationRec().
SetXAxisStdDev()
void dynadjust::measurements::CDnaStation::SetXAxisStdDev (const std::string & str)
SetYAxisStdDev()
void dynadjust::measurements::CDnaStation::SetYAxisStdDev (const std::string & str)
SetHeightStdDev()
void dynadjust::measurements::CDnaStation::SetHeightStdDev (const std::string & str)
PrepareStnData()
void dynadjust::measurements::CDnaStation::PrepareStnData (double & lat_east_x, double & lon_north_y, double & ht_zone_z, std::string & hemisphereZone, std::string & coordinateType, UINT32 & LEX_precision, UINT32 & LNY_precision, UINT32 & HZ_precision, const CDnaEllipsoid * ellipsoid, const CDnaProjection * projection, bool writeCurrentEstimates)
References CoordinateName(), WriteBinaryStn(), WriteDNAStn(), WriteDNAXMLStn(), WriteDNAXMLStnCurrentEstimates(), WriteDNAXMLStnInitialEstimates(), WriteDynaMLStn(), and WriteGeoidfile().
WriteBinaryStn()
void dynadjust::measurements::CDnaStation::WriteBinaryStn (std::ofstream * binary_stream, const UINT16 bUnused = 0)
Definition at line 625 of file dnastation.cpp.
{
    station_t stationRecord;
    strcpy(stationRecord.stationName, m_strName.substr(0, STN_NAME_WIDTH).c_str());
    strcpy(stationRecord.stationNameOrig, m_strOriginalName.substr(0, STN_NAME_WIDTH).c_str());
    strcpy(stationRecord.stationConst, m_strConstraints.substr(0, STN_CONST_WIDTH).c_str());
    strcpy(stationRecord.stationType, m_strType.substr(0, STN_TYPE_WIDTH).c_str());
    stationRecord.suppliedStationType = m_ctTypeSupplied;
    switch (m_ctTypeSupplied)
    {
    case LLH_type_i:
    case UTM_type_i:
        stationRecord.suppliedHeightRefFrame = ORTHOMETRIC_type_i;
        break;
    default:
        break;
    }
    stationRecord.initialLatitude = m_dXAxis;
    if (fabs(m_dcurrentLatitude - 0.) < PRECISION_1E15)
        stationRecord.currentLatitude = m_dXAxis;
    else
        stationRecord.currentLatitude = m_dcurrentLatitude;
    stationRecord.initialLongitude = m_dYAxis;
    if (fabs(m_dcurrentLongitude - 0.) < PRECISION_1E15)
        stationRecord.currentLongitude = m_dYAxis;
    else
        stationRecord.currentLongitude = m_dcurrentLongitude;
    stationRecord.initialHeight = m_dHeight;
    if (fabs(m_dcurrentHeight - 0.) < PRECISION_1E15)
        stationRecord.currentHeight = m_dHeight;
    else
        stationRecord.currentHeight = m_dcurrentHeight;
    stationRecord.geoidSep = m_fgeoidSep;
    stationRecord.meridianDef = m_dmeridianDef;
    stationRecord.verticalDef = m_dverticalDef;
    stationRecord.zone = m_zone;
    strcpy(stationRecord.description, m_strDescription.substr(0, STN_DESC_WIDTH).c_str());
    stationRecord.fileOrder = m_lfileOrder;
    stationRecord.nameOrder = m_lnameOrder;
    stationRecord.unusedStation = bUnused;
    strcpy(stationRecord.epoch, m_epoch.substr(0, STN_EPOCH_WIDTH).c_str());
    strcpy(stationRecord.epsgCode, m_epsgCode.substr(0, STN_EPSG_WIDTH).c_str());
    binary_stream->write(reinterpret_cast<char *>(&stationRecord), sizeof(station_t));
}
References stn_t::currentHeight, stn_t::currentLatitude, stn_t::currentLongitude, stn_t::description, stn_t::epoch, stn_t::epsgCode, stn_t::fileOrder, stn_t::geoidSep, stn_t::initialHeight, stn_t::initialLatitude, stn_t::initialLongitude, LLH_type_i, m_ctTypeSupplied, m_dcurrentHeight, m_dcurrentLatitude, m_dcurrentLongitude, m_dHeight, m_dmeridianDef, m_dverticalDef, m_dXAxis, m_dYAxis, m_epoch, m_epsgCode, m_fgeoidSep, m_lfileOrder, m_lnameOrder, m_strConstraints, m_strDescription, m_strName, m_strOriginalName, m_strType, m_zone, stn_t::meridianDef, stn_t::nameOrder, ORTHOMETRIC_type_i, PRECISION_1E15(), stn_t::stationConst, stn_t::stationName, stn_t::stationNameOrig, stn_t::stationType, STN_CONST_WIDTH(), STN_DESC_WIDTH(), STN_EPOCH_WIDTH(), STN_EPSG_WIDTH(), STN_NAME_WIDTH(), STN_TYPE_WIDTH(), stn_t::suppliedHeightRefFrame, stn_t::suppliedStationType, stn_t::unusedStation, UTM_type_i, stn_t::verticalDef, and stn_t::zone.
Referenced by PrepareStnData().
WriteDNAXMLStnCurrentEstimates()
void dynadjust::measurements::CDnaStation::WriteDNAXMLStnCurrentEstimates (std::ofstream * dna_ofstream, const CDnaEllipsoid * ellipsoid, const CDnaProjection * projection, INPUT_FILE_TYPE t, const dna_stn_fields * dsw = 0)
Definition at line 679 of file dnastation.cpp.
{
    // Get the latest estimates
    double lat_east_x(m_dcurrentLatitude);
    double lon_north_y(m_dcurrentLongitude);
    double ht_zone_z(m_dcurrentHeight);
    // Write latest station estimates
    WriteDNAXMLStn(dna_ofstream,
        ellipsoid, projection,
        lat_east_x, lon_north_y, ht_zone_z,
        t, dsw);
}
References m_dcurrentHeight, m_dcurrentLatitude, m_dcurrentLongitude, and WriteDNAXMLStn().
Referenced by PrepareStnData().
WriteDNAXMLStnInitialEstimates()
void dynadjust::measurements::CDnaStation::WriteDNAXMLStnInitialEstimates (std::ofstream * dna_ofstream, const CDnaEllipsoid * ellipsoid, const CDnaProjection * projection, INPUT_FILE_TYPE t, const dna_stn_fields * dsw = 0)
Definition at line 696 of file dnastation.cpp.
{
    // Write initial station estimates
    WriteDNAXMLStn(dna_ofstream,
        ellipsoid, projection,
        m_dXAxis, m_dYAxis, m_dHeight,
        t, dsw);
}
References m_dHeight, m_dXAxis, m_dYAxis, and WriteDNAXMLStn().
Referenced by PrepareStnData().
WriteDNAXMLStn()
void dynadjust::measurements::CDnaStation::WriteDNAXMLStn (std::ofstream * dna_ofstream, const CDnaEllipsoid * ellipsoid, const CDnaProjection * projection, const double & lat_east_x, const double & lon_north_y, const double & ht_zone_z, INPUT_FILE_TYPE t, const dna_stn_fields * dsw = 0)
Definition at line 708 of file dnastation.cpp.
{
    //m_ctTypeSupplied = LLh_type_i;
    std::string hemisphereZone(m_strHemisphereZone);
    std::string coordinateType(LLH_type);
    switch (m_ctTypeSupplied)
    {
    case XYZ_type_i:
        coordinateType = XYZ_type;
        break;
    case LLh_type_i:
        coordinateType = LLh_type;
        break;
    case UTM_type_i:
        coordinateType = UTM_type;
        break;
    case ENU_type_i:  // Not supported yet, so revert to Lat, Long, Height
        coordinateType = LLH_type;
        m_ctTypeSupplied = LLH_type_i;
        break;
    case LLH_type_i:
        coordinateType = LLH_type;
        break;
    default:
        break;
    }
    // Convert height to orthometric?
    // Decisions for printing (estimated) station height for various input coordinate types
    // and geoid model.  Estimated stations are in LLh.
    // h = H + Na
    //
    // Input Coord type     Geoid loaded?          Geoid not loaded?          Result
    // ---------------------------------------------------------------------------------
    // LLH                  ht_z - m_fgeoidSep     ht_z (m_fgeoidSep = 0)     H (orthometric)
    // UTM                  ht_z - m_fgeoidSep     ht_z (m_fgeoidSep = 0)     H (orthometric)
    // ENU                  ht_z - m_fgeoidSep     ht_z (m_fgeoidSep = 0)     H (orthometric)
    // LLh                  ht_z                   ht_z                       h (ellipsoid)
    // XYZ                  LLh->XYZ               LLh->XYZ                   X, Y, Z
    double lat_east_x_mod(lat_east_x);
    double lon_north_y_mod(lon_north_y);
    double ht_zone_z_mod(ht_zone_z);
    switch (m_ctTypeSupplied)
    {
    case LLH_type_i:
    case UTM_type_i:
        // reduce to orthometric.
        // If geoid hasn't been loaded, m_fgeoidSep will be 0.0
        ht_zone_z_mod -= m_fgeoidSep;
        break;
    default:
        break;
    }
    // Convert coordinates to cartesian or utm?
    // Convert radians values to degrees, minutes and seconds?
    std::stringstream ss;
    double zone;
    switch (m_ctTypeSupplied)
    {
    case XYZ_type_i:
        GeoToCart<double>(lat_east_x, lon_north_y, ht_zone_z,
            &lat_east_x_mod, &lon_north_y_mod, &ht_zone_z_mod, ellipsoid);
        break;
    case UTM_type_i:
        GeoToGrid<double>(lat_east_x, lon_north_y,
            &lat_east_x_mod, &lon_north_y_mod, &zone, ellipsoid, projection, true);
        ss << std::fixed << std::setprecision(0) << zone;
        hemisphereZone = ss.str();
        break;
    case LLh_type_i:
    case LLH_type_i:
        lat_east_x_mod = RadtoDms(lat_east_x);
        lon_north_y_mod = RadtoDmsL(lon_north_y);
        break;
    default:
        break;
    }
    switch (t)
    {
    case dna:
        // Write DNA station file
        WriteDNAStn(dna_ofstream, coordinateType,
            lat_east_x_mod, lon_north_y_mod, ht_zone_z_mod,
            hemisphereZone, *dsw);
        break;
    case dynaml:
        // Write DynAdjust XML station file
        WriteDynaMLStn(dna_ofstream, coordinateType,
            lat_east_x_mod, lon_north_y_mod, ht_zone_z_mod,
            hemisphereZone);
        break;
    default:
        break;
    }
}
References dna, dynaml, ENU_type_i, GeoToCart(), GeoToGrid(), LLH_type(), LLh_type(), LLH_type_i, LLh_type_i, m_ctTypeSupplied, m_fgeoidSep, m_strHemisphereZone, RadtoDms(), RadtoDmsL(), UTM_type(), UTM_type_i, WriteDNAStn(), WriteDynaMLStn(), XYZ_type(), and XYZ_type_i.
Referenced by PrepareStnData(), WriteDNAXMLStnCurrentEstimates(), and WriteDNAXMLStnInitialEstimates().
WriteDNAStn()
void dynadjust::measurements::CDnaStation::WriteDNAStn (std::ofstream * dna_ofstream, const std::string & coordinateType, const double & lat_east_x, const double & lon_north_y, const double & ht_zone_z, std::string & hemisphereZone, const dna_stn_fields & dsw)
Definition at line 818 of file dnastation.cpp.
{
    UINT32 LEX_precision(4), LNY_precision(4), HZ_precision(4);
    switch (m_ctTypeSupplied)
    {
    case LLh_type_i:
    case LLH_type_i:
        LEX_precision = LNY_precision = 10;
        break;
    default:
        break;
    }
    (*dna_ofstream) << std::left << std::setw(dsw.stn_name) << m_strName;
    (*dna_ofstream) << std::left << std::setw(dsw.stn_const) << m_strConstraints;
    (*dna_ofstream) << " ";
    (*dna_ofstream) << std::left << std::setw(dsw.stn_type) << coordinateType;
    (*dna_ofstream) << std::right << std::setw(dsw.stn_e_phi_x) << std::setprecision(LEX_precision) << std::fixed << lat_east_x;
    (*dna_ofstream) << std::right << std::setw(dsw.stn_n_lam_y) << std::setprecision(LNY_precision) << std::fixed << lon_north_y;
    (*dna_ofstream) << std::right << std::setw(dsw.stn_ht_z) << std::setprecision(HZ_precision) << std::fixed << ht_zone_z;
    if (m_ctTypeSupplied == UTM_type_i)
        (*dna_ofstream) << std::right << std::setw(dsw.stn_hemi_zo) << hemisphereZone;
    else
        (*dna_ofstream) << std::right << std::setw(dsw.stn_hemi_zo) << " ";
    (*dna_ofstream) << " ";
    (*dna_ofstream) << std::left << m_strDescription << std::endl;
}
References LLH_type_i, LLh_type_i, m_ctTypeSupplied, m_strConstraints, m_strDescription, m_strName, dna_stn_fields::stn_const, dna_stn_fields::stn_e_phi_x, dna_stn_fields::stn_hemi_zo, dna_stn_fields::stn_ht_z, dna_stn_fields::stn_n_lam_y, dna_stn_fields::stn_name, dna_stn_fields::stn_type, and UTM_type_i.
Referenced by PrepareStnData(), and WriteDNAXMLStn().
WriteDynaMLStn()
void dynadjust::measurements::CDnaStation::WriteDynaMLStn (std::ofstream * xml_ofstream, const std::string & coordinateType, const double & lat_east_x, const double & lon_north_y, const double & ht_zone_z, std::string & hemisphereZone)
Definition at line 850 of file dnastation.cpp.
{
    UINT32 LEX_precision(4), LNY_precision(4), HZ_precision(4);
    // Convert radians values to degrees, minutes and seconds
    switch (m_ctTypeSupplied)
    {
    case LLh_type_i:
    case LLH_type_i:
        LEX_precision = LNY_precision = 10;
        break;
    default:
        break;
    }
    (*xml_ofstream) << "  <DnaStation>" << std::endl;
    (*xml_ofstream) << "    <Name>" << m_strName << "</Name>" << std::endl;
    (*xml_ofstream) << "    <Constraints>" << m_strConstraints << "</Constraints>" << std::endl;
    (*xml_ofstream) << "    <Type>" << coordinateType << "</Type>" << std::endl;
    (*xml_ofstream) << "    <StationCoord>" << std::endl;
    (*xml_ofstream) << "      <Name>" << m_strName << "</Name>" << std::endl;
    (*xml_ofstream) << "      <XAxis>" << std::setprecision(LEX_precision) << std::fixed << lat_east_x << "</XAxis>" << std::endl;
    (*xml_ofstream) << "      <YAxis>" << std::setprecision(LNY_precision) << std::fixed << lon_north_y << "</YAxis>" << std::endl;
    (*xml_ofstream) << "      <Height>" << std::setprecision(HZ_precision) << std::fixed << ht_zone_z << "</Height>" << std::endl;
    // Convert radians values to degrees, minutes and seconds
    if (m_ctTypeSupplied == UTM_type_i)
        (*xml_ofstream) << "      <HemisphereZone>" << hemisphereZone << "</HemisphereZone>" << std::endl;
    (*xml_ofstream) << "    </StationCoord>" << std::endl;
    (*xml_ofstream) << "    <Description>"  << m_strDescription << "</Description>" << std::endl;
    (*xml_ofstream) << "  </DnaStation>" << std::endl;
}
References LLH_type_i, LLh_type_i, m_ctTypeSupplied, m_strConstraints, m_strDescription, m_strName, and UTM_type_i.
Referenced by PrepareStnData(), and WriteDNAXMLStn().
WriteGeoidfile()
void dynadjust::measurements::CDnaStation::WriteGeoidfile (std::ofstream * binary_stream)
Definition at line 887 of file dnastation.cpp.
{
    (*geo_ofstream) << std::setw(44) << std::left << m_strName <<
        std::setw(15) << std::setprecision(3) << std::fixed << std::left << m_fgeoidSep <<
        std::setw(10) << std::setprecision(3) << std::fixed << std::right << m_dmeridianDef <<
        std::setw(10) << std::setprecision(3) << std::fixed << std::right << m_dverticalDef << std::endl;
}
References m_dmeridianDef, m_dverticalDef, m_fgeoidSep, and m_strName.
Referenced by PrepareStnData().
CoordinateName()
std::string dynadjust::measurements::CDnaStation::CoordinateName (const char & c) static
Definition at line 950 of file dnastation.cpp.
{
    switch (c)
    {
    case 'P':
        return "Latitude";
    case 'L':
        return "Longitude";
    case 'H':
        return "H(Ortho)";
    case 'h':
        return "h(Ellipse)";
    case 'E':
        return "Easting";
    case 'N':
        return "Northing";
    case 'z':
        return "Zone";
    case 'X':
        return "X";
    case 'Y':
        return "Y";
    case 'Z':
        return "Z";
    }
    return "";
}
Referenced by PrepareStnData(), dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), and dynadjust::networkadjust::dna_adjust::PrintPosUncertaintiesHeader().
GetReferenceFrame()
std::string dynadjust::measurements::CDnaStation::GetReferenceFrame () const inline
Definition at line 292 of file dnastation.hpp.
{ return m_referenceFrame; }
References m_referenceFrame.
GetEpoch()
std::string dynadjust::measurements::CDnaStation::GetEpoch () const inline
Definition at line 293 of file dnastation.hpp.
{ return m_epoch; }
References m_epoch.
SetReferenceFrame()
void dynadjust::measurements::CDnaStation::SetReferenceFrame (const std::string & r) inline
Definition at line 295 of file dnastation.hpp.
{ m_referenceFrame = trimstr(r); }
References m_referenceFrame, and trimstr().
SetEpoch()
void dynadjust::measurements::CDnaStation::SetEpoch (const std::string & e) inline
Definition at line 296 of file dnastation.hpp.
{ m_epoch = trimstr(e); }
References m_epoch, and trimstr().
SetEpsg()
void dynadjust::measurements::CDnaStation::SetEpsg (const std::string & e) inline
Definition at line 297 of file dnastation.hpp.
{ m_epsgCode = trimstr(e); }
References m_epsgCode, and trimstr().
Friends And Related Symbol Documentation
operator< [1/2]
bool operator< (const CDnaStation & left, const CDnaStation & right) friend
Definition at line 36 of file dnastation.cpp.
{
    return left.m_strName < right.m_strName;
}
References CDnaStation(), and m_strName.
operator< [2/2]
bool operator< (const boost::shared_ptr< CDnaStation > & left, const boost::shared_ptr< CDnaStation > & right) friend
Definition at line 41 of file dnastation.cpp.
{
    return left.get()->m_strName < right.get()->m_strName;
}
Member Data Documentation
m_strName
std::string dynadjust::measurements::CDnaStation::m_strName
Definition at line 299 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), CompareStationName(), GetName(), operator<, operator=(), SetName(), SetOriginalName(), WriteBinaryStn(), WriteDNAStn(), WriteDynaMLStn(), and WriteGeoidfile().
m_strOriginalName
std::string dynadjust::measurements::CDnaStation::m_strOriginalName protected
Definition at line 303 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetOriginalName(), SetOriginalName(), SetOriginalName(), and WriteBinaryStn().
m_dXAxis
double dynadjust::measurements::CDnaStation::m_dXAxis protected
Definition at line 305 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetEasting(), GetLatitude(), GetXAxis(), operator=(), ReduceStations_LLH(), ReduceStations_XYZ(), SetStationRec(), SetXAxis(), SetXAxis_d(), WriteBinaryStn(), and WriteDNAXMLStnInitialEstimates().
m_dYAxis
double dynadjust::measurements::CDnaStation::m_dYAxis protected
Definition at line 306 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetLongitude(), GetNorthing(), GetYAxis(), operator=(), ReduceStations_LLH(), ReduceStations_XYZ(), SetStationRec(), SetYAxis(), SetYAxis_d(), WriteBinaryStn(), and WriteDNAXMLStnInitialEstimates().
m_dZAxis
double dynadjust::measurements::CDnaStation::m_dZAxis protected
Definition at line 307 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetZAxis(), operator=(), ReduceStations_LLH(), ReduceStations_XYZ(), SetZAxis(), and SetZAxis_d().
m_dHeight
double dynadjust::measurements::CDnaStation::m_dHeight protected
Definition at line 308 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetHeight(), operator=(), ReduceStations_LLH(), ReduceStations_XYZ(), SetHeight(), SetHeight_d(), SetStationRec(), WriteBinaryStn(), and WriteDNAXMLStnInitialEstimates().
m_dStdDevX
double dynadjust::measurements::CDnaStation::m_dStdDevX protected
Definition at line 310 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), operator=(), and SetXAxisStdDev_d().
m_dStdDevY
double dynadjust::measurements::CDnaStation::m_dStdDevY protected
Definition at line 311 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), operator=(), and SetYAxisStdDev_d().
m_dStdDevZ
double dynadjust::measurements::CDnaStation::m_dStdDevZ protected
Definition at line 312 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), and SetZAxisStdDev_d().
m_dStdDevHt
double dynadjust::measurements::CDnaStation::m_dStdDevHt protected
Definition at line 313 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), and operator=().
m_strConstraints
std::string dynadjust::measurements::CDnaStation::m_strConstraints protected
Definition at line 315 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), GetConstraints(), operator=(), SetConstraints(), WriteBinaryStn(), WriteDNAStn(), and WriteDynaMLStn().
m_strType
std::string dynadjust::measurements::CDnaStation::m_strType protected
Definition at line 316 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), GetCoordType(), GetMyCoordTypeC(), GetMyHeightSystemC(), operator=(), ReduceStations_LLH(), ReduceStations_XYZ(), SetCoordType(), and WriteBinaryStn().
m_strHemisphereZone
std::string dynadjust::measurements::CDnaStation::m_strHemisphereZone protected
Definition at line 317 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), GetHemisphereZone(), operator=(), SetHemisphereZone(), SetStationRec(), and WriteDNAXMLStn().
m_strDescription
std::string dynadjust::measurements::CDnaStation::m_strDescription protected
Definition at line 318 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetDescription(), operator=(), SetDescription(), WriteBinaryStn(), WriteDNAStn(), and WriteDynaMLStn().
m_strComment
std::string dynadjust::measurements::CDnaStation::m_strComment protected
Definition at line 319 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetComment(), operator=(), and SetComment().
m_cLatConstraint
char dynadjust::measurements::CDnaStation::m_cLatConstraint protected
Definition at line 321 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), operator=(), and SetConstraints().
m_cLonConstraint
char dynadjust::measurements::CDnaStation::m_cLonConstraint protected
Definition at line 322 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), operator=(), and SetConstraints().
m_cHtConstraint
char dynadjust::measurements::CDnaStation::m_cHtConstraint protected
Definition at line 323 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), operator=(), and SetConstraints().
m_ctType
COORD_TYPE dynadjust::measurements::CDnaStation::m_ctType protected
Definition at line 325 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), operator=(), ReduceStations_LLH(), ReduceStations_XYZ(), SetCoordType(), SetXAxis(), and SetYAxis().
m_ctTypeSupplied
COORD_TYPE dynadjust::measurements::CDnaStation::m_ctTypeSupplied protected
Definition at line 326 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), operator=(), SetCoordType(), SetStationRec(), WriteBinaryStn(), WriteDNAStn(), WriteDNAXMLStn(), and WriteDynaMLStn().
m_htType
HEIGHT_SYSTEM dynadjust::measurements::CDnaStation::m_htType protected
Definition at line 327 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), GetMyHeightSystem(), operator=(), and ReduceStations_LLH().
m_dcurrentLatitude
double dynadjust::measurements::CDnaStation::m_dcurrentLatitude protected
Definition at line 329 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetcurrentLatitude(), operator=(), ReduceStations_XYZ(), SetStationRec(), WriteBinaryStn(), and WriteDNAXMLStnCurrentEstimates().
m_dcurrentLongitude
double dynadjust::measurements::CDnaStation::m_dcurrentLongitude protected
Definition at line 330 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetcurrentLongitude(), operator=(), ReduceStations_XYZ(), SetStationRec(), WriteBinaryStn(), and WriteDNAXMLStnCurrentEstimates().
m_dcurrentHeight
double dynadjust::measurements::CDnaStation::m_dcurrentHeight protected
Definition at line 331 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetcurrentHeight(), operator=(), ReduceStations_XYZ(), SetcurrentHeight_d(), SetStationRec(), WriteBinaryStn(), and WriteDNAXMLStnCurrentEstimates().
m_fgeoidSep
float dynadjust::measurements::CDnaStation::m_fgeoidSep protected
Definition at line 332 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetgeoidSep(), operator=(), ReduceStations_XYZ(), SetgeoidSep(), SetStationRec(), WriteBinaryStn(), WriteDNAXMLStn(), and WriteGeoidfile().
m_dmeridianDef
double dynadjust::measurements::CDnaStation::m_dmeridianDef protected
Definition at line 333 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetmeridianDef(), operator=(), SetmeridianDef(), SetStationRec(), WriteBinaryStn(), and WriteGeoidfile().
m_dverticalDef
double dynadjust::measurements::CDnaStation::m_dverticalDef protected
Definition at line 334 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetverticalDef(), operator=(), SetStationRec(), SetverticalDef(), WriteBinaryStn(), and WriteGeoidfile().
m_lfileOrder
UINT32 dynadjust::measurements::CDnaStation::m_lfileOrder protected
Definition at line 335 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), GetfileOrder(), operator=(), SetfileOrder(), SetStationRec(), and WriteBinaryStn().
m_lnameOrder
UINT32 dynadjust::measurements::CDnaStation::m_lnameOrder protected
Definition at line 336 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), GetnameOrder(), operator=(), SetnameOrder(), SetStationRec(), and WriteBinaryStn().
m_zone
UINT32 dynadjust::measurements::CDnaStation::m_zone protected
Definition at line 337 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetZone(), operator=(), ReduceStations_LLH(), ReduceStations_XYZ(), SetHemisphereZone(), SetStationRec(), and WriteBinaryStn().
m_unusedStation
bool dynadjust::measurements::CDnaStation::m_unusedStation protected
Definition at line 338 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), IsNotUnused(), IsUnused(), operator=(), SetStationRec(), SetStationUnused(), and SetStationUse().
m_referenceFrame
std::string dynadjust::measurements::CDnaStation::m_referenceFrame protected
Definition at line 340 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetReferenceFrame(), operator=(), SetReferenceFrame(), and SetStationRec().
m_epsgCode
std::string dynadjust::measurements::CDnaStation::m_epsgCode protected
Definition at line 341 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), operator=(), SetEpsg(), SetStationRec(), and WriteBinaryStn().
m_epoch
std::string dynadjust::measurements::CDnaStation::m_epoch protected
Definition at line 342 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), CDnaStation(), GetEpoch(), operator=(), SetEpoch(), SetStationRec(), and WriteBinaryStn().
m_constraintType
CONSTRAINT_TYPE dynadjust::measurements::CDnaStation::m_constraintType protected
Definition at line 344 of file dnastation.hpp.
Referenced by CDnaStation(), CDnaStation(), GetConstraintType(), operator=(), and SetConstraints().
The documentation for this class was generated from the following files:
include/measurement_types/dnastation.hpp
include/measurement_types/dnastation.cpp