DynAdjust: CAboutDlg Class Reference
CAboutDlg Class Reference
Public Types
enum { IDD = IDD_ABOUTBOX }
Public Member Functions
CAboutDlg ()
Protected Member Functions
virtual void DoDataExchange (CDataExchange *pDX)
virtual BOOL OnInitDialog ()
Detailed Description
Definition at line 45 of file dnageoidintDlg.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
IDD
Definition at line 51 of file dnageoidintDlg.cpp.
{ IDD = IDD_ABOUTBOX };
Constructor & Destructor Documentation
CAboutDlg()
CAboutDlg::CAboutDlg ()
Definition at line 63 of file dnageoidintDlg.cpp.
                     : CDialogEx(CAboutDlg::IDD)
{
}
References CAboutDlg(), and IDD.
Referenced by CAboutDlg(), and OnInitDialog().
Member Function Documentation
DoDataExchange()
void CAboutDlg::DoDataExchange (CDataExchange * pDX) protected virtual
Definition at line 67 of file dnageoidintDlg.cpp.
{
    CDialogEx::DoDataExchange(pDX);
}
OnInitDialog()
BOOL CAboutDlg::OnInitDialog () protected virtual
Definition at line 75 of file dnageoidintDlg.cpp.
{
    CDialog::OnInitDialog();
    CString version;
    version.Format("Version %s, %s", __BINARY_VERSION__, __DATE__);
    ((CEdit*)GetDlgItem(IDC_VERSION))->SetWindowText(version);
    CString title;
    title.LoadString(IDS_TT_ABOUT_TITLE);
    SetWindowText(title);
    return TRUE;  // return TRUE  unless you set the focus to a control
}
References __BINARY_VERSION__, CAboutDlg(), IDC_VERSION, IDS_TT_ABOUT_TITLE, OnInitDialog(), and TRUE.
Referenced by OnInitDialog().
The documentation for this class was generated from the following file:
dynadjust/dnageoidint/dnageoidintDlg.cpp