DynAdjust: CFileProc Class Reference
CFileProc Class Reference
#include <FileProc.h>
Public Member Functions
CFileProc ()
~CFileProc ()
bool Delete (CString sPathName)
bool Copy (CString sSource, CString sDest)
bool Replace (CString sSource, CString sDest)
bool Rename (CString sSource, CString sDest)
int CheckPath (CString sPath)
bool CanDelete (CString sPathName)
int FilterIndex (CString strExt)
int Exists (CString strFilepath, long *hFile)
int View (CString strFilepath, CString f_viewer)
CString BrowseForDialog (CString strMsg, HWND hwndOwner)
void ClearFileArrayMemory ()
void BuildFileArray (const char *filedir, const std::vector< std::string > &filetype, const int &no_filetypes)
void EnterSingleFile (char *filename)
CString FileOpenSave (BOOL bOpen_Save, BOOL bMulti_Files, LPCTSTR lpszDir, char *cNewFile, LPCTSTR lpszTitle, LPCTSTR lpszExt, LPCTSTR strFilter, int iFileType)
Static Public Member Functions
static CString GetExt (CString strFilepath)
static CString GetFolder (CString strFilepath)
static CString GetName (CString strFilepath, LPCTSTR lpszExt)
Public Attributes
char m_strDirectory [MAX_PATH]
int m_intNumFiles
long m_lTotalBytes
CString m_strFileExt
_fileindex * m_fIndex
CString m_strDestinationFile
Protected Member Functions
bool DoDelete (CString sPathName)
bool DoCopy (CString sSource, CString sDest, bool bDelteAfterCopy=false)
bool DoFileCopy (CString sSourceFile, CString sDestFile, bool bDelteAfterCopy=false)
bool DoFolderCopy (CString sSourceFolder, CString sDestFolder, bool bDelteAfterCopy=false)
void DoRename (CString sSource, CString sDest)
bool IsFileExist (CString sPathName)
void PreparePath (CString &sPath)
void Initialize ()
void CheckSelfRecursion (CString sSource, CString sDest)
bool CheckSelfCopy (CString sSource, CString sDest)
CString ChangeFileName (CString sFileName)
CString ParseFolderName (CString sPathName)
Private Attributes
CString m_sError
DWORD m_dwError
bool m_bAskIfReadOnly
bool m_bOverwriteMode
bool m_bAborted
int m_iRecursionLimit
Detailed Description
Definition at line 28 of file FileProc.h.
Constructor & Destructor Documentation
CFileProc()
CFileProc::CFileProc ()
Definition at line 42 of file FileProc.cpp.
    : m_strDirectory(""), m_intNumFiles(1), m_lTotalBytes(0)
    , m_strFileExt(""), m_fIndex(NULL)
    , m_strDestinationFile(""), m_sError("No error"), m_dwError(0)
    , m_bAskIfReadOnly(true), m_bOverwriteMode(false), m_bAborted(false)
    , m_iRecursionLimit(-1)
{
}
References m_bAborted, m_bAskIfReadOnly, m_bOverwriteMode, m_dwError, m_fIndex, m_intNumFiles, m_iRecursionLimit, m_lTotalBytes, m_sError, m_strDestinationFile, m_strDirectory, and m_strFileExt.
~CFileProc()
CFileProc::~CFileProc ()
Definition at line 51 of file FileProc.cpp.
{
    ClearFileArrayMemory();
}
References ClearFileArrayMemory().
Member Function Documentation
Delete()
bool CFileProc::Delete (CString sPathName)
Definition at line 738 of file FileProc.cpp.
{
    return DoDelete(sPathName);
}
References DoDelete().
Referenced by CdnageoidintDlg::DeleteLogFile().
Copy()
bool CFileProc::Copy (CString sSource, CString sDest)
Definition at line 383 of file FileProc.cpp.
{
    if (CheckSelfCopy(sSource, sDest)) return true;
    bool bRes;
    bRes = DoCopy(sSource, sDest);
    m_iRecursionLimit = -1;
    return bRes;
}
References CheckSelfCopy(), DoCopy(), and m_iRecursionLimit.
Referenced by CdnageoidintDlg::OnBnClickedViewLog().
Replace()
bool CFileProc::Replace (CString sSource, CString sDest)
Rename()
bool CFileProc::Rename (CString sSource, CString sDest)
CheckPath()
int CFileProc::CheckPath (CString sPath)
Definition at line 412 of file FileProc.cpp.
{
    DWORD dwAttr = GetFileAttributes(sPath);
    if (dwAttr == 0xffffffff)
    {
        if (GetLastError() == ERROR_FILE_NOT_FOUND || GetLastError() == ERROR_PATH_NOT_FOUND)
            return PATH_NOT_FOUND;
        return PATH_ERROR;
    }
    if (dwAttr & FILE_ATTRIBUTE_DIRECTORY)
        return PATH_IS_FOLDER;
    return PATH_IS_FILE;
}
References PATH_ERROR, PATH_IS_FILE, PATH_IS_FOLDER, and PATH_NOT_FOUND.
Referenced by CheckSelfCopy(), DoCopy(), DoDelete(), and DoFolderCopy().
CanDelete()
bool CFileProc::CanDelete (CString sPathName)
Definition at line 636 of file FileProc.cpp.
{
    DWORD dwAttr = GetFileAttributes(sPathName);
    if (dwAttr == -1) return false;
    if (dwAttr & FILE_ATTRIBUTE_READONLY)
    {
        if (m_bAskIfReadOnly)
        {
            CString sTmp = sPathName;
            int pos = sTmp.ReverseFind('\\');
            if (pos != -1) sTmp.Delete(0, pos + 1);
            CString sText = sTmp + CString(" is read olny. Do you want delete it?");
            int iRes = MessageBox(NULL, sText, _T("Warning"), MB_YESNOCANCEL | MB_ICONQUESTION);
            switch (iRes)
            {
                case IDYES:
                {
                    if (!SetFileAttributes(sPathName, FILE_ATTRIBUTE_NORMAL)) return false;
                    return true;
                }
                case IDNO:
                {
                    return false;
                }
                case IDCANCEL:
                {
                    m_bAborted = true;
                    return false;
                }
            }
        }
        else
        {
            if (!SetFileAttributes(sPathName, FILE_ATTRIBUTE_NORMAL)) return false;
            return true;
        }
    }
    return true;
}
References m_bAborted, and m_bAskIfReadOnly.
Referenced by DoDelete().
FilterIndex()
int CFileProc::FilterIndex (CString strExt)
Definition at line 329 of file FileProc.cpp.
{
    if (!strExt.CompareNoCase(CSV))
        return 2;
    else if (!strExt.CompareNoCase(QIF))
        return 3;
    else if (!strExt.CompareNoCase(MAN))
        return 4;
    else if (!strExt.CompareNoCase(RES))
        return 5;
    else
        return 1;       // txt, dat, prn
}
References CSV, MAN, QIF, and RES.
Exists()
int CFileProc::Exists (CString strFilepath, long * hFile)
Definition at line 316 of file FileProc.cpp.
{
    struct _finddata_t file_t;
    if (hFile == NULL)      // do not need handle
        return (int)_findfirst((char*)((LPCTSTR)strFilepath), &file_t);
    if ((*hFile = (long)_findfirst((char*)((LPCTSTR)strFilepath), &file_t)) != -1L)
        return 1;
    else
        return 0;
}
Referenced by CRegProc::GetTemporaryFileSettings(), CdnageoidintDlg::OnInitDialog(), CRegProc::PreferencesFileExists(), and View().
View()
int CFileProc::View (CString strFilepath, CString f_viewer)
Definition at line 344 of file FileProc.cpp.
{
    STARTUPINFO si;
    PROCESS_INFORMATION pi;
    long hFile;
    if(!Exists(strFilepath, &hFile))
        return -1;
    strFilepath.Insert(0, " \"");
    strFilepath.Insert(0, f_viewer);
    strFilepath +="\"";
    si.cb = sizeof(si);
    si.wShowWindow = SW_SHOW;
    si.dwFlags = STARTF_USESHOWWINDOW;
    si.cb = sizeof(STARTUPINFO);
    si.lpReserved = NULL;
    si.lpReserved2 = NULL;
    si.cbReserved2 = 0;
    si.lpTitle = (char*)((LPCTSTR)strFilepath);
    si.lpDesktop = (LPTSTR)NULL;
    si.dwFlags = STARTF_FORCEONFEEDBACK;
    // run process
    if (!CreateProcess(NULL, (char*)((LPCTSTR)strFilepath), NULL, NULL, FALSE, NORMAL_PRIORITY_CLASS,
                        NULL, (LPTSTR)NULL, &si, &pi))
        return 0;
    // close process and thread handles
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    return 1;
}
References Exists(), and FALSE.
Referenced by CdnageoidintDlg::OnBnClickedViewLog().
GetExt()
CString CFileProc::GetExt (CString strFilepath) static
Definition at line 280 of file FileProc.cpp.
{
    int i;
    i = strFilepath.ReverseFind('.');
    if (i == -1)
        return "";
    else
        return strFilepath.Mid(i + 1);
}
Referenced by FileOpenSave(), CdnageoidintDlg::OnOpenGridFile(), and CdnageoidintDlg::OnOpenInputData().
GetFolder()
CString CFileProc::GetFolder (CString strFilepath) static
Definition at line 268 of file FileProc.cpp.
{
    int i;
    i = strFilepath.ReverseFind('\\');
    if (i == -1)
        return "";
    else
        return strFilepath.Mid(0, i);
}
Referenced by CdnageoidintDlg::DeleteLogFile(), CdnageoidintDlg::OnBnClickedViewLog(), and CdnageoidintDlg::OnOpenInputData().
GetName()
CString CFileProc::GetName (CString strFilepath, LPCTSTR lpszExt) static
Definition at line 292 of file FileProc.cpp.
{
    int i;
    i = strFilepath.ReverseFind('\\');
    if (i != -1)
        strFilepath = strFilepath.Mid(i+1);
    else
        return "";
    if (lpszExt == NULL)
        return strFilepath;
    i = strFilepath.ReverseFind('.');
    if (i == -1)
        strFilepath += '.' + lpszExt;
    else
        strFilepath = strFilepath.Mid(0, i+1) + lpszExt;
    return strFilepath;
}
Referenced by CdnageoidintDlg::OnFileCreateausgeoid(), and CdnageoidintDlg::OnOpenInputData().
BrowseForDialog()
CString CFileProc::BrowseForDialog (CString strMsg, HWND hwndOwner)
Definition at line 128 of file FileProc.cpp.
{
    CString strPath = "";
    LPITEMIDLIST pidlSelected = NULL;
    BROWSEINFO bi = {0};
    LPMALLOC pMalloc = NULL;
    SHGetMalloc(&pMalloc);
    OleInitialize(NULL);
    if (pMalloc != NULL)
    {
        ZeroMemory(&bi, sizeof(bi));
        bi.hwndOwner = hwndOwner;
        bi.pidlRoot = 0;
        bi.pszDisplayName = 0;
        bi.lpszTitle = msg;
        bi.ulFlags = BIF_RETURNONLYFSDIRS | BIF_STATUSTEXT | BIF_USENEWUI | BIF_VALIDATE;
        bi.lpfn = BrowseCallbackProc;
        bi.lParam = 0;
        pidlSelected = SHBrowseForFolder(&bi);
        if(pidlSelected)
        {
            SHGetPathFromIDList(pidlSelected, m_strDirectory);
            strPath = m_strDirectory;
        }
        pMalloc->Free(pidlSelected);
        pMalloc->Release();
    }
    return strPath;
}
References BrowseCallbackProc(), and m_strDirectory.
ClearFileArrayMemory()
void CFileProc::ClearFileArrayMemory ()
Definition at line 256 of file FileProc.cpp.
{
    // check for existence of allcoated memory for _fileindex struct
    if (m_fIndex != NULL)
    {
        // delete and NULL pointer to sruct
        delete[] m_fIndex;
        m_fIndex = NULL;
    }
}
References m_fIndex.
Referenced by FileOpenSave(), and ~CFileProc().
BuildFileArray()
void CFileProc::BuildFileArray (const char * filedir, const std::vector< std::string > & filetype, const int & no_filetypes)
Definition at line 56 of file FileProc.cpp.
{
    char chFilter[_MAX_PATH];
    struct _finddata_t _fFile;
    int iNumFile, success, FileCount;
    FileCount = 0;
    success = iNumFile = 0;
    for (int i=0; i<no_filetypes; i++)
    {
        sprintf(chFilter, "%s\\*.%s", filedir, filetypes.at(i).c_str());
        // how many are there
        iNumFile = success = (int)_findfirst(chFilter, &_fFile );
        while (success > -1)
        {
            if (_fFile.attrib != _A_SUBDIR)
                FileCount++;
            if (success > -1)
                success = _findnext(iNumFile, &_fFile);
        }
    }
    // If there are none
    if (FileCount == 0)
        return;
    if (m_fIndex == NULL)
        m_fIndex = new _fileindex[FileCount + 1];
    if (m_fIndex == NULL)
        return;     // could not allocate memory
    memset(m_fIndex, '\0', sizeof(_fileindex) * FileCount);
    m_intNumFiles = 0;
    // iterate a second time storing the names
    for (int i=0; i<no_filetypes; i++)
    {
        sprintf(chFilter, "%s\\*.%s", filedir, filetypes.at(i).c_str());
        // how many are there
        iNumFile = success = (int)_findfirst(chFilter, &_fFile );
        while (success > -1)
        {
            if (_fFile.attrib != _A_SUBDIR)
            {
                strcpy(m_fIndex[m_intNumFiles].chfilename, _fFile.name);
                m_intNumFiles++;
                m_lTotalBytes += _fFile.size;
            }
            if (success > -1)
                success = _findnext(iNumFile, &_fFile);
        }
    }
}
References m_fIndex, m_intNumFiles, and m_lTotalBytes.
Referenced by CdnageoidintDlg::DeleteLogFile(), and CdnageoidintDlg::OnTransform().
EnterSingleFile()
void CFileProc::EnterSingleFile (char * filename)
Definition at line 118 of file FileProc.cpp.
{
    // Only a single file to be used
    m_fIndex = new _fileindex[1];
    memset(m_fIndex, '\0', sizeof(_fileindex));
    strcpy_s(m_fIndex[0].chfilename, _MAX_PATH, filename);
    m_intNumFiles = 1;
}
References m_fIndex, and m_intNumFiles.
Referenced by CdnageoidintDlg::OnTransform().
FileOpenSave()
CString CFileProc::FileOpenSave (BOOL bOpen_Save, BOOL bMulti_Files, LPCTSTR lpszDir, char * cNewFile, LPCTSTR lpszTitle, LPCTSTR lpszExt, LPCTSTR strFilter, int iFileType)
Definition at line 160 of file FileProc.cpp.
{
    char szFile[MAX_FILEPATH] = "";
    DWORD Flags;
    int i;
    typedef struct tagOFNA { // ofn
        DWORD         nFilterIndex;
        LPTSTR        lpstrFile;
        DWORD         nMaxFile;
        LPCTSTR       lpstrInitialDir;
        LPCTSTR       lpstrTitle;
        DWORD         Flags;
        LPCTSTR       lpstrDefExt;
    } OPENFILENAME;
    memset(szFile, '\0', sizeof(szFile));
    if (OPEN_DLG)           // Open File
    {
        if (MULTI_FILE)
            Flags = OFN_HIDEREADONLY | OFN_ALLOWMULTISELECT;    // multi files
        else
            Flags = OFN_HIDEREADONLY;                           // single file
    }
    else                    // Save File
        Flags = OFN_HIDEREADONLY | OFN_OVERWRITEPROMPT | OFN_PATHMUSTEXIST;
    CFileDialog m_ldFile(OPEN_DLG, lpszExt, cNewFile, Flags, strFilter, NULL);
    if (MULTI_FILE)
    {
        m_ldFile.m_ofn.lpstrFile = szFile;
        strcpy(szFile, cNewFile);
        m_ldFile.m_ofn.nMaxFile = sizeof(szFile);
    }
    else
    {
        m_ldFile.m_ofn.lpstrFile = cNewFile;
    }
    //Initialise the starting variables for the open / save as file dialog box
    m_ldFile.m_ofn.nFilterIndex = iFileType;
    m_ldFile.m_ofn.lpstrInitialDir = lpszDir;
    m_ldFile.m_ofn.lpstrTitle = lpszTitle;
    m_ldFile.m_ofn.lpstrDefExt = lpszExt;
    //Show the File Open dialog and return the result
    if (m_ldFile.DoModal() == IDOK)
    {
        m_strFileExt = m_ldFile.GetFileExt();
        m_intNumFiles = 1;
        if (MULTI_FILE)
        {
            m_intNumFiles = 0;
            POSITION pos = m_ldFile.GetStartPosition();
            while (pos != NULL)
            {
                 m_ldFile.GetNextPathName(pos);
                 m_intNumFiles++;
            }
            if (m_intNumFiles == 0)
                return "";
            ClearFileArrayMemory();
            m_fIndex = new _fileindex[m_intNumFiles + 1];
            if (m_fIndex == NULL)
                return "";      // could not allocate memory
            memset(m_fIndex, '\0', sizeof(_fileindex) * (m_intNumFiles + 1));
            // iterate a second time storing the names
            pos = m_ldFile.GetStartPosition();
            i = 0;
            while (pos != NULL)
            {
                 strcpy(m_fIndex[i].chfilename, m_ldFile.GetNextPathName(pos));
                 i ++;
            }
            m_strFileExt = GetExt(m_fIndex[0].chfilename);
            return m_fIndex[0].chfilename;
        }
        else
            return m_ldFile.GetPathName();
    }
    else
        return "";
}
References ClearFileArrayMemory(), GetExt(), m_fIndex, m_intNumFiles, m_strFileExt, and MAX_FILEPATH.
Referenced by CdnageoidintDlg::OnOpenInputData().
DoDelete()
bool CFileProc::DoDelete (CString sPathName) protected
Definition at line 568 of file FileProc.cpp.
{
    CFileFind ff;
    CString sPath = sPathName;
    if (CheckPath(sPath) == PATH_IS_FILE)
    {
        if (!CanDelete(sPath))
        {
            m_bAborted = true;
            return false;
        }
        if (!DeleteFile(sPath))
            return false;
        return true;
    }
    PreparePath(sPath);
    sPath += "*.*";
    BOOL bRes = ff.FindFile(sPath);
    while(bRes)
    {
        bRes = ff.FindNextFile();
        if (ff.IsDots())
            continue;
        if (ff.IsDirectory())
        {
            sPath = ff.GetFilePath();
            DoDelete(sPath);
        }
        else DoDelete(ff.GetFilePath());
    }
    ff.Close();
    if (!RemoveDirectory(sPathName) && !m_bAborted)
        return false;
    return true;
}
References CanDelete(), CheckPath(), DoDelete(), m_bAborted, PATH_IS_FILE, and PreparePath().
Referenced by Delete(), DoDelete(), and DoFileCopy().
DoCopy()
bool CFileProc::DoCopy (CString sSource, CString sDest, bool bDelteAfterCopy = false) protected
Definition at line 427 of file FileProc.cpp.
{
    CheckSelfRecursion(sSource, sDest);
    // source not found
    if (CheckPath(sSource) == PATH_NOT_FOUND)
    {
        m_sError = sSource + CString(" not found");
        return false;
    }
    // dest not found
    if (CheckPath(sDest) == PATH_NOT_FOUND)
    {
        m_sError = sDest + CString(" not found");
        return false;
    }
    // folder to file
    if (CheckPath(sSource) == PATH_IS_FOLDER && CheckPath(sDest) == PATH_IS_FILE)
        return false;
    // folder to folder
    if (CheckPath(sSource) == PATH_IS_FOLDER && CheckPath(sDest) == PATH_IS_FOLDER)
    {
        CFileFind ff;
        m_sError = sSource + CString(" not found");
        PreparePath(sSource);
        PreparePath(sDest);
        sSource += "*.*";
        if (!ff.FindFile(sSource))
        {
            ff.Close();
            return false;
        }
        if (!ff.FindNextFile())
        {
            ff.Close();
            return false;
        }
        CString sFolderName = ParseFolderName(sSource);
        if (!sFolderName.IsEmpty()) // the source is not drive
        {
            sDest += sFolderName;
            PreparePath(sDest);
            if (!CreateDirectory(sDest, NULL))
            {
                DWORD dwErr = GetLastError();
                if (dwErr != 183)
                {
                    ff.Close();
                    return false;
                }
            }
        }
        ff.Close();
        DoFolderCopy(sSource, sDest, bDelteAfterCopy);
    }
    // file to file
    if (CheckPath(sSource) == PATH_IS_FILE && CheckPath(sDest) == PATH_IS_FILE)
    {
        if (!DoFileCopy(sSource, sDest))
            return false;
    }
    // file to folder
    if (CheckPath(sSource) == PATH_IS_FILE && CheckPath(sDest) == PATH_IS_FOLDER)
    {
        PreparePath(sDest);
        char drive[MAX_PATH], dir[MAX_PATH], name[MAX_PATH], ext[MAX_PATH];
        _splitpath(sSource, drive, dir, name, ext);
        sDest = sDest + CString(name) + CString(ext);
        if (!DoFileCopy(sSource, sDest))
            return false;
    }
    return true;
}
References CheckPath(), CheckSelfRecursion(), DoFileCopy(), DoFolderCopy(), m_sError, ParseFolderName(), PATH_IS_FILE, PATH_IS_FOLDER, PATH_NOT_FOUND, and PreparePath().
Referenced by Copy().
DoFileCopy()
bool CFileProc::DoFileCopy (CString sSourceFile, CString sDestFile, bool bDelteAfterCopy = false) protected
Definition at line 503 of file FileProc.cpp.
{
    BOOL bOvrwriteFails = FALSE;
    if (!m_bOverwriteMode)
    {
        while (IsFileExist(sDestFile))
        {
            sDestFile = ChangeFileName(sDestFile);
        }
        bOvrwriteFails = TRUE;
    }
    if (!CopyFile(sSourceFile, sDestFile, bOvrwriteFails))
    {
        m_strDestinationFile = "";
        return false;
    }
    m_strDestinationFile = sDestFile;
    if (bDelteAfterCopy)
    {
        DoDelete(sSourceFile);
    }
    return true;
}
References ChangeFileName(), DoDelete(), FALSE, IsFileExist(), m_bOverwriteMode, m_strDestinationFile, and TRUE.
Referenced by DoCopy(), and DoFolderCopy().
DoFolderCopy()
bool CFileProc::DoFolderCopy (CString sSourceFolder, CString sDestFolder, bool bDelteAfterCopy = false) protected
Definition at line 530 of file FileProc.cpp.
{
    CFileFind ff;
    CString sPathSource = sSourceFolder;
    BOOL bRes = ff.FindFile(sPathSource);
    while (bRes)
    {
        bRes = ff.FindNextFile();
        if (ff.IsDots()) continue;
        if (ff.IsDirectory()) // source is a folder
        {
            if (m_iRecursionLimit == 0) continue;
            sPathSource = ff.GetFilePath() + CString("\\") + CString("*.*");
            CString sPathDest = sDestFolder + ff.GetFileName() + CString("\\");
            if (CheckPath(sPathDest) == PATH_NOT_FOUND)
            {
                if (!CreateDirectory(sPathDest, NULL))
                {
                    ff.Close();
                    return false;
                }
            }
            if (m_iRecursionLimit > 0)
                m_iRecursionLimit --;
            if (!DoFolderCopy(sPathSource, sPathDest, bDelteAfterCopy))
                return false;
        }
        else // source is a file
        {
            CString sNewFileName = sDestFolder + ff.GetFileName();
            if (!DoFileCopy(ff.GetFilePath(), sNewFileName, bDelteAfterCopy))
                return false;
        }
    }
    ff.Close();
    return true;
}
References CheckPath(), DoFileCopy(), DoFolderCopy(), m_iRecursionLimit, and PATH_NOT_FOUND.
Referenced by DoCopy(), and DoFolderCopy().
DoRename()
void CFileProc::DoRename (CString sSource, CString sDest) protected
IsFileExist()
bool CFileProc::IsFileExist (CString sPathName) protected
Definition at line 608 of file FileProc.cpp.
{
    HANDLE hFile;
    hFile = CreateFile(sPathName, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, NULL, NULL);
    if (hFile == INVALID_HANDLE_VALUE) return false;
    CloseHandle(hFile);
    return true;
}
Referenced by DoFileCopy().
PreparePath()
void CFileProc::PreparePath (CString & sPath) protected
Definition at line 618 of file FileProc.cpp.
{
    if(sPath.Right(1) != "\\") sPath += "\\";
}
Referenced by DoCopy(), and DoDelete().
Initialize()
void CFileProc::Initialize () protected
References sFileName.
CheckSelfRecursion()
void CFileProc::CheckSelfRecursion (CString sSource, CString sDest) protected
Definition at line 624 of file FileProc.cpp.
{
    if (sDest.Find(sSource) != -1)
    {
        int i = 0, count1 = 0, count2 = 0;
        for(i = 0; i < sSource.GetLength(); i ++)   if (sSource[i] == '\\') count1 ++;
        for(i = 0; i < sDest.GetLength(); i ++) if (sDest[i] == '\\') count2 ++;
        if (count2 >= count1) m_iRecursionLimit = count2 - count1;
    }
}
References m_iRecursionLimit.
Referenced by DoCopy().
CheckSelfCopy()
bool CFileProc::CheckSelfCopy (CString sSource, CString sDest) protected
Definition at line 395 of file FileProc.cpp.
{
    bool bRes = false;
    if (CheckPath(sSource) == PATH_IS_FOLDER)
    {
        CString sTmp = sSource;
        int pos = sTmp.ReverseFind('\\');
        if (pos != -1)
        {
            sTmp.Delete(pos, sTmp.GetLength() - pos);
            if (sTmp.CompareNoCase(sDest) == 0) bRes = true;
        }
    }
    return bRes;
}
References CheckPath(), and PATH_IS_FOLDER.
Referenced by Copy().
ChangeFileName()
CString CFileProc::ChangeFileName (CString sFileName) protected
Definition at line 677 of file FileProc.cpp.
{
    CString sName, sNewName, sResult;
    char drive[MAX_PATH];
    char dir  [MAX_PATH];
    char name [MAX_PATH];
    char ext  [MAX_PATH];
    _splitpath((LPCTSTR)sFileName, drive, dir, name, ext);
    sName = name;
    int pos = sName.Find("Copy ");
    if (pos == -1)
    {
        sNewName = CString("Copy of ") + sName + CString(ext);
    }
    else
    {
        int pos1 = sName.Find('(');
        if (pos1 == -1)
        {
            sNewName = sName;
            sNewName.Delete(0, 8);
            sNewName = CString("Copy (1) of ") + sNewName + CString(ext);
        }
        else
        {
            CString sCount;
            int pos2 = sName.Find(')');
            if (pos2 == -1)
            {
                sNewName = CString("Copy of ") + sNewName + CString(ext);
            }
            else
            {
                sCount = sName.Mid(pos1 + 1, pos2 - pos1 - 1);
                sName.Delete(0, pos2 + 5);
                int iCount = atoi((LPCTSTR)sCount);
                iCount ++;
                sNewName.Format("%s%d%s%s%s", "Copy (", iCount, ") of ", (LPCTSTR)sName, ext);
            }
        }
    }
    sResult = CString(drive) + CString(dir) + sNewName;
    return sResult;
}
References sFileName.
Referenced by DoFileCopy().
ParseFolderName()
CString CFileProc::ParseFolderName (CString sPathName) protected
Definition at line 726 of file FileProc.cpp.
{
    CString sFolderName = sPathName;
    int pos = sFolderName.ReverseFind('\\');
    if (pos != -1) sFolderName.Delete(pos, sFolderName.GetLength() - pos);
    pos = sFolderName.ReverseFind('\\');
    if (pos != -1) sFolderName = sFolderName.Right(sFolderName.GetLength() - pos - 1);
    else sFolderName.Empty();
    return sFolderName;
}
Referenced by DoCopy().
Member Data Documentation
m_strDirectory
char CFileProc::m_strDirectory[MAX_PATH]
Definition at line 56 of file FileProc.h.
Referenced by BrowseForDialog(), and CFileProc().
m_intNumFiles
int CFileProc::m_intNumFiles
Definition at line 58 of file FileProc.h.
Referenced by BuildFileArray(), CFileProc(), CdnageoidintDlg::DeleteLogFile(), EnterSingleFile(), FileOpenSave(), and CdnageoidintDlg::OnTransform().
m_lTotalBytes
long CFileProc::m_lTotalBytes
Definition at line 59 of file FileProc.h.
Referenced by BuildFileArray(), and CFileProc().
m_strFileExt
CString CFileProc::m_strFileExt
Definition at line 60 of file FileProc.h.
Referenced by CFileProc(), and FileOpenSave().
m_fIndex
_fileindex* CFileProc::m_fIndex
Definition at line 61 of file FileProc.h.
Referenced by BuildFileArray(), CFileProc(), ClearFileArrayMemory(), CdnageoidintDlg::DeleteLogFile(), EnterSingleFile(), FileOpenSave(), and CdnageoidintDlg::OnTransform().
m_strDestinationFile
CString CFileProc::m_strDestinationFile
Definition at line 63 of file FileProc.h.
Referenced by CFileProc(), DoFileCopy(), and CdnageoidintDlg::OnBnClickedViewLog().
m_sError
CString CFileProc::m_sError private
Definition at line 81 of file FileProc.h.
Referenced by CFileProc(), and DoCopy().
m_dwError
DWORD CFileProc::m_dwError private
Definition at line 82 of file FileProc.h.
Referenced by CFileProc().
m_bAskIfReadOnly
bool CFileProc::m_bAskIfReadOnly private
Definition at line 83 of file FileProc.h.
Referenced by CanDelete(), and CFileProc().
m_bOverwriteMode
bool CFileProc::m_bOverwriteMode private
Definition at line 84 of file FileProc.h.
Referenced by CFileProc(), and DoFileCopy().
m_bAborted
bool CFileProc::m_bAborted private
Definition at line 85 of file FileProc.h.
Referenced by CanDelete(), CFileProc(), and DoDelete().
m_iRecursionLimit
int CFileProc::m_iRecursionLimit private
Definition at line 86 of file FileProc.h.
Referenced by CFileProc(), CheckSelfRecursion(), Copy(), and DoFolderCopy().
The documentation for this class was generated from the following files:
dynadjust/dnageoidint/FileProc.h
dynadjust/dnageoidint/FileProc.cpp