DynAdjust: dynadjust::memory::new_handler_holder Class Reference
dynadjust::memory::new_handler_holder Class Reference
#include <dnamemory_handler.hpp>
Public Member Functions
new_handler_holder (std::new_handler nh)
~new_handler_holder ()
Private Member Functions
new_handler_holder (const new_handler_holder &)
new_handler_holder & operator= (const new_handler_holder &)
Private Attributes
std::new_handler _handler
Detailed Description
Definition at line 48 of file dnamemory_handler.hpp.
Constructor & Destructor Documentation
new_handler_holder() [1/2]
dynadjust::memory::new_handler_holder::new_handler_holder (std::new_handler nh) inline explicit
Definition at line 51 of file dnamemory_handler.hpp.
        : _handler(nh) {}                                       // new handler
References _handler.
Referenced by new_handler_holder(), and operator=().
~new_handler_holder()
dynadjust::memory::new_handler_holder::~new_handler_holder () inline
Definition at line 53 of file dnamemory_handler.hpp.
{ std::set_new_handler(_handler); }     // release it
References _handler.
new_handler_holder() [2/2]
dynadjust::memory::new_handler_holder::new_handler_holder (const new_handler_holder &) private
References new_handler_holder().
Member Function Documentation
operator=()
new_handler_holder & dynadjust::memory::new_handler_holder::operator= (const new_handler_holder &) private
References new_handler_holder().
Member Data Documentation
_handler
std::new_handler dynadjust::memory::new_handler_holder::_handler private
Definition at line 55 of file dnamemory_handler.hpp.
Referenced by new_handler_holder(), and ~new_handler_holder().
The documentation for this class was generated from the following file:
include/memory/dnamemory_handler.hpp