DynAdjust: dynadjust::iostreams::dna_io_asl Class Reference
dynadjust::iostreams::dna_io_asl Class Reference
#include <dnaioasl.hpp>
Public Member Functions
dna_io_asl (void)
dna_io_asl (const dna_io_asl &asl)
virtual ~dna_io_asl (void)
dna_io_asl & operator= (const dna_io_asl &rhs)
UINT32 load_asl_file (const std::string &asl_filename, vASL *vbinary_asl, vUINT32 *vfree_stn)
void write_asl_file (const std::string &asl_filename, pvASLPtr vbinary_asl)
void write_asl_file_txt (const std::string &asl_filename, pvASLPtr vbinary_asl, vdnaStnPtr *vStations)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 41 of file dnaioasl.hpp.
Constructor & Destructor Documentation
dna_io_asl() [1/2]
dynadjust::iostreams::dna_io_asl::dna_io_asl (void) inline
Definition at line 44 of file dnaioasl.hpp.
{};
Referenced by dna_io_asl(), and operator=().
dna_io_asl() [2/2]
dynadjust::iostreams::dna_io_asl::dna_io_asl (const dna_io_asl & asl) inline
Definition at line 45 of file dnaioasl.hpp.
: dna_io_base(asl) {};
References dna_io_asl(), and dynadjust::iostreams::dna_io_base::dna_io_base().
~dna_io_asl()
virtual dynadjust::iostreams::dna_io_asl::~dna_io_asl (void) inline virtual
Definition at line 46 of file dnaioasl.hpp.
{};
Member Function Documentation
operator=()
dna_io_asl & dynadjust::iostreams::dna_io_asl::operator= (const dna_io_asl & rhs)
References dna_io_asl().
load_asl_file()
UINT32 dynadjust::iostreams::dna_io_asl::load_asl_file (const std::string & asl_filename, vASL * vbinary_asl, vUINT32 * vfree_stn)
Definition at line 33 of file dnaioasl.cpp.
{
    std::ifstream asl_file;
    std::stringstream ss;
    ss << "load_asl_file(): An error was encountered when opening " << asl_filename << "." << std::endl;
    try {
        // open stations asl file.  Throws runtime_error on failure.
        file_opener(asl_file, asl_filename, std::ios::in | std::ios::binary, binary, true);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "load_asl_file(): An error was encountered when reading from " << asl_filename << "." << std::endl;
    UINT32 stnCount;
    try {
        // read the file information
        readFileInfo(asl_file);
        // Get number of records and resize AML vector
        asl_file.read(reinterpret_cast<char *>(&stnCount), sizeof(UINT32));
        // initialise free station list
        initialiseIncrementingIntegerVector(vfree_stn, stnCount);
        // initialise assocaiated station list
        vbinary_asl->clear();
        vbinary_asl->resize(stnCount);
        _it_vasl _it_asl;
        for (_it_asl=vbinary_asl->begin();
            _it_asl!=vbinary_asl->end();
            ++_it_asl)
        {
            asl_file >> &(*_it_asl);
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    asl_file.close();
    return stnCount;
}
References binary, file_opener(), initialiseIncrementingIntegerVector(), and dynadjust::iostreams::dna_io_base::readFileInfo().
Referenced by dynadjust::networksegment::dna_segment::LoadAssociationFiles(), and dynadjust::networkadjust::dna_adjust::LoadNetworkFiles().
write_asl_file()
void dynadjust::iostreams::dna_io_asl::write_asl_file (const std::string & asl_filename, pvASLPtr vbinary_asl)
Definition at line 97 of file dnaioasl.cpp.
{
    std::ofstream asl_file;
    std::stringstream ss;
    ss << "write_asl_file(): An error was encountered when opening " << asl_filename << "." << std::endl;
    try {
        // create binary asl file.  Throws runtime_error on failure.
        file_opener(asl_file, asl_filename,
            std::ios::out | std::ios::binary, binary);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_asl_file(): An error was encountered when writing to " << asl_filename << "." << std::endl;
    // Calculate number of station records and write to binary file
    UINT32 aslCount = static_cast<UINT32>(vbinary_asl->size());
    vASLPtr::const_iterator _it_asl(vbinary_asl->begin());
    try {
        // write the file information
        writeFileInfo(asl_file);
        // write the data
        asl_file.write(reinterpret_cast<char *>(&aslCount), sizeof(UINT32));
        for (_it_asl=vbinary_asl->begin(); _it_asl!=vbinary_asl->end(); ++_it_asl)
            if (_it_asl->get())
                asl_file << _it_asl->get();         // see dnastation.hpp (region CAStationList stream handlers)
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    asl_file.close();
}
References binary, file_opener(), and dynadjust::iostreams::dna_io_base::writeFileInfo().
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseAsl().
write_asl_file_txt()
void dynadjust::iostreams::dna_io_asl::write_asl_file_txt (const std::string & asl_filename, pvASLPtr vbinary_asl, vdnaStnPtr * vStations)
Definition at line 150 of file dnaioasl.cpp.
{
    std::ofstream asl_file;
    std::stringstream ss;
    ss << "write_asl_file_txt(): An error was encountered when opening " << asl_filename << "." << std::endl;
    try {
        // create binary asl file.  Throws runtime_error on failure.
        file_opener(asl_file, asl_filename);
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    ss.str("");
    ss << "write_asl_file_txt(): An error was encountered when writing to " << asl_filename << "." << std::endl;
    // Calculate number of station records and write to binary file
    size_t aslCount = vbinary_asl->size();
    // Pump to text file
    std::stringstream ss_asl;
    ss_asl << aslCount << " stations";
    asl_file << std::left << std::setw(STATION) << ss_asl.str();
    asl_file << std::setw(HEADER_20) << std::right << "No. connected msrs";
    asl_file << std::setw(STATION) << std::right << "AML index";
    asl_file << std::setw(STATION) << std::right << "Unused?" << std::endl;
    // Create an incrementing list and sort on number of measurements to each station
    vUINT32 aslPtrs(vbinary_asl->size());
    initialiseIncrementingIntegerVector<UINT32>(aslPtrs, static_cast<UINT32>(vbinary_asl->size()));
    // Sort on measurement count
    CompareMeasCount2<ASLPtr, UINT32> msrcountCompareFunc(vbinary_asl);
    std::sort(aslPtrs.begin(), aslPtrs.end(), msrcountCompareFunc);
    vbinary_asl->at(0).get()->GetAMLStnIndex();
    try {
        it_vUINT32 _it_asl;
        vASLPtr::iterator _it_pasl;
        for (_it_asl=aslPtrs.begin(); _it_asl!=aslPtrs.end(); ++_it_asl)
        {
            if (!vbinary_asl->at(*_it_asl)) // unused station
                continue;
            _it_pasl = vbinary_asl->begin() + *_it_asl;
            // Name and measurement count
            asl_file << std::setw(STATION) << std::left <<
                vStations->at(*_it_asl)->GetName() <<
                std::setw(HEADER_20) << std::right << _it_pasl->get()->GetAssocMsrCount();
            // Aml station index
            if (_it_pasl->get()->GetAssocMsrCount() == 0)
                asl_file << std::setw(STATION) << "-";
            else
                asl_file << std::setw(STATION) << std::right << _it_pasl->get()->GetAMLStnIndex();
            // Valid station?
            asl_file << std::setw(STATION) << std::right << (_it_pasl->get()->IsValid() ? " " : "*") << std::endl;
        }
    }
    catch (const std::ios_base::failure& f) {
        ss << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (const std::runtime_error& e) {
        ss << e.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    asl_file.close();
}
References file_opener(), HEADER_20(), initialiseIncrementingIntegerVector(), and STATION().
Referenced by dynadjust::dynamlinterop::dna_import::SerialiseAslTextFile().
The documentation for this class was generated from the following files:
include/io/dnaioasl.hpp
include/io/dnaioasl.cpp