DynAdjust: dynadjust::math::matrix_2d Class Reference
dynadjust::math::matrix_2d Class Reference
#include <dnamatrix_contiguous.hpp>
Public Member Functions
matrix_2d ()
matrix_2d (const index_t &rows, const index_t &columns)
matrix_2d (const index_t &rows, const index_t &columns, const double data[], const index_t &data_size, const index_t &matrix_type=mtx_full)
matrix_2d (const matrix_2d &)
~matrix_2d ()
bool empty ()
std::size_t get_size ()
index_t memRows () const
index_t memColumns () const
index_t rows () const
index_t columns () const
double * getbuffer () const
double & get (const index_t &r, const index_t &c) const
double * getbuffer (const index_t &r, const index_t &c) const
void submatrix (const index_t &row_begin, const index_t &col_begin, matrix_2d *dest, const index_t &rows, const index_t &columns) const
matrix_2d submatrix (const index_t &row_begin, const index_t &col_begin, const index_t &rows, const index_t &columns) const
double maxvalue () const
index_t maxvalueRow () const
index_t maxvalueCol () const
double * getelementref (const index_t &r, const index_t &c) const
double * getelementref (const index_t &r, const index_t &c)
void mem_rows (const index_t &r)
void mem_columns (const index_t &c)
void rows (const index_t &r)
void columns (const index_t &c)
void maxvalueRow (const index_t &r)
void maxvalueCol (const index_t &c)
void put (const index_t &r, const index_t &c, const double &val)
index_t matrixType () const
void matrixType (const index_t t)
void copyelements (const index_t &row_dest, const index_t &column_dest, const matrix_2d &src, const index_t &row_src, const index_t &column_src, const index_t &rows, const index_t &columns)
void copyelements (const index_t &row_dest, const index_t &column_dest, const matrix_2d *src, const index_t &row_src, const index_t &column_src, const index_t &rows, const index_t &columns)
void elementadd (const index_t &r, const index_t &c, const double &inc)
void elementsubtract (const index_t &r, const index_t &c, const double &dec)
void elementmultiply (const index_t &r, const index_t &c, const double &scale)
void blockadd (const index_t &row_dest, const index_t &col_dest, const matrix_2d &mat_src, const index_t &row_src, const index_t &col_src, const index_t &rows, const index_t &cols)
void blockTadd (const index_t &row_dest, const index_t &col_dest, const matrix_2d &mat_src, const index_t &row_src, const index_t &col_src, const index_t &rows, const index_t &cols)
void blocksubtract (const index_t &row_dest, const index_t &col_dest, const matrix_2d &mat_src, const index_t &row_src, const index_t &col_src, const index_t &rows, const index_t &cols)
matrix_2d add (const matrix_2d &rhs)
matrix_2d add (const matrix_2d &lhs, const matrix_2d &rhs)
matrix_2d multiply (const char *lhs_trans, const matrix_2d &rhs, const char *rhs_trans)
matrix_2d multiply (const matrix_2d &lhs, const char *lhs_trans, const matrix_2d &rhs, const char *rhs_trans)
matrix_2d sweepinverse ()
matrix_2d cholesky_inverse (bool LOWER_IS_CLEARED=false)
matrix_2d transpose (const matrix_2d &)
matrix_2d transpose ()
matrix_2d scale (const double &scalar)
bool operator== (const matrix_2d &rhs) const
bool operator!= (const matrix_2d &rhs) const
matrix_2d operator= (const matrix_2d &rhs)
matrix_2d operator* (const double &rhs) const
void allocate ()
void allocate (const index_t &rows, const index_t &columns)
void setsize (const index_t &rows, const index_t &columns)
void redim (const index_t &rows, const index_t &columns)
void replace (const index_t &rowstart, const index_t &columnstart, const matrix_2d &newmat)
void replace (const index_t &rowstart, const index_t &columnstart, const index_t &rows, const index_t &columns, const matrix_2d &newmat)
void shrink (const index_t &rows, const index_t &columns)
void grow (const index_t &rows, const index_t &columns)
void clearlower ()
void filllower ()
void fillupper ()
void zero ()
void zero (const index_t &row_begin, const index_t &col_begin, const index_t &rows, const index_t &columns)
double compute_maximum_value ()
void ReadMappedFileRegion (void *addr)
void WriteMappedFileRegion (void *addr)
Private Member Functions
std::size_t buffersize () const
void deallocate ()
void buy (const index_t &rows, const index_t &columns, double **mem_space)
void copybuffer (const index_t &rows, const index_t &columns, const matrix_2d &oldmat)
void copybuffer (const index_t &rowstart, const index_t &columnstart, const index_t &rows, const index_t &columns, const matrix_2d &mat)
void sweep (index_t k1, index_t k2)
Private Attributes
index_t _cols
index_t _rows
index_t _mem_cols
index_t _mem_rows
index_t _maxvalCol
index_t _maxvalRow
index_t _matrixType
double * _buffer = nullptr
Friends
std::ostream & operator<< (std::ostream &os, const matrix_2d &rhs)
Additional Inherited Members
Static Public Member Functions inherited from dynadjust::memory::new_handler_support< matrix_2d >
static std::new_handler set_new_handler (std::new_handler p) noexcept
static void * operator new (size_t size) noexcept(false)
Detailed Description
Definition at line 153 of file dnamatrix_contiguous.hpp.
Constructor & Destructor Documentation
matrix_2d() [1/4]
dynadjust::math::matrix_2d::matrix_2d ()
Definition at line 104 of file dnamatrix_contiguous.cpp.
    : _mem_cols(0), _mem_rows(0), _cols(0), _rows(0), _buffer(0), _maxvalCol(0),
      _maxvalRow(0), _matrixType(mtx_full) {
    std::set_new_handler(out_of_memory_handler);
}
References _buffer, _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, mtx_full, and dynadjust::math::out_of_memory_handler().
Referenced by add(), add(), blockadd(), blocksubtract(), blockTadd(), cholesky_inverse(), copybuffer(), copybuffer(), copyelements(), copyelements(), matrix_2d(), multiply(), multiply(), operator!=(), operator*(), operator<<, operator=(), operator==(), replace(), replace(), scale(), submatrix(), submatrix(), sweepinverse(), transpose(), and transpose().
matrix_2d() [2/4]
dynadjust::math::matrix_2d::matrix_2d (const index_t & rows, const index_t & columns)
Definition at line 110 of file dnamatrix_contiguous.cpp.
    : _mem_cols(columns), _mem_rows(rows), _cols(columns), _rows(rows),
      _buffer(0), _maxvalCol(0), _maxvalRow(0), _matrixType(mtx_full) {
    std::set_new_handler(out_of_memory_handler);
    allocate(_rows, _cols);
}
References _buffer, _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, allocate(), columns(), mtx_full, dynadjust::math::out_of_memory_handler(), and rows().
matrix_2d() [3/4]
dynadjust::math::matrix_2d::matrix_2d (const index_t & rows, const index_t & columns, const double data[], const index_t & data_size, const index_t & matrix_type = mtx_full)
Definition at line 117 of file dnamatrix_contiguous.cpp.
    : _mem_cols(columns), _mem_rows(rows), _cols(columns), _rows(rows),
      _buffer(0), _maxvalCol(0), _maxvalRow(0), _matrixType(matrix_type) {
    std::set_new_handler(out_of_memory_handler);
    std::stringstream ss;
    index_t upperMatrixElements(sumOfConsecutiveIntegers(rows));
    index_t j;
    const double* dataptr = &data[0];
    switch (matrix_type) {
    case mtx_lower:
        if (upperMatrixElements != data_size) {
            ss << "Data size must match upper matrix element count for " << rows
               << " x " << columns << ".";
            throw boost::enable_current_exception(std::runtime_error(ss.str()));
        }
        allocate(_rows, _cols);
        for (j = 0; j < columns; ++j) {
            memcpy(getelementref(j, j), dataptr, (rows - j) * sizeof(double));
            dataptr += (rows - j);
        }
        fillupper();
        break;
    case mtx_sparse:
        ss << "matrix_2d(): Cannot initialise sparse matrix from double array.";
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
        break;
    case mtx_full:
    default:
        if (data_size != rows * columns) {
            ss << "Data size must match matrix dimensions (" << rows << " x "
               << columns << ").";
            throw boost::enable_current_exception(std::runtime_error(ss.str()));
        }
        allocate(_rows, _cols);
        memcpy(_buffer, data, data_size * sizeof(double));
        break;
    }
}
References _buffer, _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, allocate(), columns(), fillupper(), getelementref(), mtx_full, mtx_lower, mtx_sparse, dynadjust::math::out_of_memory_handler(), rows(), and sumOfConsecutiveIntegers().
matrix_2d() [4/4]
dynadjust::math::matrix_2d::matrix_2d (const matrix_2d & newmat)
Definition at line 160 of file dnamatrix_contiguous.cpp.
    : _mem_cols(newmat.memColumns()), _mem_rows(newmat.memRows()),
      _cols(newmat.columns()), _rows(newmat.rows()), _buffer(0),
      _maxvalCol(newmat.maxvalueCol()), _maxvalRow(newmat.maxvalueRow()),
      _matrixType(newmat.matrixType()) {
    std::set_new_handler(out_of_memory_handler);
    allocate(_mem_rows, _mem_cols);
    const double* ptr = newmat.getbuffer();
    memcpy(_buffer, ptr, newmat.buffersize());
}
References _buffer, _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, allocate(), buffersize(), columns(), getbuffer(), matrix_2d(), matrixType(), maxvalueCol(), maxvalueRow(), memColumns(), memRows(), dynadjust::math::out_of_memory_handler(), and rows().
~matrix_2d()
dynadjust::math::matrix_2d::~matrix_2d ()
Definition at line 171 of file dnamatrix_contiguous.cpp.
{ deallocate(); }
References deallocate().
Member Function Documentation
empty()
bool dynadjust::math::matrix_2d::empty () inline
Definition at line 175 of file dnamatrix_contiguous.hpp.
{ return _buffer == nullptr; }
References _buffer.
get_size()
std::size_t dynadjust::math::matrix_2d::get_size ()
Definition at line 173 of file dnamatrix_contiguous.cpp.
{
    size_t size = (7 * sizeof(index_t));
    switch (_matrixType) {
    case mtx_lower:
        size += sumOfConsecutiveIntegers(_mem_rows) * sizeof(double);
        break;
    case mtx_sparse: break;
    case mtx_full:
    default: size += buffersize(); break;
    }
    return size;
}
References _matrixType, _mem_rows, buffersize(), mtx_full, mtx_lower, mtx_sparse, and sumOfConsecutiveIntegers().
memRows()
index_t dynadjust::math::matrix_2d::memRows () const inline
Definition at line 181 of file dnamatrix_contiguous.hpp.
{ return _mem_rows; }
References _mem_rows.
Referenced by matrix_2d(), multiply(), multiply(), and operator=().
memColumns()
index_t dynadjust::math::matrix_2d::memColumns () const inline
Definition at line 184 of file dnamatrix_contiguous.hpp.
{ return _mem_cols; }
References _mem_cols.
Referenced by matrix_2d(), and operator=().
rows() [1/2]
index_t dynadjust::math::matrix_2d::rows () const inline
Definition at line 187 of file dnamatrix_contiguous.hpp.
{ return _rows; }
References _rows.
Referenced by add(), add(), allocate(), dynadjust::networkadjust::dna_adjust::BackupNormals(), blockadd(), blocksubtract(), blockTadd(), buy(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesCombine(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesReverse(), copybuffer(), copybuffer(), copyelements(), copyelements(), ErrorEllipseParameters(), FormCarttoGeoRotationMatrix_Cluster(), dynadjust::networkadjust::dna_adjust::FormInverseVarianceMatrix(), grow(), matrix_2d(), matrix_2d(), matrix_2d(), multiply(), multiply(), operator=(), dynadjust::networkadjust::dna_adjust::PrintAdjStations(), PropagateVariances_CartLocal_Diagonal(), PropagateVariances_LocalCart(), PropagateVariances_LocalPolar_Diagonal(), redim(), replace(), replace(), ScaleGPSVCV_Cluster(), dynadjust::iostreams::dna_io_snx::serialise_solution_variances(), setsize(), shrink(), submatrix(), submatrix(), transpose(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_D(), dynadjust::networkadjust::dna_adjust::UpdateGeographicCoordsPhased(), and zero().
columns() [1/2]
index_t dynadjust::math::matrix_2d::columns () const inline
Definition at line 190 of file dnamatrix_contiguous.hpp.
{ return _cols; }
References _cols.
Referenced by add(), add(), allocate(), dynadjust::networkadjust::dna_adjust::BackupNormals(), buy(), copybuffer(), copybuffer(), copyelements(), copyelements(), ErrorEllipseParameters(), grow(), matrix_2d(), matrix_2d(), matrix_2d(), multiply(), multiply(), operator=(), PropagateVariances_CartLocal_Diagonal(), PropagateVariances_LocalCart(), PropagateVariances_LocalPolar_Diagonal(), redim(), replace(), replace(), ScaleGPSVCV_Cluster(), setsize(), shrink(), submatrix(), submatrix(), transpose(), and zero().
getbuffer() [1/2]
double * dynadjust::math::matrix_2d::getbuffer () const inline
Definition at line 193 of file dnamatrix_contiguous.hpp.
{ return _buffer; }
References _buffer.
Referenced by copybuffer(), copybuffer(), copyelements(), matrix_2d(), multiply(), multiply(), and WriteMappedFileRegion().
get()
double & dynadjust::math::matrix_2d::get (const index_t & r, const index_t & c) const inline
Definition at line 196 of file dnamatrix_contiguous.hpp.
{
        return DNAMATRIX_ELEMENT(_buffer, _mem_rows, _mem_cols, r, c);
    }
References _buffer, _mem_cols, _mem_rows, and DNAMATRIX_ELEMENT.
Referenced by add(), dynadjust::networkadjust::dna_adjust::AddMsrtoNormalsCoVar2(), dynadjust::networkadjust::dna_adjust::AddMsrtoNormalsCoVar3(), dynadjust::networkadjust::dna_adjust::AddMsrtoNormalsVar(), blockadd(), blocksubtract(), blockTadd(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesCombine(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesReverse(), compute_maximum_value(), dynadjust::networkadjust::dna_adjust::ComputeChiSquare_ABCEHIJKLMPQRSVZ(), dynadjust::networkadjust::dna_adjust::ComputeChiSquare_D(), dynadjust::networkadjust::dna_adjust::ComputeChiSquare_G(), dynadjust::networkadjust::dna_adjust::ComputeChiSquare_XY(), dynadjust::networkadjust::dna_adjust::ComputePrecisionAdjMsrs_A(), dynadjust::networkadjust::dna_adjust::ComputePrecisionAdjMsrs_BCEKLMSVZ(), dynadjust::networkadjust::dna_adjust::ComputePrecisionAdjMsrs_GX(), dynadjust::networkadjust::dna_adjust::ComputePrecisionAdjMsrs_HIJPQR(), dynadjust::networkadjust::dna_adjust::ComputePrecisionAdjMsrs_Y(), dynadjust::networkplot::dna_plot::ComputeStationCorrection(), ErrorEllipseParameters(), filllower(), fillupper(), FormCarttoGeoRotationMatrix_Cluster(), dynadjust::networkadjust::dna_adjust::FormInverseVarianceMatrix(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_D(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_G(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_X(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_Y(), maxvalue(), operator*(), operator<<, dynadjust::networkadjust::dna_adjust::OutputLargestCorrection(), dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), PedalVariance(), dynadjust::measurements::CDnaGpsPoint::PopulateMsr(), Precision_Adjusted_GNSS_bsl(), dynadjust::networkadjust::dna_adjust::PrintAdjGNSSAlternateUnits(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintCorStation(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), PropagateVariances_CartLocal_Diagonal(), PropagateVariances_LocalPolar_Diagonal(), Rotate_CartLocal(), Rotate_LocalPolar(), dynadjust::iostreams::dna_io_snx::serialise_solution_estimates(), dynadjust::iostreams::dna_io_snx::serialise_solution_variances(), SetDirectionsVarianceMatrix(), SetGPSVarianceMatrix(), submatrix(), sweep(), TransformCartesian(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformMeasurement_GX(), dynadjust::referenceframe::dna_reftran::TransformMeasurement_Y(), dynadjust::referenceframe::dna_reftran::TransformStation(), transpose(), transpose(), dynadjust::networkadjust::dna_adjust::UpdateAtVinv(), dynadjust::networkadjust::dna_adjust::UpdateAtVinv_D(), dynadjust::networkadjust::dna_adjust::UpdateDesignMeasMatrices_GX(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_A(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_BK(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_CEM(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_E(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_HR(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_IP(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_JQ(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_L(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_S(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_V(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_Y(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_Z(), dynadjust::networkadjust::dna_adjust::UpdateGeographicCoordsPhased(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_A(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_BK(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_CEM(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_E(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_GX(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_HR(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_IP(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_JQ(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_K(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_L(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_S(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_V(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_Y(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_Z(), dynadjust::networkadjust::dna_adjust::UpdateMsrRecord(), dynadjust::networkadjust::dna_adjust::UpdateNormals_D(), and dynadjust::networkadjust::dna_adjust::UpdateNormals_G().
getbuffer() [2/2]
double * dynadjust::math::matrix_2d::getbuffer (const index_t & r, const index_t & c) const inline
Definition at line 201 of file dnamatrix_contiguous.hpp.
{
        return _buffer + DNAMATRIX_INDEX(_mem_rows, _mem_cols, r, c);
    }
References _buffer, _mem_cols, _mem_rows, and DNAMATRIX_INDEX.
submatrix() [1/2]
void dynadjust::math::matrix_2d::submatrix (const index_t & row_begin, const index_t & col_begin, matrix_2d * dest, const index_t & rows, const index_t & columns) const
Definition at line 360 of file dnamatrix_contiguous.cpp.
{
    if (row_begin >= _rows) {
        std::stringstream ss;
        ss << row_begin << ", " << col_begin << " lies outside matrix range ("
           << _rows << ", " << _cols << ").";
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    if (col_begin >= _cols) {
        std::stringstream ss;
        ss << row_begin << ", " << col_begin << " lies outside matrix range ("
           << _rows << ", " << _cols << ").";
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    if (subrows > dest->rows()) {
        std::stringstream ss;
        ss << subrows << ", " << subcolumns << " exceeds destination matrix ("
           << dest->rows() << ", " << dest->columns() << ").";
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    if (subcolumns > dest->columns()) {
        std::stringstream ss;
        ss << subrows << ", " << subcolumns << " exceeds destination matrix ("
           << dest->rows() << ", " << dest->columns() << ").";
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    if (row_begin + subrows > _rows) {
        std::stringstream ss;
        ss << row_begin + subrows << ", " << col_begin + subcolumns
           << " lies outside matrix range (" << _rows << ", " << _cols << ").";
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    if (col_begin + subcolumns > _cols) {
        std::stringstream ss;
        ss << row_begin + subrows << ", " << col_begin + subcolumns
           << " lies outside matrix range (" << _rows << ", " << _cols << ").";
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    index_t i, j, m(0), n(0), row_end(row_begin + subrows),
        col_end(col_begin + subcolumns);
    for (i = row_begin; i < row_end; ++i) {
        for (j = col_begin; j < col_end; ++j) {
            dest->put(m, n, get(i, j));
            n++;
        }
        n = 0;
        m++;
    }
}
References _cols, _rows, columns(), get(), matrix_2d(), put(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::ComputeChiSquare_XY(), dynadjust::measurements::CDnaGpsPoint::PopulateMsr(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), submatrix(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_X(), dynadjust::networkadjust::dna_adjust::UpdateNormals_X(), and dynadjust::networkadjust::dna_adjust::UpdateNormals_Y().
submatrix() [2/2]
matrix_2d dynadjust::math::matrix_2d::submatrix (const index_t & row_begin, const index_t & col_begin, const index_t & rows, const index_t & columns) const
Definition at line 353 of file dnamatrix_contiguous.cpp.
{
    matrix_2d b(rows, columns);
    submatrix(row_begin, col_begin, &b, rows, columns);
    return b;
}
References columns(), matrix_2d(), rows(), and submatrix().
maxvalue()
double dynadjust::math::matrix_2d::maxvalue () const inline
Definition at line 218 of file dnamatrix_contiguous.hpp.
{ return get(_maxvalRow, _maxvalCol); }
References _maxvalCol, _maxvalRow, and get().
Referenced by dynadjust::networkadjust::dna_adjust::UpdateEstimatesFinal().
maxvalueRow() [1/2]
index_t dynadjust::math::matrix_2d::maxvalueRow () const inline
Definition at line 221 of file dnamatrix_contiguous.hpp.
{ return _maxvalRow; }
References _maxvalRow.
Referenced by matrix_2d(), operator=(), and dynadjust::networkadjust::dna_adjust::OutputLargestCorrection().
maxvalueCol() [1/2]
index_t dynadjust::math::matrix_2d::maxvalueCol () const inline
Definition at line 224 of file dnamatrix_contiguous.hpp.
{ return _maxvalCol; }
References _maxvalCol.
Referenced by matrix_2d(), and operator=().
getelementref() [1/2]
double * dynadjust::math::matrix_2d::getelementref (const index_t & r, const index_t & c) const inline
Definition at line 227 of file dnamatrix_contiguous.hpp.
{
        return &(DNAMATRIX_ELEMENT(_buffer, _mem_rows, _mem_cols, r, c));
    }
References _buffer, _mem_cols, _mem_rows, and DNAMATRIX_ELEMENT.
Referenced by add(), clearlower(), dynadjust::networkplot::dna_plot::ComputeStationCorrection(), copybuffer(), copybuffer(), copyelements(), elementadd(), elementmultiply(), elementsubtract(), matrix_2d(), operator<<, ReadMappedFileRegion(), scale(), sweep(), dynadjust::referenceframe::dna_reftran::TransformMeasurement_Y(), transpose(), WriteMappedFileRegion(), and zero().
getelementref() [2/2]
double * dynadjust::math::matrix_2d::getelementref (const index_t & r, const index_t & c) inline
Definition at line 232 of file dnamatrix_contiguous.hpp.
{
        return &(DNAMATRIX_ELEMENT(_buffer, _mem_rows, _mem_cols, r, c));
    }
References _buffer, _mem_cols, _mem_rows, and DNAMATRIX_ELEMENT.
mem_rows()
void dynadjust::math::matrix_2d::mem_rows (const index_t & r) inline
Definition at line 237 of file dnamatrix_contiguous.hpp.
{ _mem_rows = r; }
References _mem_rows.
mem_columns()
void dynadjust::math::matrix_2d::mem_columns (const index_t & c) inline
Definition at line 240 of file dnamatrix_contiguous.hpp.
{ _mem_cols = c; }
References _mem_cols.
rows() [2/2]
void dynadjust::math::matrix_2d::rows (const index_t & r) inline
Definition at line 243 of file dnamatrix_contiguous.hpp.
{ _rows = r; }
References _rows.
columns() [2/2]
void dynadjust::math::matrix_2d::columns (const index_t & c) inline
Definition at line 246 of file dnamatrix_contiguous.hpp.
{ _cols = c; }
References _cols.
maxvalueRow() [2/2]
void dynadjust::math::matrix_2d::maxvalueRow (const index_t & r) inline
Definition at line 249 of file dnamatrix_contiguous.hpp.
{ _maxvalRow = r; }
References _maxvalRow.
maxvalueCol() [2/2]
void dynadjust::math::matrix_2d::maxvalueCol (const index_t & c) inline
Definition at line 252 of file dnamatrix_contiguous.hpp.
{ _maxvalCol = c; }
References _maxvalCol.
put()
void dynadjust::math::matrix_2d::put (const index_t & r, const index_t & c, const double & val) inline
Definition at line 255 of file dnamatrix_contiguous.hpp.
{
        DNAMATRIX_ELEMENT(_buffer, _mem_rows, _mem_cols, r, c) = val;
    }
References _buffer, _mem_cols, _mem_rows, and DNAMATRIX_ELEMENT.
Referenced by dynadjust::networkadjust::dna_adjust::AddElementtoDesign(), dynadjust::networkadjust::dna_adjust::AddMsrtoMeasMinusComp(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesCombine(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesReverse(), filllower(), fillupper(), FormCarttoGeoRotationMatrix(), dynadjust::networkadjust::dna_adjust::FormConstraintStationVarianceMatrix(), FormHelmertRotationMatrix(), dynadjust::networkadjust::dna_adjust::FormInverseVarianceMatrix(), FormLocaltoCartRotationMatrix(), FormLocaltoPolarRotationMatrix(), GetDirectionsVarianceMatrix(), GetGPSVarianceMatrix(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_D(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_G(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_X(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_Y(), operator*(), dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), Precision_Adjusted_GNSS_bsl(), PropagateVariances_CartLocal_Diagonal(), PropagateVariances_LocalPolar_Diagonal(), dynadjust::networkadjust::dna_adjust::ReduceYLLHMeasurementsforPrinting(), Rotate_CartLocal(), Rotate_LocalPolar(), ScaleGPSVCV(), ScaleGPSVCV_Cluster(), dynadjust::networkadjust::dna_adjust::Solve(), submatrix(), sweep(), TransformCartesian(), transpose(), and dynadjust::networkadjust::dna_adjust::UpdateAtVinv().
matrixType() [1/2]
index_t dynadjust::math::matrix_2d::matrixType () const inline
Definition at line 260 of file dnamatrix_contiguous.hpp.
{ return _matrixType; }
References _matrixType.
Referenced by matrix_2d().
matrixType() [2/2]
void dynadjust::math::matrix_2d::matrixType (const index_t t) inline
Definition at line 263 of file dnamatrix_contiguous.hpp.
{ _matrixType = t; }
References _matrixType.
copyelements() [1/2]
void dynadjust::math::matrix_2d::copyelements (const index_t & row_dest, const index_t & column_dest, const matrix_2d & src, const index_t & row_src, const index_t & column_src, const index_t & rows, const index_t & columns)
Definition at line 515 of file dnamatrix_contiguous.cpp.
{
    index_t cd(0), cs(0), colend_dest(column_dest + columns);
    for (cd = column_dest, cs = column_src; cd < colend_dest; ++cd, ++cs) {
        memcpy(getelementref(row_dest, cd), src.getbuffer(row_src, cs),
               rows * sizeof(double));
    }
}
References columns(), getbuffer(), getelementref(), matrix_2d(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::BackupNormals(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesCombine(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesReverse(), copyelements(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), and dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_Y().
copyelements() [2/2]
void dynadjust::math::matrix_2d::copyelements (const index_t & row_dest, const index_t & column_dest, const matrix_2d * src, const index_t & row_src, const index_t & column_src, const index_t & rows, const index_t & columns)
Definition at line 526 of file dnamatrix_contiguous.cpp.
{
    copyelements(row_dest, column_dest, *src, row_src, column_src, rows,
                 columns);
}
References columns(), copyelements(), matrix_2d(), and rows().
elementadd()
void dynadjust::math::matrix_2d::elementadd (const index_t & r, const index_t & c, const double & inc) inline
Definition at line 282 of file dnamatrix_contiguous.hpp.
{
        *getelementref(r, c) += inc;
    }
References getelementref().
Referenced by dynadjust::networkadjust::dna_adjust::AddMsrtoNormalsCoVar2(), dynadjust::networkadjust::dna_adjust::AddMsrtoNormalsCoVar3(), dynadjust::networkadjust::dna_adjust::AddMsrtoNormalsVar(), blockadd(), blockTadd(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_D(), Precision_Adjusted_GNSS_bsl(), PropagateVariances_CartLocal_Diagonal(), PropagateVariances_LocalPolar_Diagonal(), TransformCartesian(), dynadjust::networkadjust::dna_adjust::UpdateAtVinv_D(), dynadjust::networkadjust::dna_adjust::UpdateNormals_D(), and dynadjust::networkadjust::dna_adjust::UpdateNormals_G().
elementsubtract()
void dynadjust::math::matrix_2d::elementsubtract (const index_t & r, const index_t & c, const double & dec) inline
Definition at line 288 of file dnamatrix_contiguous.hpp.
{
        *getelementref(r, c) -= dec;
    }
References getelementref().
Referenced by blocksubtract().
elementmultiply()
void dynadjust::math::matrix_2d::elementmultiply (const index_t & r, const index_t & c, const double & scale) inline
Definition at line 294 of file dnamatrix_contiguous.hpp.
{
        *getelementref(r, c) *= scale;
    }
References getelementref(), and scale().
Referenced by TransformCartesian().
blockadd()
void dynadjust::math::matrix_2d::blockadd (const index_t & row_dest, const index_t & col_dest, const matrix_2d & mat_src, const index_t & row_src, const index_t & col_src, const index_t & rows, const index_t & cols)
Definition at line 625 of file dnamatrix_contiguous.cpp.
{
    for (index_t i_dest = row_dest, i_src = row_src; i_dest < row_dest + rows;
         ++i_dest, ++i_src) {
        for (index_t j_dest = col_dest, j_src = col_src;
             j_dest < col_dest + cols; ++j_dest, ++j_src) {
            elementadd(i_dest, j_dest, mat_src.get(i_src, j_src));
        }
    }
}
References elementadd(), get(), matrix_2d(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::AddConstraintStationstoNormalsReverse(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesCombine(), dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesReverse(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_X(), dynadjust::networkadjust::dna_adjust::UpdateNormals_X(), and dynadjust::networkadjust::dna_adjust::UpdateNormals_Y().
blockTadd()
void dynadjust::math::matrix_2d::blockTadd (const index_t & row_dest, const index_t & col_dest, const matrix_2d & mat_src, const index_t & row_src, const index_t & col_src, const index_t & rows, const index_t & cols)
Definition at line 638 of file dnamatrix_contiguous.cpp.
{
    for (index_t i_dest = row_dest, i_src = row_src; i_dest < row_dest + rows;
         ++i_dest, ++i_src) {
        for (index_t j_dest = col_dest, j_src = col_src;
             j_dest < col_dest + cols; ++j_dest, ++j_src) {
            elementadd(i_dest, j_dest, mat_src.get(j_src, i_src));
        }
    }
}
References elementadd(), get(), matrix_2d(), and rows().
blocksubtract()
void dynadjust::math::matrix_2d::blocksubtract (const index_t & row_dest, const index_t & col_dest, const matrix_2d & mat_src, const index_t & row_src, const index_t & col_src, const index_t & rows, const index_t & cols)
Definition at line 651 of file dnamatrix_contiguous.cpp.
{
    for (index_t i_dest = row_dest, i_src = row_src; i_dest < row_dest + rows;
         ++i_dest, ++i_src) {
        for (index_t j_dest = col_dest, j_src = col_src;
             j_dest < col_dest + cols; ++j_dest, ++j_src) {
            elementsubtract(i_dest, j_dest, mat_src.get(i_src, j_src));
        }
    }
}
References elementsubtract(), get(), matrix_2d(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::AddConstraintStationstoNormalsCombine().
add() [1/2]
matrix_2d dynadjust::math::matrix_2d::add (const matrix_2d & rhs)
Definition at line 729 of file dnamatrix_contiguous.cpp.
{
    if (_rows != rhs.rows() || _cols != rhs.columns()) {
        throw boost::enable_current_exception(
            std::runtime_error("add(): Dimensions are incompatible."));
    }
    for (index_t row = 0; row < _rows; row++) {
        for (index_t column = 0; column < _cols; ++column) {
            *getelementref(row, column) += rhs.get(row, column);
        }
    }
    return *this;
}
References _cols, _rows, columns(), get(), getelementref(), matrix_2d(), and rows().
Referenced by add(), dynadjust::networkadjust::dna_adjust::UpdateEstimatesCombine(), and dynadjust::networkadjust::dna_adjust::UpdateEstimatesReverse().
add() [2/2]
matrix_2d dynadjust::math::matrix_2d::add (const matrix_2d & lhs, const matrix_2d & rhs)
Definition at line 742 of file dnamatrix_contiguous.cpp.
{
    if (lhs.rows() != rhs.rows() || lhs.columns() != rhs.columns()) {
        throw boost::enable_current_exception(
            std::runtime_error("add(): Dimensions are incompatible."));
    }
    *this = lhs;
    return add(rhs);
}
References add(), columns(), matrix_2d(), and rows().
multiply() [1/2]
matrix_2d dynadjust::math::matrix_2d::multiply (const char * lhs_trans, const matrix_2d & rhs, const char * rhs_trans)
Definition at line 751 of file dnamatrix_contiguous.cpp.
{
    matrix_2d m(_rows, rhs.columns());
    lapack_int lhs_rows = static_cast<lapack_int>(rows());
    lapack_int rhs_cols = static_cast<lapack_int>(rhs.columns());
    lapack_int lhs_cols = static_cast<lapack_int>(columns());
    lapack_int rhs_rows = static_cast<lapack_int>(rhs.rows());
    CBLAS_TRANSPOSE tA =
        (strcmp(lhs_trans, "T") == 0) ? CblasTrans : CblasNoTrans;
    CBLAS_TRANSPOSE tB =
        (strcmp(rhs_trans, "T") == 0) ? CblasTrans : CblasNoTrans;
    if (tA == CblasTrans) {
        lhs_rows = columns();
        lhs_cols = rows();
    }
    if (tB == CblasTrans) {
        rhs_rows = rhs.columns();
        rhs_cols = rhs.rows();
    }
    if (lhs_cols != rhs_rows) {
        throw boost::enable_current_exception(std::runtime_error(
            "multiply(): Incompatible matrix dimensions."));
    }
    if (m.rows() != (index_t)lhs_rows || m.columns() != (index_t)rhs_cols) {
        throw boost::enable_current_exception(std::runtime_error(
            "multiply(): Result matrix dimensions mismatch."));
    }
    cblas_dgemm(CblasColMajor, tA, tB, lhs_rows, rhs_cols, lhs_cols, 1.0,
                _buffer, _mem_rows, rhs.getbuffer(), rhs.memRows(), 0.0,
                m.getbuffer(), m.memRows());
    // return (*this = m); // Benchmarking shows this is slower
    return m;
}
References _buffer, _mem_rows, _rows, columns(), getbuffer(), matrix_2d(), memRows(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::ComputeChiSquare_XY(), PropagateVariances_CartLocal_Diagonal(), PropagateVariances_LocalCart(), PropagateVariances_LocalPolar_Diagonal(), Prpagate_Variances_Geo_Cart(), Rotate_LocalCart(), ScaleMatrix(), dynadjust::networkadjust::dna_adjust::Solve(), dynadjust::networkadjust::dna_adjust::SolveMT(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_X(), and dynadjust::networkadjust::dna_adjust::UpdateNormals_X().
multiply() [2/2]
matrix_2d dynadjust::math::matrix_2d::multiply (const matrix_2d & lhs, const char * lhs_trans, const matrix_2d & rhs, const char * rhs_trans)
Definition at line 789 of file dnamatrix_contiguous.cpp.
{
    lapack_int lhs_rows = static_cast<lapack_int>(lhs.rows());
    lapack_int rhs_cols = static_cast<lapack_int>(rhs.columns());
    lapack_int lhs_cols = static_cast<lapack_int>(lhs.columns());
    lapack_int rhs_rows = static_cast<lapack_int>(rhs.rows());
    CBLAS_TRANSPOSE tA =
        (strncmp(lhs_trans, "T", 1) == 0) ? CblasTrans : CblasNoTrans;
    CBLAS_TRANSPOSE tB =
        (strncmp(rhs_trans, "T", 1) == 0) ? CblasTrans : CblasNoTrans;
    if (tA == CblasTrans) {
        lhs_rows = lhs.columns();
        lhs_cols = lhs.rows();
    }
    if (tB == CblasTrans) {
        rhs_rows = rhs.columns();
        rhs_cols = rhs.rows();
    }
    if (lhs_cols != rhs_rows) {
        throw boost::enable_current_exception(std::runtime_error(
            "multiply(): Incompatible matrix dimensions."));
    }
    if (_rows != (index_t)lhs_rows || _cols != (index_t)rhs_cols) {
        throw boost::enable_current_exception(std::runtime_error(
            "multiply(): Result matrix dimensions mismatch."));
    }
    cblas_dgemm(CblasColMajor, tA, tB, lhs_rows, rhs_cols, lhs_cols, 1.0,
                lhs.getbuffer(), lhs.memRows(), rhs.getbuffer(), rhs.memRows(),
                0.0, _buffer, _mem_rows);
    return *this;
}
References _buffer, _cols, _mem_rows, _rows, columns(), getbuffer(), matrix_2d(), memRows(), and rows().
sweepinverse()
matrix_2d dynadjust::math::matrix_2d::sweepinverse ()
Definition at line 573 of file dnamatrix_contiguous.cpp.
{
    if (_rows != _cols) {
        throw boost::enable_current_exception(
            std::runtime_error("sweepinverse(): Matrix is not square."));
    }
    sweep(0, _rows);
    return *this;
}
References _cols, _rows, matrix_2d(), and sweep().
Referenced by Prpagate_Variances_Geo_Cart().
cholesky_inverse()
matrix_2d dynadjust::math::matrix_2d::cholesky_inverse (bool LOWER_IS_CLEARED = false)
Definition at line 582 of file dnamatrix_contiguous.cpp.
{
    if (_rows < 1)
        return *this;
    if (_rows != _cols) {
        throw boost::enable_current_exception(
            std::runtime_error("cholesky_inverse(): Matrix is not square."));
    }
    char uplo = LOWER_IS_CLEARED ? 'U' : 'L';
    lapack_int info(0);
    lapack_int n = static_cast<lapack_int>(_rows);
    info = LAPACKE_dpotrf(LAPACK_COL_MAJOR, uplo, n, _buffer, n);
    if (info != 0) {
        throw boost::enable_current_exception(std::runtime_error(
            "cholesky_inverse(): Cholesky factorisation failed."));
    }
    info = LAPACKE_dpotri(LAPACK_COL_MAJOR, uplo, n, _buffer, n);
    if (info != 0) {
        throw boost::enable_current_exception(std::runtime_error(
            "cholesky_inverse(): Cholesky inversion failed."));
    }
    if (LOWER_IS_CLEARED)
        filllower();
    else
        fillupper();
    return *this;
}
References _buffer, _cols, _rows, filllower(), fillupper(), and matrix_2d().
Referenced by dynadjust::networkadjust::dna_adjust::FormInverseVarianceMatrix().
transpose() [1/2]
matrix_2d dynadjust::math::matrix_2d::transpose (const matrix_2d & matA)
Definition at line 825 of file dnamatrix_contiguous.cpp.
{
    if ((matA.columns() != _rows) || (matA.rows() != _cols)) {
        throw boost::enable_current_exception(
            std::runtime_error("transpose(): Dimensions incompatible."));
    }
    for (index_t row = 0; row < _rows; row++) {
        for (index_t column = 0; column < _cols; column++) {
            *getelementref(row, column) = matA.get(column, row);
        }
    }
    return *this;
}
References _cols, _rows, columns(), get(), getelementref(), matrix_2d(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::ComputeChiSquare_XY(), PropagateVariances_LocalCart(), and PropagateVariances_LocalPolar_Diagonal().
transpose() [2/2]
matrix_2d dynadjust::math::matrix_2d::transpose ()
Definition at line 838 of file dnamatrix_contiguous.cpp.
{
    matrix_2d m(_cols, _rows);
    for (index_t row = 0; row < _rows; row++) {
        for (index_t column = 0; column < _cols; column++) {
            m.put(column, row, get(row, column));
        }
    }
    return m;
}
References _cols, _rows, get(), matrix_2d(), and put().
scale()
matrix_2d dynadjust::math::matrix_2d::scale (const double & scalar)
Definition at line 616 of file dnamatrix_contiguous.cpp.
{
    for (index_t i = 0; i < _rows; ++i) {
        for (index_t j = 0; j < _cols; ++j) {
            *getelementref(i, j) *= scalar;
        }
    }
    return *this;
}
References _cols, _rows, getelementref(), and matrix_2d().
Referenced by elementmultiply(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_Y(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_X(), and dynadjust::networkadjust::dna_adjust::UpdateNormals_X().
operator==()
bool dynadjust::math::matrix_2d::operator== (const matrix_2d & rhs) const inline
Definition at line 376 of file dnamatrix_contiguous.hpp.
{
        if (_mem_cols != rhs._mem_cols)
            return false;
        if (_mem_rows != rhs._mem_rows)
            return false;
        if (_cols != rhs._cols)
            return false;
        if (_rows != rhs._rows)
            return false;
        if (*_buffer != *rhs._buffer)
            return false;
        if (_maxvalCol != rhs._maxvalCol)
            return false;
        if (_maxvalRow != rhs._maxvalRow)
            return false;
        if (_matrixType != rhs._matrixType)
            return false;
        return true;
    }
References _buffer, _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, and matrix_2d().
operator!=()
bool dynadjust::math::matrix_2d::operator!= (const matrix_2d & rhs) const inline
Definition at line 397 of file dnamatrix_contiguous.hpp.
{
        if (_mem_cols == rhs._mem_cols)
            return false;
        if (_mem_rows == rhs._mem_rows)
            return false;
        if (_cols == rhs._cols)
            return false;
        if (_rows == rhs._rows)
            return false;
        if (*_buffer == *rhs._buffer)
            return false;
        if (_maxvalCol == rhs._maxvalCol)
            return false;
        if (_maxvalRow == rhs._maxvalRow)
            return false;
        if (_matrixType == rhs._matrixType)
            return false;
        return true;
    }
References _buffer, _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, and matrix_2d().
operator=()
matrix_2d dynadjust::math::matrix_2d::operator= (const matrix_2d & rhs)
Definition at line 695 of file dnamatrix_contiguous.cpp.
{
    if (this == &rhs) {
        return *this;
    }
    if (_mem_rows >= rhs.rows() && _mem_cols >= rhs.columns()) {
        _rows = rhs.rows();
        _cols = rhs.columns();
        copybuffer(_rows, _cols, rhs);
        _maxvalCol = rhs.maxvalueCol();
        _maxvalRow = rhs.maxvalueRow();
        return *this;
    }
    deallocate();
    _mem_rows = rhs.memRows();
    _mem_cols = rhs.memColumns();
    _rows = rhs.rows();
    _cols = rhs.columns();
    allocate(_mem_rows, _mem_cols);
    copybuffer(_rows, _cols, rhs);
    _maxvalCol = rhs.maxvalueCol();
    _maxvalRow = rhs.maxvalueRow();
    return *this;
}
References _cols, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, allocate(), columns(), copybuffer(), deallocate(), matrix_2d(), maxvalueCol(), maxvalueRow(), memColumns(), memRows(), and rows().
operator*()
matrix_2d dynadjust::math::matrix_2d::operator* (const double & rhs) const
Definition at line 719 of file dnamatrix_contiguous.cpp.
{
    matrix_2d m(_rows, _cols);
    for (index_t row = 0; row < _rows; row++) {
        for (index_t column = 0; column < _cols; ++column) {
            m.put(row, column, get(row, column) * rhs);
        }
    }
    return m;
}
References _cols, _rows, get(), matrix_2d(), and put().
allocate() [1/2]
void dynadjust::math::matrix_2d::allocate ()
Definition at line 324 of file dnamatrix_contiguous.cpp.
{ allocate(_mem_rows, _mem_cols); }
References _mem_cols, _mem_rows, and allocate().
Referenced by allocate(), matrix_2d(), matrix_2d(), matrix_2d(), operator=(), ReadMappedFileRegion(), and redim().
allocate() [2/2]
void dynadjust::math::matrix_2d::allocate (const index_t & rows, const index_t & columns)
Definition at line 326 of file dnamatrix_contiguous.cpp.
{
    deallocate();
    buy(rows, columns, &_buffer);
}
References _buffer, buy(), columns(), deallocate(), and rows().
setsize()
void dynadjust::math::matrix_2d::setsize (const index_t & rows, const index_t & columns)
Definition at line 462 of file dnamatrix_contiguous.cpp.
{
    deallocate();
    _rows = _mem_rows = rows;
    _cols = _mem_cols = columns;
}
References _cols, _mem_cols, _mem_rows, _rows, columns(), deallocate(), and rows().
redim()
void dynadjust::math::matrix_2d::redim (const index_t & rows, const index_t & columns)
Definition at line 412 of file dnamatrix_contiguous.cpp.
{
    if (rows <= _mem_rows && columns <= _mem_cols) {
        _rows = rows;
        _cols = columns;
        return;
    }
    std::set_new_handler(out_of_memory_handler);
    deallocate();
    allocate(rows, columns);
    _rows = _mem_rows = rows;
    _cols = _mem_cols = columns;
}
References _cols, _mem_cols, _mem_rows, _rows, allocate(), columns(), deallocate(), dynadjust::math::out_of_memory_handler(), and rows().
Referenced by FormCarttoGeoRotationMatrix(), FormCarttoGeoRotationMatrix_Cluster(), FormHelmertRotationMatrix(), FormLocaltoCartRotationMatrix(), FormLocaltoPolarRotationMatrix(), GetDirectionsVarianceMatrix(), GetGPSVarianceMatrix(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_D(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_G(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_X(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_Y(), PropagateVariances_CartLocal_Diagonal(), PropagateVariances_LocalPolar_Diagonal(), Rotate_CartLocal(), Rotate_LocalCart(), Rotate_LocalPolar(), and Transform_7parameter().
replace() [1/2]
void dynadjust::math::matrix_2d::replace (const index_t & rowstart, const index_t & columnstart, const matrix_2d & newmat)
Definition at line 468 of file dnamatrix_contiguous.cpp.
{
    copybuffer(rowstart, columnstart, newmat.rows(), newmat.columns(), newmat);
}
References columns(), copybuffer(), matrix_2d(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_G().
replace() [2/2]
void dynadjust::math::matrix_2d::replace (const index_t & rowstart, const index_t & columnstart, const index_t & rows, const index_t & columns, const matrix_2d & newmat)
Definition at line 473 of file dnamatrix_contiguous.cpp.
{
    copybuffer(rowstart, columnstart, rows, columns, newmat);
}
References columns(), copybuffer(), matrix_2d(), and rows().
shrink()
void dynadjust::math::matrix_2d::shrink (const index_t & rows, const index_t & columns)
Definition at line 425 of file dnamatrix_contiguous.cpp.
{
    if (rows > _rows || columns > _cols) {
        std::stringstream ss;
        ss << " " << std::endl;
        if (rows >= _rows) {
            ss << "    Cannot shrink by " << rows << " rows on matrix of "
               << _rows << " rows. " << std::endl;
        }
        if (columns >= _cols) {
            ss << "    Cannot shrink by " << columns << " columns on matrix of "
               << _cols << " columns.";
        }
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    _rows -= rows;
    _cols -= columns;
}
References _cols, _rows, columns(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::UpdateEstimatesCombine(), and dynadjust::networkadjust::dna_adjust::UpdateEstimatesFinal().
grow()
void dynadjust::math::matrix_2d::grow (const index_t & rows, const index_t & columns)
Definition at line 443 of file dnamatrix_contiguous.cpp.
{
    if ((rows + _rows) > _mem_rows || (columns + _cols) > _mem_cols) {
        std::stringstream ss;
        ss << " " << std::endl;
        if (rows >= _rows) {
            ss << "    Cannot grow matrix by " << rows
               << " rows: exceeds row memory limit (" << _mem_rows << ").";
        }
        if (columns >= _cols) {
            ss << "    Cannot grow matrix by " << columns
               << " columns: exceeds column memory limit (" << _mem_cols
               << ").";
        }
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    _rows += rows;
    _cols += columns;
}
References _cols, _mem_cols, _mem_rows, _rows, columns(), and rows().
Referenced by dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesCombine(), and dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesReverse().
clearlower()
void dynadjust::math::matrix_2d::clearlower ()
Definition at line 664 of file dnamatrix_contiguous.cpp.
{
    for (index_t col = 0, row = 1; col < _mem_cols; ++col, ++row) {
        memset(getelementref(row, col), 0, (_mem_rows - row) * sizeof(double));
    }
}
References _mem_cols, _mem_rows, and getelementref().
filllower()
void dynadjust::math::matrix_2d::filllower ()
Definition at line 670 of file dnamatrix_contiguous.cpp.
{
    for (index_t row = 1; row < _rows; row++) {
        for (index_t column = 0; column < row; column++) {
            put(row, column, get(column, row));
        }
    }
}
References _rows, get(), and put().
Referenced by cholesky_inverse(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_G(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_X(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_Y(), Precision_Adjusted_GNSS_bsl(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), and dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_YLLH().
fillupper()
void dynadjust::math::matrix_2d::fillupper ()
Definition at line 678 of file dnamatrix_contiguous.cpp.
{
    for (index_t row = 1; row < _rows; row++) {
        for (index_t column = 0; column < row; column++) {
            put(column, row, get(row, column));
        }
    }
}
References _rows, get(), and put().
Referenced by cholesky_inverse(), matrix_2d(), dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), dynadjust::networkadjust::dna_adjust::PrintAdjGNSSAlternateUnits(), and ReadMappedFileRegion().
zero() [1/2]
void dynadjust::math::matrix_2d::zero ()
Definition at line 686 of file dnamatrix_contiguous.cpp.
{ memset(_buffer, 0, buffersize()); }
References _buffer, and buffersize().
Referenced by dynadjust::networkadjust::dna_adjust::CarryStnEstimatesandVariancesReverse(), GetDirectionsVarianceMatrix(), GetGPSVarianceMatrix(), dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_D(), Precision_Adjusted_GNSS_bsl(), and dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_D().
zero() [2/2]
void dynadjust::math::matrix_2d::zero (const index_t & row_begin, const index_t & col_begin, const index_t & rows, const index_t & columns)
Definition at line 688 of file dnamatrix_contiguous.cpp.
{
    for (index_t col = col_begin; col < col_begin + columns; ++col) {
        memset(getelementref(row_begin, col), 0, rows * sizeof(double));
    }
}
References columns(), getelementref(), and rows().
compute_maximum_value()
double dynadjust::math::matrix_2d::compute_maximum_value ()
Definition at line 848 of file dnamatrix_contiguous.cpp.
{
    _maxvalCol = _maxvalRow = 0;
    for (index_t row = 0; row < _rows; ++row) {
        for (index_t col = 0; col < _cols; col++) {
            if (std::fabs(get(row, col)) >
                std::fabs(get(_maxvalRow, _maxvalCol))) {
                _maxvalCol = col;
                _maxvalRow = row;
            }
        }
    }
    return get(_maxvalRow, _maxvalCol);
}
References _cols, _maxvalCol, _maxvalRow, _rows, and get().
Referenced by dynadjust::networkadjust::dna_adjust::OutputLargestCorrection(), and dynadjust::networkadjust::dna_adjust::UpdateEstimatesFinal().
ReadMappedFileRegion()
void dynadjust::math::matrix_2d::ReadMappedFileRegion (void * addr)
Definition at line 186 of file dnamatrix_contiguous.cpp.
{
    index_t* data_U = reinterpret_cast<index_t*>(addr);
    _matrixType = *data_U++;
    _rows = *data_U++;
    _cols = *data_U++;
    switch (_matrixType) {
    case mtx_sparse:
        _mem_rows = _rows;
        _mem_cols = _cols;
        break;
    case mtx_lower:
    case mtx_full:
    default:
        _mem_rows = *data_U++;
        _mem_cols = *data_U++;
        break;
    }
    allocate(_mem_rows, _mem_cols);
    double* data_d;
    int* data_i;
    index_t c, r, i;
    int ci;
    switch (_matrixType) {
    case mtx_sparse:
        data_i = reinterpret_cast<int*>(data_U);
        for (r = 0; r < _rows; ++r) {
            for (i = 0; i < 3; ++i) {
                ci = *data_i++;
                data_d = reinterpret_cast<double*>(data_i);
                if (ci < 0) {
                    data_d += 3;
                    data_i = reinterpret_cast<int*>(data_d);
                    continue;
                }
                memcpy(getelementref(r, ci), data_d, sizeof(double));
                data_d++;
                memcpy(getelementref(r, ci + 1), data_d, sizeof(double));
                data_d++;
                memcpy(getelementref(r, ci + 2), data_d, sizeof(double));
                data_d++;
                data_i = reinterpret_cast<int*>(data_d);
            }
        }
        return;
        break;
    case mtx_lower:
        data_d = reinterpret_cast<double*>(data_U);
        for (c = 0; c < _mem_cols; ++c) {
            memcpy(getelementref(c, c), data_d,
                   (_mem_rows - c) * sizeof(double));
            data_d += (_mem_rows - c);
        }
        fillupper();
        break;
    case mtx_full:
    default:
        data_d = reinterpret_cast<double*>(data_U);
        memcpy(_buffer, data_d, buffersize());
        data_d += _mem_rows * _mem_cols;
        break;
    }
    data_U = reinterpret_cast<index_t*>(data_d);
    _maxvalRow = *data_U++;
    _maxvalCol = *data_U;
}
References _buffer, _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, allocate(), buffersize(), fillupper(), getelementref(), mtx_full, mtx_lower, and mtx_sparse.
WriteMappedFileRegion()
void dynadjust::math::matrix_2d::WriteMappedFileRegion (void * addr)
Definition at line 258 of file dnamatrix_contiguous.cpp.
{
    index_t* data_U = reinterpret_cast<index_t*>(addr);
    *data_U++ = _matrixType;
    *data_U++ = _rows;
    *data_U++ = _cols;
    switch (_matrixType) {
    case mtx_sparse: break;
    case mtx_lower:
    case mtx_full:
    default:
        *data_U++ = _mem_rows;
        *data_U++ = _mem_cols;
        break;
    }
    double* data_d;
    int* data_i;
    index_t c, r, i;
    int ci;
    switch (_matrixType) {
    case mtx_sparse:
        data_i = reinterpret_cast<int*>(data_U);
        for (r = 0; r < _rows; ++r) {
            for (i = 0; i < 3; ++i) {
                ci = *data_i++;
                data_d = reinterpret_cast<double*>(data_i);
                if (ci < 0) {
                    data_d += 3;
                    data_i = reinterpret_cast<int*>(data_d);
                    continue;
                }
                memcpy(data_d, getelementref(r, ci), sizeof(double));
                data_d++;
                memcpy(data_d, getelementref(r, ci + 1), sizeof(double));
                data_d++;
                memcpy(data_d, getelementref(r, ci + 2), sizeof(double));
                data_d++;
                data_i = reinterpret_cast<int*>(data_d);
            }
        }
        return;
        break;
    case mtx_lower:
        data_d = reinterpret_cast<double*>(data_U);
        for (c = 0; c < _mem_cols; ++c) {
            memcpy(data_d, getbuffer(c, c), (_mem_rows - c) * sizeof(double));
            data_d += (_mem_rows - c);
        }
        break;
    case mtx_full:
    default:
        data_d = reinterpret_cast<double*>(data_U);
        memcpy(data_d, _buffer, _mem_rows * _mem_cols * sizeof(double));
        data_d += _mem_rows * _mem_cols;
        break;
    }
    data_U = reinterpret_cast<index_t*>(data_d);
    *data_U++ = _maxvalRow;
    *data_U = _maxvalCol;
}
References _buffer, _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, getbuffer(), getelementref(), mtx_full, mtx_lower, and mtx_sparse.
buffersize()
std::size_t dynadjust::math::matrix_2d::buffersize () const inline private
Definition at line 503 of file dnamatrix_contiguous.hpp.
{
        return _mem_rows * _mem_cols * sizeof(double);
    }
References _mem_cols, and _mem_rows.
Referenced by copybuffer(), get_size(), matrix_2d(), ReadMappedFileRegion(), and zero().
deallocate()
void dynadjust::math::matrix_2d::deallocate () private
Definition at line 345 of file dnamatrix_contiguous.cpp.
{
    if (_buffer != NULL) {
        delete[] _buffer;
        _buffer = 0;
    }
}
References _buffer.
Referenced by allocate(), operator=(), redim(), setsize(), and ~matrix_2d().
buy()
void dynadjust::math::matrix_2d::buy (const index_t & rows, const index_t & columns, double ** mem_space) private
Definition at line 331 of file dnamatrix_contiguous.cpp.
{
    __row__ = rows;
    __col__ = columns;
    (*mem_space) = new double[rows * columns];
    if ((*mem_space) == NULL) {
        std::stringstream ss;
        ss << "Insufficient memory for a " << rows << " x " << columns
           << " matrix.";
        throw boost::enable_current_exception(NetMemoryException(ss.str()));
    }
    memset(*mem_space, 0, byteSize<double>(rows * columns));
}
References dynadjust::math::__col__, dynadjust::math::__row__, dynadjust::math::byteSize(), columns(), and rows().
Referenced by allocate().
copybuffer() [1/2]
void dynadjust::math::matrix_2d::copybuffer (const index_t & rows, const index_t & columns, const matrix_2d & oldmat) private
Definition at line 479 of file dnamatrix_contiguous.cpp.
{
    if (rows == _mem_rows && columns == _mem_cols) {
        memcpy(_buffer, oldmat.getbuffer(), buffersize());
        return;
    }
    for (index_t column = 0; column < columns; column++) {
        memcpy(getelementref(0, column), oldmat.getbuffer(0, column),
               rows * sizeof(double));
    }
}
References _buffer, _mem_cols, _mem_rows, buffersize(), columns(), getbuffer(), getelementref(), matrix_2d(), and rows().
Referenced by operator=(), replace(), and replace().
copybuffer() [2/2]
void dynadjust::math::matrix_2d::copybuffer (const index_t & rowstart, const index_t & columnstart, const index_t & rows, const index_t & columns, const matrix_2d & mat) private
Definition at line 491 of file dnamatrix_contiguous.cpp.
{
    index_t rowend(rowstart + rows), columnend(columnstart + columns);
    if (rowend > _rows || columnend > _cols) {
        std::stringstream ss;
        ss << " " << std::endl;
        if (rowend >= _rows) {
            ss << "    Row index " << rowend << " exceeds matrix row count ("
               << _rows << "). " << std::endl;
        }
        if (columnend >= _cols) {
            ss << "    Column index " << columnend
               << " exceeds matrix column count (" << _cols << ").";
        }
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    index_t column(0), c(0);
    for (column = columnstart; column < columnend; ++column, ++c) {
        memcpy(getelementref(rowstart, column), mat.getbuffer(0, c),
               rows * sizeof(double));
    }
}
References _cols, _rows, columns(), getbuffer(), getelementref(), matrix_2d(), and rows().
sweep()
void dynadjust::math::matrix_2d::sweep (index_t k1, index_t k2) private
Definition at line 534 of file dnamatrix_contiguous.cpp.
{
    double eps(1.0e-8), d;
    if (k2 < k1) {
        index_t k = k1;
        k1 = k2;
        k2 = k;
    }
    for (index_t k = k1; k < k2; k++) {
        if (fabs(get(k, k)) < eps) {
            for (index_t it = 0; it < _rows; it++) {
                put(it, k, 0.);
                put(k, it, 0.);
            }
        } else {
            d = 1.0 / get(k, k);
            put(k, k, d);
            for (index_t i = 0; i < _rows; i++) {
                if (i != k) {
                    *getelementref(i, k) *= -d;
                }
            }
            for (index_t j = 0; j < _rows; j++) {
                if (j != k) {
                    *getelementref(k, j) *= d;
                }
            }
            for (index_t i = 0; i < _rows; i++) {
                if (i != k) {
                    for (index_t j = 0; j < _rows; j++) {
                        if (j != k) {
                            *getelementref(i, j) += get(i, k) * get(k, j) / d;
                        }
                    }
                }
            }
        }
    }
}
References _rows, get(), getelementref(), and put().
Referenced by sweepinverse().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const matrix_2d & rhs) friend
Definition at line 32 of file dnamatrix_contiguous.cpp.
{
    if (os.iword(0) == binary) {
        os.write(reinterpret_cast<const char*>(&rhs._matrixType),
                 sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._rows), sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._cols), sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._mem_rows),
                 sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._mem_cols),
                 sizeof(index_t));
        index_t c, r;
        switch (rhs._matrixType) {
        case mtx_lower:
            if (rhs._mem_rows != rhs._mem_cols) {
                throw boost::enable_current_exception(std::runtime_error(
                    "matrix_2d operator<< (): Matrix not square."));
            }
            for (c = 0; c < rhs._mem_cols; ++c) {
                os.write(reinterpret_cast<const char*>(rhs.getelementref(c, c)),
                         (rhs._mem_rows - c) * sizeof(double));
            }
            break;
        case mtx_sparse: break;
        case mtx_full:
        default:
            for (r = 0; r < rhs._mem_rows; ++r) {
                for (c = 0; c < rhs._mem_cols; ++c) {
                    os.write(
                        reinterpret_cast<const char*>(rhs.getelementref(r, c)),
                        sizeof(double));
                }
            }
            break;
        }
        os.write(reinterpret_cast<const char*>(&rhs._maxvalRow),
                 sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._maxvalCol),
                 sizeof(index_t));
    } else {
        os << rhs._matrixType << " " << rhs._rows << " " << rhs._cols << " "
           << rhs._mem_rows << " " << rhs._mem_cols << std::endl;
        for (index_t r = 0; r < rhs._mem_rows; ++r) {
            for (index_t c = 0; c < rhs._mem_cols; ++c) {
                os << std::scientific << std::setprecision(16) << rhs.get(r, c)
                   << " ";
            }
            os << std::endl;
        }
        os << rhs._maxvalRow << " " << rhs._maxvalCol << std::endl;
        os << std::endl;
    }
    return os;
}
References _cols, _matrixType, _maxvalCol, _maxvalRow, _mem_cols, _mem_rows, _rows, binary, get(), getelementref(), matrix_2d(), mtx_full, mtx_lower, and mtx_sparse.
Member Data Documentation
_cols
index_t dynadjust::math::matrix_2d::_cols private
Definition at line 525 of file dnamatrix_contiguous.hpp.
Referenced by add(), cholesky_inverse(), columns(), columns(), compute_maximum_value(), copybuffer(), grow(), matrix_2d(), matrix_2d(), matrix_2d(), matrix_2d(), multiply(), operator!=(), operator*(), operator<<, operator=(), operator==(), ReadMappedFileRegion(), redim(), scale(), setsize(), shrink(), submatrix(), sweepinverse(), transpose(), transpose(), and WriteMappedFileRegion().
_rows
index_t dynadjust::math::matrix_2d::_rows private
Definition at line 526 of file dnamatrix_contiguous.hpp.
Referenced by add(), cholesky_inverse(), compute_maximum_value(), copybuffer(), filllower(), fillupper(), grow(), matrix_2d(), matrix_2d(), matrix_2d(), matrix_2d(), multiply(), multiply(), operator!=(), operator*(), operator<<, operator=(), operator==(), ReadMappedFileRegion(), redim(), rows(), rows(), scale(), setsize(), shrink(), submatrix(), sweep(), sweepinverse(), transpose(), transpose(), and WriteMappedFileRegion().
_mem_cols
index_t dynadjust::math::matrix_2d::_mem_cols private
Definition at line 527 of file dnamatrix_contiguous.hpp.
Referenced by allocate(), buffersize(), clearlower(), copybuffer(), get(), getbuffer(), getelementref(), getelementref(), grow(), matrix_2d(), matrix_2d(), matrix_2d(), matrix_2d(), mem_columns(), memColumns(), operator!=(), operator<<, operator=(), operator==(), put(), ReadMappedFileRegion(), redim(), setsize(), and WriteMappedFileRegion().
_mem_rows
index_t dynadjust::math::matrix_2d::_mem_rows private
Definition at line 528 of file dnamatrix_contiguous.hpp.
Referenced by allocate(), buffersize(), clearlower(), copybuffer(), get(), get_size(), getbuffer(), getelementref(), getelementref(), grow(), matrix_2d(), matrix_2d(), matrix_2d(), matrix_2d(), mem_rows(), memRows(), multiply(), multiply(), operator!=(), operator<<, operator=(), operator==(), put(), ReadMappedFileRegion(), redim(), setsize(), and WriteMappedFileRegion().
_maxvalCol
index_t dynadjust::math::matrix_2d::_maxvalCol private
Definition at line 529 of file dnamatrix_contiguous.hpp.
Referenced by compute_maximum_value(), matrix_2d(), matrix_2d(), matrix_2d(), matrix_2d(), maxvalue(), maxvalueCol(), maxvalueCol(), operator!=(), operator<<, operator=(), operator==(), ReadMappedFileRegion(), and WriteMappedFileRegion().
_maxvalRow
index_t dynadjust::math::matrix_2d::_maxvalRow private
Definition at line 530 of file dnamatrix_contiguous.hpp.
Referenced by compute_maximum_value(), matrix_2d(), matrix_2d(), matrix_2d(), matrix_2d(), maxvalue(), maxvalueRow(), maxvalueRow(), operator!=(), operator<<, operator=(), operator==(), ReadMappedFileRegion(), and WriteMappedFileRegion().
_matrixType
index_t dynadjust::math::matrix_2d::_matrixType private
Definition at line 531 of file dnamatrix_contiguous.hpp.
Referenced by get_size(), matrix_2d(), matrix_2d(), matrix_2d(), matrix_2d(), matrixType(), matrixType(), operator!=(), operator<<, operator==(), ReadMappedFileRegion(), and WriteMappedFileRegion().
_buffer
double* dynadjust::math::matrix_2d::_buffer = nullptr private
Definition at line 532 of file dnamatrix_contiguous.hpp.
Referenced by allocate(), cholesky_inverse(), copybuffer(), deallocate(), empty(), get(), getbuffer(), getbuffer(), getelementref(), getelementref(), matrix_2d(), matrix_2d(), matrix_2d(), matrix_2d(), multiply(), multiply(), operator!=(), operator==(), put(), ReadMappedFileRegion(), WriteMappedFileRegion(), and zero().
The documentation for this class was generated from the following files:
include/math/dnamatrix_contiguous.hpp
include/math/dnamatrix_contiguous.cpp