DynAdjust: dynadjust::measurements::CDnaGpsPointCluster Class Reference
dynadjust::measurements::CDnaGpsPointCluster Class Reference
#include <dnagpspoint.hpp>
Public Member Functions
CDnaGpsPointCluster (void)
virtual ~CDnaGpsPointCluster (void)
CDnaGpsPointCluster (CDnaGpsPointCluster &&p)
CDnaGpsPointCluster & operator= (CDnaGpsPointCluster &&rhs)
CDnaGpsPointCluster (const UINT32 lclusterID, const std::string &referenceframe, const std::string &epoch)
bool operator== (const CDnaGpsPointCluster &rhs) const
bool operator< (const CDnaGpsPointCluster &rhs) const
std::vector< CDnaGpsPoint > & GetPoints ()
std::vector< CDnaGpsPoint > * GetPoints_ptr ()
UINT32 GetClusterID () const
std::string GetCoordType () const
UINT32 GetTotal () const
double GetPscale () const
double GetLscale () const
double GetHscale () const
double GetVscale () const
void SetCoordType (const std::string &str)
_COORD_TYPE_ GetMyCoordTypeC ()
void SetReferenceFrame (const std::string &refFrame)
void SetEpsg (const std::string &epsg)
std::string GetReferenceFrame () const
void SetTotal (const std::string &str)
void SetPscale (const std::string &str)
void SetLscale (const std::string &str)
void SetHscale (const std::string &str)
void SetVscale (const std::string &str)
void SetTotal (const UINT32 &u)
void SetPscale (const double &dbl)
void SetLscale (const double &dbl)
void SetHscale (const double &dbl)
void SetVscale (const double &dbl)
void AddGpsPoint (const CDnaMeasurement *pGpsPoint)
virtual UINT32 CalcBinaryRecordCount () const
virtual void WriteBinaryMsr (std::ofstream *binary_stream, PUINT32 msrIndex) const
virtual UINT32 SetMeasurementRec (const vstn_t &binaryStn, it_vmsr_t &it_msr, it_vdbid_t &dbidmap)
virtual void WriteDynaMLMsr (std::ofstream *dynaml_stream, const std::string &comment, bool) const
virtual void WriteDNAMsr (std::ofstream *dna_stream, const dna_msr_fields &dmw, const dna_msr_fields &dml, bool) const
virtual void SimulateMsr (vdnaStnPtr *vStations, const CDnaEllipsoid *ellipsoid)
virtual void PopulateMsr (pvstn_t bstRecords, uint32_uint32_map *blockStationsMap, vUINT32 *blockStations, const UINT32 &block, const CDnaDatum *datum, math::matrix_2d *estimates, math::matrix_2d *variances)
virtual void SerialiseDatabaseMap (std::ofstream *os)
void SetDatabaseMaps (it_vdbid_t &dbidmap)
Public Member Functions inherited from dynadjust::measurements::CDnaMeasurement
CDnaMeasurement ()
virtual ~CDnaMeasurement ()
CDnaMeasurement (CDnaMeasurement &&m)
CDnaMeasurement & operator= (CDnaMeasurement &&rhs)
std::string GetType () const
char GetTypeC () const
bool GetIgnore () const
bool NotIgnored () const
std::string GetFirst () const
MEASUREMENT_STATIONS GetMsrStnCount () const
std::string GetEpsg () const
std::string GetSource () const
bool GetInsufficient () const
void SetType (const std::string &str)
void SetIgnore (const bool bval)
void SetFirst (const std::string &str)
void SetEpsg (const std::string &e)
void SetSource (const std::string &source)
void SetInsufficient (const bool bval)
void SetMsrIndex (const UINT32 &order)
void SetStn1Index (const UINT32 &order)
void SetStn2Index (const UINT32 &order)
void SetStn3Index (const UINT32 &order)
UINT32 GetMsrIndex () const
UINT32 GetStn1Index () const
UINT32 GetStn2Index () const
UINT32 GetStn3Index () const
double GetMeasAdj () const
double GetMeasCorr () const
double GetMeasAdjPrec () const
double GetResidualPrec () const
double GetPreAdjCorr () const
virtual float GetInstrHeight () const
virtual double GetStdDev () const
virtual std::string GetTarget () const
virtual std::string GetTarget2 () const
virtual float GetTargetHeight () const
virtual double GetValue () const
std::string GetEpoch () const
virtual std::vector< CDnaGpsBaseline > * GetBaselines_ptr ()
virtual std::vector< CDnaDirection > * GetDirections_ptr ()
virtual std::vector< CDnaCovariance > * GetCovariances_ptr ()
virtual void AddDirection (const CDnaMeasurement *)
virtual void AddGpsBaseline (const CDnaMeasurement *)
virtual void AddGpsCovariance (const CDnaCovariance *)
virtual void AddPointCovariance (const CDnaCovariance *)
virtual void ReserveDirectionsCount (const UINT32 &)
virtual void ReserveGpsBaselinesCount (const UINT32 &)
virtual void ReserveGpsPointsCount (const UINT32 &)
virtual void ReserveGpsCovariancesCount (const UINT32 &)
virtual void ResizeGpsCovariancesCount (const UINT32 &)
virtual void SetRecordedTotal (const UINT32 &)
virtual void SetNonIgnoredDirns (const UINT32 &)
virtual void SetClusterID (const UINT32 &)
virtual void SetInstrumentHeight (const std::string &)
void SetEpoch (const std::string &epoch)
virtual void SetSigmaXX (const std::string &)
virtual void SetSigmaXY (const std::string &)
virtual void SetSigmaXZ (const std::string &)
virtual void SetSigmaYY (const std::string &)
virtual void SetSigmaYZ (const std::string &)
virtual void SetSigmaZZ (const std::string &)
virtual void SetStdDev (const std::string &)
virtual void SetTarget (const std::string &)
virtual void SetTarget2 (const std::string &)
virtual void SetTargetHeight (const std::string &)
virtual void SetValue (const std::string &)
virtual void SetX (const std::string &)
virtual void SetY (const std::string &)
virtual void SetZ (const std::string &)
virtual void SetXAxis (const double &)
virtual void SetYAxis (const double &)
virtual void SetZAxis (const double &)
virtual void SetSigmaXX (const double &)
virtual void SetSigmaXY (const double &)
virtual void SetSigmaXZ (const double &)
virtual void SetSigmaYY (const double &)
virtual void SetSigmaYZ (const double &)
virtual void SetSigmaZZ (const double &)
virtual void PreferGMeasurements ()
void SetMeasurementDBID (const std::string &str)
void SetClusterDBID (const std::string &str)
void SetClusterDBID (const UINT32 &u, bool s)
UINT32 GetClusterDBID ()
bool GetClusterDBIDset ()
void SetDatabaseMap (const msr_database_id_map &dbidmap)
Protected Attributes
UINT32 m_lRecordedTotal
double m_dPscale
double m_dLscale
double m_dHscale
double m_dVscale
std::string m_strCoordType
COORD_TYPE m_ctType
std::vector< CDnaGpsPoint > m_vGpsPoints
std::string m_referenceFrame
UINT32 m_lclusterID
it_vdbid_t m_dbidmap
Protected Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strType
bool m_bIgnore
UINT32 m_lmeasurementIndex
UINT32 m_lstn1Index
UINT32 m_lstn2Index
UINT32 m_lstn3Index
double m_measAdj
double m_measCorr
double m_measAdjPrec
double m_residualPrec
double m_preAdjCorr
std::string m_epsgCode
std::string m_sourceFile
std::string m_epoch
msr_database_id_map m_msr_db_map
bool m_bInsufficient
Private Member Functions
CDnaGpsPointCluster (const CDnaGpsPointCluster &)
CDnaGpsPointCluster & operator= (const CDnaGpsPointCluster &rhs)
Additional Inherited Members
Public Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strFirst
MEASUREMENT_STATIONS m_MSmeasurementStations
Protected Member Functions inherited from dynadjust::measurements::CDnaMeasurement
void coutMeasurement (std::ostream &os) const
Detailed Description
Definition at line 169 of file dnagpspoint.hpp.
Constructor & Destructor Documentation
CDnaGpsPointCluster() [1/4]
dynadjust::measurements::CDnaGpsPointCluster::CDnaGpsPointCluster (void)
Definition at line 713 of file dnagpspoint.cpp.
    : m_lRecordedTotal(0)
    , m_dPscale(1.)
    , m_dLscale(1.)
    , m_dHscale(1.)
    , m_dVscale(1.)
    , m_strCoordType("XYZ")
    , m_ctType(XYZ_type_i)
    , m_referenceFrame(DEFAULT_DATUM)
    , m_lclusterID(0)
{
    SetEpoch(DEFAULT_EPOCH);
    SetEpsg(epsgStringFromName<std::string>(m_referenceFrame));
    m_strType = "Y";
    m_MSmeasurementStations = ONE_STATION;
}
References DEFAULT_DATUM(), DEFAULT_EPOCH(), dynadjust::epsg::epsgStringFromName(), m_ctType, m_dHscale, m_dLscale, m_dPscale, m_dVscale, m_lclusterID, m_lRecordedTotal, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, m_referenceFrame, m_strCoordType, dynadjust::measurements::CDnaMeasurement::m_strType, ONE_STATION, dynadjust::measurements::CDnaMeasurement::SetEpoch(), SetEpsg(), and XYZ_type_i.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), operator<(), operator=(), operator=(), and operator==().
~CDnaGpsPointCluster()
dynadjust::measurements::CDnaGpsPointCluster::~CDnaGpsPointCluster (void) virtual
Definition at line 732 of file dnagpspoint.cpp.
{
}
CDnaGpsPointCluster() [2/4]
dynadjust::measurements::CDnaGpsPointCluster::CDnaGpsPointCluster (CDnaGpsPointCluster && p)
Definition at line 738 of file dnagpspoint.cpp.
{
    m_strType = p.m_strType;
    m_bIgnore = p.m_bIgnore;
    m_lRecordedTotal = p.m_lRecordedTotal;
    SetCoordType(p.m_strCoordType);
    m_vGpsPoints = std::move(p.m_vGpsPoints);
    m_dPscale = p.m_dPscale;
    m_dLscale = p.m_dLscale;
    m_dHscale = p.m_dHscale;
    m_dVscale = p.m_dVscale;
    m_lclusterID = p.m_lclusterID;
    m_MSmeasurementStations = p.m_MSmeasurementStations;
    m_referenceFrame = p.m_referenceFrame;
    m_epsgCode = p.m_epsgCode;
    m_epoch = p.m_epoch;
    m_msr_db_map = p.m_msr_db_map;
    m_dbidmap = p.m_dbidmap;
}
References CDnaGpsPointCluster(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dbidmap, m_dHscale, m_dLscale, m_dPscale, m_dVscale, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_epsgCode, m_lclusterID, m_lRecordedTotal, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, m_referenceFrame, dynadjust::measurements::CDnaMeasurement::m_strType, m_vGpsPoints, and SetCoordType().
CDnaGpsPointCluster() [3/4]
dynadjust::measurements::CDnaGpsPointCluster::CDnaGpsPointCluster (const CDnaGpsPointCluster &) private
References CDnaGpsPointCluster().
CDnaGpsPointCluster() [4/4]
dynadjust::measurements::CDnaGpsPointCluster::CDnaGpsPointCluster (const UINT32 lclusterID, const std::string & referenceframe, const std::string & epoch)
Definition at line 796 of file dnagpspoint.cpp.
    : m_lRecordedTotal(0)
    , m_dPscale(1.)
    , m_dLscale(1.)
    , m_dHscale(1.)
    , m_dVscale(1.)
    , m_strCoordType("XYZ")
    , m_ctType(XYZ_type_i)
    , m_referenceFrame(referenceframe)
    , m_lclusterID(lclusterID)
{
    SetEpoch(epoch);
    SetEpsg(epsgStringFromName<std::string>(referenceframe));
    m_strType = "Y";
    m_MSmeasurementStations = ONE_STATION;
}
References dynadjust::epsg::epsgStringFromName(), m_ctType, m_dHscale, m_dLscale, m_dPscale, m_dVscale, m_lclusterID, m_lRecordedTotal, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, m_referenceFrame, m_strCoordType, dynadjust::measurements::CDnaMeasurement::m_strType, ONE_STATION, dynadjust::measurements::CDnaMeasurement::SetEpoch(), SetEpsg(), and XYZ_type_i.
Member Function Documentation
operator=() [1/2]
CDnaGpsPointCluster & dynadjust::measurements::CDnaGpsPointCluster::operator= (CDnaGpsPointCluster && rhs)
Definition at line 764 of file dnagpspoint.cpp.
{
    // check for assignment to self!
    if (this == &rhs)
        return *this;
    CDnaMeasurement::operator=(std::move(rhs));
    m_lRecordedTotal = rhs.m_lRecordedTotal;
    SetCoordType(rhs.m_strCoordType);
    m_referenceFrame = rhs.m_referenceFrame;
    m_epsgCode = rhs.m_epsgCode;
    m_epoch = rhs.m_epoch;
    m_dPscale = rhs.m_dPscale;
    m_dLscale = rhs.m_dLscale;
    m_dHscale = rhs.m_dHscale;
    m_dVscale = rhs.m_dVscale;
    m_lclusterID = rhs.m_lclusterID;
    m_MSmeasurementStations = rhs.m_MSmeasurementStations;
    m_vGpsPoints = std::move(rhs.m_vGpsPoints);
    m_msr_db_map = rhs.m_msr_db_map;
    m_dbidmap = rhs.m_dbidmap;
    return *this;
}
References CDnaGpsPointCluster(), m_dbidmap, m_dHscale, m_dLscale, m_dPscale, m_dVscale, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_epsgCode, m_lclusterID, m_lRecordedTotal, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, m_referenceFrame, m_vGpsPoints, dynadjust::measurements::CDnaMeasurement::operator=(), and SetCoordType().
operator=() [2/2]
CDnaGpsPointCluster & dynadjust::measurements::CDnaGpsPointCluster::operator= (const CDnaGpsPointCluster & rhs) private
References CDnaGpsPointCluster().
operator==()
bool dynadjust::measurements::CDnaGpsPointCluster::operator== (const CDnaGpsPointCluster & rhs) const
Definition at line 815 of file dnagpspoint.cpp.
{
    return (
        m_strType == rhs.m_strType &&
        m_strFirst == rhs.m_strFirst &&
        m_bIgnore == rhs.m_bIgnore &&
        m_lRecordedTotal == rhs.m_lRecordedTotal &&
        m_strCoordType == rhs.m_strCoordType &&
        m_dPscale == rhs.m_dPscale &&
        m_dLscale == rhs.m_dLscale &&
        m_dHscale == rhs.m_dHscale &&
        m_dVscale == rhs.m_dVscale &&
        m_vGpsPoints == rhs.m_vGpsPoints
        );
}
References CDnaGpsPointCluster(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dHscale, m_dLscale, m_dPscale, m_dVscale, m_lRecordedTotal, m_strCoordType, dynadjust::measurements::CDnaMeasurement::m_strFirst, dynadjust::measurements::CDnaMeasurement::m_strType, and m_vGpsPoints.
operator<()
bool dynadjust::measurements::CDnaGpsPointCluster::operator< (const CDnaGpsPointCluster & rhs) const
Definition at line 831 of file dnagpspoint.cpp.
{
    if (m_strFirst == rhs.m_strFirst) {
        if (m_strType == rhs.m_strType) {
            if (m_bIgnore == rhs.m_bIgnore) {
                if (m_epoch == rhs.m_epoch) {
                    if (m_strCoordType == rhs.m_strCoordType) {
                        if (m_lRecordedTotal == rhs.m_lRecordedTotal)
                            return m_vGpsPoints < rhs.m_vGpsPoints;
                        else
                            return m_lRecordedTotal < rhs.m_lRecordedTotal; }
                    else
                        return m_strCoordType < rhs.m_strCoordType; }
                else
                    return m_epoch < rhs.m_epoch; }
            else
                return m_bIgnore < rhs.m_bIgnore; }
        else
            return m_strType < rhs.m_strType; }
    else
        return m_strFirst < rhs.m_strFirst;
}
References CDnaGpsPointCluster(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, dynadjust::measurements::CDnaMeasurement::m_epoch, m_lRecordedTotal, m_strCoordType, dynadjust::measurements::CDnaMeasurement::m_strFirst, dynadjust::measurements::CDnaMeasurement::m_strType, and m_vGpsPoints.
GetPoints()
std::vector< CDnaGpsPoint > & dynadjust::measurements::CDnaGpsPointCluster::GetPoints () inline
Definition at line 195 of file dnagpspoint.hpp.
{ return m_vGpsPoints; }
References m_vGpsPoints.
GetPoints_ptr()
std::vector< CDnaGpsPoint > * dynadjust::measurements::CDnaGpsPointCluster::GetPoints_ptr () inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 196 of file dnagpspoint.hpp.
{ return &m_vGpsPoints; }
References m_vGpsPoints.
GetClusterID()
UINT32 dynadjust::measurements::CDnaGpsPointCluster::GetClusterID () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 198 of file dnagpspoint.hpp.
{ return m_lclusterID; }
References m_lclusterID.
GetCoordType()
std::string dynadjust::measurements::CDnaGpsPointCluster::GetCoordType () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 199 of file dnagpspoint.hpp.
{ return m_strCoordType; }
References m_strCoordType.
GetTotal()
UINT32 dynadjust::measurements::CDnaGpsPointCluster::GetTotal () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 200 of file dnagpspoint.hpp.
{ return m_lRecordedTotal; }
References m_lRecordedTotal.
GetPscale()
double dynadjust::measurements::CDnaGpsPointCluster::GetPscale () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 201 of file dnagpspoint.hpp.
{ return m_dPscale; }
References m_dPscale.
GetLscale()
double dynadjust::measurements::CDnaGpsPointCluster::GetLscale () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 202 of file dnagpspoint.hpp.
{ return m_dLscale; }
References m_dLscale.
GetHscale()
double dynadjust::measurements::CDnaGpsPointCluster::GetHscale () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 203 of file dnagpspoint.hpp.
{ return m_dHscale; }
References m_dHscale.
GetVscale()
double dynadjust::measurements::CDnaGpsPointCluster::GetVscale () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 204 of file dnagpspoint.hpp.
{ return m_dVscale; }
References m_dVscale.
SetCoordType()
void dynadjust::measurements::CDnaGpsPointCluster::SetCoordType (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 854 of file dnagpspoint.cpp.
{
    m_strCoordType = trimstr(sType);
    m_ctType = GetMyCoordTypeC();
}
References GetMyCoordTypeC(), m_ctType, m_strCoordType, and trimstr().
Referenced by CDnaGpsPointCluster(), operator=(), PopulateMsr(), and SetMeasurementRec().
GetMyCoordTypeC()
_COORD_TYPE_ dynadjust::measurements::CDnaGpsPointCluster::GetMyCoordTypeC ()
Definition at line 860 of file dnagpspoint.cpp.
{
    return CDnaStation::GetCoordTypeC(m_strCoordType);
}
References dynadjust::measurements::CDnaStation::GetCoordTypeC(), and m_strCoordType.
Referenced by SetCoordType().
SetReferenceFrame()
void dynadjust::measurements::CDnaGpsPointCluster::SetReferenceFrame (const std::string & refFrame) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 1063 of file dnagpspoint.cpp.
{
    m_referenceFrame = refFrame;
    SetEpsg(epsgStringFromName<std::string>(refFrame));
}
References dynadjust::epsg::epsgStringFromName(), m_referenceFrame, and SetEpsg().
SetEpsg()
void dynadjust::measurements::CDnaGpsPointCluster::SetEpsg (const std::string & epsg)
Definition at line 1057 of file dnagpspoint.cpp.
{
    m_epsgCode = epsg;
}
References dynadjust::measurements::CDnaMeasurement::m_epsgCode.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), and SetReferenceFrame().
GetReferenceFrame()
std::string dynadjust::measurements::CDnaGpsPointCluster::GetReferenceFrame () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 213 of file dnagpspoint.hpp.
{ return m_referenceFrame; }
References m_referenceFrame.
SetTotal() [1/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetTotal (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 1070 of file dnagpspoint.cpp.
{
    m_lRecordedTotal = LongFromString<UINT32>(trimstr(str));
    m_vGpsPoints.reserve(m_lRecordedTotal);
}
References LongFromString(), m_lRecordedTotal, m_vGpsPoints, and trimstr().
SetPscale() [1/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetPscale (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 1077 of file dnagpspoint.cpp.
{
    DoubleFromString(m_dPscale, trimstr(str));
}
References DoubleFromString(), m_dPscale, and trimstr().
SetLscale() [1/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetLscale (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 1082 of file dnagpspoint.cpp.
{
    DoubleFromString(m_dLscale, trimstr(str));
}
References DoubleFromString(), m_dLscale, and trimstr().
SetHscale() [1/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetHscale (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 1087 of file dnagpspoint.cpp.
{
    DoubleFromString(m_dHscale, trimstr(str));
}
References DoubleFromString(), m_dHscale, and trimstr().
SetVscale() [1/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetVscale (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 1092 of file dnagpspoint.cpp.
{
    DoubleFromString(m_dVscale, trimstr(str));
}
References DoubleFromString(), m_dVscale, and trimstr().
SetTotal() [2/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetTotal (const UINT32 & u) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 223 of file dnagpspoint.hpp.
{ m_lRecordedTotal = u; }
References m_lRecordedTotal.
SetPscale() [2/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetPscale (const double & dbl) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 225 of file dnagpspoint.hpp.
{ m_dPscale = dbl; }
References m_dPscale.
SetLscale() [2/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetLscale (const double & dbl) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 226 of file dnagpspoint.hpp.
{ m_dLscale = dbl; }
References m_dLscale.
SetHscale() [2/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetHscale (const double & dbl) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 227 of file dnagpspoint.hpp.
{ m_dHscale = dbl; }
References m_dHscale.
SetVscale() [2/2]
void dynadjust::measurements::CDnaGpsPointCluster::SetVscale (const double & dbl) inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 228 of file dnagpspoint.hpp.
{ m_dVscale = dbl; }
References m_dVscale.
AddGpsPoint()
void dynadjust::measurements::CDnaGpsPointCluster::AddGpsPoint (const CDnaMeasurement * pGpsPoint) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 866 of file dnagpspoint.cpp.
{
    m_vGpsPoints.push_back(std::move((CDnaGpsPoint&)*pGpsPoint));
}
References dynadjust::measurements::CDnaMeasurement::CDnaMeasurement(), and m_vGpsPoints.
CalcBinaryRecordCount()
UINT32 dynadjust::measurements::CDnaGpsPointCluster::CalcBinaryRecordCount () const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 895 of file dnagpspoint.cpp.
{
    UINT32 recordCount(0);
    for_each(m_vGpsPoints.begin(), m_vGpsPoints.end(),
        [&recordCount](const CDnaGpsPoint& pnt) {
            recordCount += pnt.CalcBinaryRecordCount();
    });
    return recordCount;
}
References m_vGpsPoints.
WriteBinaryMsr()
void dynadjust::measurements::CDnaGpsPointCluster::WriteBinaryMsr (std::ofstream * binary_stream, PUINT32 msrIndex) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 1044 of file dnagpspoint.cpp.
{
    std::vector< CDnaGpsPoint >::const_iterator _it_pnt;
    for (_it_pnt=m_vGpsPoints.begin(); _it_pnt!=m_vGpsPoints.end(); ++_it_pnt)
        _it_pnt->WriteBinaryMsr(binary_stream, msrIndex);
    //for_each(m_vGpsPoints.begin(), m_vGpsPoints.end(),
    //  [this, &binary_stream, &msrIndex] (CDnaGpsPoint p) {
    //      p.WriteBinaryMsr(binary_stream, msrIndex);
    //});
}
References m_vGpsPoints.
SetMeasurementRec()
UINT32 dynadjust::measurements::CDnaGpsPointCluster::SetMeasurementRec (const vstn_t & binaryStn, it_vmsr_t & it_msr, it_vdbid_t & dbidmap) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 1005 of file dnagpspoint.cpp.
{
    m_lclusterID = it_msr->clusterID;
    m_MSmeasurementStations = (MEASUREMENT_STATIONS)it_msr->measurementStations;
    m_lRecordedTotal = it_msr->vectorCount1;
    m_vGpsPoints.clear();
    m_vGpsPoints.resize(m_lRecordedTotal);
    m_referenceFrame = datumFromEpsgCode<std::string, UINT32>(LongFromString<UINT32>(it_msr->epsgCode));
    m_epoch = it_msr->epoch;
    m_epsgCode = it_msr->epsgCode;
    m_dPscale = it_msr->scale1;
    m_dLscale = it_msr->scale2;
    m_dHscale = it_msr->scale3;
    m_dVscale = it_msr->scale4;
    UINT32 measrecordCount(it_msr->vectorCount1);
    // read remaining GpsPoint data and all Covariances from file
    for (UINT32 i=0; i<m_lRecordedTotal; i++)
    {
        if (i > 0)
        {
            it_msr++;
            dbidmap++;
        }
        m_strType = it_msr->measType;
        m_bIgnore = it_msr->ignore;
        SetCoordType(it_msr->coordType);
        m_vGpsPoints.at(i).SetMeasurementRec(binaryStn, it_msr, dbidmap);
    }
    return measrecordCount - 1;
}
References dynadjust::epsg::datumFromEpsgCode(), LongFromString(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dHscale, m_dLscale, m_dPscale, m_dVscale, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_epsgCode, m_lclusterID, m_lRecordedTotal, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, m_referenceFrame, dynadjust::measurements::CDnaMeasurement::m_strType, m_vGpsPoints, and SetCoordType().
WriteDynaMLMsr()
void dynadjust::measurements::CDnaGpsPointCluster::WriteDynaMLMsr (std::ofstream * dynaml_stream, const std::string & comment, bool) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 906 of file dnagpspoint.cpp.
{
    const size_t pntCount = m_vGpsPoints.size();
    if (comment.empty())
    {
        *dynaml_stream << "  <!-- Type " << measurement_name<char, std::string>(GetTypeC());
        if (pntCount > 1)
            *dynaml_stream << " (set of " << pntCount << ")";
        else
            *dynaml_stream << "  (single)";
        *dynaml_stream << " -->" << std::endl;
    }
    else
        *dynaml_stream << "  <!-- " << comment << " -->" << std::endl;
    *dynaml_stream << "  <DnaMeasurement>" << std::endl;
    *dynaml_stream << "    <Type>" << m_strType << "</Type>" << std::endl;
    // Source file from which the measurement came
    *dynaml_stream << "    <Source>" << m_sourceFile << "</Source>" << std::endl;
    if (m_bIgnore)
        *dynaml_stream << "    <Ignore>*</Ignore>" << std::endl;
    else
        *dynaml_stream << "    <Ignore/>" << std::endl;
    // Reference frame and epoch
    *dynaml_stream << "    <ReferenceFrame>" << m_referenceFrame << "</ReferenceFrame>" << std::endl;
    *dynaml_stream << "    <Epoch>" << m_epoch << "</Epoch>" << std::endl;
    // Scalars
    *dynaml_stream << "    <Vscale>" << std::fixed << std::setprecision(3) << m_dVscale << "</Vscale>" << std::endl;
    *dynaml_stream << "    <Pscale>" << m_dPscale << "</Pscale>" << std::endl;
    *dynaml_stream << "    <Lscale>" << m_dLscale << "</Lscale>" << std::endl;
    *dynaml_stream << "    <Hscale>" << m_dHscale << "</Hscale>" << std::endl;
    if (m_msr_db_map.is_cls_id_set)
        *dynaml_stream << "    <ClusterID>" << m_msr_db_map.cluster_id << "</ClusterID>" << std::endl;
    *dynaml_stream << "    <Coords>" << m_strCoordType << "</Coords>" << std::endl;
    *dynaml_stream << "    <Total>" << pntCount << "</Total>" << std::endl;
    // write GpsPoints
    std::vector<CDnaGpsPoint>::const_iterator _it_pnt;
    for (_it_pnt=m_vGpsPoints.begin(); _it_pnt!=m_vGpsPoints.end(); ++_it_pnt)
        _it_pnt->WriteDynaMLMsr(dynaml_stream, comment, true);
    *dynaml_stream << "  </DnaMeasurement>" << std::endl;
}
References dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dHscale, m_dLscale, m_dPscale, m_dVscale, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, m_referenceFrame, dynadjust::measurements::CDnaMeasurement::m_sourceFile, m_strCoordType, dynadjust::measurements::CDnaMeasurement::m_strType, m_vGpsPoints, and dynadjust::measurements::measurement_name().
WriteDNAMsr()
void dynadjust::measurements::CDnaGpsPointCluster::WriteDNAMsr (std::ofstream * dna_stream, const dna_msr_fields & dmw, const dna_msr_fields & dml, bool) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 955 of file dnagpspoint.cpp.
{
    // write GpsPoints
    std::vector<CDnaGpsPoint>::const_iterator _it_pnt;
    for (_it_pnt=m_vGpsPoints.begin(); _it_pnt!=m_vGpsPoints.end(); ++_it_pnt)
        _it_pnt->WriteDNAMsr(dna_stream, dmw, dml, true);
}
References m_vGpsPoints.
SimulateMsr()
void dynadjust::measurements::CDnaGpsPointCluster::SimulateMsr (vdnaStnPtr * vStations, const CDnaEllipsoid * ellipsoid) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Definition at line 964 of file dnagpspoint.cpp.
{
    std::vector<CDnaGpsPoint>::iterator _it_pnt = m_vGpsPoints.begin();
    for (_it_pnt=m_vGpsPoints.begin(); _it_pnt!=m_vGpsPoints.end(); ++_it_pnt)
        _it_pnt->SimulateMsr(vStations, ellipsoid);
}
References m_vGpsPoints.
PopulateMsr()
void dynadjust::measurements::CDnaGpsPointCluster::PopulateMsr (pvstn_t bstRecords, uint32_uint32_map * blockStationsMap, vUINT32 * blockStations, const UINT32 & block, const CDnaDatum * datum, math::matrix_2d * estimates, math::matrix_2d * variances) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 971 of file dnagpspoint.cpp.
{
    m_strType = 'Y';
    m_bIgnore = false;
    SetCoordType(XYZ_type);
    m_lclusterID = block;
    m_MSmeasurementStations = ONE_STATION;
    m_lRecordedTotal = static_cast<UINT32>(blockStationsMap->size());
    m_vGpsPoints.clear();
    m_vGpsPoints.resize(m_lRecordedTotal);
    m_referenceFrame = datum->GetName();
    m_epoch = datum->GetEpoch_s();
    m_epsgCode =  datum->GetEpsgCode_s();
    m_dPscale = 1.0;
    m_dLscale = 1.0;
    m_dHscale = 1.0;
    m_dVscale = 1.0;
    std::vector<CDnaGpsPoint>::iterator _it_pnt = m_vGpsPoints.begin();
    for (UINT32 i(0); i<m_lRecordedTotal; ++i)
    {
        _it_pnt->SetClusterID(block);
        _it_pnt->SetTotal(static_cast<UINT32>(blockStations->size()));
        _it_pnt->PopulateMsr(bstRecords, blockStationsMap, blockStations,
            i, datum, estimates, variances);
        ++_it_pnt;
    }
}
References dynadjust::datum_parameters::CDnaDatum::GetEpoch_s(), dynadjust::datum_parameters::CDnaDatum::GetEpsgCode_s(), dynadjust::datum_parameters::CDnaDatum::GetName(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dHscale, m_dLscale, m_dPscale, m_dVscale, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_epsgCode, m_lclusterID, m_lRecordedTotal, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, m_referenceFrame, dynadjust::measurements::CDnaMeasurement::m_strType, m_vGpsPoints, ONE_STATION, SetCoordType(), and XYZ_type().
SerialiseDatabaseMap()
void dynadjust::measurements::CDnaGpsPointCluster::SerialiseDatabaseMap (std::ofstream * os) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 872 of file dnagpspoint.cpp.
{
    for_each(m_vGpsPoints.begin(), m_vGpsPoints.end(),
        [this, os](const CDnaGpsPoint& pnt) {
            ((CDnaGpsPoint*)&pnt)->SerialiseDatabaseMap(os);
    });
}
References m_vGpsPoints.
SetDatabaseMaps()
void dynadjust::measurements::CDnaGpsPointCluster::SetDatabaseMaps (it_vdbid_t & dbidmap) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Definition at line 881 of file dnagpspoint.cpp.
{
    m_dbidmap = dbidmap;
    CDnaMeasurement::SetDatabaseMap(*m_dbidmap);
    for_each(m_vGpsPoints.begin(), m_vGpsPoints.end(),
        [this](const CDnaGpsPoint& bsl) {
            ((CDnaGpsPoint*)&bsl)->SetDatabaseMap(*m_dbidmap);
            m_dbidmap += ((CDnaGpsPoint*)&bsl)->GetCovariances_ptr()->size();
        });
}
References m_dbidmap, m_vGpsPoints, and dynadjust::measurements::CDnaMeasurement::SetDatabaseMap().
Member Data Documentation
m_lRecordedTotal
UINT32 dynadjust::measurements::CDnaGpsPointCluster::m_lRecordedTotal protected
Definition at line 248 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), CDnaGpsPointCluster(), GetTotal(), operator<(), operator=(), operator==(), PopulateMsr(), SetMeasurementRec(), SetTotal(), and SetTotal().
m_dPscale
double dynadjust::measurements::CDnaGpsPointCluster::m_dPscale protected
Definition at line 249 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), CDnaGpsPointCluster(), GetPscale(), operator=(), operator==(), PopulateMsr(), SetMeasurementRec(), SetPscale(), SetPscale(), and WriteDynaMLMsr().
m_dLscale
double dynadjust::measurements::CDnaGpsPointCluster::m_dLscale protected
Definition at line 250 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), CDnaGpsPointCluster(), GetLscale(), operator=(), operator==(), PopulateMsr(), SetLscale(), SetLscale(), SetMeasurementRec(), and WriteDynaMLMsr().
m_dHscale
double dynadjust::measurements::CDnaGpsPointCluster::m_dHscale protected
Definition at line 251 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), CDnaGpsPointCluster(), GetHscale(), operator=(), operator==(), PopulateMsr(), SetHscale(), SetHscale(), SetMeasurementRec(), and WriteDynaMLMsr().
m_dVscale
double dynadjust::measurements::CDnaGpsPointCluster::m_dVscale protected
Definition at line 252 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), CDnaGpsPointCluster(), GetVscale(), operator=(), operator==(), PopulateMsr(), SetMeasurementRec(), SetVscale(), SetVscale(), and WriteDynaMLMsr().
m_strCoordType
std::string dynadjust::measurements::CDnaGpsPointCluster::m_strCoordType protected
Definition at line 253 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), GetCoordType(), GetMyCoordTypeC(), operator<(), operator==(), SetCoordType(), and WriteDynaMLMsr().
m_ctType
COORD_TYPE dynadjust::measurements::CDnaGpsPointCluster::m_ctType protected
Definition at line 255 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), and SetCoordType().
m_vGpsPoints
std::vector<CDnaGpsPoint> dynadjust::measurements::CDnaGpsPointCluster::m_vGpsPoints protected
Definition at line 257 of file dnagpspoint.hpp.
Referenced by AddGpsPoint(), CalcBinaryRecordCount(), CDnaGpsPointCluster(), GetPoints(), GetPoints_ptr(), operator<(), operator=(), operator==(), PopulateMsr(), SerialiseDatabaseMap(), SetDatabaseMaps(), SetMeasurementRec(), SetTotal(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_referenceFrame
std::string dynadjust::measurements::CDnaGpsPointCluster::m_referenceFrame protected
Definition at line 259 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), CDnaGpsPointCluster(), GetReferenceFrame(), operator=(), PopulateMsr(), SetMeasurementRec(), SetReferenceFrame(), and WriteDynaMLMsr().
m_lclusterID
UINT32 dynadjust::measurements::CDnaGpsPointCluster::m_lclusterID protected
Definition at line 262 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), CDnaGpsPointCluster(), CDnaGpsPointCluster(), GetClusterID(), operator=(), PopulateMsr(), and SetMeasurementRec().
m_dbidmap
it_vdbid_t dynadjust::measurements::CDnaGpsPointCluster::m_dbidmap protected
Definition at line 264 of file dnagpspoint.hpp.
Referenced by CDnaGpsPointCluster(), operator=(), and SetDatabaseMaps().
The documentation for this class was generated from the following files:
include/measurement_types/dnagpspoint.hpp
include/measurement_types/dnagpspoint.cpp