DynAdjust: GPSBaseline_pimpl Class Reference
GPSBaseline_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void X (const ::std::string &)
virtual void Y (const ::std::string &)
virtual void Z (const ::std::string &)
virtual void MeasurementDBID (const ::std::string &)
virtual void SigmaXX (const ::std::string &)
virtual void SigmaXY (const ::std::string &)
virtual void SigmaXZ (const ::std::string &)
virtual void SigmaYY (const ::std::string &)
virtual void SigmaYZ (const ::std::string &)
virtual void SigmaZZ (const ::std::string &)
virtual void GPSCovariance ()
virtual void post_GPSBaseline ()
Public Member Functions inherited from GPSBaseline_pskel
void X_parser (::xml_schema::string_pskel &)
void Y_parser (::xml_schema::string_pskel &)
void Z_parser (::xml_schema::string_pskel &)
void MeasurementDBID_parser (::xml_schema::string_pskel &)
void SigmaXX_parser (::xml_schema::string_pskel &)
void SigmaXY_parser (::xml_schema::string_pskel &)
void SigmaXZ_parser (::xml_schema::string_pskel &)
void SigmaYY_parser (::xml_schema::string_pskel &)
void SigmaYZ_parser (::xml_schema::string_pskel &)
void SigmaZZ_parser (::xml_schema::string_pskel &)
void GPSCovariance_parser (::GPSCovariance_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::GPSCovariance_pskel &)
GPSBaseline_pskel ()
void InitparentGpsBaselineCluster (dnaMsrPtr pGpsBaselineCluster)
void InitparentMsrCounter (PUINT32 pMsrCounter)
Additional Inherited Members
Protected Member Functions inherited from GPSBaseline_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes inherited from GPSBaseline_pskel
::xml_schema::string_pskel * X_parser_
::xml_schema::string_pskel * Y_parser_
::xml_schema::string_pskel * Z_parser_
::xml_schema::string_pskel * MeasurementDBID_parser_
::xml_schema::string_pskel * SigmaXX_parser_
::xml_schema::string_pskel * SigmaXY_parser_
::xml_schema::string_pskel * SigmaXZ_parser_
::xml_schema::string_pskel * SigmaYY_parser_
::xml_schema::string_pskel * SigmaYZ_parser_
::xml_schema::string_pskel * SigmaZZ_parser_
::GPSCovariance_pskel * GPSCovariance_parser_
dnaMsrPtr _dnaGpsBaseline
dnaMsrPtr _parent_dnaGpsBaselineCluster
PUINT32 _pMeasurementCount
Detailed Description
Definition at line 153 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void GPSBaseline_pimpl::pre () virtual
Definition at line 1007 of file dnaparser_pimpl.cxx.
{
    _dnaGpsBaseline.reset(new CDnaGpsBaseline);
    _dnaGpsBaseline->SetType(_parent_dnaGpsBaselineCluster->GetType());
    _dnaGpsBaseline->SetFirst(_parent_dnaGpsBaselineCluster->GetFirst());
    _dnaGpsBaseline->SetTarget(_parent_dnaGpsBaselineCluster->GetTarget());
    _dnaGpsBaseline->SetReferenceFrame(_parent_dnaGpsBaselineCluster->GetReferenceFrame());
    _dnaGpsBaseline->SetEpoch(_parent_dnaGpsBaselineCluster->GetEpoch());
    _dnaGpsBaseline->SetClusterID(_parent_dnaGpsBaselineCluster->GetClusterID());
    _dnaGpsBaseline->SetClusterDBID(
        _parent_dnaGpsBaselineCluster->GetClusterDBID(),
        _parent_dnaGpsBaselineCluster->GetClusterDBIDset());
    if (_parent_dnaGpsBaselineCluster->GetType().empty())
        throw XMLInteropException("\"Type\" element must be provided before \"GPSBaseline\" element.", 0);
    // Is this a 'G' measurement
    if (_parent_dnaGpsBaselineCluster->GetTypeC() != 'X')
        return;
    const UINT32 measCount = _parent_dnaGpsBaselineCluster->GetTotal();
    // Only one baseline?  If so, no co-variances exist.
    // Two or more baselines?  Then reserve co-variance vector
    if (measCount > 1)
        _dnaGpsBaseline->ReserveGpsCovariancesCount(measCount - 1);
}
References GPSBaseline_pskel::_dnaGpsBaseline, and GPSBaseline_pskel::_parent_dnaGpsBaselineCluster.
X()
void GPSBaseline_pimpl::X (const ::std::string & X) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1039 of file dnaparser_pimpl.cxx.
{
    if (_dnaGpsBaseline)
        _dnaGpsBaseline->SetX(X);
    // increment measurement counter
    *(_pMeasurementCount) += 1;
    switch (_dnaGpsBaseline->GetTypeC())
    {
    case 'G':
        g_parsemsr_tally.G++;
        break;
    case 'X':
        g_parsemsr_tally.X++;
        break;
    }
}
References GPSBaseline_pskel::_dnaGpsBaseline, GPSBaseline_pskel::_pMeasurementCount, g_parsemsr_tally, and X().
Referenced by X().
Y()
void GPSBaseline_pimpl::Y (const ::std::string & Y) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1058 of file dnaparser_pimpl.cxx.
{
    if (_dnaGpsBaseline)
        _dnaGpsBaseline->SetY(Y);
    // increment measurement counter
    *(_pMeasurementCount) += 1;
    switch (_dnaGpsBaseline->GetTypeC())
    {
    case 'G':
        g_parsemsr_tally.G++;
        break;
    case 'X':
        g_parsemsr_tally.X++;
        break;
    }
}
References GPSBaseline_pskel::_dnaGpsBaseline, GPSBaseline_pskel::_pMeasurementCount, g_parsemsr_tally, and Y().
Referenced by Y().
Z()
void GPSBaseline_pimpl::Z (const ::std::string & Z) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1077 of file dnaparser_pimpl.cxx.
{
    if (_dnaGpsBaseline)
        _dnaGpsBaseline->SetZ(Z);
    // increment measurement counter
    *(_pMeasurementCount) += 1;
    switch (_dnaGpsBaseline->GetTypeC())
    {
    case 'G':
        g_parsemsr_tally.G++;
        break;
    case 'X':
        g_parsemsr_tally.X++;
        break;
    }
}
References GPSBaseline_pskel::_dnaGpsBaseline, GPSBaseline_pskel::_pMeasurementCount, g_parsemsr_tally, and Z().
Referenced by Z().
MeasurementDBID()
void GPSBaseline_pimpl::MeasurementDBID (const ::std::string & MeasurementID) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1096 of file dnaparser_pimpl.cxx.
{
    _dnaGpsBaseline->SetMeasurementDBID(MeasurementID);
}
References GPSBaseline_pskel::_dnaGpsBaseline.
SigmaXX()
void GPSBaseline_pimpl::SigmaXX (const ::std::string & SigmaXX) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1101 of file dnaparser_pimpl.cxx.
{
    _dnaGpsBaseline->SetSigmaXX(SigmaXX);
}
References GPSBaseline_pskel::_dnaGpsBaseline, and SigmaXX().
Referenced by SigmaXX().
SigmaXY()
void GPSBaseline_pimpl::SigmaXY (const ::std::string & SigmaXY) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1106 of file dnaparser_pimpl.cxx.
{
    _dnaGpsBaseline->SetSigmaXY(SigmaXY);
}
References GPSBaseline_pskel::_dnaGpsBaseline, and SigmaXY().
Referenced by SigmaXY().
SigmaXZ()
void GPSBaseline_pimpl::SigmaXZ (const ::std::string & SigmaXZ) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1111 of file dnaparser_pimpl.cxx.
{
    _dnaGpsBaseline->SetSigmaXZ(SigmaXZ);
}
References GPSBaseline_pskel::_dnaGpsBaseline, and SigmaXZ().
Referenced by SigmaXZ().
SigmaYY()
void GPSBaseline_pimpl::SigmaYY (const ::std::string & SigmaYY) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1116 of file dnaparser_pimpl.cxx.
{
    _dnaGpsBaseline->SetSigmaYY(SigmaYY);
}
References GPSBaseline_pskel::_dnaGpsBaseline, and SigmaYY().
Referenced by SigmaYY().
SigmaYZ()
void GPSBaseline_pimpl::SigmaYZ (const ::std::string & SigmaYZ) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1121 of file dnaparser_pimpl.cxx.
{
    _dnaGpsBaseline->SetSigmaYZ(SigmaYZ);
}
References GPSBaseline_pskel::_dnaGpsBaseline, and SigmaYZ().
Referenced by SigmaYZ().
SigmaZZ()
void GPSBaseline_pimpl::SigmaZZ (const ::std::string & SigmaZZ) virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1126 of file dnaparser_pimpl.cxx.
{
    _dnaGpsBaseline->SetSigmaZZ(SigmaZZ);
}
References GPSBaseline_pskel::_dnaGpsBaseline, and SigmaZZ().
Referenced by SigmaZZ().
GPSCovariance()
void GPSBaseline_pimpl::GPSCovariance () virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1131 of file dnaparser_pimpl.cxx.
{
}
post_GPSBaseline()
void GPSBaseline_pimpl::post_GPSBaseline () virtual
Reimplemented from GPSBaseline_pskel.
Definition at line 1135 of file dnaparser_pimpl.cxx.
{
    if (_dnaGpsBaseline && _parent_dnaGpsBaselineCluster)
        _parent_dnaGpsBaselineCluster->AddGpsBaseline(
        _dnaGpsBaseline.get());
}
References GPSBaseline_pskel::_dnaGpsBaseline, and GPSBaseline_pskel::_parent_dnaGpsBaselineCluster.
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx