DynAdjust: PointCovariance_pimpl Class Reference
PointCovariance_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void m11 (const ::std::string &)
virtual void m12 (const ::std::string &)
virtual void m13 (const ::std::string &)
virtual void m21 (const ::std::string &)
virtual void m22 (const ::std::string &)
virtual void m23 (const ::std::string &)
virtual void m31 (const ::std::string &)
virtual void m32 (const ::std::string &)
virtual void m33 (const ::std::string &)
virtual void post_PointCovariance ()
Public Member Functions inherited from PointCovariance_pskel
void m11_parser (::xml_schema::string_pskel &)
void m12_parser (::xml_schema::string_pskel &)
void m13_parser (::xml_schema::string_pskel &)
void m21_parser (::xml_schema::string_pskel &)
void m22_parser (::xml_schema::string_pskel &)
void m23_parser (::xml_schema::string_pskel &)
void m31_parser (::xml_schema::string_pskel &)
void m32_parser (::xml_schema::string_pskel &)
void m33_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &)
PointCovariance_pskel ()
void InitparentGpsPoint (dnaMsrPtr pGpsPoint)
Additional Inherited Members
Protected Member Functions inherited from PointCovariance_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes inherited from PointCovariance_pskel
::xml_schema::string_pskel * m11_parser_
::xml_schema::string_pskel * m12_parser_
::xml_schema::string_pskel * m13_parser_
::xml_schema::string_pskel * m21_parser_
::xml_schema::string_pskel * m22_parser_
::xml_schema::string_pskel * m23_parser_
::xml_schema::string_pskel * m31_parser_
::xml_schema::string_pskel * m32_parser_
::xml_schema::string_pskel * m33_parser_
dnaCovariancePtr _dnaPointCovariance
dnaMsrPtr _parent_dnaGpsPoint
Detailed Description
Definition at line 195 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void PointCovariance_pimpl::pre () virtual
Definition at line 1224 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance.reset(new CDnaCovariance);
    _dnaPointCovariance->SetType("Y");
    _dnaPointCovariance->SetClusterID(_parent_dnaGpsPoint->GetClusterID());
}
References PointCovariance_pskel::_dnaPointCovariance, and PointCovariance_pskel::_parent_dnaGpsPoint.
m11()
void PointCovariance_pimpl::m11 (const ::std::string & m11) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1231 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM11(m11);
}
References PointCovariance_pskel::_dnaPointCovariance, and m11().
Referenced by m11().
m12()
void PointCovariance_pimpl::m12 (const ::std::string & m12) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1236 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM12(m12);
}
References PointCovariance_pskel::_dnaPointCovariance, and m12().
Referenced by m12().
m13()
void PointCovariance_pimpl::m13 (const ::std::string & m13) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1241 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM13(m13);
}
References PointCovariance_pskel::_dnaPointCovariance, and m13().
Referenced by m13().
m21()
void PointCovariance_pimpl::m21 (const ::std::string & m21) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1246 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM21(m21);
}
References PointCovariance_pskel::_dnaPointCovariance, and m21().
Referenced by m21().
m22()
void PointCovariance_pimpl::m22 (const ::std::string & m22) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1251 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM22(m22);
}
References PointCovariance_pskel::_dnaPointCovariance, and m22().
Referenced by m22().
m23()
void PointCovariance_pimpl::m23 (const ::std::string & m23) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1256 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM23(m23);
}
References PointCovariance_pskel::_dnaPointCovariance, and m23().
Referenced by m23().
m31()
void PointCovariance_pimpl::m31 (const ::std::string & m31) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1261 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM31(m31);
}
References PointCovariance_pskel::_dnaPointCovariance, and m31().
Referenced by m31().
m32()
void PointCovariance_pimpl::m32 (const ::std::string & m32) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1266 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM32(m32);
}
References PointCovariance_pskel::_dnaPointCovariance, and m32().
Referenced by m32().
m33()
void PointCovariance_pimpl::m33 (const ::std::string & m33) virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1271 of file dnaparser_pimpl.cxx.
{
    _dnaPointCovariance->SetM33(m33);
}
References PointCovariance_pskel::_dnaPointCovariance, and m33().
Referenced by m33().
post_PointCovariance()
void PointCovariance_pimpl::post_PointCovariance () virtual
Reimplemented from PointCovariance_pskel.
Definition at line 1276 of file dnaparser_pimpl.cxx.
{
    if (_dnaPointCovariance && _parent_dnaGpsPoint)
        _parent_dnaGpsPoint->AddPointCovariance(
        _dnaPointCovariance.get());
}
References PointCovariance_pskel::_dnaPointCovariance, and PointCovariance_pskel::_parent_dnaGpsPoint.
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx