DynAdjust: Clusterpoint_pimpl Class Reference
Clusterpoint_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void X (const ::std::string &)
virtual void Y (const ::std::string &)
virtual void Z (const ::std::string &)
virtual void SigmaXX (const ::std::string &)
virtual void SigmaXY (const ::std::string &)
virtual void SigmaXZ (const ::std::string &)
virtual void SigmaYY (const ::std::string &)
virtual void SigmaYZ (const ::std::string &)
virtual void SigmaZZ (const ::std::string &)
virtual void PointCovariance ()
virtual void MeasurementDBID (const ::std::string &)
virtual void post_Clusterpoint ()
Public Member Functions inherited from Clusterpoint_pskel
void X_parser (::xml_schema::string_pskel &)
void Y_parser (::xml_schema::string_pskel &)
void Z_parser (::xml_schema::string_pskel &)
void MeasurementDBID_parser (::xml_schema::string_pskel &)
void SigmaXX_parser (::xml_schema::string_pskel &)
void SigmaXY_parser (::xml_schema::string_pskel &)
void SigmaXZ_parser (::xml_schema::string_pskel &)
void SigmaYY_parser (::xml_schema::string_pskel &)
void SigmaYZ_parser (::xml_schema::string_pskel &)
void SigmaZZ_parser (::xml_schema::string_pskel &)
void PointCovariance_parser (::PointCovariance_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::PointCovariance_pskel &)
Clusterpoint_pskel ()
void InitparentGpsPointCluster (dnaMsrPtr pGpsPointCluster)
void InitparentMsrCounter (PUINT32 pMsrCounter)
Protected Attributes
std::string _X
std::string _Y
std::string _Z
std::string _SigmaXX
std::string _SigmaXY
std::string _SigmaXZ
std::string _SigmaYY
std::string _SigmaYZ
std::string _SigmaZZ
Protected Attributes inherited from Clusterpoint_pskel
::xml_schema::string_pskel * X_parser_
::xml_schema::string_pskel * Y_parser_
::xml_schema::string_pskel * Z_parser_
::xml_schema::string_pskel * MeasurementDBID_parser_
::xml_schema::string_pskel * SigmaXX_parser_
::xml_schema::string_pskel * SigmaXY_parser_
::xml_schema::string_pskel * SigmaXZ_parser_
::xml_schema::string_pskel * SigmaYY_parser_
::xml_schema::string_pskel * SigmaYZ_parser_
::xml_schema::string_pskel * SigmaZZ_parser_
::PointCovariance_pskel * PointCovariance_parser_
dnaMsrPtr _dnaGpsPoint
dnaMsrPtr _parent_dnaGpsPointCluster
PUINT32 _pMeasurementCount
Additional Inherited Members
Protected Member Functions inherited from Clusterpoint_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Detailed Description
Definition at line 29 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void Clusterpoint_pimpl::pre () virtual
Definition at line 26 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint.reset(new CDnaGpsPoint);
    // The following is needed so that SetX and SetY can properly handle
    // latitude|X and longitude|Y
    _dnaGpsPoint->SetType(_parent_dnaGpsPointCluster->GetType());
    _dnaGpsPoint->SetCoordType(_parent_dnaGpsPointCluster->GetCoordType());
    _dnaGpsPoint->SetFirst(_parent_dnaGpsPointCluster->GetFirst());
    _dnaGpsPoint->SetClusterID(_parent_dnaGpsPointCluster->GetClusterID());
    _dnaGpsPoint->SetReferenceFrame(_parent_dnaGpsPointCluster->GetReferenceFrame());
    _dnaGpsPoint->SetEpoch(_parent_dnaGpsPointCluster->GetEpoch());
    _dnaGpsPoint->SetClusterDBID(
        _parent_dnaGpsPointCluster->GetClusterDBID(),
        _parent_dnaGpsPointCluster->GetClusterDBIDset());
}
References Clusterpoint_pskel::_dnaGpsPoint, and Clusterpoint_pskel::_parent_dnaGpsPointCluster.
X()
void Clusterpoint_pimpl::X (const ::std::string & X) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 45 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetX(X);
    // increment measurement counter
    *(_pMeasurementCount) += 1;
    g_parsemsr_tally.Y++;
}
References Clusterpoint_pskel::_dnaGpsPoint, Clusterpoint_pskel::_pMeasurementCount, g_parsemsr_tally, and X().
Referenced by X().
Y()
void Clusterpoint_pimpl::Y (const ::std::string & Y) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 54 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetY(Y);
    // increment measurement counter
    *(_pMeasurementCount) += 1;
    g_parsemsr_tally.Y++;
}
References Clusterpoint_pskel::_dnaGpsPoint, Clusterpoint_pskel::_pMeasurementCount, g_parsemsr_tally, and Y().
Referenced by Y().
Z()
void Clusterpoint_pimpl::Z (const ::std::string & Z) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 63 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetZ(Z);
    // increment measurement counter
    *(_pMeasurementCount) += 1;
    g_parsemsr_tally.Y++;
}
References Clusterpoint_pskel::_dnaGpsPoint, Clusterpoint_pskel::_pMeasurementCount, g_parsemsr_tally, and Z().
Referenced by Z().
SigmaXX()
void Clusterpoint_pimpl::SigmaXX (const ::std::string & SigmaXX) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 78 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetSigmaXX(SigmaXX);
}
References Clusterpoint_pskel::_dnaGpsPoint, and SigmaXX().
Referenced by SigmaXX().
SigmaXY()
void Clusterpoint_pimpl::SigmaXY (const ::std::string & SigmaXY) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 83 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetSigmaXY(SigmaXY);
}
References Clusterpoint_pskel::_dnaGpsPoint, and SigmaXY().
Referenced by SigmaXY().
SigmaXZ()
void Clusterpoint_pimpl::SigmaXZ (const ::std::string & SigmaXZ) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 88 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetSigmaXZ(SigmaXZ);
}
References Clusterpoint_pskel::_dnaGpsPoint, and SigmaXZ().
Referenced by SigmaXZ().
SigmaYY()
void Clusterpoint_pimpl::SigmaYY (const ::std::string & SigmaYY) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 93 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetSigmaYY(SigmaYY);
}
References Clusterpoint_pskel::_dnaGpsPoint, and SigmaYY().
Referenced by SigmaYY().
SigmaYZ()
void Clusterpoint_pimpl::SigmaYZ (const ::std::string & SigmaYZ) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 98 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetSigmaYZ(SigmaYZ);
}
References Clusterpoint_pskel::_dnaGpsPoint, and SigmaYZ().
Referenced by SigmaYZ().
SigmaZZ()
void Clusterpoint_pimpl::SigmaZZ (const ::std::string & SigmaZZ) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 103 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetSigmaZZ(SigmaZZ);
}
References Clusterpoint_pskel::_dnaGpsPoint, and SigmaZZ().
Referenced by SigmaZZ().
PointCovariance()
void Clusterpoint_pimpl::PointCovariance () virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 108 of file dnaparser_pimpl.cxx.
{
}
MeasurementDBID()
void Clusterpoint_pimpl::MeasurementDBID (const ::std::string & MeasurementID) virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 72 of file dnaparser_pimpl.cxx.
{
    _dnaGpsPoint->SetMeasurementDBID(MeasurementID);
}
References Clusterpoint_pskel::_dnaGpsPoint.
post_Clusterpoint()
void Clusterpoint_pimpl::post_Clusterpoint () virtual
Reimplemented from Clusterpoint_pskel.
Definition at line 112 of file dnaparser_pimpl.cxx.
{
    if (_dnaGpsPoint && _parent_dnaGpsPointCluster)
        _parent_dnaGpsPointCluster->AddGpsPoint(_dnaGpsPoint.get());
}
References Clusterpoint_pskel::_dnaGpsPoint, and Clusterpoint_pskel::_parent_dnaGpsPointCluster.
Member Data Documentation
_X
std::string Clusterpoint_pimpl::_X protected
Definition at line 47 of file dnaparser_pimpl.hxx.
_Y
std::string Clusterpoint_pimpl::_Y protected
Definition at line 48 of file dnaparser_pimpl.hxx.
_Z
std::string Clusterpoint_pimpl::_Z protected
Definition at line 49 of file dnaparser_pimpl.hxx.
_SigmaXX
std::string Clusterpoint_pimpl::_SigmaXX protected
Definition at line 50 of file dnaparser_pimpl.hxx.
_SigmaXY
std::string Clusterpoint_pimpl::_SigmaXY protected
Definition at line 51 of file dnaparser_pimpl.hxx.
_SigmaXZ
std::string Clusterpoint_pimpl::_SigmaXZ protected
Definition at line 52 of file dnaparser_pimpl.hxx.
_SigmaYY
std::string Clusterpoint_pimpl::_SigmaYY protected
Definition at line 53 of file dnaparser_pimpl.hxx.
_SigmaYZ
std::string Clusterpoint_pimpl::_SigmaYZ protected
Definition at line 54 of file dnaparser_pimpl.hxx.
_SigmaZZ
std::string Clusterpoint_pimpl::_SigmaZZ protected
Definition at line 55 of file dnaparser_pimpl.hxx.
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx