DynAdjust: dna_adjust_progress_thread Class Reference
dna_adjust_progress_thread Class Reference
#include <dnaadjustprogress.hpp>
Public Member Functions
dna_adjust_progress_thread (dna_adjust *dnaAdj, project_settings *p)
void operator() ()
Private Member Functions
void prepareAdjustment ()
void processAdjustment ()
void coutMessage (const std::string &message)
Private Attributes
dna_adjust * _dnaAdj
project_settings * _p
Detailed Description
Definition at line 75 of file dnaadjustprogress.hpp.
Constructor & Destructor Documentation
dna_adjust_progress_thread()
dna_adjust_progress_thread::dna_adjust_progress_thread (dna_adjust * dnaAdj, project_settings * p)
Definition at line 173 of file dnaadjustprogress.cpp.
        : _dnaAdj(dnaAdj), _p(p) {}
References _dnaAdj, and _p.
Member Function Documentation
operator()()
void dna_adjust_progress_thread::operator() ()
Definition at line 348 of file dnaadjustprogress.cpp.
{
    if (_p->g.quiet)
        // Nothing to be displayed
        return;
    // cout messages related to preparing adjustment
    // prepareAdjustment() will continue while the following is true:
    //  running
    //  _dnaAdj->IsPreparing()
    //  !_dnaAdj->ExceptionRaised()
    prepareAdjustment();
    if (_dnaAdj->ExceptionRaised())
        return;
    processAdjustment();
}
References _dnaAdj, _p, prepareAdjustment(), and processAdjustment().
prepareAdjustment()
void dna_adjust_progress_thread::prepareAdjustment () private
Definition at line 176 of file dnaadjustprogress.cpp.
{
    if (_p->g.quiet)
        // Nothing to be displayed
        return;
    if (_p->a.report_mode)
        // Nothing to be displayed
        return;
    std::stringstream ss;
    ss << "+ Preparing for ";
    switch (_p->a.adjust_mode)
    {
    case Phased_Block_1Mode:
    case PhasedMode:
        ss << "a " << _dnaAdj->blockCount() << " block ";
        break;
    }
    ss << "adjustment... ";
    coutMessage(ss.str());
    ss.str("");
    UINT32 block, currentBlock(0);
    std::stringstream sst;
    bool first_time(true);
    switch (_p->a.adjust_mode)
    {
    case SimultaneousMode:
        while (running && _dnaAdj->IsPreparing())
        {
            boost::this_thread::sleep(boost::posix_time::milliseconds(40));
        }
        if (_dnaAdj->ExceptionRaised())
            return;
        ss << " done." << std::endl;
        coutMessage(ss.str());
        break;
    case Phased_Block_1Mode:
    case PhasedMode:
        while (running && _dnaAdj->IsPreparing())
        {
            block = _dnaAdj->CurrentBlock();
            if (block != currentBlock)
            {
                ss.str("");
                ss << " block " << std::left << std::setw(5) << std::fixed << std::setprecision(0) << _dnaAdj->CurrentBlock() + 1;
                sst.str("");
                if (first_time)
                {
                    sst << std::setw(PROGRESS_ADJ_BLOCK_12) << std::left << " ";
                    first_time = false;
                }
                sst << PROGRESS_BACKSPACE_12 << std::setw(PROGRESS_ADJ_BLOCK_12) << std::left << ss.str();
                coutMessage(sst.str());
                currentBlock = block;
            }
            boost::this_thread::sleep(boost::posix_time::milliseconds(40));
        }
        if (_dnaAdj->ExceptionRaised())
            return;
        ss.str("");
        ss << " done.";
        sst.str("");
        if (!first_time)
            sst << PROGRESS_BACKSPACE_12;
        sst << std::setw(PROGRESS_ADJ_BLOCK_12) << std::left << ss.str() << std::endl;
        coutMessage(sst.str());
    }
}
References _dnaAdj, _p, coutMessage(), Phased_Block_1Mode, PhasedMode, PROGRESS_ADJ_BLOCK_12, PROGRESS_BACKSPACE_12, running, and SimultaneousMode.
Referenced by operator()().
processAdjustment()
void dna_adjust_progress_thread::processAdjustment () private
Definition at line 258 of file dnaadjustprogress.cpp.
{
    if (_p->g.quiet)
        // Nothing to be displayed
        return;
    if (_p->a.max_iterations > 0)
        coutMessage(std::string("+ Adjusting network...\n"));
    UINT32 block, currentBlock(0);
    UINT32 currentIteration(0);
    std::stringstream ss, sst;
    bool first_time(true);
    switch (_p->a.adjust_mode)
    {
    case SimultaneousMode:
        while (_dnaAdj->IsAdjusting())
        {
            // use message bank
            while (_dnaAdj->NewMessagesAvailable())
            {
                if (!_dnaAdj->GetMessageIteration(currentIteration))
                    break;
                ss.str("");
                ss << "  Iteration " << std::right << std::setw(2) << std::fixed << std::setprecision(0) << currentIteration;
                ss << ", max station corr: " << std::right << std::setw(PROGRESS_ADJ_BLOCK_12) <<
                    _dnaAdj->GetMaxCorrection(currentIteration) << std::endl;
                coutMessage(ss.str());
            }
            boost::this_thread::sleep(boost::posix_time::milliseconds(80));
        }
        break;
    case Phased_Block_1Mode:
    case PhasedMode:
        while (_dnaAdj->IsAdjusting())
        {
            block = _dnaAdj->CurrentBlock();
            // use message bank
            while (_dnaAdj->NewMessagesAvailable())
            {
                if (!_dnaAdj->GetMessageIteration(currentIteration))
                    break;
                ss.str("");
                ss << "  Iteration " << std::right << std::setw(2) << std::fixed << std::setprecision(0) << currentIteration;
                ss << ", max station corr: " << std::right << std::setw(PROGRESS_ADJ_BLOCK_12) << _dnaAdj->GetMaxCorrection(currentIteration) << std::endl;
                sst.str("");
                if (first_time)
                    sst << std::setw(PROGRESS_ADJ_BLOCK_28) << std::left << " ";
                sst << PROGRESS_BACKSPACE_28 << std::setw(PROGRESS_ADJ_BLOCK_28) << std::left << ss.str();
                coutMessage(sst.str());
                first_time = true;
            }
            boost::this_thread::sleep(boost::posix_time::milliseconds(40));
            // print new block to screen when adjusting only
            if (block != currentBlock && _dnaAdj->IsAdjusting())
            {
                ss.str("");
                ss << "  Iteration " << std::right << std::setw(2) << std::fixed << std::setprecision(0) << _dnaAdj->CurrentIteration();
                if (_p->a.multi_thread && !_dnaAdj->processingCombine())
                    ss << std::left << std::setw(13) << ", adjusting...";
                else
                    ss << ", block " << std::left << std::setw(6) << std::fixed << std::setprecision(0) << _dnaAdj->CurrentBlock() + 1;
                sst.str("");
                if (first_time)
                {
                    sst << std::setw(PROGRESS_ADJ_BLOCK_28) << std::left << " ";
                    first_time = false;
                }
                sst << PROGRESS_BACKSPACE_28 << std::setw(PROGRESS_ADJ_BLOCK_28) << std::left << ss.str();
                coutMessage(sst.str());
                currentBlock = block;
            }
        }
    }
}
References _dnaAdj, _p, coutMessage(), Phased_Block_1Mode, PhasedMode, PROGRESS_ADJ_BLOCK_12, PROGRESS_ADJ_BLOCK_28, PROGRESS_BACKSPACE_28, and SimultaneousMode.
Referenced by operator()().
coutMessage()
void dna_adjust_progress_thread::coutMessage (const std::string & message) private
Definition at line 367 of file dnaadjustprogress.cpp.
{
    cout_mutex.lock();
    std::cout.flush();
    std::cout << message;
    std::cout.flush();
    cout_mutex.unlock();
}
References cout_mutex.
Referenced by prepareAdjustment(), and processAdjustment().
Member Data Documentation
_dnaAdj
dna_adjust* dna_adjust_progress_thread::_dnaAdj private
Definition at line 87 of file dnaadjustprogress.hpp.
Referenced by dna_adjust_progress_thread(), operator()(), prepareAdjustment(), and processAdjustment().
_p
project_settings* dna_adjust_progress_thread::_p private
Definition at line 88 of file dnaadjustprogress.hpp.
Referenced by dna_adjust_progress_thread(), operator()(), prepareAdjustment(), and processAdjustment().
The documentation for this class was generated from the following files:
dynadjust/dnaadjustwrapper/dnaadjustprogress.hpp
dynadjust/dnaadjustwrapper/dnaadjustprogress.cpp