DynAdjust: PairCompareFirst< T, U > Class Template Reference
PairCompareFirst< T, U > Class Template Reference
#include <dnatemplatefuncs.hpp>
Public Member Functions
bool operator() (const string_string_pair &lhs, const string_string_pair &rhs) const
bool operator() (const string_string_pair &lhs, const string_string_pair::first_type &rhs) const
bool operator() (const string_string_pair::first_type &lhs, const string_string_pair &rhs) const
Private Member Functions
bool keyLess (const string_string_pair::first_type &k1, const string_string_pair::first_type &k2) const
Detailed Description
template<typename T, typename U>
class PairCompareFirst< T, U >
Definition at line 1993 of file dnatemplatefuncs.hpp.
Member Function Documentation
operator()() [1/3]
template<typename T, typename U> bool PairCompareFirst< T, U >::operator() (const string_string_pair & lhs, const string_string_pair & rhs) const inline
Definition at line 1997 of file dnatemplatefuncs.hpp.
{
        return keyLess(lhs.first, rhs.first);
    }
References keyLess().
operator()() [2/3]
template<typename T, typename U> bool PairCompareFirst< T, U >::operator() (const string_string_pair & lhs, const string_string_pair::first_type & rhs) const inline
Definition at line 2002 of file dnatemplatefuncs.hpp.
{
        return keyLess(lhs.first, rhs);
    }
References keyLess().
operator()() [3/3]
template<typename T, typename U> bool PairCompareFirst< T, U >::operator() (const string_string_pair::first_type & lhs, const string_string_pair & rhs) const inline
Definition at line 2007 of file dnatemplatefuncs.hpp.
{
        return keyLess(lhs, rhs.first);
    }
References keyLess().
keyLess()
template<typename T, typename U> bool PairCompareFirst< T, U >::keyLess (const string_string_pair::first_type & k1, const string_string_pair::first_type & k2) const inline private
Definition at line 2013 of file dnatemplatefuncs.hpp.
{
        return k1 < k2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this class was generated from the following file:
include/functions/dnatemplatefuncs.hpp