DynAdjust: dynadjust::datum_parameters::CDnaProjection Class Reference
dynadjust::datum_parameters::CDnaProjection Class Reference
#include <dnaprojection.hpp>
Public Member Functions
CDnaProjection (void)
CDnaProjection (const PROJECTION_NAME &pName)
virtual ~CDnaProjection (void)
void SetProjection (const PROJECTION_NAME &pName)
double GetFalseEasting () const
double GetFalseNorthing () const
double GetCentralScaleFactor () const
double GetZoneWidth () const
double GetLongCentralMeridianZone1 () const
double GetLongCentralMeridianZone0 () const
double GetLongWesternEdgeZone0 () const
Private Member Functions
CDnaProjection (const CDnaProjection &newProjection)
CDnaProjection & operator= (const CDnaProjection &rhs)
bool operator== (const CDnaProjection &rhs) const
Private Attributes
double m_dFalseE
double m_dFalseN
double m_dKo
double m_dZw
double m_dLcmZ1
double m_dLweZ0
double m_dLcmZ0
PROJECTION_NAME projectionName
Detailed Description
Definition at line 44 of file dnaprojection.hpp.
Constructor & Destructor Documentation
CDnaProjection() [1/3]
dynadjust::datum_parameters::CDnaProjection::CDnaProjection (void)
Definition at line 28 of file dnaprojection.cpp.
    : m_dFalseE(FALSE_E)
    , m_dFalseN(FALSE_N)        // default to UTM
    , m_dKo(K0), m_dZw(ZW), m_dLcmZ1(LCMZ1), m_dLweZ0(LWEZ0), m_dLcmZ0(LCMZ0)
    , projectionName(UTM)
{
}
References FALSE_E, FALSE_N, K0, LCMZ0, LCMZ1, LWEZ0, m_dFalseE, m_dFalseN, m_dKo, m_dLcmZ0, m_dLcmZ1, m_dLweZ0, m_dZw, projectionName, UTM, and ZW.
Referenced by CDnaProjection(), operator=(), and operator==().
CDnaProjection() [2/3]
dynadjust::datum_parameters::CDnaProjection::CDnaProjection (const PROJECTION_NAME & pName)
Definition at line 37 of file dnaprojection.cpp.
{
    SetProjection(pName);
}
References SetProjection().
~CDnaProjection()
virtual dynadjust::datum_parameters::CDnaProjection::~CDnaProjection (void) inline virtual
Definition at line 51 of file dnaprojection.hpp.
{}
CDnaProjection() [3/3]
dynadjust::datum_parameters::CDnaProjection::CDnaProjection (const CDnaProjection & newProjection) private
References CDnaProjection().
Member Function Documentation
operator=()
CDnaProjection & dynadjust::datum_parameters::CDnaProjection::operator= (const CDnaProjection & rhs) private
References CDnaProjection().
operator==()
bool dynadjust::datum_parameters::CDnaProjection::operator== (const CDnaProjection & rhs) const private
References CDnaProjection().
SetProjection()
void dynadjust::datum_parameters::CDnaProjection::SetProjection (const PROJECTION_NAME & pName)
Definition at line 84 of file dnaprojection.cpp.
{
    switch (pName)
    {
    case UTM:
    default:
        m_dFalseE = FALSE_E;
        m_dFalseN = FALSE_N;
        m_dKo = K0;
        m_dZw = ZW;
        m_dLcmZ1 = LCMZ1;
        m_dLweZ0 = LWEZ0;
        m_dLcmZ0 = LCMZ0;
        projectionName = pName;
        break;
    }
}
References FALSE_E, FALSE_N, K0, LCMZ0, LCMZ1, LWEZ0, m_dFalseE, m_dFalseN, m_dKo, m_dLcmZ0, m_dLcmZ1, m_dLweZ0, m_dZw, projectionName, UTM, and ZW.
Referenced by CDnaProjection().
GetFalseEasting()
double dynadjust::datum_parameters::CDnaProjection::GetFalseEasting () const inline
Definition at line 68 of file dnaprojection.hpp.
{ return m_dFalseE; }
References m_dFalseE.
Referenced by dynadjust::measurements::CDnaStation::ReduceStations_LLH(), and dynadjust::measurements::CDnaStation::ReduceStations_XYZ().
GetFalseNorthing()
double dynadjust::datum_parameters::CDnaProjection::GetFalseNorthing () const inline
Definition at line 69 of file dnaprojection.hpp.
{ return m_dFalseN; }
References m_dFalseN.
Referenced by dynadjust::measurements::CDnaStation::ReduceStations_LLH(), and dynadjust::measurements::CDnaStation::ReduceStations_XYZ().
GetCentralScaleFactor()
double dynadjust::datum_parameters::CDnaProjection::GetCentralScaleFactor () const inline
Definition at line 70 of file dnaprojection.hpp.
{ return m_dKo; }
References m_dKo.
Referenced by dynadjust::measurements::CDnaStation::ReduceStations_LLH(), and dynadjust::measurements::CDnaStation::ReduceStations_XYZ().
GetZoneWidth()
double dynadjust::datum_parameters::CDnaProjection::GetZoneWidth () const inline
Definition at line 71 of file dnaprojection.hpp.
{ return m_dZw; }
References m_dZw.
Referenced by GeoToGrid(), dynadjust::measurements::CDnaStation::ReduceStations_LLH(), and dynadjust::measurements::CDnaStation::ReduceStations_XYZ().
GetLongCentralMeridianZone1()
double dynadjust::datum_parameters::CDnaProjection::GetLongCentralMeridianZone1 () const inline
Definition at line 72 of file dnaprojection.hpp.
{ return m_dLcmZ1; }
References m_dLcmZ1.
Referenced by dynadjust::measurements::CDnaStation::ReduceStations_LLH(), and dynadjust::measurements::CDnaStation::ReduceStations_XYZ().
GetLongCentralMeridianZone0()
double dynadjust::datum_parameters::CDnaProjection::GetLongCentralMeridianZone0 () const inline
Definition at line 73 of file dnaprojection.hpp.
{ return m_dLcmZ0; }
References m_dLcmZ0.
Referenced by GeoToGrid().
GetLongWesternEdgeZone0()
double dynadjust::datum_parameters::CDnaProjection::GetLongWesternEdgeZone0 () const inline
Definition at line 74 of file dnaprojection.hpp.
{ return m_dLweZ0; }
References m_dLweZ0.
Referenced by GeoToGrid().
Member Data Documentation
m_dFalseE
double dynadjust::datum_parameters::CDnaProjection::m_dFalseE private
Definition at line 80 of file dnaprojection.hpp.
Referenced by CDnaProjection(), GetFalseEasting(), and SetProjection().
m_dFalseN
double dynadjust::datum_parameters::CDnaProjection::m_dFalseN private
Definition at line 81 of file dnaprojection.hpp.
Referenced by CDnaProjection(), GetFalseNorthing(), and SetProjection().
m_dKo
double dynadjust::datum_parameters::CDnaProjection::m_dKo private
Definition at line 82 of file dnaprojection.hpp.
Referenced by CDnaProjection(), GetCentralScaleFactor(), and SetProjection().
m_dZw
double dynadjust::datum_parameters::CDnaProjection::m_dZw private
Definition at line 83 of file dnaprojection.hpp.
Referenced by CDnaProjection(), GetZoneWidth(), and SetProjection().
m_dLcmZ1
double dynadjust::datum_parameters::CDnaProjection::m_dLcmZ1 private
Definition at line 84 of file dnaprojection.hpp.
Referenced by CDnaProjection(), GetLongCentralMeridianZone1(), and SetProjection().
m_dLweZ0
double dynadjust::datum_parameters::CDnaProjection::m_dLweZ0 private
Definition at line 85 of file dnaprojection.hpp.
Referenced by CDnaProjection(), GetLongWesternEdgeZone0(), and SetProjection().
m_dLcmZ0
double dynadjust::datum_parameters::CDnaProjection::m_dLcmZ0 private
Definition at line 86 of file dnaprojection.hpp.
Referenced by CDnaProjection(), GetLongCentralMeridianZone0(), and SetProjection().
projectionName
PROJECTION_NAME dynadjust::datum_parameters::CDnaProjection::projectionName private
Definition at line 88 of file dnaprojection.hpp.
Referenced by CDnaProjection(), and SetProjection().
The documentation for this class was generated from the following files:
include/parameters/dnaprojection.hpp
include/parameters/dnaprojection.cpp