DynAdjust: dynadjust::exception::NetSegmentException Class Reference
dynadjust::exception::NetSegmentException Class Reference
#include <dnaexception.hpp>
Public Member Functions
NetSegmentException (const std::string &what, const UINT32 &line_no)
virtual const char * what () const throw ()
virtual ~NetSegmentException () throw ()
Private Attributes
std::string what_
UINT32 line_no_
Detailed Description
Definition at line 111 of file dnaexception.hpp.
Constructor & Destructor Documentation
NetSegmentException()
dynadjust::exception::NetSegmentException::NetSegmentException (const std::string & what, const UINT32 & line_no) inline explicit
Definition at line 114 of file dnaexception.hpp.
        : what_(what), line_no_(line_no) {}
References line_no_, what(), and what_.
~NetSegmentException()
virtual dynadjust::exception::NetSegmentException::~NetSegmentException () throw () inline virtual
Definition at line 117 of file dnaexception.hpp.
{}
Member Function Documentation
what()
virtual const char * dynadjust::exception::NetSegmentException::what () const throw () inline virtual
Definition at line 116 of file dnaexception.hpp.
{ return what_.c_str(); }
References what_.
Referenced by NetSegmentException(), and dna_segment_thread::operator()().
Member Data Documentation
what_
std::string dynadjust::exception::NetSegmentException::what_ private
Definition at line 120 of file dnaexception.hpp.
Referenced by NetSegmentException(), and what().
line_no_
UINT32 dynadjust::exception::NetSegmentException::line_no_ private
Definition at line 121 of file dnaexception.hpp.
Referenced by NetSegmentException().
The documentation for this class was generated from the following file:
include/exception/dnaexception.hpp