DynAdjust: dynadjust::iostreams::dna_io_dna Class Reference
dynadjust::iostreams::dna_io_dna Class Reference
#include <dnaiodna.hpp>
Public Member Functions
dna_io_dna (void)
dna_io_dna (const dna_io_dna &dna)
virtual ~dna_io_dna (void)
dna_io_dna & operator= (const dna_io_dna &rhs)
void read_ren_file (const std::string &filename, pv_string_vstring_pair stnRenaming)
void write_dna_files (vdnaStnPtr *vStations, vdnaMsrPtr *vMeasurements, const std::string &stnfilename, const std::string &msrfilename, const std::string &networkname, const CDnaDatum &datum, const CDnaProjection &projection, bool flagUnused, const std::string &stn_comment, const std::string &msr_comment)
void write_dna_files (pvstn_t vbinary_stn, pvmsr_t vbinary_msr, const std::string &stnfilename, const std::string &msrfilename, const std::string &networkname, const CDnaDatum &datum, const CDnaProjection &projection, bool flagUnused, const std::string &stn_comment, const std::string &msr_comment)
void write_stn_file (vdnaStnPtr *vStations, const std::string &stnfilename, const std::string &networkname, const CDnaDatum &datum, const CDnaProjection &projection, bool flagUnused, const std::string &comment)
void write_stn_file (pvstn_t vbinary_stn, const std::string &stnfilename, const std::string &networkname, const CDnaDatum &datum, const CDnaProjection &projection, bool flagUnused, const std::string &comment)
void write_msr_file (vdnaMsrPtr *vMeasurements, const std::string &msrfilename, const std::string &networkname, const CDnaDatum &datum, const std::string &comment)
void write_msr_file (const vstn_t &binaryStn, pvmsr_t vbinary_msr, const std::string &msrfilename, const std::string &networkname, const CDnaDatum &datum, const std::string &comment)
void read_dna_header (std::ifstream *ptr, std::string &version, INPUT_DATA_TYPE &idt, CDnaDatum &referenceframe, std::string &fileEpsg, std::string &fileEpoch, std::string &geoidversion, UINT32 &count)
const dna_stn_fields dna_stn_positions ()
const dna_stn_fields dna_stn_widths ()
const dna_msr_fields dna_msr_positions ()
const dna_msr_fields dna_msr_widths ()
void set_dbid_ptr (pv_msr_database_id_map pv_msr_db_map)
bool filespecifiedReferenceFrame ()
bool filespecifiedEpoch ()
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Private Member Functions
void create_file_stn (std::ofstream *ptr, const std::string &filename)
void create_file_msr (std::ofstream *ptr, const std::string &filename)
void create_file_pointer (std::ofstream *ptr, const std::string &filename)
void open_file_pointer (std::ifstream *ptr, const std::string &filename)
void write_stn_header_data (std::ofstream *ptr, const std::string &networkname, const std::string &datum, const std::string &epoch, const size_t &count, const std::string &comment)
void write_stn_header (std::ofstream *ptr, vdnaStnPtr *vStations, const std::string &networkname, const CDnaDatum &datum, bool flagUnused, const std::string &comment)
void write_stn_header (std::ofstream *ptr, pvstn_t vbinary_stn, const std::string &networkname, const CDnaDatum &datum, bool flagUnused, const std::string &comment)
void write_msr_header_data (std::ofstream *ptr, const std::string &networkname, const std::string &datum, const std::string &epoch, const size_t &count, const std::string &comment)
void write_msr_header (std::ofstream *ptr, vdnaMsrPtr *vMeasurements, const std::string &networkname, const CDnaDatum &datum, const std::string &comment)
void write_msr_header (std::ofstream *ptr, pvmsr_t vbinary_msrn, const std::string &networkname, const CDnaDatum &datum, const std::string &comment)
void read_ren_data (std::ifstream *ptr, pv_string_vstring_pair stnRenaming)
void prepare_sort_list (const UINT32 count)
Private Attributes
dna_stn_fields dsl_
dna_stn_fields dsw_
dna_msr_fields dml_
dna_msr_fields dmw_
vUINT32 vStationList_
pv_msr_database_id_map pv_msr_db_map_
bool m_databaseIDsSet_
bool m_filespecifiedReferenceFrame_
bool m_filespecifiedEpoch_
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 48 of file dnaiodna.hpp.
Constructor & Destructor Documentation
dna_io_dna() [1/2]
dynadjust::iostreams::dna_io_dna::dna_io_dna (void) inline
Definition at line 51 of file dnaiodna.hpp.
        : pv_msr_db_map_(0)
        , m_databaseIDsSet_(false)
        , m_filespecifiedReferenceFrame_(false)
        , m_filespecifiedEpoch_(false) {
    };
References m_databaseIDsSet_, m_filespecifiedEpoch_, m_filespecifiedReferenceFrame_, and pv_msr_db_map_.
Referenced by dna_io_dna(), and operator=().
dna_io_dna() [2/2]
dynadjust::iostreams::dna_io_dna::dna_io_dna (const dna_io_dna & dna) inline
Definition at line 57 of file dnaiodna.hpp.
        : dna_io_base(dna)
        , pv_msr_db_map_(0)
        , m_databaseIDsSet_(false)
        , m_filespecifiedReferenceFrame_(false)
        , m_filespecifiedEpoch_(false) {
    };
References dna, dynadjust::iostreams::dna_io_base::dna_io_base(), dna_io_dna(), m_databaseIDsSet_, m_filespecifiedEpoch_, m_filespecifiedReferenceFrame_, and pv_msr_db_map_.
~dna_io_dna()
virtual dynadjust::iostreams::dna_io_dna::~dna_io_dna (void) inline virtual
Definition at line 64 of file dnaiodna.hpp.
{};
Member Function Documentation
operator=()
dna_io_dna & dynadjust::iostreams::dna_io_dna::operator= (const dna_io_dna & rhs)
References dna_io_dna().
read_ren_file()
void dynadjust::iostreams::dna_io_dna::read_ren_file (const std::string & filename, pv_string_vstring_pair stnRenaming)
Definition at line 154 of file dnaiodna.cpp.
{
    std::ifstream renaming_file;
    // create file pointer
    open_file_pointer(&renaming_file, filename);
    std::string version;
    INPUT_DATA_TYPE idt;
    CDnaDatum datum;
    std::string geoidVersion, fileEpsg, fileEpoch;
    UINT32 count(0);
    // read header information
    read_dna_header(&renaming_file, version, idt, datum, fileEpsg, fileEpoch, geoidVersion, count);
    read_ren_data(&renaming_file, stnRenaming);
    renaming_file.close();
}
References open_file_pointer(), read_dna_header(), and read_ren_data().
write_dna_files() [1/2]
void dynadjust::iostreams::dna_io_dna::write_dna_files (vdnaStnPtr * vStations, vdnaMsrPtr * vMeasurements, const std::string & stnfilename, const std::string & msrfilename, const std::string & networkname, const CDnaDatum & datum, const CDnaProjection & projection, bool flagUnused, const std::string & stn_comment, const std::string & msr_comment)
Definition at line 33 of file dnaiodna.cpp.
{
    write_stn_file(vStations, stnfilename, networkname, datum, projection, flagUnused, stn_comment);
    write_msr_file(vMeasurements, msrfilename, networkname, datum, msr_comment);
}
References write_msr_file(), and write_stn_file().
write_dna_files() [2/2]
void dynadjust::iostreams::dna_io_dna::write_dna_files (pvstn_t vbinary_stn, pvmsr_t vbinary_msr, const std::string & stnfilename, const std::string & msrfilename, const std::string & networkname, const CDnaDatum & datum, const CDnaProjection & projection, bool flagUnused, const std::string & stn_comment, const std::string & msr_comment)
Definition at line 43 of file dnaiodna.cpp.
{
    write_stn_file(vbinary_stn, stnfilename, networkname, datum, projection, flagUnused, stn_comment);
    write_msr_file(*vbinary_stn, vbinary_msr, msrfilename, networkname, datum, msr_comment);
}
References write_msr_file(), and write_stn_file().
write_stn_file() [1/2]
void dynadjust::iostreams::dna_io_dna::write_stn_file (vdnaStnPtr * vStations, const std::string & stnfilename, const std::string & networkname, const CDnaDatum & datum, const CDnaProjection & projection, bool flagUnused, const std::string & comment)
Definition at line 480 of file dnaiodna.cpp.
{
    // Print DNA stations from a vector of dnaStnPtr
    std::ofstream dna_stn_file;
    try {
        // Create file pointer
        create_file_stn(&dna_stn_file, stnfilename);
        // Write header and comment
        write_stn_header(&dna_stn_file, vStations, networkname, datum, flagUnused, comment);
        // Sort on original file order
        std::sort(vStations->begin(), vStations->end(), CompareStnFileOrder_CDnaStn<CDnaStation>());
        // print stations
        // Has the user specified --flag-unused-stations, in wich case, do not
        // print stations marked unused?
        if (flagUnused)
        {
            // Print stations in DNA format
            for_each(vStations->begin(), vStations->end(),
                [&dna_stn_file, &projection, &datum, this](const dnaStnPtr& stn) {
                    if (stn.get()->IsNotUnused())
                        stn.get()->WriteDNAXMLStnCurrentEstimates(&dna_stn_file, datum.GetEllipsoidRef(),
                            const_cast<CDnaProjection*>(&projection), dna, &dsw_);
            });
        }
        else
        {
            // Print stations in DNA format
            for_each(vStations->begin(), vStations->end(),
                [&dna_stn_file, &projection, &datum, this](const dnaStnPtr& stn) {
                    stn.get()->WriteDNAXMLStnCurrentEstimates(&dna_stn_file, datum.GetEllipsoidRef(),
                        const_cast<CDnaProjection*>(&projection), dna, &dsw_);
            });
        }
        dna_stn_file.close();
    }
    catch (const std::ifstream::failure& f) {
        throw boost::enable_current_exception(std::runtime_error(f.what()));
    }
}
References create_file_stn(), write_stn_file(), and write_stn_header().
Referenced by write_dna_files(), write_dna_files(), and write_stn_file().
write_stn_file() [2/2]
void dynadjust::iostreams::dna_io_dna::write_stn_file (pvstn_t vbinary_stn, const std::string & stnfilename, const std::string & networkname, const CDnaDatum & datum, const CDnaProjection & projection, bool flagUnused, const std::string & comment)
Definition at line 423 of file dnaiodna.cpp.
{
    // Print DNA stations from a vector of stn_t
    std::ofstream dna_stn_file;
    try {
        // Create file pointer
        create_file_stn(&dna_stn_file, stnfilename);
        // Write header and comment
        write_stn_header(&dna_stn_file, vbinary_stn, networkname, datum, flagUnused, comment);
        // Sort on original file order
        prepare_sort_list(static_cast<UINT32>(vbinary_stn->size()));
        CompareStnFileOrder<station_t, UINT32> stnorderCompareFunc(vbinary_stn);
        std::sort(vStationList_.begin(), vStationList_.end(), stnorderCompareFunc);
        dnaStnPtr stnPtr(new CDnaStation(datum.GetName(), datum.GetEpoch_s()));
        // print stations
        // Has the user specified --flag-unused-stations, in wich case, do not
        // print stations marked unused?
        if (flagUnused)
        {
            // Print stations in DNA format
            for_each(vStationList_.begin(), vStationList_.end(),
                [&dna_stn_file, &stnPtr, &projection, &datum, &vbinary_stn, this](const UINT32& stn) {
                    if (stnPtr->IsNotUnused())
                    {
                        stnPtr->SetStationRec(vbinary_stn->at(stn));
                        stnPtr->WriteDNAXMLStnCurrentEstimates(&dna_stn_file, datum.GetEllipsoidRef(),
                            const_cast<CDnaProjection*>(&projection), dna, &dsw_);
                    }
            });
        }
        else
        {
            // Print stations in DNA format
            for_each(vStationList_.begin(), vStationList_.end(),
                [&dna_stn_file, &stnPtr, &projection, &datum, &vbinary_stn, this](const UINT32& stn) {
                    stnPtr->SetStationRec(vbinary_stn->at(stn));
                    stnPtr->WriteDNAXMLStnCurrentEstimates(&dna_stn_file, datum.GetEllipsoidRef(),
                        const_cast<CDnaProjection*>(&projection), dna, &dsw_);
            });
        }
        dna_stn_file.close();
    }
    catch (const std::ifstream::failure& f) {
        throw boost::enable_current_exception(std::runtime_error(f.what()));
    }
}
References create_file_stn(), dynadjust::datum_parameters::CDnaDatum::GetEpoch_s(), dynadjust::datum_parameters::CDnaDatum::GetName(), prepare_sort_list(), vStationList_, and write_stn_header().
write_msr_file() [1/2]
void dynadjust::iostreams::dna_io_dna::write_msr_file (vdnaMsrPtr * vMeasurements, const std::string & msrfilename, const std::string & networkname, const CDnaDatum & datum, const std::string & comment)
Definition at line 603 of file dnaiodna.cpp.
{
    // Print DNA measurements
    std::ofstream dna_msr_file;
    _it_vdnamsrptr _it_msr(vMeasurements->begin());
    size_t dbindex;
    it_vdbid_t _it_dbid;
    try {
        // Create file pointer
        create_file_msr(&dna_msr_file, msrfilename);
        // Write header and comment
        write_msr_header(&dna_msr_file, vMeasurements, networkname, datum, comment);
        // print measurements
        for (_it_msr = vMeasurements->begin(); _it_msr != vMeasurements->end(); _it_msr++)
        {
            // Get database IDs
            dbindex = std::distance(vMeasurements->begin(), _it_msr);
            _it_dbid = pv_msr_db_map_->begin() + dbindex;
            _it_msr->get()->SetDatabaseMaps(_it_dbid);
            // Write
            _it_msr->get()->WriteDNAMsr(&dna_msr_file, dmw_, dml_);
        }
        dna_msr_file.close();
    }
    catch (const std::ifstream::failure& f) {
        throw boost::enable_current_exception(std::runtime_error(f.what()));
    }
}
References create_file_msr(), dml_, dmw_, pv_msr_db_map_, write_msr_file(), and write_msr_header().
Referenced by write_dna_files(), write_dna_files(), write_msr_file(), and write_msr_file().
write_msr_file() [2/2]
void dynadjust::iostreams::dna_io_dna::write_msr_file (const vstn_t & binaryStn, pvmsr_t vbinary_msr, const std::string & msrfilename, const std::string & networkname, const CDnaDatum & datum, const std::string & comment)
Definition at line 560 of file dnaiodna.cpp.
{
    // Print DNA measurements
    std::ofstream dna_msr_file;
    it_vmsr_t _it_msr(vbinary_msr->begin());
    dnaMsrPtr msrPtr;
    size_t dbindex;
    it_vdbid_t _it_dbid;
    try {
        // Create file pointer
        create_file_msr(&dna_msr_file, msrfilename);
        // Write header and comment
        write_msr_header(&dna_msr_file, vbinary_msr, networkname, datum, comment);
        // print measurements
        for (_it_msr=vbinary_msr->begin(); _it_msr!=vbinary_msr->end(); ++_it_msr)
        {
            ResetMeasurementPtr<char>(&msrPtr, _it_msr->measType);
            // Database IDs
            if (m_databaseIDsSet_)
            {
                dbindex = std::distance(vbinary_msr->begin(), _it_msr);
                _it_dbid = pv_msr_db_map_->begin() + dbindex;
            }
            msrPtr->SetMeasurementRec(vbinary_stn, _it_msr, _it_dbid);
            msrPtr->WriteDNAMsr(&dna_msr_file, dmw_, dml_);
        }
        dna_msr_file.close();
    }
    catch (const std::ifstream::failure& f) {
        throw boost::enable_current_exception(std::runtime_error(f.what()));
    }
}
References create_file_msr(), dml_, dmw_, m_databaseIDsSet_, pv_msr_db_map_, ResetMeasurementPtr(), write_msr_file(), and write_msr_header().
read_dna_header()
void dynadjust::iostreams::dna_io_dna::read_dna_header (std::ifstream * ptr, std::string & version, INPUT_DATA_TYPE & idt, CDnaDatum & referenceframe, std::string & fileEpsg, std::string & fileEpoch, std::string & geoidversion, UINT32 & count)
Definition at line 251 of file dnaiodna.cpp.
{
    std::string sBuf;
    getline((*ptr), sBuf);
    sBuf = trimstr(sBuf);
    m_filespecifiedReferenceFrame_ = false;
    m_filespecifiedEpoch_ = false;
    // Set the default version
    version = "1.00";
    // Attempt to get the file's version
    try {
        if (boost::iequals("!#=DNA", sBuf.substr(0, 6)))
            version = trimstr(sBuf.substr(6, 6));
    }
    catch (const std::runtime_error& e) {
        throw boost::enable_current_exception(std::runtime_error(e.what()));
    }
    // Attempt to get the file's type
    try {
        determineDNASTNFieldParameters<UINT16>(version, dsl_, dsw_);
        determineDNAMSRFieldParameters<UINT16>(version, dml_, dmw_);
    }
    catch (const std::runtime_error& e) {
        std::stringstream ssError;
        ssError << "- Error: Unable to determine DNA file version." << std::endl <<
            sBuf << std::endl << " " << e.what() << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ssError.str()));
    }
    // Version 1
    if (boost::iequals(version, "1.00"))
    {
        idt = unknown;                           // could be stn or msr
        count = 100;                            // set default 100 stations
        return;
    }
    std::string type;
    // Attempt to get the file's type
    try {
        type = trimstr(sBuf.substr(12, 3));
    }
    catch (const std::runtime_error& e) {
        std::stringstream ssError;
        ssError << "- Error: File type has not been provided in the header" << std::endl <<
            sBuf << std::endl << e.what() << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ssError.str()));
    }
    // Station file
    if (boost::iequals(type, "stn"))
        idt = stn_data;
    // Measurement file
    else if (boost::iequals(type, "msr"))
        idt = msr_data;
    // Geoid information file
    else if (boost::iequals(type, "geo"))
        idt = geo_data;
    // Station renaming
    else if (boost::iequals(type, "ren"))
        idt = ren_data;
    else
    {
        idt = unknown;
        std::stringstream ssError;
        ssError << "The supplied filetype '" << type << "' is not recognised" << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ssError.str()));
    }
    if (sBuf.length() < 29)
    {
        count = 100;
        return;
    }
    std::string file_referenceframe;
    // Attempt to get the default reference frame
    try {
        if (sBuf.length() > 42)
            file_referenceframe = trimstr(sBuf.substr(29, 14));
        else if (sBuf.length() > 29)
            file_referenceframe = trimstr(sBuf.substr(29));
        else
            file_referenceframe = "";
    }
    catch (...) {
        // datum not provided?
        file_referenceframe = "";
    }
    if (!file_referenceframe.empty())
        m_filespecifiedReferenceFrame_ = true;
    std::string epoch_version;
    // Attempt to get the default epoch / geoid version
    try {
        if (sBuf.length() > 56)
            epoch_version = trimstr(sBuf.substr(43, 14));
        else if (sBuf.length() > 43)
            epoch_version = trimstr(sBuf.substr(43));
        else
            epoch_version = "";
    }
    catch (...) {
        // epoch / version not provided?
        epoch_version = "";
    }
    if (!epoch_version.empty())
        m_filespecifiedEpoch_ = true;
    // Try to get the reference frame
    // For the first file, and unless the user has specified a reference frame,
    // the reference frame will be used to set the frame for all other files.
    try {
        switch (idt)
        {
        case stn_data:
        case msr_data:
            // Capture file epsg
            if (file_referenceframe.empty())
                // Empty? Get the epsg code from the project datum
                fileEpsg = referenceframe.GetEpsgCode_s();
            else
                fileEpsg = epsgStringFromName<std::string>(file_referenceframe);
            // capture file epoch
            if (epoch_version.empty())
            {
                // Empty?  Get the epoch of the nominated epsg (set above)
                fileEpoch = referenceepochFromEpsgString<std::string>(fileEpsg);
            }
            else
                fileEpoch = epoch_version;
            break;
        case geo_data:
            geoidversion = epoch_version;
            break;
        default:
            break;
        }
    }
    catch (const std::runtime_error& e) {
        std::stringstream ssError;
        ssError << "The supplied frame (" << file_referenceframe << ") is not recognised" << std::endl <<
            e.what() << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ssError.str()));
    }
    // Attempt to get the data count
    try {
        if (sBuf.length() > 66)
            count = val_uint<UINT32, std::string>(trimstr(sBuf.substr(57, 10)));
        else if (sBuf.length() > 57)
            count = val_uint<UINT32, std::string>(trimstr(sBuf.substr(57)));
        else
            count = 100;
    }
    catch (...) {
        count = 100;
    }
}
References determineDNAMSRFieldParameters(), determineDNASTNFieldParameters(), dml_, dmw_, dsl_, dsw_, dynadjust::epsg::epsgStringFromName(), geo_data, m_filespecifiedEpoch_, m_filespecifiedReferenceFrame_, msr_data, dynadjust::epsg::referenceepochFromEpsgString(), ren_data, stn_data, trimstr(), unknown, and val_uint().
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNA(), and read_ren_file().
dna_stn_positions()
const dna_stn_fields dynadjust::iostreams::dna_io_dna::dna_stn_positions () inline
Definition at line 101 of file dnaiodna.hpp.
{ return dsl_; }
References dsl_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNA().
dna_stn_widths()
const dna_stn_fields dynadjust::iostreams::dna_io_dna::dna_stn_widths () inline
Definition at line 102 of file dnaiodna.hpp.
{ return dsw_; }
References dsw_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNA().
dna_msr_positions()
const dna_msr_fields dynadjust::iostreams::dna_io_dna::dna_msr_positions () inline
Definition at line 103 of file dnaiodna.hpp.
{ return dml_; }
References dml_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNA().
dna_msr_widths()
const dna_msr_fields dynadjust::iostreams::dna_io_dna::dna_msr_widths () inline
Definition at line 104 of file dnaiodna.hpp.
{ return dmw_; }
References dmw_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNA().
set_dbid_ptr()
void dynadjust::iostreams::dna_io_dna::set_dbid_ptr (pv_msr_database_id_map pv_msr_db_map)
Definition at line 643 of file dnaiodna.cpp.
{
    pv_msr_db_map_ = pv_msr_db_map;
    if (pv_msr_db_map->size() > 0)
        m_databaseIDsSet_ = true;
    else
        m_databaseIDsSet_ = false;
}
References m_databaseIDsSet_, pv_msr_db_map_, and set_dbid_ptr().
Referenced by set_dbid_ptr().
filespecifiedReferenceFrame()
bool dynadjust::iostreams::dna_io_dna::filespecifiedReferenceFrame () inline
Definition at line 108 of file dnaiodna.hpp.
{ return m_filespecifiedReferenceFrame_; }
References m_filespecifiedReferenceFrame_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNA().
filespecifiedEpoch()
bool dynadjust::iostreams::dna_io_dna::filespecifiedEpoch () inline
Definition at line 109 of file dnaiodna.hpp.
{ return m_filespecifiedEpoch_; }
References m_filespecifiedEpoch_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseDNA().
create_file_stn()
void dynadjust::iostreams::dna_io_dna::create_file_stn (std::ofstream * ptr, const std::string & filename) private
Definition at line 52 of file dnaiodna.cpp.
{
    determineDNASTNFieldParameters<UINT16>("3.01", dsl_, dsw_);
    create_file_pointer(ptr, filename);
}
References create_file_pointer(), determineDNASTNFieldParameters(), dsl_, and dsw_.
Referenced by write_stn_file(), and write_stn_file().
create_file_msr()
void dynadjust::iostreams::dna_io_dna::create_file_msr (std::ofstream * ptr, const std::string & filename) private
Definition at line 58 of file dnaiodna.cpp.
{
    determineDNAMSRFieldParameters<UINT16>("3.01", dml_, dmw_);
    create_file_pointer(ptr, filename);
}
References create_file_pointer(), determineDNAMSRFieldParameters(), dml_, and dmw_.
Referenced by write_msr_file(), and write_msr_file().
create_file_pointer()
void dynadjust::iostreams::dna_io_dna::create_file_pointer (std::ofstream * ptr, const std::string & filename) private
Definition at line 72 of file dnaiodna.cpp.
{
    try {
        // Create file pointer to DNA file.
        file_opener(*ptr, filename);
    }
    catch (const std::runtime_error& e) {
        throw boost::enable_current_exception(std::runtime_error(e.what()));
    }
}
References file_opener().
Referenced by create_file_msr(), and create_file_stn().
open_file_pointer()
void dynadjust::iostreams::dna_io_dna::open_file_pointer (std::ifstream * ptr, const std::string & filename) private
Definition at line 83 of file dnaiodna.cpp.
{
    try {
        // Open DNA file.
        file_opener(*ptr, filename, std::ios::in, ascii, true);
    }
    catch (const std::runtime_error& e) {
        throw boost::enable_current_exception(std::runtime_error(e.what()));
    }
}
References ascii, and file_opener().
Referenced by read_ren_file().
write_stn_header_data()
void dynadjust::iostreams::dna_io_dna::write_stn_header_data (std::ofstream * ptr, const std::string & networkname, const std::string & datum, const std::string & epoch, const size_t & count, const std::string & comment) private
Definition at line 94 of file dnaiodna.cpp.
{
    // Write version line
    dna_header(*ptr, "3.01", "STN", datum, epoch, count);
    // Write comments
    dna_comment(*ptr, "File type:    Station file");
    dna_comment(*ptr, "Project name: " + networkname);
    // Write header comment line, e.g. "Coordinates exported from reftran."
    dna_comment(*ptr, comment);
}
References dna_comment(), and dna_header().
Referenced by write_stn_header(), and write_stn_header().
write_stn_header() [1/2]
void dynadjust::iostreams::dna_io_dna::write_stn_header (std::ofstream * ptr, vdnaStnPtr * vStations, const std::string & networkname, const CDnaDatum & datum, bool flagUnused, const std::string & comment) private
Definition at line 108 of file dnaiodna.cpp.
{
    // print stations
    // Has the user specified --flag-unused-stations, in which case, do not
    // print stations marked unused?
    size_t count(0);
    if (flagUnused)
    {
        for_each(vStations->begin(), vStations->end(),
            [&count](const dnaStnPtr& stn) {
                if (stn.get()->IsNotUnused())
                    count++;
        });
    }
    else
        count = vStations->size();
    // write header
    write_stn_header_data(ptr, networkname, datum.GetName(), datum.GetEpoch_s(), count, comment);
}
References dynadjust::datum_parameters::CDnaDatum::GetEpoch_s(), dynadjust::datum_parameters::CDnaDatum::GetName(), and write_stn_header_data().
Referenced by write_stn_file(), and write_stn_file().
write_stn_header() [2/2]
void dynadjust::iostreams::dna_io_dna::write_stn_header (std::ofstream * ptr, pvstn_t vbinary_stn, const std::string & networkname, const CDnaDatum & datum, bool flagUnused, const std::string & comment) private
Definition at line 131 of file dnaiodna.cpp.
{
    // print stations
    // Has the user specified --flag-unused-stations, in which case, do not
    // print stations marked unused?
    size_t count(0);
    if (flagUnused)
    {
        for_each(vbinary_stn->begin(), vbinary_stn->end(),
            [&count](const station_t& stn) {
                if (stn.unusedStation == 0)
                    count++;
        });
    }
    else
        count = vbinary_stn->size();
    // write header
    write_stn_header_data(ptr, networkname, datum.GetName(), datum.GetEpoch_s(), count, comment);
}
References dynadjust::datum_parameters::CDnaDatum::GetEpoch_s(), dynadjust::datum_parameters::CDnaDatum::GetName(), and write_stn_header_data().
write_msr_header_data()
void dynadjust::iostreams::dna_io_dna::write_msr_header_data (std::ofstream * ptr, const std::string & networkname, const std::string & datum, const std::string & epoch, const size_t & count, const std::string & comment) private
Definition at line 528 of file dnaiodna.cpp.
{
    // Write version line
    dna_header(*ptr, "3.01", "MSR", datum, epoch, count);
    // Write comments
    dna_comment(*ptr, "File type:    Measurement file");
    dna_comment(*ptr, "Project name: " + networkname);
    // Write header comment line
    dna_comment(*ptr, comment);
}
References dna_comment(), dna_header(), and write_msr_header_data().
Referenced by write_msr_header(), write_msr_header(), and write_msr_header_data().
write_msr_header() [1/2]
void dynadjust::iostreams::dna_io_dna::write_msr_header (std::ofstream * ptr, vdnaMsrPtr * vMeasurements, const std::string & networkname, const CDnaDatum & datum, const std::string & comment) private
Definition at line 544 of file dnaiodna.cpp.
{
    // write header
    write_msr_header_data(ptr, networkname, datum.GetName(), datum.GetEpoch_s(), vMeasurements->size(), comment);
}
References dynadjust::datum_parameters::CDnaDatum::GetEpoch_s(), dynadjust::datum_parameters::CDnaDatum::GetName(), write_msr_header(), and write_msr_header_data().
Referenced by write_msr_file(), write_msr_file(), write_msr_header(), and write_msr_header().
write_msr_header() [2/2]
void dynadjust::iostreams::dna_io_dna::write_msr_header (std::ofstream * ptr, pvmsr_t vbinary_msrn, const std::string & networkname, const CDnaDatum & datum, const std::string & comment) private
Definition at line 552 of file dnaiodna.cpp.
{
    // write header
    write_msr_header_data(ptr, networkname, datum.GetName(), datum.GetEpoch_s(), vbinary_msrn->size(), comment);
}
References dynadjust::datum_parameters::CDnaDatum::GetEpoch_s(), dynadjust::datum_parameters::CDnaDatum::GetName(), write_msr_header(), and write_msr_header_data().
read_ren_data()
void dynadjust::iostreams::dna_io_dna::read_ren_data (std::ifstream * ptr, pv_string_vstring_pair stnRenaming) private
Definition at line 175 of file dnaiodna.cpp.
{
    std::string sBuf;
    string_vstring_pair stnNames;
    vstring altStnNames;
    while (!ptr->eof())         // while EOF not found
    {
        try {
            getline((*ptr), sBuf);
        }
        catch (...) {
            if (ptr->eof())
                return;
            std::stringstream ss;
            ss << "read_ren_data(): Could not read from the renaming file." << std::endl;
            boost::enable_current_exception(std::runtime_error(ss.str()));
        }
        // blank or whitespace?
        if (trimstr(sBuf).empty())
            continue;
        // Ignore lines with blank station name
        if (trimstr(sBuf.substr(dsl_.stn_name, dsw_.stn_name)).empty())
            continue;
        // Ignore lines with comments
        if (sBuf.compare(0, 1, "*") == 0)
            continue;
        std::string tmp;
        // Add the preferred name
        try {
            tmp = trimstr(sBuf.substr(dsl_.stn_name, dsw_.stn_name));
            stnNames.first = tmp;
        }
        catch (...) {
            std::stringstream ss;
            ss << "read_ren_data(): Could not extract station name from the record:  " <<
                std::endl << "    " << sBuf << std::endl;
            boost::enable_current_exception(std::runtime_error(ss.str()));
        }
        // Alternative names
        altStnNames.clear();
        UINT32 positionEndName(dsw_.stn_name+dsw_.stn_name);
        UINT32 positionNextName(dsw_.stn_name);
        while (sBuf.length() > positionNextName)
        {
            if (sBuf.length() > positionEndName)
                tmp = trimstr(sBuf.substr(positionNextName, dsw_.stn_name));
            else
                tmp = trimstr(sBuf.substr(positionNextName));
            if (!tmp.empty())
                altStnNames.push_back(tmp);
            positionNextName = positionEndName;
            positionEndName += dsw_.stn_name;
        }
        // sort for faster searching
        std::sort(altStnNames.begin(), altStnNames.end());
        // Add the alternate names
        stnNames.second = altStnNames;
        // Okay, add the pair to the list
        stnRenaming->push_back(stnNames);
    }
}
References dsl_, dsw_, and trimstr().
Referenced by read_ren_file().
prepare_sort_list()
void dynadjust::iostreams::dna_io_dna::prepare_sort_list (const UINT32 count) private
Definition at line 64 of file dnaiodna.cpp.
{
    vStationList_.resize(count);
    // initialise vector with 0,1,2,...,n-2,n-1,n
    initialiseIncrementingIntegerVector<UINT32>(vStationList_, count);
}
References initialiseIncrementingIntegerVector(), and vStationList_.
Referenced by write_stn_file().
Member Data Documentation
dsl_
dna_stn_fields dynadjust::iostreams::dna_io_dna::dsl_ private
Definition at line 138 of file dnaiodna.hpp.
Referenced by create_file_stn(), dna_stn_positions(), read_dna_header(), and read_ren_data().
dsw_
dna_stn_fields dynadjust::iostreams::dna_io_dna::dsw_ private
Definition at line 138 of file dnaiodna.hpp.
Referenced by create_file_stn(), dna_stn_widths(), read_dna_header(), and read_ren_data().
dml_
dna_msr_fields dynadjust::iostreams::dna_io_dna::dml_ private
Definition at line 139 of file dnaiodna.hpp.
Referenced by create_file_msr(), dna_msr_positions(), read_dna_header(), write_msr_file(), and write_msr_file().
dmw_
dna_msr_fields dynadjust::iostreams::dna_io_dna::dmw_ private
Definition at line 139 of file dnaiodna.hpp.
Referenced by create_file_msr(), dna_msr_widths(), read_dna_header(), write_msr_file(), and write_msr_file().
vStationList_
vUINT32 dynadjust::iostreams::dna_io_dna::vStationList_ private
Definition at line 141 of file dnaiodna.hpp.
Referenced by prepare_sort_list(), and write_stn_file().
pv_msr_db_map_
pv_msr_database_id_map dynadjust::iostreams::dna_io_dna::pv_msr_db_map_ private
Definition at line 143 of file dnaiodna.hpp.
Referenced by dna_io_dna(), dna_io_dna(), set_dbid_ptr(), write_msr_file(), and write_msr_file().
m_databaseIDsSet_
bool dynadjust::iostreams::dna_io_dna::m_databaseIDsSet_ private
Definition at line 144 of file dnaiodna.hpp.
Referenced by dna_io_dna(), dna_io_dna(), set_dbid_ptr(), and write_msr_file().
m_filespecifiedReferenceFrame_
bool dynadjust::iostreams::dna_io_dna::m_filespecifiedReferenceFrame_ private
Definition at line 145 of file dnaiodna.hpp.
Referenced by dna_io_dna(), dna_io_dna(), filespecifiedReferenceFrame(), and read_dna_header().
m_filespecifiedEpoch_
bool dynadjust::iostreams::dna_io_dna::m_filespecifiedEpoch_ private
Definition at line 146 of file dnaiodna.hpp.
Referenced by dna_io_dna(), dna_io_dna(), filespecifiedEpoch(), and read_dna_header().
The documentation for this class was generated from the following files:
include/io/dnaiodna.hpp
include/io/dnaiodna.cpp