DynAdjust: Directions_pskel Class Reference
Directions_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void Ignore (const ::std::string &)
virtual void Target (const ::std::string &)
virtual void Value (const ::std::string &)
virtual void StdDev (const ::std::string &)
virtual void MeasurementDBID (const ::std::string &)
virtual void post_Directions (const UINT32 &)
void Ignore_parser (::xml_schema::string_pskel &)
void Target_parser (::xml_schema::string_pskel &)
void Value_parser (::xml_schema::string_pskel &)
void StdDev_parser (::xml_schema::string_pskel &)
void MeasurementDBID_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &)
Directions_pskel ()
void InitparentDirnSet (dnaMsrPtr pDirectionSet)
void InitparentMsrCounter (PUINT32 pMsrCounter)
Protected Member Functions
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * Ignore_parser_
::xml_schema::string_pskel * Target_parser_
::xml_schema::string_pskel * Value_parser_
::xml_schema::string_pskel * StdDev_parser_
::xml_schema::string_pskel * MeasurementDBID_parser_
dnaMsrPtr _dnaDirection
dnaMsrPtr _parent_dnaDirectionSet
PUINT32 _pMeasurementCount
Detailed Description
Definition at line 388 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
Directions_pskel()
Directions_pskel::Directions_pskel ()
Definition at line 186 of file dnaparser_pskel.cxx.
    : Ignore_parser_ (0),
    Target_parser_ (0),
    Value_parser_ (0),
    StdDev_parser_ (0),
    MeasurementDBID_parser_ (0)
{
}
References Ignore_parser_, MeasurementDBID_parser_, StdDev_parser_, Target_parser_, and Value_parser_.
Member Function Documentation
Ignore()
void Directions_pskel::Ignore (const ::std::string &) virtual
Reimplemented in Directions_pimpl.
Definition at line 1141 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Target()
void Directions_pskel::Target (const ::std::string &) virtual
Reimplemented in Directions_pimpl.
Definition at line 1145 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Value()
void Directions_pskel::Value (const ::std::string &) virtual
Reimplemented in Directions_pimpl.
Definition at line 1149 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
StdDev()
void Directions_pskel::StdDev (const ::std::string &) virtual
Reimplemented in Directions_pimpl.
Definition at line 1153 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
MeasurementDBID()
void Directions_pskel::MeasurementDBID (const ::std::string &) virtual
Reimplemented in Directions_pimpl.
Definition at line 1157 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
post_Directions()
void Directions_pskel::post_Directions (const UINT32 &) virtual
Reimplemented in Directions_pimpl.
Definition at line 1161 of file dnaparser_pskel.cxx.
{
}
Ignore_parser()
void Directions_pskel::Ignore_parser (::xml_schema::string_pskel & p)
Definition at line 147 of file dnaparser_pskel.cxx.
{
    this->Ignore_parser_ = &p;
}
References Ignore_parser_.
Target_parser()
void Directions_pskel::Target_parser (::xml_schema::string_pskel & p)
Definition at line 152 of file dnaparser_pskel.cxx.
{
    this->Target_parser_ = &p;
}
References Target_parser_.
Value_parser()
void Directions_pskel::Value_parser (::xml_schema::string_pskel & p)
Definition at line 157 of file dnaparser_pskel.cxx.
{
    this->Value_parser_ = &p;
}
References Value_parser_.
StdDev_parser()
void Directions_pskel::StdDev_parser (::xml_schema::string_pskel & p)
Definition at line 162 of file dnaparser_pskel.cxx.
{
    this->StdDev_parser_ = &p;
}
References StdDev_parser_.
MeasurementDBID_parser()
void Directions_pskel::MeasurementDBID_parser (::xml_schema::string_pskel & p)
Definition at line 167 of file dnaparser_pskel.cxx.
{
    this->MeasurementDBID_parser_ = &p;
}
References MeasurementDBID_parser_.
parsers()
void Directions_pskel::parsers (::xml_schema::string_pskel & Ignore, ::xml_schema::string_pskel & Target, ::xml_schema::string_pskel & Value, ::xml_schema::string_pskel & StdDev, ::xml_schema::string_pskel & MeasurementDBID)
Definition at line 172 of file dnaparser_pskel.cxx.
{
    this->Ignore_parser_ = &Ignore;
    this->Target_parser_ = &Target;
    this->Value_parser_ = &Value;
    this->StdDev_parser_ = &StdDev;
    this->MeasurementDBID_parser_ = &MeasurementDBID;
}
References Ignore(), Ignore_parser_, MeasurementDBID(), MeasurementDBID_parser_, StdDev(), StdDev_parser_, Target(), Target_parser_, Value(), and Value_parser_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
InitparentDirnSet()
void Directions_pskel::InitparentDirnSet (dnaMsrPtr pDirectionSet) inline
Definition at line 422 of file dnaparser_pskel.hxx.
{ _parent_dnaDirectionSet = pDirectionSet; }
References _parent_dnaDirectionSet.
InitparentMsrCounter()
void Directions_pskel::InitparentMsrCounter (PUINT32 pMsrCounter) inline
Definition at line 423 of file dnaparser_pskel.hxx.
{   _pMeasurementCount = pMsrCounter; }
References _pMeasurementCount.
_start_element_impl()
bool Directions_pskel::_start_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string * t) protected virtual
Definition at line 1165 of file dnaparser_pskel.cxx.
{
    XSD_UNUSED (t);
    if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
        return true;
    if (n == "Ignore" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Ignore_parser_;
        if (this->Ignore_parser_)
            this->Ignore_parser_->pre ();
        return true;
    }
    if (n == "Target" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Target_parser_;
        if (this->Target_parser_)
            this->Target_parser_->pre ();
        return true;
    }
    if (n == "Value" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Value_parser_;
        if (this->Value_parser_)
            this->Value_parser_->pre ();
        return true;
    }
    if (n == "StdDev" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->StdDev_parser_;
        if (this->StdDev_parser_)
            this->StdDev_parser_->pre ();
        return true;
    }
    if (n == "MeasurementID" && ns.empty())
    {
        this->::xml_schema::complex_content::context_.top().parser_ = this->MeasurementDBID_parser_;
        if (this->MeasurementDBID_parser_)
            this->MeasurementDBID_parser_->pre();
        return true;
    }
    return false;
}
References Ignore_parser_, MeasurementDBID_parser_, StdDev_parser_, Target_parser_, and Value_parser_.
_end_element_impl()
bool Directions_pskel::_end_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n) protected virtual
Definition at line 1227 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
        return true;
    if (n == "Ignore" && ns.empty ())
    {
        if (this->Ignore_parser_)
            this->Ignore (this->Ignore_parser_->post_string ());
        return true;
    }
    if (n == "Target" && ns.empty ())
    {
        if (this->Target_parser_)
            this->Target (this->Target_parser_->post_string ());
        return true;
    }
    if (n == "Value" && ns.empty ())
    {
        if (this->Value_parser_)
            this->Value (this->Value_parser_->post_string ());
        return true;
    }
    if (n == "StdDev" && ns.empty ())
    {
        if (this->StdDev_parser_)
            this->StdDev (this->StdDev_parser_->post_string ());
        return true;
    }
    if (n == "MeasurementID" && ns.empty())
    {
        if (this->MeasurementDBID_parser_)
            this->MeasurementDBID (this->MeasurementDBID_parser_->post_string());
        return true;
    }
    return false;
}
References Ignore(), Ignore_parser_, MeasurementDBID(), MeasurementDBID_parser_, StdDev(), StdDev_parser_, Target(), Target_parser_, Value(), and Value_parser_.
Member Data Documentation
Ignore_parser_
::xml_schema::string_pskel* Directions_pskel::Ignore_parser_ protected
Definition at line 438 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Directions_pskel(), Ignore_parser(), and parsers().
Target_parser_
::xml_schema::string_pskel* Directions_pskel::Target_parser_ protected
Definition at line 439 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Directions_pskel(), parsers(), and Target_parser().
Value_parser_
::xml_schema::string_pskel* Directions_pskel::Value_parser_ protected
Definition at line 440 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Directions_pskel(), parsers(), and Value_parser().
StdDev_parser_
::xml_schema::string_pskel* Directions_pskel::StdDev_parser_ protected
Definition at line 441 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Directions_pskel(), parsers(), and StdDev_parser().
MeasurementDBID_parser_
::xml_schema::string_pskel* Directions_pskel::MeasurementDBID_parser_ protected
Definition at line 442 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Directions_pskel(), MeasurementDBID_parser(), and parsers().
_dnaDirection
dnaMsrPtr Directions_pskel::_dnaDirection protected
Definition at line 444 of file dnaparser_pskel.hxx.
Referenced by Directions_pimpl::Ignore(), Directions_pimpl::MeasurementDBID(), Directions_pimpl::post_Directions(), Directions_pimpl::pre(), Directions_pimpl::StdDev(), Directions_pimpl::Target(), and Directions_pimpl::Value().
_parent_dnaDirectionSet
dnaMsrPtr Directions_pskel::_parent_dnaDirectionSet protected
Definition at line 445 of file dnaparser_pskel.hxx.
Referenced by InitparentDirnSet(), Directions_pimpl::post_Directions(), and Directions_pimpl::pre().
_pMeasurementCount
PUINT32 Directions_pskel::_pMeasurementCount protected
Definition at line 446 of file dnaparser_pskel.hxx.
Referenced by InitparentMsrCounter(), and Directions_pimpl::Value().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx