DynAdjust: StationNameIDCompareID Class Reference
StationNameIDCompareID Class Reference
#include <dnatemplatestnmsrfuncs.hpp>
Public Member Functions
bool operator() (const string_uint32_pair &lhs, const string_uint32_pair &rhs) const
bool operator() (const string_uint32_pair &lhs, const string_uint32_pair::second_type &k) const
bool operator() (const string_uint32_pair::second_type &k, const string_uint32_pair &rhs) const
Private Member Functions
bool keyLess (const string_uint32_pair::second_type &k1, const string_uint32_pair::second_type &k2) const
Detailed Description
Definition at line 944 of file dnatemplatestnmsrfuncs.hpp.
Member Function Documentation
operator()() [1/3]
bool StationNameIDCompareID::operator() (const string_uint32_pair & lhs, const string_uint32_pair & rhs) const inline
Definition at line 947 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(lhs.second, rhs.second);
    }
References keyLess().
operator()() [2/3]
bool StationNameIDCompareID::operator() (const string_uint32_pair & lhs, const string_uint32_pair::second_type & k) const inline
Definition at line 951 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(lhs.second, k);
    }
References keyLess().
operator()() [3/3]
bool StationNameIDCompareID::operator() (const string_uint32_pair::second_type & k, const string_uint32_pair & rhs) const inline
Definition at line 955 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(k, rhs.second);
    }
References keyLess().
keyLess()
bool StationNameIDCompareID::keyLess (const string_uint32_pair::second_type & k1, const string_uint32_pair::second_type & k2) const inline private
Definition at line 960 of file dnatemplatestnmsrfuncs.hpp.
{
        return k1 < k2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this class was generated from the following file:
include/functions/dnatemplatestnmsrfuncs.hpp