DynAdjust: dynadjust::networksegment::dna_segment Class Reference
dynadjust::networksegment::dna_segment Class Reference
#include <dnasegment.hpp>
Public Member Functions
dna_segment ()
virtual ~dna_segment ()
void PrepareSegmentation (project_settings *projectSettings)
_SEGMENT_STATUS_ SegmentNetwork (project_settings *projectSettings)
void InitialiseSegmentation ()
double GetProgress () const
UINT32 currentBlock () const
size_t blockCount () const
double averageblockSize () const
UINT32 stationSolutionCount () const
UINT32 maxBlockSize () const
UINT32 minBlockSize () const
void coutSummary () const
void coutCurrentBlockSummary (std::ostream &os)
void LoadNetFile ()
void LoadBinaryFiles (const std::string &bstrfileName, const std::string &bmsrfileName)
void LoadAssociationFiles (const std::string &aslfileName, const std::string &amlfileName)
void LoadStationMap (const std::string &stnmap_file)
void WriteSegmentedNetwork (const std::string &segfileName)
void WriteFreeStnListSortedbyASLMsrCount ()
void VerifyStationConnections ()
std::string DefaultStartingStation ()
vstring StartingStations ()
_SEGMENT_STATUS_ GetStatus () const
Private Member Functions
dna_segment (const dna_segment &)
dna_segment & operator= (const dna_segment &)
void SignalExceptionSerialise (const std::string &msg, const int &i, const char *streamType,...)
void ParseStartingStations ()
void BuildFirstBlock ()
void BuildNextBlock ()
void FinaliseBlock ()
void SortbyMeasurementCount (pvUINT32 vStnList)
UINT32 SelectInner ()
void SelectJunction ()
it_vUINT32 MoveStation (vUINT32 &fromList, it_vUINT32 it_from, vUINT32 &toList, const UINT32 &stn_index)
void MoveFreeStn (it_vUINT32 it_freeisl, vUINT32 &toList, const UINT32 &stn_index, const std::string &type)
void MoveFreeStnToInnerList (it_vUINT32 it_freeisl, const UINT32 &stn_index)
void MoveFreeStnToJunctionList (it_vUINT32 it_freeisl, const UINT32 &stn_index)
void GetInnerMeasurements (const UINT32 &innerStation)
void IdentifyLowestStationAssociation (pvUINT32 vStnList, vUINT32 &totalStations, const int currentLevel, const int maxLevel, pvUINT32 vStnCount)
void IdentifyInnerMsrsandAssociatedStns (const UINT32 &innerStation, vUINT32 &totalStations)
void AddtoJunctionStnList (const vUINT32 &msrStations)
bool AddtoCurrentMsrList (const UINT32 &amlindex, const vUINT32 &msrStations)
UINT32 GetAvailableMsrCount (const UINT32 &stn_index)
void FindCommonMeasurements ()
void MoveJunctiontoISL ()
void SetAvailableMsrCount ()
void RemoveDuplicateStations (pvstring vStations)
void RemoveInvalidFreeStations ()
void BuildFreeStationAvailabilityList ()
void CalculateAverageBlockSize ()
void VerifyStationConnections_Block (const UINT32 &block)
void VerifyStationsandBuildBlock (bool validationOnly=false)
Private Attributes
project_settings projectSettings_
_SEGMENT_STATUS_ segmentStatus_
bool isProcessing_
UINT32 currentBlock_
UINT32 currentNetwork_
std::string network_name_
UINT16 debug_level_
std::string output_folder_
CompareClusterID< measurement_t, UINT32 > clusteridCompareFunc_
vstring vinitialStns_
vUINT32 v_ContiguousNetList_
vUINT32 vCurrJunctStnList_
vUINT32 vCurrInnerStnList_
vUINT32 vCurrMeasurementList_
vstn_t bstBinaryRecords_
vmsr_t bmsBinaryRecords_
vASL vAssocStnList_
vUINT32 vASLCount_
vUINT32 vAssocMsrList_
v_aml_pair vAssocFreeMsrList_
vUINT32 vfreeStnList_
vUINT32 vfreeMsrList_
v_string_uint32_pair stnsMap_
v_freestn_pair vfreeStnAvailability_
vvUINT32 vJSL_
vvUINT32 vISL_
vvUINT32 vCML_
std::ofstream debug_file
std::ofstream trace_file
double averageBlockSize_
UINT32 stationSolutionCount_
UINT32 minBlockSize_
UINT32 maxBlockSize_
Detailed Description
Definition at line 79 of file dnasegment.hpp.
Constructor & Destructor Documentation
dna_segment() [1/2]
dynadjust::networksegment::dna_segment::dna_segment ()
Definition at line 28 of file dnasegment.cpp.
    : isProcessing_(false)
{
    network_name_ = "";
}
References isProcessing_, and network_name_.
Referenced by dna_segment(), and operator=().
~dna_segment()
dynadjust::networksegment::dna_segment::~dna_segment () virtual
Definition at line 34 of file dnasegment.cpp.
{
}
dna_segment() [2/2]
dynadjust::networksegment::dna_segment::dna_segment (const dna_segment &) private
References dna_segment().
Member Function Documentation
operator=()
dna_segment & dynadjust::networksegment::dna_segment::operator= (const dna_segment &) private
References dna_segment(), GetProgress(), InitialiseSegmentation(), PrepareSegmentation(), and SegmentNetwork().
PrepareSegmentation()
void dynadjust::networksegment::dna_segment::PrepareSegmentation (project_settings * projectSettings)
Definition at line 126 of file dnasegment.cpp.
{
    projectSettings_ = *p;
    ParseStartingStations();
    network_name_ = p->g.network_name;
    LoadBinaryFiles(p->s.bst_file, p->s.bms_file);
    LoadAssociationFiles(p->s.asl_file, p->s.aml_file);
    LoadStationMap(p->s.map_file);
    BuildFreeStationAvailabilityList();
    SortbyMeasurementCount(&vfreeStnList_);
}
References segment_settings::aml_file, segment_settings::asl_file, segment_settings::bms_file, segment_settings::bst_file, BuildFreeStationAvailabilityList(), project_settings::g, LoadAssociationFiles(), LoadBinaryFiles(), LoadStationMap(), segment_settings::map_file, general_settings::network_name, network_name_, ParseStartingStations(), projectSettings_, project_settings::s, SortbyMeasurementCount(), and vfreeStnList_.
Referenced by operator=().
SegmentNetwork()
_SEGMENT_STATUS_ dynadjust::networksegment::dna_segment::SegmentNetwork (project_settings * projectSettings)
Definition at line 170 of file dnasegment.cpp.
{
    isProcessing_ = true;
    output_folder_ = p->g.output_folder;
    if ((debug_level_ = p->g.verbose) > 2)
    {
        std::string s(p->s.seg_file + ".trace");
        try {
            // Create trace file.  Throws runtime_error on failure.
            file_opener(trace_file, s);
            print_file_header(trace_file, "DYNADJUST SEGMENTATION TRACE FILE");
            trace_file << OUTPUTLINE << std::endl << std::endl;
        }
        catch (const std::runtime_error& e) {
            SignalExceptionSerialise(e.what(), 0, NULL);
        }
    }
    if ((debug_level_ = p->g.verbose) > 1)
    {
        std::string s(p->s.seg_file + ".debug");
        try {
            // Create debug file.  Throws runtime_error on failure.
            file_opener(debug_file, s);
        }
        catch (const std::ios_base::failure& f) {
            SignalExceptionSerialise(f.what(), 0, NULL);
        }
    }
    segmentStatus_ = SEGMENT_SUCCESS;
    std::ostringstream ss;
    if (debug_level_ > 2)
        WriteFreeStnListSortedbyASLMsrCount();
    currentBlock_ = 1;
    if (debug_level_ > 2)
        trace_file << "Block " << currentBlock_ << "..." << std::endl;
    boost::timer::cpu_timer time;
    v_ContiguousNetList_.clear();
    v_ContiguousNetList_.push_back(currentNetwork_ = 0);
    if (bstBinaryRecords_.empty())
        SignalExceptionSerialise("SegmentNetwork(): the binary stations file has not been loaded into memory yet.", 0, NULL);
    if (bmsBinaryRecords_.empty())
        SignalExceptionSerialise("SegmentNetwork(): the binary measurements file has not been loaded into memory yet.", 0, NULL);
    if (vAssocStnList_.empty())
        SignalExceptionSerialise("SegmentNetwork(): the Associated Station List (ASL) has not been loaded into memory yet.", 0, NULL);
    if (vAssocFreeMsrList_.empty())
        SignalExceptionSerialise("SegmentNetwork(): the Associated Measurements List (AML) has not been loaded into memory yet.", 0, NULL);
    if (stnsMap_.empty())
        SignalExceptionSerialise("SegmentNetwork(): the station map has not been loaded into memory yet.", 0, NULL);
    // The inner stations for the first block are created from segmentCriteria._initialStns
    // Junction stations are retrieved from measurements connected to the inner stations
    BuildFirstBlock();
    while (!vfreeStnList_.empty())
    {
        isProcessing_ = true;
        currentBlock_++;
        if (debug_level_ > 2)
            trace_file << "Block " << currentBlock_ << "..." << std::endl;
        v_ContiguousNetList_.push_back(currentNetwork_);
        // The inner stations for the next block are the junction stations from the previous block
        // The junction stations are retrieved from measurements connected to the inner stations
        // BuildNextBlock applies the min and max station constraints using segmentCriteria
        BuildNextBlock();
        if (vfreeStnList_.empty())
            break;
    }
    boost::posix_time::milliseconds elapsed_time(boost::posix_time::milliseconds(0));
    if (debug_level_ > 1)
        elapsed_time = boost::posix_time::milliseconds(time.elapsed().wall/MILLI_TO_NANO);
    isProcessing_ = false;
    CalculateAverageBlockSize();
    char valid_stations(0);
    char valid_measurements_not_included(0);
    if (vfreeStnList_.size())
    {
        valid_stations = 1;
        ss.str("");
        ss << std::endl << "- Warning: The following stations were not used:" << std::endl;
        ss << "  ";
        it_vUINT32_const _it_freestn(vfreeStnList_.begin());
        for (; _it_freestn!=vfreeStnList_.end(); ++_it_freestn)
            ss << bstBinaryRecords_.at(*_it_freestn).stationName << " ";
        ss << std::endl;
        ss << "- Possible reasons why these stations were not used include:" << std::endl;
        ss << "  - No measurements to these stations were found," << std::endl;
        ss << "  - The network is made up of non-contiguous blocks," << std::endl;
        ss << "  - There is a bug in this program." << std::endl;
        if (debug_level_ > 1)
            debug_file << ss.str();
    }
    if (debug_level_ > 1)
    {
        debug_file << formatedElapsedTime<std::string>(&elapsed_time, "+ Network segmentation took ") <<
            " The network is now ready for adjustment." << std::endl;
        debug_file.close();
    }
    isProcessing_ = false;
    if (valid_measurements_not_included || valid_stations)
        return (segmentStatus_ = SEGMENT_BLOCK_ERROR);
    return (segmentStatus_ = SEGMENT_SUCCESS);
}
References bmsBinaryRecords_, bstBinaryRecords_, BuildFirstBlock(), BuildNextBlock(), CalculateAverageBlockSize(), currentBlock_, currentNetwork_, debug_file, debug_level_, file_opener(), project_settings::g, isProcessing_, MILLI_TO_NANO(), general_settings::output_folder, output_folder_, OUTPUTLINE, print_file_header(), project_settings::s, segment_settings::seg_file, SEGMENT_BLOCK_ERROR, SEGMENT_SUCCESS, segmentStatus_, SignalExceptionSerialise(), stnsMap_, trace_file, v_ContiguousNetList_, vAssocFreeMsrList_, vAssocStnList_, general_settings::verbose, vfreeStnList_, and WriteFreeStnListSortedbyASLMsrCount().
Referenced by operator=().
InitialiseSegmentation()
void dynadjust::networksegment::dna_segment::InitialiseSegmentation ()
Definition at line 143 of file dnasegment.cpp.
{
    segmentStatus_ = SEGMENT_SUCCESS;
    isProcessing_ = false;
    currentBlock_ = 0;
    network_name_ = "network_name";        // network name
    vinitialStns_.clear();
    vCurrJunctStnList_.clear();
    vCurrInnerStnList_.clear();
    vCurrMeasurementList_.clear();
    bstBinaryRecords_.clear();
    bmsBinaryRecords_.clear();
    vAssocStnList_.clear();
    vAssocMsrList_.clear();
    vfreeStnList_.clear();
    vfreeMsrList_.clear();
    stnsMap_.clear();
    vJSL_.clear();
    vISL_.clear();
    vCML_.clear();
}
References bmsBinaryRecords_, bstBinaryRecords_, currentBlock_, isProcessing_, network_name_, SEGMENT_SUCCESS, segmentStatus_, stnsMap_, vAssocMsrList_, vAssocStnList_, vCML_, vCurrInnerStnList_, vCurrJunctStnList_, vCurrMeasurementList_, vfreeMsrList_, vfreeStnList_, vinitialStns_, vISL_, and vJSL_.
Referenced by main(), and operator=().
GetProgress()
double dynadjust::networksegment::dna_segment::GetProgress () const
Definition at line 40 of file dnasegment.cpp.
{
    return ((bstBinaryRecords_.size() - vfreeStnList_.size()) * 100. / bstBinaryRecords_.size());
}
References bstBinaryRecords_, and vfreeStnList_.
Referenced by operator=().
currentBlock()
UINT32 dynadjust::networksegment::dna_segment::currentBlock () const inline
Definition at line 101 of file dnasegment.hpp.
{ return currentBlock_; }
References currentBlock_.
blockCount()
size_t dynadjust::networksegment::dna_segment::blockCount () const inline
Definition at line 102 of file dnasegment.hpp.
{ return vISL_.size(); }
References vISL_.
Referenced by main(), and VerifyStationConnections().
averageblockSize()
double dynadjust::networksegment::dna_segment::averageblockSize () const inline
Definition at line 103 of file dnasegment.hpp.
{ return averageBlockSize_; }
References averageBlockSize_.
Referenced by main().
stationSolutionCount()
UINT32 dynadjust::networksegment::dna_segment::stationSolutionCount () const inline
Definition at line 104 of file dnasegment.hpp.
{ return stationSolutionCount_; }
References stationSolutionCount_.
Referenced by main().
maxBlockSize()
UINT32 dynadjust::networksegment::dna_segment::maxBlockSize () const inline
Definition at line 105 of file dnasegment.hpp.
{ return maxBlockSize_; }
References maxBlockSize_.
Referenced by main().
minBlockSize()
UINT32 dynadjust::networksegment::dna_segment::minBlockSize () const inline
Definition at line 106 of file dnasegment.hpp.
{ return minBlockSize_; }
References minBlockSize_.
Referenced by main().
coutSummary()
void dynadjust::networksegment::dna_segment::coutSummary () const
Definition at line 1419 of file dnasegment.cpp.
{
    UINT32 stns(0), msrs(0);
    vvUINT32::const_iterator _it_isl, _it_jsl, _it_cml;
    char BLOCK = 10;
    char INNER = 12;
    char JUNCT = 15;
    char TOTAL = 12;
    char MEASR = 14;
    for (_it_cml = vCML_.begin(); _it_cml!=vCML_.end(); ++_it_cml)
        msrs += static_cast<UINT32>(_it_cml->size());
    for (_it_isl = vISL_.begin(); _it_isl!=vISL_.end(); ++_it_isl)
        stns += static_cast<UINT32>(_it_isl->size());
    std::cout << "+ Segmentation summary:" << std::endl << std::endl;
    std::cout << std::setw(BLOCK) << std::left << "  Block" << std::setw(JUNCT) << std::left << "Junction stns" << std::setw(INNER) << std::left << "Inner stns" << std::setw(MEASR) << std::left << "Measurements" << std::setw(TOTAL) << std::left << "Total stns"  << std::endl;
    std::cout << "  ";
    for (char dash=BLOCK+NETID+INNER+JUNCT+TOTAL+MEASR; dash>2; dash--)
        std::cout << "-";
    std::cout << std::endl;
    UINT32 b = 1;
    _it_jsl = vJSL_.begin();
    _it_cml = vCML_.begin();
    for (_it_isl=vISL_.begin(); _it_isl!=vISL_.end(); ++_it_isl)
    {
        // block
        std::cout << "  " << std::setw(BLOCK-2) << std::left << b;
        // junction stns
        if (_it_jsl!=vJSL_.end())
            std::cout << std::setw(JUNCT) << std::left << _it_jsl->size();
        else
            std::cout << std::setw(JUNCT) << " ";
        // inner stns
        std::cout << std::setw(INNER) << std::left << _it_isl->size();
        // total measurements
        if (_it_cml!=vCML_.end())
            std::cout << std::setw(MEASR) << std::left << _it_cml->size();
        else
            std::cout << std::setw(MEASR) << " ";
        // total stns
        if (_it_jsl!=vJSL_.end())
            std::cout << std::setw(TOTAL) << std::left << (_it_isl->size() + _it_jsl->size());
        else
            std::cout << std::setw(TOTAL) << std::left << _it_isl->size();
        std::cout << std::endl;
        ++_it_jsl;
        ++_it_cml;
        b++;
    }
    std::cout << std::endl;
    std::cout << "+ Stations used:       " << std::setw(10) << std::right << stns << std::endl;
    std::cout << "+ Measurements used:   " << std::setw(10) << std::right << msrs << std::endl;
    if (!vfreeStnList_.empty())
        std::cout << "+ Unused stations:     " << std::setw(10) << std::right << vfreeStnList_.size() << std::endl;
    //if (!vfreeMsrList_.empty())
    //  std::cout << "+ Unused measurements: " << std::setw(10) << std::right << vfreeMsrList_.size() << std::endl;
}
References BLOCK(), INNER(), JUNCT(), MEASR(), NETID(), TOTAL(), vCML_, vfreeStnList_, vISL_, and vJSL_.
Referenced by BuildNextBlock(), and main().
coutCurrentBlockSummary()
void dynadjust::networksegment::dna_segment::coutCurrentBlockSummary (std::ostream & os)
Definition at line 1399 of file dnasegment.cpp.
{
    try {
        dna_io_seg seg;
        seg.write_seg_block(os,
            vCurrInnerStnList_, vCurrJunctStnList_, vCurrMeasurementList_,
            currentBlock_,
            &bstBinaryRecords_, &bmsBinaryRecords_,
            true);
    }
    catch (const std::runtime_error& e) {
        SignalExceptionSerialise(e.what(), 0, NULL);
    }
    if (!vfreeStnList_.empty())
        os << "+ Free stations remaining:     " << std::setw(10) << std::right << vfreeStnList_.size() << std::endl;
    if (!vfreeMsrList_.empty())
        os << "+ Free measurements remaining: " << std::setw(10) << std::right << vfreeMsrList_.size() << std::endl;
}
References bmsBinaryRecords_, bstBinaryRecords_, currentBlock_, SignalExceptionSerialise(), vCurrInnerStnList_, vCurrJunctStnList_, vCurrMeasurementList_, vfreeMsrList_, vfreeStnList_, and dynadjust::iostreams::dna_io_seg::write_seg_block().
Referenced by FinaliseBlock().
LoadNetFile()
void dynadjust::networksegment::dna_segment::LoadNetFile ()
Definition at line 45 of file dnasegment.cpp.
{
    // Get stations listed in net file
    std::ifstream net_file;
    try {
        // Load net file.  Throws runtime_error on failure.
        file_opener(net_file, projectSettings_.s.net_file,
            std::ios::in, ascii, true);
    }
    catch (const std::runtime_error& e) {
        SignalExceptionSerialise(e.what(), 0, NULL);
    }
    std::string station;
    char line[PROGRAM_OPTIONS_LINE_LENGTH];
    // read header lines
    net_file.ignore(PRINT_LINE_LENGTH, '\n');                  // -------------------------------------------
    net_file.getline(line, PROGRAM_OPTIONS_LINE_LENGTH);     //            DYNADJUST BLOCK 1 STATIONS FILE
    vinitialStns_.clear();
    try {
        while (!net_file.eof())
        {
            net_file.getline(line, PROGRAM_OPTIONS_LINE_LENGTH);     // Stations
            station = line;
            if ((station = trimstr(station)).empty())
                continue;
            // add this station to the list
            vinitialStns_.push_back(station);
        }
    }
    catch (const std::ios_base::failure& f) {
        if (!net_file.eof())
        {
            std::stringstream ss;
            ss << "ParseStartingStations(): An error was encountered when reading " << projectSettings_.s.net_file << "." << std::endl << f.what();
            SignalExceptionSerialise(ss.str(), 0, "i", &net_file);
        }
    }
    net_file.close();
}
References ascii, file_opener(), PRINT_LINE_LENGTH(), PROGRAM_OPTIONS_LINE_LENGTH(), projectSettings_, SignalExceptionSerialise(), trimstr(), and vinitialStns_.
Referenced by ParseStartingStations().
LoadBinaryFiles()
void dynadjust::networksegment::dna_segment::LoadBinaryFiles (const std::string & bstrfileName, const std::string & bmsrfileName)
Definition at line 1114 of file dnasegment.cpp.
{
    binary_file_meta_t    bst_meta_, bms_meta_;
    try {
        // Load binary stations data.  Throws runtime_error on failure.
        dna_io_bst bst;
        bst.load_bst_file(bstrfileName, &bstBinaryRecords_, bst_meta_);
        // Load binary measurements data.  Throws runtime_error on failure.
        dna_io_bms bms;
        bms.load_bms_file(bmsrfileName, &bmsBinaryRecords_, bms_meta_);
    }
    catch (const std::runtime_error& e) {
        SignalExceptionSerialise(e.what(), 0, NULL);
    }
    // Update the Cluster comparison functor with the AML binary vector
    clusteridCompareFunc_.SetAMLPointer(const_cast<pvmsr_t>(&bmsBinaryRecords_));
    // count the number of measurements not ignored
    MsrTally msrTally;
    UINT32 m = msrTally.CreateTally(bmsBinaryRecords_, true);
    // throw an exception if no measurements are available
    if (m == 0)
    {
        std::stringstream ss;
        ss << "No measurements were found." << std::endl <<
            "  If measurements were successfully loaded on import, ensure that\n  all measurements have not been ignored." << std::endl;
        SignalExceptionSerialise(ss.str(), 0, NULL);
    }
}
References bmsBinaryRecords_, bstBinaryRecords_, clusteridCompareFunc_, dynadjust::measurements::MsrTally::CreateTally(), dynadjust::iostreams::dna_io_bms::load_bms_file(), dynadjust::iostreams::dna_io_bst::load_bst_file(), and SignalExceptionSerialise().
Referenced by PrepareSegmentation().
LoadAssociationFiles()
void dynadjust::networksegment::dna_segment::LoadAssociationFiles (const std::string & aslfileName, const std::string & amlfileName)
Definition at line 1062 of file dnasegment.cpp.
{
    UINT32 stn, stnCount(0);
    try {
        dna_io_asl asl;
        stnCount = asl.load_asl_file(aslfileName, &vAssocStnList_, &vfreeStnList_);
    }
    catch (const std::runtime_error& e) {
        SignalExceptionSerialise(e.what(), 0, NULL);
    }
    // Dertmine original measurement count for each station
    vASLCount_.clear();
    vASLCount_.resize(stnCount);
    _it_vasl _it_asl;
    for (stn=0, _it_asl=vAssocStnList_.begin();
        _it_asl!=vAssocStnList_.end();
        ++_it_asl, ++stn)
    {
        vASLCount_.at(stn) = _it_asl->GetAssocMsrCount();     // original measurement count
    }
    // remove stations from the free list that are invalid
    RemoveInvalidFreeStations();
    // Load associated measurements list.  Throws runtime_error on failure.
    try {
        dna_io_aml aml;
        aml.load_aml_file(amlfileName, &vAssocFreeMsrList_, &bmsBinaryRecords_);
    }
    catch (const std::runtime_error& e) {
        SignalExceptionSerialise(e.what(), 0, NULL);
    }
    // set available msr count
    SetAvailableMsrCount();
}
References bmsBinaryRecords_, dynadjust::iostreams::dna_io_aml::load_aml_file(), dynadjust::iostreams::dna_io_asl::load_asl_file(), RemoveInvalidFreeStations(), SetAvailableMsrCount(), SignalExceptionSerialise(), vASLCount_, vAssocFreeMsrList_, vAssocStnList_, and vfreeStnList_.
Referenced by PrepareSegmentation().
LoadStationMap()
void dynadjust::networksegment::dna_segment::LoadStationMap (const std::string & stnmap_file)
Definition at line 1103 of file dnasegment.cpp.
{
    try {
        dna_io_map map;
        map.load_map_file(stnmap_file, &stnsMap_);
    }
    catch (const std::runtime_error& e) {
        SignalExceptionSerialise(e.what(), 0, NULL);
    }
}
References dynadjust::iostreams::dna_io_map::load_map_file(), SignalExceptionSerialise(), and stnsMap_.
Referenced by PrepareSegmentation().
WriteSegmentedNetwork()
void dynadjust::networksegment::dna_segment::WriteSegmentedNetwork (const std::string & segfileName)
Definition at line 1487 of file dnasegment.cpp.
{
    if (bstBinaryRecords_.empty())
        SignalExceptionSerialise("WriteSegmentedNetwork(): the binary stations file has not been loaded into memory yet.", 0, NULL);
    if (bmsBinaryRecords_.empty())
        SignalExceptionSerialise("WriteSegmentedNetwork(): the binary measurements file has not been loaded into memory yet.", 0, NULL);
    if (vJSL_.empty())
        SignalExceptionSerialise("WriteSegmentedNetwork(): the junction stations list is empty, most likely because the network has not been segmented yet.", 0, NULL);
    if (vISL_.empty())
        SignalExceptionSerialise("WriteSegmentedNetwork(): the inner stations list is empty, most likely because the network has not been segmented yet.", 0, NULL);
    if (vCML_.empty())
        SignalExceptionSerialise("WriteSegmentedNetwork(): the block measurementslist is empty, most likely because the network has not been segmented yet.", 0, NULL);
    try {
        dna_io_seg seg;
        seg.write_seg_file(segfileName, projectSettings_.s.bst_file, projectSettings_.s.bms_file,
            projectSettings_.s.min_inner_stations, projectSettings_.s.max_total_stations,
            projectSettings_.s.seg_starting_stns, vinitialStns_,
            projectSettings_.s.command_line_arguments,
            vISL_, vJSL_, vCML_,
            v_ContiguousNetList_, &bstBinaryRecords_, &bmsBinaryRecords_);
    }
    catch (const std::runtime_error& e) {
        SignalExceptionSerialise(e.what(), 0, NULL);
    }
    catch (...) {
        SignalExceptionSerialise("WriteSegmentedNetwork(): failed to print segmentation file.", 0, NULL);
    }
}
References bmsBinaryRecords_, bstBinaryRecords_, projectSettings_, SignalExceptionSerialise(), v_ContiguousNetList_, vCML_, vinitialStns_, vISL_, vJSL_, and dynadjust::iostreams::dna_io_seg::write_seg_file().
Referenced by main().
WriteFreeStnListSortedbyASLMsrCount()
void dynadjust::networksegment::dna_segment::WriteFreeStnListSortedbyASLMsrCount ()
Definition at line 1364 of file dnasegment.cpp.
{
    if (!boost::filesystem::exists(output_folder_))
    {
        std::stringstream ss("WriteFreeStnListSortedbyASLMsrCount(): Path does not exist... \n\n    ");
        ss << output_folder_ << ".";
        SignalExceptionSerialise(ss.str(), 0, NULL);
    }
    std::string file(output_folder_ + "/free_stn_sorted_by_msr_count.lst");
    std::ofstream freestnlist(file.c_str());
    UINT32 x(0);
    std::string s;
    UINT32 u, msrCount, m, amlindex;
    for (; x<vfreeStnList_.size(); ++x)
    {
        u = vfreeStnList_.at(x);
        s = bstBinaryRecords_.at(vfreeStnList_.at(x)).stationName;
        s.insert(0, "'");
        s += "'";
        msrCount = vAssocStnList_.at(vfreeStnList_.at(x)).GetAssocMsrCount();
        freestnlist << std::left << std::setw(10) << u << std::left << std::setw(14) << s << std::left << std::setw(5) << msrCount;
        for (m=0; m<msrCount; m++)
        {
            // get the measurement record (holds other stations tied to this measurement)
            amlindex = vAssocStnList_.at(vfreeStnList_.at(x)).GetAMLStnIndex() + m;  // get the AML index
            freestnlist << std::left << std::setw(HEADER_20) << amlindex;
        }
        freestnlist << std::endl;
    }
    freestnlist.close();
}
References bstBinaryRecords_, HEADER_20(), output_folder_, SignalExceptionSerialise(), vAssocStnList_, and vfreeStnList_.
Referenced by SegmentNetwork().
VerifyStationConnections()
void dynadjust::networksegment::dna_segment::VerifyStationConnections ()
Definition at line 1517 of file dnasegment.cpp.
{
    UINT32 block, blockCount(static_cast<UINT32>(vISL_.size()));
    for (block=0; block<blockCount; ++block)
        VerifyStationConnections_Block(block);
}
References blockCount(), VerifyStationConnections_Block(), and vISL_.
Referenced by main().
DefaultStartingStation()
std::string dynadjust::networksegment::dna_segment::DefaultStartingStation ()
Definition at line 318 of file dnasegment.cpp.
{
    if (vfreeStnList_.empty())
        return "";
    if (bstBinaryRecords_.empty())
        return "";
    return bstBinaryRecords_.at(vfreeStnList_.at(0)).stationName;
}
References bstBinaryRecords_, and vfreeStnList_.
StartingStations()
vstring dynadjust::networksegment::dna_segment::StartingStations ()
Definition at line 328 of file dnasegment.cpp.
{
    return vinitialStns_;
}
References vinitialStns_.
GetStatus()
_SEGMENT_STATUS_ dynadjust::networksegment::dna_segment::GetStatus () const inline
Definition at line 125 of file dnasegment.hpp.
{ return segmentStatus_; }
References segmentStatus_.
Referenced by main().
SignalExceptionSerialise()
void dynadjust::networksegment::dna_segment::SignalExceptionSerialise (const std::string & msg, const int & i, const char * streamType, ...) private
Definition at line 1018 of file dnasegment.cpp.
{
    isProcessing_ = false;
    segmentStatus_ = SEGMENT_EXCEPTION_RAISED;
    if (debug_level_ > 1)
        if (debug_file.is_open())
            debug_file.close();
    if (debug_level_ > 2)
        if (trace_file.is_open())
            trace_file.close();
    if (streamType == NULL)
        throw NetSegmentException(msg, i);
    std::ofstream* ofsDynaML;
    std::ifstream* ifsbinaryFile;
    va_list argptr;
    va_start(argptr, streamType);
    while (*streamType != '\0')
    {
        //ifstream
        if (*streamType == 'i' )
        {
            ifsbinaryFile = va_arg(argptr, std::ifstream*);
            ifsbinaryFile->close();
        }
        //ofstream
        if (*streamType == 'o' )
        {
            ofsDynaML = va_arg(argptr, std::ofstream*);
            ofsDynaML->close();
        }
        streamType++;
    }
    va_end(argptr);
    throw NetSegmentException(msg, i);
}
References debug_file, debug_level_, isProcessing_, SEGMENT_EXCEPTION_RAISED, segmentStatus_, and trace_file.
Referenced by BuildNextBlock(), coutCurrentBlockSummary(), LoadAssociationFiles(), LoadBinaryFiles(), LoadNetFile(), LoadStationMap(), SegmentNetwork(), VerifyStationConnections_Block(), VerifyStationsandBuildBlock(), WriteFreeStnListSortedbyASLMsrCount(), and WriteSegmentedNetwork().
ParseStartingStations()
void dynadjust::networksegment::dna_segment::ParseStartingStations () private
Definition at line 92 of file dnasegment.cpp.
{
    // Get stations listed in net file (if it exists)
    // Rememeber, calling app should make sure that
    // projectSettings_.s.net_file contains a valid path if
    // the user wants to use a net file.
    if (boost::filesystem::exists(projectSettings_.s.net_file.c_str()))
        LoadNetFile();
    // OK, now get the additionalstations on the command line
    if (projectSettings_.s.seg_starting_stns.empty())
        return;
    vstring cmd_line_stations;
    try {
        // Extract stations from comma delimited string
        SplitDelimitedString<std::string>(
            projectSettings_.s.seg_starting_stns,   // the comma delimited string
            std::string(","),                           // the delimiter
            &cmd_line_stations);                        // the respective values
    }
    catch (...) {
        return;
    }
    if (!cmd_line_stations.empty())
        vinitialStns_.insert(vinitialStns_.end(), cmd_line_stations.begin(), cmd_line_stations.end());
    if (!vinitialStns_.empty())
        strip_duplicates(vinitialStns_);
}
References LoadNetFile(), projectSettings_, SplitDelimitedString(), strip_duplicates(), and vinitialStns_.
Referenced by PrepareSegmentation().
BuildFirstBlock()
void dynadjust::networksegment::dna_segment::BuildFirstBlock () private
Definition at line 335 of file dnasegment.cpp.
{
    vCurrJunctStnList_.clear();
    vCurrInnerStnList_.clear();
    vCurrMeasurementList_.clear();
    if (vinitialStns_.empty())
        // no station specified? then pick the first one on the free list
        // Remember, vfreeStnList_ is not sorted alphabetically, but according
        // to the number of measurements connected to each station
        vinitialStns_.push_back(bstBinaryRecords_.at(vfreeStnList_.at(0)).stationName);
    else
        RemoveDuplicateStations(&vinitialStns_);        // remove duplicates
    // First pass to validate stations
    VerifyStationsandBuildBlock(true);
    // Second pass to build the block
    VerifyStationsandBuildBlock();
    FinaliseBlock();
}
References bstBinaryRecords_, FinaliseBlock(), RemoveDuplicateStations(), vCurrInnerStnList_, vCurrJunctStnList_, vCurrMeasurementList_, VerifyStationsandBuildBlock(), vfreeStnList_, and vinitialStns_.
Referenced by SegmentNetwork().
BuildNextBlock()
void dynadjust::networksegment::dna_segment::BuildNextBlock () private
Definition at line 505 of file dnasegment.cpp.
{
    // vCurrJunctStnList_ carries the previous block's junction stations. Thus,
    // don't clear it as these stations will become the inners for the next block
    vCurrInnerStnList_.clear();
    vCurrMeasurementList_.clear();
#ifdef _MSDEBUG
    std::string station_name;
#endif
    // Select a new junction station if there are none on the JSL
    // that have free measurements left
    if (vCurrJunctStnList_.empty() && !vfreeStnList_.empty())
    {
        if (!projectSettings_.s.force_contiguous_blocks)
            v_ContiguousNetList_.back() = ++currentNetwork_;
        if (debug_level_ > 1)
        {
            debug_file << "+ Non-contiguous block found... creating a new block using " << bstBinaryRecords_.at(vfreeStnList_.at(0)).stationName << std::endl;
            if (debug_level_ > 2)
                trace_file << " + Non-contiguous block found... creating a new block using " << bstBinaryRecords_.at(vfreeStnList_.at(0)).stationName << std::endl;
        }
        // Select a new junction from the free station list
        SelectJunction();
    }
    if (vCurrJunctStnList_.empty())
    {
        coutSummary();
        SignalExceptionSerialise("BuildNextBlock(): An invalid junction list has been created.  This is most likely a bug.", 0, NULL);
    }
    UINT32 stn_index;
    UINT32 currentTotalSize;
    bool block_threshold_reached = false;
    // Until the threshold is reached...
    //  - Go through the list of junction stations (copied from the previous block) and
    //    make them inner stations if there are new stations connected to them
    //  - If the list is exhausted, add new junctions
    while (!block_threshold_reached)
    {
        // Attempt to add non-contiguous blocks to this block if the
        // station limit hasn't been reached
        if (vfreeStnList_.empty() /*|| vfreeMsrList_.empty()*/)
            break;
        // Is the junction list empty?  force_contiguous_blocks determines what to
        // do in this instance.
        if (projectSettings_.s.force_contiguous_blocks)
        {
            // Add non-contiguous blocks to this block if the
            // station limit hasn't been reached
            if (vCurrJunctStnList_.empty())
                SelectJunction();
        }
        else if (vCurrJunctStnList_.empty())
            break;
        // Get next station from current junction list
        stn_index = SelectInner();
        // Retrieve JSL (all stations connected to this station) and
        // add AML indices to CML for all measurements connected to this station
        GetInnerMeasurements(stn_index);
        currentTotalSize = static_cast<UINT32>(vCurrInnerStnList_.size() + vCurrJunctStnList_.size());
        // Has the station count threshold been exceeded?
        //if (currentTotalSize >= seg_max_total_stations_)
        if (currentTotalSize >= projectSettings_.s.max_total_stations)
        {
            if (vCurrInnerStnList_.size() < projectSettings_.s.min_inner_stations)
                continue;
            block_threshold_reached = true;
            break;
        }
    }
    if (debug_level_ > 2)
    {
        if (block_threshold_reached)
            trace_file << " + Block size threshold exceeded... finishing block." << std::endl;
        else
            trace_file << " + Block " << currentBlock_ << " complete." << std::endl;
    }
    FinaliseBlock();
}
References bstBinaryRecords_, coutSummary(), currentBlock_, currentNetwork_, debug_file, debug_level_, FinaliseBlock(), GetInnerMeasurements(), projectSettings_, SelectInner(), SelectJunction(), SignalExceptionSerialise(), trace_file, v_ContiguousNetList_, vCurrInnerStnList_, vCurrJunctStnList_, vCurrMeasurementList_, and vfreeStnList_.
Referenced by SegmentNetwork().
FinaliseBlock()
void dynadjust::networksegment::dna_segment::FinaliseBlock () private
Definition at line 598 of file dnasegment.cpp.
{
    FindCommonMeasurements();
    MoveJunctiontoISL();
    // Sort lists
    std::sort(vCurrInnerStnList_.begin(), vCurrInnerStnList_.end());
    std::sort(vCurrJunctStnList_.begin(), vCurrJunctStnList_.end());
    strip_duplicates(vCurrMeasurementList_);       // remove duplicates and sort
    vISL_.push_back(vCurrInnerStnList_);
    vJSL_.push_back(vCurrJunctStnList_);
    vCML_.push_back(vCurrMeasurementList_);
    if (debug_level_ > 1)
    {
        coutCurrentBlockSummary(debug_file);
        if (debug_level_ > 2)
        {
            UINT32 currentISLSize, currentJSLSize, currentTotalSize, currentMsrSize;
            currentISLSize = static_cast<UINT32>(vCurrInnerStnList_.size());
            currentJSLSize = static_cast<UINT32>(vCurrJunctStnList_.size());
            currentTotalSize = currentISLSize + currentJSLSize;
            currentMsrSize = static_cast<UINT32>(vCurrMeasurementList_.size());
            trace_file << " + Done." << std::endl;
            trace_file << " + BLOCK " << currentBlock_ << " SUMMARY:" << std::endl;
            trace_file << "   - " << currentISLSize << " inner stations, " << currentJSLSize << " junction stations, ";
            trace_file << currentTotalSize << " total stations, " << currentMsrSize << " measurements." << std::endl;
            trace_file << "   - Inners (" << currentISLSize << "):" << std::endl << "     ";
            it_vUINT32_const _it_freeisl(vfreeStnList_.end());
            for (_it_freeisl=vCurrInnerStnList_.begin(); _it_freeisl!=vCurrInnerStnList_.end(); ++_it_freeisl)
                trace_file << "'" << bstBinaryRecords_.at(*_it_freeisl).stationName << "' ";
            trace_file << std::endl;
            trace_file << "   - Junctions (" << currentJSLSize << "):" << std::endl << "     ";
            for (_it_freeisl=vCurrJunctStnList_.begin(); _it_freeisl!=vCurrJunctStnList_.end(); ++_it_freeisl)
                trace_file << "'" << bstBinaryRecords_.at(*_it_freeisl).stationName << "' ";
            trace_file << std::endl << " + ------------------------------------------" << std::endl;
        }
    }
}
References bstBinaryRecords_, coutCurrentBlockSummary(), currentBlock_, debug_file, debug_level_, FindCommonMeasurements(), MoveJunctiontoISL(), strip_duplicates(), trace_file, vCML_, vCurrInnerStnList_, vCurrJunctStnList_, vCurrMeasurementList_, vfreeStnList_, vISL_, and vJSL_.
Referenced by BuildFirstBlock(), and BuildNextBlock().
SortbyMeasurementCount()
void dynadjust::networksegment::dna_segment::SortbyMeasurementCount (pvUINT32 vStnList) private
Definition at line 1248 of file dnasegment.cpp.
{
    if (vStnList->size() < 2)
        return;
    // sort vStnList by number of measurements to each station (held by vAssocStnList
    CompareMeasCount<CAStationList, UINT32> msrcountCompareFunc(&vAssocStnList_);
    std::sort(vStnList->begin(), vStnList->end(), msrcountCompareFunc);
    // Search lower level
    if (projectSettings_.s.seg_search_level == 0)
        return;
    vUINT32 msrStations;
    vUINT32 stnList, stnCount;
    stnList.insert(stnList.end(), vStnList->begin(),
        (vStnList->begin() + minVal(vUINT32::size_type(5),vStnList->size())));
    IdentifyLowestStationAssociation(&stnList, msrStations, 0, projectSettings_.s.seg_search_level, &stnCount);
    UINT32 lowestStnCount(*(min_element(stnCount.begin(), stnCount.end())));
    if (stnCount.front() == lowestStnCount)
        return;
    it_vUINT32 it_stn(vStnList->begin()), it_count;
    for (it_count=stnCount.begin(); it_count!=stnCount.end(); ++it_stn, ++it_count)
    {
        if (lowestStnCount == *it_count)
            break;
    }
    if (vStnList->size() < 2)
        return;
    lowestStnCount = *it_stn;
    vStnList->erase(it_stn);
    vStnList->insert(vStnList->begin(), lowestStnCount);
}
References IdentifyLowestStationAssociation(), minVal(), projectSettings_, and vAssocStnList_.
Referenced by PrepareSegmentation(), SelectInner(), and SelectJunction().
SelectInner()
UINT32 dynadjust::networksegment::dna_segment::SelectInner () private
Definition at line 426 of file dnasegment.cpp.
{
    // Sort the list of junction stations by the number of measurements
    // connected to them, and begin with the station that has the lowest
    // number of measurements
    SortbyMeasurementCount(&vCurrJunctStnList_);
    it_vUINT32 it_currjsl(vCurrJunctStnList_.begin());
    UINT32 stn_index = *it_currjsl;
    if (debug_level_ > 2)
        trace_file << " + Inner '" << bstBinaryRecords_.at(stn_index).stationName << "'" << std::endl;
#ifdef _MSDEBUG
    std::string station_name =  bstBinaryRecords_.at(stn_index).stationName;
#endif
    // add this junction station to inner station list
    MoveStation(vCurrJunctStnList_, it_currjsl, vCurrInnerStnList_, stn_index);
    return stn_index;
}
References bstBinaryRecords_, debug_level_, MoveStation(), SortbyMeasurementCount(), trace_file, vCurrInnerStnList_, and vCurrJunctStnList_.
Referenced by BuildNextBlock().
SelectJunction()
void dynadjust::networksegment::dna_segment::SelectJunction () private
Definition at line 453 of file dnasegment.cpp.
{
    SortbyMeasurementCount(&vfreeStnList_);
    it_vUINT32 it_newjsl(vfreeStnList_.begin());
    MoveFreeStnToJunctionList(it_newjsl, *it_newjsl);
}
References MoveFreeStnToJunctionList(), SortbyMeasurementCount(), and vfreeStnList_.
Referenced by BuildNextBlock().
MoveStation()
it_vUINT32 dynadjust::networksegment::dna_segment::MoveStation (vUINT32 & fromList, it_vUINT32 it_from, vUINT32 & toList, const UINT32 & stn_index) private
Definition at line 463 of file dnasegment.cpp.
{
    // Move a station from one list to another list
    toList.push_back(stn_index);
    return fromList.erase(it_from);
}
Referenced by MoveFreeStn(), MoveJunctiontoISL(), and SelectInner().
MoveFreeStn()
void dynadjust::networksegment::dna_segment::MoveFreeStn (it_vUINT32 it_freeisl, vUINT32 & toList, const UINT32 & stn_index, const std::string & type) private
Definition at line 471 of file dnasegment.cpp.
{
    if (debug_level_ > 2)
        trace_file << " + New " << type << " station (" << stn_index << ") '" <<
            bstBinaryRecords_.at(stn_index).stationName << "'" << std::endl;
#ifdef _MSDEBUG
    std::string station_name =  bstBinaryRecords_.at(stn_index).stationName;
#endif
    // Mark this station as unavailable
    vfreeStnAvailability_.at(stn_index).consume();
    // Move a station from the free station list to the specified list
    // stnList may be either inner or junction list
    MoveStation(vfreeStnList_, it_freeisl, toList, stn_index);
}
References bstBinaryRecords_, debug_level_, MoveStation(), trace_file, vfreeStnAvailability_, and vfreeStnList_.
Referenced by MoveFreeStnToInnerList(), and MoveFreeStnToJunctionList().
MoveFreeStnToInnerList()
void dynadjust::networksegment::dna_segment::MoveFreeStnToInnerList (it_vUINT32 it_freeisl, const UINT32 & stn_index) private
Definition at line 497 of file dnasegment.cpp.
{
    // Move a station from the free station list to the junction list
    MoveFreeStn(it_freeisl, vCurrInnerStnList_, stn_index, "inner");
}
References MoveFreeStn(), and vCurrInnerStnList_.
Referenced by VerifyStationsandBuildBlock().
MoveFreeStnToJunctionList()
void dynadjust::networksegment::dna_segment::MoveFreeStnToJunctionList (it_vUINT32 it_freeisl, const UINT32 & stn_index) private
Definition at line 490 of file dnasegment.cpp.
{
    // Move a station from the free station list to the junction list
    MoveFreeStn(it_freeisl, vCurrJunctStnList_, stn_index, "junction");
}
References MoveFreeStn(), and vCurrJunctStnList_.
Referenced by AddtoJunctionStnList(), and SelectJunction().
GetInnerMeasurements()
void dynadjust::networksegment::dna_segment::GetInnerMeasurements (const UINT32 & innerStation) private
Definition at line 690 of file dnasegment.cpp.
{
    if (debug_level_ > 2)
        trace_file << " + GetInnerMeasurements()" << std::endl;
#ifdef _MSDEBUG
    std::string from, to, to2;
#endif
    measurement_t measRecord;
    vUINT32 msrStations;
    // Get the original measurement count
    UINT32 m, msrCount(vASLCount_.at(innerStation));
    // Get the aml index, initialised to the last measurement for this station
    UINT32 amlIndex(
        vAssocStnList_.at(innerStation).GetAMLStnIndex()  // beginning of the measurements associated with this station
        + msrCount - 1);                                    // the number of associated measurements
    for (m=0; m<msrCount; ++m, --amlIndex)
    {
        // is this measurement ignored or already used?
        if (!vAssocFreeMsrList_.at(amlIndex).available)
            continue;
        measRecord = bmsBinaryRecords_.at(vAssocFreeMsrList_.at(amlIndex).bmsr_index);
        if (measRecord.ignore)
            continue;
#ifdef _MSDEBUG
        from = bstBinaryRecords_.at(measRecord.station1).stationName;
        if (MsrTally::Stations(measRecord.measType) >= TWO_STATION)
        {
            to = bstBinaryRecords_.at(measRecord.station2).stationName;
            if (MsrTally::Stations(measRecord.measType) == THREE_STATION)
                to2 = bstBinaryRecords_.at(measRecord.station3).stationName;
        }
#endif
        // When a non-measurement element is found (i.e. Y or Z or covariance component),
        // continue to next element.  Hence, only pointers to the starting element of each
        // measurement are kept. See declaration of measRecord.measStart for more info.
        switch (measRecord.measType)
        {
        case 'G':
        case 'X':
        case 'Y':
            if (measRecord.measStart != xMeas)
                continue;
        }
        // Get all the stations associated with this measurement
        GetMsrStations(bmsBinaryRecords_, vAssocFreeMsrList_.at(amlIndex).bmsr_index, msrStations);
        // Add this measurement to the current measurement list
        AddtoCurrentMsrList(amlIndex, msrStations);
        // if this station is not on JSL, move it from the freestnlist to JSL
        AddtoJunctionStnList(msrStations);
    }
}
References AddtoCurrentMsrList(), AddtoJunctionStnList(), bmsBinaryRecords_, bstBinaryRecords_, debug_level_, GetMsrStations(), dynadjust::measurements::msr_t::ignore, dynadjust::measurements::msr_t::measStart, dynadjust::measurements::msr_t::measType, dynadjust::measurements::msr_t::station1, dynadjust::measurements::msr_t::station2, dynadjust::measurements::msr_t::station3, dynadjust::measurements::MsrTally::Stations(), THREE_STATION, trace_file, TWO_STATION, vASLCount_, vAssocFreeMsrList_, vAssocStnList_, and xMeas.
Referenced by BuildNextBlock(), and VerifyStationsandBuildBlock().
IdentifyLowestStationAssociation()
void dynadjust::networksegment::dna_segment::IdentifyLowestStationAssociation (pvUINT32 vStnList, vUINT32 & totalStations, const int currentLevel, const int maxLevel, pvUINT32 vStnCount) private
Definition at line 1192 of file dnasegment.cpp.
{
    it_vUINT32 it_stn;
    vUINT32 msrStations, subStations;
    //if (currentLevel == 0)
    //{
    //  TRACE("Stations to examine:\n");
    //  for_each(vStnList->begin(), vStnList->end(),
    //      [this] (UINT32& stn) {
    //          TRACE("%d ", stn);
    //  });
    //  TRACE("\n");
    //}
    for (it_stn=vStnList->begin(); it_stn!=vStnList->end(); ++it_stn)
    {
        if (currentLevel == 0)
            vStnCount->push_back(0);
        //TRACE("Level %d  Station %d: ", currentLevel, *it_stn);
        IdentifyInnerMsrsandAssociatedStns(*it_stn, msrStations);
        //for_each(msrStations.begin(), msrStations.end(),
        //  [this] (UINT32& stn) {
        //      TRACE("%d ", stn);
        //});
        //TRACE("\n  ");
        if (currentLevel < maxLevel)
            IdentifyLowestStationAssociation(&msrStations, subStations, currentLevel + 1, maxLevel, vStnCount);
        subStations.insert(subStations.end(), msrStations.begin(), msrStations.end());
        if (currentLevel == 0)
        {
            // get total stations associated with this station
            strip_duplicates(subStations);
            vStnCount->back() = static_cast<UINT32>(subStations.size());
        }
    }
    if (currentLevel == 0)
        return;
    totalStations.insert(totalStations.end(), subStations.begin(), subStations.end());
    strip_duplicates(totalStations);
    //TRACE("Summary (%d stations): ", totalStations.size());
    //for_each(totalStations.begin(), totalStations.end(),
    //  [this] (UINT32& stn) {
    //      TRACE("%d ", stn);
    //});
    //TRACE("\n\n");
}
References IdentifyInnerMsrsandAssociatedStns(), IdentifyLowestStationAssociation(), and strip_duplicates().
Referenced by IdentifyLowestStationAssociation(), and SortbyMeasurementCount().
IdentifyInnerMsrsandAssociatedStns()
void dynadjust::networksegment::dna_segment::IdentifyInnerMsrsandAssociatedStns (const UINT32 & innerStation, vUINT32 & totalStations) private
Definition at line 1148 of file dnasegment.cpp.
{
    it_vmsr_t measRecord;
    vUINT32 msrStations;
    // Get the original measurement count
    UINT32 m, msrCount(vASLCount_.at(innerStation));
    // Get the aml index, initialised to the last measurement for this station
    UINT32 amlIndex(
        vAssocStnList_.at(innerStation).GetAMLStnIndex()  // beginning of the measurements associated with this station
        + msrCount - 1);                                    // the number of associated measurements
    for (m=0; m<msrCount; ++m, --amlIndex)
    {
        // is this measurement ignored or already used?
        if (!vAssocFreeMsrList_.at(amlIndex).available)
            continue;
        measRecord = bmsBinaryRecords_.begin() + vAssocFreeMsrList_.at(amlIndex).bmsr_index;
        if (measRecord->ignore)
            continue;
        // When a non-measurement element is found (i.e. Y or Z or covariance component),
        // continue to next element.  Hence, only pointers to the starting element of each
        // measurement are kept. See declaration of measRecord.measStart for more info.
        switch (measRecord->measType)
        {
        case 'G':
        case 'X':
        case 'Y':
            if (measRecord->measStart != xMeas)
                continue;
        }
        // Get all the stations associated with this measurement
        GetMsrStations(bmsBinaryRecords_, vAssocFreeMsrList_.at(amlIndex).bmsr_index, msrStations);
        totalStations.insert(totalStations.end(), msrStations.begin(), msrStations.end());
    }
    strip_duplicates(totalStations);
}
References bmsBinaryRecords_, GetMsrStations(), strip_duplicates(), vASLCount_, vAssocFreeMsrList_, vAssocStnList_, and xMeas.
Referenced by IdentifyLowestStationAssociation().
AddtoJunctionStnList()
void dynadjust::networksegment::dna_segment::AddtoJunctionStnList (const vUINT32 & msrStations) private
Definition at line 983 of file dnasegment.cpp.
{
    it_vUINT32_const _it_stn;
    it_vUINT32 _it_freeisl;
    for (_it_stn=msrStations.begin(); _it_stn!=msrStations.end(); ++_it_stn)
    {
        // If First station is not already in the junction list...
        //if (find_if(vCurrJunctStnList_.begin(), vCurrJunctStnList_.end(),
        //  bind1st(equal_to<UINT32>(), *_it_stn)) == vCurrJunctStnList_.end())
        if (find_if(vCurrJunctStnList_.begin(), vCurrJunctStnList_.end(),
            [&_it_stn](const UINT32& junctionStn) {
                return junctionStn == *_it_stn; }) == vCurrJunctStnList_.end())
        {
            // If the first station is available, get an iterator to it and move it
            if (vfreeStnAvailability_.at(*_it_stn).isfree())
            {
                // Move it to the list of junctions
                //if ((_it_freeisl = find_if(vfreeStnList_.begin(), vfreeStnList_.end(),
                //  bind1st(equal_to<UINT32>(), *_it_stn))) != vfreeStnList_.end())
                if ((_it_freeisl = find_if(vfreeStnList_.begin(), vfreeStnList_.end(),
                    [&_it_stn](const UINT32& freeStn) {
                        return freeStn == *_it_stn; })) != vfreeStnList_.end())
                {
                    MoveFreeStnToJunctionList(_it_freeisl, *_it_stn);
                }
            }
        }
    }
}
References MoveFreeStnToJunctionList(), vCurrJunctStnList_, vfreeStnAvailability_, and vfreeStnList_.
Referenced by GetInnerMeasurements().
AddtoCurrentMsrList()
bool dynadjust::networksegment::dna_segment::AddtoCurrentMsrList (const UINT32 & amlindex, const vUINT32 & msrStations) private
Definition at line 756 of file dnasegment.cpp.
{
    if (!vAssocFreeMsrList_.at(amlIndex).available)
        return false;
    UINT32 m, msrCount, bmsrindex(vAssocFreeMsrList_.at(amlIndex).bmsr_index);
#ifdef _MSDEBUG
    measurement_t msr(bmsBinaryRecords_.at(bmsrindex));
    char measType(msr.measType);
    std::string station;
    UINT32 stn_index;
#endif
    UINT32 firstIndex(GetFirstMsrIndex<UINT32>(bmsBinaryRecords_, bmsrindex));
    // Add the index of the first binary measurement record to the measurement list
    vCurrMeasurementList_.push_back(firstIndex);
    if (debug_level_ > 2)
    {
        trace_file << "   - Measurement '" << bmsBinaryRecords_.at(bmsrindex).measType << "' ";
        if (bmsBinaryRecords_.at(bmsrindex).ignore)
            trace_file << "(ignored) ";
        trace_file << "associated with station(s): ";
    }
    it_aml_pair _it_aml;
    it_vUINT32_const _it_stn, _it_msr;
    // 1) consume each occurrence of this measurement (and all other
    //    measurements within a cluster) on the AML, then
    // 2) Decrement the measurement count for all stations associated
    //    with this measurement.
    for (_it_stn=msrStations.begin(); _it_stn!=msrStations.end(); ++_it_stn)
    {
        // Consume the occurrences of this measurement (and other measurements in a cluster)
        // in the aml for the stations in msrStations
#ifdef _MSDEBUG
        stn_index = *_it_stn;
        station = bstBinaryRecords_.at(*_it_stn).stationName;
#endif
        if (debug_level_ > 2)
            trace_file << bstBinaryRecords_.at(*_it_stn).stationName << " ";
        // set _it_aml to point to the first aml entry for station *_it_stn
        _it_aml = vAssocFreeMsrList_.begin() + vAssocStnList_.at(*_it_stn).GetAMLStnIndex();
        msrCount = vASLCount_.at(*_it_stn);
        // consume measurement and decrement measurement count
        for (m=0; m<msrCount; ++m, ++_it_aml)
        {
            // is this measurement ignored or already used?
            if (!_it_aml->available)
                continue;
            if (_it_aml->bmsr_index == bmsrindex)
            {
                // Consume the measurement
                _it_aml->consume();
                // Decrement the measurement count.
                vAssocStnList_.at(*_it_stn).DecrementMsrCount();
                break;
            }
        }
    }
    if (debug_level_ > 2)
        trace_file << std::endl;
    return true;
}
References bmsBinaryRecords_, bstBinaryRecords_, debug_level_, GetFirstMsrIndex(), dynadjust::measurements::msr_t::measType, trace_file, vASLCount_, vAssocFreeMsrList_, vAssocStnList_, and vCurrMeasurementList_.
Referenced by FindCommonMeasurements(), and GetInnerMeasurements().
GetAvailableMsrCount()
UINT32 dynadjust::networksegment::dna_segment::GetAvailableMsrCount (const UINT32 & stn_index) private
Definition at line 919 of file dnasegment.cpp.
{
    return vAssocStnList_.at(stn_index).GetAvailMsrCount();
}
References vAssocStnList_.
Referenced by MoveJunctiontoISL().
FindCommonMeasurements()
void dynadjust::networksegment::dna_segment::FindCommonMeasurements () private
Definition at line 838 of file dnasegment.cpp.
{
    // Create a temporary vector
    vUINT32 vCurrBlockStnList(vCurrJunctStnList_), msrStations;
    std::sort(vCurrBlockStnList.begin(), vCurrBlockStnList.end());
    it_vUINT32 _it_stn, _it_mstn;
    measurement_t measRecord;
    bool inList;
    if (debug_level_ > 2)
        trace_file << " + FindCommonMeasurements()" << std::endl;
#ifdef _MSDEBUG
    std::string stn;
#endif
    UINT32 m, msrCount, amlIndex;
    for (_it_stn=vCurrBlockStnList.begin(); _it_stn!=vCurrBlockStnList.end(); ++_it_stn)
    {
        // Get the original measurement count
        msrCount = vASLCount_.at(*_it_stn);
        amlIndex = vAssocStnList_.at(*_it_stn).GetAMLStnIndex();
#ifdef _MSDEBUG
        stn = bstBinaryRecords_.at(*_it_stn).stationName;
#endif
        for (m=0; m<msrCount; ++m, ++amlIndex)
        {
            // is this measurement ignored or already used?
            if (!vAssocFreeMsrList_.at(amlIndex).available)
                continue;
            measRecord = bmsBinaryRecords_.at(vAssocFreeMsrList_.at(amlIndex).bmsr_index);
            if (measRecord.ignore)
                continue;
            // Get all the stations associated with this measurement
            GetMsrStations(bmsBinaryRecords_, vAssocFreeMsrList_.at(amlIndex).bmsr_index, msrStations);
            // Since a single station measurement is not associated with other stations,
            // add the measurement to the list
            if (msrStations.size() == 1)
            {
                // Add this measurement to the current measurement list
                AddtoCurrentMsrList(amlIndex, msrStations);
                continue;
            }
            // Assume this measurement is common to the stations on vCurrBlockStnList.
            // inList will be set to false if a measurement station is not found on
            // the list
            inList = true;
            // Two or more station measurements
            for (_it_mstn=msrStations.begin(); _it_mstn!=msrStations.end(); ++_it_mstn)
            {
                // If one station in msrStations (which are all stations
                // associated with the current measurement) is not in the junction list,
                // then this cannot be a "common measurement".
                if (!binary_search(vCurrBlockStnList.begin(), vCurrBlockStnList.end(), *_it_mstn))
                {
                    // The station at _it_mstn is not in vCurrBlockStnList, so this is not a
                    // "common measurement" - break out of loop.
                    inList = false;
                    break;
                }
            }
            // If all stations in msrStations are found within vCurrBlockStnList, then
            // add this measurement to the current measurement list
            if (inList)
                AddtoCurrentMsrList(amlIndex, msrStations);
        }
    }
}
References AddtoCurrentMsrList(), bmsBinaryRecords_, bstBinaryRecords_, debug_level_, GetMsrStations(), dynadjust::measurements::msr_t::ignore, trace_file, vASLCount_, vAssocFreeMsrList_, vAssocStnList_, and vCurrJunctStnList_.
Referenced by FinaliseBlock().
MoveJunctiontoISL()
void dynadjust::networksegment::dna_segment::MoveJunctiontoISL () private
Definition at line 931 of file dnasegment.cpp.
{
    // Move stations on the current junction station list to the inner station list if
    // there are no more measurements tied to this station
    if (debug_level_ > 2)
        trace_file << " + MoveJunctiontoISL()" << std::endl;
#ifdef _MSDEBUG
    std::string station_name;
#endif
    it_vUINT32 _it_currjsl(vCurrJunctStnList_.begin());
    UINT32 stn_index;
    while (!vCurrJunctStnList_.empty())
    {
        stn_index = *_it_currjsl;
#ifdef _MSDEBUG
        station_name = bstBinaryRecords_.at(stn_index).stationName;
#endif
        // Are there no more available measurements connected to this station?
        if (GetAvailableMsrCount(stn_index) == 0)
        {
            if (debug_level_ > 2)
                trace_file << "   - Junction station '" <<
                    bstBinaryRecords_.at(static_cast<UINT32>(stn_index)).stationName <<
                    "' was moved to inner list (no more available measurements)." << std::endl;
            // Move this station from the junctions list to inners list
            _it_currjsl = MoveStation(vCurrJunctStnList_, _it_currjsl,
                vCurrInnerStnList_, stn_index);
            // Have all JSLs been removed?
            if (vCurrJunctStnList_.empty())
                // end the while loop
                break;
            else if (_it_currjsl == vCurrJunctStnList_.end())
                // reset the iterator to the previous junction station
                --_it_currjsl;
            continue;
        }
        // move to the next junction, unless the iterator is
        // pointing to the last
        if (++_it_currjsl == vCurrJunctStnList_.end())
            break;
    }
}
References bstBinaryRecords_, debug_level_, GetAvailableMsrCount(), MoveStation(), trace_file, vCurrInnerStnList_, and vCurrJunctStnList_.
Referenced by FinaliseBlock().
SetAvailableMsrCount()
void dynadjust::networksegment::dna_segment::SetAvailableMsrCount () private
Definition at line 1288 of file dnasegment.cpp.
{
    _it_vasl _it_asl;
    UINT32 stn_index, msrCount, amlIndex;
    for (_it_asl=vAssocStnList_.begin();
        _it_asl!=vAssocStnList_.end();
        ++_it_asl)
    {
        stn_index = static_cast<UINT32>(std::distance(vAssocStnList_.begin(), _it_asl));
        _it_asl->SetAvailMsrCount(_it_asl->GetAssocMsrCount());
        if (_it_asl->GetAssocMsrCount() == 0)
            continue;
        msrCount = vASLCount_.at(stn_index);  // original measurement count
        amlIndex = vAssocStnList_.at(stn_index).GetAMLStnIndex();
        // if a measurement is ignored, it will not be available
        for (UINT32 m(0); m<msrCount; ++m, ++amlIndex)
        {
            if (!vAssocFreeMsrList_.at(amlIndex).available)
                _it_asl->DecrementAvailMsrCount();
        }
    }
}
References vASLCount_, vAssocFreeMsrList_, and vAssocStnList_.
Referenced by LoadAssociationFiles().
RemoveDuplicateStations()
void dynadjust::networksegment::dna_segment::RemoveDuplicateStations (pvstring vStations) private
Definition at line 1332 of file dnasegment.cpp.
{
    if (vStations->size() < 2)
        return;
    // A prior sort on name is essential, since the criteria for removing duplicates
    // is based upon two successive station entries in an ordered vector being equal
    strip_duplicates(vStations);
}
References strip_duplicates().
Referenced by BuildFirstBlock().
RemoveInvalidFreeStations()
void dynadjust::networksegment::dna_segment::RemoveInvalidFreeStations () private
Definition at line 1318 of file dnasegment.cpp.
{
    CompareValidity<CAStationList, UINT32> aslValidityCompareFunc(&vAssocStnList_, FALSE);
    std::sort(vfreeStnList_.begin(), vfreeStnList_.end(), aslValidityCompareFunc);
    erase_if(vfreeStnList_, aslValidityCompareFunc);
}
References erase_if(), FALSE, vAssocStnList_, and vfreeStnList_.
Referenced by LoadAssociationFiles().
BuildFreeStationAvailabilityList()
void dynadjust::networksegment::dna_segment::BuildFreeStationAvailabilityList () private
Definition at line 1326 of file dnasegment.cpp.
{
    dna_io_seg seg;
    seg.build_free_stn_availability(vAssocStnList_, vfreeStnAvailability_);
}
References dynadjust::iostreams::dna_io_seg::build_free_stn_availability(), vAssocStnList_, and vfreeStnAvailability_.
Referenced by PrepareSegmentation().
CalculateAverageBlockSize()
void dynadjust::networksegment::dna_segment::CalculateAverageBlockSize () private
Definition at line 299 of file dnasegment.cpp.
{
    vUINT32 blockSizes;
    blockSizes.resize(vISL_.size());
    it_vUINT32 _it_count;
    it_vvUINT32 _it_isl, _it_jsl;
    for (_it_count=blockSizes.begin(), _it_isl=vISL_.begin(), _it_jsl=vJSL_.begin();
        _it_isl!=vISL_.end();
        ++_it_count, ++_it_isl, ++_it_jsl)
        *_it_count = static_cast<UINT32>(_it_isl->size() + _it_jsl->size());
    averageBlockSize_ = average<double, UINT32, it_vUINT32>(blockSizes.begin(), blockSizes.end(), stationSolutionCount_);
    maxBlockSize_ = *(max_element(blockSizes.begin(), blockSizes.end()));
    minBlockSize_ = *(min_element(blockSizes.begin(), blockSizes.end()));
}
References average(), averageBlockSize_, maxBlockSize_, minBlockSize_, stationSolutionCount_, vISL_, and vJSL_.
Referenced by SegmentNetwork().
VerifyStationConnections_Block()
void dynadjust::networksegment::dna_segment::VerifyStationConnections_Block (const UINT32 & block) private
Definition at line 1525 of file dnasegment.cpp.
{
    vUINT32::const_iterator _it_isl, _it_jsl, _it_cml;
    bool stationAssociated;
    vUINT32 unusedStns, msrStations, allmsrStations;
#ifdef _MSDEBUG
    std::string isl_stn_name;
#endif
    // get all stations connected with measurements
    for (_it_cml=vCML_.at(block).begin(); _it_cml!=vCML_.at(block).end(); ++_it_cml)
    {
        // Get all the stations associated with this measurement
        GetMsrStations(bmsBinaryRecords_, *_it_cml, msrStations);
        // Append to master station list
        allmsrStations.insert(allmsrStations.end(), msrStations.begin(), msrStations.end());
    }
    strip_duplicates(allmsrStations);
    // Check all isl stations are associated with a measurement
    // No need to check jsl stations as a junction may appear in a block
    // as a result of being carried forward without any measurements
    for (_it_isl=vISL_.at(block).begin(); _it_isl!=vISL_.at(block).end(); ++_it_isl)
    {
        stationAssociated = false;
        if (binary_search(allmsrStations.begin(), allmsrStations.end(), *_it_isl))
            stationAssociated = true;
        if (!stationAssociated)
        {
            unusedStns.push_back(*_it_isl);
#ifdef _MSDEBUG
            isl_stn_name = bstBinaryRecords_.at(*_it_isl).stationName;
#endif
        }
    }
    if (!unusedStns.empty())
    {
        std::stringstream ss;
        ss << "The following station(s) are not associated with any" << std::endl <<
            "  measurements in block " << block+1 << ":" << std::endl;
        for_each(unusedStns.begin(), unusedStns.end(),
            [this, &ss](UINT32& stn){
                ss << "  " << bstBinaryRecords_.at(stn).stationName << " (" << stn << ")" << std::endl;
        });
        SignalExceptionSerialise(ss.str(), 0, NULL);
    }
}
References bmsBinaryRecords_, bstBinaryRecords_, GetMsrStations(), SignalExceptionSerialise(), strip_duplicates(), vCML_, and vISL_.
Referenced by VerifyStationConnections().
VerifyStationsandBuildBlock()
void dynadjust::networksegment::dna_segment::VerifyStationsandBuildBlock (bool validationOnly = false) private
Definition at line 358 of file dnasegment.cpp.
{
#ifdef _MSDEBUG
    UINT32 stn_index;
#endif
    it_vUINT32 _it_freeisl;
    _it_vstr_const _it_name(vinitialStns_.begin());
    it_pair_string_vUINT32 it_stnmap_range;
    v_string_uint32_pair::iterator _it_stnmap(stnsMap_.begin());
    // For each station name specified as the initial stations
    for (_it_name=vinitialStns_.begin(); _it_name!=vinitialStns_.end(); ++_it_name)
    {
        // Retrieve the ASL index
        it_stnmap_range = equal_range(stnsMap_.begin(), stnsMap_.end(), *_it_name, StationNameIDCompareName());
        if (it_stnmap_range.first == it_stnmap_range.second)
        {
            // If this point is reached, _it_stnmap->second is not a known network station
            std::stringstream ss;
            ss << "VerifyStationsandBuildBlock(): " << *_it_name << " is not in the list of network stations.";
            SignalExceptionSerialise(ss.str(), 0, NULL);
        }
        _it_stnmap = it_stnmap_range.first;
#ifdef _MSDEBUG
        stn_index = _it_stnmap->second;
#endif
        // add this station to inner station list if it is on the free stations list only.
        // vfreeStnList_ is sorted according to the number of measurements connected to each station
        // hence, a binary_search (or lower_bound or similar) cannot be used here
        // Check if this station is available before trying to find it.  Why?
        // find_if over a large vector is not fast like binary_search
        if (vfreeStnAvailability_.at(_it_stnmap->second).isfree())
        {
            // Ok, find it and remove it
            //if ((_it_freeisl = find_if(vfreeStnList_.begin(), vfreeStnList_.end(),
            //  bind1st(std::equal_to<UINT32>(), _it_stnmap->second))) != vfreeStnList_.end())
            if ((_it_freeisl = find_if(vfreeStnList_.begin(), vfreeStnList_.end(),
                [&_it_stnmap](const UINT32& freeStn) {
                    return freeStn == _it_stnmap->second; } )) != vfreeStnList_.end())
            {
                if (!validationOnly)
                    MoveFreeStnToInnerList(_it_freeisl, _it_stnmap->second);
            }
        }
        else
        {
            if (validationOnly)
            {
                // If this point is reached, _it_stnmap->second is a known network station but is
                // invalid or has no measurements connected to it.
                std::stringstream ss;
                ss << "VerifyStationsandBuildBlock(): " << bstBinaryRecords_.at(_it_stnmap->second).stationName << " does not have any measurements connected to it.";
                SignalExceptionSerialise(ss.str(), 0, NULL);
            }
        }
        if (!validationOnly)
            // Retrieve JSL (all stations connected to this station) and
            // add AML indices to CML for all measurements connected to this station
            GetInnerMeasurements(_it_stnmap->second);
    }
}
References bstBinaryRecords_, GetInnerMeasurements(), MoveFreeStnToInnerList(), SignalExceptionSerialise(), stnsMap_, vfreeStnAvailability_, vfreeStnList_, and vinitialStns_.
Referenced by BuildFirstBlock().
Member Data Documentation
projectSettings_
project_settings dynadjust::networksegment::dna_segment::projectSettings_ private
Definition at line 171 of file dnasegment.hpp.
Referenced by BuildNextBlock(), LoadNetFile(), ParseStartingStations(), PrepareSegmentation(), SortbyMeasurementCount(), and WriteSegmentedNetwork().
segmentStatus_
_SEGMENT_STATUS_ dynadjust::networksegment::dna_segment::segmentStatus_ private
Definition at line 173 of file dnasegment.hpp.
Referenced by GetStatus(), InitialiseSegmentation(), SegmentNetwork(), and SignalExceptionSerialise().
isProcessing_
bool dynadjust::networksegment::dna_segment::isProcessing_ private
Definition at line 174 of file dnasegment.hpp.
Referenced by dna_segment(), InitialiseSegmentation(), SegmentNetwork(), and SignalExceptionSerialise().
currentBlock_
UINT32 dynadjust::networksegment::dna_segment::currentBlock_ private
Definition at line 175 of file dnasegment.hpp.
Referenced by BuildNextBlock(), coutCurrentBlockSummary(), currentBlock(), FinaliseBlock(), InitialiseSegmentation(), and SegmentNetwork().
currentNetwork_
UINT32 dynadjust::networksegment::dna_segment::currentNetwork_ private
Definition at line 176 of file dnasegment.hpp.
Referenced by BuildNextBlock(), and SegmentNetwork().
network_name_
std::string dynadjust::networksegment::dna_segment::network_name_ private
Definition at line 178 of file dnasegment.hpp.
Referenced by dna_segment(), InitialiseSegmentation(), and PrepareSegmentation().
debug_level_
UINT16 dynadjust::networksegment::dna_segment::debug_level_ private
Definition at line 179 of file dnasegment.hpp.
Referenced by AddtoCurrentMsrList(), BuildNextBlock(), FinaliseBlock(), FindCommonMeasurements(), GetInnerMeasurements(), MoveFreeStn(), MoveJunctiontoISL(), SegmentNetwork(), SelectInner(), and SignalExceptionSerialise().
output_folder_
std::string dynadjust::networksegment::dna_segment::output_folder_ private
Definition at line 181 of file dnasegment.hpp.
Referenced by SegmentNetwork(), and WriteFreeStnListSortedbyASLMsrCount().
clusteridCompareFunc_
CompareClusterID<measurement_t, UINT32> dynadjust::networksegment::dna_segment::clusteridCompareFunc_ private
Definition at line 184 of file dnasegment.hpp.
Referenced by LoadBinaryFiles().
vinitialStns_
vstring dynadjust::networksegment::dna_segment::vinitialStns_ private
Definition at line 187 of file dnasegment.hpp.
Referenced by BuildFirstBlock(), InitialiseSegmentation(), LoadNetFile(), ParseStartingStations(), StartingStations(), VerifyStationsandBuildBlock(), and WriteSegmentedNetwork().
v_ContiguousNetList_
vUINT32 dynadjust::networksegment::dna_segment::v_ContiguousNetList_ private
Definition at line 188 of file dnasegment.hpp.
Referenced by BuildNextBlock(), SegmentNetwork(), and WriteSegmentedNetwork().
vCurrJunctStnList_
vUINT32 dynadjust::networksegment::dna_segment::vCurrJunctStnList_ private
Definition at line 189 of file dnasegment.hpp.
Referenced by AddtoJunctionStnList(), BuildFirstBlock(), BuildNextBlock(), coutCurrentBlockSummary(), FinaliseBlock(), FindCommonMeasurements(), InitialiseSegmentation(), MoveFreeStnToJunctionList(), MoveJunctiontoISL(), and SelectInner().
vCurrInnerStnList_
vUINT32 dynadjust::networksegment::dna_segment::vCurrInnerStnList_ private
Definition at line 190 of file dnasegment.hpp.
Referenced by BuildFirstBlock(), BuildNextBlock(), coutCurrentBlockSummary(), FinaliseBlock(), InitialiseSegmentation(), MoveFreeStnToInnerList(), MoveJunctiontoISL(), and SelectInner().
vCurrMeasurementList_
vUINT32 dynadjust::networksegment::dna_segment::vCurrMeasurementList_ private
Definition at line 191 of file dnasegment.hpp.
Referenced by AddtoCurrentMsrList(), BuildFirstBlock(), BuildNextBlock(), coutCurrentBlockSummary(), FinaliseBlock(), and InitialiseSegmentation().
bstBinaryRecords_
vstn_t dynadjust::networksegment::dna_segment::bstBinaryRecords_ private
Definition at line 193 of file dnasegment.hpp.
Referenced by AddtoCurrentMsrList(), BuildFirstBlock(), BuildNextBlock(), coutCurrentBlockSummary(), DefaultStartingStation(), FinaliseBlock(), FindCommonMeasurements(), GetInnerMeasurements(), GetProgress(), InitialiseSegmentation(), LoadBinaryFiles(), MoveFreeStn(), MoveJunctiontoISL(), SegmentNetwork(), SelectInner(), VerifyStationConnections_Block(), VerifyStationsandBuildBlock(), WriteFreeStnListSortedbyASLMsrCount(), and WriteSegmentedNetwork().
bmsBinaryRecords_
vmsr_t dynadjust::networksegment::dna_segment::bmsBinaryRecords_ private
Definition at line 194 of file dnasegment.hpp.
Referenced by AddtoCurrentMsrList(), coutCurrentBlockSummary(), FindCommonMeasurements(), GetInnerMeasurements(), IdentifyInnerMsrsandAssociatedStns(), InitialiseSegmentation(), LoadAssociationFiles(), LoadBinaryFiles(), SegmentNetwork(), VerifyStationConnections_Block(), and WriteSegmentedNetwork().
vAssocStnList_
vASL dynadjust::networksegment::dna_segment::vAssocStnList_ private
Definition at line 195 of file dnasegment.hpp.
Referenced by AddtoCurrentMsrList(), BuildFreeStationAvailabilityList(), FindCommonMeasurements(), GetAvailableMsrCount(), GetInnerMeasurements(), IdentifyInnerMsrsandAssociatedStns(), InitialiseSegmentation(), LoadAssociationFiles(), RemoveInvalidFreeStations(), SegmentNetwork(), SetAvailableMsrCount(), SortbyMeasurementCount(), and WriteFreeStnListSortedbyASLMsrCount().
vASLCount_
vUINT32 dynadjust::networksegment::dna_segment::vASLCount_ private
Definition at line 196 of file dnasegment.hpp.
Referenced by AddtoCurrentMsrList(), FindCommonMeasurements(), GetInnerMeasurements(), IdentifyInnerMsrsandAssociatedStns(), LoadAssociationFiles(), and SetAvailableMsrCount().
vAssocMsrList_
vUINT32 dynadjust::networksegment::dna_segment::vAssocMsrList_ private
Definition at line 197 of file dnasegment.hpp.
Referenced by InitialiseSegmentation().
vAssocFreeMsrList_
v_aml_pair dynadjust::networksegment::dna_segment::vAssocFreeMsrList_ private
Definition at line 198 of file dnasegment.hpp.
Referenced by AddtoCurrentMsrList(), FindCommonMeasurements(), GetInnerMeasurements(), IdentifyInnerMsrsandAssociatedStns(), LoadAssociationFiles(), SegmentNetwork(), and SetAvailableMsrCount().
vfreeStnList_
vUINT32 dynadjust::networksegment::dna_segment::vfreeStnList_ private
Definition at line 199 of file dnasegment.hpp.
Referenced by AddtoJunctionStnList(), BuildFirstBlock(), BuildNextBlock(), coutCurrentBlockSummary(), coutSummary(), DefaultStartingStation(), FinaliseBlock(), GetProgress(), InitialiseSegmentation(), LoadAssociationFiles(), MoveFreeStn(), PrepareSegmentation(), RemoveInvalidFreeStations(), SegmentNetwork(), SelectJunction(), VerifyStationsandBuildBlock(), and WriteFreeStnListSortedbyASLMsrCount().
vfreeMsrList_
vUINT32 dynadjust::networksegment::dna_segment::vfreeMsrList_ private
Definition at line 200 of file dnasegment.hpp.
Referenced by coutCurrentBlockSummary(), and InitialiseSegmentation().
stnsMap_
v_string_uint32_pair dynadjust::networksegment::dna_segment::stnsMap_ private
Definition at line 201 of file dnasegment.hpp.
Referenced by InitialiseSegmentation(), LoadStationMap(), SegmentNetwork(), and VerifyStationsandBuildBlock().
vfreeStnAvailability_
v_freestn_pair dynadjust::networksegment::dna_segment::vfreeStnAvailability_ private
Definition at line 203 of file dnasegment.hpp.
Referenced by AddtoJunctionStnList(), BuildFreeStationAvailabilityList(), MoveFreeStn(), and VerifyStationsandBuildBlock().
vJSL_
vvUINT32 dynadjust::networksegment::dna_segment::vJSL_ private
Definition at line 205 of file dnasegment.hpp.
Referenced by CalculateAverageBlockSize(), coutSummary(), FinaliseBlock(), InitialiseSegmentation(), and WriteSegmentedNetwork().
vISL_
vvUINT32 dynadjust::networksegment::dna_segment::vISL_ private
Definition at line 206 of file dnasegment.hpp.
Referenced by blockCount(), CalculateAverageBlockSize(), coutSummary(), FinaliseBlock(), InitialiseSegmentation(), VerifyStationConnections(), VerifyStationConnections_Block(), and WriteSegmentedNetwork().
vCML_
vvUINT32 dynadjust::networksegment::dna_segment::vCML_ private
Definition at line 207 of file dnasegment.hpp.
Referenced by coutSummary(), FinaliseBlock(), InitialiseSegmentation(), VerifyStationConnections_Block(), and WriteSegmentedNetwork().
debug_file
std::ofstream dynadjust::networksegment::dna_segment::debug_file private
Definition at line 209 of file dnasegment.hpp.
Referenced by BuildNextBlock(), FinaliseBlock(), SegmentNetwork(), and SignalExceptionSerialise().
trace_file
std::ofstream dynadjust::networksegment::dna_segment::trace_file private
Definition at line 210 of file dnasegment.hpp.
Referenced by AddtoCurrentMsrList(), BuildNextBlock(), FinaliseBlock(), FindCommonMeasurements(), GetInnerMeasurements(), MoveFreeStn(), MoveJunctiontoISL(), SegmentNetwork(), SelectInner(), and SignalExceptionSerialise().
averageBlockSize_
double dynadjust::networksegment::dna_segment::averageBlockSize_ private
Definition at line 212 of file dnasegment.hpp.
Referenced by averageblockSize(), and CalculateAverageBlockSize().
stationSolutionCount_
UINT32 dynadjust::networksegment::dna_segment::stationSolutionCount_ private
Definition at line 213 of file dnasegment.hpp.
Referenced by CalculateAverageBlockSize(), and stationSolutionCount().
minBlockSize_
UINT32 dynadjust::networksegment::dna_segment::minBlockSize_ private
Definition at line 214 of file dnasegment.hpp.
Referenced by CalculateAverageBlockSize(), and minBlockSize().
maxBlockSize_
UINT32 dynadjust::networksegment::dna_segment::maxBlockSize_ private
Definition at line 215 of file dnasegment.hpp.
Referenced by CalculateAverageBlockSize(), and maxBlockSize().
The documentation for this class was generated from the following files:
dynadjust/dnasegment/dnasegment.hpp
dynadjust/dnasegment/dnasegment.cpp