DynAdjust: dynadjust::iostreams::dna_io_pdf Class Reference
dynadjust::iostreams::dna_io_pdf Class Reference
#include <dnaiopdf.hpp>
Public Member Functions
dna_io_pdf (void)
dna_io_pdf (const dna_io_pdf &)
virtual ~dna_io_pdf (void)
dna_io_pdf & operator= (const dna_io_pdf &rhs)
std::string form_pdf_action_command_string (const std::string &pdf_filename, const std::string &ddename, const std::string &action)
std::string form_pdf_close_string (const std::string &pdf_filename, const std::string &ddename)
std::string form_pdf_open_string (const std::string &pdf_filename, const std::string &ddename)
Public Member Functions inherited from dynadjust::iostreams::dna_io_base
dna_io_base (void)
dna_io_base (const dna_io_base &)
virtual ~dna_io_base (void)
dna_io_base & operator= (const dna_io_base &rhs)
std::string getVersion () const
void setVersion (const std::string &version)
void writeFileInfo (std::ofstream &file_stream)
void readFileInfo (std::ifstream &file_stream)
void writeFileMetadata (std::ofstream &file_stream, binary_file_meta_t &file_meta)
void readFileMetadata (std::ifstream &file_stream, binary_file_meta_t &file_meta)
Additional Inherited Members
Protected Member Functions inherited from dynadjust::iostreams::dna_io_base
void writeVersion (std::ofstream &file_stream)
void readVersion (std::ifstream &file_stream)
void writeDate (std::ofstream &file_stream)
void readDate (std::ifstream &file_stream)
void writeApp (std::ofstream &file_stream)
void readApp (std::ifstream &file_stream)
Protected Attributes inherited from dynadjust::iostreams::dna_io_base
std::string m_strVersion
std::string m_strDate
std::string m_strApp
Detailed Description
Definition at line 71 of file dnaiopdf.hpp.
Constructor & Destructor Documentation
dna_io_pdf() [1/2]
dynadjust::iostreams::dna_io_pdf::dna_io_pdf (void) inline
Definition at line 74 of file dnaiopdf.hpp.
{};
Referenced by dna_io_pdf(), and operator=().
dna_io_pdf() [2/2]
dynadjust::iostreams::dna_io_pdf::dna_io_pdf (const dna_io_pdf &) inline
Definition at line 75 of file dnaiopdf.hpp.
{};
References dna_io_pdf().
~dna_io_pdf()
virtual dynadjust::iostreams::dna_io_pdf::~dna_io_pdf (void) inline virtual
Definition at line 76 of file dnaiopdf.hpp.
{};
Member Function Documentation
operator=()
dna_io_pdf & dynadjust::iostreams::dna_io_pdf::operator= (const dna_io_pdf & rhs)
References dna_io_pdf().
form_pdf_action_command_string()
std::string dynadjust::iostreams::dna_io_pdf::form_pdf_action_command_string (const std::string & pdf_filename, const std::string & ddename, const std::string & action)
Definition at line 32 of file dnaiopdf.cpp.
{
    if (pdf_filename.empty())
        return "";
#if defined(_WIN32) || defined(__WIN32__)
    char viewer_filepath[256];
    FindExecutable(pdf_filename.c_str(), 0, viewer_filepath);
    std::string viewer(path(viewer_filepath).stem());
    if (boost::iequals(viewer, "AcroRd32") || boost::iequals(viewer, "Acrobat"))
    {
        std::stringstream ss;
        ss << "\"" << viewer_filepath << "\" " << pdf_filename;
        return ss.str();
    }
#elif defined(__linux) || defined(sun) || defined(__unix__) || defined(__APPLE__)
#endif
    return "";
}
form_pdf_close_string()
std::string dynadjust::iostreams::dna_io_pdf::form_pdf_close_string (const std::string & pdf_filename, const std::string & ddename)
Definition at line 60 of file dnaiopdf.cpp.
{
    //return form_pdf_action_command_string(pdf_filename, ddename, "DocClose");
    return "";
}
form_pdf_open_string()
std::string dynadjust::iostreams::dna_io_pdf::form_pdf_open_string (const std::string & pdf_filename, const std::string & ddename)
Definition at line 66 of file dnaiopdf.cpp.
{
    // return form_pdf_action_command_string(pdf_filename, ddename, "DocOpen");
    return "";
}
The documentation for this class was generated from the following files:
include/io/dnaiopdf.hpp
include/io/dnaiopdf.cpp