DynAdjust: DnaXmlFormat_pimpl Class Reference
DnaXmlFormat_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
DnaXmlFormat_pimpl (std::ifstream *is, PUINT32 clusterID, const std::string &referenceframe, const std::string &epoch, bool firstFile, bool userspecifiedreferenceframe, bool userspecifiedepoch, bool overridereferenceframe)
virtual void pre ()
virtual void DnaStation ()
virtual void DnaMeasurement ()
virtual void type ()
virtual void referenceframe ()
virtual void epoch ()
virtual void post_DnaXmlFormat (vdnaStnPtr *vStations, vdnaMsrPtr *vMeasurements)
bool filespecifiedreferenceframe ()
bool filespecifiedepoch ()
std::string DnaXmlParseMessage ()
UINT32 NumStationsRead () const
UINT32 NumMeasurementsRead () const
UINT32 CurrentClusterID () const
std::string FileEpsg () const
std::string FileEpoch () const
Public Member Functions inherited from DnaXmlFormat_pskel
virtual void post_DnaXmlFormat ()
void DnaStation_parser (::DnaStation_pskel &)
void DnaMeasurement_parser (::DnaMeasurement_pskel &)
void type_parser (::type_pskel &)
void referenceframe_parser (::referenceframe_pskel &)
void epoch_parser (::epoch_pskel &)
void parsers (::DnaStation_pskel &, ::DnaMeasurement_pskel &, ::type_pskel &, ::referenceframe_pskel &, ::epoch_pskel &)
DnaXmlFormat_pskel ()
Protected Attributes
std::string _parse_msg
Protected Attributes inherited from DnaXmlFormat_pskel
::DnaStation_pskel * DnaStation_parser_
::DnaMeasurement_pskel * DnaMeasurement_parser_
::type_pskel * type_parser_
::referenceframe_pskel * referenceframe_parser_
::epoch_pskel * epoch_parser_
vdnaStnPtr * _pStns
vdnaMsrPtr * _pMsrs
UINT32 _clusterID
UINT32 _measurement_count
UINT32 _station_count
std::string _referenceframe
std::string _epoch
std::string _fileEpsg
std::string _fileEpoch
bool _firstFile
bool _userspecifiedreferenceframe
bool _filespecifiedreferenceframe
bool _overridereferenceframe
bool _userspecifiedepoch
bool _filespecifiedepoch
Private Attributes
std::ifstream * is_
Additional Inherited Members
Protected Member Functions inherited from DnaXmlFormat_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
virtual bool _attribute_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
vdnaStnPtr & StationList ()
vdnaMsrPtr & MeasurementList ()
Detailed Description
Definition at line 119 of file dnaparser_pimpl.hxx.
Constructor & Destructor Documentation
DnaXmlFormat_pimpl()
DnaXmlFormat_pimpl::DnaXmlFormat_pimpl (std::ifstream * is, PUINT32 clusterID, const std::string & referenceframe, const std::string & epoch, bool firstFile, bool userspecifiedreferenceframe, bool userspecifiedepoch, bool overridereferenceframe)
Definition at line 929 of file dnaparser_pimpl.cxx.
{
    // capture pointer to file stream
    is_ = is;
    // capture global cluster ID to permit sequential numbering over several input files
    _clusterID = *clusterID;
    // capture default reference frame and epoch
    _referenceframe = referenceframe;
    _epoch = epoch;
    // capture first file flag
    _firstFile = firstFile;
    // Has the user supplied a reference frame and should this be used to override all?
    _userspecifiedreferenceframe = userspecifiedreferenceframe;
    _filespecifiedreferenceframe = false;
    _filespecifiedepoch = false;
    _overridereferenceframe = overridereferenceframe;
    _userspecifiedepoch = userspecifiedepoch;
}
References DnaXmlFormat_pskel::_clusterID, DnaXmlFormat_pskel::_epoch, DnaXmlFormat_pskel::_filespecifiedepoch, DnaXmlFormat_pskel::_filespecifiedreferenceframe, DnaXmlFormat_pskel::_firstFile, DnaXmlFormat_pskel::_overridereferenceframe, DnaXmlFormat_pskel::_referenceframe, DnaXmlFormat_pskel::_userspecifiedepoch, DnaXmlFormat_pskel::_userspecifiedreferenceframe, epoch(), is_, and referenceframe().
Member Function Documentation
pre()
void DnaXmlFormat_pimpl::pre () virtual
Definition at line 955 of file dnaparser_pimpl.cxx.
{
    _pStns = new vdnaStnPtr ;
    _pMsrs = new vdnaMsrPtr ;
    g_parsemsr_tally.initialise();
    g_parsestn_tally.initialise();
    _station_count = 0;
    _measurement_count = 0;
}
References DnaXmlFormat_pskel::_measurement_count, DnaXmlFormat_pskel::_pMsrs, DnaXmlFormat_pskel::_pStns, DnaXmlFormat_pskel::_station_count, g_parsemsr_tally, and g_parsestn_tally.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
DnaStation()
void DnaXmlFormat_pimpl::DnaStation () virtual
Reimplemented from DnaXmlFormat_pskel.
Definition at line 966 of file dnaparser_pimpl.cxx.
{
    _station_count++;
}
References DnaXmlFormat_pskel::_station_count.
DnaMeasurement()
void DnaXmlFormat_pimpl::DnaMeasurement () virtual
Reimplemented from DnaXmlFormat_pskel.
Definition at line 971 of file dnaparser_pimpl.cxx.
{
}
type()
void DnaXmlFormat_pimpl::type () virtual
Reimplemented from DnaXmlFormat_pskel.
Definition at line 975 of file dnaparser_pimpl.cxx.
{
}
referenceframe()
void DnaXmlFormat_pimpl::referenceframe () virtual
Reimplemented from DnaXmlFormat_pskel.
Definition at line 979 of file dnaparser_pimpl.cxx.
{
}
Referenced by DnaXmlFormat_pimpl().
epoch()
void DnaXmlFormat_pimpl::epoch () virtual
Reimplemented from DnaXmlFormat_pskel.
Definition at line 983 of file dnaparser_pimpl.cxx.
{
}
Referenced by DnaXmlFormat_pimpl().
post_DnaXmlFormat()
void DnaXmlFormat_pimpl::post_DnaXmlFormat (vdnaStnPtr * vStations, vdnaMsrPtr * vMeasurements) virtual
Definition at line 987 of file dnaparser_pimpl.cxx.
{
    std::ostringstream ss("");
    if (_station_count > 0)
    {
        ss << "Loaded " << _station_count << " stations";
        _parse_msg = ss.str();
        (*vStations) = (vdnaStnPtr) (*(_pStns));
    }
    if (_measurement_count > 0)
    {
        ss << "Loaded " << _measurement_count << " measurements";
        _parse_msg = ss.str();
        (*vMeasurements) = (vdnaMsrPtr) (*(_pMsrs));
    }
}
References DnaXmlFormat_pskel::_measurement_count, _parse_msg, DnaXmlFormat_pskel::_pMsrs, DnaXmlFormat_pskel::_pStns, and DnaXmlFormat_pskel::_station_count.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
filespecifiedreferenceframe()
bool DnaXmlFormat_pimpl::filespecifiedreferenceframe () inline
Definition at line 134 of file dnaparser_pimpl.hxx.
{ return _filespecifiedreferenceframe; }
References DnaXmlFormat_pskel::_filespecifiedreferenceframe.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
filespecifiedepoch()
bool DnaXmlFormat_pimpl::filespecifiedepoch () inline
Definition at line 135 of file dnaparser_pimpl.hxx.
{ return _filespecifiedepoch; }
References DnaXmlFormat_pskel::_filespecifiedepoch.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
DnaXmlParseMessage()
std::string DnaXmlFormat_pimpl::DnaXmlParseMessage () inline
Definition at line 137 of file dnaparser_pimpl.hxx.
{ return _parse_msg; }
References _parse_msg.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
NumStationsRead()
UINT32 DnaXmlFormat_pimpl::NumStationsRead () const inline
Definition at line 139 of file dnaparser_pimpl.hxx.
{ return _station_count; }
References DnaXmlFormat_pskel::_station_count.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
NumMeasurementsRead()
UINT32 DnaXmlFormat_pimpl::NumMeasurementsRead () const inline
Definition at line 140 of file dnaparser_pimpl.hxx.
{ return _measurement_count; }
References DnaXmlFormat_pskel::_measurement_count.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
CurrentClusterID()
UINT32 DnaXmlFormat_pimpl::CurrentClusterID () const inline
Definition at line 141 of file dnaparser_pimpl.hxx.
{ return _clusterID; }
References DnaXmlFormat_pskel::_clusterID.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
FileEpsg()
std::string DnaXmlFormat_pimpl::FileEpsg () const inline
Definition at line 143 of file dnaparser_pimpl.hxx.
{ return _fileEpsg; }
References DnaXmlFormat_pskel::_fileEpsg.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
FileEpoch()
std::string DnaXmlFormat_pimpl::FileEpoch () const inline
Definition at line 144 of file dnaparser_pimpl.hxx.
{ return _fileEpoch; }
References DnaXmlFormat_pskel::_fileEpoch.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
Member Data Documentation
_parse_msg
std::string DnaXmlFormat_pimpl::_parse_msg protected
Definition at line 147 of file dnaparser_pimpl.hxx.
Referenced by DnaXmlParseMessage(), and post_DnaXmlFormat().
is_
std::ifstream* DnaXmlFormat_pimpl::is_ private
Definition at line 150 of file dnaparser_pimpl.hxx.
Referenced by DnaXmlFormat_pimpl().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx