DynAdjust: StationNameIDCompareName Class Reference
StationNameIDCompareName Class Reference
#include <dnatemplatestnmsrfuncs.hpp>
Public Member Functions
bool operator() (const string_uint32_pair &lhs, const string_uint32_pair &rhs) const
bool operator() (const string_uint32_pair &lhs, const string_uint32_pair::first_type &k) const
bool operator() (const string_uint32_pair::first_type &k, const string_uint32_pair &rhs) const
Private Member Functions
bool keyLess (const string_uint32_pair::first_type &k1, const string_uint32_pair::first_type &k2) const
Detailed Description
Definition at line 923 of file dnatemplatestnmsrfuncs.hpp.
Member Function Documentation
operator()() [1/3]
bool StationNameIDCompareName::operator() (const string_uint32_pair & lhs, const string_uint32_pair & rhs) const inline
Definition at line 926 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(lhs.first, rhs.first);
    }
References keyLess().
operator()() [2/3]
bool StationNameIDCompareName::operator() (const string_uint32_pair & lhs, const string_uint32_pair::first_type & k) const inline
Definition at line 930 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(lhs.first, k);
    }
References keyLess().
operator()() [3/3]
bool StationNameIDCompareName::operator() (const string_uint32_pair::first_type & k, const string_uint32_pair & rhs) const inline
Definition at line 934 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(k, rhs.first);
    }
References keyLess().
keyLess()
bool StationNameIDCompareName::keyLess (const string_uint32_pair::first_type & k1, const string_uint32_pair::first_type & k2) const inline private
Definition at line 939 of file dnatemplatestnmsrfuncs.hpp.
{
        return k1 < k2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this class was generated from the following file:
include/functions/dnatemplatestnmsrfuncs.hpp