DynAdjust: dynadjust::iostreams::CompareTypeBStationID< T1, T2 > Class Template Reference
dynadjust::iostreams::CompareTypeBStationID< T1, T2 > Class Template Reference
#include <dnaiotbu.hpp>
Public Member Functions
bool operator() (const T2 &lhs, const T2 &rhs) const
bool operator() (const T2 &lhs, const T1 &rhs)
bool operator() (const T1 &lhs, const T2 &rhs)
Private Member Functions
bool keyLess (const T1 &s1, const T1 &s2) const
Detailed Description
template<class T1 = UINT32, class T2 = type_b_uncertainty>
class dynadjust::iostreams::CompareTypeBStationID< T1, T2 >
Definition at line 85 of file dnaiotbu.hpp.
Member Function Documentation
operator()() [1/3]
template<class T1 = UINT32, class T2 = type_b_uncertainty> bool dynadjust::iostreams::CompareTypeBStationID< T1, T2 >::operator() (const T2 & lhs, const T2 & rhs) const inline
Definition at line 88 of file dnaiotbu.hpp.
{
        return keyLess(lhs.second, rhs.second);
    }
References keyLess().
operator()() [2/3]
template<class T1 = UINT32, class T2 = type_b_uncertainty> bool dynadjust::iostreams::CompareTypeBStationID< T1, T2 >::operator() (const T2 & lhs, const T1 & rhs) inline
Definition at line 91 of file dnaiotbu.hpp.
{
        return keyLess(lhs.station_id, rhs);
    }
References keyLess().
operator()() [3/3]
template<class T1 = UINT32, class T2 = type_b_uncertainty> bool dynadjust::iostreams::CompareTypeBStationID< T1, T2 >::operator() (const T1 & lhs, const T2 & rhs) inline
Definition at line 94 of file dnaiotbu.hpp.
{
        return keyLess(lhs, rhs.station_id);
    }
References keyLess().
keyLess()
template<class T1 = UINT32, class T2 = type_b_uncertainty> bool dynadjust::iostreams::CompareTypeBStationID< T1, T2 >::keyLess (const T1 & s1, const T1 & s2) const inline private
Definition at line 98 of file dnaiotbu.hpp.
{
        return s1 < s2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this class was generated from the following file:
include/io/dnaiotbu.hpp