DynAdjust: CRegProc Class Reference
CRegProc Class Reference
#include <RegProc.h>
Public Member Functions
CRegProc ()
CString GetPreferencesFolder ()
bool PreferencesFileExists ()
bool CreatePreferencesFile ()
bool PreferencesFolderExists ()
bool PreferencesSubFolderExists (const char *const)
bool CreatePreferencesFolder (char *)
void InitialiseSettings (T_user *)
bool GetTemporaryFileSettings (T_user *)
void SaveTemporaryFileSettings (T_user *)
void SaveTFDword (FILE *, int)
int GetTFDword (FILE *)
void SaveTFString (FILE *, char *, int)
CString GetTFString (FILE *, int)
Detailed Description
Definition at line 20 of file RegProc.h.
Constructor & Destructor Documentation
CRegProc()
CRegProc::CRegProc ()
Definition at line 16 of file RegProc.cpp.
{
}
Member Function Documentation
GetPreferencesFolder()
CString CRegProc::GetPreferencesFolder ()
Definition at line 132 of file RegProc.cpp.
{
    TCHAR szPath[MAX_PATH];
    if (!SUCCEEDED(SHGetFolderPath(NULL, CSIDL_COMMON_APPDATA, NULL, 0, szPath)))
        return "";
    return (CString)szPath;
}
Referenced by CdnageoidintApp::InitInstance().
PreferencesFileExists()
bool CRegProc::PreferencesFileExists ()
Definition at line 76 of file RegProc.cpp.
{
    TCHAR szPath[MAX_PATH];
    if (!SUCCEEDED(SHGetFolderPath(NULL, CSIDL_COMMON_APPDATA, NULL, 0, szPath)))
        return false;
    TCHAR szTempFileName[MAX_PATH];
    // Generate a temporary file name within the application folder (product-specific path).
    sprintf(szTempFileName, "%s\\%s", szPath, preferencesFile);
    long hFile;
    CFileProc fp;
    if (fp.Exists(szTempFileName, &hFile))
        return true;
    else
        return false;
}
References CFileProc::Exists(), and preferencesFile.
Referenced by CdnageoidintApp::InitInstance().
CreatePreferencesFile()
bool CRegProc::CreatePreferencesFile ()
Definition at line 20 of file RegProc.cpp.
{
    TCHAR szPath[MAX_PATH];
    // Get path for each computer, non-user specific and non-roaming data.
    if (SUCCEEDED(SHGetFolderPath(NULL, CSIDL_COMMON_APPDATA, NULL, 0, szPath)))
    {
        TCHAR szTempFileName[MAX_PATH];
        if (!PreferencesFolderExists())
            CreatePreferencesFolder(szPath);
        // Generate a temporary file name within the application folder (product-specific path).
        sprintf(szTempFileName, "%s\\%s", szPath, preferencesFile);
        HANDLE hFile = NULL;
        // Open the file.
        if ((hFile = CreateFile(szTempFileName,
                                    GENERIC_WRITE,
                                    0,
                                    NULL,
                                    CREATE_ALWAYS,
                                    FILE_ATTRIBUTE_NORMAL,
                                    NULL)) != INVALID_HANDLE_VALUE)
        {
            // Write temporary data (code omitted).
            CloseHandle(hFile);
            return true;
        }
    }
    return false;
}
References CreatePreferencesFolder(), preferencesFile, and PreferencesFolderExists().
Referenced by CdnageoidintApp::InitInstance().
PreferencesFolderExists()
bool CRegProc::PreferencesFolderExists ()
Definition at line 97 of file RegProc.cpp.
{
    return PreferencesSubFolderExists(preferencesFolder);
}
References preferencesFolder, and PreferencesSubFolderExists().
Referenced by CreatePreferencesFile().
PreferencesSubFolderExists()
bool CRegProc::PreferencesSubFolderExists (const char * const preferencesSubFolder)
Definition at line 102 of file RegProc.cpp.
{
    TCHAR szPath[MAX_PATH];
    if (!SUCCEEDED(SHGetFolderPath(NULL, CSIDL_COMMON_APPDATA, NULL, 0, szPath)))
        return false;
    TCHAR szTempFileName[MAX_PATH];
    // Generate a temporary file name within the application folder (product-specific path).
    sprintf(szTempFileName, "%s\\%s", szPath, preferencesSubFolder);
    HANDLE hFile = NULL;
    // Open the folder.
    if ((hFile = CreateFile(
                    szTempFileName,
                    GENERIC_READ,
                    FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,
                    NULL,
                    OPEN_EXISTING,
                    FILE_FLAG_BACKUP_SEMANTICS,
                    NULL)) != INVALID_HANDLE_VALUE)
    {
        // Write temporary data (code omitted).
        CloseHandle(hFile);
        return true;
    }
    return false;
}
Referenced by CreatePreferencesFolder(), and PreferencesFolderExists().
CreatePreferencesFolder()
bool CRegProc::CreatePreferencesFolder (char * szPath)
Definition at line 54 of file RegProc.cpp.
{
    TCHAR szTempFileName[MAX_PATH];
    if (!PreferencesSubFolderExists(icsmFolder))
    {
        sprintf(szTempFileName, "%s\\%s", szPath, icsmFolder);
        if (!CreateDirectory(szTempFileName, NULL))
            return false;
    }
    if (!PreferencesSubFolderExists(preferencesFolder))
    {
        sprintf(szTempFileName, "%s\\%s", szPath, preferencesFolder);
        if (!CreateDirectory(szTempFileName, NULL))
            return false;
    }
    return true;
}
References icsmFolder, preferencesFolder, and PreferencesSubFolderExists().
Referenced by CreatePreferencesFile().
InitialiseSettings()
void CRegProc::InitialiseSettings (T_user * theUser)
Definition at line 189 of file RegProc.cpp.
{
    // Distortion grid type
    theUser->GridType = "gsb";
    // Grid file path
    theUser->GridFile = noGridSpecified;
    // Log file path
    TCHAR szPath[MAX_PATH];
    if (SUCCEEDED(SHGetFolderPath(NULL, CSIDL_COMMON_APPDATA, NULL, 0, szPath)))
        theUser->LogFile.Format("%s\\%sNterpolate.log", szPath, preferencesFolder);
    else
        theUser->LogFile = "";
    SaveTemporaryFileSettings(theUser);
}
References T_user::GridFile, T_user::GridType, T_user::LogFile, noGridSpecified, preferencesFolder, and SaveTemporaryFileSettings().
Referenced by CdnageoidintApp::InitInstance().
GetTemporaryFileSettings()
bool CRegProc::GetTemporaryFileSettings (T_user * theUser)
Definition at line 141 of file RegProc.cpp.
{
    TCHAR szPath[MAX_PATH];
    if (!SUCCEEDED(SHGetFolderPath(NULL, CSIDL_COMMON_APPDATA, NULL, 0, szPath)))
        return false;
    CString strTmp;
    long hfile;
    CFileProc fp;
    // Open the preferences file from the application folder (product-specific path).
    FILE* fin;
    TCHAR szTempFileName[MAX_PATH];
    sprintf(szTempFileName, "%s\\%s", szPath, preferencesFile);
    if (fopen_s(&fin, szTempFileName, "rb") != 0)
        return false;
    // grid file type
    theUser->GridType = GetTFString(fin, 4);
    // ---------------------------------------------------------
    // Grid file path
    // create default
    theUser->GridFile = noGridSpecified;
    // get file path and save if file exists
    strTmp = GetTFString(fin, MAX_PATH);
    if (fp.Exists(strTmp, &hfile))
        theUser->GridFile = strTmp;
    // ---------------------------------------------------------
    // ---------------------------------------------------------
    // Log file path (saved to preferences folder)
    // create default
    theUser->LogFile.Format("%s\\%sNterpolate.log", szPath, preferencesFolder);
    // get file path and save if file exists
    strTmp = GetTFString(fin, MAX_PATH);
    if (fp.Exists(strTmp, &hfile))
        theUser->LogFile = strTmp;
    // ---------------------------------------------------------
    fclose(fin);
    return true;
}
References CFileProc::Exists(), GetTFString(), T_user::GridFile, T_user::GridType, T_user::LogFile, noGridSpecified, preferencesFile, and preferencesFolder.
Referenced by CdnageoidintApp::InitInstance().
SaveTemporaryFileSettings()
void CRegProc::SaveTemporaryFileSettings (T_user * theUser)
Definition at line 208 of file RegProc.cpp.
{
    TCHAR szPath[MAX_PATH];
    if (!SUCCEEDED(SHGetFolderPath(NULL, CSIDL_COMMON_APPDATA, NULL, 0, szPath)))
        return;
    FILE* fout;
    TCHAR szTempFileName[MAX_PATH];
    // Generate a temporary file name within the application folder (product-specific path).
    sprintf(szTempFileName, "%s\\%s", szPath, preferencesFile);
    fopen_s(&fout, szTempFileName, "wb");
    // Distortion grid type
    SaveTFString(fout, (char*)((LPCTSTR)theUser->GridType), 4);
    // Grid file
    SaveTFString(fout, (char*)((LPCTSTR)theUser->GridFile), MAX_PATH);
    // Log file
    SaveTFString(fout, (char*)((LPCTSTR)theUser->LogFile), MAX_PATH);
    fclose(fout);
}
References T_user::GridFile, T_user::GridType, T_user::LogFile, preferencesFile, and SaveTFString().
Referenced by InitialiseSettings(), and CdnageoidintApp::InitInstance().
SaveTFDword()
void CRegProc::SaveTFDword (FILE * fout, int i)
Definition at line 235 of file RegProc.cpp.
{
    fwrite(&i, sizeof(int), 1, fout);
}
GetTFDword()
int CRegProc::GetTFDword (FILE * fin)
Definition at line 240 of file RegProc.cpp.
{
    int i;
    fread(&i, sizeof(int), 1, fin);
    return i;
}
SaveTFString()
void CRegProc::SaveTFString (FILE * fout, char * s, int iLen)
Definition at line 247 of file RegProc.cpp.
{
    fwrite(s, sizeof(char), iLen, fout);
}
Referenced by SaveTemporaryFileSettings().
GetTFString()
CString CRegProc::GetTFString (FILE * fin, int iLen)
Definition at line 252 of file RegProc.cpp.
{
    char* str = new char[iLen+1];
    memset(str, '\0', iLen);
    fread(&(*str), sizeof(char), iLen, fin);
    CString s = str;
    delete []str;
    return s;
}
Referenced by GetTemporaryFileSettings().
The documentation for this class was generated from the following files:
dynadjust/dnageoidint/RegProc.h
dynadjust/dnageoidint/RegProc.cpp