DynAdjust: GPSBaseline_pskel Class Reference
GPSBaseline_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void X (const ::std::string &)
virtual void Y (const ::std::string &)
virtual void Z (const ::std::string &)
virtual void MeasurementDBID (const ::std::string &)
virtual void SigmaXX (const ::std::string &)
virtual void SigmaXY (const ::std::string &)
virtual void SigmaXZ (const ::std::string &)
virtual void SigmaYY (const ::std::string &)
virtual void SigmaYZ (const ::std::string &)
virtual void SigmaZZ (const ::std::string &)
virtual void GPSCovariance ()
virtual void post_GPSBaseline ()
void X_parser (::xml_schema::string_pskel &)
void Y_parser (::xml_schema::string_pskel &)
void Z_parser (::xml_schema::string_pskel &)
void MeasurementDBID_parser (::xml_schema::string_pskel &)
void SigmaXX_parser (::xml_schema::string_pskel &)
void SigmaXY_parser (::xml_schema::string_pskel &)
void SigmaXZ_parser (::xml_schema::string_pskel &)
void SigmaYY_parser (::xml_schema::string_pskel &)
void SigmaYZ_parser (::xml_schema::string_pskel &)
void SigmaZZ_parser (::xml_schema::string_pskel &)
void GPSCovariance_parser (::GPSCovariance_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::GPSCovariance_pskel &)
GPSBaseline_pskel ()
void InitparentGpsBaselineCluster (dnaMsrPtr pGpsBaselineCluster)
void InitparentMsrCounter (PUINT32 pMsrCounter)
Protected Member Functions
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * X_parser_
::xml_schema::string_pskel * Y_parser_
::xml_schema::string_pskel * Z_parser_
::xml_schema::string_pskel * MeasurementDBID_parser_
::xml_schema::string_pskel * SigmaXX_parser_
::xml_schema::string_pskel * SigmaXY_parser_
::xml_schema::string_pskel * SigmaXZ_parser_
::xml_schema::string_pskel * SigmaYY_parser_
::xml_schema::string_pskel * SigmaYZ_parser_
::xml_schema::string_pskel * SigmaZZ_parser_
::GPSCovariance_pskel * GPSCovariance_parser_
dnaMsrPtr _dnaGpsBaseline
dnaMsrPtr _parent_dnaGpsBaselineCluster
PUINT32 _pMeasurementCount
Detailed Description
Definition at line 861 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
GPSBaseline_pskel()
GPSBaseline_pskel::GPSBaseline_pskel ()
Definition at line 573 of file dnaparser_pskel.cxx.
    : X_parser_ (0),
    Y_parser_ (0),
    Z_parser_ (0),
    MeasurementDBID_parser_ (0),
    SigmaXX_parser_ (0),
    SigmaXY_parser_ (0),
    SigmaXZ_parser_ (0),
    SigmaYY_parser_ (0),
    SigmaYZ_parser_ (0),
    SigmaZZ_parser_ (0),
    GPSCovariance_parser_ (0)
{
}
References GPSCovariance_parser_, MeasurementDBID_parser_, SigmaXX_parser_, SigmaXY_parser_, SigmaXZ_parser_, SigmaYY_parser_, SigmaYZ_parser_, SigmaZZ_parser_, X_parser_, Y_parser_, and Z_parser_.
Member Function Documentation
X()
void GPSBaseline_pskel::X (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2185 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Y()
void GPSBaseline_pskel::Y (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2189 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Z()
void GPSBaseline_pskel::Z (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2193 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
MeasurementDBID()
void GPSBaseline_pskel::MeasurementDBID (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2197 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaXX()
void GPSBaseline_pskel::SigmaXX (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2201 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaXY()
void GPSBaseline_pskel::SigmaXY (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2205 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaXZ()
void GPSBaseline_pskel::SigmaXZ (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2209 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaYY()
void GPSBaseline_pskel::SigmaYY (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2213 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaYZ()
void GPSBaseline_pskel::SigmaYZ (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2217 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaZZ()
void GPSBaseline_pskel::SigmaZZ (const ::std::string &) virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2221 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
GPSCovariance()
void GPSBaseline_pskel::GPSCovariance () virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2225 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
post_GPSBaseline()
void GPSBaseline_pskel::post_GPSBaseline () virtual
Reimplemented in GPSBaseline_pimpl.
Definition at line 2229 of file dnaparser_pskel.cxx.
{
}
X_parser()
void GPSBaseline_pskel::X_parser (::xml_schema::string_pskel & p)
Definition at line 492 of file dnaparser_pskel.cxx.
{
    this->X_parser_ = &p;
}
References X_parser_.
Y_parser()
void GPSBaseline_pskel::Y_parser (::xml_schema::string_pskel & p)
Definition at line 497 of file dnaparser_pskel.cxx.
{
    this->Y_parser_ = &p;
}
References Y_parser_.
Z_parser()
void GPSBaseline_pskel::Z_parser (::xml_schema::string_pskel & p)
Definition at line 502 of file dnaparser_pskel.cxx.
{
    this->Z_parser_ = &p;
}
References Z_parser_.
MeasurementDBID_parser()
void GPSBaseline_pskel::MeasurementDBID_parser (::xml_schema::string_pskel & p)
Definition at line 507 of file dnaparser_pskel.cxx.
{
    this->MeasurementDBID_parser_ = &p;
}
References MeasurementDBID_parser_.
SigmaXX_parser()
void GPSBaseline_pskel::SigmaXX_parser (::xml_schema::string_pskel & p)
Definition at line 512 of file dnaparser_pskel.cxx.
{
    this->SigmaXX_parser_ = &p;
}
References SigmaXX_parser_.
SigmaXY_parser()
void GPSBaseline_pskel::SigmaXY_parser (::xml_schema::string_pskel & p)
Definition at line 517 of file dnaparser_pskel.cxx.
{
    this->SigmaXY_parser_ = &p;
}
References SigmaXY_parser_.
SigmaXZ_parser()
void GPSBaseline_pskel::SigmaXZ_parser (::xml_schema::string_pskel & p)
Definition at line 522 of file dnaparser_pskel.cxx.
{
    this->SigmaXZ_parser_ = &p;
}
References SigmaXZ_parser_.
SigmaYY_parser()
void GPSBaseline_pskel::SigmaYY_parser (::xml_schema::string_pskel & p)
Definition at line 527 of file dnaparser_pskel.cxx.
{
    this->SigmaYY_parser_ = &p;
}
References SigmaYY_parser_.
SigmaYZ_parser()
void GPSBaseline_pskel::SigmaYZ_parser (::xml_schema::string_pskel & p)
Definition at line 532 of file dnaparser_pskel.cxx.
{
    this->SigmaYZ_parser_ = &p;
}
References SigmaYZ_parser_.
SigmaZZ_parser()
void GPSBaseline_pskel::SigmaZZ_parser (::xml_schema::string_pskel & p)
Definition at line 537 of file dnaparser_pskel.cxx.
{
    this->SigmaZZ_parser_ = &p;
}
References SigmaZZ_parser_.
GPSCovariance_parser()
void GPSBaseline_pskel::GPSCovariance_parser (::GPSCovariance_pskel & p)
Definition at line 542 of file dnaparser_pskel.cxx.
{
    this->GPSCovariance_parser_ = &p;
}
References GPSCovariance_parser_.
parsers()
void GPSBaseline_pskel::parsers (::xml_schema::string_pskel & X, ::xml_schema::string_pskel & Y, ::xml_schema::string_pskel & Z, ::xml_schema::string_pskel & MeasurementDBID, ::xml_schema::string_pskel & SigmaXX, ::xml_schema::string_pskel & SigmaXY, ::xml_schema::string_pskel & SigmaXZ, ::xml_schema::string_pskel & SigmaYY, ::xml_schema::string_pskel & SigmaYZ, ::xml_schema::string_pskel & SigmaZZ, ::GPSCovariance_pskel & GPSCovariance)
Definition at line 547 of file dnaparser_pskel.cxx.
{
    this->X_parser_ = &X;
    this->Y_parser_ = &Y;
    this->Z_parser_ = &Z;
    this->MeasurementDBID_parser_ = &MeasurementDBID;
    this->SigmaXX_parser_ = &SigmaXX;
    this->SigmaXY_parser_ = &SigmaXY;
    this->SigmaXZ_parser_ = &SigmaXZ;
    this->SigmaYY_parser_ = &SigmaYY;
    this->SigmaYZ_parser_ = &SigmaYZ;
    this->SigmaZZ_parser_ = &SigmaZZ;
    this->GPSCovariance_parser_ = &GPSCovariance;
}
References GPSCovariance(), GPSCovariance_parser_, MeasurementDBID(), MeasurementDBID_parser_, SigmaXX(), SigmaXX_parser_, SigmaXY(), SigmaXY_parser_, SigmaXZ(), SigmaXZ_parser_, SigmaYY(), SigmaYY_parser_, SigmaYZ(), SigmaYZ_parser_, SigmaZZ(), SigmaZZ_parser_, X(), X_parser_, Y(), Y_parser_, Z(), and Z_parser_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
InitparentGpsBaselineCluster()
void GPSBaseline_pskel::InitparentGpsBaselineCluster (dnaMsrPtr pGpsBaselineCluster) inline
Definition at line 914 of file dnaparser_pskel.hxx.
{ _parent_dnaGpsBaselineCluster = pGpsBaselineCluster; }
References _parent_dnaGpsBaselineCluster.
InitparentMsrCounter()
void GPSBaseline_pskel::InitparentMsrCounter (PUINT32 pMsrCounter) inline
Definition at line 915 of file dnaparser_pskel.hxx.
{   _pMeasurementCount = pMsrCounter; }
References _pMeasurementCount.
_start_element_impl()
bool GPSBaseline_pskel::_start_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string * t) protected virtual
Definition at line 2233 of file dnaparser_pskel.cxx.
{
    XSD_UNUSED (t);
    if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
        return true;
    if (n == "X" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->X_parser_;
        if (this->X_parser_)
            this->X_parser_->pre ();
        return true;
    }
    if (n == "Y" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Y_parser_;
        if (this->Y_parser_)
            this->Y_parser_->pre ();
        return true;
    }
    if (n == "Z" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Z_parser_;
        if (this->Z_parser_)
            this->Z_parser_->pre ();
        return true;
    }
    if (n == "MeasurementID" && ns.empty())
    {
        this->::xml_schema::complex_content::context_.top().parser_ = this->MeasurementDBID_parser_;
        if (this->MeasurementDBID_parser_)
            this->MeasurementDBID_parser_->pre();
        return true;
    }
    if (n == "SigmaXX" && ns.empty())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaXX_parser_;
        if (this->SigmaXX_parser_)
            this->SigmaXX_parser_->pre ();
        return true;
    }
    if (n == "SigmaXY" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaXY_parser_;
        if (this->SigmaXY_parser_)
            this->SigmaXY_parser_->pre ();
        return true;
    }
    if (n == "SigmaXZ" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaXZ_parser_;
        if (this->SigmaXZ_parser_)
            this->SigmaXZ_parser_->pre ();
        return true;
    }
    if (n == "SigmaYY" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaYY_parser_;
        if (this->SigmaYY_parser_)
            this->SigmaYY_parser_->pre ();
        return true;
    }
    if (n == "SigmaYZ" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaYZ_parser_;
        if (this->SigmaYZ_parser_)
            this->SigmaYZ_parser_->pre ();
        return true;
    }
    if (n == "SigmaZZ" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaZZ_parser_;
        if (this->SigmaZZ_parser_)
            this->SigmaZZ_parser_->pre ();
        return true;
    }
    if (n == "GPSCovariance" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->GPSCovariance_parser_;
        if (this->GPSCovariance_parser_)
        {
            this->GPSCovariance_parser_->InitparentGpsBaseline(_dnaGpsBaseline);
            this->GPSCovariance_parser_->pre ();
        }
        return true;
    }
    return false;
}
References _dnaGpsBaseline, GPSCovariance_parser_, MeasurementDBID_parser_, SigmaXX_parser_, SigmaXY_parser_, SigmaXZ_parser_, SigmaYY_parser_, SigmaYZ_parser_, SigmaZZ_parser_, X_parser_, Y_parser_, and Z_parser_.
_end_element_impl()
bool GPSBaseline_pskel::_end_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n) protected virtual
Definition at line 2358 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
        return true;
    if (n == "X" && ns.empty ())
    {
        if (this->X_parser_)
            this->X (this->X_parser_->post_string ());
        return true;
    }
    if (n == "Y" && ns.empty ())
    {
        if (this->Y_parser_)
            this->Y (this->Y_parser_->post_string ());
        return true;
    }
    if (n == "Z" && ns.empty ())
    {
        if (this->Z_parser_)
            this->Z (this->Z_parser_->post_string ());
        return true;
    }
    if (n == "MeasurementID" && ns.empty())
    {
        if (this->MeasurementDBID_parser_)
            this->MeasurementDBID (this->MeasurementDBID_parser_->post_string());
        return true;
    }
    if (n == "SigmaXX" && ns.empty())
    {
        if (this->SigmaXX_parser_)
            this->SigmaXX (this->SigmaXX_parser_->post_string ());
        return true;
    }
    if (n == "SigmaXY" && ns.empty ())
    {
        if (this->SigmaXY_parser_)
            this->SigmaXY (this->SigmaXY_parser_->post_string ());
        return true;
    }
    if (n == "SigmaXZ" && ns.empty ())
    {
        if (this->SigmaXZ_parser_)
            this->SigmaXZ (this->SigmaXZ_parser_->post_string ());
        return true;
    }
    if (n == "SigmaYY" && ns.empty ())
    {
        if (this->SigmaYY_parser_)
            this->SigmaYY (this->SigmaYY_parser_->post_string ());
        return true;
    }
    if (n == "SigmaYZ" && ns.empty ())
    {
        if (this->SigmaYZ_parser_)
            this->SigmaYZ (this->SigmaYZ_parser_->post_string ());
        return true;
    }
    if (n == "SigmaZZ" && ns.empty ())
    {
        if (this->SigmaZZ_parser_)
            this->SigmaZZ (this->SigmaZZ_parser_->post_string ());
        return true;
    }
    if (n == "GPSCovariance" && ns.empty ())
    {
        if (this->GPSCovariance_parser_)
        {
            this->GPSCovariance_parser_->post_GPSCovariance ();
            this->GPSCovariance ();
        }
        return true;
    }
    return false;
}
References GPSCovariance(), GPSCovariance_parser_, MeasurementDBID(), MeasurementDBID_parser_, SigmaXX(), SigmaXX_parser_, SigmaXY(), SigmaXY_parser_, SigmaXZ(), SigmaXZ_parser_, SigmaYY(), SigmaYY_parser_, SigmaYZ(), SigmaYZ_parser_, SigmaZZ(), SigmaZZ_parser_, X(), X_parser_, Y(), Y_parser_, Z(), and Z_parser_.
Member Data Documentation
X_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::X_parser_ protected
Definition at line 930 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and X_parser().
Y_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::Y_parser_ protected
Definition at line 931 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and Y_parser().
Z_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::Z_parser_ protected
Definition at line 932 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and Z_parser().
MeasurementDBID_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::MeasurementDBID_parser_ protected
Definition at line 933 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), MeasurementDBID_parser(), and parsers().
SigmaXX_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::SigmaXX_parser_ protected
Definition at line 934 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and SigmaXX_parser().
SigmaXY_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::SigmaXY_parser_ protected
Definition at line 935 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and SigmaXY_parser().
SigmaXZ_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::SigmaXZ_parser_ protected
Definition at line 936 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and SigmaXZ_parser().
SigmaYY_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::SigmaYY_parser_ protected
Definition at line 937 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and SigmaYY_parser().
SigmaYZ_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::SigmaYZ_parser_ protected
Definition at line 938 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and SigmaYZ_parser().
SigmaZZ_parser_
::xml_schema::string_pskel* GPSBaseline_pskel::SigmaZZ_parser_ protected
Definition at line 939 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), parsers(), and SigmaZZ_parser().
GPSCovariance_parser_
::GPSCovariance_pskel* GPSBaseline_pskel::GPSCovariance_parser_ protected
Definition at line 940 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), GPSBaseline_pskel(), GPSCovariance_parser(), and parsers().
_dnaGpsBaseline
dnaMsrPtr GPSBaseline_pskel::_dnaGpsBaseline protected
Definition at line 942 of file dnaparser_pskel.hxx.
Referenced by _start_element_impl(), GPSBaseline_pimpl::MeasurementDBID(), GPSBaseline_pimpl::post_GPSBaseline(), GPSBaseline_pimpl::pre(), GPSBaseline_pimpl::SigmaXX(), GPSBaseline_pimpl::SigmaXY(), GPSBaseline_pimpl::SigmaXZ(), GPSBaseline_pimpl::SigmaYY(), GPSBaseline_pimpl::SigmaYZ(), GPSBaseline_pimpl::SigmaZZ(), GPSBaseline_pimpl::X(), GPSBaseline_pimpl::Y(), and GPSBaseline_pimpl::Z().
_parent_dnaGpsBaselineCluster
dnaMsrPtr GPSBaseline_pskel::_parent_dnaGpsBaselineCluster protected
Definition at line 943 of file dnaparser_pskel.hxx.
Referenced by InitparentGpsBaselineCluster(), GPSBaseline_pimpl::post_GPSBaseline(), and GPSBaseline_pimpl::pre().
_pMeasurementCount
PUINT32 GPSBaseline_pskel::_pMeasurementCount protected
Definition at line 944 of file dnaparser_pskel.hxx.
Referenced by InitparentMsrCounter(), GPSBaseline_pimpl::X(), GPSBaseline_pimpl::Y(), and GPSBaseline_pimpl::Z().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx