DynAdjust: Clusterpoint_pskel Class Reference
Clusterpoint_pskel Class Reference
#include <dnaparser_pskel.hxx>
Public Member Functions
virtual void X (const ::std::string &)
virtual void Y (const ::std::string &)
virtual void Z (const ::std::string &)
virtual void MeasurementDBID (const ::std::string &)
virtual void SigmaXX (const ::std::string &)
virtual void SigmaXY (const ::std::string &)
virtual void SigmaXZ (const ::std::string &)
virtual void SigmaYY (const ::std::string &)
virtual void SigmaYZ (const ::std::string &)
virtual void SigmaZZ (const ::std::string &)
virtual void PointCovariance ()
virtual void post_Clusterpoint ()
void X_parser (::xml_schema::string_pskel &)
void Y_parser (::xml_schema::string_pskel &)
void Z_parser (::xml_schema::string_pskel &)
void MeasurementDBID_parser (::xml_schema::string_pskel &)
void SigmaXX_parser (::xml_schema::string_pskel &)
void SigmaXY_parser (::xml_schema::string_pskel &)
void SigmaXZ_parser (::xml_schema::string_pskel &)
void SigmaYY_parser (::xml_schema::string_pskel &)
void SigmaYZ_parser (::xml_schema::string_pskel &)
void SigmaZZ_parser (::xml_schema::string_pskel &)
void PointCovariance_parser (::PointCovariance_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::PointCovariance_pskel &)
Clusterpoint_pskel ()
void InitparentGpsPointCluster (dnaMsrPtr pGpsPointCluster)
void InitparentMsrCounter (PUINT32 pMsrCounter)
Protected Member Functions
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes
::xml_schema::string_pskel * X_parser_
::xml_schema::string_pskel * Y_parser_
::xml_schema::string_pskel * Z_parser_
::xml_schema::string_pskel * MeasurementDBID_parser_
::xml_schema::string_pskel * SigmaXX_parser_
::xml_schema::string_pskel * SigmaXY_parser_
::xml_schema::string_pskel * SigmaXZ_parser_
::xml_schema::string_pskel * SigmaYY_parser_
::xml_schema::string_pskel * SigmaYZ_parser_
::xml_schema::string_pskel * SigmaZZ_parser_
::PointCovariance_pskel * PointCovariance_parser_
dnaMsrPtr _dnaGpsPoint
dnaMsrPtr _parent_dnaGpsPointCluster
PUINT32 _pMeasurementCount
Detailed Description
Definition at line 302 of file dnaparser_pskel.hxx.
Constructor & Destructor Documentation
Clusterpoint_pskel()
Clusterpoint_pskel::Clusterpoint_pskel ()
Definition at line 129 of file dnaparser_pskel.cxx.
    : X_parser_ (0),
    Y_parser_ (0),
    Z_parser_ (0),
    MeasurementDBID_parser_ (0),
    SigmaXX_parser_ (0),
    SigmaXY_parser_ (0),
    SigmaXZ_parser_ (0),
    SigmaYY_parser_ (0),
    SigmaYZ_parser_ (0),
    SigmaZZ_parser_ (0),
    PointCovariance_parser_ (0)
{
}
References MeasurementDBID_parser_, PointCovariance_parser_, SigmaXX_parser_, SigmaXY_parser_, SigmaXZ_parser_, SigmaYY_parser_, SigmaYZ_parser_, SigmaZZ_parser_, X_parser_, Y_parser_, and Z_parser_.
Member Function Documentation
X()
void Clusterpoint_pskel::X (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 865 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Y()
void Clusterpoint_pskel::Y (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 869 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
Z()
void Clusterpoint_pskel::Z (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 873 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
MeasurementDBID()
void Clusterpoint_pskel::MeasurementDBID (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 877 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaXX()
void Clusterpoint_pskel::SigmaXX (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 881 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaXY()
void Clusterpoint_pskel::SigmaXY (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 885 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaXZ()
void Clusterpoint_pskel::SigmaXZ (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 889 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaYY()
void Clusterpoint_pskel::SigmaYY (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 893 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaYZ()
void Clusterpoint_pskel::SigmaYZ (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 897 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
SigmaZZ()
void Clusterpoint_pskel::SigmaZZ (const ::std::string &) virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 901 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
PointCovariance()
void Clusterpoint_pskel::PointCovariance () virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 905 of file dnaparser_pskel.cxx.
{
}
Referenced by _end_element_impl(), and parsers().
post_Clusterpoint()
void Clusterpoint_pskel::post_Clusterpoint () virtual
Reimplemented in Clusterpoint_pimpl.
Definition at line 909 of file dnaparser_pskel.cxx.
{
}
X_parser()
void Clusterpoint_pskel::X_parser (::xml_schema::string_pskel & p)
Definition at line 48 of file dnaparser_pskel.cxx.
{
    this->X_parser_ = &p;
}
References X_parser_.
Y_parser()
void Clusterpoint_pskel::Y_parser (::xml_schema::string_pskel & p)
Definition at line 53 of file dnaparser_pskel.cxx.
{
    this->Y_parser_ = &p;
}
References Y_parser_.
Z_parser()
void Clusterpoint_pskel::Z_parser (::xml_schema::string_pskel & p)
Definition at line 58 of file dnaparser_pskel.cxx.
{
    this->Z_parser_ = &p;
}
References Z_parser_.
MeasurementDBID_parser()
void Clusterpoint_pskel::MeasurementDBID_parser (::xml_schema::string_pskel & p)
Definition at line 63 of file dnaparser_pskel.cxx.
{
    this->MeasurementDBID_parser_ = &p;
}
References MeasurementDBID_parser_.
SigmaXX_parser()
void Clusterpoint_pskel::SigmaXX_parser (::xml_schema::string_pskel & p)
Definition at line 68 of file dnaparser_pskel.cxx.
{
    this->SigmaXX_parser_ = &p;
}
References SigmaXX_parser_.
SigmaXY_parser()
void Clusterpoint_pskel::SigmaXY_parser (::xml_schema::string_pskel & p)
Definition at line 73 of file dnaparser_pskel.cxx.
{
    this->SigmaXY_parser_ = &p;
}
References SigmaXY_parser_.
SigmaXZ_parser()
void Clusterpoint_pskel::SigmaXZ_parser (::xml_schema::string_pskel & p)
Definition at line 78 of file dnaparser_pskel.cxx.
{
    this->SigmaXZ_parser_ = &p;
}
References SigmaXZ_parser_.
SigmaYY_parser()
void Clusterpoint_pskel::SigmaYY_parser (::xml_schema::string_pskel & p)
Definition at line 83 of file dnaparser_pskel.cxx.
{
    this->SigmaYY_parser_ = &p;
}
References SigmaYY_parser_.
SigmaYZ_parser()
void Clusterpoint_pskel::SigmaYZ_parser (::xml_schema::string_pskel & p)
Definition at line 88 of file dnaparser_pskel.cxx.
{
    this->SigmaYZ_parser_ = &p;
}
References SigmaYZ_parser_.
SigmaZZ_parser()
void Clusterpoint_pskel::SigmaZZ_parser (::xml_schema::string_pskel & p)
Definition at line 93 of file dnaparser_pskel.cxx.
{
    this->SigmaZZ_parser_ = &p;
}
References SigmaZZ_parser_.
PointCovariance_parser()
void Clusterpoint_pskel::PointCovariance_parser (::PointCovariance_pskel & p)
Definition at line 98 of file dnaparser_pskel.cxx.
{
    this->PointCovariance_parser_ = &p;
}
References PointCovariance_parser_.
parsers()
void Clusterpoint_pskel::parsers (::xml_schema::string_pskel & X, ::xml_schema::string_pskel & Y, ::xml_schema::string_pskel & Z, ::xml_schema::string_pskel & MeasurementDBID, ::xml_schema::string_pskel & SigmaXX, ::xml_schema::string_pskel & SigmaXY, ::xml_schema::string_pskel & SigmaXZ, ::xml_schema::string_pskel & SigmaYY, ::xml_schema::string_pskel & SigmaYZ, ::xml_schema::string_pskel & SigmaZZ, ::PointCovariance_pskel & PointCovariance)
Definition at line 103 of file dnaparser_pskel.cxx.
{
    this->X_parser_ = &X;
    this->Y_parser_ = &Y;
    this->Z_parser_ = &Z;
    this->MeasurementDBID_parser_ = &MeasurementDBID;
    this->SigmaXX_parser_ = &SigmaXX;
    this->SigmaXY_parser_ = &SigmaXY;
    this->SigmaXZ_parser_ = &SigmaXZ;
    this->SigmaYY_parser_ = &SigmaYY;
    this->SigmaYZ_parser_ = &SigmaYZ;
    this->SigmaZZ_parser_ = &SigmaZZ;
    this->PointCovariance_parser_ = &PointCovariance;
}
References MeasurementDBID(), MeasurementDBID_parser_, PointCovariance(), PointCovariance_parser_, SigmaXX(), SigmaXX_parser_, SigmaXY(), SigmaXY_parser_, SigmaXZ(), SigmaXZ_parser_, SigmaYY(), SigmaYY_parser_, SigmaYZ(), SigmaYZ_parser_, SigmaZZ(), SigmaZZ_parser_, X(), X_parser_, Y(), Y_parser_, Z(), and Z_parser_.
Referenced by dynadjust::dynamlinterop::dna_import::ParseXML().
InitparentGpsPointCluster()
void Clusterpoint_pskel::InitparentGpsPointCluster (dnaMsrPtr pGpsPointCluster) inline
Definition at line 355 of file dnaparser_pskel.hxx.
{   _parent_dnaGpsPointCluster = pGpsPointCluster; }
References _parent_dnaGpsPointCluster.
InitparentMsrCounter()
void Clusterpoint_pskel::InitparentMsrCounter (PUINT32 pMsrCounter) inline
Definition at line 356 of file dnaparser_pskel.hxx.
{ _pMeasurementCount = pMsrCounter; }
References _pMeasurementCount.
_start_element_impl()
bool Clusterpoint_pskel::_start_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n, const ::xml_schema::ro_string * t) protected virtual
Definition at line 913 of file dnaparser_pskel.cxx.
{
    XSD_UNUSED (t);
    if (this->::xml_schema::complex_content::_start_element_impl (ns, n, t))
        return true;
    if (n == "X" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->X_parser_;
        if (this->X_parser_)
            this->X_parser_->pre ();
        return true;
    }
    if (n == "Y" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Y_parser_;
        if (this->Y_parser_)
            this->Y_parser_->pre ();
        return true;
    }
    if (n == "Z" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->Z_parser_;
        if (this->Z_parser_)
            this->Z_parser_->pre ();
        return true;
    }
    if (n == "MeasurementID" && ns.empty())
    {
        this->::xml_schema::complex_content::context_.top().parser_ = this->MeasurementDBID_parser_;
        if (this->MeasurementDBID_parser_)
            this->MeasurementDBID_parser_->pre();
        return true;
    }
    if (n == "SigmaXX" && ns.empty())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaXX_parser_;
        if (this->SigmaXX_parser_)
            this->SigmaXX_parser_->pre ();
        return true;
    }
    if (n == "SigmaXY" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaXY_parser_;
        if (this->SigmaXY_parser_)
            this->SigmaXY_parser_->pre ();
        return true;
    }
    if (n == "SigmaXZ" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaXZ_parser_;
        if (this->SigmaXZ_parser_)
            this->SigmaXZ_parser_->pre ();
        return true;
    }
    if (n == "SigmaYY" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaYY_parser_;
        if (this->SigmaYY_parser_)
            this->SigmaYY_parser_->pre ();
        return true;
    }
    if (n == "SigmaYZ" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaYZ_parser_;
        if (this->SigmaYZ_parser_)
            this->SigmaYZ_parser_->pre ();
        return true;
    }
    if (n == "SigmaZZ" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->SigmaZZ_parser_;
        if (this->SigmaZZ_parser_)
            this->SigmaZZ_parser_->pre ();
        return true;
    }
    if (n == "PointCovariance" && ns.empty ())
    {
        this->::xml_schema::complex_content::context_.top ().parser_ = this->PointCovariance_parser_;
        if (this->PointCovariance_parser_)
        {
            this->PointCovariance_parser_->InitparentGpsPoint(_dnaGpsPoint);
            this->PointCovariance_parser_->pre ();
        }
        return true;
    }
    return false;
}
References _dnaGpsPoint, MeasurementDBID_parser_, PointCovariance_parser_, SigmaXX_parser_, SigmaXY_parser_, SigmaXZ_parser_, SigmaYY_parser_, SigmaYZ_parser_, SigmaZZ_parser_, X_parser_, Y_parser_, and Z_parser_.
_end_element_impl()
bool Clusterpoint_pskel::_end_element_impl (const ::xml_schema::ro_string & ns, const ::xml_schema::ro_string & n) protected virtual
Definition at line 1038 of file dnaparser_pskel.cxx.
{
    if (this->::xml_schema::complex_content::_end_element_impl (ns, n))
        return true;
    if (n == "X" && ns.empty ())
    {
        if (this->X_parser_)
            this->X (this->X_parser_->post_string ());
        return true;
    }
    if (n == "Y" && ns.empty ())
    {
        if (this->Y_parser_)
            this->Y (this->Y_parser_->post_string ());
        return true;
    }
    if (n == "Z" && ns.empty ())
    {
        if (this->Z_parser_)
            this->Z (this->Z_parser_->post_string ());
        return true;
    }
    if (n == "MeasurementID" && ns.empty())
    {
        if (this->MeasurementDBID_parser_)
            this->MeasurementDBID (this->MeasurementDBID_parser_->post_string());
        return true;
    }
    if (n == "SigmaXX" && ns.empty())
    {
        if (this->SigmaXX_parser_)
            this->SigmaXX (this->SigmaXX_parser_->post_string ());
        return true;
    }
    if (n == "SigmaXY" && ns.empty ())
    {
        if (this->SigmaXY_parser_)
            this->SigmaXY (this->SigmaXY_parser_->post_string ());
        return true;
    }
    if (n == "SigmaXZ" && ns.empty ())
    {
        if (this->SigmaXZ_parser_)
            this->SigmaXZ (this->SigmaXZ_parser_->post_string ());
        return true;
    }
    if (n == "SigmaYY" && ns.empty ())
    {
        if (this->SigmaYY_parser_)
            this->SigmaYY (this->SigmaYY_parser_->post_string ());
        return true;
    }
    if (n == "SigmaYZ" && ns.empty ())
    {
        if (this->SigmaYZ_parser_)
            this->SigmaYZ (this->SigmaYZ_parser_->post_string ());
        return true;
    }
    if (n == "SigmaZZ" && ns.empty ())
    {
        if (this->SigmaZZ_parser_)
            this->SigmaZZ (this->SigmaZZ_parser_->post_string ());
        return true;
    }
    if (n == "PointCovariance" && ns.empty ())
    {
        if (this->PointCovariance_parser_)
        {
            this->PointCovariance_parser_->post_PointCovariance ();
            this->PointCovariance ();
        }
        return true;
    }
    return false;
}
References MeasurementDBID(), MeasurementDBID_parser_, PointCovariance(), PointCovariance_parser_, SigmaXX(), SigmaXX_parser_, SigmaXY(), SigmaXY_parser_, SigmaXZ(), SigmaXZ_parser_, SigmaYY(), SigmaYY_parser_, SigmaYZ(), SigmaYZ_parser_, SigmaZZ(), SigmaZZ_parser_, X(), X_parser_, Y(), Y_parser_, Z(), and Z_parser_.
Member Data Documentation
X_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::X_parser_ protected
Definition at line 371 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and X_parser().
Y_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::Y_parser_ protected
Definition at line 372 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and Y_parser().
Z_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::Z_parser_ protected
Definition at line 373 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and Z_parser().
MeasurementDBID_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::MeasurementDBID_parser_ protected
Definition at line 374 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), MeasurementDBID_parser(), and parsers().
SigmaXX_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::SigmaXX_parser_ protected
Definition at line 375 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and SigmaXX_parser().
SigmaXY_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::SigmaXY_parser_ protected
Definition at line 376 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and SigmaXY_parser().
SigmaXZ_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::SigmaXZ_parser_ protected
Definition at line 377 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and SigmaXZ_parser().
SigmaYY_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::SigmaYY_parser_ protected
Definition at line 378 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and SigmaYY_parser().
SigmaYZ_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::SigmaYZ_parser_ protected
Definition at line 379 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and SigmaYZ_parser().
SigmaZZ_parser_
::xml_schema::string_pskel* Clusterpoint_pskel::SigmaZZ_parser_ protected
Definition at line 380 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and SigmaZZ_parser().
PointCovariance_parser_
::PointCovariance_pskel* Clusterpoint_pskel::PointCovariance_parser_ protected
Definition at line 381 of file dnaparser_pskel.hxx.
Referenced by _end_element_impl(), _start_element_impl(), Clusterpoint_pskel(), parsers(), and PointCovariance_parser().
_dnaGpsPoint
dnaMsrPtr Clusterpoint_pskel::_dnaGpsPoint protected
Definition at line 383 of file dnaparser_pskel.hxx.
Referenced by _start_element_impl(), Clusterpoint_pimpl::MeasurementDBID(), Clusterpoint_pimpl::post_Clusterpoint(), Clusterpoint_pimpl::pre(), Clusterpoint_pimpl::SigmaXX(), Clusterpoint_pimpl::SigmaXY(), Clusterpoint_pimpl::SigmaXZ(), Clusterpoint_pimpl::SigmaYY(), Clusterpoint_pimpl::SigmaYZ(), Clusterpoint_pimpl::SigmaZZ(), Clusterpoint_pimpl::X(), Clusterpoint_pimpl::Y(), and Clusterpoint_pimpl::Z().
_parent_dnaGpsPointCluster
dnaMsrPtr Clusterpoint_pskel::_parent_dnaGpsPointCluster protected
Definition at line 384 of file dnaparser_pskel.hxx.
Referenced by InitparentGpsPointCluster(), Clusterpoint_pimpl::post_Clusterpoint(), and Clusterpoint_pimpl::pre().
_pMeasurementCount
PUINT32 Clusterpoint_pskel::_pMeasurementCount protected
Definition at line 385 of file dnaparser_pskel.hxx.
Referenced by InitparentMsrCounter(), Clusterpoint_pimpl::X(), Clusterpoint_pimpl::Y(), and Clusterpoint_pimpl::Z().
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pskel.hxx
dynadjust/dnaimport/dnaparser_pskel.cxx