DynAdjust: ParamStnMsrCompareStn Class Reference
ParamStnMsrCompareStn Class Reference
#include <dnatemplatestnmsrfuncs.hpp>
Public Member Functions
bool operator() (const uint32_string_pair &lhs, const uint32_string_pair &rhs) const
bool operator() (const uint32_string_pair &lhs, const uint32_string_pair::first_type &k) const
bool operator() (const uint32_string_pair::first_type &k, const uint32_string_pair &rhs) const
Private Member Functions
bool keyLess (const uint32_string_pair::first_type &k1, const uint32_string_pair::first_type &k2) const
Detailed Description
Definition at line 966 of file dnatemplatestnmsrfuncs.hpp.
Member Function Documentation
operator()() [1/3]
bool ParamStnMsrCompareStn::operator() (const uint32_string_pair & lhs, const uint32_string_pair & rhs) const inline
Definition at line 969 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(lhs.first, rhs.first);
    }
References keyLess().
operator()() [2/3]
bool ParamStnMsrCompareStn::operator() (const uint32_string_pair & lhs, const uint32_string_pair::first_type & k) const inline
Definition at line 973 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(lhs.first, k);
    }
References keyLess().
operator()() [3/3]
bool ParamStnMsrCompareStn::operator() (const uint32_string_pair::first_type & k, const uint32_string_pair & rhs) const inline
Definition at line 977 of file dnatemplatestnmsrfuncs.hpp.
{
        return keyLess(k, rhs.first);
    }
References keyLess().
keyLess()
bool ParamStnMsrCompareStn::keyLess (const uint32_string_pair::first_type & k1, const uint32_string_pair::first_type & k2) const inline private
Definition at line 982 of file dnatemplatestnmsrfuncs.hpp.
{
        return k1 < k2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this class was generated from the following file:
include/functions/dnatemplatestnmsrfuncs.hpp