DynAdjust: dynadjust::networkadjust::adjust_process_prepare_thread Class Reference
dynadjust::networkadjust::adjust_process_prepare_thread Class Reference
#include <dnaadjust.hpp>
Public Member Functions
adjust_process_prepare_thread (dna_adjust *dnaAdj, const UINT32 &id, boost::exception_ptr &error, std::vector< boost::exception_ptr > &prep_errors)
void operator() ()
Private Member Functions
adjust_process_prepare_thread & operator= (const adjust_process_prepare_thread &rhs)
Private Attributes
dna_adjust * main_adj_
UINT32 thread_id_
boost::exception_ptr & error_
std::vector< boost::exception_ptr > & prep_errors_
Detailed Description
Definition at line 125 of file dnaadjust.hpp.
Constructor & Destructor Documentation
adjust_process_prepare_thread()
dynadjust::networkadjust::adjust_process_prepare_thread::adjust_process_prepare_thread (dna_adjust * dnaAdj, const UINT32 & id, boost::exception_ptr & error, std::vector< boost::exception_ptr > & prep_errors) inline
Definition at line 127 of file dnaadjust.hpp.
        : main_adj_(dnaAdj), thread_id_(id), error_(error),
          prep_errors_(prep_errors) {}
References error(), error_, main_adj_, prep_errors_, and thread_id_.
Referenced by operator=().
Member Function Documentation
operator()()
void dynadjust::networkadjust::adjust_process_prepare_thread::operator() ()
Definition at line 720 of file dnaadjust-multi.cpp.
{
    std::stringstream ss;
    UINT32 currentBlock;
    try {
        while (true)
        {
            if (prepareAdjustmentQueue.is_queue_exhausted())
                break;
            // Have any other adjustments failed?
            if (prepareAdjustmentExceptionThrown(prep_errors_))
                return;
            // Wait here until blocks have been placed on the queue
            if (!prepareAdjustmentQueue.front_and_pop(currentBlock))
            {
                boost::this_thread::sleep(boost::posix_time::milliseconds(2));
                continue;
            }
            // Have any other adjustments failed?
            if (prepareAdjustmentExceptionThrown(prep_errors_))
                return;
            main_adj_->SetcurrentBlock(currentBlock);
            main_adj_->CreateMeasurementTally(currentBlock);
            main_adj_->PrepareAdjustmentBlock(currentBlock, thread_id_);
            if (prepareAdjustmentQueue.is_empty())
                prepareAdjustmentQueue.queue_exhausted();
        }
        error_ = boost::exception_ptr();
    }
    catch (...) {
        error_ = boost::current_exception();
    }
}
References error_, main_adj_, prep_errors_, dynadjust::networkadjust::prepareAdjustmentExceptionThrown(), dynadjust::networkadjust::prepareAdjustmentQueue, and thread_id_.
operator=()
adjust_process_prepare_thread & dynadjust::networkadjust::adjust_process_prepare_thread::operator= (const adjust_process_prepare_thread & rhs) private
References adjust_process_prepare_thread().
Member Data Documentation
main_adj_
dna_adjust* dynadjust::networkadjust::adjust_process_prepare_thread::main_adj_ private
Definition at line 135 of file dnaadjust.hpp.
Referenced by adjust_process_prepare_thread(), and operator()().
thread_id_
UINT32 dynadjust::networkadjust::adjust_process_prepare_thread::thread_id_ private
Definition at line 136 of file dnaadjust.hpp.
Referenced by adjust_process_prepare_thread(), and operator()().
error_
boost::exception_ptr& dynadjust::networkadjust::adjust_process_prepare_thread::error_ private
Definition at line 137 of file dnaadjust.hpp.
Referenced by adjust_process_prepare_thread(), and operator()().
prep_errors_
std::vector<boost::exception_ptr>& dynadjust::networkadjust::adjust_process_prepare_thread::prep_errors_ private
Definition at line 138 of file dnaadjust.hpp.
Referenced by adjust_process_prepare_thread(), and operator()().
The documentation for this class was generated from the following files:
dynadjust/dnaadjust/dnaadjust.hpp
dynadjust/dnaadjust/dnaadjust-multi.cpp