DynAdjust: dynadjust::CDnaProjectFile Class Reference
dynadjust::CDnaProjectFile Class Reference
#include <dnaprojectfile.hpp>
Public Member Functions
CDnaProjectFile (void)
CDnaProjectFile (const std::string &projectFile, const UINT16 &verifyContext)
virtual ~CDnaProjectFile (void)
project_settings GetSettings () const
void LoadProjectFile (const std::string &projectFile)
void LoadProjectFile ()
void PrintProjectFile ()
template<typename T, typename U>
void PrintRecord (std::ostream &os, const T &variable, const U &value)
template<typename T>
void PrintVariable (std::ostream &os, const T &variable)
template<typename T>
void PrintValue (std::ostream &os, const T &value)
void UpdateSettingsGeneral (const general_settings &g)
void UpdateSettingsImport (const project_settings &p)
void UpdateSettingsGeoid (const project_settings &p)
void UpdateSettingsReftran (const project_settings &p)
void UpdateSettingsAdjust (const project_settings &p)
void UpdateSettingsSegment (const project_settings &p)
void UpdateSettingsPlot (const project_settings &p)
void UpdateSettingsOutput (const project_settings &p)
template<typename T>
void AddOptionValue (std::ostream &os, const char *const option, const T &value)
template<typename T>
void AddDefaultValue (std::ostream &os, const T &value)
std::string FormCommandLineOptionsStringImport ()
std::string FormCommandLineOptionsStringGeneral ()
Private Member Functions
CDnaProjectFile (const project_settings &project)
CDnaProjectFile (const CDnaProjectFile &newProject)
CDnaProjectFile & operator= (const CDnaProjectFile &rhs)
bool operator== (const CDnaProjectFile &rhs) const
void InitialiseGeneralSettings ()
void InitialiseImportSettings ()
void InitialiseReftranSettings ()
void InitialiseGeoidSettings ()
void InitialiseSegmentSettings ()
void InitialiseAdjustSettings ()
void LoadSettingGeneral (const settingMode mSetting, const std::string &var, std::string &val)
void LoadSettingImport (const settingMode mSetting, const std::string &var, std::string &val)
void LoadSettingReftran (const std::string &var, std::string &val)
void LoadSettingGeoid (const std::string &var, std::string &val)
void LoadSettingSegment (const std::string &var, std::string &val)
void LoadSettingAdjust (const std::string &var, std::string &val)
void LoadSettingOutput (const std::string &var, std::string &val)
Private Attributes
project_settings settings_
Detailed Description
Definition at line 47 of file dnaprojectfile.hpp.
Constructor & Destructor Documentation
CDnaProjectFile() [1/4]
dynadjust::CDnaProjectFile::CDnaProjectFile (void)
Definition at line 33 of file dnaprojectfile.cpp.
{
}
Referenced by CDnaProjectFile(), operator=(), and operator==().
CDnaProjectFile() [2/4]
dynadjust::CDnaProjectFile::CDnaProjectFile (const std::string & projectFile, const UINT16 & verifyContext)
Definition at line 39 of file dnaprojectfile.cpp.
{
    LoadProjectFile(projectFile);
    switch (verifyContext)
    {
    case importSetting:
        InitialiseImportSettings();
        break;
    case reftranSetting:
        InitialiseReftranSettings();
        break;
    case geoidSetting:
        InitialiseGeoidSettings();
        break;
    case segmentSetting:
        InitialiseSegmentSettings();
        break;
    case adjustSetting:
        InitialiseAdjustSettings();
        break;
    default:
        InitialiseGeneralSettings();
    }
}
References adjustSetting, geoidSetting, importSetting, InitialiseAdjustSettings(), InitialiseGeneralSettings(), InitialiseGeoidSettings(), InitialiseImportSettings(), InitialiseReftranSettings(), InitialiseSegmentSettings(), LoadProjectFile(), reftranSetting, and segmentSetting.
~CDnaProjectFile()
virtual dynadjust::CDnaProjectFile::~CDnaProjectFile (void) inline virtual
Definition at line 54 of file dnaprojectfile.hpp.
{}
CDnaProjectFile() [3/4]
dynadjust::CDnaProjectFile::CDnaProjectFile (const project_settings & project) private
CDnaProjectFile() [4/4]
dynadjust::CDnaProjectFile::CDnaProjectFile (const CDnaProjectFile & newProject) private
References CDnaProjectFile().
Member Function Documentation
operator=()
CDnaProjectFile & dynadjust::CDnaProjectFile::operator= (const CDnaProjectFile & rhs) private
References CDnaProjectFile().
operator==()
bool dynadjust::CDnaProjectFile::operator== (const CDnaProjectFile & rhs) const private
References CDnaProjectFile().
GetSettings()
project_settings dynadjust::CDnaProjectFile::GetSettings () const inline
Definition at line 67 of file dnaprojectfile.hpp.
{ return settings_; }
References settings_.
Referenced by main(), ParseCommandLineOptions(), and ParseCommandLineOptions().
LoadProjectFile() [1/2]
void dynadjust::CDnaProjectFile::LoadProjectFile (const std::string & projectFile)
Definition at line 92 of file dnaprojectfile.cpp.
{
    // load project file
    if (boost::filesystem::exists(projectFile))
    {
        settings_.g.project_file = projectFile;
        LoadProjectFile();
    }
    else
    {
        std::stringstream err_msg;
        err_msg << "LoadProjectFile(): Project file " <<
        projectFile << " does not exist." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
    }
}
References LoadProjectFile(), and settings_.
Referenced by main().
LoadProjectFile() [2/2]
void dynadjust::CDnaProjectFile::LoadProjectFile ()
Definition at line 110 of file dnaprojectfile.cpp.
{
    // load project file using p.g.project_file
    std::ifstream dnaproj_file;
    std::stringstream err_msg;
    err_msg << "LoadProjectFile(): An error was encountered when opening " <<
        settings_.g.project_file << "." << std::endl;
    try {
        // create binary aml file.  Throws runtime_error on failure.
        file_opener(dnaproj_file, settings_.g.project_file,
            std::ios::in, ascii, true);
    }
    catch (const std::runtime_error& e) {
        err_msg << e.what();
        throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
    }
    err_msg.str("");
    err_msg << "LoadProjectFile(): An error was encountered when loading from " <<
        settings_.g.project_file << "." << std::endl;
    std::string str, line, var, val;
    std::stringstream ss;
    settingMode mSetting(unknownSetting);
    while (!dnaproj_file.eof())
    {
        try {
            getline(dnaproj_file, line, '\n');
        }
        catch (std::ifstream::failure& f)
        {
            if (dnaproj_file.eof())
                break;
            err_msg << f.what() << std::endl;
            throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
        }
        catch (...)
        {
            if (dnaproj_file.eof())
                break;
            err_msg << "Could not read file." << std::endl;
            throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
        }
        // Blank line?
        if (line.empty())
            continue;
        // Line too short?
        if (line.length() <= PRINT_VAR_PAD)
            continue;
        // #variables
        if (line.find(section_variables) != std::string::npos)
        {
            mSetting = switchSetting;
            continue;
        }
        // #general
        if (line.find(section_general) != std::string::npos)
        {
            mSetting = generalSetting;
            continue;
        }
        // #import
        if (line.find(section_import) != std::string::npos)
        {
            mSetting = importSetting;
            continue;
        }
        // #reftran
        if (line.find(section_reftran) != std::string::npos)
        {
            mSetting = reftranSetting;
            continue;
        }
        // #general
        if (line.find(section_geoid) != std::string::npos)
        {
            mSetting = geoidSetting;
            continue;
        }
        // #segment
        if (line.find(section_segment) != std::string::npos)
        {
            mSetting = segmentSetting;
            continue;
        }
        // #adjust
        if (line.find(section_adjust) != std::string::npos)
        {
            mSetting = adjustSetting;
            continue;
        }
        // #output
        if (line.find(section_output) != std::string::npos)
        {
            mSetting = outputSetting;
            continue;
        }
        // #plot
        if (line.find(section_plot) != std::string::npos)
        {
            mSetting = plotSetting;
            continue;
        }
        // #display
        if (line.find(section_display) != std::string::npos)
        {
            mSetting = displaySetting;
            continue;
        }
        // Line?
        if (line.find("----------") != std::string::npos)
            continue;
        // Now get the variables and their value relating to the setting
        var = trimstr(line.substr(0, PRINT_VAR_PAD));
        if (line.length() > PRINT_VAR_PAD)
            val = trimstr(line.substr(PRINT_VAR_PAD));
        else
            val.clear();
        try {
            switch (mSetting)
            {
            case generalSetting:
                LoadSettingGeneral(mSetting, var, val);
                break;
            case importSetting:
                LoadSettingImport(mSetting, var, val);
                break;
            case reftranSetting:
                LoadSettingReftran(var, val);
                break;
            case geoidSetting:
                LoadSettingGeoid(var, val);
                break;
            case segmentSetting:
                LoadSettingSegment(var, val);
                break;
            case adjustSetting:
                LoadSettingAdjust(var, val);
                LoadSettingOutput(var, val);
                break;
            case outputSetting:
                LoadSettingOutput(var, val);
                break;
            case plotSetting:
                LoadSettingOutput(var, val);
                break;
            case displaySetting:
                break;
            default:
                break;
            }
        }
        catch (const std::runtime_error& e) {
            err_msg << e.what();
            throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
        }
        catch (...) {
            throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
        }
    }
    dnaproj_file.clear();
    dnaproj_file.close();
}
References adjustSetting, ascii, displaySetting, file_opener(), generalSetting, geoidSetting, importSetting, LoadSettingAdjust(), LoadSettingGeneral(), LoadSettingGeoid(), LoadSettingImport(), LoadSettingOutput(), LoadSettingReftran(), LoadSettingSegment(), outputSetting, plotSetting, PRINT_VAR_PAD(), reftranSetting, section_adjust, section_display, section_general, section_geoid, section_import, section_output, section_plot, section_reftran, section_segment, section_variables, segmentSetting, settings_, switchSetting, trimstr(), and unknownSetting.
Referenced by CDnaProjectFile(), and LoadProjectFile().
PrintProjectFile()
void dynadjust::CDnaProjectFile::PrintProjectFile ()
Definition at line 1686 of file dnaprojectfile.cpp.
{
    std::ofstream dnaproj_file;
    std::stringstream err_msg;
    err_msg << "PrintProjectFile(): An error was encountered when opening " <<
        settings_.g.project_file << "." << std::endl;
    try {
        // create binary aml file.  Throws runtime_error on failure.
        file_opener(dnaproj_file, settings_.g.project_file,
            std::ios::out, ascii);
    }
    catch (const std::runtime_error& e) {
        err_msg << e.what();
        throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
    }
    catch (...) {
        throw boost::enable_current_exception(std::runtime_error(err_msg.str()));
    }
    err_msg.str("");
    err_msg << "PrintProjectFile(): An error was encountered when writing to " <<
        settings_.g.project_file << "." << std::endl;
    std::stringstream ss;
    // Write header line
    dnaproj_header(dnaproj_file, settings_.g.network_name + " project file");
    dnaproj_file << std::endl << std::endl;
    // #general
    ss.str("");
    ss << section_general << " (" << PRINT_VAR_PAD << ")";
    PrintRecord(dnaproj_file, ss.str(), "VALUE");
    dnaproj_file << OUTPUTLINE << std::endl;
    PrintRecord(dnaproj_file, NETWORK_NAME, settings_.g.network_name);                              // network name
    PrintRecord(dnaproj_file, INPUT_FOLDER, boost::filesystem::system_complete(settings_.g.input_folder).string()); // Path containing all input files
    PrintRecord(dnaproj_file, OUTPUT_FOLDER, boost::filesystem::system_complete(settings_.g.output_folder).string());  // Path for all output files
    PrintRecord(dnaproj_file, VERBOSE, settings_.g.verbose);                                     // Give detailed information about what dnainterop is doing.
                                                                                                    // 0: No information (default)
                                                                                                    // 1: Helpful information
                                                                                                    // 2: Extended information\n3: Debug level information
    PrintRecord(dnaproj_file, QUIET, yesno_string(settings_.g.quiet));                             // Run quietly?
    PrintRecord(dnaproj_file, PROJECT_FILE, boost::filesystem::system_complete(settings_.g.project_file).string()); // project file
    PrintRecord(dnaproj_file, DYNADJUST_LOG_FILE, boost::filesystem::system_complete(settings_.g.log_file).string()); // dynadjust log file
    dnaproj_file << std::endl;
    // #import
    ss.str("");
    ss << section_import << " (" << PRINT_VAR_PAD << ")";
    PrintRecord(dnaproj_file, ss.str(), "VALUE");
    dnaproj_file << OUTPUTLINE << std::endl;
    // Input files
    for_each (settings_.i.input_files.begin(), settings_.i.input_files.end(),
        [&dnaproj_file, this] (std::string file) {
            PrintRecord(dnaproj_file, IMPORT_FILE, leafStr<std::string>(file.c_str()));
    });
    // geoid file
    PrintRecord(dnaproj_file, IMPORT_GEO_FILE,
        (settings_.i.geo_file.empty() ? " " : leafStr<std::string>(settings_.i.geo_file)));
    // reference frame settings
    PrintRecord(dnaproj_file, REFERENCE_FRAME, settings_.i.reference_frame);
    PrintRecord(dnaproj_file, EPOCH, settings_.i.epoch);
    PrintRecord(dnaproj_file, OVERRIDE_INPUT_FRAME,
        yesno_string(settings_.i.override_input_rfame));
    // data screening
    PrintRecord(dnaproj_file, BOUNDING_BOX, settings_.i.bounding_box);
    PrintRecord(dnaproj_file, GET_MSRS_TRANSCENDING_BOX,
        yesno_string(settings_.i.include_transcending_msrs));
    PrintRecord(dnaproj_file, INCLUDE_STN_ASSOC_MSRS,
        (settings_.i.stn_associated_msr_include.empty() ? "no" : settings_.i.stn_associated_msr_include));
    PrintRecord(dnaproj_file, EXCLUDE_STN_ASSOC_MSRS,
        (settings_.i.stn_associated_msr_exclude.empty() ? "no" : settings_.i.stn_associated_msr_exclude));
    PrintRecord(dnaproj_file, SPLIT_CLUSTERS,
        yesno_string(settings_.i.split_clusters));
    PrintRecord(dnaproj_file, IMPORT_SEG_BLOCK,
        (settings_.i.import_block ? val_uint<std::string, UINT32>(settings_.i.import_block_number) : "no"));
    PrintRecord(dnaproj_file, SEG_FILE,
        (settings_.i.seg_file.empty() ? " " : leafStr<std::string>(settings_.i.seg_file)));
    PrintRecord(dnaproj_file, PREFER_X_MSR_AS_G,
        yesno_string(settings_.i.prefer_single_x_as_g));
    PrintRecord(dnaproj_file, INCLUDE_MSRS, settings_.i.include_msrs);
    PrintRecord(dnaproj_file, EXCLUDE_MSRS, settings_.i.exclude_msrs);
    PrintRecord(dnaproj_file, STATION_RENAMING_FILE,
        leafStr<std::string>(settings_.i.stn_renamingfile));
    PrintRecord(dnaproj_file, STATION_DISCONTINUITY_FILE,
        leafStr<std::string>(settings_.i.stn_discontinuityfile));
    PrintRecord(dnaproj_file, TEST_NEARBY_STNS,
        yesno_string(settings_.i.search_nearby_stn));
    PrintRecord(dnaproj_file, TEST_NEARBY_STN_DIST, settings_.i.search_stn_radius);
    PrintRecord(dnaproj_file, TEST_SIMILAR_GNSS_MSRS,
        yesno_string(settings_.i.search_similar_msr_gx));
    PrintRecord(dnaproj_file, TEST_SIMILAR_MSRS,
        yesno_string(settings_.i.search_similar_msr));
    PrintRecord(dnaproj_file, IGNORE_INSUFFICIENT_MSRS,
        yesno_string(settings_.i.ignore_insufficient_msrs));
    PrintRecord(dnaproj_file, IGNORE_SIMILAR_MSRS,
        yesno_string(settings_.i.ignore_similar_msr));
    PrintRecord(dnaproj_file, REMOVE_IGNORED_MSRS,
        yesno_string(settings_.i.remove_ignored_msr));
    PrintRecord(dnaproj_file, FLAG_UNUSED_STNS,
        yesno_string(settings_.i.flag_unused_stn));
    PrintRecord(dnaproj_file, TEST_INTEGRITY,
        yesno_string(settings_.i.test_integrity));
    // GNSS variance matrix scaling
    PrintRecord(dnaproj_file, VSCALE, settings_.i.vscale);
    PrintRecord(dnaproj_file, PSCALE, settings_.i.pscale);
    PrintRecord(dnaproj_file, LSCALE, settings_.i.lscale);
    PrintRecord(dnaproj_file, HSCALE, settings_.i.hscale);
    PrintRecord(dnaproj_file, SCALAR_FILE, leafStr<std::string>(settings_.i.scalar_file));
    // export options
    PrintRecord(dnaproj_file, EXPORT_XML_FILES,
        yesno_string(settings_.i.export_dynaml));                      // Create DynaML output file
    PrintRecord(dnaproj_file, EXPORT_SINGLE_XML_FILE,
        yesno_string(settings_.i.export_single_xml_file));             // Create single station and measurement DynaML output files
    PrintRecord(dnaproj_file, EXPORT_DNA_FILES,
        yesno_string(settings_.i.export_dna_files));
    PrintRecord(dnaproj_file, EXPORT_ASL_FILE,
        yesno_string(settings_.i.export_asl_file));
    PrintRecord(dnaproj_file, EXPORT_AML_FILE,
        yesno_string(settings_.i.export_aml_file));
    PrintRecord(dnaproj_file, EXPORT_MAP_FILE,
        yesno_string(settings_.i.export_map_file));
    PrintRecord(dnaproj_file, SIMULATE_MSR_FILE,
        yesno_string(settings_.i.simulate_measurements));
    dnaproj_file << std::endl;
    // #reftran
    ss.str("");
    ss << section_reftran << " (" << PRINT_VAR_PAD << ")";
    PrintRecord(dnaproj_file, ss.str(), "VALUE");
    dnaproj_file << OUTPUTLINE << std::endl;
    PrintRecord(dnaproj_file, REFERENCE_FRAME, settings_.r.reference_frame);
    PrintRecord(dnaproj_file, EPOCH, settings_.r.epoch);
    PrintRecord(dnaproj_file, TECTONIC_PLATE_MODEL_OPTION, settings_.r.plate_model_option);                  // Plate motion model option
    PrintRecord(dnaproj_file, TECTONIC_PLATE_BDY_FILE, leafStr<std::string>(settings_.r.tpb_file));              // Tectonic plate boundary file
    PrintRecord(dnaproj_file, TECTONIC_PLATE_POLE_FILE, leafStr<std::string>(settings_.r.tpp_file));                // Tectonic plate pole file
    dnaproj_file << std::endl;
    // #geoid
    ss.str("");
    ss << section_geoid << " (" << PRINT_VAR_PAD << ")";
    PrintRecord(dnaproj_file, ss.str(), "VALUE");
    dnaproj_file << OUTPUTLINE << std::endl;
    // Output configured to populate binary station files
    PrintRecord(dnaproj_file, NTV2_FILEPATH, boost::filesystem::system_complete(settings_.n.ntv2_geoid_file).string());                    // Full file path to geoid file
    PrintRecord(dnaproj_file, METHOD, settings_.n.interpolation_method);
    PrintRecord(dnaproj_file, DDEG_FORMAT, settings_.n.coordinate_format);
    PrintRecord(dnaproj_file, DIRECTION, settings_.n.ellipsoid_to_ortho);
    //PrintRecord(dnaproj_file, CONVERT_BST_HT,
    //  yesno_string(settings_.n.convert_heights));
    PrintRecord(dnaproj_file, EXPORT_GEO_FILE,
        yesno_string(settings_.n.export_dna_geo_file));
    dnaproj_file << std::endl;
    // #segment
    ss.str("");
    ss << section_segment << " (" << PRINT_VAR_PAD << ")";
    PrintRecord(dnaproj_file, ss.str(), "VALUE");
    dnaproj_file << OUTPUTLINE << std::endl;
    PrintRecord(dnaproj_file, NET_FILE, leafStr<std::string>(settings_.s.net_file));                // Starting stations file
    PrintRecord(dnaproj_file, SEG_FILE, leafStr<std::string>(settings_.s.seg_file));                // Segmentation output file
    PrintRecord(dnaproj_file, SEG_MIN_INNER_STNS, settings_.s.min_inner_stations);            // Minimum number of inner stations per block
    PrintRecord(dnaproj_file, SEG_THRESHOLD_STNS, settings_.s.max_total_stations);            // Maximum number of total stations per block
    PrintRecord(dnaproj_file, SEG_FORCE_CONTIGUOUS,
        yesno_string(settings_.s.force_contiguous_blocks));
    // Stations to be incorporated within the first block.
    PrintRecord(dnaproj_file, SEG_STARTING_STN, settings_.s.seg_starting_stns);
    dnaproj_file << std::endl;
    // #adjust
    ss.str("");
    ss << section_adjust << " (" << PRINT_VAR_PAD << ")";
    PrintRecord(dnaproj_file, ss.str(), "VALUE");
    dnaproj_file << OUTPUTLINE << std::endl;
    PrintRecord(dnaproj_file, SEG_FILE, leafStr<std::string>(settings_.a.seg_file));                // Starting stations file
    PrintRecord(dnaproj_file, COMMENTS, settings_.a.comments);                              // Starting stations file
    PrintRecord(dnaproj_file, ADJUSTMENT_MODE, adjustmentMode<std::string, UINT32>(settings_.a.adjust_mode));
    PrintRecord(dnaproj_file, MODE_PHASED_MT,
        yesno_string(settings_.a.multi_thread));
    PrintRecord(dnaproj_file, STAGED_ADJUSTMENT,
        yesno_string(settings_.a.stage));
    PrintRecord(dnaproj_file, CONF_INTERVAL, settings_.a.confidence_interval);             // Confidence interval
    PrintRecord(dnaproj_file, ITERATION_THRESHOLD, settings_.a.iteration_threshold);     // Threshold to halt iterations
    PrintRecord(dnaproj_file, MAX_ITERATIONS, settings_.a.max_iterations);                    // Number of iteration before a solution is adopted
    PrintRecord(dnaproj_file, STN_CONSTRAINTS, settings_.a.station_constraints);
    ss.str("");
    ss << std::fixed << std::setprecision(3) << settings_.a.free_std_dev;
    PrintRecord(dnaproj_file, FREE_STN_SD, ss.str());                                     // SD for free stations
    ss.str("");
    ss << std::scientific << std::setprecision(4) << settings_.a.fixed_std_dev;
    PrintRecord(dnaproj_file, FIXED_STN_SD, ss.str());                                       // SD for fixed stations
    //PrintRecord(dnaproj_file, LSQ_INVERSE_METHOD, settings_.a.inverse_method_lsq);            // Least squares inverse method
    PrintRecord(dnaproj_file, SCALE_NORMAL_UNITY,
        yesno_string(settings_.a.scale_normals_to_unity));                                 // Scale normals to unity before inversion
    PrintRecord(dnaproj_file, RECREATE_STAGE_FILES,
        yesno_string(settings_.a.recreate_stage_files));                                   // Recreate stage files
    PrintRecord(dnaproj_file, PURGE_STAGE_FILES,
        yesno_string(settings_.a.purge_stage_files));                                      // Purge stage files
    PrintRecord(dnaproj_file, TYPE_B_GLOBAL, settings_.a.type_b_global);                   // Global Type B uncertainties
    PrintRecord(dnaproj_file, TYPE_B_FILE, leafStr<std::string>(settings_.a.type_b_file));       // Type B uncertainty file
    dnaproj_file << std::endl;
    // #output
    ss.str("");
    ss << section_output << " (" << PRINT_VAR_PAD << ")";
    PrintRecord(dnaproj_file, ss.str(), "VALUE");
    dnaproj_file << OUTPUTLINE << std::endl;
    PrintRecord(dnaproj_file, OUTPUT_MSR_TO_STN,
        yesno_string(settings_.o._msr_to_stn));
    PrintRecord(dnaproj_file, OUTPUT_MSR_TO_STN_SORTBY, settings_.o._sort_msr_to_stn);
    PrintRecord(dnaproj_file, OUTPUT_ADJ_STN_ITER,
        yesno_string(settings_.o._adj_stn_iteration));
    PrintRecord(dnaproj_file, OUTPUT_ADJ_STAT_ITER,
        yesno_string(settings_.o._adj_stat_iteration));
    PrintRecord(dnaproj_file, OUTPUT_ADJ_MSR_ITER,
        yesno_string(settings_.o._adj_msr_iteration));
    PrintRecord(dnaproj_file, OUTPUT_CMP_MSR_ITER,
        yesno_string(settings_.o._cmp_msr_iteration));
    PrintRecord(dnaproj_file, OUTPUT_ADJ_MSR,
        yesno_string(settings_.o._adj_msr_final));
    PrintRecord(dnaproj_file, OUTPUT_ADJ_GNSS_UNITS,
        settings_.o._adj_gnss_units);
    PrintRecord(dnaproj_file, OUTPUT_ADJ_MSR_TSTAT,
        yesno_string(settings_.o._adj_msr_tstat));
    PrintRecord(dnaproj_file, OUTPUT_ADJ_MSR_SORTBY, settings_.o._sort_adj_msr);
    PrintRecord(dnaproj_file, OUTPUT_ADJ_MSR_DBID,
        yesno_string(settings_.o._database_ids));
    PrintRecord(dnaproj_file, OUTPUT_ADJ_MSR_BLOCKS,
        yesno_string(settings_.o._output_msr_blocks));
    PrintRecord(dnaproj_file, OUTPUT_ADJ_STN_SORT_ORDER,
        yesno_string(settings_.o._sort_stn_file_order));
    PrintRecord(dnaproj_file, OUTPUT_STN_COORD_TYPES, settings_.o._stn_coord_types);
    PrintRecord(dnaproj_file, OUTPUT_ANGULAR_TYPE_STN, settings_.o._angular_type_stn);
    PrintRecord(dnaproj_file, OUTPUT_STN_CORR,
        yesno_string(settings_.o._stn_corr));
    PrintRecord(dnaproj_file, OUTPUT_PRECISION_METRES_STN, settings_.o._precision_metres_stn);
    PrintRecord(dnaproj_file, OUTPUT_PRECISION_SECONDS_STN, settings_.o._precision_seconds_stn);
    PrintRecord(dnaproj_file, OUTPUT_PRECISION_METRES_MSR, settings_.o._precision_metres_msr);
    PrintRecord(dnaproj_file, OUTPUT_PRECISION_SECONDS_MSR, settings_.o._precision_seconds_msr);
    PrintRecord(dnaproj_file, OUTPUT_ANGULAR_TYPE_MSR, settings_.o._angular_type_msr);
    PrintRecord(dnaproj_file, OUTPUT_DMS_FORMAT_MSR, settings_.o._dms_format_msr);
    PrintRecord(dnaproj_file, OUTPUT_POS_UNCERTAINTY,
        yesno_string(settings_.o._positional_uncertainty));
    PrintRecord(dnaproj_file, OUTPUT_APU_CORRELATIONS,
        yesno_string(settings_.o._output_pu_covariances));
    PrintRecord(dnaproj_file, OUTPUT_APU_UNITS,
        settings_.o._apu_vcv_units);
    PrintRecord(dnaproj_file, OUTPUT_STN_COR_FILE,
        yesno_string(settings_.o._init_stn_corrections));
    ss.str("");
    ss << std::fixed << std::setprecision(3) << settings_.o._hz_corr_threshold;
    PrintRecord(dnaproj_file, HZ_CORR_THRESHOLD, ss.str());
    ss.str("");
    ss << std::fixed << std::setprecision(3) << settings_.o._vt_corr_threshold;
    PrintRecord(dnaproj_file, VT_CORR_THRESHOLD, ss.str());
    PrintRecord(dnaproj_file, EXPORT_XML_STN_FILE,
        yesno_string(settings_.o._export_xml_stn_file));
    PrintRecord(dnaproj_file, EXPORT_DNA_STN_FILE,
        yesno_string(settings_.o._export_dna_stn_file));
    PrintRecord(dnaproj_file, EXPORT_SNX_FILE,
        yesno_string(settings_.o._export_snx_file));
    dnaproj_file << std::endl;
    // #plot
    ss.str("");
    ss << section_plot << " (" << PRINT_VAR_PAD << ")";
    PrintRecord(dnaproj_file, ss.str(), "VALUE");
    dnaproj_file << OUTPUTLINE << std::endl;
    dnaproj_file << std::endl;
    dnaproj_file.close();
}
References ADJUSTMENT_MODE, adjustmentMode(), ascii, BOUNDING_BOX, COMMENTS, CONF_INTERVAL, DDEG_FORMAT, DIRECTION, dnaproj_header(), DYNADJUST_LOG_FILE, EPOCH, EXCLUDE_MSRS, EXCLUDE_STN_ASSOC_MSRS, EXPORT_AML_FILE, EXPORT_ASL_FILE, EXPORT_DNA_FILES, EXPORT_DNA_STN_FILE, EXPORT_GEO_FILE, EXPORT_MAP_FILE, EXPORT_SINGLE_XML_FILE, EXPORT_SNX_FILE, EXPORT_XML_FILES, EXPORT_XML_STN_FILE, file_opener(), FIXED_STN_SD, FLAG_UNUSED_STNS, FREE_STN_SD, GET_MSRS_TRANSCENDING_BOX, HSCALE, HZ_CORR_THRESHOLD, IGNORE_INSUFFICIENT_MSRS, IGNORE_SIMILAR_MSRS, IMPORT_GEO_FILE, IMPORT_SEG_BLOCK, INCLUDE_MSRS, INCLUDE_STN_ASSOC_MSRS, INPUT_FOLDER, ITERATION_THRESHOLD, leafStr(), LSCALE, MAX_ITERATIONS, METHOD, MODE_PHASED_MT, NET_FILE, NETWORK_NAME, NTV2_FILEPATH, OUTPUT_ADJ_GNSS_UNITS, OUTPUT_ADJ_MSR, OUTPUT_ADJ_MSR_BLOCKS, OUTPUT_ADJ_MSR_DBID, OUTPUT_ADJ_MSR_ITER, OUTPUT_ADJ_MSR_SORTBY, OUTPUT_ADJ_MSR_TSTAT, OUTPUT_ADJ_STAT_ITER, OUTPUT_ADJ_STN_ITER, OUTPUT_ADJ_STN_SORT_ORDER, OUTPUT_ANGULAR_TYPE_MSR, OUTPUT_ANGULAR_TYPE_STN, OUTPUT_APU_CORRELATIONS, OUTPUT_APU_UNITS, OUTPUT_CMP_MSR_ITER, OUTPUT_DMS_FORMAT_MSR, OUTPUT_FOLDER, OUTPUT_MSR_TO_STN, OUTPUT_MSR_TO_STN_SORTBY, OUTPUT_POS_UNCERTAINTY, OUTPUT_PRECISION_METRES_MSR, OUTPUT_PRECISION_METRES_STN, OUTPUT_PRECISION_SECONDS_MSR, OUTPUT_PRECISION_SECONDS_STN, OUTPUT_STN_COORD_TYPES, OUTPUT_STN_COR_FILE, OUTPUT_STN_CORR, OUTPUTLINE, OVERRIDE_INPUT_FRAME, PREFER_X_MSR_AS_G, PRINT_VAR_PAD(), PrintRecord(), PROJECT_FILE, PSCALE, PURGE_STAGE_FILES, QUIET, RECREATE_STAGE_FILES, REFERENCE_FRAME, REMOVE_IGNORED_MSRS, SCALAR_FILE, SCALE_NORMAL_UNITY, section_adjust, section_general, section_geoid, section_import, section_output, section_plot, section_reftran, section_segment, SEG_FILE, SEG_FORCE_CONTIGUOUS, SEG_MIN_INNER_STNS, SEG_STARTING_STN, SEG_THRESHOLD_STNS, settings_, SIMULATE_MSR_FILE, SPLIT_CLUSTERS, STAGED_ADJUSTMENT, STATION_DISCONTINUITY_FILE, STATION_RENAMING_FILE, STN_CONSTRAINTS, TECTONIC_PLATE_BDY_FILE, TECTONIC_PLATE_MODEL_OPTION, TECTONIC_PLATE_POLE_FILE, TEST_INTEGRITY, TEST_NEARBY_STN_DIST, TEST_NEARBY_STNS, TEST_SIMILAR_GNSS_MSRS, TEST_SIMILAR_MSRS, TYPE_B_FILE, TYPE_B_GLOBAL, val_uint(), VERBOSE, VSCALE, VT_CORR_THRESHOLD, and yesno_string().
Referenced by main().
PrintRecord()
template<typename T, typename U> void dynadjust::CDnaProjectFile::PrintRecord (std::ostream & os, const T & variable, const U & value)
Definition at line 1629 of file dnaprojectfile.cpp.
{
    PrintVariable(os, variable);
    PrintValue(os, value);
}
References PrintValue(), and PrintVariable().
Referenced by PrintProjectFile().
PrintVariable()
template<typename T> void dynadjust::CDnaProjectFile::PrintVariable (std::ostream & os, const T & variable)
Definition at line 1637 of file dnaprojectfile.cpp.
{
    // width of 35
    os << std::setw(PRINT_VAR_PAD) << std::left << variable;
}
References PRINT_VAR_PAD().
Referenced by PrintRecord().
PrintValue()
template<typename T> void dynadjust::CDnaProjectFile::PrintValue (std::ostream & os, const T & value)
Definition at line 1644 of file dnaprojectfile.cpp.
{
    // width of 45
    os << std::setw(PRINT_VAL_PAD) << std::left << value << std::endl;
}
References PRINT_VAL_PAD().
Referenced by PrintRecord().
UpdateSettingsGeneral()
void dynadjust::CDnaProjectFile::UpdateSettingsGeneral (const general_settings & g) inline
Definition at line 81 of file dnaprojectfile.hpp.
{
        settings_.g = g;
    }
References settings_.
Referenced by main(), UpdateSettingsAdjust(), UpdateSettingsGeoid(), UpdateSettingsImport(), UpdateSettingsOutput(), UpdateSettingsPlot(), UpdateSettingsReftran(), and UpdateSettingsSegment().
UpdateSettingsImport()
void dynadjust::CDnaProjectFile::UpdateSettingsImport (const project_settings & p) inline
Definition at line 84 of file dnaprojectfile.hpp.
{
        UpdateSettingsGeneral(p.g);
        settings_.i = p.i;
    }
References project_settings::g, project_settings::i, settings_, and UpdateSettingsGeneral().
Referenced by main().
UpdateSettingsGeoid()
void dynadjust::CDnaProjectFile::UpdateSettingsGeoid (const project_settings & p) inline
Definition at line 88 of file dnaprojectfile.hpp.
{
        UpdateSettingsGeneral(p.g);
        settings_.n = p.n;
    }
References project_settings::g, project_settings::n, settings_, and UpdateSettingsGeneral().
Referenced by main().
UpdateSettingsReftran()
void dynadjust::CDnaProjectFile::UpdateSettingsReftran (const project_settings & p) inline
Definition at line 92 of file dnaprojectfile.hpp.
{
        UpdateSettingsGeneral(p.g);
        settings_.r = p.r;
    }
References project_settings::g, project_settings::r, settings_, and UpdateSettingsGeneral().
Referenced by main().
UpdateSettingsAdjust()
void dynadjust::CDnaProjectFile::UpdateSettingsAdjust (const project_settings & p) inline
Definition at line 96 of file dnaprojectfile.hpp.
{
        UpdateSettingsGeneral(p.g);
        settings_.a = p.a;
    }
References project_settings::a, project_settings::g, settings_, and UpdateSettingsGeneral().
Referenced by main().
UpdateSettingsSegment()
void dynadjust::CDnaProjectFile::UpdateSettingsSegment (const project_settings & p) inline
Definition at line 100 of file dnaprojectfile.hpp.
{
        UpdateSettingsGeneral(p.g);
        settings_.s = p.s;
    }
References project_settings::g, project_settings::s, settings_, and UpdateSettingsGeneral().
Referenced by main().
UpdateSettingsPlot()
void dynadjust::CDnaProjectFile::UpdateSettingsPlot (const project_settings & p) inline
Definition at line 104 of file dnaprojectfile.hpp.
{
        UpdateSettingsGeneral(p.g);
        settings_.p = p.p;
    }
References project_settings::g, project_settings::p, settings_, and UpdateSettingsGeneral().
UpdateSettingsOutput()
void dynadjust::CDnaProjectFile::UpdateSettingsOutput (const project_settings & p) inline
Definition at line 108 of file dnaprojectfile.hpp.
{
        UpdateSettingsGeneral(p.g);
        settings_.o = p.o;
    }
References project_settings::g, project_settings::o, settings_, and UpdateSettingsGeneral().
Referenced by main().
AddOptionValue()
template<typename T> void dynadjust::CDnaProjectFile::AddOptionValue (std::ostream & os, const char *const option, const T & value)
Definition at line 1618 of file dnaprojectfile.cpp.
{
    os << " --" << option << " " << value;
}
Referenced by FormCommandLineOptionsStringGeneral().
AddDefaultValue()
template<typename T> void dynadjust::CDnaProjectFile::AddDefaultValue (std::ostream & os, const T & value)
Definition at line 1623 of file dnaprojectfile.cpp.
{
    os << " " << value;
}
Referenced by FormCommandLineOptionsStringImport().
FormCommandLineOptionsStringImport()
std::string dynadjust::CDnaProjectFile::FormCommandLineOptionsStringImport ()
Definition at line 1650 of file dnaprojectfile.cpp.
{
    std::stringstream options;
    // General settings
    AddDefaultValue(options, FormCommandLineOptionsStringGeneral());
    // Import settings
    // files
    for (_it_vstr_const _it_tmp(settings_.i.input_files.begin());
        _it_tmp!=settings_.i.input_files.end(); ++_it_tmp)
        AddDefaultValue<std::string>(options,
            leafStr<std::string>(trimstr<std::string>(_it_tmp->c_str())));
    return options.str();
}
References AddDefaultValue(), FormCommandLineOptionsStringGeneral(), leafStr(), settings_, and trimstr().
FormCommandLineOptionsStringGeneral()
std::string dynadjust::CDnaProjectFile::FormCommandLineOptionsStringGeneral ()
Definition at line 1669 of file dnaprojectfile.cpp.
{
    std::stringstream options;
    // General settings
    // project file
    AddOptionValue<std::string>(options, PROJECT_FILE, settings_.g.project_file);
    // network name
    AddOptionValue<std::string>(options, NETWORK_NAME, settings_.g.network_name);
    // verbose
    AddOptionValue<UINT16>(options, VERBOSE, settings_.g.verbose);
    // verbose
    AddOptionValue<UINT16>(options, QUIET, settings_.g.quiet);
    return options.str();
}
References AddOptionValue(), NETWORK_NAME, PROJECT_FILE, QUIET, settings_, and VERBOSE.
Referenced by FormCommandLineOptionsStringImport().
InitialiseGeneralSettings()
void dynadjust::CDnaProjectFile::InitialiseGeneralSettings () private
Definition at line 300 of file dnaprojectfile.cpp.
{
    if (settings_.g.network_name.empty())
    {
        std::stringstream ss;
        ss << "The project file does not provide the network name. " << std::endl << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
}
References settings_.
Referenced by CDnaProjectFile(), InitialiseAdjustSettings(), InitialiseGeoidSettings(), InitialiseImportSettings(), InitialiseReftranSettings(), and InitialiseSegmentSettings().
InitialiseImportSettings()
void dynadjust::CDnaProjectFile::InitialiseImportSettings () private
Definition at line 310 of file dnaprojectfile.cpp.
{
    InitialiseGeneralSettings();
    if (settings_.i.input_files.empty() &&
        settings_.i.seg_file.empty())
    {
        std::stringstream ss;
        ss << "Nothing to do - the project file does not list any files to import. " << std::endl << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    std::string firstPart(settings_.g.output_folder + FOLDER_SLASH + settings_.g.network_name + ".");
    if (!settings_.i.bst_file.empty())
    {
        if (!boost::filesystem::exists(settings_.i.bst_file))
            // Does the file exist?  No.
            // Assume it is a filename contained in the input folder.
            // import will throw an exception if it cannot be found.
            settings_.i.bst_file = formPath<std::string>(settings_.g.input_folder,
                leafStr<std::string>(settings_.i.bst_file));
    }
    else
        settings_.i.bst_file = firstPart + "bst";  // binary stations file
    if (!settings_.i.bms_file.empty())
    {
        if (!boost::filesystem::exists(settings_.i.bms_file))
            // Does the file exist?  No.
            // Assume it is a filename contained in the input folder.
            // import will throw an exception if it cannot be found.
            settings_.i.bms_file = formPath<std::string>(settings_.g.input_folder,
                leafStr<std::string>(settings_.i.bms_file));
    }
    else
        settings_.i.bms_file = firstPart + "bms";  // binary measurements file
    settings_.i.asl_file = firstPart + "asl";  // associated stations list
    settings_.i.aml_file = firstPart + "aml";  // associated measurements list
    settings_.i.map_file = firstPart + "map";  // station names map
    settings_.i.dst_file = firstPart + "dst";  // fuplicate stations
    settings_.i.dms_file = firstPart + "dms";  // duplicate measurements
    settings_.i.imp_file = firstPart + "imp";  // log
    if (settings_.o._msr_to_stn == 1)
        settings_.o._m2s_file = firstPart + "m2s"; // measurement to stations table
    if (!settings_.i.seg_file.empty())
    {
        if (!boost::filesystem::exists(settings_.i.seg_file))
            // Does the file exist?  No.
            // Assume it is a filename contained in the input folder.
            // import will throw an exception if it cannot be found.
            settings_.i.seg_file = formPath<std::string>(settings_.g.input_folder,
                leafStr<std::string>(settings_.i.seg_file));
    }
    // GNSS scaling
    if (fabs(settings_.i.pscale - 1.0) > PRECISION_1E5 ||
        fabs(settings_.i.lscale - 1.0) > PRECISION_1E5 ||
        fabs(settings_.i.hscale - 1.0) > PRECISION_1E5 ||
        fabs(settings_.i.vscale - 1.0) > PRECISION_1E5 ||
        !settings_.i.scalar_file.empty())
        settings_.i.apply_scaling = 1;
    if (!settings_.i.scalar_file.empty())
    {
        if (!boost::filesystem::exists(settings_.i.scalar_file))
            // Does the file exist?  No.
            // Assume it is a filename contained in the input folder.
            // import will throw an exception if it cannot be found.
            settings_.i.scalar_file = formPath<std::string>(settings_.g.input_folder,
                leafStr<std::string>(settings_.i.scalar_file));
    }
    // Create file name based on the provided block
    std::string fileName(settings_.g.network_name);
    if (settings_.i.import_block)
    {
        std::stringstream blk("");
        blk << ".block-" << settings_.i.import_block_number;
        fileName += blk.str();
    }
    if (settings_.i.export_dynaml)
    {
        if (settings_.i.export_single_xml_file)
            settings_.i.xml_outfile = formPath<std::string>(settings_.g.output_folder,
                fileName, "xml");
        else
        {
            settings_.i.xml_stnfile = formPath<std::string>(settings_.g.output_folder,
                fileName + "stn", "xml");
            settings_.i.xml_msrfile = formPath<std::string>(settings_.g.output_folder,
                fileName + "msr", "xml");
        }
    }
    if (settings_.i.export_dna_files)
    {
        settings_.i.dna_stnfile = formPath<std::string>(settings_.g.output_folder,
            fileName, "stn");
        settings_.i.dna_msrfile = formPath<std::string>(settings_.g.output_folder,
            fileName, "msr");
    }
    if (settings_.i.simulate_measurements)
        settings_.i.simulate_msrfile = formPath<std::string>(settings_.g.output_folder,
            settings_.g.network_name, "simulated.msr");
}
References formPath(), InitialiseGeneralSettings(), leafStr(), PRECISION_1E5(), and settings_.
Referenced by CDnaProjectFile().
InitialiseReftranSettings()
void dynadjust::CDnaProjectFile::InitialiseReftranSettings () private
Definition at line 424 of file dnaprojectfile.cpp.
{
    InitialiseGeneralSettings();
    if (settings_.r.reference_frame.empty())
    {
        std::stringstream ss;
        ss << "Nothing to do - the project file does not specify a reference frame." << std::endl << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    std::string firstPart(settings_.g.output_folder + FOLDER_SLASH + settings_.g.network_name + ".");
    settings_.r.bst_file = firstPart + "bst";  // binary stations file
    settings_.r.bms_file = firstPart + "bms";  // binary measurements file
    settings_.r.rft_file = firstPart + "rft";  // log
    if (settings_.i.export_dynaml == 1)
    {
        if (settings_.i.export_single_xml_file == 1)
            settings_.i.xml_outfile = firstPart + "xml";       // single XML file
        else
        {
            settings_.i.xml_stnfile = formPath<std::string>(settings_.g.output_folder,
                settings_.g.network_name + "stn", "xml");
            settings_.i.xml_msrfile = formPath<std::string>(settings_.g.output_folder,
                settings_.g.network_name + "msr", "xml");;
        }
    }
    if (settings_.i.export_dna_files == 1)
    {
        settings_.i.dna_stnfile = firstPart + "stn";   // station file
        settings_.i.dna_msrfile = firstPart + "msr";   // measurement file
    }
    if (settings_.o._export_snx_file == 1)
        settings_.o._snx_file = firstPart + "snx";     // SINEX file
}
References formPath(), InitialiseGeneralSettings(), and settings_.
Referenced by CDnaProjectFile().
InitialiseGeoidSettings()
void dynadjust::CDnaProjectFile::InitialiseGeoidSettings () private
Definition at line 464 of file dnaprojectfile.cpp.
{
    InitialiseGeneralSettings();
    // Expected behaviour: when running geoid using a project file, network name must exist
    if (settings_.g.network_name.empty())
    {
        std::stringstream ss;
        ss << "Nothing to do - the project file does not provide a network name. " << std::endl << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    settings_.n.bst_file = formPath<std::string>(settings_.g.input_folder, settings_.g.network_name, "bst");        // binary stations file
    settings_.n.geo_file = formPath<std::string>(settings_.g.output_folder, settings_.g.network_name, "geo");   // dna geo file
    settings_.n.file_mode = 1;
    if (settings_.n.ntv2_geoid_file.empty())
    {
        std::stringstream ss;
        ss << "Nothing to do - the project file does not provide an NTv2 grid file path. " << std::endl << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
}
References formPath(), InitialiseGeneralSettings(), and settings_.
Referenced by CDnaProjectFile().
InitialiseSegmentSettings()
void dynadjust::CDnaProjectFile::InitialiseSegmentSettings () private
Definition at line 488 of file dnaprojectfile.cpp.
{
    InitialiseGeneralSettings();
    std::string firstPart(settings_.g.output_folder + FOLDER_SLASH + settings_.g.network_name + ".");
    settings_.s.bst_file = firstPart + "bst";  // binary stations file
    settings_.s.bms_file = firstPart + "bms";  // binary measurements file
    settings_.s.asl_file = firstPart + "asl";  // associated stations list
    settings_.s.aml_file = firstPart + "aml";  // associated measurements list
    settings_.s.map_file = firstPart + "map";  // station names map
    settings_.s.seg_file = firstPart + "seg";  // segmentation file
    settings_.s.sap_file = firstPart + "sap";  // station appearance file
}
References InitialiseGeneralSettings(), and settings_.
Referenced by CDnaProjectFile().
InitialiseAdjustSettings()
void dynadjust::CDnaProjectFile::InitialiseAdjustSettings () private
Definition at line 502 of file dnaprojectfile.cpp.
{
    InitialiseGeneralSettings();
    std::string firstPart(settings_.g.output_folder + FOLDER_SLASH + settings_.g.network_name + ".");
    settings_.a.bst_file = firstPart + "bst";  // binary stations file
    settings_.a.bms_file = firstPart + "bms";  // binary measurements file
    if (!boost::filesystem::exists(settings_.a.bst_file) || !boost::filesystem::exists(settings_.a.bms_file))
    {
        std::stringstream ss;
        ss << "- Nothing to do: ";
        if (settings_.g.network_name.empty())
            ss << std::endl << "network name has not been specified specified, and " << std::endl << "               ";
        ss << settings_.a.bst_file << " and " << settings_.a.bms_file << " do not exist." << std::endl << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    // Station appearance file
    settings_.a.seg_file = firstPart + "seg";  // segmentation file
    settings_.s.sap_file = firstPart + "sap";  // station appearance file
    settings_.s.asl_file = firstPart + "asl";  // associated stations list
    settings_.s.aml_file = firstPart + "aml";  // associated measurements list
    settings_.a.map_file = firstPart + "map";  // station names map
    // Set up file names dependent on adjustment mode
    settings_.o._xyz_file = settings_.o._adj_file =
        formPath<std::string>(settings_.g.output_folder, settings_.g.network_name);
    if (settings_.o._positional_uncertainty)
        settings_.o._apu_file = settings_.o._adj_file;
    if (settings_.o._init_stn_corrections)
        settings_.o._cor_file = settings_.o._adj_file;
    switch (settings_.a.adjust_mode)
    {
    case Phased_Block_1Mode:
    case PhasedMode:
        settings_.o._adj_file += ".phased";
        settings_.o._xyz_file += ".phased";
        if (settings_.o._positional_uncertainty)
            settings_.o._apu_file += ".phased";
        if (settings_.o._init_stn_corrections)
            settings_.o._cor_file += ".phased";
        if (settings_.a.adjust_mode == Phased_Block_1Mode)
        {
            settings_.o._adj_file += "-block1";
            settings_.o._xyz_file += "-block1";
            if (settings_.o._positional_uncertainty)
                settings_.o._apu_file += "-block1";
            if (settings_.o._init_stn_corrections)
                settings_.o._cor_file += "-block1";
        }
        else if (settings_.a.stage)
        {
            settings_.o._adj_file += "-stage";
            settings_.o._xyz_file += "-stage";
            if (settings_.o._positional_uncertainty)
                settings_.o._apu_file += "-stage";
            if (settings_.o._init_stn_corrections)
                settings_.o._cor_file += "-stage";
        }
        else if (settings_.a.multi_thread)
        {
            settings_.o._adj_file += "-mt";
            settings_.o._xyz_file += "-mt";
            if (settings_.o._positional_uncertainty)
                settings_.o._apu_file += "-mt";
            if (settings_.o._init_stn_corrections)
                settings_.o._cor_file += "-mt";
        }
        break;
    case SimultaneousMode:
        settings_.o._adj_file += ".simult";
        settings_.o._xyz_file += ".simult";
        if (settings_.o._positional_uncertainty)
            settings_.o._apu_file += ".simult";
        if (settings_.o._init_stn_corrections)
            settings_.o._cor_file += ".simult";
        break;
    }
    settings_.o._adj_file += ".adj";
    settings_.o._xyz_file += ".xyz";
    if (settings_.o._positional_uncertainty)
        settings_.o._apu_file += ".apu";
    if (settings_.o._init_stn_corrections)
        settings_.o._cor_file += ".cor";
    if (settings_.a.fixed_std_dev < 0.)
        settings_.a.fixed_std_dev = PRECISION_1E6;
    else if (settings_.a.fixed_std_dev < PRECISION_1E10)
        settings_.a.fixed_std_dev = PRECISION_1E6;
    if (settings_.a.free_std_dev < 0.)
        settings_.a.free_std_dev = 10.0;
    else if (settings_.a.free_std_dev < PRECISION_1E10)
        settings_.a.free_std_dev = 10.0;
}
References formPath(), InitialiseGeneralSettings(), Phased_Block_1Mode, PhasedMode, PRECISION_1E10(), PRECISION_1E6(), settings_, and SimultaneousMode.
Referenced by CDnaProjectFile().
LoadSettingGeneral()
void dynadjust::CDnaProjectFile::LoadSettingGeneral (const settingMode mSetting, const std::string & var, std::string & val) private
Definition at line 620 of file dnaprojectfile.cpp.
{
    // general settings
    if (boost::iequals(var, QUIET))
    {
        if (val.empty())
            return;
        settings_.g.quiet = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, VERBOSE))
    {
        if (val.empty())
            return;
        settings_.g.verbose = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, PROJECT_FILE))
    {
        if (val.empty())
            return;
        settings_.g.project_file = val;
    }
    else if (boost::iequals(var, DYNADJUST_LOG_FILE))
    {
        if (val.empty())
            return;
        settings_.g.log_file = val;
    }
    else if (boost::iequals(var, NETWORK_NAME))
    {
        if (val.empty())
            return;
        string_string_pair t;
        switch (mSetting)
        {
        case switchSetting:
            t.first = var.c_str();
            t.second = val.substr(0,4).c_str();
            t.second = trimstr(t.second);
            if (t.second.substr(0,2) == "${" && t.second.at(3) == '}')
            {
                settings_.g.variables.push_back(t);
                std::sort(settings_.g.variables.begin(), settings_.g.variables.end(), PairCompareFirst<std::string, std::string>());
            }
            break;
        case generalSetting:
            settings_.g.network_name = val;
            break;
        default:
            break;
        }
    }
    else if (boost::iequals(var, INPUT_FOLDER))
    {
        if (val.empty())
            return;
        settings_.g.input_folder = val;
    }
    else if (boost::iequals(var, OUTPUT_FOLDER))
    {
        if (val.empty())
            return;
        settings_.g.output_folder = val;
    }
}
References DYNADJUST_LOG_FILE, generalSetting, INPUT_FOLDER, NETWORK_NAME, OUTPUT_FOLDER, PROJECT_FILE, QUIET, settings_, switchSetting, trimstr(), VERBOSE, and yesno_uint().
Referenced by LoadProjectFile().
LoadSettingImport()
void dynadjust::CDnaProjectFile::LoadSettingImport (const settingMode mSetting, const std::string & var, std::string & val) private
Definition at line 686 of file dnaprojectfile.cpp.
{
    // Import settings
    if (boost::iequals(var, IMPORT_FILE))
    {
        if (val.empty())
            return;
        settings_.i.input_files.push_back(formPath<std::string>(settings_.g.input_folder, val));
    }
    else if (boost::iequals(var, REFERENCE_FRAME))
    {
        if (val.empty())
            return;
        settings_.i.reference_frame = val;
    }
    else if (boost::iequals(var, EPOCH))
    {
        if (val.empty())
            return;
        settings_.i.epoch = val;
    }
    else if (boost::iequals(var, OVERRIDE_INPUT_FRAME))
    {
        if (val.empty())
            return;
        settings_.i.override_input_rfame = yesno_uint<UINT16, std::string>(val);;
    }
    else if (boost::iequals(var, IMPORT_GEO_FILE))
    {
        if (val.empty())
            return;
        settings_.i.geo_file = formPath<std::string>(settings_.g.input_folder, val);
        settings_.i.import_geo_file = 1;
    }
    else if (boost::iequals(var, BIN_STN_FILE))
    {
        string_string_pair t;
        switch (mSetting)
        {
        case switchSetting:
            if (val.empty())
                return;
            t.first = var.c_str();
            t.second = val.substr(0,4).c_str();
            t.second = trimstr(t.second);
            if (t.second.substr(0,2) == "${" && t.second.at(3) == '}')
            {
                settings_.g.variables.push_back(t);
                std::sort(settings_.g.variables.begin(), settings_.g.variables.end(), PairCompareFirst<std::string, std::string>());
            }
            break;
        case importSetting:
            if (val.empty())
                // default export bst file - create in output folder
                settings_.i.bst_file = formPath<std::string>(settings_.g.output_folder, settings_.g.network_name, "bst");   // binary stations file
            else
                // user specified bst file - look in input folder
                settings_.i.bst_file = formPath<std::string>(settings_.g.input_folder, val);
            break;
        default:
            break;
        }
    }
    else if (boost::iequals(var, BIN_MSR_FILE))
    {
        string_string_pair t;
        switch (mSetting)
        {
        case switchSetting:
            if (val.empty())
                return;
            t.first = var.c_str();
            t.second = val.substr(0,4).c_str();
            t.second = trimstr(t.second);
            if (t.second.substr(0,2) == "${" && t.second.at(3) == '}')
            {
                settings_.g.variables.push_back(t);
                std::sort(settings_.g.variables.begin(), settings_.g.variables.end(), PairCompareFirst<std::string, std::string>());
            }
            break;
        case importSetting:
            if (val.empty())
                settings_.i.bms_file = formPath<std::string>(settings_.g.output_folder, settings_.g.network_name, "bms");   // binary stations file
            else
                settings_.i.bms_file = formPath<std::string>(settings_.g.input_folder, val);
            break;
        default:
            break;
        }
    }
    else if (boost::iequals(var, DNA_MAP_FILE))
    {
        if (val.empty())
            return;
        string_string_pair t;
        switch (mSetting)
        {
        case switchSetting:
            t.first = var.c_str();
            t.second = val.substr(0,4).c_str();
            t.second = trimstr(t.second);
            if (t.second.substr(0,2) == "${" && t.second.at(3) == '}')
            {
                settings_.g.variables.push_back(t);
                std::sort(settings_.g.variables.begin(), settings_.g.variables.end(), PairCompareFirst<std::string, std::string>());
            }
            break;
        case importSetting:
            settings_.i.map_file = formPath<std::string>(settings_.g.output_folder, val);
            break;
        default:
            break;
        }
    }
    else if (boost::iequals(var, ASL_FILE))
    {
        if (val.empty())
            return;
        string_string_pair t;
        switch (mSetting)
        {
        case switchSetting:
            t.first = var.c_str();
            t.second = val.substr(0,4).c_str();
            t.second = trimstr(t.second);
            if (t.second.substr(0,2) == "${" && t.second.at(3) == '}')
            {
                settings_.g.variables.push_back(t);
                std::sort(settings_.g.variables.begin(), settings_.g.variables.end(), PairCompareFirst<std::string, std::string>());
            }
            break;
        case importSetting:
            settings_.i.asl_file = formPath<std::string>(settings_.g.output_folder, val);
            break;
        default:
            break;
        }
    }
    else if (boost::iequals(var, AML_FILE))
    {
        if (val.empty())
            return;
        string_string_pair t;
        switch (mSetting)
        {
        case switchSetting:
            t.first = var.c_str();
            t.second = val.substr(0,4).c_str();
            t.second = trimstr(t.second);
            if (t.second.substr(0,2) == "${" && t.second.at(3) == '}')
            {
                settings_.g.variables.push_back(t);
                std::sort(settings_.g.variables.begin(), settings_.g.variables.end(), PairCompareFirst<std::string, std::string>());
            }
            break;
        case importSetting:
            settings_.i.aml_file = formPath<std::string>(settings_.g.output_folder, val);
            break;
        default:
            break;
        }
    }
    else if (boost::iequals(var, DST_FILE))
    {
        if (val.empty())
            return;
        settings_.i.dst_file = formPath<std::string>(settings_.g.output_folder, val);
    }
    else if (boost::iequals(var, DMS_FILE))
    {
        if (val.empty())
            return;
        settings_.i.dms_file = formPath<std::string>(settings_.g.output_folder, val);
    }
    else if (boost::iequals(var, BOUNDING_BOX))
    {
        if (val.empty())
            return;
        settings_.i.bounding_box = val;
    }
    else if (boost::iequals(var, GET_MSRS_TRANSCENDING_BOX))
    {
        if (val.empty())
            return;
        settings_.i.include_transcending_msrs = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, INCLUDE_STN_ASSOC_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.stn_associated_msr_include = valorno_string<std::string>(val);
    }
    else if (boost::iequals(var, EXCLUDE_STN_ASSOC_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.stn_associated_msr_exclude = valorno_string<std::string>(val);
    }
    else if (boost::iequals(var, SPLIT_CLUSTERS))
    {
        if (val.empty())
            return;
        settings_.i.split_clusters = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, IMPORT_SEG_BLOCK))
    {
        if (val.empty())
            return;
        settings_.i.import_block_number = valorno_uint<UINT16, std::string>(val, settings_.i.import_block);
    }
    else if (boost::iequals(var, SEG_FILE))
    {
        if (val.empty())
            return;
        settings_.i.seg_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, PREFER_X_MSR_AS_G))
    {
        if (val.empty())
            return;
        settings_.i.prefer_single_x_as_g = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, INCLUDE_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.include_msrs = val;
    }
    else if (boost::iequals(var, EXCLUDE_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.exclude_msrs = val;
    }
    else if (boost::iequals(var, STATION_RENAMING_FILE))
    {
        if (val.empty())
            return;
        settings_.i.stn_renamingfile = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, STATION_DISCONTINUITY_FILE))
    {
        if (val.empty())
            return;
        settings_.i.stn_discontinuityfile = formPath<std::string>(settings_.g.input_folder, val);
        settings_.i.apply_discontinuities = true;
    }
    else if (boost::iequals(var, TEST_NEARBY_STNS))
    {
        if (val.empty())
            return;
        settings_.i.search_nearby_stn = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, TEST_NEARBY_STN_DIST))
    {
        if (val.empty())
            return;
        settings_.i.search_stn_radius = DoubleFromString<double>(val);
    }
    else if (boost::iequals(var, TEST_SIMILAR_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.search_similar_msr = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, TEST_SIMILAR_GNSS_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.search_similar_msr_gx = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, IGNORE_INSUFFICIENT_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.ignore_insufficient_msrs = yesno_uint<UINT16, std::string>(val);
        }
    else if (boost::iequals(var, IGNORE_SIMILAR_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.ignore_similar_msr = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, REMOVE_IGNORED_MSRS))
    {
        if (val.empty())
            return;
        settings_.i.remove_ignored_msr = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, FLAG_UNUSED_STNS))
    {
        if (val.empty())
            return;
        settings_.i.flag_unused_stn = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, TEST_INTEGRITY))
    {
        if (val.empty())
            return;
        settings_.i.test_integrity = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, VSCALE))
    {
        if (val.empty())
            return;
        settings_.i.vscale = DoubleFromString<double>(val);
    }
    else if (boost::iequals(var, PSCALE))
    {
        if (val.empty())
            return;
        settings_.i.pscale = DoubleFromString<double>(val);
    }
    else if (boost::iequals(var, LSCALE))
    {
        if (val.empty())
            return;
        settings_.i.lscale = DoubleFromString<double>(val);
    }
    else if (boost::iequals(var, HSCALE))
    {
        if (val.empty())
            return;
        settings_.i.hscale = DoubleFromString<double>(val);
    }
    else if (boost::iequals(var, SCALAR_FILE))
    {
        if (val.empty())
            return;
        settings_.i.scalar_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, EXPORT_XML_FILES))
    {
        if (val.empty())
            return;
        settings_.i.export_dynaml = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_SINGLE_XML_FILE))
    {
        if (val.empty())
            return;
        settings_.i.export_single_xml_file = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_FROM_BINARY))
    {
        if (val.empty())
            return;
        settings_.i.export_from_bfiles = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_DNA_FILES))
    {
        if (val.empty())
            return;
        settings_.i.export_dna_files = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_ASL_FILE))
    {
        if (val.empty())
            return;
        settings_.i.export_asl_file = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_AML_FILE))
    {
        if (val.empty())
            return;
        settings_.i.export_aml_file = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_MAP_FILE))
    {
        if (val.empty())
            return;
        settings_.i.export_map_file = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, SIMULATE_MSR_FILE))
    {
        if (val.empty())
            return;
        settings_.i.simulate_measurements = yesno_uint<UINT16, std::string>(val);
    }
    //else if (boost::iequals(var, VERIFY_COORDS))
    //{
    //  if (val.empty())
    //      return;
    //  settings_.i.verify_coordinates = boost::lexical_cast<UINT16, std::string>(val);
    //}
}
References AML_FILE, ASL_FILE, BIN_MSR_FILE, BIN_STN_FILE, BOUNDING_BOX, DMS_FILE, DNA_MAP_FILE, DoubleFromString(), DST_FILE, EPOCH, EXCLUDE_MSRS, EXCLUDE_STN_ASSOC_MSRS, EXPORT_AML_FILE, EXPORT_ASL_FILE, EXPORT_DNA_FILES, EXPORT_FROM_BINARY, EXPORT_MAP_FILE, EXPORT_SINGLE_XML_FILE, EXPORT_XML_FILES, FLAG_UNUSED_STNS, formPath(), GET_MSRS_TRANSCENDING_BOX, HSCALE, IGNORE_INSUFFICIENT_MSRS, IGNORE_SIMILAR_MSRS, IMPORT_FILE, IMPORT_GEO_FILE, IMPORT_SEG_BLOCK, importSetting, INCLUDE_MSRS, INCLUDE_STN_ASSOC_MSRS, LSCALE, OVERRIDE_INPUT_FRAME, PREFER_X_MSR_AS_G, PSCALE, REFERENCE_FRAME, REMOVE_IGNORED_MSRS, SCALAR_FILE, SEG_FILE, settings_, SIMULATE_MSR_FILE, SPLIT_CLUSTERS, STATION_DISCONTINUITY_FILE, STATION_RENAMING_FILE, switchSetting, TEST_INTEGRITY, TEST_NEARBY_STN_DIST, TEST_NEARBY_STNS, TEST_SIMILAR_GNSS_MSRS, TEST_SIMILAR_MSRS, trimstr(), valorno_string(), valorno_uint(), VSCALE, and yesno_uint().
Referenced by LoadProjectFile().
LoadSettingReftran()
void dynadjust::CDnaProjectFile::LoadSettingReftran (const std::string & var, std::string & val) private
Definition at line 1074 of file dnaprojectfile.cpp.
{
    if (boost::iequals(var, REFERENCE_FRAME))
    {
        if (val.empty())
            return;
        settings_.r.reference_frame = val;
    }
    else if (boost::iequals(var, EPOCH))
    {
        if (val.empty())
            return;
        settings_.r.epoch = val;
    }
    else if (boost::iequals(var, TECTONIC_PLATE_MODEL_OPTION))
    {
        if (val.empty())
            return;
        settings_.r.plate_model_option = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, TECTONIC_PLATE_BDY_FILE))
    {
        if (val.empty())
            return;
        settings_.r.tpb_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.r.tpb_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, TECTONIC_PLATE_POLE_FILE))
    {
        if (val.empty())
            return;
        settings_.r.tpp_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.r.tpp_file = formPath<std::string>(settings_.g.input_folder, val);
    }
}
References EPOCH, formPath(), REFERENCE_FRAME, settings_, TECTONIC_PLATE_BDY_FILE, TECTONIC_PLATE_MODEL_OPTION, and TECTONIC_PLATE_POLE_FILE.
Referenced by LoadProjectFile().
LoadSettingGeoid()
void dynadjust::CDnaProjectFile::LoadSettingGeoid (const std::string & var, std::string & val) private
Definition at line 1116 of file dnaprojectfile.cpp.
{
    if (boost::iequals(var, DAT_FILEPATH))
    {
        if (val.empty())
            return;
        settings_.n.rdat_geoid_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, NTV2_FILEPATH))
    {
        if (val.empty())
            return;
        settings_.n.ntv2_geoid_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.n.ntv2_geoid_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, INPUT_FILE))
    {
        if (val.empty())
            return;
        settings_.n.input_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    //else if (boost::iequals(var, BIN_STN_FILE))
    //{
    //  if (val.empty())
    //      return;
    //  settings_.n.bst_file = formPath<std::string>(settings_.g.input_folder, val);
    //}
    else if (boost::iequals(var, METHOD))
    {
        if (val.empty())
            return;
        settings_.n.interpolation_method = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, DDEG_FORMAT))
    {
        if (val.empty())
            return;
        settings_.n.coordinate_format = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, DIRECTION))
    {
        if (val.empty())
            return;
        settings_.n.ellipsoid_to_ortho = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, CONVERT_BST_HT))
    {
        if (val.empty())
            return;
        settings_.n.convert_heights = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_GEO_FILE))
    {
        if (val.empty())
            return;
        settings_.n.export_dna_geo_file = yesno_uint<UINT16, std::string>(val);
    }
}
References CONVERT_BST_HT, DAT_FILEPATH, DDEG_FORMAT, DIRECTION, EXPORT_GEO_FILE, formPath(), INPUT_FILE, METHOD, NTV2_FILEPATH, settings_, and yesno_uint().
Referenced by LoadProjectFile().
LoadSettingSegment()
void dynadjust::CDnaProjectFile::LoadSettingSegment (const std::string & var, std::string & val) private
Definition at line 1178 of file dnaprojectfile.cpp.
{
    if (boost::iequals(var, NET_FILE))
    {
        if (val.empty())
            return;
        settings_.s.net_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, SEG_FILE))
    {
        if (val.empty())
            return;
        settings_.s.seg_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.s.seg_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, BIN_STN_FILE))
    {
        if (val.empty())
            return;
        settings_.s.bst_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.s.bst_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, BIN_MSR_FILE))
    {
        if (val.empty())
            return;
        settings_.s.bms_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.s.bms_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, SEG_MIN_INNER_STNS))
    {
        if (val.empty())
            return;
        settings_.s.min_inner_stations = boost::lexical_cast<UINT32, std::string>(val);
    }
    else if (boost::iequals(var, SEG_THRESHOLD_STNS))
    {
        if (val.empty())
            return;
        settings_.s.max_total_stations = boost::lexical_cast<UINT32, std::string>(val);
    }
    else if (boost::iequals(var, SEG_FORCE_CONTIGUOUS))
    {
        if (val.empty())
            return;
        settings_.s.force_contiguous_blocks = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, SEG_STARTING_STN))
    {
        if (val.empty())
            return;
        settings_.s.seg_starting_stns = val;
    }
    else if (boost::iequals(var, SEG_SEARCH_LEVEL))
    {
        if (val.empty())
            return;
        settings_.s.seg_search_level = boost::lexical_cast<UINT16, std::string>(val);
    }
}
References BIN_MSR_FILE, BIN_STN_FILE, formPath(), NET_FILE, SEG_FILE, SEG_FORCE_CONTIGUOUS, SEG_MIN_INNER_STNS, SEG_SEARCH_LEVEL, SEG_STARTING_STN, SEG_THRESHOLD_STNS, settings_, and yesno_uint().
Referenced by LoadProjectFile().
LoadSettingAdjust()
void dynadjust::CDnaProjectFile::LoadSettingAdjust (const std::string & var, std::string & val) private
Definition at line 1248 of file dnaprojectfile.cpp.
{
    if (boost::iequals(var, BIN_STN_FILE))
    {
        if (val.empty())
            return;
        settings_.a.bst_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.a.bst_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, BIN_MSR_FILE))
    {
        if (val.empty())
            return;
        settings_.a.bms_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.a.bms_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, SEG_FILE))
    {
        if (val.empty())
            return;
        settings_.a.seg_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.a.seg_file = formPath<std::string>(settings_.g.input_folder, val);
    }
    else if (boost::iequals(var, COMMENTS))
    {
        if (val.empty())
            return;
        settings_.a.comments = val;
    }
    if (boost::iequals(var, ADJUSTMENT_MODE))
    {
        if (val.empty())
            return;
        if (boost::iequals(val, MODE_SIMULTANEOUS))
        {
            settings_.a.adjust_mode = SimultaneousMode;
            settings_.a.multi_thread = false;
            settings_.a.stage = false;
        }
        else if (boost::iequals(val, MODE_PHASED))
        {
            settings_.a.adjust_mode = PhasedMode;
        }
        else if (boost::iequals(val, MODE_PHASED_BLOCK1))
        {
            settings_.a.adjust_mode = Phased_Block_1Mode;
            settings_.a.multi_thread = false;
        }
        else if (boost::iequals(val, MODE_SIMULATION))
        {
            settings_.a.adjust_mode = SimulationMode;
            settings_.a.multi_thread = false;
            settings_.a.stage = false;
        }
    }
    else if (boost::iequals(var, MODE_PHASED_MT))
    {
        if (val.empty())
            return;
        settings_.a.multi_thread = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, STAGED_ADJUSTMENT))
    {
        if (val.empty())
            return;
        settings_.a.stage = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, CONF_INTERVAL))
    {
        if (val.empty())
            return;
        settings_.a.confidence_interval = FloatFromString<float>(val);
    }
    else if (boost::iequals(var, ITERATION_THRESHOLD))
    {
        if (val.empty())
            return;
        settings_.a.iteration_threshold = FloatFromString<float>(val);
    }
    else if (boost::iequals(var, MAX_ITERATIONS))
    {
        if (val.empty())
            return;
        settings_.a.max_iterations = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, STN_CONSTRAINTS))
    {
        if (val.empty())
            return;
        settings_.a.station_constraints = val;
    }
    else if (boost::iequals(var, FREE_STN_SD))
    {
        if (val.empty())
            return;
        settings_.a.free_std_dev = DoubleFromString<double>(val);
    }
    else if (boost::iequals(var, FIXED_STN_SD))
    {
        if (val.empty())
            return;
        settings_.a.fixed_std_dev = DoubleFromString<double>(val);
    }
    //else if (boost::iequals(var, LSQ_INVERSE_METHOD))
    //{
    //  if (val.empty())
    //      return;
    //  settings_.a.inverse_method_lsq = boost::lexical_cast<UINT16, std::string>(val);
    //}
    else if (boost::iequals(var, SCALE_NORMAL_UNITY))
    {
        if (val.empty())
            return;
        settings_.a.scale_normals_to_unity = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, RECREATE_STAGE_FILES))
    {
        if (val.empty())
            return;
        settings_.a.recreate_stage_files = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, PURGE_STAGE_FILES))
    {
        if (val.empty())
            return;
        settings_.a.purge_stage_files = yesno_uint<UINT16, std::string>(val) == 1;
    }
    else if (boost::iequals(var, TYPE_B_GLOBAL))
    {
        if (val.empty())
            return;
        settings_.a.type_b_global = val;
    }
    else if (boost::iequals(var, TYPE_B_FILE))
    {
        if (val.empty())
            return;
        settings_.a.type_b_file = val;
        if (!boost::filesystem::exists(val))
            if (boost::filesystem::exists(formPath<std::string>(settings_.g.input_folder, val)))
                settings_.a.type_b_file = formPath<std::string>(settings_.g.input_folder, val);
    }
}
References ADJUSTMENT_MODE, BIN_MSR_FILE, BIN_STN_FILE, COMMENTS, CONF_INTERVAL, DoubleFromString(), FIXED_STN_SD, FloatFromString(), formPath(), FREE_STN_SD, ITERATION_THRESHOLD, MAX_ITERATIONS, MODE_PHASED, MODE_PHASED_BLOCK1, MODE_PHASED_MT, MODE_SIMULATION, MODE_SIMULTANEOUS, Phased_Block_1Mode, PhasedMode, PURGE_STAGE_FILES, RECREATE_STAGE_FILES, SCALE_NORMAL_UNITY, SEG_FILE, settings_, SimulationMode, SimultaneousMode, STAGED_ADJUSTMENT, STN_CONSTRAINTS, TYPE_B_FILE, TYPE_B_GLOBAL, and yesno_uint().
Referenced by LoadProjectFile().
LoadSettingOutput()
void dynadjust::CDnaProjectFile::LoadSettingOutput (const std::string & var, std::string & val) private
Definition at line 1404 of file dnaprojectfile.cpp.
{
    if (boost::iequals(var, OUTPUT_MSR_TO_STN))
    {
        if (val.empty())
            return;
        settings_.o._msr_to_stn = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_MSR_TO_STN_SORTBY))
    {
        if (val.empty())
            return;
        settings_.o._sort_msr_to_stn = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_STN_ITER))
    {
        if (val.empty())
            return;
        settings_.o._adj_stn_iteration = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_STAT_ITER))
    {
        if (val.empty())
            return;
        settings_.o._adj_stat_iteration = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_MSR_ITER))
    {
        if (val.empty())
            return;
        settings_.o._adj_msr_iteration = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_CMP_MSR_ITER))
    {
        if (val.empty())
            return;
        settings_.o._cmp_msr_iteration = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_MSR))
    {
        if (val.empty())
            return;
        settings_.o._adj_msr_final = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_GNSS_UNITS))
    {
        if (val.empty())
            return;
        settings_.o._adj_gnss_units = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_MSR_TSTAT))
    {
        if (val.empty())
            return;
        settings_.o._adj_msr_tstat = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_MSR_SORTBY))
    {
        if (val.empty())
            return;
        settings_.o._sort_adj_msr = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_MSR_DBID))
    {
        if (val.empty())
            return;
        settings_.o._database_ids = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_STN_BLOCKS))
    {
        if (val.empty())
            return;
        settings_.o._output_stn_blocks = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_MSR_BLOCKS))
    {
        if (val.empty())
            return;
        settings_.o._output_msr_blocks = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ADJ_STN_SORT_ORDER))
    {
        if (val.empty())
            return;
        settings_.o._sort_stn_file_order = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_STN_COORD_TYPES))
    {
        if (val.empty())
            return;
        settings_.o._stn_coord_types = val;
    }
    else if (boost::iequals(var, OUTPUT_ANGULAR_TYPE_STN))
    {
        if (val.empty())
            return;
        settings_.o._angular_type_stn = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_STN_CORR))
    {
        if (val.empty())
            return;
        settings_.o._stn_corr = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_PRECISION_METRES_STN))
    {
        if (val.empty())
            return;
        settings_.o._precision_metres_stn = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_PRECISION_SECONDS_STN))
    {
        if (val.empty())
            return;
        settings_.o._precision_seconds_stn = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_PRECISION_METRES_MSR))
    {
        if (val.empty())
            return;
        settings_.o._precision_metres_msr = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_PRECISION_SECONDS_MSR))
    {
        if (val.empty())
            return;
        settings_.o._precision_seconds_msr = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_ANGULAR_TYPE_MSR))
    {
        if (val.empty())
            return;
        settings_.o._angular_type_msr = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_DMS_FORMAT_MSR))
    {
        if (val.empty())
            return;
        settings_.o._dms_format_msr = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_POS_UNCERTAINTY))
    {
        if (val.empty())
            return;
        settings_.o._positional_uncertainty = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_APU_CORRELATIONS))
    {
        if (val.empty())
            return;
        settings_.o._output_pu_covariances = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_APU_UNITS))
    {
        if (val.empty())
            return;
        settings_.o._apu_vcv_units = boost::lexical_cast<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, OUTPUT_STN_COR_FILE))
    {
        if (val.empty())
            return;
        settings_.o._init_stn_corrections = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, HZ_CORR_THRESHOLD))
    {
        if (val.empty())
            return;
        settings_.o._hz_corr_threshold = DoubleFromString<double>(val);
    }
    else if (boost::iequals(var, VT_CORR_THRESHOLD))
    {
        if (val.empty())
            return;
        settings_.o._vt_corr_threshold = DoubleFromString<double>(val);
    }
    //else if (boost::iequals(var, UPDATE_ORIGINAL_STN_FILE))
    //{
    //  if (val.empty())
    //      return;
    //  settings_.o. = yesno_uint<UINT16, std::string>(val);
    //}
    else if (boost::iequals(var, EXPORT_XML_STN_FILE))
    {
        if (val.empty())
            return;
        settings_.o._export_xml_stn_file= yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_DNA_STN_FILE))
    {
        if (val.empty())
            return;
        settings_.o._export_dna_stn_file = yesno_uint<UINT16, std::string>(val);
    }
    else if (boost::iequals(var, EXPORT_SNX_FILE))
    {
        if (val.empty())
            return;
        settings_.o._export_snx_file = yesno_uint<UINT16, std::string>(val);
    }
    // ???
    // EXPORT_DISCONT_FILE = "export-discont-file";
}
References DoubleFromString(), EXPORT_DNA_STN_FILE, EXPORT_SNX_FILE, EXPORT_XML_STN_FILE, HZ_CORR_THRESHOLD, OUTPUT_ADJ_GNSS_UNITS, OUTPUT_ADJ_MSR, OUTPUT_ADJ_MSR_BLOCKS, OUTPUT_ADJ_MSR_DBID, OUTPUT_ADJ_MSR_ITER, OUTPUT_ADJ_MSR_SORTBY, OUTPUT_ADJ_MSR_TSTAT, OUTPUT_ADJ_STAT_ITER, OUTPUT_ADJ_STN_BLOCKS, OUTPUT_ADJ_STN_ITER, OUTPUT_ADJ_STN_SORT_ORDER, OUTPUT_ANGULAR_TYPE_MSR, OUTPUT_ANGULAR_TYPE_STN, OUTPUT_APU_CORRELATIONS, OUTPUT_APU_UNITS, OUTPUT_CMP_MSR_ITER, OUTPUT_DMS_FORMAT_MSR, OUTPUT_MSR_TO_STN, OUTPUT_MSR_TO_STN_SORTBY, OUTPUT_POS_UNCERTAINTY, OUTPUT_PRECISION_METRES_MSR, OUTPUT_PRECISION_METRES_STN, OUTPUT_PRECISION_SECONDS_MSR, OUTPUT_PRECISION_SECONDS_STN, OUTPUT_STN_COORD_TYPES, OUTPUT_STN_COR_FILE, OUTPUT_STN_CORR, settings_, VT_CORR_THRESHOLD, and yesno_uint().
Referenced by LoadProjectFile().
Member Data Documentation
settings_
project_settings dynadjust::CDnaProjectFile::settings_ private
Definition at line 139 of file dnaprojectfile.hpp.
Referenced by FormCommandLineOptionsStringGeneral(), FormCommandLineOptionsStringImport(), GetSettings(), InitialiseAdjustSettings(), InitialiseGeneralSettings(), InitialiseGeoidSettings(), InitialiseImportSettings(), InitialiseReftranSettings(), InitialiseSegmentSettings(), LoadProjectFile(), LoadProjectFile(), LoadSettingAdjust(), LoadSettingGeneral(), LoadSettingGeoid(), LoadSettingImport(), LoadSettingOutput(), LoadSettingReftran(), LoadSettingSegment(), PrintProjectFile(), UpdateSettingsAdjust(), UpdateSettingsGeneral(), UpdateSettingsGeoid(), UpdateSettingsImport(), UpdateSettingsOutput(), UpdateSettingsPlot(), UpdateSettingsReftran(), and UpdateSettingsSegment().
The documentation for this class was generated from the following files:
include/config/dnaprojectfile.hpp
include/config/dnaprojectfile.cpp