DynAdjust: dynadjust::measurements::CDnaHeight Class Reference
dynadjust::measurements::CDnaHeight Class Reference
#include <dnaheight.hpp>
Public Member Functions
CDnaHeight (void)
virtual ~CDnaHeight (void)
bool operator== (const CDnaHeight &rhs) const
bool operator< (const CDnaHeight &rhs) const
double GetValue () const
double GetStdDev () const
void SetValue (const std::string &str)
void SetStdDev (const std::string &str)
virtual UINT32 CalcBinaryRecordCount () const
virtual void WriteBinaryMsr (std::ofstream *binary_stream, PUINT32 msrIndex) const
virtual UINT32 SetMeasurementRec (const vstn_t &binaryStn, it_vmsr_t &it_msr, it_vdbid_t &dbidmap)
virtual void WriteDynaMLMsr (std::ofstream *dynaml_stream, const std::string &comment, bool) const
virtual void WriteDNAMsr (std::ofstream *dna_stream, const dna_msr_fields &dmw, const dna_msr_fields &dml, bool) const
virtual void SimulateMsr (vdnaStnPtr *vStations, const CDnaEllipsoid *ellipsoid)
Public Member Functions inherited from dynadjust::measurements::CDnaMeasurement
CDnaMeasurement ()
virtual ~CDnaMeasurement ()
CDnaMeasurement (CDnaMeasurement &&m)
CDnaMeasurement & operator= (CDnaMeasurement &&rhs)
std::string GetType () const
char GetTypeC () const
bool GetIgnore () const
bool NotIgnored () const
std::string GetFirst () const
MEASUREMENT_STATIONS GetMsrStnCount () const
std::string GetEpsg () const
std::string GetSource () const
bool GetInsufficient () const
void SetType (const std::string &str)
void SetIgnore (const bool bval)
void SetFirst (const std::string &str)
void SetEpsg (const std::string &e)
void SetSource (const std::string &source)
void SetInsufficient (const bool bval)
void SetMsrIndex (const UINT32 &order)
void SetStn1Index (const UINT32 &order)
void SetStn2Index (const UINT32 &order)
void SetStn3Index (const UINT32 &order)
UINT32 GetMsrIndex () const
UINT32 GetStn1Index () const
UINT32 GetStn2Index () const
UINT32 GetStn3Index () const
double GetMeasAdj () const
double GetMeasCorr () const
double GetMeasAdjPrec () const
double GetResidualPrec () const
double GetPreAdjCorr () const
virtual void PopulateMsr (pvstn_t, uint32_uint32_map *, vUINT32 *, const UINT32 &, const CDnaDatum *, math::matrix_2d *, math::matrix_2d *)
virtual UINT32 GetClusterID () const
virtual std::string GetCoordType () const
virtual float GetInstrHeight () const
virtual double GetVscale () const
virtual double GetPscale () const
virtual double GetLscale () const
virtual double GetHscale () const
virtual std::string GetTarget () const
virtual std::string GetTarget2 () const
virtual float GetTargetHeight () const
virtual UINT32 GetTotal () const
virtual std::string GetReferenceFrame () const
std::string GetEpoch () const
virtual std::vector< CDnaGpsBaseline > * GetBaselines_ptr ()
virtual std::vector< CDnaDirection > * GetDirections_ptr ()
virtual std::vector< CDnaGpsPoint > * GetPoints_ptr ()
virtual std::vector< CDnaCovariance > * GetCovariances_ptr ()
virtual void AddDirection (const CDnaMeasurement *)
virtual void AddGpsBaseline (const CDnaMeasurement *)
virtual void AddGpsPoint (const CDnaMeasurement *)
virtual void AddGpsCovariance (const CDnaCovariance *)
virtual void AddPointCovariance (const CDnaCovariance *)
virtual void ReserveDirectionsCount (const UINT32 &)
virtual void ReserveGpsBaselinesCount (const UINT32 &)
virtual void ReserveGpsPointsCount (const UINT32 &)
virtual void ReserveGpsCovariancesCount (const UINT32 &)
virtual void ResizeGpsCovariancesCount (const UINT32 &)
virtual void SetRecordedTotal (const UINT32 &)
virtual void SetNonIgnoredDirns (const UINT32 &)
virtual void SetClusterID (const UINT32 &)
virtual void SetCoordType (const std::string &)
virtual void SetHscale (const std::string &)
virtual void SetHscale (const double &)
virtual void SetInstrumentHeight (const std::string &)
virtual void SetReferenceFrame (const std::string &)
void SetEpoch (const std::string &epoch)
virtual void SetLscale (const std::string &)
virtual void SetLscale (const double &)
virtual void SetPscale (const std::string &)
virtual void SetPscale (const double &)
virtual void SetSigmaXX (const std::string &)
virtual void SetSigmaXY (const std::string &)
virtual void SetSigmaXZ (const std::string &)
virtual void SetSigmaYY (const std::string &)
virtual void SetSigmaYZ (const std::string &)
virtual void SetSigmaZZ (const std::string &)
virtual void SetTarget (const std::string &)
virtual void SetTarget2 (const std::string &)
virtual void SetTargetHeight (const std::string &)
virtual void SetTotal (const std::string &)
virtual void SetVscale (const std::string &)
virtual void SetVscale (const double &)
virtual void SetX (const std::string &)
virtual void SetY (const std::string &)
virtual void SetZ (const std::string &)
virtual void SetXAxis (const double &)
virtual void SetYAxis (const double &)
virtual void SetZAxis (const double &)
virtual void SetSigmaXX (const double &)
virtual void SetSigmaXY (const double &)
virtual void SetSigmaXZ (const double &)
virtual void SetSigmaYY (const double &)
virtual void SetSigmaYZ (const double &)
virtual void SetSigmaZZ (const double &)
virtual void SetTotal (const UINT32 &)
virtual void PreferGMeasurements ()
void SetMeasurementDBID (const std::string &str)
void SetClusterDBID (const std::string &str)
void SetClusterDBID (const UINT32 &u, bool s)
UINT32 GetClusterDBID ()
bool GetClusterDBIDset ()
void SetDatabaseMap (const msr_database_id_map &dbidmap)
virtual void SetDatabaseMaps (it_vdbid_t &it_dbidmap)
virtual void SerialiseDatabaseMap (std::ofstream *os)
Protected Attributes
double m_dValue
double m_dStdDev
Protected Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strType
bool m_bIgnore
UINT32 m_lmeasurementIndex
UINT32 m_lstn1Index
UINT32 m_lstn2Index
UINT32 m_lstn3Index
double m_measAdj
double m_measCorr
double m_measAdjPrec
double m_residualPrec
double m_preAdjCorr
std::string m_epsgCode
std::string m_sourceFile
std::string m_epoch
msr_database_id_map m_msr_db_map
bool m_bInsufficient
Additional Inherited Members
Public Attributes inherited from dynadjust::measurements::CDnaMeasurement
std::string m_strFirst
MEASUREMENT_STATIONS m_MSmeasurementStations
Protected Member Functions inherited from dynadjust::measurements::CDnaMeasurement
void coutMeasurement (std::ostream &os) const
Detailed Description
Definition at line 37 of file dnaheight.hpp.
Constructor & Destructor Documentation
CDnaHeight()
dynadjust::measurements::CDnaHeight::CDnaHeight (void)
Definition at line 28 of file dnaheight.cpp.
    : m_dValue(0.)
    , m_dStdDev(0.)
{
    m_strType = "H";       // default is orthometric distance, but could also be 'R'
    m_MSmeasurementStations = ONE_STATION;
}
References m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_strType, and ONE_STATION.
Referenced by operator<(), and operator==().
~CDnaHeight()
dynadjust::measurements::CDnaHeight::~CDnaHeight (void) virtual
Definition at line 37 of file dnaheight.cpp.
{
}
Member Function Documentation
operator==()
bool dynadjust::measurements::CDnaHeight::operator== (const CDnaHeight & rhs) const
Definition at line 43 of file dnaheight.cpp.
{
    return (
        m_strFirst == rhs.m_strFirst &&
        m_strType == rhs.m_strType &&
        m_bIgnore == rhs.m_bIgnore &&
        m_dValue == rhs.m_dValue &&
        m_dStdDev == rhs.m_dStdDev &&
        m_epoch == rhs.m_epoch
        );
}
References CDnaHeight(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_strFirst, and dynadjust::measurements::CDnaMeasurement::m_strType.
operator<()
bool dynadjust::measurements::CDnaHeight::operator< (const CDnaHeight & rhs) const
Definition at line 55 of file dnaheight.cpp.
{
    if (m_strFirst == rhs.m_strFirst) {
        if (m_strType == rhs.m_strType) {  // don't think this is needed
            if (m_bIgnore == rhs.m_bIgnore) {
                if (m_epoch == rhs.m_epoch) {
                    if (m_dValue == rhs.m_dValue)
                        return m_dStdDev < rhs.m_dStdDev;
                    else
                        return m_dValue < rhs.m_dValue; }
                else
                    return m_epoch < rhs.m_epoch; }
            else
                return m_bIgnore < rhs.m_bIgnore; }
        else
            return m_strType < rhs.m_strType; }
    else
        return m_strFirst < rhs.m_strFirst;
}
References CDnaHeight(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_strFirst, and dynadjust::measurements::CDnaMeasurement::m_strType.
GetValue()
double dynadjust::measurements::CDnaHeight::GetValue () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 56 of file dnaheight.hpp.
{ return m_dValue; }
References m_dValue.
GetStdDev()
double dynadjust::measurements::CDnaHeight::GetStdDev () const inline virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 57 of file dnaheight.hpp.
{ return m_dStdDev; }
References m_dStdDev.
SetValue()
void dynadjust::measurements::CDnaHeight::SetValue (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 219 of file dnaheight.cpp.
{
    DoubleFromString(m_dValue, trimstr(str));
}
References DoubleFromString(), m_dValue, and trimstr().
SetStdDev()
void dynadjust::measurements::CDnaHeight::SetStdDev (const std::string & str) virtual
Reimplemented from dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 224 of file dnaheight.cpp.
{
    DoubleFromString(m_dStdDev, trimstr(str));
}
References DoubleFromString(), m_dStdDev, and trimstr().
CalcBinaryRecordCount()
virtual UINT32 dynadjust::measurements::CDnaHeight::CalcBinaryRecordCount () const inline virtual
Implements dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 63 of file dnaheight.hpp.
{ return 1; }
WriteBinaryMsr()
void dynadjust::measurements::CDnaHeight::WriteBinaryMsr (std::ofstream * binary_stream, PUINT32 msrIndex) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 194 of file dnaheight.cpp.
{
    measurement_t measRecord;
    measRecord.measType = GetTypeC();
    measRecord.measStart = xMeas;
    measRecord.ignore = m_bIgnore;
    measRecord.station1 = m_lstn1Index;
    measRecord.measAdj = m_measAdj;
    measRecord.measCorr = m_measCorr;
    measRecord.measAdjPrec = m_measAdjPrec;
    measRecord.residualPrec = m_residualPrec;
    measRecord.preAdjCorr = m_preAdjCorr;
    measRecord.term1 = m_dValue;
    measRecord.term2 = m_dStdDev * m_dStdDev; // convert to variance
    measRecord.term3 = 0.;
    measRecord.term4 = 0.;
    measRecord.measurementStations = m_MSmeasurementStations;
    measRecord.fileOrder = ((*msrIndex)++);
    snprintf(measRecord.epoch, sizeof(measRecord.epoch), "%s", m_epoch.substr(0, STN_EPOCH_WIDTH).c_str());
    binary_stream->write(reinterpret_cast<char *>(&measRecord), sizeof(measurement_t));
}
References dynadjust::measurements::msr_t::epoch, dynadjust::measurements::msr_t::fileOrder, dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::msr_t::ignore, dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::msr_t::measAdj, dynadjust::measurements::msr_t::measAdjPrec, dynadjust::measurements::msr_t::measCorr, dynadjust::measurements::msr_t::measStart, dynadjust::measurements::msr_t::measType, dynadjust::measurements::msr_t::measurementStations, dynadjust::measurements::msr_t::preAdjCorr, dynadjust::measurements::msr_t::residualPrec, dynadjust::measurements::msr_t::station1, STN_EPOCH_WIDTH(), dynadjust::measurements::msr_t::term1, dynadjust::measurements::msr_t::term2, dynadjust::measurements::msr_t::term3, dynadjust::measurements::msr_t::term4, and xMeas.
SetMeasurementRec()
UINT32 dynadjust::measurements::CDnaHeight::SetMeasurementRec (const vstn_t & binaryStn, it_vmsr_t & it_msr, it_vdbid_t & dbidmap) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 169 of file dnaheight.cpp.
{
    m_strType = it_msr->measType;
    m_bIgnore = it_msr->ignore;
    m_MSmeasurementStations = (MEASUREMENT_STATIONS)it_msr->measurementStations;
    m_lstn1Index = it_msr->station1;
    m_strFirst = binaryStn.at(it_msr->station1).stationName;
    m_measAdj = it_msr->measAdj;
    m_measCorr = it_msr->measCorr;
    m_measAdjPrec = it_msr->measAdjPrec;
    m_residualPrec = it_msr->residualPrec;
    m_preAdjCorr = it_msr->preAdjCorr;
    m_dValue = it_msr->term1;
    m_dStdDev = sqrt(it_msr->term2);
    m_epoch = it_msr->epoch;
    CDnaMeasurement::SetDatabaseMap(*dbidmap);
    return 0;
}
References dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_measAdj, dynadjust::measurements::CDnaMeasurement::m_measAdjPrec, dynadjust::measurements::CDnaMeasurement::m_measCorr, dynadjust::measurements::CDnaMeasurement::m_MSmeasurementStations, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, dynadjust::measurements::CDnaMeasurement::m_residualPrec, dynadjust::measurements::CDnaMeasurement::m_strFirst, dynadjust::measurements::CDnaMeasurement::m_strType, and dynadjust::measurements::CDnaMeasurement::SetDatabaseMap().
WriteDynaMLMsr()
void dynadjust::measurements::CDnaHeight::WriteDynaMLMsr (std::ofstream * dynaml_stream, const std::string & comment, bool) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 76 of file dnaheight.cpp.
{
    if (comment.empty())
        *dynaml_stream << "  <!-- Type " << measurement_name<char, std::string>(GetTypeC()) << " -->" << std::endl;
    else
        *dynaml_stream << "  <!-- " << comment << " -->" << std::endl;
    *dynaml_stream << "  <DnaMeasurement>" << std::endl;
    *dynaml_stream << "    <Type>" << m_strType << "</Type>" << std::endl;
    // Source file from which the measurement came
    *dynaml_stream << "    <Source>" << m_sourceFile << "</Source>" << std::endl;
    if (m_bIgnore)
        *dynaml_stream << "    <Ignore>*</Ignore>" << std::endl;
    else
        *dynaml_stream << "    <Ignore/>" << std::endl;
    if (m_epoch.empty())
        *dynaml_stream << "    <Epoch/>" << std::endl;
    else
        *dynaml_stream << "    <Epoch>" << m_epoch << "</Epoch>" << std::endl;
    *dynaml_stream << "    <First>" << m_strFirst << "</First>" << std::endl;
    *dynaml_stream << "    <Value>" << std::fixed << std::setprecision(4) << m_dValue << "</Value>" << std::endl;
    *dynaml_stream << "    <StdDev>" << std::scientific << std::setprecision(6) << m_dStdDev << "</StdDev>" << std::endl;
    if (m_msr_db_map.is_msr_id_set)
        *dynaml_stream << "    <MeasurementID>" << m_msr_db_map.msr_id << "</MeasurementID>" << std::endl;
    *dynaml_stream << "  </DnaMeasurement>" << std::endl;
}
References dynadjust::measurements::CDnaMeasurement::GetTypeC(), dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_sourceFile, dynadjust::measurements::CDnaMeasurement::m_strFirst, dynadjust::measurements::CDnaMeasurement::m_strType, and dynadjust::measurements::measurement_name().
WriteDNAMsr()
void dynadjust::measurements::CDnaHeight::WriteDNAMsr (std::ofstream * dna_stream, const dna_msr_fields & dmw, const dna_msr_fields & dml, bool) const virtual
Implements dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 108 of file dnaheight.cpp.
{
    *dna_stream << std::setw(dmw.msr_type) << m_strType;
    if (m_bIgnore)
        *dna_stream << std::setw(dmw.msr_ignore) << "*";
    else
        *dna_stream << std::setw(dmw.msr_ignore) << " ";
    *dna_stream << std::left << std::setw(dmw.msr_inst) << m_strFirst;
    *dna_stream << std::setw(dmw.msr_targ1) << " ";
    *dna_stream << std::setw(dmw.msr_targ2) << " ";
    *dna_stream << std::right << std::setw(dmw.msr_linear) << std::fixed << std::setprecision(4) << m_dValue; // linear measurement value
    *dna_stream << std::setw(dmw.msr_ang_d + dmw.msr_ang_m + dmw.msr_ang_s) << " ";
    UINT32 m_stdDevPrec(3);   // note change from 6 decimal places to 3
    *dna_stream << std::setw(dmw.msr_stddev) << StringFromTW(m_dStdDev, dmw.msr_stddev, m_stdDevPrec);
    //*dna_stream << std::setw(dmw.msr_stddev) << std::fixed << std::setprecision(6) << m_dStdDev;
    *dna_stream << std::setw(dml.msr_gps_epoch - dml.msr_inst_ht) << " ";
    *dna_stream << std::setw(dmw.msr_gps_epoch) << m_epoch;
    if (m_msr_db_map.is_msr_id_set)
        *dna_stream << std::setw(dmw.msr_id_msr) << m_msr_db_map.msr_id;
    *dna_stream << std::endl;
}
References dynadjust::measurements::CDnaMeasurement::m_bIgnore, m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_msr_db_map, dynadjust::measurements::CDnaMeasurement::m_strFirst, dynadjust::measurements::CDnaMeasurement::m_strType, dna_msr_fields::msr_ang_d, dna_msr_fields::msr_ang_m, dna_msr_fields::msr_ang_s, dna_msr_fields::msr_gps_epoch, dna_msr_fields::msr_id_msr, dna_msr_fields::msr_ignore, dna_msr_fields::msr_inst, dna_msr_fields::msr_inst_ht, dna_msr_fields::msr_linear, dna_msr_fields::msr_stddev, dna_msr_fields::msr_targ1, dna_msr_fields::msr_targ2, dna_msr_fields::msr_type, and StringFromTW().
SimulateMsr()
void dynadjust::measurements::CDnaHeight::SimulateMsr (vdnaStnPtr * vStations, const CDnaEllipsoid * ellipsoid) virtual
Implements dynadjust::measurements::CDnaMeasurement.
Reimplemented in dynadjust::measurements::CDnaHeightDifference.
Definition at line 136 of file dnaheight.cpp.
{
    // Zn is the z coordinate element of the point on the z-axis
    // which intersects with the the normal at the given Latitude
    double nu1, Zn1;
    // calculated height
    m_dValue = EllipsoidHeight<double>(
        vStations->at(m_lstn1Index).get()->GetXAxis(),
        vStations->at(m_lstn1Index).get()->GetYAxis(),
        vStations->at(m_lstn1Index).get()->GetZAxis(),
        vStations->at(m_lstn1Index).get()->GetcurrentLatitude(),
        &nu1, &Zn1, ellipsoid);
    m_dStdDev = 0.024;
    switch (GetTypeC())
    {
    case 'H':
        // N value available?
        if (fabs(vStations->at(m_lstn1Index).get()->GetgeoidSep()) > PRECISION_1E4)
        {
            // reduce to orthometric height
            m_preAdjCorr = vStations->at(m_lstn1Index).get()->GetgeoidSep();
            m_dValue -= m_preAdjCorr;
        }
        break;
    }
    m_epoch = "01.10.1985";
}
References EllipsoidHeight(), dynadjust::measurements::CDnaMeasurement::GetTypeC(), m_dStdDev, m_dValue, dynadjust::measurements::CDnaMeasurement::m_epoch, dynadjust::measurements::CDnaMeasurement::m_lstn1Index, dynadjust::measurements::CDnaMeasurement::m_preAdjCorr, and PRECISION_1E4().
Member Data Documentation
m_dValue
double dynadjust::measurements::CDnaHeight::m_dValue protected
Definition at line 71 of file dnaheight.hpp.
Referenced by CDnaHeight(), GetValue(), operator<(), operator==(), SetMeasurementRec(), SetValue(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
m_dStdDev
double dynadjust::measurements::CDnaHeight::m_dStdDev protected
Definition at line 72 of file dnaheight.hpp.
Referenced by CDnaHeight(), GetStdDev(), operator<(), operator==(), SetMeasurementRec(), SetStdDev(), SimulateMsr(), WriteBinaryMsr(), WriteDNAMsr(), and WriteDynaMLMsr().
The documentation for this class was generated from the following files:
include/measurement_types/dnaheight.hpp
include/measurement_types/dnaheight.cpp