DynAdjust: GPSCovariance_pimpl Class Reference
GPSCovariance_pimpl Class Reference
#include <dnaparser_pimpl.hxx>
Public Member Functions
virtual void pre ()
virtual void m11 (const ::std::string &)
virtual void m12 (const ::std::string &)
virtual void m13 (const ::std::string &)
virtual void m21 (const ::std::string &)
virtual void m22 (const ::std::string &)
virtual void m23 (const ::std::string &)
virtual void m31 (const ::std::string &)
virtual void m32 (const ::std::string &)
virtual void m33 (const ::std::string &)
virtual void post_GPSCovariance ()
Public Member Functions inherited from GPSCovariance_pskel
void m11_parser (::xml_schema::string_pskel &)
void m12_parser (::xml_schema::string_pskel &)
void m13_parser (::xml_schema::string_pskel &)
void m21_parser (::xml_schema::string_pskel &)
void m22_parser (::xml_schema::string_pskel &)
void m23_parser (::xml_schema::string_pskel &)
void m31_parser (::xml_schema::string_pskel &)
void m32_parser (::xml_schema::string_pskel &)
void m33_parser (::xml_schema::string_pskel &)
void parsers (::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &, ::xml_schema::string_pskel &)
GPSCovariance_pskel ()
void InitparentGpsBaseline (dnaMsrPtr pGpsBaseline)
Additional Inherited Members
Protected Member Functions inherited from GPSCovariance_pskel
virtual bool _start_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &, const ::xml_schema::ro_string *)
virtual bool _end_element_impl (const ::xml_schema::ro_string &, const ::xml_schema::ro_string &)
Protected Attributes inherited from GPSCovariance_pskel
::xml_schema::string_pskel * m11_parser_
::xml_schema::string_pskel * m12_parser_
::xml_schema::string_pskel * m13_parser_
::xml_schema::string_pskel * m21_parser_
::xml_schema::string_pskel * m22_parser_
::xml_schema::string_pskel * m23_parser_
::xml_schema::string_pskel * m31_parser_
::xml_schema::string_pskel * m32_parser_
::xml_schema::string_pskel * m33_parser_
dnaCovariancePtr _dnaGpsCovariance
dnaMsrPtr _parent_dnaGpsBaseline
Detailed Description
Definition at line 171 of file dnaparser_pimpl.hxx.
Member Function Documentation
pre()
void GPSCovariance_pimpl::pre () virtual
Definition at line 1145 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance.reset(new CDnaCovariance);
    _dnaGpsCovariance->SetType("X");
    _dnaGpsCovariance->SetClusterID(_parent_dnaGpsBaseline->GetClusterID());
}
References GPSCovariance_pskel::_dnaGpsCovariance, and GPSCovariance_pskel::_parent_dnaGpsBaseline.
m11()
void GPSCovariance_pimpl::m11 (const ::std::string & m11) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1152 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM11(m11);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m11().
Referenced by m11().
m12()
void GPSCovariance_pimpl::m12 (const ::std::string & m12) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1157 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM12(m12);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m12().
Referenced by m12().
m13()
void GPSCovariance_pimpl::m13 (const ::std::string & m13) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1162 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM13(m13);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m13().
Referenced by m13().
m21()
void GPSCovariance_pimpl::m21 (const ::std::string & m21) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1167 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM21(m21);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m21().
Referenced by m21().
m22()
void GPSCovariance_pimpl::m22 (const ::std::string & m22) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1172 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM22(m22);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m22().
Referenced by m22().
m23()
void GPSCovariance_pimpl::m23 (const ::std::string & m23) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1177 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM23(m23);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m23().
Referenced by m23().
m31()
void GPSCovariance_pimpl::m31 (const ::std::string & m31) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1182 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM31(m31);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m31().
Referenced by m31().
m32()
void GPSCovariance_pimpl::m32 (const ::std::string & m32) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1187 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM32(m32);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m32().
Referenced by m32().
m33()
void GPSCovariance_pimpl::m33 (const ::std::string & m33) virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1192 of file dnaparser_pimpl.cxx.
{
    _dnaGpsCovariance->SetM33(m33);
}
References GPSCovariance_pskel::_dnaGpsCovariance, and m33().
Referenced by m33().
post_GPSCovariance()
void GPSCovariance_pimpl::post_GPSCovariance () virtual
Reimplemented from GPSCovariance_pskel.
Definition at line 1197 of file dnaparser_pimpl.cxx.
{
    if (_dnaGpsCovariance && _parent_dnaGpsBaseline)
        _parent_dnaGpsBaseline->AddGpsCovariance(
        _dnaGpsCovariance.get());
}
References GPSCovariance_pskel::_dnaGpsCovariance, and GPSCovariance_pskel::_parent_dnaGpsBaseline.
The documentation for this class was generated from the following files:
dynadjust/dnaimport/dnaparser_pimpl.hxx
dynadjust/dnaimport/dnaparser_pimpl.cxx