DynAdjust: include/config/dnaconsts.hpp File Reference
dnaconsts.hpp File Reference
#include <include/config/dnatypes.hpp>
#include <include/parameters/dnaconsts-datums.hpp>
Functions
const UINT16 BUF_WIDTH (512)
const UINT16 DNA_COUT (1)
const UINT16 GEOLAB_COUT (2)
const UINT16 NEWGAN_COUT (3)
const UINT16 GMT_OUT (4)
const char *const DEFAULT_DATUM (GDA2020_s)
const char *const DEFAULT_EPSG_S (GDA2020_c)
const UINT32 DEFAULT_EPSG_U (GDA2020_i)
const char *const DEFAULT_EPOCH (GDA2020_epoch)
const char *const XYZ_type ("XYZ")
const char *const LLh_type ("LLh")
const char *const LLH_type ("LLH")
const char *const UTM_type ("UTM")
const char *const ENU_type ("ENU")
const char *const ORTHOMETRIC_type ("orthometric")
const char *const ELLIPSOIDAL_type ("ellipsoidal")
const double DAYS_PER_YEAR (365.25)
const double PI (3.1415926535897932384626433832795029)
const double HALF_PI (1.5707963267948966192313216916397514)
const double THIRD_PI (PI/3.)
const double QUART_PI (0.7853981633974483096156608458198757)
const double PI_20 (PI/9.)
const double PI_135 (PI - QUART_PI)
const double TWO_PI (PI+PI)
const double DEG_TO_RAD (PI/180.0)
const double RAD_TO_DEG (180.0/PI)
const double DEG_TO_SEC (3600.0)
const double RAD_TO_SEC (RAD_TO_DEG *DEG_TO_SEC)
const double SEC_TO_RAD (DEG_TO_RAD/DEG_TO_SEC)
const double INCH_TO_CM (2.54)
const double CM_TO_INCH (1./INCH_TO_CM)
const double CONSTRAINT_X (0.0001 *0.0001)
const double CONSTRAINT_Y (0.0001 *0.0001)
const double CONSTRAINT_Z (0.0001 *0.0001)
const double PRECISION_1E100 (1.0e-100)
const double PRECISION_1E35 (1.0e-35)
const double PRECISION_1E25 (1.0e-25)
const double PRECISION_1E16 (1.0e-16)
const double PRECISION_1E15 (1.0e-15)
const double PRECISION_1E14 (1.0e-14)
const double PRECISION_1E12 (1.0e-12)
const double PRECISION_1E11 (1.0e-11)
const double PRECISION_1E10 (1.0e-10)
const double PRECISION_1E6 (1.0e-6)
const double PRECISION_1E5 (1.0e-5)
const double PRECISION_1E4 (1.0e-4)
const double PRECISION_1E3 (1.0e-3)
const double PRECISION_1E2 (1.0e-2)
const long MILLI_TO_NANO (1000000)
const double HPOS_UNCERT_Q0 (1.96079)
const double HPOS_UNCERT_Q1 (0.004071)
const double HPOS_UNCERT_Q2 (0.114276)
const double HPOS_UNCERT_Q3 (0.371625)
const double E4_SEC_DEFLECTION (0.0001 *SEC_TO_RAD)
const double STN_SEARCH_RADIUS (0.3)
const std::string STN_SEARCH_RADIUS_STR ("0.3")
const double TOLERANCE_SEC_MIN (1.)
const double TOLERANCE_SEC_MAX (7200.)
const double TOLERANCE_ZERO (0.00001)
const double UNRELIABLE (999.99)
const double STABLE_LIMIT (700.)
const double MIN_DBL_VALUE (-1.7e308)
const double MAX_DBL_VALUE (+1.7e308)
const UINT32 MAX_UINT32_VALUE (0xffffffff)
Variables
const double seconds60 = 0.016666666666666667
const double seconds30 = 0.008333333333333333
const double seconds15 = 0.004166666666666667
const double seconds10 = 0.002777777777777778
const double seconds05 = 0.001388888888888889
Function Documentation
BUF_WIDTH()
const UINT16 BUF_WIDTH (512)
DNA_COUT()
const UINT16 DNA_COUT (1)
GEOLAB_COUT()
const UINT16 GEOLAB_COUT (2)
NEWGAN_COUT()
const UINT16 NEWGAN_COUT (3)
GMT_OUT()
const UINT16 GMT_OUT (4)
DEFAULT_DATUM()
const char *const DEFAULT_DATUM (GDA2020_s)
References GDA2020_s.
Referenced by dynadjust::datum_parameters::CDnaDatum::CDnaDatum(), dynadjust::measurements::CDnaGpsBaseline::CDnaGpsBaseline(), dynadjust::measurements::CDnaGpsBaselineCluster::CDnaGpsBaselineCluster(), dynadjust::measurements::CDnaGpsPoint::CDnaGpsPoint(), dynadjust::measurements::CDnaGpsPointCluster::CDnaGpsPointCluster(), dynadjust::measurements::CDnaStation::CDnaStation(), import_settings::import_settings(), and reftran_settings::reftran_settings().
DEFAULT_EPSG_S()
const char *const DEFAULT_EPSG_S (GDA2020_c)
References GDA2020_c.
Referenced by dynadjust::measurements::CDnaMeasurement::CDnaMeasurement(), dynadjust::measurements::CDnaStation::CDnaStation(), dynadjust::dynamlinterop::dna_import::dna_import(), and dynadjust::measurements::msr_t::msr_t().
DEFAULT_EPSG_U()
const UINT32 DEFAULT_EPSG_U (GDA2020_i)
References GDA2020_i.
Referenced by dynadjust::networkplot::dna_plot::CalculateLimitsFromPoint(), dynadjust::datum_parameters::CDnaDatum::CDnaDatum(), dynadjust::datum_parameters::CDnaEllipsoid::CDnaEllipsoid(), dynadjust::networkadjust::dna_adjust::dna_adjust(), and dynadjust::networkplot::dna_plot::dna_plot().
DEFAULT_EPOCH()
const char *const DEFAULT_EPOCH (GDA2020_epoch)
References GDA2020_epoch.
Referenced by dynadjust::measurements::CDnaGpsBaseline::CDnaGpsBaseline(), dynadjust::measurements::CDnaGpsBaselineCluster::CDnaGpsBaselineCluster(), dynadjust::measurements::CDnaGpsPoint::CDnaGpsPoint(), dynadjust::measurements::CDnaGpsPointCluster::CDnaGpsPointCluster(), dynadjust::dynamlinterop::dna_import::dna_import(), import_settings::import_settings(), and reftran_settings::reftran_settings().
XYZ_type()
const char *const XYZ_type ("XYZ")
Referenced by dynadjust::measurements::CDnaStation::GetCoordTypeC(), dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), dynadjust::iostreams::dna_io_snx::parse_sinex_stn(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRGPSPoints(), dynadjust::measurements::CDnaGpsPoint::PopulateMsr(), dynadjust::measurements::CDnaGpsPointCluster::PopulateMsr(), dynadjust::measurements::CDnaStation::ReduceStations_XYZ(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_Y(), dynadjust::measurements::CDnaGpsPoint::WriteDNAMsr(), and dynadjust::measurements::CDnaStation::WriteDNAXMLStn().
LLh_type()
const char *const LLh_type ("LLh")
Referenced by dynadjust::measurements::CDnaStation::GetCoordTypeC(), dynadjust::measurements::CDnaStation::GetMyHeightSystemC(), dynadjust::measurements::CDnaStation::ReduceStations_LLH(), dynadjust::measurements::CDnaGpsPoint::WriteDNAMsr(), and dynadjust::measurements::CDnaStation::WriteDNAXMLStn().
LLH_type()
const char *const LLH_type ("LLH")
Referenced by dynadjust::measurements::CDnaStation::GetCoordTypeC(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_YLLH(), dynadjust::measurements::CDnaStation::ReduceStations_LLH(), dynadjust::measurements::CDnaGpsPoint::WriteDNAMsr(), and dynadjust::measurements::CDnaStation::WriteDNAXMLStn().
UTM_type()
const char *const UTM_type ("UTM")
Referenced by dynadjust::measurements::CDnaStation::GetCoordTypeC(), and dynadjust::measurements::CDnaStation::WriteDNAXMLStn().
ENU_type()
const char *const ENU_type ("ENU")
Referenced by dynadjust::measurements::CDnaStation::GetCoordTypeC().
ORTHOMETRIC_type()
const char *const ORTHOMETRIC_type ("orthometric")
ELLIPSOIDAL_type()
const char *const ELLIPSOIDAL_type ("ellipsoidal")
Referenced by dynadjust::measurements::CDnaStation::GetHeightSystemC().
DAYS_PER_YEAR()
const double DAYS_PER_YEAR (365. 25)
Referenced by year_doy_Average().
PI()
const double PI (3. 1415926535897932384626433832795029)
Referenced by atan_2(), CartToGeo(), CartToGeo_SimpleIteration(), DEG_TO_RAD(), ErrorEllipseParameters(), dynadjust::networkplot::dna_plot::FinaliseGMTParameters(), GridToGeo(), PI_135(), PI_20(), Rad180Mod(), RAD_TO_DEG(), RobbinsReverse(), THIRD_PI(), and TWO_PI().
HALF_PI()
const double HALF_PI (1. 5707963267948966192313216916397514)
Referenced by Direction().
THIRD_PI()
const double THIRD_PI (PI/ 3.)
References PI().
Referenced by dynadjust::networkplot::dna_plot::FinaliseGMTParameters().
QUART_PI()
const double QUART_PI (0. 7853981633974483096156608458198757)
Referenced by dynadjust::networkplot::dna_plot::FinaliseGMTParameters(), and PI_135().
PI_20()
const double PI_20 (PI/ 9.)
References PI().
Referenced by dynadjust::networkplot::dna_plot::FinaliseGMTParameters().
PI_135()
const double PI_135 (PI - QUART_PI)
References PI(), and QUART_PI().
Referenced by dynadjust::networkplot::dna_plot::FinaliseGMTParameters().
TWO_PI()
const double TWO_PI (PI+ PI)
References PI().
Referenced by dynadjust::networkadjust::dna_adjust::AddMsrtoMeasMinusComp(), atan_2(), Direction(), dynadjust::networkplot::dna_plot::FinaliseGMTParameters(), HorizontalAngle(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_D(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_D(), and dynadjust::networkadjust::dna_adjust::UpdateMsrRecord().
DEG_TO_RAD()
const double DEG_TO_RAD (PI/180. 0)
References PI().
Referenced by degrees_to_radians_(), and SEC_TO_RAD().
RAD_TO_DEG()
const double RAD_TO_DEG (180.0/ PI)
References PI().
Referenced by DegreesL(), DegreesL(), RAD_TO_SEC(), and radians_to_degrees_().
DEG_TO_SEC()
const double DEG_TO_SEC (3600. 0)
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::ApplyAusGeoidGrid(), dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), RAD_TO_SEC(), reportGridProperties(), and SEC_TO_RAD().
RAD_TO_SEC()
const double RAD_TO_SEC (RAD_TO_DEG * DEG_TO_SEC)
References DEG_TO_SEC(), and RAD_TO_DEG().
Referenced by dynadjust::referenceframe::dna_reftran::CalculateRotations(), dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ExportToAscii(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ExportToBinary(), dynadjust::geoidinterpolation::dna_geoid_interpolation::PopulateStationRecords(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ReadAsciiShifts(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ReadBinaryShifts(), Seconds(), Seconds(), and SecondstoRadians().
SEC_TO_RAD()
const double SEC_TO_RAD (DEG_TO_RAD/ DEG_TO_SEC)
References DEG_TO_RAD(), and DEG_TO_SEC().
Referenced by E4_SEC_DEFLECTION().
INCH_TO_CM()
const double INCH_TO_CM (2. 54)
Referenced by CM_TO_INCH().
CM_TO_INCH()
const double CM_TO_INCH (1./ INCH_TO_CM)
References INCH_TO_CM().
Referenced by dynadjust::networkplot::dna_plot::CreateGMTCommandFile().
CONSTRAINT_X()
const double CONSTRAINT_X (0.0001 *0. 0001)
CONSTRAINT_Y()
const double CONSTRAINT_Y (0.0001 *0. 0001)
CONSTRAINT_Z()
const double CONSTRAINT_Z (0.0001 *0. 0001)
PRECISION_1E100()
const double PRECISION_1E100 (1.0e- 100)
PRECISION_1E35()
const double PRECISION_1E35 (1.0e- 35)
Referenced by DoubleFromString_ZeroCheck().
PRECISION_1E25()
const double PRECISION_1E25 (1.0e- 25)
Referenced by ErrorEllipseParameters(), dynadjust::dynamlinterop::dna_import::ParseStdDevValue(), and DnaMeasurement_pimpl::StdDev().
PRECISION_1E16()
const double PRECISION_1E16 (1.0e- 16)
Referenced by CartToGeo_SimpleIteration(), and VincentyDirect().
PRECISION_1E15()
const double PRECISION_1E15 (1.0e- 15)
Referenced by ErrorEllipseParameters(), RobbinsReverse(), and dynadjust::measurements::CDnaStation::WriteBinaryStn().
PRECISION_1E14()
const double PRECISION_1E14 (1.0e- 14)
PRECISION_1E12()
const double PRECISION_1E12 (1.0e- 12)
Referenced by CartToGeo(), and CartToLat().
PRECISION_1E11()
const double PRECISION_1E11 (1.0e- 11)
PRECISION_1E10()
const double PRECISION_1E10 (1.0e- 10)
Referenced by dynadjust::CDnaProjectFile::InitialiseAdjustSettings(), dynadjust::networkadjust::dna_adjust::UpdateMsrTstatistic(), dynadjust::networkadjust::dna_adjust::UpdateMsrTstatistic_D(), and dynadjust::networkadjust::dna_adjust::UpdateMsrTstatistic_GXY().
PRECISION_1E6()
const double PRECISION_1E6 (1.0e- 6)
Referenced by adjust_settings::adjust_settings(), are_floats_equal(), and dynadjust::CDnaProjectFile::InitialiseAdjustSettings().
PRECISION_1E5()
const double PRECISION_1E5 (1.0e- 5)
Referenced by dynadjust::measurements::CDnaStation::CDnaStation(), dynadjust::networkplot::dna_plot::ComputeStationCorrection(), dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), dynadjust::dynamlinterop::dna_import::EditGNSSMsrScalars(), dynadjust::geoidinterpolation::dna_geoid_interpolation::FindSubGrid(), dynadjust::CDnaProjectFile::InitialiseImportSettings(), dynadjust::geoidinterpolation::dna_geoid_interpolation::InterpolateNvalue_BiCubic(), dynadjust::geoidinterpolation::dna_geoid_interpolation::InterpolateNvalue_BiLinear(), dynadjust::geoidinterpolation::dna_geoid_interpolation::IsWithinLowerLatitudeGridInterval(), dynadjust::geoidinterpolation::dna_geoid_interpolation::IsWithinLowerLongitudeGridInterval(), dynadjust::geoidinterpolation::dna_geoid_interpolation::IsWithinUpperLatitudeGridInterval(), dynadjust::geoidinterpolation::dna_geoid_interpolation::IsWithinUpperLongitudeGridInterval(), dynadjust::networkadjust::dna_adjust::LoadVarianceScaling(), and dynadjust::networkadjust::dna_adjust::PrintCorStation().
PRECISION_1E4()
const double PRECISION_1E4 (1.0e- 4)
Referenced by dynadjust::measurements::CDnaStation::CDnaStation(), dynadjust::networkplot::dna_plot::CreateGMTCommandFile(), dynadjust::measurements::CDnaGpsBaseline::operator<(), dynadjust::measurements::CDnaGpsPoint::operator<(), dynadjust::measurements::CDnaGpsBaseline::operator==(), dynadjust::measurements::CDnaGpsPoint::operator==(), PartialD_HorizAngle(), PartialD_Latitude(), dynadjust::networkadjust::dna_adjust::ReduceYLLHMeasurementsforPrinting(), dynadjust::measurements::CDnaGpsPoint::SimulateMsr(), dynadjust::measurements::CDnaHeight::SimulateMsr(), dynadjust::measurements::CDnaHeightDifference::SimulateMsr(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_H(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_L(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_Y(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_H(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_L(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_Y(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::WriteDNA1GeoidFile().
PRECISION_1E3()
const double PRECISION_1E3 (1.0e- 3)
PRECISION_1E2()
const double PRECISION_1E2 (1.0e- 2)
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File().
MILLI_TO_NANO()
const long MILLI_TO_NANO (1000000)
Referenced by dynadjust::networkadjust::dna_adjust::AdjustPhasedMultiThread(), main(), dna_import_thread::operator()(), dna_segment_thread::operator()(), dynadjust::networkadjust::dna_adjust::PrintAdjustmentTime(), and dynadjust::networksegment::dna_segment::SegmentNetwork().
HPOS_UNCERT_Q0()
const double HPOS_UNCERT_Q0 (1. 96079)
Referenced by PositionalUncertainty().
HPOS_UNCERT_Q1()
const double HPOS_UNCERT_Q1 (0. 004071)
Referenced by PositionalUncertainty().
HPOS_UNCERT_Q2()
const double HPOS_UNCERT_Q2 (0. 114276)
Referenced by PositionalUncertainty().
HPOS_UNCERT_Q3()
const double HPOS_UNCERT_Q3 (0. 371625)
Referenced by PositionalUncertainty().
E4_SEC_DEFLECTION()
const double E4_SEC_DEFLECTION (0.0001 * SEC_TO_RAD)
References SEC_TO_RAD().
Referenced by dynadjust::measurements::CDnaAngle::SimulateMsr(), dynadjust::measurements::CDnaCoordinate::SimulateMsr(), dynadjust::measurements::CDnaDirection::SimulateMsr(), dynadjust::measurements::CDnaDirectionSet::SimulateMsr(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_A(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_BK(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_I(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_J(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_V(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_Z(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_A(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_I(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_J(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_K(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_V(), dynadjust::networkadjust::dna_adjust::UpdateIgnoredMeasurements_Z(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::WriteDNA1GeoidFile().
STN_SEARCH_RADIUS()
const double STN_SEARCH_RADIUS (0. 3)
Referenced by import_settings::import_settings(), and main().
STN_SEARCH_RADIUS_STR()
const std::string STN_SEARCH_RADIUS_STR ("0.3")
TOLERANCE_SEC_MIN()
const double TOLERANCE_SEC_MIN (1.)
TOLERANCE_SEC_MAX()
const double TOLERANCE_SEC_MAX (7200.)
TOLERANCE_ZERO()
const double TOLERANCE_ZERO (0. 00001)
UNRELIABLE()
const double UNRELIABLE (999. 99)
Referenced by dynadjust::networkadjust::dna_adjust::ComputeGlobalPelzer(), dynadjust::networkadjust::dna_adjust::ComputeGlobalPelzer_D(), dynadjust::networkadjust::dna_adjust::ComputeGlobalPelzer_GXY(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessCsvFile(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessDatFile(), and dynadjust::networkadjust::dna_adjust::UpdateMsrRecordStats().
STABLE_LIMIT()
const double STABLE_LIMIT (700.)
Referenced by dynadjust::networkadjust::dna_adjust::ComputeGlobalPelzer(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), and dynadjust::networkadjust::dna_adjust::UpdateMsrRecordStats().
MIN_DBL_VALUE()
const double MIN_DBL_VALUE (-1. 7e308)
MAX_DBL_VALUE()
const double MAX_DBL_VALUE (+1. 7e308)
Referenced by GetFields().
MAX_UINT32_VALUE()
const UINT32 MAX_UINT32_VALUE (0xffffffff)
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements(), and dynadjust::networkadjust::dna_adjust::PrintIgnoredAdjMeasurements().
Variable Documentation
seconds60
const double seconds60 = 0.016666666666666667
Definition at line 75 of file dnaconsts.hpp.
Referenced by dynadjust::networkplot::dna_plot::FinaliseGMTParameters().
seconds30
const double seconds30 = 0.008333333333333333
Definition at line 76 of file dnaconsts.hpp.
seconds15
const double seconds15 = 0.004166666666666667
Definition at line 77 of file dnaconsts.hpp.
Referenced by dynadjust::networkplot::dna_plot::FinaliseGMTParameters().
seconds10
const double seconds10 = 0.002777777777777778
Definition at line 78 of file dnaconsts.hpp.
seconds05
const double seconds05 = 0.001388888888888889
Definition at line 79 of file dnaconsts.hpp.
Referenced by dynadjust::networkplot::dna_plot::FinaliseGMTParameters().