DynAdjust: include/config/dnaconsts-iostream.hpp File Reference
dnaconsts-iostream.hpp File Reference
#include <include/config/dnatypes.hpp>
Functions
const UINT32 OUTPUTLINELENGTH (80)
const UINT32 PROGRAM_OPTIONS_LINE_LENGTH (100)
const UINT32 PRINT_LINE_LENGTH (500)
const UINT32 PRINT_VAR_PAD (35)
const UINT32 PRINT_VAL_PAD (45)
const UINT32 NUMERIC_WIDTH (8)
const UINT32 PASS_FAIL (16)
const UINT32 CHISQRLIMITS (OUTPUTLINELENGTH - PRINT_VAR_PAD - PASS_FAIL)
const UINT16 HEADER_18 (18)
const UINT16 HEADER_20 (20)
const UINT16 HEADER_25 (25)
const UINT16 HEADER_32 (32)
const UINT16 BLOCK (14)
const UINT16 NETID (14)
const UINT16 INNER (16)
const UINT16 JUNCT (16)
const UINT16 MEASR (16)
const UINT16 TOTAL (16)
const UINT16 STATION (20)
const UINT16 MSR (19)
const UINT16 OUTLIER (12)
const UINT16 PACORR (14)
const UINT16 CORR (12)
const UINT16 PREC (13)
const UINT16 REL (12)
const UINT16 STAT (11)
const UINT16 PAD2 (2)
const UINT16 PAD3 (3)
const UINT16 PAD (5)
const UINT16 CONSTRAINT (5)
const UINT16 LAT_EAST (14)
const UINT16 LON_NORTH (15)
const UINT16 HEIGHT (11)
const UINT16 ZONE (8)
const UINT16 XYZ (15)
const UINT16 STDDEV (10)
const UINT16 PAD5 (5)
const UINT16 COMMENT (56)
Variables
const char *const CORRELATION_MATRIX = "CORR"
const char *const COVARIANCE_MATRIX = "COVA"
const char *const INFORMATION_MATRIX = "INFO"
const char *const ENDSNX = "%ENDSNX"
const char *const OUTPUTLINE = "--------------------------------------------------------------------------------"
const int MAX_RECORD_LENGTH = 600
const int NULL_PAD = 4
const int INT_BUF = 4
const int IDENT_BUF = 8
const int HEADER_RECORD = 100
const int DATA_RECORD = 100
const int OVERVIEW_RECS = 8
Function Documentation
OUTPUTLINELENGTH()
const UINT32 OUTPUTLINELENGTH (80)
Referenced by CHISQRLIMITS().
PROGRAM_OPTIONS_LINE_LENGTH()
const UINT32 PROGRAM_OPTIONS_LINE_LENGTH (100)
Referenced by dynadjust::networksegment::dna_segment::LoadNetFile(), and main().
PRINT_LINE_LENGTH()
const UINT32 PRINT_LINE_LENGTH (500)
Referenced by dynadjust::iostreams::dna_io_seg::load_seg_file(), dynadjust::iostreams::dna_io_seg::load_seg_file_header(), dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::networksegment::dna_segment::LoadNetFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), and dynadjust::dynamlinterop::dna_import::ParseInputFile().
PRINT_VAR_PAD()
const UINT32 PRINT_VAR_PAD (35)
Referenced by dynadjust::networkadjust::dna_adjust::AdjustPhasedMultiThread(), CHISQRLIMITS(), dynadjust::measurements::MsrTally::coutSummary(), dynadjust::measurements::StnTally::coutSummary(), GenerateStatistics(), dynadjust::networkadjust::dna_adjust::GetMemoryFootprint(), dynadjust::iostreams::dna_io_scalar::load_scalar_file(), dynadjust::iostreams::dna_io_seg::load_seg_file_header(), dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::CDnaProjectFile::LoadProjectFile(), main(), output_build(), output_version(), dynadjust::networkadjust::dna_adjust::OutputLargestCorrection(), dynadjust::networkplot::dna_plot::PlotGnuplotDatFileMsrs(), print_file_header(), dynadjust::iostreams::dna_io_snx::print_warnings(), dynadjust::networkadjust::dna_adjust::PrintAdjustmentStatus(), dynadjust::networkadjust::dna_adjust::PrintAdjustmentTime(), dynadjust::networkplot::dna_plot::PrintGnuplotCommandFileMsrs(), dynadjust::networkadjust::dna_adjust::PrintIteration(), dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations(), dynadjust::networkadjust::dna_adjust::PrintNetworkStationCorrections(), dynadjust::networkadjust::dna_adjust::PrintOutputFileHeaderInfo(), PrintOutputFileHeaderInfo(), PrintOutputFileHeaderInfo(), dynadjust::networkadjust::dna_adjust::PrintPositionalUncertainty(), dynadjust::CDnaProjectFile::PrintProjectFile(), dynadjust::networkadjust::dna_adjust::PrintStatistics(), dynadjust::CDnaProjectFile::PrintVariable(), ProcessGMTPlot(), ProcessGnuPlot(), ReturnBadStationRecords(), and dynadjust::iostreams::dna_io_seg::write_seg_file().
PRINT_VAL_PAD()
const UINT32 PRINT_VAL_PAD (45)
Referenced by dynadjust::referenceframe::dna_reftran::LogFrameSubstitutions(), dynadjust::networkadjust::dna_adjust::PrintOutputFileHeaderInfo(), and dynadjust::CDnaProjectFile::PrintValue().
NUMERIC_WIDTH()
const UINT32 NUMERIC_WIDTH (8)
Referenced by dynadjust::measurements::MsrTally::coutSummary(), dynadjust::measurements::StnTally::coutSummary(), dynadjust::measurements::MsrTally::coutSummaryMsrToStn(), dynadjust::networkadjust::dna_adjust::GetMemoryFootprint(), dynadjust::referenceframe::dna_reftran::LogFrameSubstitutions(), dynadjust::measurements::MsrToStnSummaryHeader(), and dynadjust::measurements::MsrToStnSummaryHeaderLine().
PASS_FAIL()
const UINT32 PASS_FAIL (16)
Referenced by CHISQRLIMITS(), GenerateStatistics(), and dynadjust::networkadjust::dna_adjust::PrintStatistics().
CHISQRLIMITS()
const UINT32 CHISQRLIMITS (OUTPUTLINELENGTH - PRINT_VAR_PAD - PASS_FAIL)
References OUTPUTLINELENGTH(), PASS_FAIL(), and PRINT_VAR_PAD().
Referenced by GenerateStatistics(), and dynadjust::networkadjust::dna_adjust::PrintStatistics().
HEADER_18()
const UINT16 HEADER_18 (18)
Referenced by dynadjust::referenceframe::dna_reftran::CalculateRotations(), dynadjust::networkplot::dna_plot::PlotGnuplotDatFileStns(), and dynadjust::iostreams::dna_io_aml::write_aml_file_txt().
HEADER_20()
const UINT16 HEADER_20 (20)
Referenced by dynadjust::networkadjust::dna_adjust::LoadSegmentationMetrics(), main(), dynadjust::iostreams::dna_io_asl::write_asl_file_txt(), dynadjust::iostreams::dna_io_map::write_map_file_txt(), and dynadjust::networksegment::dna_segment::WriteFreeStnListSortedbyASLMsrCount().
HEADER_25()
const UINT16 HEADER_25 (25)
Referenced by dynadjust::networkplot::dna_plot::PlotGnuplotDatFileStns().
HEADER_32()
const UINT16 HEADER_32 (32)
Referenced by dynadjust::networkplot::dna_plot::PlotGnuplotDatFileStns().
BLOCK()
const UINT16 BLOCK (14)
Referenced by dynadjust::networksegment::dna_segment::coutSummary(), dynadjust::iostreams::dna_io_seg::load_seg_file(), dynadjust::iostreams::dna_io_seg::write_seg_block(), and dynadjust::iostreams::dna_io_seg::write_seg_file().
NETID()
const UINT16 NETID (14)
Referenced by dynadjust::networksegment::dna_segment::coutSummary(), dynadjust::iostreams::dna_io_seg::load_seg_file(), and dynadjust::iostreams::dna_io_seg::write_seg_file().
INNER()
const UINT16 INNER (16)
Referenced by dynadjust::networksegment::dna_segment::coutSummary(), dynadjust::iostreams::dna_io_seg::load_seg_file(), dynadjust::iostreams::dna_io_seg::write_seg_block(), and dynadjust::iostreams::dna_io_seg::write_seg_file().
JUNCT()
const UINT16 JUNCT (16)
Referenced by dynadjust::networksegment::dna_segment::coutSummary(), dynadjust::iostreams::dna_io_seg::load_seg_file(), dynadjust::iostreams::dna_io_seg::write_seg_block(), and dynadjust::iostreams::dna_io_seg::write_seg_file().
MEASR()
const UINT16 MEASR (16)
Referenced by dynadjust::networksegment::dna_segment::coutSummary(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::iostreams::dna_io_seg::load_seg_file(), reportGridProperties(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformStation(), dynadjust::referenceframe::dna_reftran::TransformStationRecords(), dynadjust::iostreams::dna_io_seg::write_seg_block(), and dynadjust::iostreams::dna_io_seg::write_seg_file().
TOTAL()
const UINT16 TOTAL (16)
Referenced by dynadjust::networksegment::dna_segment::coutSummary(), and dynadjust::iostreams::dna_io_seg::write_seg_file().
STATION()
const UINT16 STATION (20)
Referenced by dynadjust::measurements::MsrTally::coutSummaryMsrToStn(), dynadjust::measurements::MsrTally::coutSummaryMsrToStn_Compressed(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::iostreams::dna_io_scalar::load_scalar_file(), dynadjust::iostreams::dna_io_tbu::load_tbu_file(), dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), main(), dynadjust::measurements::MsrToStnSummaryHeader(), dynadjust::measurements::MsrToStnSummaryHeaderLine(), dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_A(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_BKVZ(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_CELMS(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_GXY(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_HR(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_IJPQ(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_A(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_BKVZ(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_CELMS(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_GXY(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_HR(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_IJPQ(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_YLLH(), dynadjust::networkadjust::dna_adjust::PrintCorStation(), dynadjust::networkadjust::dna_adjust::PrintCorStations(), dynadjust::networkadjust::dna_adjust::PrintCorStationsUniqueList(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsLinear(), dynadjust::networkadjust::dna_adjust::PrintPosUncertaintiesHeader(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ReturnBadStationRecords(), dynadjust::dynamlinterop::dna_import::SerialiseDiscontTextFile(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformStation(), dynadjust::referenceframe::dna_reftran::TransformStationRecords(), dynadjust::iostreams::dna_io_asl::write_asl_file_txt(), dynadjust::iostreams::dna_io_map::write_map_file_txt(), and dynadjust::iostreams::dna_io_aml::write_msr_to_stn().
MSR()
const UINT16 MSR (19)
Referenced by dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_D(), dynadjust::networkplot::dna_plot::PrintCorrectionArrows(), dynadjust::networkadjust::dna_adjust::PrintCorStation(), dynadjust::networkadjust::dna_adjust::PrintCorStations(), dynadjust::networkadjust::dna_adjust::PrintCorStationsUniqueList(), dynadjust::networkplot::dna_plot::PrintErrorEllipses(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsLinear(), dynadjust::networkplot::dna_plot::PrintPositionalUncertainty(), dynadjust::networkadjust::dna_adjust::PrintPosUncertaintiesHeader(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), and dynadjust::iostreams::dna_io_aml::write_aml_file_txt().
OUTLIER()
const UINT16 OUTLIER (12)
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), and dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementStatistics().
PACORR()
const UINT16 PACORR (14)
Referenced by dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintMeasurementCorrection(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), and dynadjust::referenceframe::dna_reftran::TransformStationRecords().
CORR()
const UINT16 CORR (12)
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), and dynadjust::networkadjust::dna_adjust::PrintMeasurementsLinear().
PREC()
const UINT16 PREC (13)
Referenced by dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsLinear(), dynadjust::networkadjust::dna_adjust::PrintPosUncertaintiesHeader(), and dynadjust::networkadjust::dna_adjust::PrintPosUncertainty().
REL()
const UINT16 REL (12)
Referenced by dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementStatistics(), reportGridProperties(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformStation(), and dynadjust::referenceframe::dna_reftran::TransformStationRecords().
STAT()
const UINT16 STAT (11)
Referenced by dynadjust::measurements::MsrTally::coutSummaryMsrToStn(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), main(), dynadjust::measurements::MsrToStnSummaryHeader(), dynadjust::measurements::MsrToStnSummaryHeaderLine(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementStatistics(), dynadjust::networkadjust::dna_adjust::PrintPosUncertaintiesHeader(), and dynadjust::networkadjust::dna_adjust::PrintPosUncertainty().
PAD2()
const UINT16 PAD2 (2)
Referenced by dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_GXY(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_GXY(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_YLLH(), dynadjust::networkadjust::dna_adjust::PrintCorStation(), dynadjust::networkadjust::dna_adjust::PrintCorStations(), dynadjust::networkadjust::dna_adjust::PrintCorStationsUniqueList(), dynadjust::networkadjust::dna_adjust::PrintIgnoredAdjMeasurements(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsLinear(), dynadjust::networkadjust::dna_adjust::PrintPosUncertaintiesHeader(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::ReturnBadStationRecords().
PAD3()
const UINT16 PAD3 (3)
Referenced by dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_D(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsLinear(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformStation(), and dynadjust::referenceframe::dna_reftran::TransformStationRecords().
PAD()
const UINT16 PAD (5)
Referenced by dynadjust::referenceframe::dna_reftran::CalculateRotations(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), output_build(), output_version(), ReturnBadStationRecords(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel(), dynadjust::referenceframe::dna_reftran::TransformStation(), dynadjust::referenceframe::dna_reftran::TransformStationRecords(), and dynadjust::iostreams::dna_io_seg::write_seg_block().
CONSTRAINT()
const UINT16 CONSTRAINT (5)
Referenced by dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), and dynadjust::networkadjust::dna_adjust::PrintAdjStation().
LAT_EAST()
const UINT16 LAT_EAST (14)
Referenced by dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintPosUncertaintiesHeader(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::ReturnBadStationRecords().
LON_NORTH()
const UINT16 LON_NORTH (15)
Referenced by dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintPosUncertaintiesHeader(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::ReturnBadStationRecords().
HEIGHT()
const UINT16 HEIGHT (11)
Referenced by dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkplot::dna_plot::PrintCorrectionArrows(), dynadjust::networkadjust::dna_adjust::PrintCorStation(), dynadjust::networkadjust::dna_adjust::PrintCorStations(), and dynadjust::networkadjust::dna_adjust::PrintCorStationsUniqueList().
ZONE()
const UINT16 ZONE (8)
Referenced by dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), reportGridProperties(), and ReturnBadStationRecords().
XYZ()
const UINT16 XYZ (15)
Referenced by dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), and dynadjust::networkadjust::dna_adjust::PrintAdjStation().
STDDEV()
const UINT16 STDDEV (10)
Referenced by dynadjust::iostreams::dna_io_tbu::load_tbu_file(), dynadjust::iostreams::dna_io_adj::print_stn_info_col_header(), dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementsHeader(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), and dynadjust::networkadjust::dna_adjust::PrintMeasurementDatabaseID().
PAD5()
const UINT16 PAD5 (5)
COMMENT()
const UINT16 COMMENT (56)
Referenced by dynadjust::referenceframe::dna_reftran::CalculateRotations(), and dynadjust::iostreams::dna_io_adj::print_stn_info_col_header().
Variable Documentation
CORRELATION_MATRIX
const char* const CORRELATION_MATRIX = "CORR"
Definition at line 34 of file dnaconsts-iostream.hpp.
COVARIANCE_MATRIX
const char* const COVARIANCE_MATRIX = "COVA"
Definition at line 35 of file dnaconsts-iostream.hpp.
INFORMATION_MATRIX
const char* const INFORMATION_MATRIX = "INFO"
Definition at line 36 of file dnaconsts-iostream.hpp.
ENDSNX
const char* const ENDSNX = "%ENDSNX"
Definition at line 37 of file dnaconsts-iostream.hpp.
Referenced by dynadjust::iostreams::dna_io_snx::parse_discontinuity_file(), and dynadjust::iostreams::dna_io_snx::parse_sinex_data().
OUTPUTLINE
const char* const OUTPUTLINE = "--------------------------------------------------------------------------------"
Definition at line 41 of file dnaconsts-iostream.hpp.
Referenced by GenerateStatistics(), print_file_header(), dynadjust::iostreams::dna_io_snx::print_warnings(), dynadjust::networkadjust::dna_adjust::PrintAdjustmentStatus(), dynadjust::networkadjust::dna_adjust::PrintIteration(), dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations(), dynadjust::networkadjust::dna_adjust::PrintNetworkStationCorrections(), dynadjust::networkadjust::dna_adjust::PrintOutputFileHeaderInfo(), PrintOutputFileHeaderInfo(), PrintOutputFileHeaderInfo(), dynadjust::networkadjust::dna_adjust::PrintPositionalUncertainty(), dynadjust::CDnaProjectFile::PrintProjectFile(), ReturnBadStationRecords(), dynadjust::networksegment::dna_segment::SegmentNetwork(), and dynadjust::iostreams::dna_io_seg::write_seg_file().
MAX_RECORD_LENGTH
const int MAX_RECORD_LENGTH = 600
Definition at line 86 of file dnaconsts-iostream.hpp.
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessCsvFile(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessDatFile().
NULL_PAD
const int NULL_PAD = 4
Definition at line 87 of file dnaconsts-iostream.hpp.
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::OpenGridFile(), dynadjust::geoidinterpolation::dna_geoid_interpolation::PrintGridHeaderInfoBinary(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::PrintSubGridHeaderInfoBinary().
INT_BUF
const int INT_BUF = 4
Definition at line 88 of file dnaconsts-iostream.hpp.
IDENT_BUF
const int IDENT_BUF = 8
Definition at line 89 of file dnaconsts-iostream.hpp.
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateGridIndex(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::OpenGridFile().
HEADER_RECORD
const int HEADER_RECORD = 100
Definition at line 90 of file dnaconsts-iostream.hpp.
DATA_RECORD
const int DATA_RECORD = 100
Definition at line 91 of file dnaconsts-iostream.hpp.
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateGridIndex(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ExportToBinary(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::ReadAsciiShifts().
OVERVIEW_RECS
const int OVERVIEW_RECS = 8
Definition at line 92 of file dnaconsts-iostream.hpp.
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ExportToBinary(), dynadjust::geoidinterpolation::dna_geoid_interpolation::OpenGridFile(), dynadjust::geoidinterpolation::dna_geoid_interpolation::PrintGridHeaderInfoBinary(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::PrintSubGridHeaderInfoBinary().