DynAdjust: include/functions/dnafilepathfuncs.hpp File Reference
dnafilepathfuncs.hpp File Reference
#include <include/config/dnaconsts.hpp>
Functions
template<typename T>
T formPath (const T &folder, const T &file, const T &ext)
template<typename T>
T formPath (const T &folder, const T file)
template<typename T>
T leafStr (const T &filePath)
Function Documentation
formPath() [1/2]
template<typename T> T formPath (const T & folder, const T & file, const T & ext)
Definition at line 47 of file dnafilepathfuncs.hpp.
{
    return T(folder + FOLDER_SLASH + file + "." + ext);
}
Referenced by ImportDataFiles(), dynadjust::CDnaProjectFile::InitialiseAdjustSettings(), dynadjust::CDnaProjectFile::InitialiseGeoidSettings(), dynadjust::CDnaProjectFile::InitialiseImportSettings(), dynadjust::CDnaProjectFile::InitialiseReftranSettings(), dynadjust::dynamlinterop::dna_import::LoadDatabaseId(), dynadjust::networkadjust::dna_adjust::LoadDatabaseId(), dynadjust::referenceframe::dna_reftran::LoadDatabaseId(), dynadjust::CDnaProjectFile::LoadSettingAdjust(), dynadjust::CDnaProjectFile::LoadSettingGeoid(), dynadjust::CDnaProjectFile::LoadSettingImport(), dynadjust::CDnaProjectFile::LoadSettingReftran(), dynadjust::CDnaProjectFile::LoadSettingSegment(), main(), ParseCommandLineOptions(), ParseCommandLineOptions(), PrepareImportSegmentedData(), and ReturnBadStationRecords().
formPath() [2/2]
template<typename T> T formPath (const T & folder, const T file)
Definition at line 53 of file dnafilepathfuncs.hpp.
{
    return T(folder + FOLDER_SLASH + file);
}
leafStr()
template<typename T> T leafStr (const T & filePath)
Definition at line 59 of file dnafilepathfuncs.hpp.
{
    return boost::filesystem::path(filePath).filename().string();
}
Referenced by ExportDNA(), ExportDynaML(), ExportNTv2GridToAscii(), ExportNTv2GridToBinary(), ExportSinex(), dynadjust::CDnaProjectFile::FormCommandLineOptionsStringImport(), ImportDataFiles(), dynadjust::networkplot::dna_plot::InitialiseGMTFilenames(), dynadjust::CDnaProjectFile::InitialiseImportSettings(), main(), ParseCommandLineOptions(), dynadjust::dynamlinterop::dna_import::ParseInputFile(), PrepareImportSegmentedData(), dynadjust::CDnaProjectFile::PrintProjectFile(), PrintSummaryMessage(), and ReportExportedData().