DynAdjust: dynadjust/dnageoidint/dnageoidintDlg.cpp File Reference
dnageoidintDlg.cpp File Reference
#include "precompile.h"
#include "InputCoords.h"
#include "FileProc.h"
#include "dnageoidint.h"
#include "dnageoidintDlg.h"
#include "afxdialogex.h"
#include "RegProc.h"
Classes
class CAboutDlg
Functions
UINT CreateGridFile (LPVOID pParam)
Variables
BOOL CreatingGrid
const UINT lpIDArray []
Function Documentation
CreateGridFile()
UINT CreateGridFile (LPVOID pParam)
Definition at line 19 of file dnageoidintDlg.cpp.
{
    n_file_par grid;
    n_gridfileindex subgrid;
    CdnageoidintDlg* dlg = (CdnageoidintDlg*)pParam;
    strcpy(grid.filename, dlg->tUserSettings.GridFile);
    strcpy(grid.filetype, dlg->tUserSettings.GridType);
    try {
        dlg->m_dnaGeoid.CreateNTv2File(
        (char*)((LPCTSTR)dlg->m_strAusGeoidDatFile), &grid);
    }
    catch (const NetGeoidException& e) {
        dlg->PrintLogFileMessage(e.what());
        dlg->PrintLogFileMessage("\n\n");
        MessageBox(0, e.what(), dlg->m_dnaGeoid.ErrorCaption(e.error_no()).c_str(), MB_ICONEXCLAMATION);
    }
    CreatingGrid = FALSE;
    return 0;
}
References dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), CreatingGrid, dynadjust::exception::NetGeoidException::error_no(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ErrorCaption(), FALSE, file_par::filename, file_par::filetype, T_user::GridFile, T_user::GridType, CdnageoidintDlg::m_dnaGeoid, CdnageoidintDlg::m_strAusGeoidDatFile, CdnageoidintDlg::PrintLogFileMessage(), CdnageoidintDlg::tUserSettings, and dynadjust::exception::NetGeoidException::what().
Referenced by CdnageoidintDlg::OnFileCreateausgeoid().
Variable Documentation
CreatingGrid
BOOL CreatingGrid
Definition at line 17 of file dnageoidintDlg.cpp.
Referenced by CreateGridFile(), and CdnageoidintDlg::OnFileCreateausgeoid().
lpIDArray
const UINT lpIDArray[]
Initial value:
=
{
    IDS_TT_IDLEMESSAGE,
    IDS_TT_PROGRESS
}
Definition at line 152 of file dnageoidintDlg.cpp.
{
    IDS_TT_IDLEMESSAGE,
    IDS_TT_PROGRESS
};
Referenced by CdnageoidintDlg::OnInitDialog().