DynAdjust: dynadjust/dnageoidwrapper/dnageoidwrapper.hpp File Reference
dnageoidwrapper.hpp File Reference
#include <include/config/dnaexports.hpp>
#include <include/config/dnaversion.hpp>
#include <include/config/dnaconsts.hpp>
#include <include/config/dnaprojectfile.hpp>
#include <include/config/dnaoptions-interface.hpp>
#include <include/config/dnatypes-gui.hpp>
#include <include/config/dnaversion-stream.hpp>
#include <include/functions/dnafilepathfuncs.hpp>
#include <include/functions/dnatemplatefuncs.hpp>
#include <include/functions/dnastringfuncs.hpp>
#include <include/functions/dnatemplatedatetimefuncs.hpp>
#include <include/functions/dnastrmanipfuncs.hpp>
#include <dynadjust/dnageoid/dnageoid.hpp>
Functions
bool CreateNTv2Grid (dna_geoid_interpolation *g, const char *dat_gridfilePath, const n_file_par *grid)
bool createGridIndex (dna_geoid_interpolation *g, const char *gridfilePath, const char *gridfileType, const int &quiet)
bool reportGridProperties (dna_geoid_interpolation *g, const char *gridfilePath, const char *gridfileType)
bool InterpolateGridPoint (dna_geoid_interpolation *g, const char *gridfilePath, geoid_point *apInterpolant, const int &method, const int &coordinate_format, const std::string &inputLatitude, const std::string &inputLongitude)
bool InterpolateGridPointFile (dna_geoid_interpolation *g, const char *inputfilePath, const int &method, const int EllipsoidtoOrtho, const int &coordinate_format, bool exportDnaGeoidFile, const char *dnageofilePath, std::string &outputfilePath)
bool InterpolateGridBinaryStationFile (dna_geoid_interpolation *g, const std::string &bstnfilePath, const int &method, bool convertHeights, bool exportDnaGeoidFile, const char *dnageofilePath)
int ParseCommandLineOptions (const int &argc, char *argv[], const boost::program_options::variables_map &vm, project_settings &p)
Function Documentation
CreateNTv2Grid()
bool CreateNTv2Grid (dna_geoid_interpolation * g, const char * dat_gridfilePath, const n_file_par * grid)
Definition at line 27 of file dnageoidwrapper.cpp.
{
    // example:
    // geoid -d ausgeoid09_gda94_v1.01_clip_1x1.dat -c -g ausgeoid_clip_1.0.1.0.gsb --grid-shift radians --grid-version 1.0.1.0 --system-fr ___GDA94 --system-to ___AHD71 --sub-grid-n 1D-grid --creation 21.04.2021 --update 22.04.2021
    //
    std::cout << "+ Creating NTv2 geoid grid file from WINTER DAT file format..." << std::endl;
    try {
        g->CreateNTv2File(dat_gridfilePath, grid);
    }
    catch (const NetGeoidException& e) {
        std::cout << std::endl << "- Error: " << e.what() << std::endl;
        return false;
    }
    std::cout << std::endl;
    // Open the new grid file and print its properties
    if (!reportGridProperties(g, grid->filename, grid->filetype))
        return false;
    return true;
}
References dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), file_par::filename, file_par::filetype, reportGridProperties(), and dynadjust::exception::NetGeoidException::what().
Referenced by main().
createGridIndex()
bool createGridIndex (dna_geoid_interpolation * g, const char * gridfilePath, const char * gridfileType, const int & quiet)
Definition at line 175 of file dnageoidwrapper.cpp.
{
    if (!quiet)
        std::cout << "+ Opening grid file... ";
    try {
        g->CreateGridIndex(gridfilePath, gridfileType);
    }
    catch (const NetGeoidException& e) {
        std::cout << std::endl << "- Error: " << e.what() << std::endl;
        return false;
    }
    if (!quiet)
        std::cout << "done." << std::endl;
    return true;
}
References dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateGridIndex(), and dynadjust::exception::NetGeoidException::what().
Referenced by main().
reportGridProperties()
bool reportGridProperties (dna_geoid_interpolation * g, const char * gridfilePath, const char * gridfileType)
Definition at line 194 of file dnageoidwrapper.cpp.
{
    n_file_par grid_properties;
    try {
        g->ReportGridProperties(gridfilePath, gridfileType, &grid_properties);
    }
    catch (const NetGeoidException& e) {
        std::cout << std::endl << "- Error: " << e.what() << std::endl;
        return false;
    }
    bool isRadians(false);
    std::string shiftType(grid_properties.chGs_type);
    if (boost::iequals(trimstr(shiftType), "radians"))
        isRadians = true;
    std::string formattedLimit;
    std::cout << "+ Grid properties for " << gridfilePath << ":" << std::endl;
    std::cout << "  - GS_TYPE  = " << grid_properties.chGs_type << std::endl;                          // grid shift type (GS_TYPE)
    std::cout << "  - VERSION  = " << grid_properties.chVersion << std::endl;                          // grid file version (VERSION)
    std::cout << "  - SYSTEM_F = " << grid_properties.chSystem_f << std::endl;                        // reference system (SYSTEM_F)
    std::cout << "  - SYSTEM_T = " << grid_properties.chSystem_t << std::endl;                        // reference system (SYSTEM_T)
    std::cout << "  - MAJOR_F  = " << std::setprecision(3) << std::fixed << grid_properties.daf << std::endl;    // semi major of from system (MAJOR_F)
    std::cout << "  - MAJOR_T  = " << std::setprecision(3) << std::fixed << grid_properties.dat << std::endl;    // semi major of to system (MAJOR_T)
    std::cout << "  - MINOR_F  = " << std::setprecision(3) << std::fixed << grid_properties.dbf << std::endl;    // semi minor of from system (MINOR_F)
    std::cout << "  - MINOR_T  = " << std::setprecision(3) << std::fixed << grid_properties.dbt << std::endl;    // semi minor of to system (MINOR_T)
    std::cout << "  - NUM_OREC = " << grid_properties.iH_info << std::endl;                          // Number of header identifiers (NUM_OREC)
    std::cout << "  - NUM_SREC = " << grid_properties.iSubH_info << std::endl;                        // Number of sub-header idents (NUM_SREC)
    std::cout << "  - NUM_FILE = " << grid_properties.iNumsubgrids << std::endl;                        // number of subgrids in file (NUM_FILE)
    for (int i=0; i<grid_properties.iNumsubgrids; ++i)
    {
        std::string formattedLimit;
        std::cout << "  - SUBGRID " << i << ":" << std::endl;
        std::cout << "    - SUB_NAME = " << grid_properties.ptrIndex[i].chSubname << std::endl;        // name of subgrid (SUB_NAME)
        std::cout << "    - PARENT   = " << grid_properties.ptrIndex[i].chParent << std::endl;      // name of parent grid (PARENT)
        std::cout << "    - CREATED  = " << grid_properties.ptrIndex[i].chCreated << std::endl;        // date of creation (CREATED)
        std::cout << "    - UPDATED  = " << grid_properties.ptrIndex[i].chUpdated << std::endl;        // date of last file update (UPDATED)
        // In ptrIndex, all values for the limits of a grid are held in seconds, despite
        // whether the grid node records are in radians.
        // lower latitude (S_LAT)
        std::cout << "    - S_LAT    = " << std::right << std::setw(isRadians ? ZONE : REL) << grid_properties.ptrIndex[i].dSlat;
        formattedLimit = "(" + FormatDmsString(DegtoDms(grid_properties.ptrIndex[i].dSlat / DEG_TO_SEC), 6, true, false) + ")";
        std::cout << std::right << std::setw(MEASR) << formattedLimit << std::endl;
        // upper latitude (N_LAT)
        std::cout << "    - N_LAT    = " << std::right << std::setw(isRadians ? ZONE : REL) << grid_properties.ptrIndex[i].dNlat;
        formattedLimit = "(" + FormatDmsString(DegtoDms(grid_properties.ptrIndex[i].dNlat / DEG_TO_SEC), 6, true, false) + ")";
        std::cout << std::right << std::setw(MEASR) << formattedLimit << std::endl;
        // lower longitude (E_LONG)
        std::cout << "    - E_LONG   = " << std::right << std::setw(isRadians ? ZONE : REL) << grid_properties.ptrIndex[i].dElong;
        formattedLimit = "(" + FormatDmsString(DegtoDms(grid_properties.ptrIndex[i].dElong / DEG_TO_SEC), 6, true, false) + ")";
        std::cout << std::right << std::setw(MEASR) << formattedLimit << std::endl;
        // upper longitude (W_LONG)
        std::cout << "    - W_LONG   = " << std::right << std::setw(isRadians ? ZONE : REL) << grid_properties.ptrIndex[i].dWlong;
        formattedLimit = "(" + FormatDmsString(DegtoDms(grid_properties.ptrIndex[i].dWlong / DEG_TO_SEC), 6, true, false) + ")";
        std::cout << std::right << std::setw(MEASR) << formattedLimit << std::endl;
        std::cout << "    - LAT_INC  = " << std::fixed << grid_properties.ptrIndex[i].dLatinc << std::endl;      // latitude interval (LAT_INC)
        std::cout << "    - LONG_INC = " << std::fixed << grid_properties.ptrIndex[i].dLonginc << std::endl;        // longitude interval (LONG_INC)
        std::cout << "    - GS_COUNT = " << std::fixed << std::setprecision(0) << grid_properties.ptrIndex[i].lGscount;                     // number of nodes (GS_COUNT)
    }
    std::cout << std::endl;
    return true;
}
References gridfileindex::chCreated, file_par::chGs_type, gridfileindex::chParent, gridfileindex::chSubname, file_par::chSystem_f, file_par::chSystem_t, gridfileindex::chUpdated, file_par::chVersion, file_par::daf, file_par::dat, file_par::dbf, file_par::dbt, DEG_TO_SEC(), DegtoDms(), gridfileindex::dElong, gridfileindex::dLatinc, gridfileindex::dLonginc, gridfileindex::dNlat, gridfileindex::dSlat, gridfileindex::dWlong, FormatDmsString(), file_par::iH_info, file_par::iNumsubgrids, file_par::iSubH_info, gridfileindex::lGscount, MEASR(), file_par::ptrIndex, REL(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ReportGridProperties(), trimstr(), dynadjust::exception::NetGeoidException::what(), and ZONE().
Referenced by CreateNTv2Grid(), ExportNTv2GridToAscii(), ExportNTv2GridToBinary(), and main().
InterpolateGridPoint()
bool InterpolateGridPoint (dna_geoid_interpolation * g, const char * gridfilePath, geoid_point * apInterpolant, const int & method, const int & coordinate_format, const std::string & inputLatitude, const std::string & inputLongitude)
InterpolateGridPointFile()
bool InterpolateGridPointFile (dna_geoid_interpolation * g, const char * inputfilePath, const int & method, const int EllipsoidtoOrtho, const int & coordinate_format, bool exportDnaGeoidFile, const char * dnageofilePath, std::string & outputfilePath)
Definition at line 307 of file dnageoidwrapper.cpp.
{
    boost::filesystem::path inputFile(inputfilePath);
    if (inputFile.has_extension())
        outputfilePath = inputFile.stem().string() + "_out" + inputFile.extension().string();
    else
    {
        outputfilePath = inputfilePath;
        outputfilePath.append("_out");
    }
    char outfilePath[601];
    strcpy(outfilePath, outputfilePath.c_str());
    try {
        g->FileTransformation(inputfilePath, outfilePath,
            method, EllipsoidtoOrtho, coordinate_format,
            exportDnaGeoidFile, dnageofilePath);
    }
    catch (const NetGeoidException& e) {
        std::cout << std::endl << "- Error: " << e.what() << std::endl;
        return false;
    }
    return true;
} // InterpolateGridPointFile
References dynadjust::geoidinterpolation::dna_geoid_interpolation::FileTransformation(), and dynadjust::exception::NetGeoidException::what().
Referenced by main().
InterpolateGridBinaryStationFile()
bool InterpolateGridBinaryStationFile (dna_geoid_interpolation * g, const std::string & bstnfilePath, const int & method, bool convertHeights, bool exportDnaGeoidFile, const char * dnageofilePath)
Definition at line 338 of file dnageoidwrapper.cpp.
{
    try {
        g->PopulateBinaryStationFile(bstnfilePath, method, convertHeights,
            exportDnaGeoidFile, dnageofilePath);
    }
    catch (const NetGeoidException& e) {
        std::cout << std::endl << "- Error: " << e.what() << std::endl;
        return false;
    }
    return true;
} // InterpolateGridBinaryStationFile
References dynadjust::geoidinterpolation::dna_geoid_interpolation::PopulateBinaryStationFile(), and dynadjust::exception::NetGeoidException::what().
Referenced by main().
ParseCommandLineOptions()
int ParseCommandLineOptions (const int & argc, char * argv[], const boost::program_options::variables_map & vm, project_settings & p)
Definition at line 426 of file dnaadjustwrapper.cpp.
{
    // capture command line arguments
    for (int cmd_arg(0); cmd_arg<argc; ++cmd_arg)
    {
         p.a.command_line_arguments += argv[cmd_arg];
         p.a.command_line_arguments += " ";
    }
    if (vm.count(PROJECT_FILE))
    {
        if (boost::filesystem::exists(p.g.project_file))
        {
            try {
                CDnaProjectFile projectFile(p.g.project_file, adjustSetting);
                p = projectFile.GetSettings();
            }
            catch (const std::runtime_error& e) {
                std::cout << std::endl << "- Error: " << e.what() << std::endl;
                return EXIT_FAILURE;
            }
            return EXIT_SUCCESS;
        }
        std::cout << std::endl << "- Error: project file " << p.g.project_file << " does not exist." << std::endl << std::endl;
        return EXIT_FAILURE;
    }
    if (!vm.count(NETWORK_NAME))
    {
        std::cout << std::endl << "- Nothing to do - no network name specified. " << std::endl << std::endl;
        return EXIT_FAILURE;
    }
    p.g.project_file = formPath<std::string>(p.g.output_folder, p.g.network_name, "dnaproj");
    if (boost::filesystem::exists(p.g.project_file))
    {
        // update import settings from dnaproj file
        try {
            CDnaProjectFile projectFile(p.g.project_file, importSetting);
            p.i = projectFile.GetSettings().i;
        }
        catch (...) {
            // do nothing
        }
        // update geoid file name from dnaproj file (blank if geoid was not executed)
        try {
            CDnaProjectFile projectFile(p.g.project_file, geoidSetting);
            p.n = projectFile.GetSettings().n;
        }
        catch (...) {
            // do nothing
        }
        // update reftran settings from dnaproj file
        // Note, if reftran was not executed, reference frame and epoch will be set to
        // the frame and epoch captured on import.
        try {
            CDnaProjectFile projectFile(p.g.project_file, reftranSetting);
            p.r = projectFile.GetSettings().r;
        }
        catch (...) {
            // do nothing
        }
    }
    // binary station file location (output)
    if (vm.count(BIN_STN_FILE))
        p.a.bst_file = formPath<std::string>(p.g.input_folder, p.a.bst_file);
    else
        p.a.bst_file = formPath<std::string>(p.g.output_folder, p.g.network_name, "bst");
    // binary station file location (output)
    if (vm.count(BIN_MSR_FILE))
        p.a.bms_file = formPath<std::string>(p.g.input_folder, p.a.bms_file);
    else
        p.a.bms_file = formPath<std::string>(p.g.output_folder, p.g.network_name, "bms");
    if (!boost::filesystem::exists(p.a.bst_file) || !boost::filesystem::exists(p.a.bms_file))
    {
        cout_mutex.lock();
        std::cout << std::endl << "- Nothing to do: ";
        if (p.g.network_name.empty())
            std::cout << std::endl << "network name has not been specified specified, and " << std::endl << "               ";
        std::cout << p.a.bst_file << " and " << p.a.bms_file << " do not exist." << std::endl << std::endl;
        cout_mutex.unlock();
        return EXIT_FAILURE;
    }
    // output settings
    if (vm.count(OUTPUT_ADJ_STN_ITER))
        p.o._adj_stn_iteration = 1;
    if (vm.count(OUTPUT_ADJ_MSR_ITER))
        p.o._adj_msr_iteration = 1;
    if (vm.count(OUTPUT_CMP_MSR_ITER))
        p.o._cmp_msr_iteration = 1;
    if (vm.count(OUTPUT_ADJ_STAT_ITER))
        p.o._adj_stat_iteration = 1;
    if (vm.count(OUTPUT_ADJ_MSR) ||               // print adjusted measurements?
        vm.count(OUTPUT_ADJ_GNSS_UNITS) ||     // print alternative units for adjusted GNSS measurements?
        vm.count(OUTPUT_ADJ_MSR_SORTBY) ||     // print sort adjusted measurements?
        vm.count(OUTPUT_ADJ_MSR_TSTAT))         // print t-statistic for adjusted measurements?
        p.o._adj_msr_final = 1;
    if (vm.count(OUTPUT_ADJ_STN_BLOCKS))
        p.o._output_stn_blocks = 1;
    if (vm.count(OUTPUT_ADJ_MSR_BLOCKS))
        p.o._output_msr_blocks = 1;
    if (vm.count(OUTPUT_ADJ_STN_SORT_ORDER))
        p.o._sort_stn_file_order = 1;
    if (vm.count(MODE_SIMULTANEOUS))
        p.a.adjust_mode = SimultaneousMode;     // default
    else if (vm.count(MODE_PHASED_BLOCK1))
        p.a.adjust_mode = Phased_Block_1Mode;
    else if (vm.count(MODE_PHASED_MT))
    {
        p.a.multi_thread = 1;
        p.a.adjust_mode = PhasedMode;
    }
    else if (vm.count(MODE_PHASED))
        p.a.adjust_mode = PhasedMode;
    else if (vm.count(MODE_SIMULATION))
        p.a.adjust_mode = SimulationMode;
    // Report mode?
    if (vm.count(MODE_ADJ_REPORT))
    {
        p.a.report_mode = true;
        p.a.max_iterations = 0;
    }
    else if (p.a.max_iterations < 1)
        p.a.report_mode = true;
    if (vm.count(STAGED_ADJUSTMENT))
    {
        p.a.stage = true;
        p.a.multi_thread = false;
        p.a.adjust_mode = PhasedMode;
        //p.o._output_stn_blocks = true;
    }
    // Force inverse method for measurement variances to be the same as that which
    // is used for the inversion of the normals
    //if (vm.count(LSQ_INVERSE_METHOD))
    //  p.a.inverse_method_msr = p.a.inverse_method_lsq;
    if (vm.count(SCALE_NORMAL_UNITY))
        p.a.scale_normals_to_unity = 1;
    if (vm.count(OUTPUT_ADJ_MSR_TSTAT))
        p.o._adj_msr_tstat = 1;
    if (vm.count(OUTPUT_ADJ_MSR_DBID))
        p.o._database_ids = 1;
    if (vm.count(OUTPUT_IGNORED_MSRS))
        p.o._print_ignored_msrs = 1;
    if (vm.count(PURGE_STAGE_FILES))
        p.a.purge_stage_files = 1;
    if (vm.count(RECREATE_STAGE_FILES))
        p.a.recreate_stage_files = 1;
    if (vm.count(TYPE_B_GLOBAL))
        p.o._apply_type_b_global = 1;
    if (vm.count(TYPE_B_FILE))
        p.o._apply_type_b_file = 1;
    p.s.asl_file = formPath<std::string>(p.g.output_folder, p.g.network_name, "asl");  // associated stations list
    p.s.aml_file = formPath<std::string>(p.g.output_folder, p.g.network_name, "aml");  // associated measurements list
    p.a.map_file = formPath<std::string>(p.g.output_folder, p.g.network_name, "map");  // station names map
    // has a seg file name been specified?
    if (vm.count(SEG_FILE))
        p.a.seg_file = formPath<std::string>(p.g.input_folder, p.a.seg_file);
    else
        p.a.seg_file = formPath<std::string>(p.g.output_folder, p.g.network_name, "seg");
    if (vm.count(OUTPUT_APU_CORRELATIONS))
        p.o._output_pu_covariances = 1;
    // Set up file names dependent on adjustment mode
    p.o._xyz_file = p.o._adj_file =
        formPath<std::string>(p.g.output_folder, p.g.network_name);
    if (vm.count(OUTPUT_POS_UNCERTAINTY))
    {
        p.o._positional_uncertainty = 1;
        p.o._apu_file = p.o._adj_file;
    }
    if (vm.count(OUTPUT_STN_COR_FILE))
        p.o._cor_file = p.o._adj_file;
    switch (p.a.adjust_mode)
    {
    case Phased_Block_1Mode:
    case PhasedMode:
        p.o._adj_file += ".phased";
        p.o._xyz_file += ".phased";
        if (vm.count(OUTPUT_POS_UNCERTAINTY))
            p.o._apu_file += ".phased";
        if (vm.count(OUTPUT_STN_COR_FILE))
            p.o._cor_file += ".phased";
        if (p.a.adjust_mode == Phased_Block_1Mode)
        {
            p.o._adj_file += "-block1";
            p.o._xyz_file += "-block1";
            if (vm.count(OUTPUT_POS_UNCERTAINTY))
                p.o._apu_file += "-block1";
            if (vm.count(OUTPUT_STN_COR_FILE))
                p.o._cor_file += "-block1";
        }
        else if (p.a.stage)
        {
            p.o._adj_file += "-stage";
            p.o._xyz_file += "-stage";
            if (vm.count(OUTPUT_POS_UNCERTAINTY))
                p.o._apu_file += "-stage";
            if (vm.count(OUTPUT_STN_COR_FILE))
                p.o._cor_file += "-stage";
        }
        else if (p.a.multi_thread)
        {
            p.o._adj_file += "-mt";
            p.o._xyz_file += "-mt";
            if (vm.count(OUTPUT_POS_UNCERTAINTY))
                p.o._apu_file += "-mt";
            if (vm.count(OUTPUT_STN_COR_FILE))
                p.o._cor_file += "-mt";
        }
        break;
    case SimultaneousMode:
        p.o._adj_file += ".simult";
        p.o._xyz_file += ".simult";
        if (vm.count(OUTPUT_POS_UNCERTAINTY))
            p.o._apu_file += ".simult";
        if (vm.count(OUTPUT_STN_COR_FILE))
            p.o._cor_file += ".simult";
        break;
    }
    p.o._adj_file += ".adj";
    p.o._xyz_file += ".xyz";
    if (vm.count(OUTPUT_POS_UNCERTAINTY))
        p.o._apu_file += ".apu";
    if (vm.count(OUTPUT_STN_COR_FILE))
        p.o._cor_file += ".cor";
    if (vm.count(OUTPUT_STN_COR_FILE))
        p.o._init_stn_corrections = 1;
    if (vm.count(OUTPUT_STN_CORR))
        p.o._stn_corr = 1;
    if (vm.count(OUTPUT_MSR_TO_STN))
        p.o._msr_to_stn = 1;
    if (vm.count(TEST_INTEGRITY))
        p.i.test_integrity = 1;
    if (vm.count(EXPORT_XML_STN_FILE))
        p.o._export_xml_stn_file = 1;
    if (vm.count(EXPORT_XML_MSR_FILE))
        p.o._export_xml_msr_file = 1;
    if (vm.count(EXPORT_DNA_STN_FILE))
        p.o._export_dna_stn_file = 1;
    if (vm.count(EXPORT_DNA_MSR_FILE))
        p.o._export_dna_msr_file = 1;
    if (vm.count(EXPORT_SNX_FILE))
        p.o._export_snx_file = 1;
    return EXIT_SUCCESS;
}
References output_settings::_adj_file, output_settings::_adj_msr_final, output_settings::_adj_msr_iteration, output_settings::_adj_msr_tstat, output_settings::_adj_stat_iteration, output_settings::_adj_stn_iteration, output_settings::_apply_type_b_file, output_settings::_apply_type_b_global, output_settings::_apu_file, output_settings::_cmp_msr_iteration, output_settings::_cor_file, output_settings::_database_ids, output_settings::_export_dna_msr_file, output_settings::_export_dna_stn_file, output_settings::_export_snx_file, output_settings::_export_xml_msr_file, output_settings::_export_xml_stn_file, output_settings::_init_stn_corrections, output_settings::_m2s_file, output_settings::_msr_to_stn, output_settings::_output_msr_blocks, output_settings::_output_pu_covariances, output_settings::_output_stn_blocks, output_settings::_positional_uncertainty, output_settings::_print_ignored_msrs, output_settings::_sort_stn_file_order, output_settings::_stn_corr, output_settings::_xyz_file, project_settings::a, adjust_settings::adjust_mode, adjustSetting, import_settings::aml_file, segment_settings::aml_file, import_settings::apply_scaling, import_settings::asl_file, segment_settings::asl_file, BIN_MSR_FILE, BIN_STN_FILE, adjust_settings::bms_file, import_settings::bms_file, segment_settings::bms_file, adjust_settings::bst_file, geoid_settings::bst_file, import_settings::bst_file, segment_settings::bst_file, adjust_settings::command_line_arguments, geoid_settings::command_line_arguments, import_settings::command_line_arguments, segment_settings::command_line_arguments, geoid_settings::convert_heights, geoid_settings::coordinate_format, cout_mutex, CREATE_NTV2, DAT_FILEPATH, DDEG, DDEG_FORMAT, import_settings::dms_file, import_settings::dna_msrfile, import_settings::dna_stnfile, import_settings::dst_file, EPOCH, import_settings::epoch, EXPORT_AML_FILE, import_settings::export_aml_file, EXPORT_ASL_FILE, import_settings::export_asl_file, EXPORT_DISCONT_FILE, import_settings::export_discont_file, EXPORT_DNA_FILES, import_settings::export_dna_files, geoid_settings::export_dna_geo_file, EXPORT_DNA_MSR_FILE, EXPORT_DNA_STN_FILE, import_settings::export_dynaml, EXPORT_GEO_FILE, EXPORT_MAP_FILE, import_settings::export_map_file, EXPORT_NTV2_ASCII_FILE, EXPORT_NTV2_BINARY_FILE, EXPORT_SINGLE_XML_FILE, import_settings::export_single_xml_file, EXPORT_SNX_FILE, EXPORT_XML_FILES, EXPORT_XML_MSR_FILE, EXPORT_XML_STN_FILE, geoid_settings::file_mode, import_settings::flag_unused_stn, FLAG_UNUSED_STNS, FormatDateString(), formPath(), project_settings::g, geoid_settings::geo_file, geoidSetting, GET_MSRS_TRANSCENDING_BOX, dynadjust::CDnaProjectFile::GetSettings(), HSCALE, project_settings::i, IGNORE_INSUFFICIENT_MSRS, import_settings::ignore_insufficient_msrs, import_settings::ignore_similar_msr, IGNORE_SIMILAR_MSRS, import_settings::imp_file, import_settings::import_block, import_settings::import_block_number, IMPORT_CONTIG_NET, IMPORT_FILE, IMPORT_GEO_FILE, import_settings::import_geo_file, import_settings::import_network, import_settings::import_network_number, IMPORT_SEG_BLOCK, importSetting, import_settings::include_transcending_msrs, INPUT_FILE, geoid_settings::input_file, import_settings::input_files, general_settings::input_folder, INTERACTIVE, LATITUDE, leafStr(), LONGITUDE, LSCALE, adjust_settings::map_file, import_settings::map_file, segment_settings::map_file, adjust_settings::max_iterations, MODE_ADJ_REPORT, MODE_PHASED, MODE_PHASED_BLOCK1, MODE_PHASED_MT, MODE_SIMULATION, MODE_SIMULTANEOUS, adjust_settings::multi_thread, project_settings::n, NET_FILE, segment_settings::net_file, NETWORK_NAME, general_settings::network_name, NTV2_FILEPATH, project_settings::o, OUTPUT_ADJ_GNSS_UNITS, OUTPUT_ADJ_MSR, OUTPUT_ADJ_MSR_BLOCKS, OUTPUT_ADJ_MSR_DBID, OUTPUT_ADJ_MSR_ITER, OUTPUT_ADJ_MSR_SORTBY, OUTPUT_ADJ_MSR_TSTAT, OUTPUT_ADJ_STAT_ITER, OUTPUT_ADJ_STN_BLOCKS, OUTPUT_ADJ_STN_ITER, OUTPUT_ADJ_STN_SORT_ORDER, OUTPUT_APU_CORRELATIONS, OUTPUT_CMP_MSR_ITER, general_settings::output_folder, OUTPUT_IGNORED_MSRS, OUTPUT_MSR_TO_STN, OUTPUT_POS_UNCERTAINTY, OUTPUT_STN_COR_FILE, OUTPUT_STN_CORR, OVERRIDE_INPUT_FRAME, import_settings::override_input_rfame, Phased_Block_1Mode, PhasedMode, import_settings::prefer_single_x_as_g, PREFER_X_MSR_AS_G, PROJECT_FILE, general_settings::project_file, PSCALE, PURGE_STAGE_FILES, adjust_settings::purge_stage_files, project_settings::r, geoid_settings::rdat_geoid_file, RECREATE_STAGE_FILES, adjust_settings::recreate_stage_files, REFERENCE_FRAME, import_settings::reference_frame, reftranSetting, import_settings::remove_ignored_msr, REMOVE_IGNORED_MSRS, import_settings::rename_stations, adjust_settings::report_mode, project_settings::s, segment_settings::sap_file, SCALAR_FILE, import_settings::scalar_file, SCALE_NORMAL_UNITY, adjust_settings::scale_normals_to_unity, import_settings::search_nearby_stn, import_settings::search_similar_msr, import_settings::search_similar_msr_gx, SEG_FILE, adjust_settings::seg_file, import_settings::seg_file, segment_settings::seg_file, segmentSetting, import_settings::simulate_measurements, SIMULATE_MSR_FILE, import_settings::simulate_msrfile, SimulationMode, SimultaneousMode, SPLIT_CLUSTERS, import_settings::split_clusters, adjust_settings::stage, STAGED_ADJUSTMENT, STATION_RENAMING_FILE, str_upper(), stringFromToday(), SUMMARY, TEST_INTEGRITY, import_settings::test_integrity, TEST_NEARBY_STNS, TEST_SIMILAR_GNSS_MSRS, TEST_SIMILAR_MSRS, TYPE_B_FILE, TYPE_B_GLOBAL, import_settings::user_supplied_epoch, import_settings::user_supplied_frame, VSCALE, import_settings::xml_msrfile, import_settings::xml_outfile, and import_settings::xml_stnfile.
Referenced by main().