DynAdjust: include/functions/dnaiostreamfuncs.hpp File Reference
dnaiostreamfuncs.hpp File Reference
#include <include/config/dnaversion-stream.hpp>
#include <include/config/dnaconsts-iostream.hpp>
#include <include/config/dnaversion.hpp>
Functions
template<typename T>
T real_line_length_ascii (const T &line_length_ascii)
template<typename T>
void file_opener (T *stream, const std::string &str, std::ios_base::openmode mode=std::ios_base::out, const iosMode type=ascii, bool fileMustExist=false)
template<typename T>
void file_opener (T &stream, const std::string &str, std::ios_base::openmode mode=std::ios_base::out, const iosMode type=ascii, bool fileMustExist=false)
template<typename T>
void print_file_header (T &stream, const std::string &header)
Function Documentation
real_line_length_ascii()
template<typename T> T real_line_length_ascii (const T & line_length_ascii)
Definition at line 51 of file dnaiostreamfuncs.hpp.
{
    // return the real length of a line based on the system definition
    // of a "new line".  On Windows, a new line is comprised of two characters
    // namely, carriage return (CR, '\r') and line feed (LF, '\n'). On Unix
    // and Unix-like systems (Linux, mac OS, BSD, etc.), a new line is
    // comprised of a line feed (LF, '\n') only.
    //
#if defined(__linux) || defined(sun) || defined(__unix__) || defined(__APPLE__)
    // "real" line length = line_length_ascii + "\n"
    return line_length_ascii + 1;
#else // #if defined(_WIN32) || defined(__WIN32__)
    // "real" line length = line_length_ascii + "\r\n"
    return line_length_ascii + 2;
#endif
}
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::dna_geoid_interpolation().
file_opener() [1/2]
template<typename T> void file_opener (T * stream, const std::string & str, std::ios_base::openmode mode = std::ios_base::out, const iosMode type = ascii, bool fileMustExist = false)
Definition at line 73 of file dnaiostreamfuncs.hpp.
{
    file_opener(*stream, str, mode, type, fileMustExist);
}
References ascii, and file_opener().
Referenced by dynadjust::iostreams::dna_io_dna::create_file_pointer(), dynadjust::networkplot::dna_plot::CreateGMTCommandFiles(), dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ExportToAscii(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ExportToBinary(), file_opener(), dynadjust::geoidinterpolation::dna_geoid_interpolation::FileTransformation(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLFile(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLSepMeasurementFile(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLSepStationFile(), dynadjust::iostreams::dna_io_aml::load_aml_file(), dynadjust::iostreams::dna_io_asl::load_asl_file(), dynadjust::iostreams::dna_io_bms::load_bms_file(), dynadjust::iostreams::dna_io_bms::load_bms_file_meta(), dynadjust::iostreams::dna_io_bst::load_bst_file(), dynadjust::iostreams::dna_io_bst::load_bst_file_meta(), dynadjust::iostreams::dna_io_map::load_map_file(), dynadjust::iostreams::dna_io_scalar::load_scalar_file(), dynadjust::iostreams::dna_io_seg::load_seg_file(), dynadjust::iostreams::dna_io_seg::load_seg_file_header_f(), dynadjust::iostreams::dna_io_seg::load_stn_appearance(), dynadjust::iostreams::dna_io_tbu::load_tbu_file(), dynadjust::iostreams::dna_io_tpb::load_tpb_file(), dynadjust::iostreams::dna_io_tpb::load_tpp_file(), dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::dynamlinterop::dna_import::LoadDatabaseId(), dynadjust::networkadjust::dna_adjust::LoadDatabaseId(), dynadjust::referenceframe::dna_reftran::LoadDatabaseId(), dynadjust::dynamlinterop::dna_import::LoadDNAGeoidFile(), dynadjust::networksegment::dna_segment::LoadNetFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::CDnaProjectFile::LoadProjectFile(), main(), dynadjust::iostreams::dna_io_dna::open_file_pointer(), dynadjust::geoidinterpolation::dna_geoid_interpolation::OpenGridFile(), dynadjust::networkadjust::dna_adjust::OpenOutputFileStreams(), dynadjust::networkadjust::dna_adjust::OpenStageFileStreams(), dynadjust::dynamlinterop::dna_import::ParseDiscontinuities(), dynadjust::dynamlinterop::dna_import::ParseInputFile(), dynadjust::networkplot::dna_plot::PlotGnuplotDatFileMsrs(), dynadjust::networkplot::dna_plot::PlotGnuplotDatFileStns(), dynadjust::networkplot::dna_plot::PrintCorrectionArrows(), dynadjust::networkplot::dna_plot::PrintErrorEllipses(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML_Y(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoSNX(), dynadjust::networkplot::dna_plot::PrintGnuplotCommandFile(), dynadjust::networkplot::dna_plot::PrintMeasurementsDatFiles(), dynadjust::networkplot::dna_plot::PrintMeasurementsDatFilesBlock(), dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations(), dynadjust::networkadjust::dna_adjust::PrintNetworkStationCorrections(), dynadjust::networkplot::dna_plot::PrintPlateBoundaries(), dynadjust::networkadjust::dna_adjust::PrintPositionalUncertainty(), dynadjust::networkplot::dna_plot::PrintPositionalUncertainty(), dynadjust::CDnaProjectFile::PrintProjectFile(), dynadjust::networkplot::dna_plot::PrintStationLabels(), dynadjust::networkplot::dna_plot::PrintStationLabelsBlock(), dynadjust::networkplot::dna_plot::PrintStationsDataFile(), dynadjust::networkplot::dna_plot::PrintStationsDataFileBlock(), ReturnBadStationRecords(), SearchForSimilarMeasurements(), dynadjust::networksegment::dna_segment::SegmentNetwork(), dynadjust::dynamlinterop::dna_import::SerialiseDatabaseId(), dynadjust::dynamlinterop::dna_import::SerialiseDiscontTextFile(), dynadjust::referenceframe::dna_reftran::SerialiseDynaML(), dynadjust::referenceframe::dna_reftran::SerialiseDynaML(), dynadjust::dynamlinterop::dna_import::SerialiseMSR(), dynadjust::dynamlinterop::dna_import::SerialiseSTN(), dynadjust::dynamlinterop::dna_import::SimulateMSR(), dynadjust::iostreams::dna_io_aml::write_aml_file(), dynadjust::iostreams::dna_io_aml::write_aml_file_txt(), dynadjust::iostreams::dna_io_asl::write_asl_file(), dynadjust::iostreams::dna_io_asl::write_asl_file_txt(), dynadjust::iostreams::dna_io_bms::write_bms_file(), dynadjust::iostreams::dna_io_bms::write_bms_file(), dynadjust::iostreams::dna_io_bst::write_bst_file(), dynadjust::iostreams::dna_io_bst::write_bst_file(), dynadjust::iostreams::dna_io_map::write_map_file(), dynadjust::iostreams::dna_io_map::write_map_file_txt(), dynadjust::iostreams::dna_io_seg::write_seg_file(), dynadjust::iostreams::dna_io_seg::write_stn_appearance(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::WriteDNA1GeoidFile().
file_opener() [2/2]
template<typename T> void file_opener (T & stream, const std::string & str, std::ios_base::openmode mode = std::ios_base::out, const iosMode type = ascii, bool fileMustExist = false)
Definition at line 84 of file dnaiostreamfuncs.hpp.
{
    try {
        stream.open(str.c_str(), mode);
        stream.exceptions (/*std::ios_base::eofbit | */std::ios_base::badbit | std::ios_base::failbit);
        stream.iword(0) = type;
    }
    catch (const std::ios_base::failure& f) {
        std::stringstream ss;
        if (fileMustExist && !boost::filesystem::exists(str.c_str()))
            ss << "file_opener(): Can't find " << str << ".";
        else
            ss << "file_opener(): An error was encountered when opening " <<
                str << ". \n  Check that the file is not already opened.";
        ss << std::endl << f.what();
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    if (!stream.good()) {
        std::stringstream ss;
        ss << "file_opener(): An error was encountered when opening " <<
            str << ". \n  Check that the file is not already opened.";
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
}
References ascii.
print_file_header()
template<typename T> void print_file_header (T & stream, const std::string & header)
Definition at line 116 of file dnaiostreamfuncs.hpp.
{
    // Print formatted header
    stream << OUTPUTLINE << std::endl;
    stream << header << std::endl << std::endl;
    // version
    output_version(stream, true);
    stream << std::endl;
    // build
    output_build(stream, true);
    stream << std::endl;
    // File creation time
    stream << std::setw(PRINT_VAR_PAD) << std::left << "File created:";
    std::ostringstream datetime_ss;
    boost::posix_time::time_facet* p_time_output = new boost::posix_time::time_facet;
    std::locale special_locale (std::locale(""), p_time_output);
    // special_locale takes ownership of the p_time_output facet
    datetime_ss.imbue (special_locale);
    (*p_time_output).format("%A, %d %B %Y, %X");
    datetime_ss << boost::posix_time::second_clock::local_time();
    stream << datetime_ss.str().c_str() << std::endl;
}
References output_build(), output_version(), OUTPUTLINE, and PRINT_VAR_PAD().
Referenced by dynadjust::iostreams::dna_io_snx::print_warnings(), dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations(), dynadjust::networkadjust::dna_adjust::PrintNetworkStationCorrections(), dynadjust::networkadjust::dna_adjust::PrintOutputFileHeaderInfo(), PrintOutputFileHeaderInfo(), PrintOutputFileHeaderInfo(), dynadjust::networkadjust::dna_adjust::PrintPositionalUncertainty(), ReturnBadStationRecords(), dynadjust::networksegment::dna_segment::SegmentNetwork(), and dynadjust::iostreams::dna_io_seg::write_seg_file().