DynAdjust: include/functions/dnaintegermanipfuncs.hpp File Reference
dnaintegermanipfuncs.hpp File Reference
#include <include/config/dnatypes.hpp>
Functions
template<class T>
void initialiseIncrementingIntegerVector (std::vector< T > &vt, const T &size)
template<class T>
void initialiseIncrementingIntegerVector (std::vector< T > *vt, const T &size)
template<class T>
std::vector< T > createIncrementingIntegerVector (const T &size)
Function Documentation
initialiseIncrementingIntegerVector() [1/2]
template<class T> void initialiseIncrementingIntegerVector (std::vector< T > & vt, const T & size)
Definition at line 39 of file dnaintegermanipfuncs.hpp.
{
    vt.resize(size);
    T t(0);
    for_each(vt.begin(), vt.end(),
        [&t](T& t_){
            t_ = t++;
    });
}
Referenced by createIncrementingIntegerVector(), initialiseIncrementingIntegerVector(), dynadjust::iostreams::dna_io_asl::load_asl_file(), dynadjust::iostreams::dna_io_dna::prepare_sort_list(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsToStation(), dynadjust::dynamlinterop::dna_import::PrintMeasurementsToStations(), dynadjust::networkplot::dna_plot::PrintStationLabels(), and dynadjust::iostreams::dna_io_asl::write_asl_file_txt().
initialiseIncrementingIntegerVector() [2/2]
template<class T> void initialiseIncrementingIntegerVector (std::vector< T > * vt, const T & size)
Definition at line 50 of file dnaintegermanipfuncs.hpp.
{
    initialiseIncrementingIntegerVector(*vt, size);
}
References initialiseIncrementingIntegerVector().
createIncrementingIntegerVector()
template<class T> std::vector< T > createIncrementingIntegerVector (const T & size)
Definition at line 56 of file dnaintegermanipfuncs.hpp.
{
    std::vector<T> vt(size);
    initialiseIncrementingIntegerVector(vt, size);
    return vt;
}
References initialiseIncrementingIntegerVector().
Referenced by dynadjust::networkadjust::adjust_prepare_thread::operator()().