DynAdjust: include/io/dnaiodnatypes.hpp File Reference
dnaiodnatypes.hpp File Reference
#include <include/exception/dnaexception.hpp>
Classes
struct msr_database_t
struct dna_stn_fields
struct dna_msr_fields
struct _dna_stn_fields_100_< U >
class dna_stn_fields_100
struct _dna_msr_fields_100_< U >
class dna_msr_fields_100
struct _dna_stn_fields_300_< U >
class dna_stn_fields_300
struct _dna_msr_fields_300_< U >
class dna_msr_fields_300
struct _dna_stn_fields_301_< U >
class dna_stn_fields_301
struct _dna_msr_fields_301_< U >
class dna_msr_fields_301
Typedefs
typedef struct msr_database_t msr_database_id_map
typedef std::vector< msr_database_id_map > v_msr_database_id_map
typedef std::vector< msr_database_id_map > * pv_msr_database_id_map
typedef v_msr_database_id_map::iterator it_vdbid_t
Functions
template<typename U>
void assignDNASTNFieldParameters (const UINT16 *locs, const UINT16 *widths, dna_stn_fields &dflocs, dna_stn_fields &dfwidths)
template<typename U>
void determineDNASTNFieldParameters (const std::string &version, dna_stn_fields &dflocs, dna_stn_fields &dfwidths)
template<typename U>
void assignDNAMSRFieldParameters (const UINT16 *locs, const UINT16 *widths, dna_msr_fields &dflocs, dna_msr_fields &dfwidths)
template<typename U>
void determineDNAMSRFieldParameters (const std::string &version, dna_msr_fields &dflocs, dna_msr_fields &dfwidths, const U u=0)
Variables
template<class U>
const U _dna_stn_fields_100_< U >::_locations_ [8]
template<class U>
const U _dna_stn_fields_100_< U >::_widths_ [8]
template<class U>
const U _dna_msr_fields_100_< U >::_locations_ [24]
template<class U>
const U _dna_msr_fields_100_< U >::_widths_ [24]
template<class U>
const U _dna_stn_fields_300_< U >::_locations_ [8]
template<class U>
const U _dna_stn_fields_300_< U >::_widths_ [8]
template<class U>
const U _dna_msr_fields_300_< U >::_locations_ [24]
template<class U>
const U _dna_msr_fields_300_< U >::_widths_ [24]
template<class U>
const U _dna_stn_fields_301_< U >::_locations_ [8]
template<class U>
const U _dna_stn_fields_301_< U >::_widths_ [8]
template<class U>
const U _dna_msr_fields_301_< U >::_locations_ [24]
template<class U>
const U _dna_msr_fields_301_< U >::_widths_ [24]
Typedef Documentation
msr_database_id_map
typedef struct msr_database_t msr_database_id_map
v_msr_database_id_map
typedef std::vector<msr_database_id_map> v_msr_database_id_map
Definition at line 58 of file dnaiodnatypes.hpp.
pv_msr_database_id_map
typedef std::vector<msr_database_id_map> * pv_msr_database_id_map
Definition at line 58 of file dnaiodnatypes.hpp.
it_vdbid_t
typedef v_msr_database_id_map::iterator it_vdbid_t
Definition at line 59 of file dnaiodnatypes.hpp.
Function Documentation
assignDNASTNFieldParameters()
template<typename U> void assignDNASTNFieldParameters (const UINT16 * locs, const UINT16 * widths, dna_stn_fields & dflocs, dna_stn_fields & dfwidths)
Definition at line 445 of file dnaiodnatypes.hpp.
{
    dflocs.stn_name = locs[0];
    dflocs.stn_const = locs[1];
    dflocs.stn_type = locs[2];
    dflocs.stn_e_phi_x = locs[3];
    dflocs.stn_n_lam_y = locs[4];
    dflocs.stn_ht_z = locs[5];
    dflocs.stn_hemi_zo = locs[6];
    dflocs.stn_desc = locs[7];
    dfwidths.stn_name = widths[0];
    dfwidths.stn_const = widths[1];
    dfwidths.stn_type = widths[2];
    dfwidths.stn_e_phi_x = widths[3];
    dfwidths.stn_n_lam_y = widths[4];
    dfwidths.stn_ht_z = widths[5];
    dfwidths.stn_hemi_zo = widths[6];
    dfwidths.stn_desc = widths[7];
}
References dna_stn_fields::stn_const, dna_stn_fields::stn_desc, dna_stn_fields::stn_e_phi_x, dna_stn_fields::stn_hemi_zo, dna_stn_fields::stn_ht_z, dna_stn_fields::stn_n_lam_y, dna_stn_fields::stn_name, and dna_stn_fields::stn_type.
Referenced by determineDNASTNFieldParameters().
determineDNASTNFieldParameters()
template<typename U> void determineDNASTNFieldParameters (const std::string & version, dna_stn_fields & dflocs, dna_stn_fields & dfwidths)
Definition at line 469 of file dnaiodnatypes.hpp.
{
    if (boost::iequals(version, "3.01"))
    {
        assignDNASTNFieldParameters<U>(dna_stn_fields_301::_locations_,
            dna_stn_fields_301::_widths_,
            dflocs, dfwidths);
        return;
    }
    if (boost::iequals(version, "3.00"))
    {
        assignDNASTNFieldParameters<U>(dna_stn_fields_300::_locations_,
            dna_stn_fields_300::_widths_,
            dflocs, dfwidths);
        return;
    }
    if (boost::iequals(version, "1.00"))
    {
        assignDNASTNFieldParameters<U>(dna_stn_fields_100::_locations_,
            dna_stn_fields_100::_widths_,
            dflocs, dfwidths);
        return;
    }
}
References _dna_stn_fields_100_< UINT16 >::_locations_, _dna_stn_fields_300_< UINT16 >::_locations_, _dna_stn_fields_301_< UINT16 >::_locations_, _dna_stn_fields_100_< UINT16 >::_widths_, _dna_stn_fields_300_< UINT16 >::_widths_, _dna_stn_fields_301_< UINT16 >::_widths_, and assignDNASTNFieldParameters().
Referenced by dynadjust::iostreams::dna_io_dna::create_file_stn(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML(), dynadjust::iostreams::dna_io_dna::read_dna_header(), and dynadjust::dynamlinterop::dna_import::SerialiseSTN().
assignDNAMSRFieldParameters()
template<typename U> void assignDNAMSRFieldParameters (const UINT16 * locs, const UINT16 * widths, dna_msr_fields & dflocs, dna_msr_fields & dfwidths)
Definition at line 499 of file dnaiodnatypes.hpp.
{
    dflocs.msr_type = locs[0];
    dflocs.msr_ignore = locs[1];
    dflocs.msr_inst = locs[2];
    dflocs.msr_targ1 = locs[3];
    dflocs.msr_targ2 = locs[4];
    dflocs.msr_linear = locs[5];
    dflocs.msr_gps = locs[6];
    dflocs.msr_gps_vcv_1 = locs[7];
    dflocs.msr_gps_vcv_2 = locs[8];
    dflocs.msr_gps_vcv_3 = locs[9];
    dflocs.msr_gps_vscale = locs[10];
    dflocs.msr_gps_pscale = locs[11];
    dflocs.msr_gps_lscale = locs[12];
    dflocs.msr_gps_hscale = locs[13];
    dflocs.msr_gps_reframe = locs[14];
    dflocs.msr_gps_epoch = locs[15];
    dflocs.msr_ang_d = locs[16];
    dflocs.msr_ang_m = locs[17];
    dflocs.msr_ang_s = locs[18];
    dflocs.msr_stddev = locs[19];
    dflocs.msr_inst_ht = locs[20];
    dflocs.msr_targ_ht = locs[21];
    dflocs.msr_id_msr = locs[22];
    dflocs.msr_id_cluster = locs[23];
    dfwidths.msr_type = widths[0];
    dfwidths.msr_ignore = widths[1];
    dfwidths.msr_inst = widths[2];
    dfwidths.msr_targ1 = widths[3];
    dfwidths.msr_targ2 = widths[4];
    dfwidths.msr_linear = widths[5];
    dfwidths.msr_gps = widths[6];
    dfwidths.msr_gps_vcv_1 = widths[7];
    dfwidths.msr_gps_vcv_2 = widths[8];
    dfwidths.msr_gps_vcv_3 = widths[9];
    dfwidths.msr_gps_vscale = widths[10];
    dfwidths.msr_gps_pscale = widths[11];
    dfwidths.msr_gps_lscale = widths[12];
    dfwidths.msr_gps_hscale = widths[13];
    dfwidths.msr_gps_reframe = widths[14];
    dfwidths.msr_gps_epoch = widths[15];
    dfwidths.msr_ang_d = widths[16];
    dfwidths.msr_ang_m = widths[17];
    dfwidths.msr_ang_s = widths[18];
    dfwidths.msr_stddev = widths[19];
    dfwidths.msr_inst_ht = widths[20];
    dfwidths.msr_targ_ht = widths[21];
    dfwidths.msr_id_msr = widths[22];
    dfwidths.msr_id_cluster = widths[23];
}
References dna_msr_fields::msr_ang_d, dna_msr_fields::msr_ang_m, dna_msr_fields::msr_ang_s, dna_msr_fields::msr_gps, dna_msr_fields::msr_gps_epoch, dna_msr_fields::msr_gps_hscale, dna_msr_fields::msr_gps_lscale, dna_msr_fields::msr_gps_pscale, dna_msr_fields::msr_gps_reframe, dna_msr_fields::msr_gps_vcv_1, dna_msr_fields::msr_gps_vcv_2, dna_msr_fields::msr_gps_vcv_3, dna_msr_fields::msr_gps_vscale, dna_msr_fields::msr_id_cluster, dna_msr_fields::msr_id_msr, dna_msr_fields::msr_ignore, dna_msr_fields::msr_inst, dna_msr_fields::msr_inst_ht, dna_msr_fields::msr_linear, dna_msr_fields::msr_stddev, dna_msr_fields::msr_targ1, dna_msr_fields::msr_targ2, dna_msr_fields::msr_targ_ht, and dna_msr_fields::msr_type.
Referenced by determineDNAMSRFieldParameters().
determineDNAMSRFieldParameters()
template<typename U> void determineDNAMSRFieldParameters (const std::string & version, dna_msr_fields & dflocs, dna_msr_fields & dfwidths, const U u = 0)
Definition at line 556 of file dnaiodnatypes.hpp.
{
    if (boost::iequals(version, "3.01"))
    {
        assignDNAMSRFieldParameters<U>(dna_msr_fields_301::_locations_,
            dna_msr_fields_301::_widths_,
            dflocs, dfwidths);
        return;
    }
    if (boost::iequals(version, "3.00"))
    {
        assignDNAMSRFieldParameters<U>(dna_msr_fields_300::_locations_,
            dna_msr_fields_300::_widths_,
            dflocs, dfwidths);
        return;
    }
    if (boost::iequals(version, "1.00"))
    {
        assignDNAMSRFieldParameters<U>(dna_msr_fields_100::_locations_,
            dna_msr_fields_100::_widths_,
            dflocs, dfwidths);
        return;
    }
    std::stringstream ss;
    ss << " Unknown file version: " << version << std::endl;
    throw XMLInteropException(ss.str(), u);
}
References _dna_msr_fields_100_< UINT16 >::_locations_, _dna_msr_fields_300_< UINT16 >::_locations_, _dna_msr_fields_301_< UINT16 >::_locations_, _dna_msr_fields_100_< UINT16 >::_widths_, _dna_msr_fields_300_< UINT16 >::_widths_, _dna_msr_fields_301_< UINT16 >::_widths_, and assignDNAMSRFieldParameters().
Referenced by dynadjust::iostreams::dna_io_dna::create_file_msr(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML_Y(), dynadjust::iostreams::dna_io_dna::read_dna_header(), dynadjust::dynamlinterop::dna_import::SerialiseSTN(), and dynadjust::dynamlinterop::dna_import::SimulateMSR().
Variable Documentation
_dna_stn_fields_100_< U >::_locations_
template<class U> const U _dna_stn_fields_100_< U >::_locations_[8]
Initial value:
=
{
    0,
    10,
    14,
    17,
    31,
    45,
    59,
    63
}
Definition at line 109 of file dnaiodnatypes.hpp.
{
    0,      // station name
    10,     // constraints
    14,     // type
    17,     // e / phi / x
    31,     // n / lambda / y
    45,     // height / z
    59,     // hemisphere-zone
    63      // description
};
_dna_stn_fields_100_< U >::_widths_
template<class U> const U _dna_stn_fields_100_< U >::_widths_[8]
Initial value:
=
{
    10,
    3,
    3,
    14,
    14,
    14,
    3,
    128
}
Definition at line 122 of file dnaiodnatypes.hpp.
{
    10,     // station name
    3,      // constraints
    3,      // type
    14,     // e / phi / x
    14,     // n / lambda / y
    14,     // height / z
    3,      // hemisphere-zone
    128     // description
};
_dna_msr_fields_100_< U >::_locations_
template<class U> const U _dna_msr_fields_100_< U >::_locations_[24]
Initial value:
=
{
    0,
    1,
    2,
    12,
    22,
    32,
    32,
    46,
    57,
    68,
    32,
    46,
    57,
    68,
    79,
    89,
    46,
    50,
    54,
    60,
    69,
    76,
    83,
    93
}
Definition at line 149 of file dnaiodnatypes.hpp.
{
    0,      // msr type
    1,      // ignore
    2,      // instrument name
    12,     // target 1
    22,     // target 2
    32,     // linear measurement
    32,     // gps measurement
    46,     // gps vcv 1
    57,     // gps vcv 2
    68,     // gps vcv 3
    32,     // gps vscale
    46,     // gps pscale
    57,     // gps lscale
    68,     // gps hscale
    79,     // gps ref frame
    89,     // gps epoch
    46,     // angular d
    50,     // angular m
    54,     // angular s
    60,     // standard deviation
    69,     // inst height
    76,     // target height
    83,     // msr id
    93      // cluster id
};
_dna_msr_fields_100_< U >::_widths_
template<class U> const U _dna_msr_fields_100_< U >::_widths_[24]
Initial value:
=
{
    1,
    1,
    10,
    10,
    10,
    14,
    14,
    11,
    11,
    11,
    14,
    11,
    11,
    11,
    10,
    10,
    4,
    4,
    6,
    9,
    7,
    7,
    10,
    10
}
Definition at line 178 of file dnaiodnatypes.hpp.
{
    1,      // msr type
    1,      // ignore
    10,     // instrument name
    10,     // target 1
    10,     // target 2
    14,     // linear measurement
    14,     // gps measurement
    11,     // gps vcv 1
    11,     // gps vcv 2
    11,     // gps vcv 3
    14,     // gps vscale
    11,     // gps pscale
    11,     // gps lscale
    11,     // gps hscale
    10,     // gps ref frame
    10,     // gps epoch
    4,      // angular d
    4,      // angular m
    6,      // angular s
    9,      // standard deviation
    7,      // inst height
    7,      // target height
    10,     // msr id
    10      // cluster id
};
_dna_stn_fields_300_< U >::_locations_
template<class U> const U _dna_stn_fields_300_< U >::_locations_[8]
Initial value:
=
{
    0,
    20,
    24,
    27,
    41,
    55,
    69,
    73
}
Definition at line 223 of file dnaiodnatypes.hpp.
{
    0,      // station name
    20,     // constraints
    24,     // type
    27,     // e / phi / x
    41,     // n / lambda / y
    55,     // height / z
    69,     // hemisphere-zone
    73      // description
};
_dna_stn_fields_300_< U >::_widths_
template<class U> const U _dna_stn_fields_300_< U >::_widths_[8]
Initial value:
=
{
    20,
    3,
    3,
    14,
    14,
    14,
    3,
    128
}
Definition at line 236 of file dnaiodnatypes.hpp.
{
    20,     // station name
    3,      // constraints
    3,      // type
    14,     // e / phi / x
    14,     // n / lambda / y
    14,     // height / z
    3,      // hemisphere-zone
    128     // description
};
_dna_msr_fields_300_< U >::_locations_
template<class U> const U _dna_msr_fields_300_< U >::_locations_[24]
Initial value:
=
{
    0,
    1,
    2,
    22,
    42,
    62,
    62,
    76,
    90,
    104,
    62,
    69,
    76,
    83,
    90,
    104,
    76,
    80,
    82,
    90,
    99,
    106,
    118,
    128
}
Definition at line 264 of file dnaiodnatypes.hpp.
{
    0,      // msr type
    1,      // ignore
    2,      // instrument name
    22,     // target 1
    42,     // target 2
    62,     // linear measurement
    62,     // gps measurement
    76,     // gps vcv 1
    90,     // gps vcv 2
    104,    // gps vcv 3
    62,     // gps vscale
    69,     // gps pscale
    76,     // gps lscale
    83,     // gps hscale
    90,     // gps ref frame
    104,    // gps epoch
    76,     // angular d
    80,     // angular m
    82,     // angular s
    90,     // standard deviation
    99,     // inst height
    106,    // target height
    118,    // msr id
    128     // cluster id
};
_dna_msr_fields_300_< U >::_widths_
template<class U> const U _dna_msr_fields_300_< U >::_widths_[24]
Initial value:
=
{
    1,
    1,
    20,
    20,
    20,
    14,
    14,
    14,
    14,
    14,
    7,
    7,
    7,
    7,
    14,
    14,
    4,
    2,
    8,
    9,
    7,
    7,
    10,
    10
}
Definition at line 293 of file dnaiodnatypes.hpp.
{
    1,      // msr type
    1,      // ignore
    20,     // instrument name
    20,     // target 1
    20,     // target 2
    14,     // linear measurement
    14,     // gps measurement
    14,     // gps vcv 1
    14,     // gps vcv 2
    14,     // gps vcv 3
    7,      // gps vscale
    7,      // gps pscale
    7,      // gps lscale
    7,      // gps hscale
    14,     // gps ref frame
    14,     // gps epoch
    4,      // angular d
    2,      // angular m
    8,      // angular s
    9,      // standard deviation
    7,      // inst height
    7,      // target height
    10,     // msr id
    10      // cluster id
};
_dna_stn_fields_301_< U >::_locations_
template<class U> const U _dna_stn_fields_301_< U >::_locations_[8]
Initial value:
=
{
    0,
    20,
    24,
    27,
    47,
    67,
    87,
    91
}
Definition at line 338 of file dnaiodnatypes.hpp.
{
    0,      // station name
    20,     // constraints
    24,     // type
    27,     // e / phi / x
    47,     // n / lambda / y
    67,     // height / z
    87,     // hemisphere-zone
    91      // description
};
_dna_stn_fields_301_< U >::_widths_
template<class U> const U _dna_stn_fields_301_< U >::_widths_[8]
Initial value:
=
{
    20,
    3,
    3,
    20,
    20,
    20,
    3,
    128
}
Definition at line 351 of file dnaiodnatypes.hpp.
{
    20,     // station name
    3,      // constraints
    3,      // type
    20,     // e / phi / x
    20,     // n / lambda / y
    20,     // height / z
    3,      // hemisphere-zone
    128     // description
};
_dna_msr_fields_301_< U >::_locations_
template<class U> const U _dna_msr_fields_301_< U >::_locations_[24]
Initial value:
=
{
    0,
    1,
    2,
    22,
    42,
    62,
    62,
    82,
    102,
    122,
    62,
    72,
    82,
    92,
    102,
    122,
    76,
    80,
    82,
    90,
    99,
    106,
    142,
    152
}
Definition at line 379 of file dnaiodnatypes.hpp.
{
    0,      // msr type
    1,      // ignore
    2,      // instrument name
    22,     // target 1
    42,     // target 2
    62,     // linear measurement
    62,     // gps measurement
    82,     // gps vcv 1
    102,    // gps vcv 2
    122,    // gps vcv 3
    62,     // gps vscale
    72,     // gps pscale
    82,     // gps lscale
    92,     // gps hscale
    102,    // gps ref frame
    122,    // gps epoch
    76,     // angular d
    80,     // angular m
    82,     // angular s
    90,     // standard deviation
    99,     // inst height
    106,    // target height
    142,    // msr id
    152     // cluster id
};
_dna_msr_fields_301_< U >::_widths_
template<class U> const U _dna_msr_fields_301_< U >::_widths_[24]
Initial value:
=
{
    1,
    1,
    20,
    20,
    20,
    14,
    20,
    20,
    20,
    20,
    10,
    10,
    10,
    10,
    20,
    20,
    4,
    2,
    8,
    9,
    7,
    7,
    10,
    10
}
Definition at line 408 of file dnaiodnatypes.hpp.
{
    1,      // msr type
    1,      // ignore
    20,     // instrument name
    20,     // target 1
    20,     // target 2
    14,     // linear measurement
    20,     // gps measurement
    20,     // gps vcv 1
    20,     // gps vcv 2
    20,     // gps vcv 3
    10,     // gps vscale
    10,     // gps pscale
    10,     // gps lscale
    10,     // gps hscale
    20,     // gps ref frame
    20,     // gps epoch
    4,      // angular d
    2,      // angular m
    8,      // angular s
    9,      // standard deviation
    7,      // inst height
    7,      // target height
    10,     // msr id
    10      // cluster id
};