DynAdjust: include/functions/dnastrmanipfuncs.hpp File Reference
dnastrmanipfuncs.hpp File Reference
#include <include/functions/dnatemplatecalcfuncs.hpp>
Functions
template<class T, class U>
T val_uint (const U &value)
template<class T, class U>
T valorno_uint (const U &value, T &var)
template<class T>
T valorno_string (const T &value)
template<class T, class U>
T yesno_uint (const U &value)
template<class T>
std::string yesno_string (const T value)
template<class T>
std::string bool_string (const T value)
template<class T>
T findandreplace (const T &source, const T &find, const T &replace)
template<class T>
void str_toupper (std::string &strtext)
template<class S, class T>
S str_upper (const T *const strtext)
template<class S>
S str_upper (S &strtext)
template<class T>
T trimstr_ (const T &Src, const T &c)
template<class T>
T trimstrleft_ (const T &Src, const T &c)
template<class T>
T trimstrright_ (const T &Src, const T &c)
template<class T>
T trimstr (T &Src)
template<class T>
T trimstr (const T &Src)
template<class T>
T trimstrleft (const T &Src)
template<class T>
T trimstrright (const T &Src)
template<class T, class U>
std::string StringFromTW (const T &t, const U &width, const U &precision=0)
template<class T>
std::string StringFromT (const T &t, const int &precision=-1)
template<class T, class U, class S>
S double_string_width (const T value, const U &width)
template<class T>
T DoubleFromString (const std::string &str)
template<class T>
T FloatFromString (const std::string &str)
template<class T>
void DoubleFromString (T &t, const std::string &str)
template<class T>
void FloatFromString (T &t, const std::string &str)
template<class T>
bool DoubleFromString_ZeroCheck (T &t, const std::string &str)
template<class T>
std::enable_if< std::is_signed< T >::value, T >::type LongFromString (const std::string &str)
template<class T>
std::enable_if< std::is_unsigned< T >::value, T >::type LongFromString (const std::string &str)
template<class T>
void FromDmsString (T *d, const std::string &str)
template<class T>
T FromDmsString (const std::string &str)
template<class T>
void RadFromDmsString (T *d, const std::string &str)
template<class T>
void RadFromSecondsString (T *d, const std::string &str)
template<class T>
void SplitDelimitedString (const T &str, const T &separator, std::vector< T > *tokenList)
Function Documentation
val_uint()
template<class T, class U> T val_uint (const U & value)
Definition at line 58 of file dnastrmanipfuncs.hpp.
{
    return boost::lexical_cast<T, U>(value);
}
Referenced by dynadjust::dynamlinterop::dna_import::LoadDatabaseId(), dynadjust::networkadjust::dna_adjust::LoadDatabaseId(), dynadjust::referenceframe::dna_reftran::LoadDatabaseId(), dynadjust::iostreams::dna_io_snx::parse_sinex_discontinuities(), dynadjust::iostreams::dna_io_snx::parse_sinex_epochs(), dynadjust::dynamlinterop::dna_import::ParseDatabaseClusterId(), dynadjust::dynamlinterop::dna_import::ParseDatabaseMsrId(), dynadjust::CDnaProjectFile::PrintProjectFile(), and dynadjust::iostreams::dna_io_dna::read_dna_header().
valorno_uint()
template<class T, class U> T valorno_uint (const U & value, T & var)
Definition at line 64 of file dnastrmanipfuncs.hpp.
{
    if (boost::iequals(value, "no"))
        return var = 0;
    var = 1;
    return boost::lexical_cast<T, U>(value);
}
Referenced by dynadjust::CDnaProjectFile::LoadSettingImport().
valorno_string()
template<class T> T valorno_string (const T & value)
Definition at line 74 of file dnastrmanipfuncs.hpp.
{
    if (boost::iequals(value, "no"))
        return "";
    return value;
}
Referenced by dynadjust::CDnaProjectFile::LoadSettingImport().
yesno_uint()
template<class T, class U> T yesno_uint (const U & value)
Definition at line 82 of file dnastrmanipfuncs.hpp.
{
    if (boost::iequals(value, "yes"))
        return 1;
    //if (boost::iequals(value, "no"))
        return 0;
}
Referenced by dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::CDnaProjectFile::LoadSettingAdjust(), dynadjust::CDnaProjectFile::LoadSettingGeneral(), dynadjust::CDnaProjectFile::LoadSettingGeoid(), dynadjust::CDnaProjectFile::LoadSettingImport(), dynadjust::CDnaProjectFile::LoadSettingOutput(), and dynadjust::CDnaProjectFile::LoadSettingSegment().
yesno_string()
template<class T> std::string yesno_string (const T value)
Definition at line 92 of file dnastrmanipfuncs.hpp.
{
    if (value == 1)
        return std::string("yes");
    else
        return std::string("no");
}
Referenced by main(), PrintOutputFileHeaderInfo(), and dynadjust::CDnaProjectFile::PrintProjectFile().
bool_string()
template<class T> std::string bool_string (const T value)
Definition at line 101 of file dnastrmanipfuncs.hpp.
{
    if (value)
        return std::string("true");
    else
        return std::string("false");
}
findandreplace()
template<class T> T findandreplace (const T & source, const T & find, const T & replace)
Definition at line 110 of file dnastrmanipfuncs.hpp.
{
    size_t index;
    T str = source;
    while ((index = str.find(find)) != T::npos)
        str.replace(index, find.length(), replace);
    return str;
}
Referenced by dateSINEXFormat(), DnaStation_pimpl::Description(), ExportSinex(), and dynadjust::iostreams::dna_io_snx::serialise_meta().
str_toupper()
template<class T> void str_toupper (std::string & strtext)
Definition at line 121 of file dnastrmanipfuncs.hpp.
{
    transform(strtext.begin(), strtext.end(), strtext.begin(), (T(*)(T))toupper);
}
Referenced by dynadjust::networkadjust::dna_adjust::ApplyAdditionalConstraints(), dynadjust::dynamlinterop::dna_import::ExcludeMeasurementTypes(), dynadjust::dynamlinterop::dna_import::IncludeMeasurementTypes(), dynadjust::iostreams::dna_io_tpb::load_tpb_file(), main(), ParseCommandLineOptions(), ProcessGMTPlot(), dynadjust::measurements::CDnaMeasurement::SetType(), str_upper(), and str_upper().
str_upper() [1/2]
template<class S, class T> S str_upper (const T *const strtext)
Definition at line 128 of file dnastrmanipfuncs.hpp.
{
    S strtext_(strtext);
    str_toupper<int>(strtext_);
    return strtext_;
}
References str_toupper().
Referenced by main(), and ParseCommandLineOptions().
str_upper() [2/2]
template<class S> S str_upper (S & strtext)
Definition at line 137 of file dnastrmanipfuncs.hpp.
{
    str_toupper<int>(strtext);
    return strtext;
}
References str_toupper().
trimstr_()
template<class T> T trimstr_ (const T & Src, const T & c)
Definition at line 144 of file dnastrmanipfuncs.hpp.
{
    size_t p2 = Src.find_last_not_of(c);
    if (p2 == std::string::npos)
        return std::string();
    size_t p1 = Src.find_first_not_of(c);
    if (p1 == std::string::npos)
        p1 = 0;
    return Src.substr(p1, (p2-p1)+1);
}
Referenced by trimstr(), and trimstr().
trimstrleft_()
template<class T> T trimstrleft_ (const T & Src, const T & c)
Definition at line 156 of file dnastrmanipfuncs.hpp.
{
    size_t p2 = Src.length();
    size_t p1 = Src.find_first_not_of(c);
    if (p1 == std::string::npos)
        p1 = 0;
    return Src.substr(p1, (p2-p1)+1);
}
Referenced by trimstrleft().
trimstrright_()
template<class T> T trimstrright_ (const T & Src, const T & c)
Definition at line 166 of file dnastrmanipfuncs.hpp.
{
    size_t p2 = Src.find_last_not_of(c);
    if (p2 == std::string::npos)
        return std::string();
    return Src.substr(0, p2+1);
}
Referenced by trimstrright().
trimstr() [1/2]
template<class T> T trimstr (T & Src)
Definition at line 175 of file dnastrmanipfuncs.hpp.
                  {
    return trimstr_(Src, static_cast<T>(" \r\n"));
}
References trimstr_().
Referenced by dynadjust::datum_parameters::CDnaEllipsoid::CDnaEllipsoid(), dynadjust::geoidinterpolation::dna_geoid_interpolation::CreateNTv2File(), double_string_width(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ExportToAscii(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ExportToBinary(), dynadjust::geoidinterpolation::dna_geoid_interpolation::FileTransformation(), dynadjust::CDnaProjectFile::FormCommandLineOptionsStringImport(), dynadjust::iostreams::dna_io_scalar::load_scalar_file(), dynadjust::iostreams::dna_io_seg::load_seg_file(), dynadjust::iostreams::dna_io_tbu::load_tbu_file(), dynadjust::iostreams::dna_io_tpb::load_tpb_file(), dynadjust::iostreams::dna_io_tpb::load_tpp_file(), dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::dynamlinterop::dna_import::LoadDNAGeoidFile(), dynadjust::networksegment::dna_segment::LoadNetFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::CDnaProjectFile::LoadProjectFile(), dynadjust::CDnaProjectFile::LoadSettingGeneral(), dynadjust::CDnaProjectFile::LoadSettingImport(), main(), dynadjust::geoidinterpolation::dna_geoid_interpolation::OpenGridFile(), dynadjust::iostreams::dna_io_snx::parse_sinex_discontinuities(), dynadjust::iostreams::dna_io_snx::parse_sinex_epochs(), dynadjust::iostreams::dna_io_snx::parse_sinex_sites(), dynadjust::iostreams::dna_io_snx::parse_sinex_stn(), dynadjust::dynamlinterop::dna_import::ParseAngularValue(), dynadjust::dynamlinterop::dna_import::ParseDatabaseClusterId(), dynadjust::dynamlinterop::dna_import::ParseDatabaseMsrId(), dynadjust::dynamlinterop::dna_import::ParseDNAMSR(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRAngular(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRCoordinate(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRDirections(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRGPSBaselines(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRGPSPoints(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRLinear(), dynadjust::dynamlinterop::dna_import::ParseDNASTN(), dynadjust::dynamlinterop::dna_import::ParseEpochValue(), dynadjust::dynamlinterop::dna_import::ParseGPSMsrValue(), dynadjust::dynamlinterop::dna_import::ParseGPSVarValue(), dynadjust::dynamlinterop::dna_import::ParseInstHeightValue(), dynadjust::dynamlinterop::dna_import::ParseInstrumentValue(), dynadjust::dynamlinterop::dna_import::ParseLinearValue(), dynadjust::dynamlinterop::dna_import::ParseMsrCountValue(), dynadjust::dynamlinterop::dna_import::ParseRefFrameValue(), dynadjust::dynamlinterop::dna_import::ParseScaleHValue(), dynadjust::dynamlinterop::dna_import::ParseScaleLValue(), dynadjust::dynamlinterop::dna_import::ParseScalePValue(), dynadjust::dynamlinterop::dna_import::ParseScaleVValue(), dynadjust::dynamlinterop::dna_import::ParseStdDevValue(), dynadjust::dynamlinterop::dna_import::ParseTarget2Value(), dynadjust::dynamlinterop::dna_import::ParseTargetValue(), dynadjust::dynamlinterop::dna_import::ParseTargHeightValue(), epoch_pimpl::post_type(), referenceframe_pimpl::post_type(), dynadjust::networkadjust::dna_adjust::PrintOutputFileHeaderInfo(), dynadjust::networkplot::dna_plot::PrintStationLabel(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessCsvFile(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessDatFile(), processFile(), dynadjust::iostreams::dna_io_dna::read_dna_header(), dynadjust::iostreams::dna_io_dna::read_ren_data(), dynadjust::iostreams::dna_io_tbu::read_tbu_header(), dynadjust::iostreams::dna_io_base::readApp(), dynadjust::iostreams::dna_io_base::readDate(), dynadjust::iostreams::dna_io_base::readVersion(), reportGridProperties(), dynadjust::measurements::CDnaStation::SetComment(), dynadjust::measurements::CDnaStation::SetConstraints(), dynadjust::measurements::CDnaGpsPoint::SetCoordType(), dynadjust::measurements::CDnaGpsPointCluster::SetCoordType(), dynadjust::measurements::CDnaStation::SetCoordType(), dynadjust::datum_parameters::CDnaDatum::SetDatum(), dynadjust::datum_parameters::CDnaDatum::SetDatumFromEpsg(), dynadjust::measurements::CDnaStation::SetDescription(), dynadjust::measurements::CDnaStation::SetEpoch(), dynadjust::measurements::CDnaMeasurement::SetEpsg(), dynadjust::measurements::CDnaStation::SetEpsg(), dynadjust::measurements::CDnaMeasurement::SetFirst(), dynadjust::measurements::CDnaStation::SetHeight(), dynadjust::measurements::CDnaStation::SetHemisphereZone(), dynadjust::measurements::CDnaGpsBaseline::SetHscale(), dynadjust::measurements::CDnaGpsBaselineCluster::SetHscale(), dynadjust::measurements::CDnaGpsPointCluster::SetHscale(), dynadjust::measurements::CDnaDirection::SetInstrumentHeight(), dynadjust::measurements::CDnaDistance::SetInstrumentHeight(), dynadjust::measurements::CDnaGpsBaseline::SetLscale(), dynadjust::measurements::CDnaGpsBaselineCluster::SetLscale(), dynadjust::measurements::CDnaGpsPointCluster::SetLscale(), dynadjust::measurements::CDnaCovariance::SetM11(), dynadjust::measurements::CDnaCovariance::SetM12(), dynadjust::measurements::CDnaCovariance::SetM13(), dynadjust::measurements::CDnaCovariance::SetM21(), dynadjust::measurements::CDnaCovariance::SetM22(), dynadjust::measurements::CDnaCovariance::SetM23(), dynadjust::measurements::CDnaCovariance::SetM31(), dynadjust::measurements::CDnaCovariance::SetM32(), dynadjust::measurements::CDnaCovariance::SetM33(), dynadjust::measurements::CDnaStation::SetName(), dynadjust::measurements::CDnaStation::SetOriginalName(), dynadjust::measurements::CDnaGpsBaseline::SetPscale(), dynadjust::measurements::CDnaGpsBaselineCluster::SetPscale(), dynadjust::measurements::CDnaGpsPointCluster::SetPscale(), dynadjust::measurements::CDnaStation::SetReferenceFrame(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaXX(), dynadjust::measurements::CDnaGpsPoint::SetSigmaXX(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaXY(), dynadjust::measurements::CDnaGpsPoint::SetSigmaXY(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaXZ(), dynadjust::measurements::CDnaGpsPoint::SetSigmaXZ(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaYY(), dynadjust::measurements::CDnaGpsPoint::SetSigmaYY(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaYZ(), dynadjust::measurements::CDnaGpsPoint::SetSigmaYZ(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaZZ(), dynadjust::measurements::CDnaGpsPoint::SetSigmaZZ(), dynadjust::measurements::CDnaAngle::SetStdDev(), dynadjust::measurements::CDnaCoordinate::SetStdDev(), dynadjust::measurements::CDnaDirection::SetStdDev(), dynadjust::measurements::CDnaDirectionSet::SetStdDev(), dynadjust::measurements::CDnaDistance::SetStdDev(), dynadjust::measurements::CDnaHeight::SetStdDev(), dynadjust::measurements::CDnaHeightDifference::SetStdDev(), dynadjust::measurements::CDnaAngle::SetTarget(), dynadjust::measurements::CDnaDirection::SetTarget(), dynadjust::measurements::CDnaDirectionSet::SetTarget(), dynadjust::measurements::CDnaDistance::SetTarget(), dynadjust::measurements::CDnaGpsBaseline::SetTarget(), dynadjust::measurements::CDnaGpsBaselineCluster::SetTarget(), dynadjust::measurements::CDnaHeightDifference::SetTarget(), dynadjust::measurements::CDnaAngle::SetTarget2(), dynadjust::measurements::CDnaDirection::SetTargetHeight(), dynadjust::measurements::CDnaDistance::SetTargetHeight(), dynadjust::measurements::CDnaDirectionSet::SetTotal(), dynadjust::measurements::CDnaGpsBaselineCluster::SetTotal(), dynadjust::measurements::CDnaGpsPointCluster::SetTotal(), dynadjust::measurements::CDnaCovariance::SetType(), dynadjust::measurements::CDnaMeasurement::SetType(), dynadjust::measurements::CDnaAngle::SetValue(), dynadjust::measurements::CDnaCoordinate::SetValue(), dynadjust::measurements::CDnaDirection::SetValue(), dynadjust::measurements::CDnaDirectionSet::SetValue(), dynadjust::measurements::CDnaDistance::SetValue(), dynadjust::measurements::CDnaHeight::SetValue(), dynadjust::measurements::CDnaHeightDifference::SetValue(), dynadjust::measurements::CDnaGpsBaseline::SetVscale(), dynadjust::measurements::CDnaGpsBaselineCluster::SetVscale(), dynadjust::measurements::CDnaGpsPointCluster::SetVscale(), dynadjust::measurements::CDnaGpsBaseline::SetX(), dynadjust::measurements::CDnaGpsPoint::SetX(), dynadjust::measurements::CDnaStation::SetXAxis(), dynadjust::measurements::CDnaGpsBaseline::SetY(), dynadjust::measurements::CDnaGpsPoint::SetY(), dynadjust::measurements::CDnaStation::SetYAxis(), dynadjust::measurements::CDnaGpsBaseline::SetZ(), dynadjust::measurements::CDnaGpsPoint::SetZ(), dynadjust::measurements::CDnaStation::SetZAxis(), StringFromTW(), dynadjust::referenceframe::dna_reftran::TransformMeasurementRecords(), and dynadjust::referenceframe::dna_reftran::TransformStationRecords().
trimstr() [2/2]
template<class T> T trimstr (const T & Src)
Definition at line 179 of file dnastrmanipfuncs.hpp.
{
    return trimstr_(Src, static_cast<T>(" \r\n"));
}
References trimstr_().
trimstrleft()
template<class T> T trimstrleft (const T & Src)
Definition at line 183 of file dnastrmanipfuncs.hpp.
{
    return trimstrleft_(Src, static_cast<T>(" \r\n"));
}
References trimstrleft_().
trimstrright()
template<class T> T trimstrright (const T & Src)
Definition at line 187 of file dnastrmanipfuncs.hpp.
{
    return trimstrright_(Src, static_cast<T>(" \r\n"));
}
References trimstrright_().
StringFromTW()
template<class T, class U> std::string StringFromTW (const T & t, const U & width, const U & precision = 0)
Definition at line 192 of file dnastrmanipfuncs.hpp.
{
    std::stringstream ss;
    // Assume number at precision prints within width
    ss << std::setw(width) << std::fixed << std::right << std::setprecision(precision) << t;
    int trim = (int)trimstr(ss.str()).length() - width;
    // Formatted string length is less than or equal to the fixed width
    if (trim <= 0)
        return ss.str();
    ss.str("");
    // Formatted string length exceeds fixed width by trim.
    // Use scientific notation if the overflow is
    // greater than the precision
    if (trim > 0)
    {
        // scientific notation requires 6 or 5
        // characters (e.g. -1e+00 or 1e+00), not
        // including the fractional part
        if (width < UINT32(t < 0. ? 6 : 5))
        {
            // insufficient space for scientific notation!!!
            ss << std::setw(width) << std::string(width, '#');
            return ss.str();
        }
        int prec1 = width - (t < 0. ? 6 : 5);
        // if precision is required, an extra space is needed for
        // the decimal point, so reduce by one.
        if (prec1 > 0)
            prec1--;
        int prec = std::min<int>(precision, prec1);
        ss << std::setw(width) << std::scientific << std::right << std::setprecision(prec) << t;
    }
    else
    {
        int prec = precision - trim;
        if (prec < 0)
            prec = 0;
        ss << std::setw(width) << std::fixed << std::right << std::setprecision(prec) << t;
    }
    return ss.str();
}
References trimstr().
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementStatistics(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintCorStation(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsLinear(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), dynadjust::measurements::CDnaAngle::WriteDNAMsr(), dynadjust::measurements::CDnaCoordinate::WriteDNAMsr(), dynadjust::measurements::CDnaDirection::WriteDNAMsr(), dynadjust::measurements::CDnaDirectionSet::WriteDNAMsr(), dynadjust::measurements::CDnaDistance::WriteDNAMsr(), dynadjust::measurements::CDnaHeight::WriteDNAMsr(), and dynadjust::measurements::CDnaHeightDifference::WriteDNAMsr().
StringFromT()
template<class T> std::string StringFromT (const T & t, const int & precision = -1)
Definition at line 243 of file dnastrmanipfuncs.hpp.
{
    std::stringstream ss;
    if (precision < 0)
        ss << t;
    else
        ss << std::setprecision(precision) << std::fixed << t;
    return ss.str();
}
Referenced by dynadjust::networkplot::dna_plot::CreateGMTCommandFile(), dynadjust::networkplot::dna_plot::InitialiseGMTFilenames(), main(), dynadjust::dynamlinterop::dna_import::ParseAngularValue(), dynadjust::geoidinterpolation::dna_geoid_interpolation::PopulateStationRecords(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), and dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_D().
double_string_width()
template<class T, class U, class S> S double_string_width (const T value, const U & width)
Definition at line 254 of file dnastrmanipfuncs.hpp.
{
    S s;
    char* cvalue = new char[width+1];
#if defined(_WIN32) || defined(__WIN32__)
    _snprintf(cvalue, width, "%.2f", value);
#else
    snprintf(cvalue, width, "%.2f", value);
#endif
    s = cvalue;
    delete[] cvalue;
    return trimstr(s);
}
References trimstr().
Referenced by dynadjust::measurements::CDnaGpsBaseline::WriteDNAMsr(), and dynadjust::measurements::CDnaGpsPoint::WriteDNAMsr().
DoubleFromString() [1/2]
template<class T> T DoubleFromString (const std::string & str)
Definition at line 278 of file dnastrmanipfuncs.hpp.
{
    T t(0.);
    parse(str.begin(), str.end(), double_, t);
    return t;
}
Referenced by dynadjust::iostreams::dna_io_tbu::assign_typeb_values_global(), dynadjust::iostreams::dna_io_tbu::assign_typeb_values_local(), dynadjust::iostreams::dna_io_tpb::load_tpb_file(), dynadjust::iostreams::dna_io_tpb::load_tpp_file(), dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::dynamlinterop::dna_import::LoadDNAGeoidFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::CDnaProjectFile::LoadSettingAdjust(), dynadjust::CDnaProjectFile::LoadSettingImport(), dynadjust::CDnaProjectFile::LoadSettingOutput(), main(), dynadjust::iostreams::dna_io_snx::parse_sinex_stn(), dynadjust::dynamlinterop::dna_import::ParseAngularValue(), ParseDmsString(), dynadjust::dynamlinterop::dna_import::ParseStdDevValue(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessDatFile(), dynadjust::measurements::CDnaStation::SetHeight(), dynadjust::measurements::CDnaGpsBaseline::SetHscale(), dynadjust::measurements::CDnaGpsBaselineCluster::SetHscale(), dynadjust::measurements::CDnaGpsPointCluster::SetHscale(), dynadjust::measurements::CDnaGpsBaseline::SetLscale(), dynadjust::measurements::CDnaGpsBaselineCluster::SetLscale(), dynadjust::measurements::CDnaGpsPointCluster::SetLscale(), dynadjust::measurements::CDnaCovariance::SetM11(), dynadjust::measurements::CDnaCovariance::SetM12(), dynadjust::measurements::CDnaCovariance::SetM13(), dynadjust::measurements::CDnaCovariance::SetM21(), dynadjust::measurements::CDnaCovariance::SetM22(), dynadjust::measurements::CDnaCovariance::SetM23(), dynadjust::measurements::CDnaCovariance::SetM31(), dynadjust::measurements::CDnaCovariance::SetM32(), dynadjust::measurements::CDnaCovariance::SetM33(), dynadjust::measurements::CDnaGpsBaseline::SetPscale(), dynadjust::measurements::CDnaGpsBaselineCluster::SetPscale(), dynadjust::measurements::CDnaGpsPointCluster::SetPscale(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaXY(), dynadjust::measurements::CDnaGpsPoint::SetSigmaXY(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaXZ(), dynadjust::measurements::CDnaGpsPoint::SetSigmaXZ(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaYZ(), dynadjust::measurements::CDnaGpsPoint::SetSigmaYZ(), dynadjust::measurements::CDnaDistance::SetStdDev(), dynadjust::measurements::CDnaHeight::SetStdDev(), dynadjust::measurements::CDnaHeightDifference::SetStdDev(), dynadjust::measurements::CDnaDistance::SetTargetHeight(), dynadjust::measurements::CDnaDistance::SetValue(), dynadjust::measurements::CDnaHeight::SetValue(), dynadjust::measurements::CDnaHeightDifference::SetValue(), dynadjust::measurements::CDnaGpsBaseline::SetVscale(), dynadjust::measurements::CDnaGpsBaselineCluster::SetVscale(), dynadjust::measurements::CDnaGpsPointCluster::SetVscale(), dynadjust::measurements::CDnaGpsBaseline::SetX(), dynadjust::measurements::CDnaGpsPoint::SetX(), dynadjust::measurements::CDnaStation::SetXAxis(), dynadjust::measurements::CDnaGpsBaseline::SetY(), dynadjust::measurements::CDnaGpsPoint::SetY(), dynadjust::measurements::CDnaStation::SetYAxis(), dynadjust::measurements::CDnaGpsBaseline::SetZ(), dynadjust::measurements::CDnaGpsPoint::SetZ(), dynadjust::measurements::CDnaStation::SetZAxis(), and DnaMeasurement_pimpl::StdDev().
FloatFromString() [1/2]
template<class T> T FloatFromString (const std::string & str)
Definition at line 286 of file dnastrmanipfuncs.hpp.
{
    T t(0.);
    parse(str.begin(), str.end(), float_, t);
    return t;
}
Referenced by dynadjust::CDnaProjectFile::LoadSettingAdjust(), dynadjust::measurements::CDnaDirection::SetInstrumentHeight(), dynadjust::measurements::CDnaDistance::SetInstrumentHeight(), and dynadjust::measurements::CDnaDirection::SetTargetHeight().
DoubleFromString() [2/2]
template<class T> void DoubleFromString (T & t, const std::string & str)
Definition at line 294 of file dnastrmanipfuncs.hpp.
{
    parse(str.begin(), str.end(), double_, t);
}
FloatFromString() [2/2]
template<class T> void FloatFromString (T & t, const std::string & str)
Definition at line 300 of file dnastrmanipfuncs.hpp.
{
    parse(str.begin(), str.end(), float_, t);
}
DoubleFromString_ZeroCheck()
template<class T> bool DoubleFromString_ZeroCheck (T & t, const std::string & str)
Definition at line 306 of file dnastrmanipfuncs.hpp.
{
    parse(str.begin(), str.end(), double_, t);
    if (fabs(t) < PRECISION_1E35)
        return true;
    return false;
}
References PRECISION_1E35().
Referenced by dynadjust::measurements::CDnaGpsBaseline::SetSigmaXX(), dynadjust::measurements::CDnaGpsPoint::SetSigmaXX(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaYY(), dynadjust::measurements::CDnaGpsPoint::SetSigmaYY(), dynadjust::measurements::CDnaGpsBaseline::SetSigmaZZ(), and dynadjust::measurements::CDnaGpsPoint::SetSigmaZZ().
LongFromString() [1/2]
template<class T> std::enable_if< std::is_signed< T >::value, T >::type LongFromString (const std::string & str)
Definition at line 316 of file dnastrmanipfuncs.hpp.
{
    char* end(NULL);
    T t(strtol(str.c_str(), &end,  10));
    if (*end)
    {
        std::stringstream ss;
        ss << "String to long conversion error: non-convertible part: " << end;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return t;
}
Referenced by dynadjust::datum_parameters::CDnaEllipsoid::CDnaEllipsoid(), dateFromString_safe(), dynadjust::epsg::datumFromEpsgString(), ImportDataFiles(), dynadjust::referenceframe::dna_reftran::IsolateandApplySubstitute(), dynadjust::iostreams::dna_io_seg::load_seg_file(), dynadjust::networkplot::dna_plot::LoadCorrectionsFile(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), dynadjust::iostreams::dna_io_snx::parse_date_from_string(), dynadjust::iostreams::dna_io_snx::parse_sinex_header(), dynadjust::iostreams::dna_io_snx::parse_sinex_stn(), dynadjust::dynamlinterop::dna_import::ParseAngularValue(), dynadjust::dynamlinterop::dna_import::ParseDNA(), dynadjust::dynamlinterop::dna_import::ParseMsrCountValue(), dynadjust::dynamlinterop::dna_import::ParseXML(), dynadjust::epsg::referenceepochFromEpsgString(), dynadjust::referenceframe::dna_reftran::SerialiseDynaMLStn(), dynadjust::measurements::CDnaMeasurement::SetClusterDBID(), dynadjust::datum_parameters::CDnaDatum::SetDatum(), dynadjust::datum_parameters::CDnaDatum::SetDatumFromEpsg(), dynadjust::measurements::CDnaStation::SetHemisphereZone(), dynadjust::measurements::CDnaMeasurement::SetMeasurementDBID(), dynadjust::measurements::CDnaGpsPoint::SetMeasurementRec(), dynadjust::measurements::CDnaGpsPointCluster::SetMeasurementRec(), dynadjust::measurements::CDnaStation::SetStationRec(), dynadjust::measurements::CDnaDirectionSet::SetTotal(), dynadjust::measurements::CDnaGpsBaselineCluster::SetTotal(), dynadjust::measurements::CDnaGpsPointCluster::SetTotal(), and DnaMeasurement_pimpl::Total().
LongFromString() [2/2]
template<class T> std::enable_if< std::is_unsigned< T >::value, T >::type LongFromString (const std::string & str)
Definition at line 333 of file dnastrmanipfuncs.hpp.
{
    char* end(NULL);
    T t(strtoul(str.c_str(), &end,  10));
    if (*end)
    {
        std::stringstream ss;
        ss << "String to long conversion error: non-convertible part: " << end;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return t;
}
FromDmsString() [1/2]
template<class T> void FromDmsString (T * d, const std::string & str)
Definition at line 387 of file dnastrmanipfuncs.hpp.
{
    DmstoDeg(atof(str.c_str()), d);
}
References DmstoDeg().
Referenced by dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessDatFile(), dynadjust::measurements::CDnaGpsPoint::SetX(), dynadjust::measurements::CDnaStation::SetXAxis(), dynadjust::measurements::CDnaGpsPoint::SetY(), and dynadjust::measurements::CDnaStation::SetYAxis().
FromDmsString() [2/2]
template<class T> T FromDmsString (const std::string & str)
Definition at line 393 of file dnastrmanipfuncs.hpp.
{
    return DmstoDeg(atof(str.c_str()));
}
References DmstoDeg().
RadFromDmsString()
template<class T> void RadFromDmsString (T * d, const std::string & str)
Definition at line 399 of file dnastrmanipfuncs.hpp.
{
    DmstoDeg(atof(str.c_str()), d);
    Radians(d);
}
References DmstoDeg(), and Radians().
Referenced by dynadjust::measurements::CDnaAngle::SetValue(), dynadjust::measurements::CDnaCoordinate::SetValue(), dynadjust::measurements::CDnaDirection::SetValue(), and dynadjust::measurements::CDnaDirectionSet::SetValue().
RadFromSecondsString()
template<class T> void RadFromSecondsString (T * d, const std::string & str)
Definition at line 406 of file dnastrmanipfuncs.hpp.
{
    *d = SecondstoRadians(atof(str.c_str()));
}
References SecondstoRadians().
Referenced by dynadjust::measurements::CDnaAngle::SetStdDev(), dynadjust::measurements::CDnaCoordinate::SetStdDev(), dynadjust::measurements::CDnaDirection::SetStdDev(), and dynadjust::measurements::CDnaDirectionSet::SetStdDev().
SplitDelimitedString()
template<class T> void SplitDelimitedString (const T & str, const T & separator, std::vector< T > * tokenList)
Definition at line 412 of file dnastrmanipfuncs.hpp.
{
    // use boost to extract stations from comma delimited string
    typedef boost::tokenizer<boost::char_separator<char> > btokenizer;
    boost::char_separator<char> sepa(separator.c_str());
    btokenizer tokens(str, sepa);
    tokenList->clear();
    try {
        for_each(tokens.begin(), tokens.end(),
            [&tokenList](const std::string& s) {
                if (!trimstr(s).empty())
                    tokenList->push_back(trimstr(s));
        });
    }
    catch (...) {
        return;
    }
}
Referenced by dynadjust::networkadjust::dna_adjust::ApplyAdditionalConstraints(), dynadjust::dynamlinterop::dna_import::BuildExtractStationsList(), dateFromString_safe(), FormatDateString(), dynadjust::iostreams::dna_io_tbu::load_tbu_argument(), dynadjust::iostreams::dna_io_tpb::load_tpb_file(), ParseDmsString(), and dynadjust::networksegment::dna_segment::ParseStartingStations().