DynAdjust: include/functions/dnastringfuncs.hpp File Reference
dnastringfuncs.hpp File Reference
#include <include/config/dnaversion.hpp>
#include <include/config/dnaconsts.hpp>
Functions
int GetFields (char *line, char delim, bool multiple_delim_as_one, const char *fmt,...)
void fileproc_help_header (std::string *msg)
void dynaml_header (std::ostream &os, const std::string &fileType, const std::string &referenceFrame, const std::string &epoch)
void dynaml_footer (std::ostream &os)
void dynaml_comment (std::ostream &os, const std::string &comment)
void dna_header (std::ostream &os, const std::string &fileVersion, const std::string &fileType, const std::string &reference_frame, const std::string &epoch_version, const size_t &count)
void dna_comment (std::ostream &os, const std::string &comment)
void dnaproj_header (std::ostream &os, const std::string &comment)
void dnaproj_comment (std::ostream &os, const std::string &comment)
std::string snx_softwarehardware_text ()
Function Documentation
GetFields()
int GetFields (char * line, char delim, bool multiple_delim_as_one, const char * fmt, ...)
Definition at line 28 of file dnastringfuncs.cpp.
{
    va_list ap;
    size_t length = strlen(line);
    // 1. determine "expected" number of fields
    size_t field_count = strlen(fmt);
    size_t* field = new size_t[field_count+1];
    size_t i(0), j(0);
    // 2. Determine indices of the beginning of each field
    // first field commences at 0
    field[j++] = 0;
    // 3. Determine indices of remaining fields, but don't let j
    //    go beyond the number of 'wanted' fields (field_count)
    while (line[i] != '\n' && i < length && j <= field_count)
    //while (line[i] != '\n' && i < length)
    //while(line[i] != '\n' && line[i] != '\0')
    {
        // replace all delimiters with NULL
        if (line[i] == delim)
        {
            if (multiple_delim_as_one && i < length-1)
            {
                if (line[i+1] == delim)
                {
                    i++;
                    continue;
                }
            }
            line[i] = '\0';
            field[j++] = i+1;
        }
        i++;
    }
    // 4. terminate end of the wanted string with null
    line[i] = '\0';
    i = 0;
    va_start(ap, fmt);
    int success(0);
    char* p;
    // 5. get the data
    while (i < j && *fmt != '\0')
    {
        p = &line[field[i]];
        switch(*fmt) {
        case 'd':
            if (strlen(p) == 0)
                *(va_arg(ap, int *)) = INT_MIN;
            else
            {
                success++;
                *(va_arg(ap, int *)) = atoi(p);
            }
            break;
        case 'f':
            if (strlen(p) == 0)
                *(va_arg(ap, double *)) = MAX_DBL_VALUE;
            else
            {
                success++;
                *(va_arg(ap, double *)) = atof(p);
            }
            break;
        case 's':
            if (strlen(p) != 0)
                success++;
            strcpy((va_arg(ap, char *)), p);
            break;
        default :
            delete[] field;
            return 0;
        }
        i++;
        fmt++;
    }
    va_end(ap);
    delete[] field;
    // 6. Return number of fields with non-empty data
    return success;
}
References INT_MIN, and MAX_DBL_VALUE().
Referenced by dynadjust::dynamlinterop::dna_import::DetermineBoundingBox(), dynadjust::networkplot::dna_plot::DetermineBoundingBox(), dynadjust::iostreams::dna_io_snx::parse_sinex_msr(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessCsvFile().
fileproc_help_header()
void fileproc_help_header (std::string * msg)
Definition at line 131 of file dnastringfuncs.cpp.
{
    std::stringstream str;
    str << "+---------------------------------------------------------------------------" << std::endl;
    str << "+ ";
    output_binaryname(str);
    str << " - ";
    output_theappname(str);
    str << ".";
    str << std::endl;
    str << "+ ";
    output_binarydescription(str);
    str << std::endl;
    str << "+ ";
    output_version(str);
    str << std::endl;
    str << "+ ";
    output_build(str);
    str << std::endl;
    *msg = str.str();
    *msg += "+ Copyright:    (C) ";
    *msg += __COPYRIGHT_YEAR__;
    *msg += " ";
    *msg += __COPYRIGHT_OWNER__;
    *msg += ".\n";
    *msg += "                ";
    *msg += __COPYRIGHT_MSG__;
    *msg += "\n";
    *msg += "+ Contact:      ";
    *msg += __CONTACT_EMAIL__;
    *msg += "\n";
    *msg += "+---------------------------------------------------------------------------\n\n";
}
References __CONTACT_EMAIL__, __COPYRIGHT_MSG__, __COPYRIGHT_OWNER__, __COPYRIGHT_YEAR__, output_binarydescription(), output_binaryname(), output_build(), output_theappname(), and output_version().
Referenced by main().
dynaml_header()
void dynaml_header (std::ostream & os, const std::string & fileType, const std::string & referenceFrame, const std::string & epoch)
Definition at line 173 of file dnastringfuncs.cpp.
{
    os << "<?xml version=\"1.0\"?>" << std::endl;
    os << "<DnaXmlFormat type=\"" << fileType <<
        "\" referenceframe=\"" << referenceFrame <<
        "\" epoch=\"" << epoch <<
        "\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:noNamespaceSchemaLocation=\"DynaML.xsd\">" << std::endl;
    os << "<!-- ";
    output_createdby(os);
    os << " -->" << std::endl;
    os << "<!-- ";
    output_version(os);
    os << " -->" << std::endl;
    os << "<!-- ";
    output_build(os);
    os << " -->" << std::endl;
}
References output_build(), output_createdby(), and output_version().
Referenced by dynadjust::dynamlinterop::dna_import::InitialiseDynaMLFile(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLSepMeasurementFile(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLSepStationFile(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML_Y(), dynadjust::referenceframe::dna_reftran::SerialiseDynaML(), and dynadjust::referenceframe::dna_reftran::SerialiseDynaML().
dynaml_footer()
void dynaml_footer (std::ostream & os)
Definition at line 193 of file dnastringfuncs.cpp.
{
    os << "</DnaXmlFormat>" << std::endl;
}
Referenced by dynadjust::referenceframe::dna_reftran::SerialiseDynaML(), and dynadjust::referenceframe::dna_reftran::SerialiseDynaML().
dynaml_comment()
void dynaml_comment (std::ostream & os, const std::string & comment)
Definition at line 199 of file dnastringfuncs.cpp.
{
    os << "<!-- " << comment << " -->" << std::endl;
}
Referenced by dynadjust::dynamlinterop::dna_import::InitialiseDynaMLFile(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLSepMeasurementFile(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLSepStationFile(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML_Y(), dynadjust::referenceframe::dna_reftran::SerialiseDynaML(), and dynadjust::referenceframe::dna_reftran::SerialiseDynaML().
dna_header()
void dna_header (std::ostream & os, const std::string & fileVersion, const std::string & fileType, const std::string & reference_frame, const std::string & epoch_version, const size_t & count)
Definition at line 230 of file dnastringfuncs.cpp.
{
    std::stringstream str;
    str << "!#=DNA " << fileVersion << " " << fileType;
    boost::gregorian::date today(boost::gregorian::day_clock::local_day());
    // creation date
    str << std::setw(14) << std::right << stringFromDate<boost::gregorian::date>(today);
    // default reference frame
    str << std::setw(14) << std::right << reference_frame;
    // default epoch
    str << std::setw(14) << std::right << epoch_version;
    // count of records
    str << std::setw(10) << std::right << count;
    os << str.str() << std::endl;
    // Provide comments on the version of DynAdjust that is creating this file
    os << "* ";
    output_createdby(os);
    os << ". " << std::endl;
    os << "* ";
    output_version(os);
    os << ". " << std::endl;
    os << "* ";
    output_build(os);
    os << std::endl;
}
References output_build(), output_createdby(), and output_version().
Referenced by dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML_Y(), dynadjust::dynamlinterop::dna_import::SerialiseMSR(), dynadjust::dynamlinterop::dna_import::SerialiseSTN(), dynadjust::dynamlinterop::dna_import::SimulateMSR(), dynadjust::iostreams::dna_io_dna::write_msr_header_data(), and dynadjust::iostreams::dna_io_dna::write_stn_header_data().
dna_comment()
void dna_comment (std::ostream & os, const std::string & comment)
Definition at line 261 of file dnastringfuncs.cpp.
{
    os << "* " << comment << std::endl;
}
Referenced by dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML(), dynadjust::networkadjust::dna_adjust::PrintEstimatedStationCoordinatestoDNAXML_Y(), dynadjust::dynamlinterop::dna_import::SerialiseMSR(), dynadjust::dynamlinterop::dna_import::SerialiseSTN(), dynadjust::dynamlinterop::dna_import::SimulateMSR(), dynadjust::iostreams::dna_io_dna::write_msr_header_data(), and dynadjust::iostreams::dna_io_dna::write_stn_header_data().
dnaproj_header()
void dnaproj_header (std::ostream & os, const std::string & comment)
Definition at line 266 of file dnastringfuncs.cpp.
{
    // DynAdjust version
    os << "# " << comment << ". ";
    output_createdby(os);
    os << ". ";
    output_version(os);
    os << ". ";
    output_build(os);
}
References output_build(), output_createdby(), and output_version().
Referenced by dynadjust::CDnaProjectFile::PrintProjectFile(), and dynadjust::geoidinterpolation::dna_geoid_interpolation::WriteDNA1GeoidFile().
dnaproj_comment()
void dnaproj_comment (std::ostream & os, const std::string & comment)
Definition at line 277 of file dnastringfuncs.cpp.
{
    os << "# " << comment << std::endl;
}
snx_softwarehardware_text()
std::string snx_softwarehardware_text ()
Definition at line 204 of file dnastringfuncs.cpp.
{
    std::stringstream str, str2;
    // name
    output_globalname(str2);
    str << " SOFTWARE           " << std::left << std::setw(60) << str2.str() << std::endl;
    // version
    str2.str("");
    output_version(str2);
    str << " SOFTWARE           " << std::left << std::setw(60) << str2.str() << std::endl;
    // build
    str2.str("");
    output_build(str2);
    str << " SOFTWARE           " << std::left << std::setw(60) << str2.str() << std::endl;
    // hardware
    str << " HARDWARE           " << std::left << std::setw(60) << __HARDWARE__ << std::endl;
    return str.str();
}
References output_build(), output_globalname(), and output_version().
Referenced by dynadjust::iostreams::dna_io_snx::serialise_meta().