DynAdjust: include/config/dnatypes.hpp File Reference
dnatypes.hpp File Reference
Classes
struct stn_appearance_t< T1, T2 >
struct stn_block_map_t< T, U >
struct freestnpair_t< T1, T2 >
struct amlpair_t< T1, T2 >
struct sequential_adj_t< T1, T2 >
struct statSummary_t
struct stationCorrections
struct stationPosUncertainty_t
struct segmentParam_t
struct block_meta
struct stn_t
struct input_file_meta
struct binary_file_meta
Macros
#define INT_MIN -2147483648
#define TRUE 1
#define FALSE 0
Typedefs
typedef unsigned int UINT32
typedef unsigned int * PUINT32
typedef const PUINT32 PUINT32_const
typedef unsigned short UINT16
typedef unsigned short * PUINT16
typedef uint32_t index_t
typedef std::vector< char > vchar
typedef vchar::iterator _it_chr
typedef std::vector< double > vdouble
typedef vdouble::iterator _it_dbl
typedef std::vector< bool > vbool
typedef vbool::iterator _it_bool
typedef std::vector< bool >::reference boolRef
typedef std::string::iterator _it_str
typedef std::string::const_iterator _it_str_const
typedef std::vector< std::string > vstring
typedef std::vector< std::string > * pvstring
typedef vstring::iterator _it_vstr
typedef vstring::const_iterator _it_vstr_const
typedef std::pair< vchar::iterator, vchar::iterator > _it_pair_vchar
typedef std::pair< vstring::iterator, vstring::iterator > _it_pair_vstring
typedef std::queue< UINT32 > qUINT32
typedef std::vector< UINT32 > vUINT32
typedef std::vector< UINT32 > * pvUINT32
typedef std::vector< vUINT32 > vvUINT32
typedef std::vector< vUINT32 > * pvvUINT32
typedef vUINT32::iterator it_vUINT32
typedef vUINT32::const_iterator it_vUINT32_const
typedef vvUINT32::iterator it_vvUINT32
typedef std::pair< std::string, std::string > string_string_pair
typedef std::pair< std::string, UINT32 > string_uint32_pair
typedef std::pair< UINT32, UINT32 > uint32_uint32_pair
typedef std::pair< UINT32, std::string > uint32_string_pair
typedef std::pair< bool, UINT32 > bool_uint32_pair
typedef std::pair< std::string, vstring > string_vstring_pair
typedef std::pair< uint32_uint32_pair, UINT32 > u32u32_uint32_pair
typedef std::pair< UINT32, uint32_uint32_pair > uint32_u32u32_pair
typedef std::pair< double, double > doubledouble_pair
typedef std::pair< string_string_pair, doubledouble_pair > stringstring_doubledouble_pair
typedef std::vector< stringstring_doubledouble_pair > v_stringstring_doubledouble_pair
typedef std::vector< stringstring_doubledouble_pair > * pv_stringstring_doubledouble_pair
typedef v_stringstring_doubledouble_pair::iterator _it_string_doubledouble_pair
typedef std::vector< doubledouble_pair > v_doubledouble_pair
typedef std::vector< doubledouble_pair > * pv_doubledouble_pair
typedef std::pair< std::string, v_doubledouble_pair > string_v_doubledouble_pair
typedef std::vector< string_v_doubledouble_pair > v_string_v_doubledouble_pair
typedef std::vector< string_v_doubledouble_pair > * pv_string_v_doubledouble_pair
typedef v_string_v_doubledouble_pair::iterator it_v_string_v_doubledouble_pair
typedef std::pair< uint32_uint32_pair, double > u32u32_double_pair
typedef std::pair< std::string, bool > stringbool_pair
typedef std::pair< string_uint32_pair, stringbool_pair > stringuint32_stringbool_pair
typedef stn_appearance_t< UINT32, bool > stn_appear
typedef std::vector< stn_appear > v_stn_appear
typedef v_stn_appear::iterator it_vstn_appear
typedef std::vector< v_stn_appear > vv_stn_appear
typedef vv_stn_appear::iterator it_vvstn_appear
typedef stn_block_map_t< UINT32 > stn_block_map
typedef std::vector< stn_block_map > v_stn_block_map
typedef v_stn_block_map::iterator it_vstn_block_map
typedef freestnpair_t< UINT32, bool > freestn_pair
typedef std::vector< freestn_pair > v_freestn_pair
typedef v_freestn_pair::iterator it_freestn_pair
typedef amlpair_t< UINT32, bool > aml_pair
typedef std::vector< aml_pair > v_aml_pair
typedef v_aml_pair::iterator it_aml_pair
typedef sequential_adj_t< UINT32, bool > sequential_adj
typedef std::vector< sequential_adj > v_sequential_adj
typedef v_sequential_adj::iterator it_sequential_adj
typedef std::map< UINT32, UINT32 > uint32_uint32_map
typedef uint32_uint32_map::iterator it_uint32_uint32_map
typedef std::vector< uint32_uint32_map > v_uint32_uint32_map
typedef v_uint32_uint32_map::iterator it_v_uint32_uint32_map
typedef std::vector< string_string_pair > v_string_string_pair
typedef std::vector< string_string_pair > * pv_string_string_pair
typedef std::vector< string_vstring_pair > v_string_vstring_pair
typedef std::vector< string_vstring_pair > * pv_string_vstring_pair
typedef std::vector< string_uint32_pair > v_string_uint32_pair
typedef std::vector< string_uint32_pair > * pv_string_uint32_pair
typedef std::vector< uint32_uint32_pair > v_uint32_uint32_pair
typedef std::vector< uint32_uint32_pair > * pv_uint32_uint32_pair
typedef std::vector< uint32_string_pair > v_uint32_string_pair
typedef std::vector< uint32_string_pair > * pv_uint32_string_pair
typedef std::vector< u32u32_uint32_pair > v_u32u32_uint32_pair
typedef std::vector< uint32_u32u32_pair > v_uint32_u32u32_pair
typedef v_string_vstring_pair::iterator _it_string_vstring_pair
typedef v_string_uint32_pair::iterator _it_string_uint32_pair
typedef v_uint32_string_pair::iterator _it_uint32_string_pair
typedef v_u32u32_uint32_pair::iterator _it_u32u32_uint32_pair
typedef v_uint32_u32u32_pair::iterator _it_uint32_u32u32_pair
typedef v_uint32_uint32_pair::iterator _it_uint32_uint32_pair
typedef std::pair< _it_u32u32_uint32_pair, _it_u32u32_uint32_pair > _it_pair_u32u32_uint32
typedef std::vector< v_string_string_pair > vv_string_string_pair
typedef std::pair< it_vUINT32_const, it_vUINT32_const > _it_pair_vUINT32_const
typedef std::pair< it_vUINT32, it_vUINT32 > it_pair_vUINT32
typedef v_string_string_pair::iterator it_string_pair
typedef std::pair< v_string_string_pair::iterator, v_string_string_pair::iterator > it_pair_string
typedef std::pair< _it_string_uint32_pair, _it_string_uint32_pair > it_pair_string_vUINT32
typedef std::pair< _it_uint32_string_pair, _it_uint32_string_pair > it_pair_uint32_string
typedef std::pair< uint32_uint32_map::iterator, uint32_uint32_map::iterator > it_pair_map_vUINT32_vUINT32
typedef enum _SIGMA_ZERO_STAT_PASS_ SIGMA_ZERO_STAT_PASS
typedef enum _INPUT_FILE_TYPE_ INPUT_FILE_TYPE
typedef enum _INPUT_DATA_TYPE_ INPUT_DATA_TYPE
typedef enum _TIMER_TYPE_ TIMER_TYPE
typedef enum _ANGULAR_TYPE_ ANGULAR_TYPE
typedef enum _DMS_FORMAT_ DMS_FORMAT
typedef enum _COORD_TYPE_ COORD_TYPE
typedef enum _STATION_ELEM_ STATION_ELEM
typedef enum _CART_ELEM_ CART_ELEM
typedef enum _COORDINATE_TYPES_ COORDINATE_TYPES
typedef enum _HEIGHT_SYSTEM_ HEIGHT_SYSTEM
typedef enum _MEASUREMENT_STATIONS_ MEASUREMENT_STATIONS
typedef enum _MEASUREMENT_START_ MEASUREMENT_START
typedef enum _CONSTRAINT_TYPE_ CONSTRAINT_TYPE
typedef enum _AML_TYPE_ AML_TYPE
typedef enum _STAGE_FILE_ STAGE_FILE
typedef struct stationCorrections stationCorrections_t
typedef std::vector< stationCorrections_t > vstnCor_t
typedef std::vector< stationCorrections_t > * pvstnCor_t
typedef std::vector< vstnCor_t > vvstnCor_t
typedef vstnCor_t::iterator it_vstnCor_t
typedef std::vector< stationPosUncertainty_t > vstnPU_t
typedef std::vector< stationPosUncertainty_t > * pvstnPU_t
typedef std::vector< vstnPU_t > vvstnPU_t
typedef vstnPU_t::iterator it_vstnPU_t
typedef struct block_meta blockMeta_t
typedef struct stn_t station_t
typedef std::vector< station_t > vstn_t
typedef std::vector< station_t > * pvstn_t
typedef vstn_t::iterator it_vstn_t
typedef vstn_t::const_iterator it_vstn_t_const
typedef std::vector< statSummary_t > vsummary_t
typedef std::vector< statSummary_t > * pvsummary_t
typedef std::pair< station_t, std::string > stn_t_string_pair
typedef std::vector< stn_t_string_pair > v_stn_string
typedef v_stn_string::iterator it_stn_string
typedef struct input_file_meta input_file_meta_t
typedef struct binary_file_meta binary_file_meta_t
typedef std::vector< input_file_meta_t > vifm_t
typedef vifm_t::iterator it_vifm_t
typedef std::vector< binary_file_meta_t > vbfm_t
typedef vbfm_t::iterator it_vbfm_t
Enumerations
enum _SIGMA_ZERO_STAT_PASS_ { test_stat_pass = 0 , test_stat_warning = 1 , test_stat_fail = 2 }
enum _INPUT_FILE_TYPE_ {
geodesyml = 0 , dynaml = 1 , dna = 2 , csv = 3 ,
sinex = 4
}
enum _INPUT_DATA_TYPE_ {
stn_data = 0 , msr_data = 1 , stn_msr_data = 2 , geo_data = 3 ,
ren_data = 4 , tbu_data = 5 , unknown = 6
}
enum _TIMER_TYPE_ { iteration_time = 0 , total_time = 1 }
enum _ANGULAR_TYPE_ { DMS = 0 , DDEG = 1 }
enum _DMS_FORMAT_ { SEPARATED = 0 , SEPARATED_WITH_SYMBOLS = 1 , HP_NOTATION = 2 }
enum _COORD_TYPE_ {
XYZ_type_i = 0 , LLh_type_i = 1 , LLH_type_i = 2 , UTM_type_i = 3 ,
ENU_type_i = 4 , AED_type_i = 5
}
enum _STATION_ELEM_ { station_1 = 0 , station_2 = 1 , station_3 = 2 }
enum _CART_ELEM_ { x_element = 0 , y_element = 1 , z_element = 2 }
enum _COORDINATE_TYPES_ { latitude_t = 0 , longitude_t = 1 , easting_t = 2 , northing_t = 3 }
enum _HEIGHT_SYSTEM_ { ORTHOMETRIC_type_i = 0 , ELLIPSOIDAL_type_i = 1 }
enum _MEASUREMENT_STATIONS_ { ONE_STATION = 1 , TWO_STATION = 2 , THREE_STATION = 3 , UNKNOWN_TYPE = -1 }
enum _MEASUREMENT_START_ {
xMeas = 0 , yMeas = 1 , zMeas = 2 , xCov = 3 ,
yCov = 4 , zCov = 5
}
enum _CONSTRAINT_TYPE_ {
free_3D = 0 , constrained_3D = 1 , free_2D = 2 , free_1D = 3 ,
custom_constraint = 4
}
enum _AML_TYPE_ { str_msr = 0 , cls_msr = 1 }
enum iosMode { binary = 0 , ascii = 1 }
enum mtxType { mtx_full = 0 , mtx_lower = 1 , mtx_sparse = 2 }
enum _STAGE_FILE_ {
sf_normals = 0 , sf_normals_r = 1 , sf_atvinv = 2 , sf_design = 3 ,
sf_meas_minus_comp = 4 , sf_estimated_stns = 5 , sf_original_stns = 6 , sf_rigorous_stns = 7 ,
sf_junction_vars = 8 , sf_junction_vars_f = 9 , sf_junction_ests_f = 10 , sf_junction_ests_r = 11 ,
sf_rigorous_vars = 12 , sf_prec_adj_msrs = 13 , sf_corrections = 14
}
Functions
const UINT16 STN_NAME_WIDTH (31)
const UINT16 STN_NAME_ORIG_WIDTH (40)
const UINT16 STN_DESC_WIDTH (129)
const UINT16 STN_CONST_WIDTH (4)
const UINT16 STN_TYPE_WIDTH (4)
const UINT16 STN_EPSG_WIDTH (7)
const UINT16 STN_EPOCH_WIDTH (12)
const UINT16 STN_PLATE_WIDTH (3)
const UINT32 MOD_NAME_WIDTH (20)
const UINT32 FILE_NAME_WIDTH (256)
template<typename S>
S formatStnMsrFileSourceString (const vifm_t *vfile_meta, const size_t &file_type)
template<typename S = std::string>
S FormatFileType (const size_t &file_type)
Variables
const char LOWER_TRIANGLE = 'L'
const char UPPER_TRIANGLE = 'U'
const UINT16 VALID_STATION = 1
const UINT16 INVALID_STATION = 0
Macro Definition Documentation
INT_MIN
#define INT_MIN -2147483648
Definition at line 57 of file dnatypes.hpp.
Referenced by GetFields().
TRUE
#define TRUE 1
Definition at line 61 of file dnatypes.hpp.
Referenced by AppIsAlreadyRunning(), BrowseCallbackProc(), CdnageoidintDlg::CreateGridIndex(), CFileProc::DoFileCopy(), CdnageoidintDlg::OnBrowseForFolder(), CdnageoidintDlg::OnClickDirectoryCheckBox(), CdnageoidintDlg::OnClickRecurseDirectory(), CdnageoidintDlg::OnEllipsOrtho(), CdnageoidintDlg::OnFileCreateausgeoid(), CdnageoidintDlg::OnFileDdmmss(), CAboutDlg::OnInitDialog(), CdnageoidintDlg::OnInitDialog(), CInputCoords::OnInitDialog(), CdnageoidintDlg::OnOpenGridFile(), CdnageoidintDlg::OnOpenInputData(), CdnageoidintDlg::OnOrthoEllips(), CdnageoidintDlg::OnSetMessageString(), CdnageoidintDlg::OnTransform(), CdnageoidintDlg::OnUpdateControls(), dynadjust::dynamlinterop::dna_import::ParseXML(), run_command(), dynadjust::measurements::CAStationList::SetValid(), ShowAppEnum(), and dynadjust::iostreams::dna_io_bst::write_bst_file().
FALSE
#define FALSE 0
Definition at line 65 of file dnatypes.hpp.
Referenced by AppIsAlreadyRunning(), CdnageoidintDlg::CdnageoidintDlg(), CreateGridFile(), CdnageoidintDlg::CreateGridIndex(), CFileProc::DoFileCopy(), CdnageoidintApp::InitInstance(), CdnageoidintDlg::OnBrowseForFolder(), CdnageoidintDlg::OnClickDirectoryCheckBox(), CInputCoords::OnEnSetfocusLat(), CInputCoords::OnEnSetfocusLong(), CdnageoidintDlg::OnFileInterpolate(), CdnageoidintDlg::OnInitDialog(), CdnageoidintDlg::OnInterpolateInputCoords(), CdnageoidintDlg::OnOpenGridFile(), CdnageoidintDlg::OnOpenInputData(), CdnageoidintDlg::OnUpdateControls(), dynadjust::networksegment::dna_segment::RemoveInvalidFreeStations(), dynadjust::networkadjust::dna_adjust::RemoveInvalidISLStations(), dynadjust::measurements::CAStationList::SetInvalid(), StartServer(), stn_t::stn_t(), and CFileProc::View().
Typedef Documentation
UINT32
typedef unsigned int UINT32
Definition at line 50 of file dnatypes.hpp.
PUINT32
typedef unsigned int * PUINT32
Definition at line 50 of file dnatypes.hpp.
PUINT32_const
typedef const PUINT32 PUINT32_const
Definition at line 51 of file dnatypes.hpp.
UINT16
typedef unsigned short UINT16
Definition at line 52 of file dnatypes.hpp.
PUINT16
typedef unsigned short * PUINT16
Definition at line 52 of file dnatypes.hpp.
index_t
typedef uint32_t index_t
Definition at line 54 of file dnatypes.hpp.
vchar
typedef std::vector<char> vchar
Definition at line 74 of file dnatypes.hpp.
_it_chr
typedef vchar::iterator _it_chr
Definition at line 75 of file dnatypes.hpp.
vdouble
typedef std::vector<double> vdouble
Definition at line 77 of file dnatypes.hpp.
_it_dbl
typedef vdouble::iterator _it_dbl
Definition at line 78 of file dnatypes.hpp.
vbool
typedef std::vector<bool> vbool
Definition at line 80 of file dnatypes.hpp.
_it_bool
typedef vbool::iterator _it_bool
Definition at line 81 of file dnatypes.hpp.
boolRef
typedef std::vector<bool>::reference boolRef
Definition at line 82 of file dnatypes.hpp.
_it_str
typedef std::string::iterator _it_str
Definition at line 84 of file dnatypes.hpp.
_it_str_const
typedef std::string::const_iterator _it_str_const
Definition at line 85 of file dnatypes.hpp.
vstring
typedef std::vector<std::string> vstring
Definition at line 86 of file dnatypes.hpp.
pvstring
typedef std::vector<std::string> * pvstring
Definition at line 86 of file dnatypes.hpp.
_it_vstr
typedef vstring::iterator _it_vstr
Definition at line 87 of file dnatypes.hpp.
_it_vstr_const
typedef vstring::const_iterator _it_vstr_const
Definition at line 88 of file dnatypes.hpp.
_it_pair_vchar
typedef std::pair<vchar::iterator, vchar::iterator> _it_pair_vchar
Definition at line 90 of file dnatypes.hpp.
_it_pair_vstring
typedef std::pair<vstring::iterator, vstring::iterator> _it_pair_vstring
Definition at line 92 of file dnatypes.hpp.
qUINT32
typedef std::queue<UINT32> qUINT32
Definition at line 94 of file dnatypes.hpp.
vUINT32
typedef std::vector<UINT32> vUINT32
Definition at line 96 of file dnatypes.hpp.
pvUINT32
typedef std::vector<UINT32> * pvUINT32
Definition at line 96 of file dnatypes.hpp.
vvUINT32
typedef std::vector<vUINT32> vvUINT32
Definition at line 97 of file dnatypes.hpp.
pvvUINT32
typedef std::vector<vUINT32> * pvvUINT32
Definition at line 97 of file dnatypes.hpp.
it_vUINT32
typedef vUINT32::iterator it_vUINT32
Definition at line 99 of file dnatypes.hpp.
it_vUINT32_const
typedef vUINT32::const_iterator it_vUINT32_const
Definition at line 100 of file dnatypes.hpp.
it_vvUINT32
typedef vvUINT32::iterator it_vvUINT32
Definition at line 101 of file dnatypes.hpp.
string_string_pair
typedef std::pair<std::string, std::string> string_string_pair
Definition at line 103 of file dnatypes.hpp.
string_uint32_pair
typedef std::pair<std::string, UINT32> string_uint32_pair
Definition at line 104 of file dnatypes.hpp.
uint32_uint32_pair
typedef std::pair<UINT32, UINT32> uint32_uint32_pair
Definition at line 105 of file dnatypes.hpp.
uint32_string_pair
typedef std::pair<UINT32, std::string> uint32_string_pair
Definition at line 106 of file dnatypes.hpp.
bool_uint32_pair
typedef std::pair<bool, UINT32> bool_uint32_pair
Definition at line 108 of file dnatypes.hpp.
string_vstring_pair
typedef std::pair<std::string, vstring> string_vstring_pair
Definition at line 110 of file dnatypes.hpp.
u32u32_uint32_pair
typedef std::pair<uint32_uint32_pair, UINT32> u32u32_uint32_pair
Definition at line 112 of file dnatypes.hpp.
uint32_u32u32_pair
typedef std::pair<UINT32, uint32_uint32_pair> uint32_u32u32_pair
Definition at line 113 of file dnatypes.hpp.
doubledouble_pair
typedef std::pair<double, double> doubledouble_pair
Definition at line 115 of file dnatypes.hpp.
stringstring_doubledouble_pair
typedef std::pair<string_string_pair, doubledouble_pair> stringstring_doubledouble_pair
Definition at line 116 of file dnatypes.hpp.
v_stringstring_doubledouble_pair
typedef std::vector<stringstring_doubledouble_pair> v_stringstring_doubledouble_pair
Definition at line 117 of file dnatypes.hpp.
pv_stringstring_doubledouble_pair
typedef std::vector<stringstring_doubledouble_pair> * pv_stringstring_doubledouble_pair
Definition at line 117 of file dnatypes.hpp.
_it_string_doubledouble_pair
typedef v_stringstring_doubledouble_pair::iterator _it_string_doubledouble_pair
Definition at line 118 of file dnatypes.hpp.
v_doubledouble_pair
typedef std::vector<doubledouble_pair> v_doubledouble_pair
Definition at line 120 of file dnatypes.hpp.
pv_doubledouble_pair
typedef std::vector<doubledouble_pair> * pv_doubledouble_pair
Definition at line 120 of file dnatypes.hpp.
string_v_doubledouble_pair
typedef std::pair<std::string, v_doubledouble_pair> string_v_doubledouble_pair
Definition at line 121 of file dnatypes.hpp.
v_string_v_doubledouble_pair
typedef std::vector<string_v_doubledouble_pair> v_string_v_doubledouble_pair
Definition at line 122 of file dnatypes.hpp.
pv_string_v_doubledouble_pair
typedef std::vector<string_v_doubledouble_pair> * pv_string_v_doubledouble_pair
Definition at line 122 of file dnatypes.hpp.
it_v_string_v_doubledouble_pair
typedef v_string_v_doubledouble_pair::iterator it_v_string_v_doubledouble_pair
Definition at line 123 of file dnatypes.hpp.
u32u32_double_pair
typedef std::pair<uint32_uint32_pair, double> u32u32_double_pair
Definition at line 125 of file dnatypes.hpp.
stringbool_pair
typedef std::pair<std::string, bool> stringbool_pair
Definition at line 127 of file dnatypes.hpp.
stringuint32_stringbool_pair
typedef std::pair<string_uint32_pair, stringbool_pair> stringuint32_stringbool_pair
Definition at line 128 of file dnatypes.hpp.
stn_appear
typedef stn_appearance_t<UINT32, bool> stn_appear
Definition at line 157 of file dnatypes.hpp.
v_stn_appear
typedef std::vector<stn_appear> v_stn_appear
Definition at line 158 of file dnatypes.hpp.
it_vstn_appear
typedef v_stn_appear::iterator it_vstn_appear
Definition at line 159 of file dnatypes.hpp.
vv_stn_appear
typedef std::vector<v_stn_appear> vv_stn_appear
Definition at line 160 of file dnatypes.hpp.
it_vvstn_appear
typedef vv_stn_appear::iterator it_vvstn_appear
Definition at line 161 of file dnatypes.hpp.
stn_block_map
typedef stn_block_map_t<UINT32> stn_block_map
Definition at line 199 of file dnatypes.hpp.
v_stn_block_map
typedef std::vector<stn_block_map> v_stn_block_map
Definition at line 200 of file dnatypes.hpp.
it_vstn_block_map
typedef v_stn_block_map::iterator it_vstn_block_map
Definition at line 201 of file dnatypes.hpp.
freestn_pair
typedef freestnpair_t<UINT32, bool> freestn_pair
Definition at line 222 of file dnatypes.hpp.
v_freestn_pair
typedef std::vector<freestn_pair> v_freestn_pair
Definition at line 223 of file dnatypes.hpp.
it_freestn_pair
typedef v_freestn_pair::iterator it_freestn_pair
Definition at line 224 of file dnatypes.hpp.
aml_pair
typedef amlpair_t<UINT32, bool> aml_pair
Definition at line 244 of file dnatypes.hpp.
v_aml_pair
typedef std::vector<aml_pair> v_aml_pair
Definition at line 245 of file dnatypes.hpp.
it_aml_pair
typedef v_aml_pair::iterator it_aml_pair
Definition at line 246 of file dnatypes.hpp.
sequential_adj
typedef sequential_adj_t<UINT32, bool> sequential_adj
Definition at line 270 of file dnatypes.hpp.
v_sequential_adj
typedef std::vector<sequential_adj> v_sequential_adj
Definition at line 271 of file dnatypes.hpp.
it_sequential_adj
typedef v_sequential_adj::iterator it_sequential_adj
Definition at line 272 of file dnatypes.hpp.
uint32_uint32_map
typedef std::map<UINT32, UINT32> uint32_uint32_map
Definition at line 275 of file dnatypes.hpp.
it_uint32_uint32_map
typedef uint32_uint32_map::iterator it_uint32_uint32_map
Definition at line 276 of file dnatypes.hpp.
v_uint32_uint32_map
typedef std::vector<uint32_uint32_map> v_uint32_uint32_map
Definition at line 277 of file dnatypes.hpp.
it_v_uint32_uint32_map
typedef v_uint32_uint32_map::iterator it_v_uint32_uint32_map
Definition at line 278 of file dnatypes.hpp.
v_string_string_pair
typedef std::vector<string_string_pair> v_string_string_pair
Definition at line 280 of file dnatypes.hpp.
pv_string_string_pair
typedef std::vector<string_string_pair> * pv_string_string_pair
Definition at line 280 of file dnatypes.hpp.
v_string_vstring_pair
typedef std::vector<string_vstring_pair> v_string_vstring_pair
Definition at line 281 of file dnatypes.hpp.
pv_string_vstring_pair
typedef std::vector<string_vstring_pair> * pv_string_vstring_pair
Definition at line 281 of file dnatypes.hpp.
v_string_uint32_pair
typedef std::vector<string_uint32_pair> v_string_uint32_pair
Definition at line 283 of file dnatypes.hpp.
pv_string_uint32_pair
typedef std::vector<string_uint32_pair> * pv_string_uint32_pair
Definition at line 283 of file dnatypes.hpp.
v_uint32_uint32_pair
typedef std::vector<uint32_uint32_pair> v_uint32_uint32_pair
Definition at line 284 of file dnatypes.hpp.
pv_uint32_uint32_pair
typedef std::vector<uint32_uint32_pair> * pv_uint32_uint32_pair
Definition at line 284 of file dnatypes.hpp.
v_uint32_string_pair
typedef std::vector<uint32_string_pair> v_uint32_string_pair
Definition at line 285 of file dnatypes.hpp.
pv_uint32_string_pair
typedef std::vector<uint32_string_pair> * pv_uint32_string_pair
Definition at line 285 of file dnatypes.hpp.
v_u32u32_uint32_pair
typedef std::vector<u32u32_uint32_pair> v_u32u32_uint32_pair
Definition at line 286 of file dnatypes.hpp.
v_uint32_u32u32_pair
typedef std::vector<uint32_u32u32_pair> v_uint32_u32u32_pair
Definition at line 287 of file dnatypes.hpp.
_it_string_vstring_pair
typedef v_string_vstring_pair::iterator _it_string_vstring_pair
Definition at line 289 of file dnatypes.hpp.
_it_string_uint32_pair
typedef v_string_uint32_pair::iterator _it_string_uint32_pair
Definition at line 290 of file dnatypes.hpp.
_it_uint32_string_pair
typedef v_uint32_string_pair::iterator _it_uint32_string_pair
Definition at line 291 of file dnatypes.hpp.
_it_u32u32_uint32_pair
typedef v_u32u32_uint32_pair::iterator _it_u32u32_uint32_pair
Definition at line 292 of file dnatypes.hpp.
_it_uint32_u32u32_pair
typedef v_uint32_u32u32_pair::iterator _it_uint32_u32u32_pair
Definition at line 293 of file dnatypes.hpp.
_it_uint32_uint32_pair
typedef v_uint32_uint32_pair::iterator _it_uint32_uint32_pair
Definition at line 294 of file dnatypes.hpp.
_it_pair_u32u32_uint32
typedef std::pair<_it_u32u32_uint32_pair, _it_u32u32_uint32_pair> _it_pair_u32u32_uint32
Definition at line 296 of file dnatypes.hpp.
vv_string_string_pair
typedef std::vector<v_string_string_pair> vv_string_string_pair
Definition at line 298 of file dnatypes.hpp.
_it_pair_vUINT32_const
typedef std::pair<it_vUINT32_const, it_vUINT32_const> _it_pair_vUINT32_const
Definition at line 300 of file dnatypes.hpp.
it_pair_vUINT32
typedef std::pair<it_vUINT32, it_vUINT32> it_pair_vUINT32
Definition at line 301 of file dnatypes.hpp.
it_string_pair
typedef v_string_string_pair::iterator it_string_pair
Definition at line 304 of file dnatypes.hpp.
it_pair_string
typedef std::pair<v_string_string_pair::iterator, v_string_string_pair::iterator> it_pair_string
Definition at line 305 of file dnatypes.hpp.
it_pair_string_vUINT32
typedef std::pair<_it_string_uint32_pair, _it_string_uint32_pair> it_pair_string_vUINT32
Definition at line 306 of file dnatypes.hpp.
it_pair_uint32_string
typedef std::pair<_it_uint32_string_pair, _it_uint32_string_pair> it_pair_uint32_string
Definition at line 307 of file dnatypes.hpp.
it_pair_map_vUINT32_vUINT32
typedef std::pair<uint32_uint32_map::iterator, uint32_uint32_map::iterator> it_pair_map_vUINT32_vUINT32
Definition at line 309 of file dnatypes.hpp.
SIGMA_ZERO_STAT_PASS
typedef enum _SIGMA_ZERO_STAT_PASS_ SIGMA_ZERO_STAT_PASS
INPUT_FILE_TYPE
typedef enum _INPUT_FILE_TYPE_ INPUT_FILE_TYPE
INPUT_DATA_TYPE
typedef enum _INPUT_DATA_TYPE_ INPUT_DATA_TYPE
TIMER_TYPE
typedef enum _TIMER_TYPE_ TIMER_TYPE
ANGULAR_TYPE
typedef enum _ANGULAR_TYPE_ ANGULAR_TYPE
DMS_FORMAT
typedef enum _DMS_FORMAT_ DMS_FORMAT
COORD_TYPE
typedef enum _COORD_TYPE_ COORD_TYPE
STATION_ELEM
typedef enum _STATION_ELEM_ STATION_ELEM
CART_ELEM
typedef enum _CART_ELEM_ CART_ELEM
COORDINATE_TYPES
typedef enum _COORDINATE_TYPES_ COORDINATE_TYPES
HEIGHT_SYSTEM
typedef enum _HEIGHT_SYSTEM_ HEIGHT_SYSTEM
MEASUREMENT_STATIONS
typedef enum _MEASUREMENT_STATIONS_ MEASUREMENT_STATIONS
MEASUREMENT_START
typedef enum _MEASUREMENT_START_ MEASUREMENT_START
CONSTRAINT_TYPE
typedef enum _CONSTRAINT_TYPE_ CONSTRAINT_TYPE
AML_TYPE
typedef enum _AML_TYPE_ AML_TYPE
STAGE_FILE
typedef enum _STAGE_FILE_ STAGE_FILE
stationCorrections_t
typedef struct stationCorrections stationCorrections_t
vstnCor_t
typedef std::vector<stationCorrections_t> vstnCor_t
Definition at line 488 of file dnatypes.hpp.
pvstnCor_t
typedef std::vector<stationCorrections_t> * pvstnCor_t
Definition at line 488 of file dnatypes.hpp.
vvstnCor_t
typedef std::vector<vstnCor_t> vvstnCor_t
Definition at line 489 of file dnatypes.hpp.
it_vstnCor_t
typedef vstnCor_t::iterator it_vstnCor_t
Definition at line 490 of file dnatypes.hpp.
vstnPU_t
typedef std::vector<stationPosUncertainty_t> vstnPU_t
Definition at line 509 of file dnatypes.hpp.
pvstnPU_t
typedef std::vector<stationPosUncertainty_t> * pvstnPU_t
Definition at line 509 of file dnatypes.hpp.
vvstnPU_t
typedef std::vector<vstnPU_t> vvstnPU_t
Definition at line 510 of file dnatypes.hpp.
it_vstnPU_t
typedef vstnPU_t::iterator it_vstnPU_t
Definition at line 511 of file dnatypes.hpp.
blockMeta_t
typedef struct block_meta blockMeta_t
station_t
typedef struct stn_t station_t
vstn_t
typedef std::vector<station_t> vstn_t
Definition at line 598 of file dnatypes.hpp.
pvstn_t
typedef std::vector<station_t> * pvstn_t
Definition at line 598 of file dnatypes.hpp.
it_vstn_t
typedef vstn_t::iterator it_vstn_t
Definition at line 599 of file dnatypes.hpp.
it_vstn_t_const
typedef vstn_t::const_iterator it_vstn_t_const
Definition at line 600 of file dnatypes.hpp.
vsummary_t
typedef std::vector<statSummary_t> vsummary_t
Definition at line 601 of file dnatypes.hpp.
pvsummary_t
typedef std::vector<statSummary_t> * pvsummary_t
Definition at line 601 of file dnatypes.hpp.
stn_t_string_pair
typedef std::pair<station_t, std::string> stn_t_string_pair
Definition at line 603 of file dnatypes.hpp.
v_stn_string
typedef std::vector<stn_t_string_pair> v_stn_string
Definition at line 604 of file dnatypes.hpp.
it_stn_string
typedef v_stn_string::iterator it_stn_string
Definition at line 605 of file dnatypes.hpp.
input_file_meta_t
typedef struct input_file_meta input_file_meta_t
binary_file_meta_t
typedef struct binary_file_meta binary_file_meta_t
vifm_t
typedef std::vector<input_file_meta_t> vifm_t
Definition at line 640 of file dnatypes.hpp.
it_vifm_t
typedef vifm_t::iterator it_vifm_t
Definition at line 641 of file dnatypes.hpp.
vbfm_t
typedef std::vector<binary_file_meta_t> vbfm_t
Definition at line 642 of file dnatypes.hpp.
it_vbfm_t
typedef vbfm_t::iterator it_vbfm_t
Definition at line 643 of file dnatypes.hpp.
Enumeration Type Documentation
_SIGMA_ZERO_STAT_PASS_
enum _SIGMA_ZERO_STAT_PASS_
Enumerator
test_stat_pass
test_stat_warning
test_stat_fail
Definition at line 311 of file dnatypes.hpp.
{
    test_stat_pass = 0,
    test_stat_warning = 1,
    test_stat_fail = 2
} SIGMA_ZERO_STAT_PASS;
_INPUT_FILE_TYPE_
enum _INPUT_FILE_TYPE_
Enumerator
geodesyml
dynaml
dna
csv
sinex
Definition at line 318 of file dnatypes.hpp.
{
    geodesyml = 0,
    dynaml = 1,
    dna = 2,
    csv = 3,
    sinex = 4
} INPUT_FILE_TYPE;
_INPUT_DATA_TYPE_
enum _INPUT_DATA_TYPE_
Enumerator
stn_data
msr_data
stn_msr_data
geo_data
ren_data
tbu_data
unknown
Definition at line 327 of file dnatypes.hpp.
{
    stn_data = 0,
    msr_data = 1,
    stn_msr_data = 2,
    geo_data = 3,
    ren_data = 4,
    tbu_data = 5,
    unknown = 6
} INPUT_DATA_TYPE;
_TIMER_TYPE_
enum _TIMER_TYPE_
Enumerator
iteration_time
total_time
Definition at line 338 of file dnatypes.hpp.
{
    iteration_time = 0,
    total_time = 1
} TIMER_TYPE;
_ANGULAR_TYPE_
enum _ANGULAR_TYPE_
Enumerator
DMS
DDEG
Definition at line 344 of file dnatypes.hpp.
{
    DMS = 0,
    //#define DMIN 1
    DDEG = 1
} ANGULAR_TYPE;
_DMS_FORMAT_
enum _DMS_FORMAT_
Enumerator
SEPARATED
SEPARATED_WITH_SYMBOLS
HP_NOTATION
Definition at line 351 of file dnatypes.hpp.
{
    SEPARATED = 0,
    SEPARATED_WITH_SYMBOLS = 1,
    HP_NOTATION = 2
} DMS_FORMAT;
_COORD_TYPE_
enum _COORD_TYPE_
Enumerator
XYZ_type_i
LLh_type_i
LLH_type_i
UTM_type_i
ENU_type_i
AED_type_i
Definition at line 358 of file dnatypes.hpp.
{
    XYZ_type_i = 0,       // Cartesian
    LLh_type_i = 1,       // Geographic (ellipsoid height)
    LLH_type_i = 2,       // Geographic (orthometric height)
    UTM_type_i = 3,       // Projection
    ENU_type_i = 4,       // Local
    AED_type_i = 5        // Azimuth, elevation and distance
} COORD_TYPE;
_STATION_ELEM_
enum _STATION_ELEM_
Enumerator
station_1
station_2
station_3
Definition at line 368 of file dnatypes.hpp.
{
    station_1 = 0,
    station_2 = 1,
    station_3 = 2
} STATION_ELEM;
_CART_ELEM_
enum _CART_ELEM_
Enumerator
x_element
y_element
z_element
Definition at line 375 of file dnatypes.hpp.
{
    x_element = 0,
    y_element = 1,
    z_element = 2
} CART_ELEM;
_COORDINATE_TYPES_
enum _COORDINATE_TYPES_
Enumerator
latitude_t
longitude_t
easting_t
northing_t
Definition at line 382 of file dnatypes.hpp.
{
    latitude_t = 0,
    longitude_t = 1,
    easting_t = 2,
    northing_t = 3
} COORDINATE_TYPES;
_HEIGHT_SYSTEM_
enum _HEIGHT_SYSTEM_
Enumerator
ORTHOMETRIC_type_i
ELLIPSOIDAL_type_i
Definition at line 390 of file dnatypes.hpp.
{
    ORTHOMETRIC_type_i = 0,
    ELLIPSOIDAL_type_i = 1
} HEIGHT_SYSTEM;
_MEASUREMENT_STATIONS_
enum _MEASUREMENT_STATIONS_
Enumerator
ONE_STATION
TWO_STATION
THREE_STATION
UNKNOWN_TYPE
Definition at line 396 of file dnatypes.hpp.
{
    ONE_STATION = 1,
    TWO_STATION = 2,
    THREE_STATION = 3,
    UNKNOWN_TYPE = -1
} MEASUREMENT_STATIONS;
_MEASUREMENT_START_
enum _MEASUREMENT_START_
Enumerator
xMeas
yMeas
zMeas
xCov
yCov
zCov
Definition at line 403 of file dnatypes.hpp.
{
    xMeas = 0,
    yMeas = 1,
    zMeas = 2,
    xCov = 3,
    yCov = 4,
    zCov = 5
} MEASUREMENT_START;
_CONSTRAINT_TYPE_
enum _CONSTRAINT_TYPE_
Enumerator
free_3D
constrained_3D
free_2D
free_1D
custom_constraint
Definition at line 412 of file dnatypes.hpp.
{
    free_3D = 0,         // FFF - positional or 3d adjustment
    constrained_3D = 1,       // CCC
    free_2D = 2,         // FFC - horizontal or 2d adjustment. Implies vertical is tightly constrained (or fixed).
    free_1D = 3,         // CCF - vertical or 1d adjustment. Implies horizontal is tightly constrained (or fixed).
    custom_constraint = 4   // A custom constraint type that isn't necessarily
} CONSTRAINT_TYPE;
_AML_TYPE_
enum _AML_TYPE_
Enumerator
str_msr
cls_msr
Definition at line 420 of file dnatypes.hpp.
{
    str_msr = 0, // msr_t struct
    cls_msr = 1      // CDnaMeasurement class
} AML_TYPE;
iosMode
enum iosMode
Enumerator
binary
ascii
Definition at line 425 of file dnatypes.hpp.
{
    binary = 0,
    ascii = 1
};
mtxType
enum mtxType
Enumerator
mtx_full
mtx_lower
mtx_sparse
Definition at line 431 of file dnatypes.hpp.
{
    // mtx_full is intended for non-square matrices which are
    // commonly fully populated, such as a vector of estimates.
    // In this case, the whole buffer is copied/stored.
    mtx_full = 0,
    // mtx_lower is intended for square matrices, such as
    // full variance matrices and normal equations.
    // In this case, data is stored in columns, from left to right
    mtx_lower = 1,
    // mtx_sparse is intended for matrices which have many
    // zeros, such as design and AtV-1 matrices.
    // In this case, each element is stored with its index
    mtx_sparse = 2
};
_STAGE_FILE_
enum _STAGE_FILE_
Enumerator
sf_normals
sf_normals_r
sf_atvinv
sf_design
sf_meas_minus_comp
sf_estimated_stns
sf_original_stns
sf_rigorous_stns
sf_junction_vars
sf_junction_vars_f
sf_junction_ests_f
sf_junction_ests_r
sf_rigorous_vars
sf_prec_adj_msrs
sf_corrections
Definition at line 447 of file dnatypes.hpp.
{
    sf_normals = 0,
    sf_normals_r = 1,
    sf_atvinv = 2,
    sf_design = 3,
    sf_meas_minus_comp = 4,
    sf_estimated_stns = 5,
    sf_original_stns = 6,
    sf_rigorous_stns = 7,
    sf_junction_vars = 8,
    sf_junction_vars_f = 9,
    sf_junction_ests_f = 10,
    sf_junction_ests_r = 11,
    sf_rigorous_vars = 12,
    sf_prec_adj_msrs = 13,
    sf_corrections = 14
} STAGE_FILE;
Function Documentation
STN_NAME_WIDTH()
const UINT16 STN_NAME_WIDTH (31)
Referenced by dynadjust::iostreams::dna_io_map::load_map_file(), dynadjust::iostreams::dna_io_map::write_map_file(), and dynadjust::measurements::CDnaStation::WriteBinaryStn().
STN_NAME_ORIG_WIDTH()
const UINT16 STN_NAME_ORIG_WIDTH (40)
STN_DESC_WIDTH()
const UINT16 STN_DESC_WIDTH (129)
Referenced by dynadjust::measurements::CDnaStation::WriteBinaryStn().
STN_CONST_WIDTH()
const UINT16 STN_CONST_WIDTH (4)
Referenced by dynadjust::networkadjust::dna_adjust::ApplyAdditionalConstraints(), and dynadjust::measurements::CDnaStation::WriteBinaryStn().
STN_TYPE_WIDTH()
const UINT16 STN_TYPE_WIDTH (4)
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_YLLH(), and dynadjust::measurements::CDnaStation::WriteBinaryStn().
STN_EPSG_WIDTH()
const UINT16 STN_EPSG_WIDTH (7)
Referenced by dynadjust::dynamlinterop::dna_import::InitialiseDatum(), dynadjust::dynamlinterop::dna_import::ParseInputFile(), dynadjust::iostreams::dna_io_base::readFileMetadata(), dynadjust::referenceframe::dna_reftran::WriteBinaryMeasurementFile(), dynadjust::measurements::CDnaCovariance::WriteBinaryMsr(), dynadjust::measurements::CDnaGpsBaseline::WriteBinaryMsr(), dynadjust::measurements::CDnaGpsPoint::WriteBinaryMsr(), dynadjust::referenceframe::dna_reftran::WriteBinaryStationFile(), dynadjust::measurements::CDnaStation::WriteBinaryStn(), and dynadjust::iostreams::dna_io_base::writeFileMetadata().
STN_EPOCH_WIDTH()
const UINT16 STN_EPOCH_WIDTH (12)
Referenced by dynadjust::dynamlinterop::dna_import::InitialiseDatum(), dynadjust::dynamlinterop::dna_import::ParseInputFile(), dynadjust::iostreams::dna_io_base::readFileMetadata(), dynadjust::referenceframe::dna_reftran::WriteBinaryMeasurementFile(), dynadjust::measurements::CDnaAngle::WriteBinaryMsr(), dynadjust::measurements::CDnaCoordinate::WriteBinaryMsr(), dynadjust::measurements::CDnaCovariance::WriteBinaryMsr(), dynadjust::measurements::CDnaDirection::WriteBinaryMsr(), dynadjust::measurements::CDnaDirectionSet::WriteBinaryMsr(), dynadjust::measurements::CDnaDistance::WriteBinaryMsr(), dynadjust::measurements::CDnaGpsBaseline::WriteBinaryMsr(), dynadjust::measurements::CDnaGpsPoint::WriteBinaryMsr(), dynadjust::measurements::CDnaHeight::WriteBinaryMsr(), dynadjust::measurements::CDnaHeightDifference::WriteBinaryMsr(), dynadjust::referenceframe::dna_reftran::WriteBinaryStationFile(), dynadjust::measurements::CDnaStation::WriteBinaryStn(), and dynadjust::iostreams::dna_io_base::writeFileMetadata().
STN_PLATE_WIDTH()
const UINT16 STN_PLATE_WIDTH (3)
MOD_NAME_WIDTH()
const UINT32 MOD_NAME_WIDTH (20)
Referenced by dynadjust::iostreams::dna_io_base::readFileMetadata(), and dynadjust::iostreams::dna_io_base::writeFileMetadata().
FILE_NAME_WIDTH()
const UINT32 FILE_NAME_WIDTH (256)
Referenced by dynadjust::iostreams::dna_io_base::readFileMetadata(), and dynadjust::iostreams::dna_io_base::writeFileMetadata().
formatStnMsrFileSourceString()
template<typename S> S formatStnMsrFileSourceString (const vifm_t * vfile_meta, const size_t & file_type)
Definition at line 646 of file dnatypes.hpp.
{
    std::string source_files("");
    bool this_file;
    for (UINT32 i(0); i<vfile_meta->size(); ++i)
    {
        this_file= false;
        switch (file_type)
        {
        case stn_data:
            if (vfile_meta->at(i).datatype == stn_data ||
                vfile_meta->at(i).datatype == stn_msr_data)
                this_file= true;
            break;
        case msr_data:
            if (vfile_meta->at(i).datatype == msr_data ||
                vfile_meta->at(i).datatype == stn_msr_data)
                this_file= true;
            break;
        case stn_msr_data:
            if (vfile_meta->at(i).datatype == stn_data ||
                vfile_meta->at(i).datatype == msr_data ||
                vfile_meta->at(i).datatype == stn_msr_data)
                this_file= true;
            break;
        }
        if (this_file)
        {
            source_files += vfile_meta->at(i).filename;
            source_files += " ";
        }
    }
    return source_files;
}
References msr_data, stn_data, and stn_msr_data.
Referenced by dynadjust::dynamlinterop::dna_import::InitialiseDynaMLFile(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLSepMeasurementFile(), dynadjust::dynamlinterop::dna_import::InitialiseDynaMLSepStationFile(), dynadjust::dynamlinterop::dna_import::SerialiseMSR(), and dynadjust::dynamlinterop::dna_import::SerialiseSTN().
FormatFileType()
template<typename S = std::string> S FormatFileType (const size_t & file_type)
Definition at line 685 of file dnatypes.hpp.
{
    switch (file_type)
    {
    case dna:
        return "DNA";
        break;
    case sinex:
        return "SNX";
        break;
    case geodesyml:
        return "GML";
        break;
    case dynaml:
        return "XML";
        break;
    case csv:
        return "CSV";
        break;
    }
    return "unknown";
}
References csv, dna, dynaml, geodesyml, and sinex.
Referenced by ImportDataFiles().
Variable Documentation
LOWER_TRIANGLE
const char LOWER_TRIANGLE = 'L'
Definition at line 68 of file dnatypes.hpp.
Referenced by dynadjust::iostreams::dna_io_snx::parse_sinex_msr().
UPPER_TRIANGLE
const char UPPER_TRIANGLE = 'U'
Definition at line 69 of file dnatypes.hpp.
VALID_STATION
const UINT16 VALID_STATION = 1
Definition at line 71 of file dnatypes.hpp.
Referenced by dynadjust::measurements::CAStationList::CAStationList(), dynadjust::measurements::CAStationList::CAStationList(), dynadjust::measurements::CAStationList::IsValid(), and dynadjust::measurements::CDnaStation::SetStationRec().
INVALID_STATION
const UINT16 INVALID_STATION = 0
Definition at line 72 of file dnatypes.hpp.
Referenced by dynadjust::measurements::CAStationList::CAStationList(), dynadjust::measurements::CDnaStation::CDnaStation(), dynadjust::measurements::CDnaStation::CDnaStation(), and dynadjust::measurements::CAStationList::IsInvalid().