DynAdjust: include/functions/dnatemplatestnmsrfuncs.hpp File Reference
dnatemplatestnmsrfuncs.hpp File Reference
#include <include/config/dnaexports.hpp>
#include <include/functions/dnatemplatefuncs.hpp>
#include <include/config/dnatypes.hpp>
#include <include/measurement_types/dnameasurement_types.hpp>
Classes
class CompareStationName< T, S >
class EqualStationNameSaveDuplicates< T, S >
class EqualStationName< T >
class EqualStationName_CaseInsensitive< T, S >
class TestEqualStationName< T, S >
class TestNotEqualStationName< T, S >
class NearbyStation_LowAcc< T, S, U >
class NearbyStation_HighAcc< T, U, S, E >
class FindStnsWithinBoundingBox< T >
class FindMsrsConnectedToStns_GX< U >
class FindMsrsConnectedToStns_Y< U >
class FindMsrsConnectedToStns_D< U >
class FindMsrsConnectedToStns< T >
class SortDirectionsObsClockwise< T >
class CompareLatitude< T >
class CompareLongitude< T >
class CompareMsr< M >
class StationNameIDCompareName
class StationNameIDCompareID
class ParamStnMsrCompareStn
Functions
template<typename T>
void GetGXMsrStations (std::vector< CDnaGpsBaseline > *vgpsBsls, std::vector< T > &msrStations)
template<typename T>
void GetMsrStations (const vmsr_t &binaryMsrs, const T &bmsIndex, std::vector< T > &msrStations)
template<typename T>
void GetMsrIndices (const vmsr_t &binaryMsrs, const T &bmsIndex, std::vector< T > &msrIndices)
template<typename T>
T GetFirstMsrIndex (const vmsr_t &binaryMsrs, const T &bmsIndex)
template<typename T, typename Iter>
void RenameStationsMsr (T *msr, Iter begin, Iter end)
template<typename T, typename Iter>
void IgnoreGXMeasurements (T *msr, Iter begin, Iter end)
template<typename T, typename msriterator>
void CopyClusterMsr (T &cluster, const msriterator _it_msr, T &clusterCopy)
template<typename T>
void ResetMeasurementPtr (dnaMsrPtr *msrPtr, const T &cType)
template<class CharT, class Traits>
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &is, CAStationList t)
template<class CharT, class Traits>
std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > &is, CAStationList *t)
template<class CharT, class TraitsT>
std::basic_ostream< CharT, TraitsT > & operator<< (std::basic_ostream< CharT, TraitsT > &os, CAStationList t)
template<class CharT, class TraitsT>
std::basic_ostream< CharT, TraitsT > & operator<< (std::basic_ostream< CharT, TraitsT > &os, CAStationList *t)
Function Documentation
GetGXMsrStations()
template<typename T> void GetGXMsrStations (std::vector< CDnaGpsBaseline > * vgpsBsls, std::vector< T > & msrStations)
Definition at line 59 of file dnatemplatestnmsrfuncs.hpp.
{
    msrStations.clear();
    // Step 1. Set ignore flag for all baselines to true
    for_each(vgpsBsls->begin(), vgpsBsls->end(),
        [&msrStations](CDnaGpsBaseline& bsl) {
            msrStations.push_back(bsl.GetFirst());
            msrStations.push_back(bsl.GetTarget());
    });
    // Strip duplicate entries
    strip_duplicates(msrStations);
}
References strip_duplicates().
Referenced by dynadjust::dynamlinterop::dna_import::FindSimilarGXMeasurements().
GetMsrStations()
template<typename T> void GetMsrStations (const vmsr_t & binaryMsrs, const T & bmsIndex, std::vector< T > & msrStations)
Definition at line 77 of file dnatemplatestnmsrfuncs.hpp.
{
    msrStations.clear();
    T clusterID(binaryMsrs.at(bmsIndex).clusterID);
    it_vmsr_t_const _it_msr_start = binaryMsrs.begin() + bmsIndex;
    it_vmsr_t_const _it_msr_prev = _it_msr_start;
    bool bCluster(false);
    // I don't think this is necessary for X measruements, since
    // bmsIndex points to the first element in a cluster.  Perhaps keep
    // this here to safe guard against cases where bmsIndex is not the
    // first???
    switch (binaryMsrs.at(bmsIndex).measType)
    {
    case 'D':
    case 'X':
    case 'Y':
        // move to the beginning of the cluster
        while (_it_msr_start != binaryMsrs.begin())
        {
            if ((--_it_msr_prev)->clusterID != clusterID)
                break;
            _it_msr_start--;
        }
        bCluster = true;
        break;
    }
    while (_it_msr_start->clusterID == clusterID)       // Will be true for non-cluster measurements
    {
        if (_it_msr_start->measType != 'D')
        {
            if (_it_msr_start->measStart != xMeas)
            {
                if (++_it_msr_start == binaryMsrs.end())
                    break;
                continue;
            }
        }
        // add the relevant stations
        // Station 1 is in all measurement types
        msrStations.push_back(_it_msr_start->station1);
        // Station 2 is in two- and three-station measurements
        if (MsrTally::Stations(_it_msr_start->measType) >= TWO_STATION)
            msrStations.push_back(_it_msr_start->station2);
        // Station 3 is only in three-station measurements
        if (MsrTally::Stations(_it_msr_start->measType) == THREE_STATION)
            msrStations.push_back(_it_msr_start->station3);
        if (!bCluster)
            break;
        if (++_it_msr_start == binaryMsrs.end())
            break;
    }
    // Strip duplicate entries
    strip_duplicates(msrStations);
}
References dynadjust::measurements::MsrTally::Stations(), strip_duplicates(), THREE_STATION, TWO_STATION, and xMeas.
Referenced by dynadjust::networksegment::dna_segment::FindCommonMeasurements(), dynadjust::networksegment::dna_segment::GetInnerMeasurements(), dynadjust::networksegment::dna_segment::IdentifyInnerMsrsandAssociatedStns(), dynadjust::networksegment::dna_segment::VerifyStationConnections_Block(), and dynadjust::iostreams::dna_io_seg::write_seg_block().
GetMsrIndices()
template<typename T> void GetMsrIndices (const vmsr_t & binaryMsrs, const T & bmsIndex, std::vector< T > & msrIndices)
Definition at line 144 of file dnatemplatestnmsrfuncs.hpp.
{
    msrIndices.clear();
    // First, sift out conventional measurement types and return immediately.
    switch (binaryMsrs.at(bmsIndex).measType)
    {
    case 'D':
    case 'X':
    case 'Y':
        // Clusters dealt with after this switch statement
        break;
    default:
        // basic measurement type for which there is only one index, so
        // add the index and return
        msrIndices.push_back(bmsIndex);
        return;
    }
    // Ok, now deal with cluster measurements
    UINT32 clusterID(binaryMsrs.at(bmsIndex).clusterID);
    it_vmsr_t_const _it_msr_start(binaryMsrs.begin() + bmsIndex);
    it_vmsr_t_const _it_msr_prev(_it_msr_start);
    // move to the beginning of the cluster
    while (_it_msr_start != binaryMsrs.begin())
    {
        if ((--_it_msr_prev)->clusterID != clusterID)
            break;
        --_it_msr_start;
    }
    while (_it_msr_start->clusterID == clusterID && _it_msr_start != binaryMsrs.end())
    {
        if (_it_msr_start->ignore)
        {
            if (++_it_msr_start == binaryMsrs.end())
                break;
            continue;
        }
        if (_it_msr_start->measType != 'D')
        {
            if (_it_msr_start->measStart > xMeas)
            {
                if (++_it_msr_start == binaryMsrs.end())
                    break;
                continue;
            }
        }
        msrIndices.push_back(static_cast<T>(std::distance(binaryMsrs.begin(), _it_msr_start)));
        if (++_it_msr_start == binaryMsrs.end())
            break;
    }
    // Sort and strip duplicate entries
    strip_duplicates(msrIndices);
}
References strip_duplicates(), and xMeas.
Referenced by dynadjust::networkplot::dna_plot::PrintMeasurementsDatFileBlock(), and dynadjust::iostreams::dna_io_aml::write_aml_file_txt().
GetFirstMsrIndex()
template<typename T> T GetFirstMsrIndex (const vmsr_t & binaryMsrs, const T & bmsIndex)
Definition at line 209 of file dnatemplatestnmsrfuncs.hpp.
{
    // First, sift out conventional measurement types and return immediately.
    switch (binaryMsrs.at(bmsIndex).measType)
    {
    case 'D':
    case 'X':
    case 'Y':
        // Clusters dealt with after this switch statement
        break;
    default:
        // basic measurement type for which there is only one index, so
        // return bmsIndex
        return bmsIndex;
    }
    // Ok, now deal with cluster measurements
    UINT32 clusterID(binaryMsrs.at(bmsIndex).clusterID);
    it_vmsr_t_const _it_msr_start(binaryMsrs.begin() + bmsIndex);
    it_vmsr_t_const _it_msr_prev(_it_msr_start);
    // move to the beginning of the cluster
    while (_it_msr_start != binaryMsrs.begin())
    {
        if ((--_it_msr_prev)->clusterID != clusterID)
            break;
        --_it_msr_start;
    }
    // return the index of the measurement's first record in the binary measurement file
    return static_cast<UINT32>(std::distance(binaryMsrs.begin(), _it_msr_start));
}
Referenced by dynadjust::networksegment::dna_segment::AddtoCurrentMsrList().
RenameStationsMsr()
template<typename T, typename Iter> void RenameStationsMsr (T * msr, Iter begin, Iter end)
Definition at line 278 of file dnatemplatestnmsrfuncs.hpp.
{
    _it_string_vstring_pair it;
    Iter original = begin;
    // Search the aliases for the first station name
    // Emulate for_each behaviour
    while (begin != end)
    {
        if (binary_search(begin->second.begin(), begin->second.end(), msr->GetFirst()))
        {
            msr->SetFirst(begin->first);
            break;
        }
        ++begin;
    }
    // Is this measurement a one-station measurement?
    if (msr->m_MSmeasurementStations == ONE_STATION)
        return;
    // Search the aliases for the second station name
    // Emulate for_each behaviour
    begin = original;
    while (begin != end)
    {
        if (binary_search(begin->second.begin(), begin->second.end(), msr->GetTarget()))
        {
            msr->SetTarget(begin->first);
            break;
        }
        ++begin;
    }
    // Is this measurement a two-station measurement?
    if (msr->m_MSmeasurementStations == TWO_STATION)
        return;
    // Search the aliases for the third station name
    // Emulate for_each behaviour
    begin = original;
    while (begin != end)
    {
        if (binary_search(begin->second.begin(), begin->second.end(), msr->GetTarget2()))
        {
            msr->SetTarget2(begin->first);
            break;
        }
        ++begin;
    }
}
References ONE_STATION, and TWO_STATION.
IgnoreGXMeasurements()
template<typename T, typename Iter> void IgnoreGXMeasurements (T * msr, Iter begin, Iter end)
Definition at line 331 of file dnatemplatestnmsrfuncs.hpp.
{
    // Search the aliases for the first station name
    // Emulate for_each behaviour
    if (binary_search(begin, end, msr->GetClusterID()))
    {
        msr->SetIgnore(true);
        for_each(msr->GetBaselines_ptr()->begin(),
            msr->GetBaselines_ptr()->end(),
            [] (CDnaGpsBaseline& bsl) {
                bsl.SetIgnore(true);
        });
    }
}
Referenced by dynadjust::dynamlinterop::dna_import::FindSimilarGXMeasurements().
CopyClusterMsr()
template<typename T, typename msriterator> void CopyClusterMsr (T & cluster, const msriterator _it_msr, T & clusterCopy)
Definition at line 350 of file dnatemplatestnmsrfuncs.hpp.
{
    clusterCopy.clear();
    // First, sift out conventional measurement types and return immediately.
    switch (_it_msr->measType)
    {
    case 'D':
    case 'X':
    case 'Y':
        // Clusters dealt with after this switch statement
        break;
    default:
        // basic measurement type for which there is only one element
        clusterCopy.push_back(*_it_msr);
        return;
    }
    // Ok, now deal with cluster measurements
    UINT32 clusterID(_it_msr->clusterID);
    msriterator _it_msr_start(_it_msr);
    msriterator _it_msr_temp(_it_msr_start);
    while (_it_msr_start != cluster.begin())
    {
        if ((--_it_msr_temp)->clusterID != clusterID)
            break;
        --_it_msr_start;
    }
    msriterator _it_msr_last(_it_msr);
    while (_it_msr_last != cluster.end())
    {
        if ((++_it_msr_temp)->measType != 'Y')
        {
            ++_it_msr_last;
            break;
        }
        ++_it_msr_last;
    }
    clusterCopy.insert(clusterCopy.begin(), _it_msr_start, _it_msr_last);
}
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjMeasurements_YLLH(), and dynadjust::networkadjust::dna_adjust::PrintCompMeasurements_YLLH().
ResetMeasurementPtr()
template<typename T> void ResetMeasurementPtr (dnaMsrPtr * msrPtr, const T & cType)
Definition at line 735 of file dnatemplatestnmsrfuncs.hpp.
{
    switch (cType)
    {
    case 'A': // Horizontal angle
        msrPtr->reset(new CDnaAngle);
        break;
    case 'B': // Geodetic azimuth
    case 'K': // Astronomic azimuth
        msrPtr->reset(new CDnaAzimuth);
        break;
    case 'C': // Chord dist
    case 'E': // Ellipsoid arc
    case 'M': // MSL arc
    case 'S': // Slope distance
        msrPtr->reset(new CDnaDistance);
        break;
    case 'D': // Direction set
        msrPtr->reset(new CDnaDirectionSet);
        break;
    case 'G': // GPS Baseline (treat as single-baseline cluster)
    case 'X': // GPS Baseline cluster
        msrPtr->reset(new CDnaGpsBaselineCluster);
        break;
    case 'H': // Orthometric height
        msrPtr->reset(new CDnaHeight);
        break;
    case 'I': // Astronomic latitude
    case 'J': // Astronomic longitude
    case 'P': // Geodetic latitude
    case 'Q': // Geodetic longitude
        msrPtr->reset(new CDnaCoordinate);
        break;
    case 'L': // Level difference
        msrPtr->reset(new CDnaHeightDifference);
        break;
    case 'R': // Ellipsoidal height
        msrPtr->reset(new CDnaHeight);
        break;
    case 'V': // Zenith distance
    case 'Z': // Vertical angle
        msrPtr->reset(new CDnaDirection);
        break;
    case 'Y': // GPS point cluster
        msrPtr->reset(new CDnaGpsPointCluster);
        break;
    }
}
Referenced by dynadjust::dynamlinterop::dna_import::ImportStnsMsrsFromBlock(), dynadjust::dynamlinterop::dna_import::ImportStnsMsrsFromNetwork(), dynadjust::referenceframe::dna_reftran::SerialiseDynaMLMsr(), and dynadjust::iostreams::dna_io_dna::write_msr_file().
operator>>() [1/2]
template<class CharT, class Traits> std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > & is, CAStationList t)
Definition at line 887 of file dnatemplatestnmsrfuncs.hpp.
{
    is.read(reinterpret_cast<char *>(t.GetAssocMsrCountPtr()), sizeof(UINT32));
    is.read(reinterpret_cast<char *>(t.GetAMLStnIndexPtr()), sizeof(UINT32));
    is.read(reinterpret_cast<char *>(t.ValidityPtr()), sizeof(UINT16));
    return is;
}
References dynadjust::measurements::CAStationList::GetAMLStnIndexPtr(), dynadjust::measurements::CAStationList::GetAssocMsrCountPtr(), and dynadjust::measurements::CAStationList::ValidityPtr().
operator>>() [2/2]
template<class CharT, class Traits> std::basic_istream< CharT, Traits > & operator>> (std::basic_istream< CharT, Traits > & is, CAStationList * t)
Definition at line 896 of file dnatemplatestnmsrfuncs.hpp.
{
    is.read(reinterpret_cast<char *>(t->GetAssocMsrCountPtr()), sizeof(UINT32));
    is.read(reinterpret_cast<char *>(t->GetAMLStnIndexPtr()), sizeof(UINT32));
    is.read(reinterpret_cast<char *>(t->ValidityPtr()), sizeof(UINT16));
    return is;
}
operator<<() [1/2]
template<class CharT, class TraitsT> std::basic_ostream< CharT, TraitsT > & operator<< (std::basic_ostream< CharT, TraitsT > & os, CAStationList t)
Definition at line 896 of file dnatemplatestnmsrfuncs.hpp.
{
    os.write(reinterpret_cast<char *>(t.GetAssocMsrCountPtr()), sizeof(UINT32));
    os.write(reinterpret_cast<char *>(t.GetAMLStnIndexPtr()), sizeof(UINT32));
    os.write(reinterpret_cast<char *>(t.ValidityPtr()), sizeof(UINT16));
    return os;
}
References dynadjust::measurements::CAStationList::GetAMLStnIndexPtr(), dynadjust::measurements::CAStationList::GetAssocMsrCountPtr(), and dynadjust::measurements::CAStationList::ValidityPtr().
operator<<() [2/2]
template<class CharT, class TraitsT> std::basic_ostream< CharT, TraitsT > & operator<< (std::basic_ostream< CharT, TraitsT > & os, CAStationList * t)
Definition at line 896 of file dnatemplatestnmsrfuncs.hpp.
{
    os.write(reinterpret_cast<char *>(t->GetAssocMsrCountPtr()), sizeof(UINT32));
    os.write(reinterpret_cast<char *>(t->GetAMLStnIndexPtr()), sizeof(UINT32));
    os.write(reinterpret_cast<char *>(t->ValidityPtr()), sizeof(UINT16));
    return os;
}