DynAdjust: include/functions/dnatemplatedatetimefuncs.hpp File Reference
dnatemplatedatetimefuncs.hpp File Reference
#include <include/functions/dnastrmanipfuncs.hpp>
Classes
struct _cumulative_days_in_year_< P >
class CUMULATIVE_DAY_YEAR
struct _month_names_< P >
class MONTH_NAMES
Functions
template<class T>
void dateSINEXFormat (T *os, const boost::gregorian::date &theDate, bool calculateSeconds=false)
template<class U>
U dateYear (const boost::gregorian::date &theDate)
template<class U>
U dateDOY (const boost::gregorian::date &theDate)
template<class U>
U dateMonth (const boost::gregorian::date &theDate)
template<class U>
U dateDay (const boost::gregorian::date &theDate)
template<class U>
U dateDaynumber (const boost::gregorian::date &theDate)
template<class U>
U todayYear ()
template<class U>
U todayMonth ()
template<class U>
U todayDay ()
template<class U>
U todayDaynumber ()
template<class U, class T>
T integerToDate (const U &integer)
template<class U, class T>
T dateToInteger (const T &theDate)
template<class U, class T>
T ymdToDate (const U &year, const U &month, const U &day)
template<class T>
T timeImmemorial ()
template<class T>
bool isTimeImmemorial (const T &theDate)
template<class T>
void year_doy_Average (const T &start_year, const T &end_year, const T &start_doy, const T &end_doy, T &average_year, T &average_doy)
template<class T>
T yearFraction (const boost::gregorian::date &epoch)
template<class T>
T referenceEpoch (const boost::gregorian::date &theDate)
template<class T>
T elapsedTime (const T &current_epoch, const T &reference_epoch)
template<class T>
T elapsedTime (const T &current_epoch, const boost::gregorian::date &reference_epoch)
template<class T>
T elapsedTime (const boost::gregorian::date &current_epoch, const T &reference_epoch)
template<class T>
T elapsedTime (const boost::gregorian::date &current_epoch, const boost::gregorian::date &reference_epoch)
template<class T>
boost::gregorian::date dateFromString_safe (const std::string &dateString)
template<class T, class S>
T dateFromStringstream_doy_year (S &thedate)
template<class T, class S>
T dateFromString_doy_year (S &thedate)
template<class T, class D>
T dateFromDouble_doy_year (const D &thedate)
template<class T>
std::string stringFromDate (const T &thedate)
template<class T>
std::string stringFromToday ()
template<class T>
std::string stringFromDate (const T &thedate, const std::string &format)
template<class T>
T dateFromString (const std::string &dateString)
template<class T>
std::string formattedDateStringFromNumericString (const std::string &dateString)
template<typename T>
T formattedDateTimeString ()
template<typename S>
S formatedElapsedTime (boost::posix_time::milliseconds *elapsed_time, S app_message)
Variables
const UINT32 TIME_IMMEMORIAL = 1900
template<class P>
short const _cumulative_days_in_year_< P >::cumulativeDays [2][12]
template<class P>
const char _month_names_< P >::monthNames [12][12]
Function Documentation
dateSINEXFormat()
template<class T> void dateSINEXFormat (T * os, const boost::gregorian::date & theDate, bool calculateSeconds = false)
Definition at line 80 of file dnatemplatedatetimefuncs.hpp.
{
    // Time stamps must be in the following format:  YY:DOY:SECOD
    // where:
    //   YY     : year
    //   DOY    : day of year
    //   SECOD  : sec of day (e.g. the epoch)
    // Example:
    //      95:120:86399 denotes April 30, 1995 (23:59:59UT).
    //
    std::stringstream year;
    boost::posix_time::time_facet* facet(new boost::posix_time::time_facet("%y"));
    year.imbue(std::locale(year.getloc(), facet));
    boost::posix_time::ptime dateTime(theDate);
    year << dateTime;
    std::stringstream dayofyear;
    dayofyear << std::right << std::setw(3) << theDate.day_of_year();
    std::string dayofyearstr(dayofyear.str());
    dayofyearstr = findandreplace<std::string>(dayofyearstr, " ", "0");
    *os <<
        std::right << std::setw(2) <<
            year.str() << ":" <<        // year (YY)
        std::right << std::setw(3) <<
            dayofyearstr << ":";        // day of year
    if (calculateSeconds)
    {
        boost::posix_time::ptime currentTime(boost::posix_time::second_clock::local_time());
        boost::posix_time::time_duration timeInterval(currentTime - dateTime);
        std::stringstream secondsofday;
        secondsofday << std::left << std::setw(5) << timeInterval.total_seconds();
        *os << std::left << std::setw(5) << secondsofday.str();
        return;
    }
    *os << "00000";
}
References findandreplace().
Referenced by dynadjust::iostreams::dna_io_snx::serialise_meta(), and dynadjust::iostreams::dna_io_snx::serialise_solution_estimates().
dateYear()
template<class U> U dateYear (const boost::gregorian::date & theDate)
Definition at line 124 of file dnatemplatedatetimefuncs.hpp.
{
    return theDate.year();
}
Referenced by todayYear().
dateDOY()
template<class U> U dateDOY (const boost::gregorian::date & theDate)
Definition at line 130 of file dnatemplatedatetimefuncs.hpp.
{
    return theDate.day_of_year();
}
dateMonth()
template<class U> U dateMonth (const boost::gregorian::date & theDate)
Definition at line 136 of file dnatemplatedatetimefuncs.hpp.
{
    return theDate.month();
}
Referenced by todayMonth().
dateDay()
template<class U> U dateDay (const boost::gregorian::date & theDate)
Definition at line 142 of file dnatemplatedatetimefuncs.hpp.
{
    return theDate.day();
}
Referenced by todayDay().
dateDaynumber()
template<class U> U dateDaynumber (const boost::gregorian::date & theDate)
Definition at line 148 of file dnatemplatedatetimefuncs.hpp.
{
    return theDate.day_number();
}
Referenced by dateToInteger(), and todayDaynumber().
todayYear()
template<class U> U todayYear ()
Definition at line 154 of file dnatemplatedatetimefuncs.hpp.
{
    return dateYear<U>(boost::gregorian::day_clock::local_day());
}
References dateYear().
todayMonth()
template<class U> U todayMonth ()
Definition at line 160 of file dnatemplatedatetimefuncs.hpp.
{
    return dateMonth<U>(boost::gregorian::day_clock::local_day());
}
References dateMonth().
todayDay()
template<class U> U todayDay ()
Definition at line 166 of file dnatemplatedatetimefuncs.hpp.
{
    return dateDay<U>(boost::gregorian::day_clock::local_day());
}
References dateDay().
todayDaynumber()
template<class U> U todayDaynumber ()
Definition at line 172 of file dnatemplatedatetimefuncs.hpp.
{
    return dateDaynumber<U>(boost::gregorian::day_clock::local_day());
}
References dateDaynumber().
integerToDate()
template<class U, class T> T integerToDate (const U & integer)
Definition at line 178 of file dnatemplatedatetimefuncs.hpp.
{
    return boost::gregorian::date(integer);
}
dateToInteger()
template<class U, class T> T dateToInteger (const T & theDate)
Definition at line 184 of file dnatemplatedatetimefuncs.hpp.
{
    return dateDaynumber(theDate);
}
References dateDaynumber().
ymdToDate()
template<class U, class T> T ymdToDate (const U & year, const U & month, const U & day)
Definition at line 190 of file dnatemplatedatetimefuncs.hpp.
{
    return boost::gregorian::date(year, month, day);
}
timeImmemorial()
template<class T> T timeImmemorial ()
Definition at line 196 of file dnatemplatedatetimefuncs.hpp.
{
    return T(TIME_IMMEMORIAL, 1, 1);
}
References TIME_IMMEMORIAL.
Referenced by dynadjust::dynamlinterop::dna_import::InitialiseDatum(), and dynadjust::datum_parameters::CDnaDatum::SetEpoch().
isTimeImmemorial()
template<class T> bool isTimeImmemorial (const T & theDate)
Definition at line 202 of file dnatemplatedatetimefuncs.hpp.
{
    return theDate < T(TIME_IMMEMORIAL, 1, 2);
}
References TIME_IMMEMORIAL.
Referenced by dynadjust::datum_parameters::CDnaDatum::GetEpoch_s().
year_doy_Average()
template<class T> void year_doy_Average (const T & start_year, const T & end_year, const T & start_doy, const T & end_doy, T & average_year, T & average_doy)
Definition at line 264 of file dnatemplatedatetimefuncs.hpp.
{
    if (start_year != end_year)
    {
        average_doy = average(start_doy, start_doy + end_doy);
        if (average_doy > DAYS_PER_YEAR)
        {
            average_year = end_year;
            average_doy -= static_cast<T>(DAYS_PER_YEAR);
        }
        else
            average_year = start_year;
        return;
    }
    average_year = start_year;
    if (start_doy != end_doy)
        average_doy = average(start_doy, end_doy);
    else
        average_doy = start_doy;
}
References average(), and DAYS_PER_YEAR().
Referenced by dynadjust::iostreams::dna_io_snx::parse_sinex_header().
yearFraction()
template<class T> T yearFraction (const boost::gregorian::date & epoch)
Definition at line 291 of file dnatemplatedatetimefuncs.hpp.
{
    // Day of year, less 0.5 day correction to
    // bring to middle of day, divided by number
    // of days in a year
    //return (dateDOY<T>(epoch) - 0.5) / DAYS_PER_YEAR;
    short leap(0);
    T days_in_year(365);
    if (fmod((T)epoch.year(), 400.) == 0)
    {
        leap = 1;
        days_in_year = 366;
    }
    else if (fmod((T)epoch.year(), 100.) == 0)
        leap = 0;
    else if (fmod((T)epoch.year(), 4.) == 0)
    {
        leap = 1;
        days_in_year = 366;
    }
    else
        leap = 0;
    T day_of_year(CUMULATIVE_DAY_YEAR::cumulativeDays[leap][epoch.month() - 1] + epoch.day());
    return (day_of_year - (T)0.5) / days_in_year;
}
References _cumulative_days_in_year_< void >::cumulativeDays.
Referenced by referenceEpoch().
referenceEpoch()
template<class T> T referenceEpoch (const boost::gregorian::date & theDate)
Definition at line 323 of file dnatemplatedatetimefuncs.hpp.
{
    // Epoch of interest
    return yearFraction<T>(theDate) + theDate.year();
}
References yearFraction().
Referenced by dynadjust::referenceframe::dna_reftran::DetermineElapsedTime(), elapsedTime(), elapsedTime(), elapsedTime(), dynadjust::referenceframe::dna_reftran::TransformEpochs_PlateMotionModel(), and dynadjust::referenceframe::dna_reftran::TransformFrames_WithoutPlateMotionModel().
elapsedTime() [1/4]
template<class T> T elapsedTime (const T & current_epoch, const T & reference_epoch)
Definition at line 331 of file dnatemplatedatetimefuncs.hpp.
{
    // Elapsed time
    return (current_epoch - reference_epoch);
}
Referenced by dynadjust::referenceframe::dna_reftran::DetermineElapsedTime(), elapsedTime(), elapsedTime(), elapsedTime(), and ReduceParameters().
elapsedTime() [2/4]
template<class T> T elapsedTime (const T & current_epoch, const boost::gregorian::date & reference_epoch)
Definition at line 339 of file dnatemplatedatetimefuncs.hpp.
{
    return elapsedTime(current_epoch, referenceEpoch<T>(reference_epoch));
}
References elapsedTime(), and referenceEpoch().
elapsedTime() [3/4]
template<class T> T elapsedTime (const boost::gregorian::date & current_epoch, const T & reference_epoch)
Definition at line 346 of file dnatemplatedatetimefuncs.hpp.
{
    return elapsedTime(referenceEpoch<T>(current_epoch), reference_epoch);
}
References elapsedTime(), and referenceEpoch().
elapsedTime() [4/4]
template<class T> T elapsedTime (const boost::gregorian::date & current_epoch, const boost::gregorian::date & reference_epoch)
Definition at line 353 of file dnatemplatedatetimefuncs.hpp.
{
    return elapsedTime(referenceEpoch<T>(current_epoch), referenceEpoch<T>(reference_epoch));
}
References elapsedTime(), and referenceEpoch().
dateFromString_safe()
template<class T> boost::gregorian::date dateFromString_safe (const std::string & dateString)
Definition at line 360 of file dnatemplatedatetimefuncs.hpp.
{
    std::vector<std::string> vdateList;
    SplitDelimitedString<std::string>(dateString, std::string("."), &vdateList);
    try {
        // boost date requires input in the following order: year, month, day
        return boost::gregorian::date(
            LongFromString<UINT32>(vdateList.at(2)),  // year
            LongFromString<UINT32>(vdateList.at(1)),  // month
            LongFromString<UINT32>(vdateList.at(0))); // day
    }
    catch (std::runtime_error& e)
    {
        std::stringstream ss;
        ss << "dateFromString_safe(): Could not parse the date string \"" << dateString << "\"" << std::endl <<
            "  Details: " << e.what() << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    catch (...)
    {
        std::stringstream ss;
        ss << "dateFromString_safe(): Could not parse the date string \"" << dateString << "\"." << std::endl <<
            "  Check that the epoch is formatted as dd.mm.yyyy" << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
}
References LongFromString(), and SplitDelimitedString().
Referenced by dateFromString().
dateFromStringstream_doy_year()
template<class T, class S> T dateFromStringstream_doy_year (S & thedate)
Definition at line 390 of file dnatemplatedatetimefuncs.hpp.
{
    T parsedDate;
    // From boost_1_54_0/doc/html/date_time/date_time_io.html
    // %j : Day of year as decimal from 001 to 366 for leap years, 001 - 365 for non-leap years.
    //      "060" => Feb-29
    // %y : Two digit year
    //      "05" => 2005
    // %Y : Four digit year
    //      "2005" => 2005
    // But! 94 => 2094!
    // So use %Y"
    thedate.imbue(std::locale(thedate.getloc(), new boost::gregorian::date_input_facet("%j %Y")));
    thedate >> parsedDate;
    return parsedDate;
}
Referenced by dynadjust::iostreams::dna_io_snx::parse_sinex_discontinuities(), dynadjust::iostreams::dna_io_snx::parse_sinex_header(), and dynadjust::iostreams::dna_io_snx::parse_sinex_stn().
dateFromString_doy_year()
template<class T, class S> T dateFromString_doy_year (S & thedate)
Definition at line 409 of file dnatemplatedatetimefuncs.hpp.
{
    T parsedDate;
    // From boost_1_54_0/doc/html/date_time/date_time_io.html
    // %j : Day of year as decimal from 001 to 366 for leap years, 001 - 365 for non-leap years.
    //      "060" => Feb-29
    // %y : Two digit year
    //      "05" => 2005
    // %Y : Four digit year
    //      "2005" => 2005
    // But! 94 => 2094!
    // So use %Y"
    std::stringstream ss_date;
    ss_date << thedate;
    ss_date.imbue(std::locale(ss_date.getloc(), new boost::gregorian::date_input_facet("%j %Y")));
    ss_date >> parsedDate;
    return parsedDate;
}
Referenced by dynadjust::iostreams::dna_io_snx::format_station_names().
dateFromDouble_doy_year()
template<class T, class D> T dateFromDouble_doy_year (const D & thedate)
Definition at line 430 of file dnatemplatedatetimefuncs.hpp.
{
    T parsedDate;
    D year(floor(thedate));
    D year_fraction(thedate - year);
    D days_in_year(365.0);
    if (fmod(year, 400.) == 0)
        days_in_year += 1.0;
    else if (fmod(year, 4.) == 0)
        days_in_year += 1.0;
    // Calculate integer day from floating point.
    // If this rounds up or down, the net result is a day before
    // or a day after.  For some applications, this might cause
    // one some concern.  But for reference frame geodesy and plate
    // tectonics, not a lot happens in a day so this is quite acceptable.
    D doy = year_fraction * days_in_year;
    size_t idoy = static_cast<size_t>(doy);
    if (idoy < 1)
        idoy = 1;
    // From boost_1_54_0/doc/html/date_time/date_time_io.html
    // %j : Day of year as decimal from 001 to 366 for leap years, 001 - 365 for non-leap years.
    //      "060" => Feb-29
    // %y : Two digit year
    //      "05" => 2005
    // %Y : Four digit year
    //      "2005" => 2005
    // But! 94 => 2094!
    // So use %Y"
    std::stringstream strdate;
    if (idoy < 10.)
        strdate << "00";
    else if (idoy < 100.)
        strdate << "0";
    strdate << idoy << " " << std::fixed << std::setprecision(0) << year;
    strdate.imbue(std::locale(strdate.getloc(), new boost::gregorian::date_input_facet("%j %Y")));
    strdate >> parsedDate;
    return parsedDate;
}
stringFromDate() [1/2]
template<class T> std::string stringFromDate (const T & thedate)
Definition at line 474 of file dnatemplatedatetimefuncs.hpp.
{
    std::stringstream ss;
    ss.imbue(std::locale(ss.getloc(), new boost::gregorian::date_facet("%d.%m.%Y")));
    ss << thedate;
    return ss.str();
}
Referenced by dateFromString(), dynadjust::datum_parameters::CDnaDatum::GetEpoch_s(), main(), and dynadjust::iostreams::dna_io_snx::parse_sinex_stn().
stringFromToday()
template<class T> std::string stringFromToday ()
Definition at line 485 of file dnatemplatedatetimefuncs.hpp.
{
    std::stringstream ss;
    ss.imbue(std::locale(ss.getloc(), new boost::gregorian::date_facet("%d.%m.%Y")));
    ss << boost::gregorian::date(boost::gregorian::day_clock::local_day());
    return ss.str();
}
Referenced by ParseCommandLineOptions(), and ParseCommandLineOptions().
stringFromDate() [2/2]
template<class T> std::string stringFromDate (const T & thedate, const std::string & format)
Definition at line 496 of file dnatemplatedatetimefuncs.hpp.
{
    std::stringstream ss;
    ss.imbue(std::locale(ss.getloc(), new boost::gregorian::date_facet(format.c_str())));
    ss << thedate;
    return ss.str();
}
dateFromString()
template<class T> T dateFromString (const std::string & dateString)
Definition at line 507 of file dnatemplatedatetimefuncs.hpp.
{
    // The following works well when dateString is "03.02.2013", but fails
    // if dateString is "3.2.2013".
    //
    //istringstream ss(dateString);
    //ss.imbue(std::locale(std::locale::classic(), new boost::gregorian::date_input_facet("%e.%m.%Y")));
    //T date;
    //ss >> date;
    //return date;
    //
    // The Boost.Gregorian documentation specifies that:
    //  %d      Day of the month as decimal 01 to 31
    //  %e #    Like %d, the day of the month as a decimal number, but a leading zero is replaced by a space
    //  The top part of the documentation states the following warning:
    //  The flags marked with a hash sign (#) are implemented by system locale and are known to be missing on some platforms
    // Is today's date required?
    if (boost::iequals(dateString, "today"))
        return dateFromString_safe<T>(stringFromDate<T>(T(boost::gregorian::day_clock::local_day())));
    // Parse manually.
    return dateFromString_safe<T>(dateString);
}
References dateFromString_safe(), and stringFromDate().
Referenced by dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements(), dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements_GX(), dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements_Y(), dynadjust::dynamlinterop::dna_import::FindSimilarGXMeasurements(), formattedDateStringFromNumericString(), dynadjust::referenceframe::dna_reftran::IsolateandApplySubstitute(), main(), dynadjust::datum_parameters::CDnaDatum::SetDatum(), dynadjust::datum_parameters::CDnaDatum::SetEpoch(), dynadjust::frame_substitutions::WGS84_G1150_ITRF2000< T1, T2, T3 >::WGS84_G1150_ITRF2000(), dynadjust::frame_substitutions::WGS84_G1674_ITRF2008< T1, T2, T3 >::WGS84_G1674_ITRF2008(), dynadjust::frame_substitutions::WGS84_G1762_ITRF2008< T1, T2, T3 >::WGS84_G1762_ITRF2008(), dynadjust::frame_substitutions::WGS84_G2139_ITRF2014< T1, T2, T3 >::WGS84_G2139_ITRF2014(), dynadjust::frame_substitutions::WGS84_G730_ITRF91< T1, T2, T3 >::WGS84_G730_ITRF91(), dynadjust::frame_substitutions::WGS84_G873_ITRF94< T1, T2, T3 >::WGS84_G873_ITRF94(), dynadjust::frame_substitutions::WGS84_ITRF2000< T1, T2, T3 >::WGS84_ITRF2000(), dynadjust::frame_substitutions::WGS84_ITRF2008_1< T1, T2, T3 >::WGS84_ITRF2008_1(), dynadjust::frame_substitutions::WGS84_ITRF2008_2< T1, T2, T3 >::WGS84_ITRF2008_2(), dynadjust::frame_substitutions::WGS84_ITRF2014< T1, T2, T3 >::WGS84_ITRF2014(), dynadjust::frame_substitutions::WGS84_ITRF90< T1, T2, T3 >::WGS84_ITRF90(), dynadjust::frame_substitutions::WGS84_ITRF91< T1, T2, T3 >::WGS84_ITRF91(), dynadjust::frame_substitutions::WGS84_ITRF94< T1, T2, T3 >::WGS84_ITRF94(), and dynadjust::frame_substitutions::WGS84_TRANSIT_ITRF90< T1, T2, T3 >::WGS84_TRANSIT_ITRF90().
formattedDateStringFromNumericString()
template<class T> std::string formattedDateStringFromNumericString (const std::string & dateString)
Definition at line 535 of file dnatemplatedatetimefuncs.hpp.
{
    boost::gregorian::date ddate(dateFromString<T>(dateString));
    std::stringstream ss;
    ss.imbue(std::locale(ss.getloc(), new boost::gregorian::date_facet("%A, %d %B %Y")));
    ss << ddate;
    return ss.str();
}
References dateFromString().
formattedDateTimeString()
template<typename T> T formattedDateTimeString ()
Definition at line 547 of file dnatemplatedatetimefuncs.hpp.
{
    std::stringstream datetime_ss, stream;
    boost::posix_time::time_facet* p_time_output = new boost::posix_time::time_facet;
    std::locale special_locale (std::locale(""), p_time_output);
    // special_locale takes ownership of the p_time_output facet
    datetime_ss.imbue (special_locale);
    (*p_time_output).format("%d-%m-%Y %X");
    datetime_ss << boost::posix_time::second_clock::local_time();
    stream << datetime_ss.str().c_str();
    return stream.str();
}
Referenced by PrintAppStartTimeMessage().
formatedElapsedTime()
template<typename S> S formatedElapsedTime (boost::posix_time::milliseconds * elapsed_time, S app_message)
Definition at line 563 of file dnatemplatedatetimefuncs.hpp.
{
    std::ostringstream ss_time;
    boost::posix_time::ptime pt(boost::posix_time::ptime(boost::gregorian::day_clock::local_day(), *elapsed_time));
    if (*elapsed_time < boost::posix_time::seconds(3))
    {
        boost::posix_time::time_facet* facet(new boost::posix_time::time_facet("%s"));
        ss_time.imbue(std::locale(ss_time.getloc(), facet));
        ss_time.str("");
        ss_time << pt << "s";
    }
    else if (*elapsed_time < boost::posix_time::seconds(61))
    {
        boost::posix_time::time_facet* facet(new boost::posix_time::time_facet("%S"));
        ss_time.imbue(std::locale(ss_time.getloc(), facet));
        ss_time.str("");
        ss_time << pt << "s";
    }
    else
        ss_time << boost::posix_time::seconds(static_cast<long>(elapsed_time->total_seconds()));
    size_t pos = std::string::npos;
    std::string time_message = ss_time.str();
    while ((pos = time_message.find("0s")) != std::string::npos)
        time_message = time_message.substr(0, pos) + "s";
    time_message = app_message + time_message + ".";
    if ((pos = time_message.find(" 00.")) != std::string::npos)
        time_message = time_message.replace(pos, 4, " 0.");
    if ((pos = time_message.find(" 0.s")) != std::string::npos)
        time_message = time_message.replace(pos, 4, " 0s");
    return time_message;
}
Referenced by main().
Variable Documentation
TIME_IMMEMORIAL
const UINT32 TIME_IMMEMORIAL = 1900
Definition at line 41 of file dnatemplatedatetimefuncs.hpp.
Referenced by dynadjust::iostreams::discontinuity_tuple_t< T1, T2, T3, T4 >::discontinuity_tuple_t(), isTimeImmemorial(), dynadjust::iostreams::dna_io_snx::parse_date_from_string(), and timeImmemorial().
_cumulative_days_in_year_< P >::cumulativeDays
template<class P> short const _cumulative_days_in_year_< P >::cumulativeDays[2][12]
Initial value:
=
    {{
        0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334
    },
    {
        0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335
    }}
Definition at line 215 of file dnatemplatedatetimefuncs.hpp.
    {{
        0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334
    },
    // leap year
    {
        0, 31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335
    }};
_month_names_< P >::monthNames
template<class P> const char _month_names_< P >::monthNames[12][12]
Initial value:
=
    {
        {"January"},
        {"February"},
        {"March"},
        {"April"},
        {"May"},
        {"June"},
        {"July"},
        {"August"},
        {"September"},
        {"October"},
        {"November"},
        {"December"}
    }
Definition at line 240 of file dnatemplatedatetimefuncs.hpp.
    {
        {"January"},
        {"February"},
        {"March"},
        {"April"},
        {"May"},
        {"June"},
        {"July"},
        {"August"},
        {"September"},
        {"October"},
        {"November"},
        {"December"}
    };