DynAdjust: include/functions/dnatemplatefuncs.hpp File Reference
dnatemplatefuncs.hpp File Reference
#include <include/config/dnatypes.hpp>
#include <include/measurement_types/dnameasurement.hpp>
Classes
class value_equals< K, V >
class CompareStationPairs< T >
class CompareClusterID< M, U >
class CompareMeasCount< A, U >
class CompareMeasCount2< A, U >
class CompareValidity< A, U >
class CompareMeasStart< M, U >
class CompareNonMeasStart< M, U >
class CompareMsrFileOrder< M, U >
class CompareBlockStationMapUnique_byBlock< U >
class CompareBlockStationMapUnique_Station< U, T >
class CompareBlockStationMapUnique_byFileOrder< S, U >
class CompareMeasType_PairFirst< M, U >
class CompareMeasFromStn_PairFirst< M, U >
class CompareMeasToStn_PairFirst< M, U >
class CompareMeasValue_PairFirst< M, U >
class CompareMeasResidual_PairFirst< M, U >
class CompareMeasAdjSD_PairFirst< M, U >
class CompareMeasNstat_PairFirst< M, U >
class CompareStnFileOrder< S, U >
class CompareStnName_CDnaStn< S, T >
class CompareStnFileOrder_CDnaStn< S >
class CompareStnFileOrder_StnBlockMap< S, U >
class CompareStnOrder_StnBlockMap< U >
class CompareStnName< T >
class CompareStnOriginalName< T, S >
class CompareStnLongitude< S, U >
class CompareMeasTypeT< M, C >
class CompareValidMeasTypeT< M >
class CompareScalars< T >
class CompareScalarStations< T, S >
class CompareValidFreeMeasType_vT< M, U, C >
class CompareIgnoreedMeas< M, U >
class CompareIgnoreedClusterMeas< M >
class CompareIgnoredMsr< M >
class CompareInsufficientClusterMeas< M >
class CompareInsufficientMsr< M >
class CompareEmptyClusterMeas< M >
class CompareClusterMsrFunc< M >
class CompareMeasType< M >
class CompareNonMeasType< M >
class CompareCovarianceStart< M, U >
class ComparePairSecond< T >
class ComparePairFirst< T >
class CompareOddPairFirst< T, U >
class CompareOddPairFirst_FileOrder< S, T, U >
class ComparePairSecondf< T >
class CompareFreeClusterAllStns< U, M, C >
class PairCompareFirst< T, U >
Functions
template<typename T>
bool isOdd (T integer)
template<typename T>
bool is_digit (const T &s)
template<typename T>
bool is_number (const T &s)
template<typename T>
bool is_floatingpoint (const T &s)
template<typename InputIterator, typename Predicate>
void copy_if_all_occurrences (InputIterator begin, InputIterator end, Predicate pred)
template<typename T, typename InputIterator, typename Predicate>
void erase_if_impl (T *t, InputIterator begin, InputIterator end, Predicate pred)
template<typename T, typename Predicate>
void erase_if (T &t, Predicate pred)
template<typename T, typename Predicate>
void erase_if (T *t, Predicate pred)
template<typename T>
void strip_duplicates (T &t)
template<typename T>
void strip_duplicates (T *t)
template<class T>
void outputObject (T t, std::ostream &os)
template<class S = std::string>
S FormatDateString (const S &datestring)
template<class T>
T ParseDmsString (const std::string &dmsString, const std::string &delimiter)
template<class T>
std::string FormatDmsString (const T &dDegMinSec, const int precision, bool withSpaces, bool withSymbols)
template<class T>
std::string FormatDnaDmsString (const T &dDegMinSec, int precision)
template<typename m>
bool isCompoundMeas (const m &msrType)
template<typename m>
bool notCompoundMeas (const m &msrType)
template<typename m>
bool isCompoundMeasAll (const m &msrType)
template<typename m>
bool notCompoundMeasAll (const m &msrType)
template<typename Iter, typename C>
Iter binary_search_index_noval (Iter begin, Iter end, C compare)
template<typename Iter, typename T, typename C>
Iter binary_search_index (Iter begin, Iter end, T value, C compare)
template<typename Iter, typename T>
Iter binary_search_index_pair (Iter begin, Iter end, T value)
Function Documentation
isOdd()
template<typename T> bool isOdd (T integer)
Definition at line 53 of file dnatemplatefuncs.hpp.
{
    return (integer %2 == 0);
}
is_digit()
template<typename T> bool is_digit (const T & s)
Definition at line 59 of file dnatemplatefuncs.hpp.
{
    return (!s.empty() &&
        std::find_if(s.begin(), s.end(), [](unsigned char c) {
            return !std::isdigit(c);
        }) == s.end());
}
is_number()
template<typename T> bool is_number (const T & s)
Definition at line 68 of file dnatemplatefuncs.hpp.
{
    return (
        s.find_first_not_of("0123456789") == std::string::npos);
}
Referenced by dynadjust::networkplot::dna_plot::CreateGMTCommandFile().
is_floatingpoint()
template<typename T> bool is_floatingpoint (const T & s)
Definition at line 75 of file dnatemplatefuncs.hpp.
{
    return (
        s.find_first_not_of("0123456789.") == std::string::npos);
}
Referenced by dynadjust::iostreams::dna_io_tbu::validate_typeb_values().
copy_if_all_occurrences()
template<typename InputIterator, typename Predicate> void copy_if_all_occurrences (InputIterator begin, InputIterator end, Predicate pred)
Definition at line 101 of file dnatemplatefuncs.hpp.
{
    InputIterator next;
    while (begin != end) {
        next = begin+1;
        while (next != end)
        {
            if (pred(*begin, *next))
                next++;
            else
                next = end;
        }
        ++begin;
    }
}
Referenced by dynadjust::dynamlinterop::dna_import::RemoveDuplicateStations().
erase_if_impl()
template<typename T, typename InputIterator, typename Predicate> void erase_if_impl (T * t, InputIterator begin, InputIterator end, Predicate pred)
Definition at line 119 of file dnatemplatefuncs.hpp.
{
    t->erase(std::remove_if(begin, end, pred), end);
}
Referenced by erase_if(), and erase_if().
erase_if() [1/2]
template<typename T, typename Predicate> void erase_if (T & t, Predicate pred)
Definition at line 125 of file dnatemplatefuncs.hpp.
{
    erase_if_impl(&t, t.begin(), t.end(), pred);
}
References erase_if_impl().
Referenced by dynadjust::dynamlinterop::dna_import::ExcludeAllOutsideBoundingBox(), dynadjust::dynamlinterop::dna_import::ExcludeMeasurementTypes(), dynadjust::dynamlinterop::dna_import::ExtractAssociatedMsrsBoundingBox(), dynadjust::dynamlinterop::dna_import::ExtractStnsAndAssociatedMsrs(), dynadjust::dynamlinterop::dna_import::FindSimilarGXMeasurements(), dynadjust::dynamlinterop::dna_import::IgnoreInsufficientMeasurements(), dynadjust::dynamlinterop::dna_import::IncludeMeasurementTypes(), dynadjust::dynamlinterop::dna_import::RemoveIgnoredMeasurements(), dynadjust::networksegment::dna_segment::RemoveInvalidFreeStations(), dynadjust::networkadjust::dna_adjust::RemoveInvalidISLStations(), dynadjust::dynamlinterop::dna_import::RemoveNonMeasurements(), dynadjust::networkadjust::dna_adjust::RemoveNonMeasurements(), dynadjust::dynamlinterop::dna_import::SplitClusterMsrs(), and dynadjust::dynamlinterop::dna_import::SplitClusterMsrsConnectedToStns().
erase_if() [2/2]
template<typename T, typename Predicate> void erase_if (T * t, Predicate pred)
Definition at line 131 of file dnatemplatefuncs.hpp.
{
    erase_if_impl(t, t->begin(), t->end(), pred);
}
References erase_if_impl().
strip_duplicates() [1/2]
template<typename T> void strip_duplicates (T & t)
Definition at line 137 of file dnatemplatefuncs.hpp.
{
    std::sort(t.begin(), t.end());
    typename T::iterator it_newend(std::unique(t.begin(), t.end()));
    if (it_newend != t.end())
        t.resize(it_newend - t.begin());
}
Referenced by dynadjust::dynamlinterop::dna_import::BuildExtractStationsList(), dynadjust::dynamlinterop::dna_import::CompleteASLDirections(), dynadjust::dynamlinterop::dna_import::CompleteASLGpsBaselines(), dynadjust::dynamlinterop::dna_import::ExcludeAllOutsideBoundingBox(), dynadjust::dynamlinterop::dna_import::ExtractStnsAndAssociatedMsrs(), dynadjust::networksegment::dna_segment::FinaliseBlock(), GetGXMsrStations(), GetMsrIndices(), GetMsrStations(), dynadjust::networksegment::dna_segment::IdentifyInnerMsrsandAssociatedStns(), dynadjust::networksegment::dna_segment::IdentifyLowestStationAssociation(), dynadjust::networkadjust::dna_adjust::LoadSegmentationMetrics(), dynadjust::dynamlinterop::dna_import::MapMeasurementStationsBsl(), dynadjust::dynamlinterop::dna_import::MapMeasurementStationsDir(), dynadjust::networksegment::dna_segment::ParseStartingStations(), dynadjust::networkadjust::dna_adjust::RemoveDuplicateStations(), dynadjust::networksegment::dna_segment::RemoveDuplicateStations(), dynadjust::iostreams::dna_io_snx::serialise_meta(), strip_duplicates(), and dynadjust::networksegment::dna_segment::VerifyStationConnections_Block().
strip_duplicates() [2/2]
template<typename T> void strip_duplicates (T * t)
Definition at line 146 of file dnatemplatefuncs.hpp.
{
    strip_duplicates(*t);
}
References strip_duplicates().
outputObject()
template<class T> void outputObject (T t, std::ostream & os)
Definition at line 153 of file dnatemplatefuncs.hpp.
{ os << t; }
Referenced by main().
FormatDateString()
template<class S = std::string> S FormatDateString (const S & datestring)
Definition at line 193 of file dnatemplatefuncs.hpp.
{
    std::vector<S> tokenList;
    S delimiter(".");
    SplitDelimitedString<S>(datestring, delimiter, &tokenList);
    if (tokenList.size() < 3)
        return "";
    if (tokenList.at(0).size() < 2)
        tokenList.at(0).insert(0, "0");
    if (tokenList.at(1).size() < 2)
        tokenList.at(1).insert(0, "0");
    std::stringstream datess;
    datess << tokenList.at(0) << "." << tokenList.at(1) << "." << tokenList.at(2);
    return datess.str();
}
References SplitDelimitedString().
Referenced by ParseCommandLineOptions(), and ParseCommandLineOptions().
ParseDmsString()
template<class T> T ParseDmsString (const std::string & dmsString, const std::string & delimiter)
Definition at line 218 of file dnatemplatefuncs.hpp.
{
    std::vector<std::string> tokenList;
    SplitDelimitedString<std::string>(dmsString, delimiter, &tokenList);
    // "-38 43 28.24255"
    // "-38"       -> 38.000000000
    T dms = DoubleFromString<T>(tokenList.at(0));
    if (tokenList.size() < 2)
        return dms;
    // "43"        ->  0.430000000
    //             -> 38.430000000
    T min = DoubleFromString<T>(tokenList.at(1));
    min /= 100.;
    if (dms < 0.0)
        dms -= min;
    else
        dms += min;
    if (tokenList.size() < 3)
        return dms;
    // "28.24255"  ->  0.002824255
    //             -> 38.432824255
    T sec = DoubleFromString<T>(tokenList.at(2));
    sec /= 10000.;
    if (dms < 0.0)
        dms -= sec;
    else
        dms += sec;
    return dms;
}
References DoubleFromString(), and SplitDelimitedString().
Referenced by dynadjust::networkplot::dna_plot::LoadCorrectionsFile().
FormatDmsString()
template<class T> std::string FormatDmsString (const T & dDegMinSec, const int precision, bool withSpaces, bool withSymbols)
Definition at line 257 of file dnatemplatefuncs.hpp.
{
    std::stringstream ss;
    ss << std::fixed << std::setprecision(precision) << dDegMinSec;
    // No symbols or spaces? return std::string
    if (!withSpaces && !withSymbols)
        return ss.str();
    std::string strNumber(ss.str()), strBuf(ss.str());
    size_t decimal(0);
    int precision_fmt(precision);
    int minute_symbol_loc(withSymbols ? 4 : 3), second_symbol_loc(withSymbols ? 8 : 6);
    // Add symbols for degrees minutes and seconds
    if ((decimal = strNumber.find('.')) != std::string::npos)
    {
        // found a decimal point!
        if (decimal == 0)                   // decimal point at start, ie >>   .0123
        {
            strBuf.insert(decimal, "0");
            decimal++;
        }
        // add spaces
        if (withSpaces)
            strBuf.replace(decimal, 1, " ");
        // add symbols
        if (withSymbols)
            strBuf.insert(decimal, "\260");     // 272 is the degree symbol
        // add zero after "tens" minute or "tens" second value
        if (precision == 1 || precision == 3)
        {
            strBuf += "0";
            precision_fmt++;
        }
        if (precision > 2)
        {
            // add spaces
            if (withSpaces)
                strBuf.insert((decimal + minute_symbol_loc), " ");
            // add symbols
            if (withSymbols)
                strBuf.insert((decimal + minute_symbol_loc), "\222");       //minutes symbol
        }
        if (precision == 2 && withSymbols)
            strBuf += "\222";
        if (precision > 4)
        {
            strBuf.insert((decimal + second_symbol_loc), ".");
            if (withSymbols)
                strBuf += "\224";
        }
        if (precision == 4 && withSymbols)
            strBuf += "\224";
    }
    else if (withSymbols)
        strBuf += "\260";       // couldn't find a decimal point, so append the degree symbol
    //if (strNumber[0] == '-' || strNumber[0] == 's' || strNumber[0] == 'S' ||
    //  strNumber[0] == 'w' || strNumber[0] == 'W')
    //{
    //  if (iFlag == 1 || iFlag == 3)   // input/output latitude
    //      strBuf.replace(0, 1, "S");
    //  else                            // input/output longitude
    //      strBuf.replace(0, 1, "W");
    //}
    //else
    //{
    //  if (iFlag == 1 || iFlag == 3)
    //      strBuf = "N" + strBuf;
    //  else
    //      strBuf = "E" + strBuf;
    //}
    //
    //strBuf = strBuf.Mid(0, 1) + " " + strBuf.Mid(1);
    return strBuf;
}
Referenced by dynadjust::networkadjust::dna_adjust::PrintCorStation(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintMsrVarianceMatrixException(), ProcessGMTPlot(), reportGridProperties(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ReturnBadStationRecords(), and dynadjust::iostreams::dna_io_snx::serialise_site_id().
FormatDnaDmsString()
template<class T> std::string FormatDnaDmsString (const T & dDegMinSec, int precision)
Definition at line 350 of file dnatemplatefuncs.hpp.
{
    std::stringstream ss;
    if (precision < 4)
        precision = 4;
    ss << std::fixed << std::setprecision(precision) << dDegMinSec;
    std::string strBuf(ss.str());
    size_t decimal(0);
    std::string d, m, s;
    // Format degrees minutes and seconds
    if ((decimal = strBuf.find('.')) != std::string::npos)
    {
        // found a decimal point!
        if (decimal == 0)                   // decimal point at start, ie >>   .0123
        {
            strBuf.insert(decimal, "0");
            decimal++;
        }
        // degrees
        d = strBuf.substr(0, decimal);
        // minutes
        m = strBuf.substr(decimal+1, 2);
        // seconds
        s = strBuf.substr(decimal+3);
        if (s.length() > 2)
            s.insert(2, ".");
        // cater for rounding
        if (s.substr(0, 2) == "60")
        {
            s.replace(0, 2, "00");
            int mm = atoi(m.c_str()) + 1;
            ss.str("");
            ss << mm;
            m = ss.str();
            if (mm < 10)
                m.insert(0, "0");
        }
        if (m.substr(0, 2) == "60")
        {
            m.replace(0, 2, "00");
            int dd = atoi(d.c_str()) + 1;
            ss.str("");
            ss << dd;
            d = ss.str();
        }
        ss.str("");
        ss << std::setw(3) << d << std::setw(3) << std::right << m << " " << std::setw(6) << s;
        strBuf = ss.str();
    }
    return strBuf;
}
Referenced by dynadjust::measurements::CDnaAngle::WriteDNAMsr(), dynadjust::measurements::CDnaDirection::WriteDNAMsr(), and dynadjust::measurements::CDnaDirectionSet::WriteDNAMsr().
isCompoundMeas()
template<typename m> bool isCompoundMeas (const m & msrType)
Definition at line 708 of file dnatemplatefuncs.hpp.
{
    switch (msrType)
    {
    case 'G':
    case 'X':
    case 'Y':
        return true;
    }
    return false;
}
notCompoundMeas()
template<typename m> bool notCompoundMeas (const m & msrType)
Definition at line 721 of file dnatemplatefuncs.hpp.
{
    switch (msrType)
    {
    case 'G':
    case 'X':
    case 'Y':
        return false;
    }
    return true;
}
isCompoundMeasAll()
template<typename m> bool isCompoundMeasAll (const m & msrType)
Definition at line 735 of file dnatemplatefuncs.hpp.
{
    switch (msrType)
    {
    case 'D':
    case 'G':
    case 'X':
    case 'Y':
        return true;
    }
    return false;
}
Referenced by CompareMeasAdjSD_PairFirst< M, U >::operator()(), CompareMeasNstat_PairFirst< M, U >::operator()(), CompareMeasResidual_PairFirst< M, U >::operator()(), and CompareMeasValue_PairFirst< M, U >::operator()().
notCompoundMeasAll()
template<typename m> bool notCompoundMeasAll (const m & msrType)
Definition at line 749 of file dnatemplatefuncs.hpp.
{
    switch (msrType)
    {
    case 'D':
    case 'G':
    case 'X':
    case 'Y':
        return false;
    }
    return true;
}
Referenced by CompareMeasAdjSD_PairFirst< M, U >::operator()(), CompareMeasNstat_PairFirst< M, U >::operator()(), CompareMeasResidual_PairFirst< M, U >::operator()(), and CompareMeasValue_PairFirst< M, U >::operator()().
binary_search_index_noval()
template<typename Iter, typename C> Iter binary_search_index_noval (Iter begin, Iter end, C compare)
Definition at line 1900 of file dnatemplatefuncs.hpp.
{
    Iter i = lower_bound(begin, end, compare);
    if (i != end)
        return i;
    else
        return end;
}
binary_search_index()
template<typename Iter, typename T, typename C> Iter binary_search_index (Iter begin, Iter end, T value, C compare)
Definition at line 1911 of file dnatemplatefuncs.hpp.
{
    Iter i = lower_bound(begin, end, value, compare);
    if (i != end)
        return i;
    else
        return end;
}
binary_search_index_pair()
template<typename Iter, typename T> Iter binary_search_index_pair (Iter begin, Iter end, T value)
Definition at line 1922 of file dnatemplatefuncs.hpp.
{
    Iter i = lower_bound(begin, end, value, ComparePairFirst<T>());
    if (i != end && i->first == value)
        return i;
    else
        return end;
}
Referenced by dynadjust::dynamlinterop::dna_import::AddDiscontinuityStations().