DynAdjust: include/functions/dnatemplatecalcfuncs.hpp File Reference
dnatemplatecalcfuncs.hpp File Reference
#include <include/config/dnatypes.hpp>
#include <include/config/dnaconsts.hpp>
Functions
template<class U>
U sumOfConsecutiveIntegers (const U &max, const U &min=1)
template<typename T, typename U>
T removeNegativeZero (const T &t, const U &precision)
template<typename T>
bool are_floats_equal (const T &lhs, const T &rhs, const T epsilon=PRECISION_1E6)
template<typename T, typename U, typename iterator>
T average (const iterator begin, const iterator end, U &sum)
template<class T, class U>
T average (const U &a, const U &b)
template<class T>
T average (const T &a, const T &b)
template<class T, typename U>
T minVal (const T &lhs, const U &rhs)
template<class T, typename U>
T maxVal (const T &lhs, const U &rhs)
template<class T>
T Rad180Mod (const T &dValue)
template<class T>
T degrees_to_radians_ (T &degrees)
template<class T>
T Radians (T &degrees)
template<class T>
T Radians (const T &degrees)
template<class T>
void Radians (T *degrees)
template<class T>
T radians_to_degrees_ (T &radians)
template<class T>
T Degrees (T &radians)
template<class T>
T Degrees (const T &radians)
template<class T>
void Degrees (T *radians)
template<class T>
T DegreesL (const T &radians)
template<class T>
void DegreesL (T *dValue)
template<class T>
T Seconds (const T &radians)
template<class T>
T Seconds (T *radians)
template<class T>
T SecondstoRadians (const T &seconds)
template<class T, typename U>
void DegtoDms (const T &dDegrees, U *dDegMinSec)
template<class T>
T DegtoDms (const T &dDegrees)
template<class T, typename U>
void DmstoDeg (const T &dDegMinSec, U *dDegrees)
template<class T>
T DmstoDeg (const T &dDegMinSec)
template<class T, typename U>
void DmstoRad (const T &dDegMinSec, U *dRadians)
template<class T>
T DmstoRad (const T &dDegMinSec)
template<class T>
T RadtoDms (const T &dRadians)
template<class T>
T RadtoDmsL (const T &dRadians)
template<class T, typename U>
void DmintoDeg (const T &dDegMin, U *dDegrees)
template<class T>
T DmintoDeg (const T &dDegMin)
template<class T, typename U>
void DegtoDmin (const T &dDegrees, U *dDegMin)
template<class T>
T DegtoDmin (const T &dDegrees)
template<class T>
T atan_2 (const T &x, const T &y)
Function Documentation
sumOfConsecutiveIntegers()
template<class U> U sumOfConsecutiveIntegers (const U & max, const U & min = 1)
Definition at line 45 of file dnatemplatecalcfuncs.hpp.
{
    //U q(static_cast<U>(average<double, U>(max, min) * max));
    U sum(0);
    for (U u=min; u<=max; u++)
        sum += u;
    return sum;
}
Referenced by dynadjust::math::matrix_2d::get_size(), and dynadjust::math::matrix_2d::matrix_2d().
removeNegativeZero()
template<typename T, typename U> T removeNegativeZero (const T & t, const U & precision)
Definition at line 55 of file dnatemplatecalcfuncs.hpp.
{
    if (t < 0.0 || t == T(-0.0))
    {
        T v(floor((t * pow(10.0, precision)) + 0.5));
        if (fabs(v) > 0.)
            // t is non-zero at precision
            return t;
        // t is a negative zero
        return 0.;
    }
    return t;
}
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjMeasurementStatistics(), dynadjust::networkadjust::dna_adjust::PrintMeasurementCorrection(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), and dynadjust::networkadjust::dna_adjust::PrintMeasurementsLinear().
are_floats_equal()
template<typename T> bool are_floats_equal (const T & lhs, const T & rhs, const T epsilon = PRECISION_1E6)
Definition at line 70 of file dnatemplatecalcfuncs.hpp.
{
    return (fabs(lhs - rhs) < epsilon);
}
References PRECISION_1E6().
Referenced by ProcessGMTPlot().
average() [1/3]
template<typename T, typename U, typename iterator> T average (const iterator begin, const iterator end, U & sum)
Definition at line 76 of file dnatemplatecalcfuncs.hpp.
{
    U n(static_cast<UINT32>(std::distance(begin, end)));
    sum = std::accumulate(begin, end, 0);
    return static_cast<T>(sum) / n;
}
Referenced by dynadjust::networksegment::dna_segment::CalculateAverageBlockSize(), EllipsoidChordtoMSLChord(), MSLArctoMSLChord(), MSLChordtoEllipsoidChord(), MSLChordtoMSLArc(), dynadjust::networkadjust::dna_adjust::PrintAdjGNSSAlternateUnits(), RadiusCurvatureInChordDirection(), and year_doy_Average().
average() [2/3]
template<class T, class U> T average (const U & a, const U & b)
Definition at line 84 of file dnatemplatecalcfuncs.hpp.
{
    T t(a + b);
    return t / 2.;
}
average() [3/3]
template<class T> T average (const T & a, const T & b)
Definition at line 91 of file dnatemplatecalcfuncs.hpp.
{
    T t(a + b);
    return (t / (T)(2.));
}
minVal()
template<class T, typename U> T minVal (const T & lhs, const U & rhs)
Definition at line 98 of file dnatemplatecalcfuncs.hpp.
{
    if (lhs < rhs)
        return lhs;
    else
        return rhs;
}
Referenced by dynadjust::networkadjust::dna_adjust::LoadVarianceScaling(), and dynadjust::networksegment::dna_segment::SortbyMeasurementCount().
maxVal()
template<class T, typename U> T maxVal (const T & lhs, const U & rhs)
Definition at line 107 of file dnatemplatecalcfuncs.hpp.
{
    if (lhs > rhs)
        return lhs;
    else
        return rhs;
}
Rad180Mod()
template<class T> T Rad180Mod (const T & dValue)
Definition at line 118 of file dnatemplatecalcfuncs.hpp.
{
    if (dValue < -PI)
         return dValue + (PI + PI);
    else if (dValue > PI)
         return dValue - (PI + PI);
    return dValue;
}
References PI().
Referenced by DegreesL(), and DegreesL().
degrees_to_radians_()
template<class T> T degrees_to_radians_ (T & degrees)
Definition at line 128 of file dnatemplatecalcfuncs.hpp.
{
    return (degrees * DEG_TO_RAD);
}
References DEG_TO_RAD().
Referenced by Radians(), Radians(), and Radians().
Radians() [1/3]
template<class T> T Radians (T & degrees)
Definition at line 134 of file dnatemplatecalcfuncs.hpp.
{
    return degrees_to_radians_(degrees);
}
References degrees_to_radians_().
Referenced by dynadjust::networkplot::dna_plot::CalculateLimitsFromPoint(), dynadjust::referenceframe::dna_reftran::CalculateRotations(), dynadjust::networkplot::dna_plot::ComputeStationCorrection(), DmstoRad(), dynadjust::networkplot::dna_plot::FinaliseGMTParameters(), GeoToGrid(), CInputCoords::OnUpdateInterpolationResults(), RadFromDmsString(), dynadjust::measurements::CDnaGpsPoint::SetX(), dynadjust::measurements::CDnaStation::SetXAxis(), dynadjust::measurements::CDnaGpsPoint::SetY(), and dynadjust::measurements::CDnaStation::SetYAxis().
Radians() [2/3]
template<class T> T Radians (const T & degrees)
Definition at line 140 of file dnatemplatecalcfuncs.hpp.
{
    return degrees_to_radians_(degrees);
}
References degrees_to_radians_().
Radians() [3/3]
template<class T> void Radians (T * degrees)
Definition at line 146 of file dnatemplatecalcfuncs.hpp.
{
    *degrees = degrees_to_radians_(*degrees);
}
References degrees_to_radians_().
radians_to_degrees_()
template<class T> T radians_to_degrees_ (T & radians)
Definition at line 152 of file dnatemplatecalcfuncs.hpp.
{
    return (radians * RAD_TO_DEG);
}
References RAD_TO_DEG().
Referenced by Degrees(), Degrees(), Degrees(), and dynadjust::referenceframe::dna_reftran::IdentifyStationPlate().
Degrees() [1/3]
template<class T> T Degrees (T & radians)
Definition at line 158 of file dnatemplatecalcfuncs.hpp.
{
    return radians_to_degrees_(radians);
}
References radians_to_degrees_().
Referenced by dynadjust::networkplot::dna_plot::CalculateLimitsFromPoint(), dynadjust::networkplot::dna_plot::FinaliseGMTParameters(), GeoToGrid(), dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), RadtoDms(), and dynadjust::networkplot::dna_plot::ReduceStationCoordinates().
Degrees() [2/3]
template<class T> T Degrees (const T & radians)
Definition at line 164 of file dnatemplatecalcfuncs.hpp.
{
    return radians_to_degrees_(radians);
}
References radians_to_degrees_().
Degrees() [3/3]
template<class T> void Degrees (T * radians)
Definition at line 170 of file dnatemplatecalcfuncs.hpp.
{
    *radians = radians_to_degrees_(*radians);
}
References radians_to_degrees_().
DegreesL() [1/2]
template<class T> T DegreesL (const T & radians)
Definition at line 178 of file dnatemplatecalcfuncs.hpp.
{
    return (Rad180Mod(radians) * RAD_TO_DEG);
}
References Rad180Mod(), and RAD_TO_DEG().
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), and RadtoDmsL().
DegreesL() [2/2]
template<class T> void DegreesL (T * dValue)
Definition at line 186 of file dnatemplatecalcfuncs.hpp.
{
    *dValue = (Rad180Mod(*dValue) * RAD_TO_DEG);
}
References Rad180Mod(), and RAD_TO_DEG().
Seconds() [1/2]
template<class T> T Seconds (const T & radians)
Definition at line 193 of file dnatemplatecalcfuncs.hpp.
{
    return radians * RAD_TO_SEC;
}
References RAD_TO_SEC().
Referenced by dynadjust::networkadjust::dna_adjust::LoadVarianceMatrix_D(), dynadjust::networkadjust::dna_adjust::PrintMeasurementCorrection(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::geoidinterpolation::dna_geoid_interpolation::WriteDNA1GeoidFile(), dynadjust::measurements::CDnaAngle::WriteDNAMsr(), dynadjust::measurements::CDnaCoordinate::WriteDNAMsr(), dynadjust::measurements::CDnaDirection::WriteDNAMsr(), dynadjust::measurements::CDnaDirectionSet::WriteDNAMsr(), dynadjust::measurements::CDnaAngle::WriteDynaMLMsr(), dynadjust::measurements::CDnaCoordinate::WriteDynaMLMsr(), dynadjust::measurements::CDnaDirection::WriteDynaMLMsr(), and dynadjust::measurements::CDnaDirectionSet::WriteDynaMLMsr().
Seconds() [2/2]
template<class T> T Seconds (T * radians)
Definition at line 199 of file dnatemplatecalcfuncs.hpp.
{
    return *radians * RAD_TO_SEC;
}
References RAD_TO_SEC().
SecondstoRadians()
template<class T> T SecondstoRadians (const T & seconds)
Definition at line 205 of file dnatemplatecalcfuncs.hpp.
{
    return seconds / static_cast<T>(RAD_TO_SEC);
}
References RAD_TO_SEC().
Referenced by dynadjust::dynamlinterop::dna_import::LoadDNAGeoidFile(), dynadjust::geoidinterpolation::dna_geoid_interpolation::PopulateStationRecords(), RadFromSecondsString(), ReduceParameters(), dynadjust::measurements::CDnaAngle::SimulateMsr(), dynadjust::measurements::CDnaCoordinate::SimulateMsr(), dynadjust::measurements::CDnaDirection::SimulateMsr(), and dynadjust::measurements::CDnaDirectionSet::SimulateMsr().
DegtoDms() [1/2]
template<class T, typename U> void DegtoDms (const T & dDegrees, U * dDegMinSec)
Definition at line 211 of file dnatemplatecalcfuncs.hpp.
{
    T d, m, s;
    *dDegMinSec = fabs(dDegrees);        // retain original value
    d = floor(*dDegMinSec);
    m = floor((((*dDegMinSec) - d) * 60.0));
    s = ((*dDegMinSec) - d - (m/60.0)) * 3600.0;
    if (fabs(s - 60.0) < 0.000000001)
    {
        s = 0.0;
        m += 1.0;
    }
    *dDegMinSec = d + (m/100.0) + (s/10000.0);
    if (dDegrees < 0.0)
        *dDegMinSec *= -1;
}
Referenced by DegtoDms(), CInputCoords::OnUpdateInterpolationResults(), dynadjust::networkplot::dna_plot::PrintErrorEllipses(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessDatFile(), ProcessGMTPlot(), RadtoDms(), RadtoDmsL(), and reportGridProperties().
DegtoDms() [2/2]
template<class T> T DegtoDms (const T & dDegrees)
Definition at line 232 of file dnatemplatecalcfuncs.hpp.
{
    T dDegMinSec;
    DegtoDms(dDegrees, &dDegMinSec);
    return dDegMinSec;
}
References DegtoDms().
DmstoDeg() [1/2]
template<class T, typename U> void DmstoDeg (const T & dDegMinSec, U * dDegrees)
Definition at line 241 of file dnatemplatecalcfuncs.hpp.
{
    T dh, dm, ds;
    dh = fabs(dDegMinSec);       // retain original value
    *dDegrees = floor(dh);
    dm = floor(((dh - (*dDegrees)) * 100.0) + 0.0001);
    ds = (((dh - (*dDegrees)) * 100.0) - dm) * 100.0;
    *dDegrees += ((dm / 60.0) + (ds / 3600.0));
    if (dDegMinSec < 0.0)
        (*dDegrees) *= -1;
}
Referenced by dynadjust::networkplot::dna_plot::DetermineBoundingBox(), DmstoDeg(), FromDmsString(), FromDmsString(), dynadjust::networkplot::dna_plot::LoadPosUncertaintyFile(), main(), CdnageoidintDlg::OnInterpolateInputCoords(), CInputCoords::OnUpdateInterpolationResults(), dynadjust::networkplot::dna_plot::PrintErrorEllipses(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ProcessCsvFile(), and RadFromDmsString().
DmstoDeg() [2/2]
template<class T> T DmstoDeg (const T & dDegMinSec)
Definition at line 256 of file dnatemplatecalcfuncs.hpp.
{
    T dDegrees;
    DmstoDeg(dDegMinSec, &dDegrees);
    return dDegrees;
}
References DmstoDeg().
DmstoRad() [1/2]
template<class T, typename U> void DmstoRad (const T & dDegMinSec, U * dRadians)
Definition at line 264 of file dnatemplatecalcfuncs.hpp.
{
    T dh, dm, ds;
    dh = fabs(dDegMinSec);       // retain original value
    *dRadians = floor(dh);
    dm = floor(((dh - (*dRadians)) * 100.0) + 0.0001);
    ds = (((dh - (*dRadians)) * 100.0) - dm) * 100.0;
    *dRadians += ((dm / 60.0) + (ds / 3600.0));
    if (dDegMinSec < 0.0)
        (*dRadians) *= -1;
    Radians(dRadians);
}
References Radians().
Referenced by dynadjust::dynamlinterop::dna_import::DetermineBoundingBox(), and DmstoRad().
DmstoRad() [2/2]
template<class T> T DmstoRad (const T & dDegMinSec)
Definition at line 280 of file dnatemplatecalcfuncs.hpp.
{
    T dRadians;
    DmstoRad(dDegMinSec, &dRadians);
    return dRadians;
}
References DmstoRad().
RadtoDms()
template<class T> T RadtoDms (const T & dRadians)
Definition at line 288 of file dnatemplatecalcfuncs.hpp.
{
    T dDms;
    DegtoDms(Degrees(dRadians), &dDms);
    return dDms;
}
References Degrees(), and DegtoDms().
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintCorStation(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsAngular(), dynadjust::networkadjust::dna_adjust::PrintMsrVarianceMatrixException(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ReturnBadStationRecords(), dynadjust::iostreams::dna_io_snx::serialise_site_id(), dynadjust::networkadjust::dna_adjust::UpdateDesignNormalMeasMatrices_D(), dynadjust::measurements::CDnaAngle::WriteDNAMsr(), dynadjust::measurements::CDnaCoordinate::WriteDNAMsr(), dynadjust::measurements::CDnaDirection::WriteDNAMsr(), dynadjust::measurements::CDnaDirectionSet::WriteDNAMsr(), dynadjust::measurements::CDnaGpsPoint::WriteDNAMsr(), dynadjust::measurements::CDnaStation::WriteDNAXMLStn(), dynadjust::measurements::CDnaAngle::WriteDynaMLMsr(), dynadjust::measurements::CDnaCoordinate::WriteDynaMLMsr(), dynadjust::measurements::CDnaDirection::WriteDynaMLMsr(), dynadjust::measurements::CDnaDirectionSet::WriteDynaMLMsr(), and dynadjust::measurements::CDnaGpsPoint::WriteDynaMLMsr().
RadtoDmsL()
template<class T> T RadtoDmsL (const T & dRadians)
Definition at line 296 of file dnatemplatecalcfuncs.hpp.
{
    T dDms;
    DegtoDms(DegreesL(dRadians), &dDms);
    return dDms;
}
References DegreesL(), and DegtoDms().
Referenced by dynadjust::networkadjust::dna_adjust::PrintAdjStation(), dynadjust::networkadjust::dna_adjust::PrintPosUncertainty(), dynadjust::measurements::CDnaGpsPoint::WriteDNAMsr(), dynadjust::measurements::CDnaStation::WriteDNAXMLStn(), dynadjust::measurements::CDnaCoordinate::WriteDynaMLMsr(), and dynadjust::measurements::CDnaGpsPoint::WriteDynaMLMsr().
DmintoDeg() [1/2]
template<class T, typename U> void DmintoDeg (const T & dDegMin, U * dDegrees)
Definition at line 304 of file dnatemplatecalcfuncs.hpp.
{
    T dh;
    dh = fabs(dDegMin); // retain original value
    *dDegrees = floor(dh);
    *dDegrees += (dh - *dDegrees) * 100.0 / 60.0;
    if (dDegMin < 0.0)
        *dDegrees *= -1;
}
Referenced by DmintoDeg().
DmintoDeg() [2/2]
template<class T> T DmintoDeg (const T & dDegMin)
Definition at line 317 of file dnatemplatecalcfuncs.hpp.
{
    T dDegrees;
    DmintoDeg(dDegMin, &dDegrees);
    return dDegrees;
}
References DmintoDeg().
DegtoDmin() [1/2]
template<class T, typename U> void DegtoDmin (const T & dDegrees, U * dDegMin)
Definition at line 325 of file dnatemplatecalcfuncs.hpp.
{
    T d;
    *dDegMin = fabs(dDegrees);  // retain original value
    d = floor(*dDegMin);
    *dDegMin = d + ((*dDegMin - d) * 0.6);
    if (dDegrees < 0.0)
        *dDegMin *= -1;
}
DegtoDmin() [2/2]
template<class T> T DegtoDmin (const T & dDegrees)
Definition at line 339 of file dnatemplatecalcfuncs.hpp.
{
    T dDegMin;
    DegtoDin(dDegrees, &dDegMin);
    return dDegMin;
}
atan_2()
template<class T> T atan_2 (const T & x, const T & y)
Definition at line 355 of file dnatemplatecalcfuncs.hpp.
{
    T theta(atan(x / y));           // first quadrant (default)
    if (y < 0)                      // second or third quadrant
        return theta + PI;
    else
    {
        if (x > 0)                  // first quadrant
            return theta;
        else                        // fourth quadrant
            return theta + TWO_PI;
    }
  return 0.;
}
References PI(), and TWO_PI().
Referenced by Direction(), and ErrorEllipseParameters().