DynAdjust: include/config/dnaversion-stream.hpp File Reference
dnaversion-stream.hpp File Reference
#include <include/config/dnaversion.hpp>
#include <include/config/dnaconsts-iostream.hpp>
Functions
template<class T>
void output_theappname (T &stream)
template<class T>
void output_binaryname (T &stream)
template<class T>
void output_binarydescription (T &stream)
template<class T>
void output_globalname (T &stream)
template<class T>
void output_createdby (T &stream)
template<class T>
void output_version (T &stream, bool PAD=false)
template<class T>
void output_build (T &stream, bool PAD=false)
Function Documentation
output_theappname()
template<class T> void output_theappname (T & stream)
Definition at line 42 of file dnaversion-stream.hpp.
{
    stream << __the_app_name__ << " " << __COPYRIGHT_YEAR__;
}
References __COPYRIGHT_YEAR__, and __the_app_name__.
Referenced by fileproc_help_header().
output_binaryname()
template<class T> void output_binaryname (T & stream)
Definition at line 49 of file dnaversion-stream.hpp.
{
    stream << "Title:        " << __BINARY_NAME__;
}
Referenced by fileproc_help_header().
output_binarydescription()
template<class T> void output_binarydescription (T & stream)
Definition at line 56 of file dnaversion-stream.hpp.
{
    stream << "Description:  " << __BINARY_DESC__;
}
Referenced by fileproc_help_header().
output_globalname()
template<class T> void output_globalname (T & stream)
Definition at line 63 of file dnaversion-stream.hpp.
{
    stream << __GLOBAL_BINARY_NAME__ << ", " << __GLOBAL_BINARY_DESC__;
}
References __GLOBAL_BINARY_DESC__, and __GLOBAL_BINARY_NAME__.
Referenced by snx_softwarehardware_text().
output_createdby()
template<class T> void output_createdby (T & stream)
Definition at line 70 of file dnaversion-stream.hpp.
{
    stream << "Created by:   " << __BINARY_NAME__ << ", " << __BINARY_DESC__;
}
Referenced by dna_header(), dnaproj_header(), and dynaml_header().
output_version()
template<class T> void output_version (T & stream, bool PAD = false)
Definition at line 77 of file dnaversion-stream.hpp.
{
    if (PAD)
        stream << std::setw(PRINT_VAR_PAD) << std::left << "Version: ";
    else
        stream << "Version:      ";
    stream << __BINARY_VERSION__ << ", " << __BINARY_BUILDTYPE__ << " with " << __LINEAR_ALGEBRA_LIB__;
}
References __BINARY_VERSION__, __LINEAR_ALGEBRA_LIB__, PAD(), and PRINT_VAR_PAD().
Referenced by dna_header(), dnaproj_header(), dynaml_header(), fileproc_help_header(), print_file_header(), and snx_softwarehardware_text().
output_build()
template<class T> void output_build (T & stream, bool PAD = false)
Definition at line 88 of file dnaversion-stream.hpp.
{
    if (PAD)
        stream << std::setw(PRINT_VAR_PAD) << std::left << "Build: ";
    else
        stream << "Build:        ";
    stream <<
        // __DATE__ The compilation date of the current source file.
        // The date is a constant length string literal of the form
        // Mmm dd yyyy. The month name Mmm is the same as the abbreviated
        // month name generated by the C Runtime Library(CRT) asctime
        // function.The first character of date dd is a space if the
        // value is less than 10. This macro is always defined.
        __DATE__ << ", " <<
        // __TIME__ The time of translation of the preprocessed
        // translation unit. The time is a character string literal of
        // the form hh:mm:ss, the same as the time returned by the CRT
        // asctime function. This macro is always defined.
        __TIME__;
    if (strlen(__COMPILER__) > 2)
        stream <<  " - " << __COMPILER__ << " " << __COMPILER_VERSION__ << "";
}
References __COMPILER__, PAD(), and PRINT_VAR_PAD().
Referenced by dna_header(), dnaproj_header(), dynaml_header(), fileproc_help_header(), print_file_header(), and snx_softwarehardware_text().