DynAdjust: dynadjust/driver/driver.cpp File Reference
driver.cpp File Reference
#include <dynadjust/dnageoid/dnageoid_ext.hpp>
Functions
bool CreateNTv2Grid (const char *datGridFile, const char *gsbGridFile)
bool createGridIndex (const char *gridfilePath, const char *gridfileType)
bool reportGridProperties (const char *gridfilePath, const char *gridfileType)
bool interpolateGridPoint (geoid_point *theGeoidPoint, const int &method)
bool FileTransformation (const char *fileIn, const char *fileOut, const int &intDmsFlag=0)
int main (int argc, char *argv[])
Function Documentation
CreateNTv2Grid()
bool CreateNTv2Grid (const char * datGridFile, const char * gsbGridFile)
Definition at line 45 of file driver.cpp.
{
    std::cout << "+ Creating NTv2 grid file... ";
    int status(0);
    n_file_par theGrid;
    strcpy(theGrid.filename, gsbGridFile);
    strcpy(theGrid.filetype, "gsb");
    if (!DNAGEOID_CreateNTv2Grid(datGridFile, &theGrid, &status))
    {
        std::cout << std::endl << "Error: " << status << std::endl;
        return false;
    }
    std::cout << "done." << std::endl << std::endl;
    return true;
}
References file_par::filename, and file_par::filetype.
createGridIndex()
bool createGridIndex (const char * gridfilePath, const char * gridfileType)
Definition at line 68 of file driver.cpp.
{
    std::cout << "+ Opening grid file... ";
    int status(0);
    if (!DNAGEOID_CreateGridIndex(gridfilePath, gridfileType, &status))
    {
        std::cout << "Error: " << status << std::endl;
        return false;
    }
    std::cout << "done." << std::endl << std::endl;
    return true;
}
Referenced by main().
reportGridProperties()
bool reportGridProperties (const char * gridfilePath, const char * gridfileType)
Definition at line 86 of file driver.cpp.
{
    std::cout << "+ Reporting grid file properties... ";
    n_file_par grid_properties;
    int status(0);
    if (!DNAGEOID_ReportGridProperties(gridfilePath, gridfileType, &grid_properties, &status))
    {
        std::cout << "Error: " << status << std::endl;
        return false;
    }
    std::cout << std::endl << std::endl <<
        "----------------------------------------------------------------" <<
        std::endl <<
        "Grid properties for \"" << gridfilePath << "\":" << std::endl;
    std::cout << "+ GS_TYPE  = " << grid_properties.chGs_type << std::endl;            // grid shift type (GS_TYPE)
    std::cout << "+ VERSION  = " << grid_properties.chVersion << std::endl;            // grid file version (VERSION)
    std::cout << "+ SYSTEM_F = " << grid_properties.chSystem_f << std::endl;          // reference system (SYSTEM_F)
    std::cout << "+ SYSTEM_T = " << grid_properties.chSystem_t << std::endl;          // reference system (SYSTEM_T)
    std::cout << "+ MAJOR_F  = " << std::setprecision(3) << std::fixed << grid_properties.daf << std::endl;                  // semi major of from system (MAJOR_F)
    std::cout << "+ MAJOR_T  = " << std::setprecision(3) << std::fixed << grid_properties.dat << std::endl;                  // semi major of to system (MAJOR_T)
    std::cout << "+ MINOR_F  = " << std::setprecision(3) << std::fixed << grid_properties.dbf << std::endl;                  // semi minor of from system (MINOR_F)
    std::cout << "+ MINOR_T  = " << std::setprecision(3) << std::fixed << grid_properties.dbt << std::endl;                  // semi minor of to system (MINOR_T)
    std::cout << "+ NUM_OREC = " << grid_properties.iH_info << std::endl;                // Number of header identifiers (NUM_OREC)
    std::cout << "+ NUM_SREC = " << grid_properties.iSubH_info << std::endl;              // Number of sub-header idents (NUM_SREC)
    std::cout << "+ NUM_FILE = " << grid_properties.iNumsubgrids << std::endl;          // number of subgrids in file (NUM_FILE)
    for (int i=0; i<grid_properties.iNumsubgrids; ++i)
    {
        std::cout << "  + SUBGRID " << i << ":" << std::endl;
        std::cout << "    SUB_NAME = " << grid_properties.ptrIndex[i].chSubname << std::endl;          // name of subgrid (SUB_NAME)
        std::cout << "    PARENT   = " << grid_properties.ptrIndex[i].chParent << std::endl;            // name of parent grid (PARENT)
        std::cout << "    CREATED  = " << grid_properties.ptrIndex[i].chCreated << std::endl;          // date of creation (CREATED)
        std::cout << "    UPDATED  = " << grid_properties.ptrIndex[i].chUpdated << std::endl;          // date of last file update (UPDATED)
        std::cout << "    S_LAT    = " << grid_properties.ptrIndex[i].dSlat << std::endl;              // lower latitude (S_LAT)
        std::cout << "    N_LAT    = " << grid_properties.ptrIndex[i].dNlat << std::endl;              // upper latitude (N_LAT)
        std::cout << "    E_LONG   = " << grid_properties.ptrIndex[i].dElong << std::endl;            // lower longitude (E_LONG)
        std::cout << "    W_LONG   = " << grid_properties.ptrIndex[i].dWlong << std::endl;            // upper longitude (W_LONG)
        std::cout << "    LAT_INC  = " << grid_properties.ptrIndex[i].dLatinc << std::endl;          // latitude interval (LAT_INC)
        std::cout << "    LONG_INC = " << grid_properties.ptrIndex[i].dLonginc << std::endl;            // longitude interval (LONG_INC)
        std::cout << "    GS_COUNT = " << grid_properties.ptrIndex[i].lGscount << std::endl;            // number of nodes (GS_COUNT)
    }
    std::cout << "----------------------------------------------------------------" <<
        std::endl << std::endl;
    return true;
}
References gridfileindex::chCreated, file_par::chGs_type, gridfileindex::chParent, gridfileindex::chSubname, file_par::chSystem_f, file_par::chSystem_t, gridfileindex::chUpdated, file_par::chVersion, file_par::daf, file_par::dat, file_par::dbf, file_par::dbt, gridfileindex::dElong, gridfileindex::dLatinc, gridfileindex::dLonginc, gridfileindex::dNlat, gridfileindex::dSlat, gridfileindex::dWlong, file_par::iH_info, file_par::iNumsubgrids, file_par::iSubH_info, gridfileindex::lGscount, and file_par::ptrIndex.
Referenced by main().
interpolateGridPoint()
bool interpolateGridPoint (geoid_point * theGeoidPoint, const int & method)
Definition at line 137 of file driver.cpp.
{
    int status(0);
    if (!DNAGEOID_InterpolatePoint(theGeoidPoint, method, &status))
    {
        if (status == -1)
        {
            std::cout << "+ The point " << std::fixed << std::setprecision(6) << theGeoidPoint->cVar.dLatitude << ", " << theGeoidPoint->cVar.dLongitude << " is outside the grid file." << std::endl << std::endl;
            return true;
        }
        std::cout << "Error: " << status << std::endl;
        return false;
    }
    std::cout << "+ Interpolation results for ";
    std::cout << std::fixed << std::setprecision(6) << theGeoidPoint->cVar.dLatitude << ", " << theGeoidPoint->cVar.dLongitude << " (ddd.dddddd):" << std::endl;
    std::cout << "  N VALUE      = " << std::setw(6) << std::right << std::setprecision(3) << theGeoidPoint->gVar.dN_value << std::endl;            // N value
    std::cout << "  DEFL PRIME M = " << std::setw(6) << std::right << theGeoidPoint->gVar.dDefl_meridian << std::endl;                        // Defl PM value
    std::cout << "  DEFL PRIME V = " << std::setw(6) << std::right << theGeoidPoint->gVar.dDefl_primev << std::endl;                        // Defl PV value
    std::cout << std::endl;
    return true;
}
References geoid_point::cVar, geoid_values::dDefl_meridian, geoid_values::dDefl_primev, interpolant::dLatitude, interpolant::dLongitude, geoid_values::dN_value, and geoid_point::gVar.
Referenced by main().
FileTransformation()
bool FileTransformation (const char * fileIn, const char * fileOut, const int & intDmsFlag = 0)
Definition at line 164 of file driver.cpp.
{
    std::cout << "+ Interpolating geoid information using a points file... ";
    int method(BICUBIC);
    int intEllipsoidtoOrtho(0);
    bool exportDnaGeoidFile(false);
    int status(0);
    if (!DNAGEOID_FileTransformation(fileIn, fileOut, method,
        intEllipsoidtoOrtho, intDmsFlag, exportDnaGeoidFile, &status))
    {
        std::cout << "Error: " << status << std::endl;
        return false;
    }
    std::cout << "done." << std::endl <<
        "+ File written to:" << std::endl <<
        "  " << fileOut << std::endl << std::endl;
    int pointsInterpolated(0), pointsNotInterpolated(0);
    if (!DNAGEOID_PointsInterpolated(&pointsInterpolated, &status))
    {
        std::cout << "Error: " << status << std::endl;
        return false;
    }
    if (!DNAGEOID_PointsNotInterpolated(&pointsNotInterpolated, &status))
    {
        std::cout << "Error: " << status << std::endl;
        return false;
    }
    std::cout << "+ Points interpolated:     " << pointsInterpolated << std::endl <<
        "+ Points not interpolated: " << pointsNotInterpolated << std::endl << std::endl;
    return true;
}
References BICUBIC.
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 206 of file driver.cpp.
{
    char datGridFile[256];
    strcpy(datGridFile, "C:\\Data\\vs10\\projects\\geoidDllTest\\sample_files\\AUSGeoid09_NSW_ACT_CLIP.dat");
    char gsbGridFile[256];
    sprintf(gsbGridFile, "%s%s", datGridFile, ".gsb");
    strcpy(gsbGridFile, "C:\\Data\\dist\\ausgeoid09.gsb");
    // Create a NTv2 grid file from a Winter DAT file
    //if (!CreateNTv2Grid(datGridFile, gsbGridFile))
    //  return EXIT_FAILURE;
    // Print a grid file's properties
    if (!reportGridProperties(gsbGridFile, "gsb"))
        return EXIT_FAILURE;
    // 1. Call createGridIndex() once
    if (!createGridIndex(gsbGridFile, "gsb"))
        return EXIT_FAILURE;
    geoid_point theGeoidPoint;
    // Decimal degrees
    theGeoidPoint.cVar.dLatitude = -37.678634;
    theGeoidPoint.cVar.dLongitude = 147.678634;
    theGeoidPoint.cVar.dHeight = 100.0;
    theGeoidPoint.cVar.iHeightSystem = 0;
    // 2. Call interpolateGridPoint() as many times as required
    std::cout << "+ Interpolating from grid file... " << std::endl;
    for (int i=0; i<4; ++i)
    {
        theGeoidPoint.cVar.dLatitude += 1.0 * i;
        theGeoidPoint.cVar.dLongitude += 2.0 * i;
        if (!interpolateGridPoint(&theGeoidPoint, BICUBIC))
            return EXIT_FAILURE;
    }
    // 3. As required, call FileTransformation
    char fileIn[256], fileOut[256];
    // 19 points (one bad) in decimal degrees
    strcpy(fileIn, "C:\\Data\\vs10\\projects\\geoidDllTest\\sample_files\\balltran.csv");
    strcpy(fileOut, "C:\\Data\\vs10\\projects\\geoidDllTest\\sample_files\\balltran_out.txt");
    FileTransformation(fileIn, fileOut, 1);
    // 10 points in decimal degrees
    strcpy(fileIn, "C:\\Data\\vs10\\projects\\geoidDllTest\\sample_files\\gda94_ddeg.csv");
    strcpy(fileOut, "C:\\Data\\vs10\\projects\\geoidDllTest\\sample_files\\gda94_ddeg_out.csv");
    FileTransformation(fileIn, fileOut, 1);
    // 10 points in degrees, minutes and seconds
    strcpy(fileIn, "C:\\Data\\vs10\\projects\\geoidDllTest\\sample_files\\gda94_dms.csv");
    strcpy(fileOut, "C:\\Data\\vs10\\projects\\geoidDllTest\\sample_files\\gda94_dms_out.csv");
    FileTransformation(fileIn, fileOut);
    return EXIT_SUCCESS;
}
References BICUBIC, createGridIndex(), geoid_point::cVar, interpolant::dHeight, interpolant::dLatitude, interpolant::dLongitude, FileTransformation(), interpolant::iHeightSystem, interpolateGridPoint(), and reportGridProperties().