DynAdjust: dynadjust::math Namespace Reference
dynadjust::math Namespace Reference
Classes
class matrix_2d
Typedefs
typedef std::vector< matrix_2d > v_mat_2d
typedef std::vector< matrix_2d > * pv_mat_2d
typedef v_mat_2d::iterator _it_v_mat_2d
typedef v_mat_2d::const_iterator _it_v_mat_2d_const
typedef std::vector< v_mat_2d > vv_mat_2d
Functions
std::ostream & operator<< (std::ostream &os, const matrix_2d &rhs)
void out_of_memory_handler ()
template<typename T>
std::size_t byteSize (const index_t elements=1)
Variables
index_t __row__
index_t __col__
Typedef Documentation
v_mat_2d
typedef std::vector<matrix_2d> dynadjust::math::v_mat_2d
Definition at line 126 of file dnamatrix_contiguous.hpp.
pv_mat_2d
typedef std::vector<matrix_2d> * dynadjust::math::pv_mat_2d
Definition at line 126 of file dnamatrix_contiguous.hpp.
_it_v_mat_2d
typedef v_mat_2d::iterator dynadjust::math::_it_v_mat_2d
Definition at line 127 of file dnamatrix_contiguous.hpp.
_it_v_mat_2d_const
typedef v_mat_2d::const_iterator dynadjust::math::_it_v_mat_2d_const
Definition at line 128 of file dnamatrix_contiguous.hpp.
vv_mat_2d
typedef std::vector<v_mat_2d> dynadjust::math::vv_mat_2d
Definition at line 129 of file dnamatrix_contiguous.hpp.
Function Documentation
operator<<()
std::ostream & dynadjust::math::operator<< (std::ostream & os, const matrix_2d & rhs)
Definition at line 32 of file dnamatrix_contiguous.cpp.
{
    if (os.iword(0) == binary) {
        os.write(reinterpret_cast<const char*>(&rhs._matrixType),
                 sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._rows), sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._cols), sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._mem_rows),
                 sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._mem_cols),
                 sizeof(index_t));
        index_t c, r;
        switch (rhs._matrixType) {
        case mtx_lower:
            if (rhs._mem_rows != rhs._mem_cols) {
                throw boost::enable_current_exception(std::runtime_error(
                    "matrix_2d operator<< (): Matrix not square."));
            }
            for (c = 0; c < rhs._mem_cols; ++c) {
                os.write(reinterpret_cast<const char*>(rhs.getelementref(c, c)),
                         (rhs._mem_rows - c) * sizeof(double));
            }
            break;
        case mtx_sparse: break;
        case mtx_full:
        default:
            for (r = 0; r < rhs._mem_rows; ++r) {
                for (c = 0; c < rhs._mem_cols; ++c) {
                    os.write(
                        reinterpret_cast<const char*>(rhs.getelementref(r, c)),
                        sizeof(double));
                }
            }
            break;
        }
        os.write(reinterpret_cast<const char*>(&rhs._maxvalRow),
                 sizeof(index_t));
        os.write(reinterpret_cast<const char*>(&rhs._maxvalCol),
                 sizeof(index_t));
    } else {
        os << rhs._matrixType << " " << rhs._rows << " " << rhs._cols << " "
           << rhs._mem_rows << " " << rhs._mem_cols << std::endl;
        for (index_t r = 0; r < rhs._mem_rows; ++r) {
            for (index_t c = 0; c < rhs._mem_cols; ++c) {
                os << std::scientific << std::setprecision(16) << rhs.get(r, c)
                   << " ";
            }
            os << std::endl;
        }
        os << rhs._maxvalRow << " " << rhs._maxvalCol << std::endl;
        os << std::endl;
    }
    return os;
}
out_of_memory_handler()
void dynadjust::math::out_of_memory_handler ()
Definition at line 89 of file dnamatrix_contiguous.cpp.
{
    std::stringstream ss("");
    index_t mem(std::max(__row__, __col__));
    mem *= std::min(__row__, __col__) * sizeof(index_t);
    ss << "Insufficient memory available to create a " << __row__ << " x "
       << __col__ << " matrix (" << std::fixed << std::setprecision(2);
    if (mem < MEGABYTE_SIZE)
        ss << (mem / KILOBYTE_SIZE) << " KB).";
    else if (mem < GIGABYTE_SIZE)
        ss << (mem / MEGABYTE_SIZE) << " MB).";
    else
        ss << (mem / GIGABYTE_SIZE) << " GB).";
    throw boost::enable_current_exception(NetMemoryException(ss.str()));
}
References __col__, __row__, GIGABYTE_SIZE, KILOBYTE_SIZE, and MEGABYTE_SIZE.
Referenced by dynadjust::math::matrix_2d::matrix_2d(), dynadjust::math::matrix_2d::matrix_2d(), dynadjust::math::matrix_2d::matrix_2d(), dynadjust::math::matrix_2d::matrix_2d(), and dynadjust::math::matrix_2d::redim().
byteSize()
template<typename T> std::size_t dynadjust::math::byteSize (const index_t elements = 1)
Definition at line 146 of file dnamatrix_contiguous.hpp.
{
    return elements * sizeof(T);
}
Referenced by dynadjust::math::matrix_2d::buy().
Variable Documentation
__row__
index_t dynadjust::math::__row__
Definition at line 86 of file dnamatrix_contiguous.cpp.
Referenced by dynadjust::math::matrix_2d::buy(), and out_of_memory_handler().
__col__
index_t dynadjust::math::__col__
Definition at line 87 of file dnamatrix_contiguous.cpp.
Referenced by dynadjust::math::matrix_2d::buy(), and out_of_memory_handler().