DynAdjust: dynadjust::datum_parameters Namespace Reference
dynadjust::datum_parameters Namespace Reference
Classes
struct _gda94_to_gda2020_
struct _itrf1996_to_gda2020_
struct _itrf1996_to_gda94_
struct _itrf1997_to_gda2020_
struct _itrf1997_to_gda94_
struct _itrf2000_to_gda2020_
struct _itrf2000_to_gda94_
struct _itrf2000_to_itrf1988_
struct _itrf2000_to_itrf1989_
struct _itrf2000_to_itrf1990_
struct _itrf2000_to_itrf1991_
struct _itrf2000_to_itrf1992_
struct _itrf2000_to_itrf1993_
struct _itrf2000_to_itrf1994_
struct _itrf2000_to_itrf1996_
struct _itrf2000_to_itrf1997_
struct _itrf2005_to_gda2020_
struct _itrf2005_to_gda94_
struct _itrf2005_to_itrf2000_
struct _itrf2008_to_gda2020_
struct _itrf2008_to_gda94_
struct _itrf2008_to_itrf1988_
struct _itrf2008_to_itrf1989_
struct _itrf2008_to_itrf1990_
struct _itrf2008_to_itrf1991_
struct _itrf2008_to_itrf1992_
struct _itrf2008_to_itrf1993_
struct _itrf2008_to_itrf1994_
struct _itrf2008_to_itrf1996_
struct _itrf2008_to_itrf1997_
struct _itrf2008_to_itrf2000_
struct _itrf2008_to_itrf2005_
struct _itrf2014_to_gda2020_
struct _itrf2014_to_gda94_
struct _itrf2014_to_itrf1988_
struct _itrf2014_to_itrf1989_
struct _itrf2014_to_itrf1990_
struct _itrf2014_to_itrf1991_
struct _itrf2014_to_itrf1992_
struct _itrf2014_to_itrf1993_
struct _itrf2014_to_itrf1994_
struct _itrf2014_to_itrf1996_
struct _itrf2014_to_itrf1997_
struct _itrf2014_to_itrf2000_
struct _itrf2014_to_itrf2005_
struct _itrf2014_to_itrf2008_
struct _itrf2020_to_gda2020_
struct _itrf2020_to_itrf1988_
struct _itrf2020_to_itrf1989_
struct _itrf2020_to_itrf1990_
struct _itrf2020_to_itrf1991_
struct _itrf2020_to_itrf1992_
struct _itrf2020_to_itrf1993_
struct _itrf2020_to_itrf1994_
struct _itrf2020_to_itrf1996_
struct _itrf2020_to_itrf1997_
struct _itrf2020_to_itrf2000_
struct _itrf2020_to_itrf2005_
struct _itrf2020_to_itrf2008_
struct _itrf2020_to_itrf2014_
class AUS_PLATE_MOTION_MODEL
class CDnaDatum
class CDnaEllipsoid
class CDnaProjection
class GDA94_GDA2020
class ITRF1996_GDA2020
class ITRF1996_GDA94
class ITRF1997_GDA2020
class ITRF1997_GDA94
class ITRF2000_GDA2020
class ITRF2000_GDA94
class ITRF2000_ITRF1988
class ITRF2000_ITRF1989
class ITRF2000_ITRF1990
class ITRF2000_ITRF1991
class ITRF2000_ITRF1992
class ITRF2000_ITRF1993
class ITRF2000_ITRF1994
class ITRF2000_ITRF1996
class ITRF2000_ITRF1997
class ITRF2005_GDA2020
class ITRF2005_GDA94
class ITRF2005_ITRF2000
class ITRF2008_GDA2020
class ITRF2008_GDA94
class ITRF2008_ITRF1988
class ITRF2008_ITRF1989
class ITRF2008_ITRF1990
class ITRF2008_ITRF1991
class ITRF2008_ITRF1992
class ITRF2008_ITRF1993
class ITRF2008_ITRF1994
class ITRF2008_ITRF1996
class ITRF2008_ITRF1997
class ITRF2008_ITRF2000
class ITRF2008_ITRF2005
class ITRF2014_GDA2020
class ITRF2014_GDA94
class ITRF2014_ITRF1988
class ITRF2014_ITRF1989
class ITRF2014_ITRF1990
class ITRF2014_ITRF1991
class ITRF2014_ITRF1992
class ITRF2014_ITRF1993
class ITRF2014_ITRF1994
class ITRF2014_ITRF1996
class ITRF2014_ITRF1997
class ITRF2014_ITRF2000
class ITRF2014_ITRF2005
class ITRF2014_ITRF2008
class ITRF2020_GDA2020
class ITRF2020_ITRF1988
class ITRF2020_ITRF1989
class ITRF2020_ITRF1990
class ITRF2020_ITRF1991
class ITRF2020_ITRF1992
class ITRF2020_ITRF1993
class ITRF2020_ITRF1994
class ITRF2020_ITRF1996
class ITRF2020_ITRF1997
class ITRF2020_ITRF2000
class ITRF2020_ITRF2005
class ITRF2020_ITRF2008
class ITRF2020_ITRF2014
struct transformation_parameter_set_
Typedefs
typedef struct dynadjust::datum_parameters::transformation_parameter_set_ transformation_parameter_set
typedef std::vector< transformation_parameter_set > vtransparams
Enumerations
enum transformationDirection { __paramForward__ = 0 , __paramReverse__ = 1 }
enum transformationType {
__static_to_static__ = 0 , __static_to_dynamic__ = 1 , __static_to_step__ = 2 , __dynamic_to_step__ = 3 ,
__dynamic_to_static__ = 4 , __dynamic_to_dynamic__ = 5 , __step_to_dynamic__ = 6 , __step_to_static__ = 7 ,
__plate_motion_model__ = 8
}
enum frameSimilarity { __frame_frame_same__ = 0 , __frame_frame_diff__ = 1 }
enum epochSimilarity { __epoch_epoch_same__ = 0 , __epoch_epoch_diff__ = 1 }
Functions
template<class S, class U>
S message_parameters_undefined (U from_epsg_code, U to_epsg_code)
template<typename U>
void determineGDA94Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineGDA2020Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1988Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1989Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1990Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1991Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1992Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1993Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1994Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1996Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF1997Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF2000Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF2005Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF2008Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF2014Parameters (transformation_parameter_set &tParam)
template<typename U>
void determineITRF2020Parameters (transformation_parameter_set &tParam)
template<typename T, typename U>
void getAustralianPlateMotionModelParameters (transformation_parameter_set &tParam)
template<typename T, typename U>
void setDefinedPlateMotionModelParameters (transformation_parameter_set &tParam, const T &x, const T &y, const T &z)
template<typename U>
void determineHelmertParameters (transformation_parameter_set &tParam)
template<class S = std::string, class U>
S TransformationType (const U &u)
Variables
template<class T, class U>
const U _itrf2000_to_itrf1997_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1997_< T, U >::reference_epoch = 1997.0
template<class T, class U>
const T _itrf2000_to_itrf1997_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_itrf1996_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1996_< T, U >::reference_epoch = 1997.0
template<class T, class U>
const T _itrf2000_to_itrf1996_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_itrf1994_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1994_< T, U >::reference_epoch = 1997.0
template<class T, class U>
const T _itrf2000_to_itrf1994_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_itrf1993_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1993_< T, U >::reference_epoch = 1988.0
template<class T, class U>
const T _itrf2000_to_itrf1993_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_itrf1992_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1992_< T, U >::reference_epoch = 1988.0
template<class T, class U>
const T _itrf2000_to_itrf1992_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_itrf1991_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1991_< T, U >::reference_epoch = 1988.0
template<class T, class U>
const T _itrf2000_to_itrf1991_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_itrf1990_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1990_< T, U >::reference_epoch = 1988.0
template<class T, class U>
const T _itrf2000_to_itrf1990_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_itrf1989_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1989_< T, U >::reference_epoch = 1988.0
template<class T, class U>
const T _itrf2000_to_itrf1989_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_itrf1988_< T, U >::reference_frame = ITRF2000_i
template<class T, class U>
const T _itrf2000_to_itrf1988_< T, U >::reference_epoch = 1988.0
template<class T, class U>
const T _itrf2000_to_itrf1988_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2005_to_itrf2000_< T, U >::reference_frame = ITRF2005_i
template<class T, class U>
const T _itrf2005_to_itrf2000_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2005_to_itrf2000_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf2005_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf2005_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf2005_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf2000_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf2000_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf2000_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1997_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1997_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1997_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1996_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1996_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1996_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1994_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1994_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1994_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1993_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1993_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1993_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1992_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1992_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1992_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1991_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1991_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1991_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1990_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1990_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1990_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1989_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1989_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1989_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_itrf1988_< T, U >::reference_frame = ITRF2008_i
template<class T, class U>
const T _itrf2008_to_itrf1988_< T, U >::reference_epoch = 2000.0
template<class T, class U>
const T _itrf2008_to_itrf1988_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf2008_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf2008_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf2008_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf2005_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf2005_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf2005_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf2000_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf2000_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf2000_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1997_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1997_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1997_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1996_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1996_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1996_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1994_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1994_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1994_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1993_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1993_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1993_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1992_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1992_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1992_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1991_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1991_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1991_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1990_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1990_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1990_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1989_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1989_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1989_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_itrf1988_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_itrf1988_< T, U >::reference_epoch = 2010.0
template<class T, class U>
const T _itrf2014_to_itrf1988_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_gda2020_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2014_to_gda2020_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _itrf2014_to_gda2020_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf2014_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf2014_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf2014_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf2008_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf2008_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf2008_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf2005_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf2005_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf2005_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf2000_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf2000_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf2000_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1997_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf1997_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1997_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1996_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf1996_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1996_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1994_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf1994_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1994_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1993_< T, U >::reference_frame = ITRF2014_i
template<class T, class U>
const T _itrf2020_to_itrf1993_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1993_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1992_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf1992_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1992_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1991_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf1991_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1991_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1990_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf1990_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1990_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1989_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf1989_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1989_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_itrf1988_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_itrf1988_< T, U >::reference_epoch = 2015.0
template<class T, class U>
const T _itrf2020_to_itrf1988_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2020_to_gda2020_< T, U >::reference_frame = ITRF2020_i
template<class T, class U>
const T _itrf2020_to_gda2020_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _itrf2020_to_gda2020_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf1996_to_gda2020_< T, U >::reference_frame = GDA2020_i
template<class T, class U>
const T _itrf1996_to_gda2020_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _itrf1996_to_gda2020_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf1997_to_gda2020_< T, U >::reference_frame = GDA2020_i
template<class T, class U>
const T _itrf1997_to_gda2020_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _itrf1997_to_gda2020_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_gda2020_< T, U >::reference_frame = GDA2020_i
template<class T, class U>
const T _itrf2000_to_gda2020_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _itrf2000_to_gda2020_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2005_to_gda2020_< T, U >::reference_frame = GDA2020_i
template<class T, class U>
const T _itrf2005_to_gda2020_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _itrf2005_to_gda2020_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_gda2020_< T, U >::reference_frame = GDA2020_i
template<class T, class U>
const T _itrf2008_to_gda2020_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _itrf2008_to_gda2020_< T, U >::transformationParameters [14]
template<class T, class U>
const U _gda94_to_gda2020_< T, U >::reference_frame = GDA2020_i
template<class T, class U>
const T _gda94_to_gda2020_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _gda94_to_gda2020_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2014_to_gda94_< T, U >::reference_frame = GDA94_i
template<class T, class U>
const T _itrf2014_to_gda94_< T, U >::reference_epoch = 2020.0
template<class T, class U>
const T _itrf2014_to_gda94_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2008_to_gda94_< T, U >::reference_frame = GDA94_i
template<class T, class U>
const T _itrf2008_to_gda94_< T, U >::reference_epoch = 1994.0
template<class T, class U>
const T _itrf2008_to_gda94_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2005_to_gda94_< T, U >::reference_frame = GDA94_i
template<class T, class U>
const T _itrf2005_to_gda94_< T, U >::reference_epoch = 1994.0
template<class T, class U>
const T _itrf2005_to_gda94_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf2000_to_gda94_< T, U >::reference_frame = GDA94_i
template<class T, class U>
const T _itrf2000_to_gda94_< T, U >::reference_epoch = 1994.0
template<class T, class U>
const T _itrf2000_to_gda94_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf1997_to_gda94_< T, U >::reference_frame = GDA94_i
template<class T, class U>
const T _itrf1997_to_gda94_< T, U >::reference_epoch = 1994.0
template<class T, class U>
const T _itrf1997_to_gda94_< T, U >::transformationParameters [14]
template<class T, class U>
const U _itrf1996_to_gda94_< T, U >::reference_frame = GDA94_i
template<class T, class U>
const T _itrf1996_to_gda94_< T, U >::reference_epoch = 1994.0
template<class T, class U>
const T _itrf1996_to_gda94_< T, U >::transformationParameters [14]
Typedef Documentation
transformation_parameter_set
typedef struct dynadjust::datum_parameters::transformation_parameter_set_ dynadjust::datum_parameters::transformation_parameter_set
vtransparams
typedef std::vector<transformation_parameter_set> dynadjust::datum_parameters::vtransparams
Definition at line 150 of file dnatransformationparameters.hpp.
Enumeration Type Documentation
transformationDirection
enum dynadjust::datum_parameters::transformationDirection
Enumerator
__paramForward__
__paramReverse__
Definition at line 46 of file dnatransformationparameters.hpp.
{
    __paramForward__ = 0,
    __paramReverse__ = 1
} transformationDirection;
transformationType
enum dynadjust::datum_parameters::transformationType
Enumerator
__static_to_static__
__static_to_dynamic__
__static_to_step__
__dynamic_to_step__
__dynamic_to_static__
__dynamic_to_dynamic__
__step_to_dynamic__
__step_to_static__
__plate_motion_model__
Definition at line 52 of file dnatransformationparameters.hpp.
{
    __static_to_static__ =   0,
    __static_to_dynamic__ =  1,
    __static_to_step__ =     2,
    __dynamic_to_step__ =    3,
    __dynamic_to_static__ =  4,
    __dynamic_to_dynamic__ = 5,
    __step_to_dynamic__ =    6,
    __step_to_static__ =     7,
    __plate_motion_model__ = 8
} transformationType;
frameSimilarity
enum dynadjust::datum_parameters::frameSimilarity
Enumerator
__frame_frame_same__
__frame_frame_diff__
Definition at line 97 of file dnatransformationparameters.hpp.
{
    __frame_frame_same__ = 0,
    __frame_frame_diff__ = 1
} frameSimilarity;
epochSimilarity
enum dynadjust::datum_parameters::epochSimilarity
Enumerator
__epoch_epoch_same__
__epoch_epoch_diff__
Definition at line 103 of file dnatransformationparameters.hpp.
{
    __epoch_epoch_same__ = 0,
    __epoch_epoch_diff__ = 1
} epochSimilarity;
Function Documentation
message_parameters_undefined()
template<class S, class U> S dynadjust::datum_parameters::message_parameters_undefined (U from_epsg_code, U to_epsg_code)
Definition at line 50 of file dnatransparamfuncs.hpp.
{
    // No direct parameters exist!
    std::stringstream ss;
    ss << datumFromEpsgCode<S, U>(from_epsg_code) << " to " <<
        datumFromEpsgCode<S, U>(to_epsg_code) << " parameters have not been defined.";
    return ss.str();
}
References dynadjust::epsg::datumFromEpsgCode().
Referenced by determineGDA2020Parameters(), determineGDA94Parameters(), determineITRF1988Parameters(), determineITRF1989Parameters(), determineITRF1990Parameters(), determineITRF1991Parameters(), determineITRF1992Parameters(), determineITRF1993Parameters(), determineITRF1994Parameters(), determineITRF1996Parameters(), determineITRF1997Parameters(), determineITRF2005Parameters(), and determineITRF2020Parameters().
determineGDA94Parameters()
template<typename U> void dynadjust::datum_parameters::determineGDA94Parameters (transformation_parameter_set & tParam)
Definition at line 62 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // GDA94-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        memcpy(&tParam.parameters_, GDA94_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = GDA94_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = GDA94_GDA2020<double, UINT32>::reference_frame;
        break;
    // GDA94-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        // no transformation - set zero
        memset(&tParam.parameters_, 0, sizeof(double) * 14);
        break;
    // GDA94-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // GDA94-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // GDA94-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // GDA94-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // GDA94-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // GDA94-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // GDA94-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // GDA94-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        memcpy(&tParam.parameters_, ITRF1996_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF1996_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF1996_GDA94<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA94-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        memcpy(&tParam.parameters_, ITRF1997_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF1997_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF1997_GDA94<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA94-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_GDA94<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA94-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        memcpy(&tParam.parameters_, ITRF2005_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2005_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2005_GDA94<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA94-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_GDA94<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA94-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_GDA94<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA94-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // GDA94-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineGDA94Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineGDA2020Parameters()
template<typename U> void dynadjust::datum_parameters::determineGDA2020Parameters (transformation_parameter_set & tParam)
Definition at line 192 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // GDA2020-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        memcpy(&tParam.parameters_, GDA94_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = GDA94_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = GDA94_GDA2020<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA2020-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        // no transformation - set zero
        memset(&tParam.parameters_, 0, sizeof(double) * 14);
        break;
    // GDA2020-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // GDA2020-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // GDA2020-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // GDA2020-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // GDA2020-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // GDA2020-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // GDA2020-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // GDA2020-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        memcpy(&tParam.parameters_, ITRF1996_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF1996_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF1996_GDA2020<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA2020-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        memcpy(&tParam.parameters_, ITRF1997_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF1997_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF1997_GDA2020<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA2020-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_GDA2020<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA2020-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        memcpy(&tParam.parameters_, ITRF2005_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2005_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2005_GDA2020<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA2020-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_GDA2020<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA2020-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_GDA2020<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA2020-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_GDA2020<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // GDA2020-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineGDA2020Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1988Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1988Parameters (transformation_parameter_set & tParam)
Definition at line 327 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1988-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF1988-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // ITRF1988-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1988-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1988-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1988-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1988-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1988-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1988-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1988-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF1988-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1988-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1992 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1988-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1988<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1988<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1988<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1988-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1988<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1988<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1988<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1988-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1988<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1988<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1988<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1988-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1988<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1988<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1988<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1988-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1988Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1988_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1988_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1988_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1989Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1989Parameters (transformation_parameter_set & tParam)
Definition at line 438 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1989-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF1989-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // ITRF1989-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1989-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1989-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1989-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1989-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1989-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1989-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1989-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF1989-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1989-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1992 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1989-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1989<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1989-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1989<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1989-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1989<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1989-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1989<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1989-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1989Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1990Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1990Parameters (transformation_parameter_set & tParam)
Definition at line 549 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1990-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF1990-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // ITRF1990-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1990-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1990-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1990-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1990-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1990-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1990-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1990-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF1990-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1990-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1990 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1990-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1990<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1990<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1990<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1990-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1990<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1990<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1990<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1990-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1990<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1990<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1990<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1990-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1990<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1990<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1990<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1990-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1990Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1991Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1991Parameters (transformation_parameter_set & tParam)
Definition at line 660 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1991-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF1991-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // ITRF1991-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1991-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1991-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1991-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1991-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1991-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1991-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1991-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF1991-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1991-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1991 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1991-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1991<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1991<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1991<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1991-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1991<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1991<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1991<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1991-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1991<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1991<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1991<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1991-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1991<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1991<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1991<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1991-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1991Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1992Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1992Parameters (transformation_parameter_set & tParam)
Definition at line 771 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1992-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF1992-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // ITRF1992-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1992-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1992-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1992-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1992-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1992-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1992-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1992-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF1992-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1992-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1992 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1992-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1992<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1992<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1992<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1992-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1992<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1992<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1992<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1992-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1992<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1992<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1992<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1992-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1992<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1992<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1992<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1992-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1992Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1993Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1993Parameters (transformation_parameter_set & tParam)
Definition at line 882 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1993-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF1993-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // ITRF1993-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1993-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1993-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1993-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1993-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1993-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1993-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1993-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF1993-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1993-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1993 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1993-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1993<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1993<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1993<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1993-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1993<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1993<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1993<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1993-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1993<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1993<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1993<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1993-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1993<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1993<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1993<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1993-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1993Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1994Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1994Parameters (transformation_parameter_set & tParam)
Definition at line 993 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1994-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF1994-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // ITRF1994-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1994-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1994-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1994-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1994-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1994-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1994-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1994-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF1994-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1994-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1994 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1994-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1994<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1994<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1994<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1994-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1994<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1994<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1994<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1994-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1994<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1994<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1994<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1994-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1994<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1994<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1994<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1994-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1994Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1996Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1996Parameters (transformation_parameter_set & tParam)
Definition at line 1104 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1996-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        memcpy(&tParam.parameters_, ITRF1996_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF1996_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF1996_GDA2020<double, UINT32>::reference_frame;
        break;
    // ITRF1996-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        memcpy(&tParam.parameters_, ITRF1996_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF1996_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF1996_GDA94<double, UINT32>::reference_frame;
        break;
    // ITRF1996-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1996-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1996-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1996-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1996-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1996-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1996-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1996-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF1996-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1996-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1996 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1996-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1996<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1996<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1996<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1996-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1996<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1996<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1996<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1996-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1996<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1996<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1996<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1996-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1996<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1996<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1996<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1996-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1996Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF1997Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF1997Parameters (transformation_parameter_set & tParam)
Definition at line 1223 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF1997-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        memcpy(&tParam.parameters_, ITRF1997_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF1997_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF1997_GDA2020<double, UINT32>::reference_frame;
        break;
    // ITRF1997-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        memcpy(&tParam.parameters_, ITRF1997_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF1997_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF1997_GDA94<double, UINT32>::reference_frame;
        break;
    // ITRF1997-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1997-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1997-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1997-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1997-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1997-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1997-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1997-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1997-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF1997-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF1997 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF1997-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1997<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1997<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1997<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1997-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1997<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1997<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1997<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1997-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1997<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1997<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1997<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1997-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1997<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1997<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1997<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF1997-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF1997Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF2000Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF2000Parameters (transformation_parameter_set & tParam)
Definition at line 1342 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF2000-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        memcpy(&tParam.parameters_, ITRF2000_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_GDA2020<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        memcpy(&tParam.parameters_, ITRF2000_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_GDA94<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1988<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1988<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1988<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1989<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1990<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1990<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1990<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1991<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1991<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1991<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1992<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1992<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1992<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1993<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1993<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1993<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1994<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1994<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1994<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1996<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1996<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1996<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        memcpy(&tParam.parameters_, ITRF2000_ITRF1997<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2000_ITRF1997<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2000_ITRF1997<double, UINT32>::reference_frame;
        break;
    // ITRF2000-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF2005 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF2000-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        memcpy(&tParam.parameters_, ITRF2005_ITRF2000<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2005_ITRF2000<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2005_ITRF2000<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2000-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF2000<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF2000<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF2000<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2000-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF2000<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF2000<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF2000<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2000-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF2000<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF2000<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF2000<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2000-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF2000Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF2005Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF2005Parameters (transformation_parameter_set & tParam)
Definition at line 1494 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF2005-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        memcpy(&tParam.parameters_, ITRF2005_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2005_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2005_GDA2020<double, UINT32>::reference_frame;
        break;
    // ITRF2005-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        memcpy(&tParam.parameters_, ITRF2005_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2005_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2005_GDA94<double, UINT32>::reference_frame;
        break;
    // ITRF2005-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF2005-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF2005-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF2005-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF2005-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF2005-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF2005-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF2005-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF2005-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
    // ITRF2005-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2005_ITRF2000<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2005_ITRF2000<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2005_ITRF2000<double, UINT32>::reference_frame;
        break;
    // ITRF2005-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF2005 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF2005-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF2005<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF2005<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF2005<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2005-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF2005<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF2005<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF2005<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2005-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF2005<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF2005<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF2005<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2005-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF2005Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF2008Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF2008Parameters (transformation_parameter_set & tParam)
Definition at line 1611 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF2008-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        memcpy(&tParam.parameters_, ITRF2008_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_GDA2020<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        memcpy(&tParam.parameters_, ITRF2008_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_GDA94<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1988<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1988<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1988<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1989<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1990<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1990<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1990<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1991<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1991<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1991<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1992<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1992<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1992<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1993<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1993<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1993<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1994<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1994<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1994<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1996<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1996<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1996<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF1997<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF1997<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF1997<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF2000<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF2000<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF2000<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        memcpy(&tParam.parameters_, ITRF2008_ITRF2005<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2008_ITRF2005<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2008_ITRF2005<double, UINT32>::reference_frame;
        break;
    // ITRF2008-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF2008 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF2008-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF2008<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF2008<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF2008<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2008-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF2008<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF2008<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF2008<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2008-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF2008Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF2014Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF2014Parameters (transformation_parameter_set & tParam)
Definition at line 1760 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF2014-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        memcpy(&tParam.parameters_, ITRF2014_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_GDA2020<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        memcpy(&tParam.parameters_, ITRF2014_GDA94<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_GDA94<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_GDA94<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1989<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1989<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1990<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1990<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1990<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1991<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1991<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1991<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1992<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1992<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1992<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1993<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1993<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1993<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1994<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1994<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1994<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1996<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1996<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1996<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF1997<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF1997<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF1997<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF2000<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF2000<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF2000<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF2005<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF2005<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF2005<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2014_ITRF2008<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2014_ITRF2008<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2014_ITRF2008<double, UINT32>::reference_frame;
        break;
    // ITRF2014-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF2014 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF2014-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF2014<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF2014<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF2014<double, UINT32>::reference_frame;
        tParam.paramDirection_ = __paramReverse__;
        tParam.reverse();
        break;
    // ITRF2014-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF2014Parameters(): "));
    }
}
References __paramReverse__, dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::transformation_parameter_set_::reverse(), dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
determineITRF2020Parameters()
template<typename U> void dynadjust::datum_parameters::determineITRF2020Parameters (transformation_parameter_set & tParam)
Definition at line 1906 of file dnatransparamfuncs.hpp.
{
    // Which 'to' datum?
    switch (tParam.from_to_.second)
    {
    // ITRF2020-to-GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        memcpy(&tParam.parameters_, ITRF2020_GDA2020<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_GDA2020<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_GDA2020<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        // No direct parameters exist!
        throw RefTranException(message_parameters_undefined<std::string, UINT32>(tParam.from_to_.first, tParam.from_to_.second),
            REFTRAN_DIRECT_PARAMS_UNAVAILABLE);
        break;
    // ITRF2020-to-ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1988<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1988<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1988<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1989<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1989<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1989<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1990<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1990<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1990<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1991<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1991<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1991<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1992<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1992<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1992<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1993<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1993<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1993<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1994<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1994<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1994<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1996<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1996<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1996<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF1997<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF1997<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF1997<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF2000<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF2000<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF2000<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF2005<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF2005<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF2005<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF2008<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF2008<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF2008<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        memcpy(&tParam.parameters_, ITRF2020_ITRF2014<double, UINT32>::transformationParameters, sizeof(double) * 14);
        tParam.reference_epoch_ = ITRF2020_ITRF2014<double, UINT32>::reference_epoch;
        tParam.reference_frame_ = ITRF2020_ITRF2014<double, UINT32>::reference_frame;
        break;
    // ITRF2020-to-ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        // not a transformation of frame, but a shift in epoch only
        // Not defined yet - requires interpolation from the ITRF2014 velocity model
        throw RefTranException("A transformation between different epochs on the same frame is required.",
            REFTRAN_TRANS_ON_PLATE_REQUIRED);
    // ITRF2014-to-WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
    default:
        throw boost::enable_current_exception(std::runtime_error("determineITRF2020Parameters(): "));
    }
}
References dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, message_parameters_undefined(), dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::reference_epoch, dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::reference_frame, dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, REFTRAN_DIRECT_PARAMS_UNAVAILABLE, REFTRAN_TRANS_ON_PLATE_REQUIRED, dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::transformationParameters, dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::transformationParameters, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by determineHelmertParameters().
getAustralianPlateMotionModelParameters()
template<typename T, typename U> void dynadjust::datum_parameters::getAustralianPlateMotionModelParameters (transformation_parameter_set & tParam)
Definition at line 2052 of file dnatransparamfuncs.hpp.
{
    tParam.paramDirection_ = __paramForward__;
    memcpy(&tParam.parameters_, AUS_PLATE_MOTION_MODEL<T, U>::transformationParameters, sizeof(T) * 14);
    tParam.reference_epoch_ = AUS_PLATE_MOTION_MODEL<T, U>::reference_epoch;
    tParam.reference_frame_ = AUS_PLATE_MOTION_MODEL<T, U>::reference_frame;
}
References __paramForward__, dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, dynadjust::datum_parameters::transformation_parameter_set_::parameters_, dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::reference_epoch, dynadjust::datum_parameters::transformation_parameter_set_::reference_epoch_, dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::reference_frame, dynadjust::datum_parameters::transformation_parameter_set_::reference_frame_, and dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::transformationParameters.
Referenced by dynadjust::referenceframe::dna_reftran::ObtainPlateMotionParameters().
setDefinedPlateMotionModelParameters()
template<typename T, typename U> void dynadjust::datum_parameters::setDefinedPlateMotionModelParameters (transformation_parameter_set & tParam, const T & x, const T & y, const T & z)
Definition at line 2063 of file dnatransparamfuncs.hpp.
{
    tParam.paramDirection_ = __paramForward__;
    tParam.parameters_[0] = 0.0; // x translation (millimetres)
    tParam.parameters_[1] = 0.0; // y translation (millimetres)
    tParam.parameters_[2] = 0.0; // z translation (millimetres)
    tParam.parameters_[3] = 0.0; // scale (ppb)
    tParam.parameters_[4] = 0.0; // x rotation (milli-arc-seconds)
    tParam.parameters_[5] = 0.0; // y rotation (milli-arc-seconds)
    tParam.parameters_[6] = 0.0; // z rotation (milli-arc-seconds)
    tParam.parameters_[7] = 0.0; // x translation rate (millimetres p/yr)
    tParam.parameters_[8] = 0.0; // y translation rate (millimetres p/yr)
    tParam.parameters_[9] = 0.0; // z translation rate (millimetres p/yr)
    tParam.parameters_[10] = 0.0;    // scale rate (ppb p/yr)
    tParam.parameters_[11] = x;      // x rotation rate (milli-arc-seconds p/yr)
    tParam.parameters_[12] = y;      // y rotation rate (milli-arc-seconds p/yr)
    tParam.parameters_[13] = z;      // z rotation rate (milli-arc-seconds p/yr)
}
References __paramForward__, dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, and dynadjust::datum_parameters::transformation_parameter_set_::parameters_.
Referenced by dynadjust::referenceframe::dna_reftran::ObtainPlateMotionParameters().
determineHelmertParameters()
template<typename U> void dynadjust::datum_parameters::determineHelmertParameters (transformation_parameter_set & tParam)
Definition at line 2084 of file dnatransparamfuncs.hpp.
{
    tParam.paramDirection_ = __paramForward__;
    try
    {
        // Which 'from' datum?
        switch (tParam.from_to_.first)
        {
        // GDA94
        case GDA94_i_xyz:
        case GDA94_i_2d:
        case GDA94_i:
            determineGDA94Parameters<U>(tParam);
            break;
        // GDA2020
        case GDA2020_i_xyz:
        case GDA2020_i_2d:
        case GDA2020_i:
            determineGDA2020Parameters<U>(tParam);
            break;
        // ITRF1988
        case ITRF1988_i_xyz:
        case ITRF1988_i:
            determineITRF1988Parameters<U>(tParam);
            break;
        // ITRF1989
        case ITRF1989_i_xyz:
        case ITRF1989_i:
            determineITRF1989Parameters<U>(tParam);
            break;
        // ITRF1990
        case ITRF1990_i_xyz:
        case ITRF1990_i:
            determineITRF1990Parameters<U>(tParam);
            break;
        // ITRF1991
        case ITRF1991_i_xyz:
        case ITRF1991_i:
            determineITRF1991Parameters<U>(tParam);
            break;
        // ITRF1992
        case ITRF1992_i_xyz:
        case ITRF1992_i:
            determineITRF1992Parameters<U>(tParam);
            break;
        // ITRF1993
        case ITRF1993_i_xyz:
        case ITRF1993_i:
            determineITRF1993Parameters<U>(tParam);
            break;
        // ITRF1994
        case ITRF1994_i_xyz:
        case ITRF1994_i:
            determineITRF1994Parameters<U>(tParam);
            break;
        // ITRF1996
        case ITRF1996_i_xyz:
        case ITRF1996_i:
            determineITRF1996Parameters<U>(tParam);
            break;
        // ITRF1997
        case ITRF1997_i_xyz:
        case ITRF1997_i:
            determineITRF1997Parameters<U>(tParam);
            break;
        // ITRF2000
        case ITRF2000_i_xyz:
        case ITRF2000_i:
            determineITRF2000Parameters<U>(tParam);
            break;
        // ITRF2005
        case ITRF2005_i_xyz:
        case ITRF2005_i:
            determineITRF2005Parameters<U>(tParam);
            break;
        // ITRF2008
        case ITRF2008_i_xyz:
        case ITRF2008_i:
            determineITRF2008Parameters<U>(tParam);
            break;
        // ITRF2014
        case ITRF2014_i_xyz:
        case ITRF2014_i:
            determineITRF2014Parameters<U>(tParam);
            break;
        // ITRF2020
        case ITRF2020_i_xyz:
        case ITRF2020_i:
            determineITRF2020Parameters<U>(tParam);
            break;
        // WGS84
        case WGS84_i_xyz:
        case WGS84_i:
        case WGS84_transit_i_xyz:
        case WGS84_transit_i:
        case WGS84_G730_i_xyz:
        case WGS84_G730_i:
        case WGS84_G873_i_xyz:
        case WGS84_G873_i:
        case WGS84_G1150_i_xyz:
        case WGS84_G1150_i:
        case WGS84_G1674_i_xyz:
        case WGS84_G1674_i:
        case WGS84_G1762_i_xyz:
        case WGS84_G1762_i:
        case WGS84_G2139_i_xyz:
        case WGS84_G2139_i:
            throw RefTranException("Transformation parameters from WGS 84 are unavailable.",
                REFTRAN_WGS84_TRANS_UNSUPPORTED);
            break;
        default:
            throw boost::enable_current_exception(std::runtime_error(""));
        }
    }
    catch (std::runtime_error& e)
    {
        std::stringstream ss;
        ss << "determineHelmertParameters():" << std::endl <<
            "  " << e.what() << " Parameters for transforming between" << std::endl <<
            "  " << datumFromEpsgCode<std::string, UINT32>(tParam.from_to_.first) << " and " <<
            datumFromEpsgCode<std::string, UINT32>(tParam.from_to_.second) <<
            " have not been defined yet." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
}
References __paramForward__, dynadjust::epsg::datumFromEpsgCode(), determineGDA2020Parameters(), determineGDA94Parameters(), determineITRF1988Parameters(), determineITRF1989Parameters(), determineITRF1990Parameters(), determineITRF1991Parameters(), determineITRF1992Parameters(), determineITRF1993Parameters(), determineITRF1994Parameters(), determineITRF1996Parameters(), determineITRF1997Parameters(), determineITRF2000Parameters(), determineITRF2005Parameters(), determineITRF2008Parameters(), determineITRF2014Parameters(), determineITRF2020Parameters(), dynadjust::datum_parameters::transformation_parameter_set_::from_to_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, dynadjust::datum_parameters::transformation_parameter_set_::paramDirection_, REFTRAN_WGS84_TRANS_UNSUPPORTED, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by dynadjust::referenceframe::dna_reftran::ObtainHelmertParameters().
TransformationType()
template<class S = std::string, class U> S dynadjust::datum_parameters::TransformationType (const U & u)
Definition at line 66 of file dnatransformationparameters.hpp.
{
    switch (u)
    {
        case __static_to_static__:
            return "SS";
        case __static_to_dynamic__:
            return "SD";
        case __static_to_step__:
            // static (S) to intermediate (I)
            return "SI";
        case __dynamic_to_step__:
            // dynamic (D) to intermediate (I)
            return "DI";
        case __dynamic_to_static__:
            return "DS";
        case __dynamic_to_dynamic__:
            return "DD";
        case __step_to_dynamic__:
            // intermediate (I) to dynamic (D)
            return "ID";
        case __step_to_static__:
            // intermediate (I) to static (S)
            return "IS";
        case __plate_motion_model__:
            return "PM";
        default:
            return " ";
    }
}
References __dynamic_to_dynamic__, __dynamic_to_static__, __dynamic_to_step__, __plate_motion_model__, __static_to_dynamic__, __static_to_static__, __static_to_step__, __step_to_dynamic__, and __step_to_static__.
Variable Documentation
_itrf2000_to_itrf1997_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::reference_frame = ITRF2000_i
Definition at line 206 of file dnatransformationparameters.hpp.
Referenced by dynadjust::dynamlinterop::dna_import::InitialiseDatum().
_itrf2000_to_itrf1997_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::reference_epoch = 1997.0
Definition at line 209 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1997_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1997_< T, U >::transformationParameters[14]
Initial value:
=
{
      6.7,
      6.1,
    -18.5,
     1.55,
      0.0,
      0.0,
      0.0,
      0.0,
     -0.6,
     -1.4,
     0.01,
     0.00,
     0.00,
    -0.02
}
Definition at line 212 of file dnatransformationparameters.hpp.
{
      6.7,      // x translation (millimetres) - CONVERTED FROM CM
      6.1,      // y translation (millimetres) - CONVERTED FROM CM
    -18.5,      // z translation (millimetres) - CONVERTED FROM CM
     1.55,      // scale (ppb)
      0.0,      // x rotation (milli-arc-seconds)
      0.0,      // y rotation (milli-arc-seconds)
      0.0,      // z rotation (milli-arc-seconds)
      0.0,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -1.4,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
Referenced by dynadjust::referenceframe::dna_reftran::TransformMeasurementRecords(), and dynadjust::referenceframe::dna_reftran::TransformStationRecords().
_itrf2000_to_itrf1996_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::reference_frame = ITRF2000_i
Definition at line 247 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1996_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::reference_epoch = 1997.0
Definition at line 250 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1996_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1996_< T, U >::transformationParameters[14]
Initial value:
=
{
      6.7,
      6.1,
    -18.5,
     1.55,
      0.0,
      0.0,
      0.0,
      0.0,
     -0.6,
     -1.4,
     0.01,
     0.00,
     0.00,
    -0.02
}
Definition at line 253 of file dnatransformationparameters.hpp.
{
      6.7,      // x translation (millimetres) - CONVERTED FROM CM
      6.1,      // y translation (millimetres) - CONVERTED FROM CM
    -18.5,      // z translation (millimetres) - CONVERTED FROM CM
     1.55,      // scale (ppb)
      0.0,      // x rotation (milli-arc-seconds)
      0.0,      // y rotation (milli-arc-seconds)
      0.0,      // z rotation (milli-arc-seconds)
      0.0,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -1.4,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2000_to_itrf1994_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::reference_frame = ITRF2000_i
Definition at line 288 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1994_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::reference_epoch = 1997.0
Definition at line 291 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1994_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1994_< T, U >::transformationParameters[14]
Initial value:
=
{
      6.7,
      6.1,
    -18.5,
     1.55,
      0.0,
      0.0,
      0.0,
      0.0,
     -0.6,
     -1.4,
     0.01,
     0.00,
     0.00,
    -0.02
}
Definition at line 294 of file dnatransformationparameters.hpp.
{
      6.7,      // x translation (millimetres) - CONVERTED FROM CM
      6.1,      // y translation (millimetres) - CONVERTED FROM CM
    -18.5,      // z translation (millimetres) - CONVERTED FROM CM
     1.55,      // scale (ppb)
      0.0,      // x rotation (milli-arc-seconds)
      0.0,      // y rotation (milli-arc-seconds)
      0.0,      // z rotation (milli-arc-seconds)
      0.0,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -1.4,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2000_to_itrf1993_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::reference_frame = ITRF2000_i
Definition at line 329 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1993_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::reference_epoch = 1988.0
Definition at line 332 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1993_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1993_< T, U >::transformationParameters[14]
Initial value:
=
{
     12.7,
      6.5,
    -20.9,
     1.95,
     0.39,
    -0.80,
     1.14,
     -2.9,
     -0.2,
     -0.6,
     0.01,
     0.11,
     0.19,
    -0.07
}
Definition at line 335 of file dnatransformationparameters.hpp.
{
     12.7,      // x translation (millimetres) - CONVERTED FROM CM
      6.5,      // y translation (millimetres) - CONVERTED FROM CM
    -20.9,      // z translation (millimetres) - CONVERTED FROM CM
     1.95,      // scale (ppb)
     0.39,      // x rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
    -0.80,      // y rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     1.14,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     -2.9,      // x translation rate (millimetres p/yr) - CONVERTED FROM CM
     -0.2,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -0.6,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.11,      // x rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
     0.19,      // y rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
    -0.07       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2000_to_itrf1992_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::reference_frame = ITRF2000_i
Definition at line 370 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1992_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::reference_epoch = 1988.0
Definition at line 373 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1992_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1992_< T, U >::transformationParameters[14]
Initial value:
=
{
     14.7,
     13.5,
    -13.9,
     0.75,
     0.00,
     0.00,
     0.18,
      0.0,
     -0.6,
     -1.4,
     0.01,
     0.00,
     0.00,
    -0.02
}
Definition at line 376 of file dnatransformationparameters.hpp.
{
     14.7,      // x translation (millimetres) - CONVERTED FROM CM
     13.5,      // y translation (millimetres) - CONVERTED FROM CM
    -13.9,      // z translation (millimetres) - CONVERTED FROM CM
     0.75,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.18,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.0,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -1.4,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2000_to_itrf1991_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::reference_frame = ITRF2000_i
Definition at line 411 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1991_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::reference_epoch = 1988.0
Definition at line 414 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1991_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1991_< T, U >::transformationParameters[14]
Initial value:
=
{
     26.7,
     27.5,
    -19.9,
     2.15,
     0.00,
     0.00,
     0.18,
      0.0,
     -0.6,
     -1.4,
     0.01,
     0.00,
     0.00,
    -0.02
}
Definition at line 417 of file dnatransformationparameters.hpp.
{
     26.7,      // x translation (millimetres) - CONVERTED FROM CM
     27.5,      // y translation (millimetres) - CONVERTED FROM CM
    -19.9,      // z translation (millimetres) - CONVERTED FROM CM
     2.15,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.18,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.0,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -1.4,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2000_to_itrf1990_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::reference_frame = ITRF2000_i
Definition at line 452 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1990_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::reference_epoch = 1988.0
Definition at line 455 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1990_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1990_< T, U >::transformationParameters[14]
Initial value:
=
{
     24.7,
     23.5,
    -35.9,
     2.45,
     0.00,
     0.00,
     0.18,
      0.0,
     -0.6,
     -1.4,
     0.01,
     0.00,
     0.00,
    -0.02
}
Definition at line 458 of file dnatransformationparameters.hpp.
{
     24.7,      // x translation (millimetres) - CONVERTED FROM CM
     23.5,      // y translation (millimetres) - CONVERTED FROM CM
    -35.9,      // z translation (millimetres) - CONVERTED FROM CM
     2.45,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.18,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.0,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -1.4,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2000_to_itrf1989_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::reference_frame = ITRF2000_i
Definition at line 493 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1989_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::reference_epoch = 1988.0
Definition at line 496 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1989_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1989_< T, U >::transformationParameters[14]
Initial value:
=
{
     29.7,
     47.5,
    -73.9,
     5.85,
     0.00,
     0.00,
     0.18,
      0.0,
     -0.6,
     -1.4,
     0.01,
     0.00,
     0.00,
    -0.02
}
Definition at line 499 of file dnatransformationparameters.hpp.
{
     29.7,      // x translation (millimetres) - CONVERTED FROM CM
     47.5,      // y translation (millimetres) - CONVERTED FROM CM
    -73.9,      // z translation (millimetres) - CONVERTED FROM CM
     5.85,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.18,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.0,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -1.4,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2000_to_itrf1988_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::reference_frame = ITRF2000_i
Definition at line 534 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1988_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::reference_epoch = 1988.0
Definition at line 537 of file dnatransformationparameters.hpp.
_itrf2000_to_itrf1988_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_itrf1988_< T, U >::transformationParameters[14]
Initial value:
=
{
     24.7,
     11.5,
    -97.9,
     8.95,
    -0.10,
     0.00,
     0.18,
      0.0,
     -0.6,
     -1.4,
     0.01,
     0.00,
     0.00,
    -0.02
}
Definition at line 540 of file dnatransformationparameters.hpp.
{
     24.7,      // x translation (millimetres) - CONVERTED FROM CM
     11.5,      // y translation (millimetres) - CONVERTED FROM CM
    -97.9,      // z translation (millimetres) - CONVERTED FROM CM
     8.95,      // scale (ppb)
    -0.10,      // x rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     0.00,      // y rotation (milli-arc-seconds)
     0.18,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.0,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr) - CONVERTED FROM CM
     -1.4,      // z translation rate (millimetres p/yr) - CONVERTED FROM CM
     0.01,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2005_to_itrf2000_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::reference_frame = ITRF2005_i
Definition at line 581 of file dnatransformationparameters.hpp.
_itrf2005_to_itrf2000_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::reference_epoch = 2000.0
Definition at line 584 of file dnatransformationparameters.hpp.
_itrf2005_to_itrf2000_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2005_to_itrf2000_< T, U >::transformationParameters[14]
Initial value:
=
{
      0.1,
     -0.8,
     -5.8,
     0.40,
     0.00,
     0.00,
     0.00,
     -0.2,
      0.1,
     -1.8,
     0.08,
     0.00,
     0.00,
     0.00
}
Definition at line 587 of file dnatransformationparameters.hpp.
{
      0.1,      // x translation (millimetres)
     -0.8,      // y translation (millimetres)
     -5.8,      // z translation (millimetres)
     0.40,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
     -0.2,      // x translation rate (millimetres p/yr)
      0.1,      // y translation rate (millimetres p/yr)
     -1.8,      // z translation rate (millimetres p/yr)
     0.08,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2008_to_itrf2005_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::reference_frame = ITRF2008_i
Definition at line 628 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf2005_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::reference_epoch = 2000.0
Definition at line 631 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf2005_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf2005_< T, U >::transformationParameters[14]
Initial value:
=
{
     -2.0,
     -0.9,
     -4.7,
     0.94,
     0.00,
     0.00,
     0.00,
      0.3,
      0.0,
      0.0,
     0.00,
     0.00,
     0.00,
     0.00
}
Definition at line 634 of file dnatransformationparameters.hpp.
{
     -2.0,      // x translation (millimetres). Note this differs from Zuheir's JOG paper DOI 10.1007/s00190-011-0444-4
     -0.9,      // y translation (millimetres)
     -4.7,      // z translation (millimetres)
     0.94,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.3,      // x translation rate (millimetres p/yr)
      0.0,      // y translation rate (millimetres p/yr)
      0.0,      // z translation rate (millimetres p/yr)
     0.00,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2008_to_itrf2000_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::reference_frame = ITRF2008_i
Definition at line 669 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf2000_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::reference_epoch = 2000.0
Definition at line 672 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf2000_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf2000_< T, U >::transformationParameters[14]
Initial value:
=
{
     -1.9,
     -1.7,
    -10.5,
     1.34,
     0.00,
     0.00,
     0.00,
      0.1,
      0.1,
     -1.8,
     0.08,
     0.00,
     0.00,
     0.00
}
Definition at line 675 of file dnatransformationparameters.hpp.
{
     -1.9,      // x translation (millimetres)
     -1.7,      // y translation (millimetres)
    -10.5,      // z translation (millimetres)
     1.34,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.1,      // x translation rate (millimetres p/yr)
      0.1,      // y translation rate (millimetres p/yr)
     -1.8,      // z translation rate (millimetres p/yr)
     0.08,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2008_to_itrf1997_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::reference_frame = ITRF2008_i
Definition at line 710 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1997_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::reference_epoch = 2000.0
Definition at line 713 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1997_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1997_< T, U >::transformationParameters[14]
Initial value:
=
{
      4.8,
      2.6,
    -33.2,
     2.92,
     0.00,
     0.00,
    -0.06,
      0.1,
     -0.5,
     -3.2,
     0.09,
     0.00,
     0.00,
    -0.02
}
Definition at line 716 of file dnatransformationparameters.hpp.
{
      4.8,      // x translation (millimetres)
      2.6,      // y translation (millimetres)
    -33.2,      // z translation (millimetres)
     2.92,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.06,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.2,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2008_to_itrf1996_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::reference_frame = ITRF2008_i
Definition at line 751 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1996_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::reference_epoch = 2000.0
Definition at line 754 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1996_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1996_< T, U >::transformationParameters[14]
Initial value:
=
{
      4.8,
      2.6,
    -33.2,
     2.92,
     0.00,
     0.00,
    -0.06,
      0.1,
     -0.5,
     -3.2,
     0.09,
     0.00,
     0.00,
    -0.02
}
Definition at line 757 of file dnatransformationparameters.hpp.
{
      4.8,      // x translation (millimetres)
      2.6,      // y translation (millimetres)
    -33.2,      // z translation (millimetres)
     2.92,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.06,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.2,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2008_to_itrf1994_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::reference_frame = ITRF2008_i
Definition at line 792 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1994_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::reference_epoch = 2000.0
Definition at line 795 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1994_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1994_< T, U >::transformationParameters[14]
Initial value:
=
{
      4.8,
      2.6,
    -33.2,
     2.92,
     0.00,
     0.00,
    -0.06,
      0.1,
     -0.5,
     -3.2,
     0.09,
     0.00,
     0.00,
    -0.02
}
Definition at line 798 of file dnatransformationparameters.hpp.
{
      4.8,      // x translation (millimetres)
      2.6,      // y translation (millimetres)
    -33.2,      // z translation (millimetres)
     2.92,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.06,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.2,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2008_to_itrf1993_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::reference_frame = ITRF2008_i
Definition at line 833 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1993_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::reference_epoch = 2000.0
Definition at line 836 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1993_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1993_< T, U >::transformationParameters[14]
Initial value:
=
{
    -24.0,
      2.4,
    -38.6,
     3.41,
     1.71,
     1.48,
     0.30,
     -2.8,
     -0.1,
     -2.4,
     0.09,
     0.11,
     0.19,
    -0.07
}
Definition at line 839 of file dnatransformationparameters.hpp.
{
    -24.0,      // x translation (millimetres)
      2.4,      // y translation (millimetres)
    -38.6,      // z translation (millimetres)
     3.41,      // scale (ppb)
     1.71,      // x rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     1.48,      // y rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     0.30,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     -2.8,      // x translation rate (millimetres p/yr)
     -0.1,      // y translation rate (millimetres p/yr)
     -2.4,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.11,      // x rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
     0.19,      // y rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
    -0.07       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2008_to_itrf1992_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::reference_frame = ITRF2008_i
Definition at line 874 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1992_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::reference_epoch = 2000.0
Definition at line 877 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1992_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1992_< T, U >::transformationParameters[14]
Initial value:
=
{
     12.8,
      4.6,
    -41.2,
     2.21,
     0.00,
     0.00,
    -0.06,
      0.1,
     -0.5,
     -3.2,
     0.09,
     0.00,
     0.00,
    -0.02
}
Definition at line 880 of file dnatransformationparameters.hpp.
{
     12.8,      // x translation (millimetres)
      4.6,      // y translation (millimetres)
    -41.2,      // z translation (millimetres)
     2.21,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.06,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.2,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2008_to_itrf1991_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::reference_frame = ITRF2008_i
Definition at line 915 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1991_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::reference_epoch = 2000.0
Definition at line 918 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1991_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1991_< T, U >::transformationParameters[14]
Initial value:
=
{
     24.8,
     18.6,
    -47.2,
     3.61,
     0.00,
     0.00,
    -0.06,
      0.1,
     -0.5,
     -3.2,
     0.09,
     0.00,
     0.00,
    -0.02
}
Definition at line 921 of file dnatransformationparameters.hpp.
{
     24.8,      // x translation (millimetres)
     18.6,      // y translation (millimetres)
    -47.2,      // z translation (millimetres)
     3.61,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.06,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.2,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2008_to_itrf1990_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::reference_frame = ITRF2008_i
Definition at line 956 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1990_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::reference_epoch = 2000.0
Definition at line 959 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1990_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1990_< T, U >::transformationParameters[14]
Initial value:
=
{
     22.8,
     14.6,
    -63.2,
     3.91,
     0.00,
     0.00,
    -0.06,
      0.1,
     -0.5,
     -3.2,
     0.09,
     0.00,
     0.00,
    -0.02
}
Definition at line 962 of file dnatransformationparameters.hpp.
{
     22.8,      // x translation (millimetres)
     14.6,      // y translation (millimetres)
    -63.2,      // z translation (millimetres)
     3.91,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.06,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.2,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2008_to_itrf1989_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::reference_frame = ITRF2008_i
Definition at line 997 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1989_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::reference_epoch = 2000.0
Definition at line 1000 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1989_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1989_< T, U >::transformationParameters[14]
Initial value:
=
{
     27.8,
     38.6,
   -101.2,
     7.31,
     0.00,
     0.00,
    -0.06,
      0.1,
     -0.5,
     -3.2,
     0.09,
     0.00,
     0.00,
    -0.02
}
Definition at line 1003 of file dnatransformationparameters.hpp.
{
     27.8,      // x translation (millimetres)
     38.6,      // y translation (millimetres)
   -101.2,      // z translation (millimetres)
     7.31,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.06,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.2,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2008_to_itrf1988_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::reference_frame = ITRF2008_i
Definition at line 1038 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1988_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::reference_epoch = 2000.0
Definition at line 1041 of file dnatransformationparameters.hpp.
_itrf2008_to_itrf1988_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_itrf1988_< T, U >::transformationParameters[14]
Initial value:
=
{
     22.8,
      2.6,
   -125.2,
    10.41,
    -0.10,
     0.00,
    -0.06,
      0.1,
     -0.5,
     -3.2,
     0.09,
     0.00,
     0.00,
    -0.02
}
Definition at line 1044 of file dnatransformationparameters.hpp.
{
     22.8,      // x translation (millimetres)
      2.6,      // y translation (millimetres)
   -125.2,      // z translation (millimetres)
    10.41,      // scale (ppb)
    -0.10,      // x rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     0.00,      // y rotation (milli-arc-seconds)
    -0.06,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.2,      // z translation rate (millimetres p/yr)
     0.09,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf2008_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::reference_frame = ITRF2014_i
Definition at line 1085 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf2008_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::reference_epoch = 2010.0
Definition at line 1088 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf2008_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf2008_< T, U >::transformationParameters[14]
Initial value:
=
{
      1.6,
      1.9,
      2.4,
    -0.02,
     0.00,
     0.00,
     0.00,
      0.0,
      0.0,
     -0.1,
     0.03,
     0.00,
     0.00,
     0.00
}
Definition at line 1091 of file dnatransformationparameters.hpp.
{
      1.6,      // x translation (millimetres)
      1.9,      // y translation (millimetres)
      2.4,      // z translation (millimetres)
    -0.02,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.0,      // x translation rate (millimetres p/yr)
      0.0,      // y translation rate (millimetres p/yr)
     -0.1,      // z translation rate (millimetres p/yr)
     0.03,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2014_to_itrf2005_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::reference_frame = ITRF2014_i
Definition at line 1126 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf2005_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::reference_epoch = 2010.0
Definition at line 1129 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf2005_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf2005_< T, U >::transformationParameters[14]
Initial value:
=
{
      2.6,
      1.0,
     -2.3,
     0.92,
     0.00,
     0.00,
     0.00,
      0.3,
      0.0,
     -0.1,
     0.03,
     0.00,
     0.00,
     0.00
}
Definition at line 1132 of file dnatransformationparameters.hpp.
{
      2.6,      // x translation (millimetres)
      1.0,      // y translation (millimetres)
     -2.3,      // z translation (millimetres)
     0.92,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.3,      // x translation rate (millimetres p/yr)
      0.0,      // y translation rate (millimetres p/yr)
     -0.1,      // z translation rate (millimetres p/yr)
     0.03,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2014_to_itrf2000_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::reference_frame = ITRF2014_i
Definition at line 1167 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf2000_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::reference_epoch = 2010.0
Definition at line 1170 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf2000_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf2000_< T, U >::transformationParameters[14]
Initial value:
=
{
      0.7,
      1.2,
    -26.1,
     2.12,
     0.00,
     0.00,
     0.00,
      0.1,
      0.1,
     -1.9,
     0.11,
     0.00,
     0.00,
     0.00
}
Definition at line 1173 of file dnatransformationparameters.hpp.
{
      0.7,      // x translation (millimetres)
      1.2,      // y translation (millimetres)
    -26.1,      // z translation (millimetres)
     2.12,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.1,      // x translation rate (millimetres p/yr)
      0.1,      // y translation rate (millimetres p/yr)
     -1.9,      // z translation rate (millimetres p/yr)
     0.11,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2014_to_itrf1997_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::reference_frame = ITRF2014_i
Definition at line 1208 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1997_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::reference_epoch = 2010.0
Definition at line 1211 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1997_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1997_< T, U >::transformationParameters[14]
Initial value:
=
{
      7.4,
     -0.5,
    -62.8,
     3.80,
     0.00,
     0.00,
    -0.26,
      0.1,
     -0.5,
     -3.3,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1214 of file dnatransformationparameters.hpp.
{
      7.4,      // x translation (millimetres)
     -0.5,      // y translation (millimetres)
    -62.8,      // z translation (millimetres)
     3.80,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.26,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.3,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf1996_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::reference_frame = ITRF2014_i
Definition at line 1249 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1996_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::reference_epoch = 2010.0
Definition at line 1252 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1996_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1996_< T, U >::transformationParameters[14]
Initial value:
=
{
      7.4,
     -0.5,
    -62.8,
     3.80,
     0.00,
     0.00,
    -0.26,
      0.1,
     -0.5,
     -3.3,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1255 of file dnatransformationparameters.hpp.
{
      7.4,      // x translation (millimetres)
     -0.5,      // y translation (millimetres)
    -62.8,      // z translation (millimetres)
     3.80,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.26,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.3,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf1994_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::reference_frame = ITRF2014_i
Definition at line 1290 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1994_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::reference_epoch = 2010.0
Definition at line 1293 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1994_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1994_< T, U >::transformationParameters[14]
Initial value:
=
{
      7.4,
     -0.5,
    -62.8,
     3.80,
     0.00,
     0.00,
    -0.26,
      0.1,
     -0.5,
     -3.3,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1296 of file dnatransformationparameters.hpp.
{
      7.4,      // x translation (millimetres)
     -0.5,      // y translation (millimetres)
    -62.8,      // z translation (millimetres)
     3.80,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.26,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.3,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf1993_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::reference_frame = ITRF2014_i
Definition at line 1331 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1993_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::reference_epoch = 2010.0
Definition at line 1334 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1993_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1993_< T, U >::transformationParameters[14]
Initial value:
=
{
    -50.4,
      3.3,
    -60.2,
     4.29,
     2.81,
     3.38,
    -0.40,
     -2.8,
     -0.1,
     -2.5,
     0.12,
     0.11,
     0.19,
    -0.07
}
Definition at line 1337 of file dnatransformationparameters.hpp.
{
    -50.4,      // x translation (millimetres)
      3.3,      // y translation (millimetres)
    -60.2,      // z translation (millimetres)
     4.29,      // scale (ppb)
     2.81,      // x rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     3.38,      // y rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
    -0.40,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     -2.8,      // x translation rate (millimetres p/yr)
     -0.1,      // y translation rate (millimetres p/yr)
     -2.5,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.11,      // x rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
     0.19,      // y rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
    -0.07       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf1992_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::reference_frame = ITRF2014_i
Definition at line 1372 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1992_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::reference_epoch = 2010.0
Definition at line 1375 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1992_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1992_< T, U >::transformationParameters[14]
Initial value:
=
{
     15.4,
      1.5,
    -70.8,
     3.09,
     0.00,
     0.00,
    -0.26,
      0.1,
     -0.5,
     -3.3,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1378 of file dnatransformationparameters.hpp.
{
     15.4,      // x translation (millimetres)
      1.5,      // y translation (millimetres)
    -70.8,      // z translation (millimetres)
     3.09,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.26,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.3,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf1991_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::reference_frame = ITRF2014_i
Definition at line 1413 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1991_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::reference_epoch = 2010.0
Definition at line 1416 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1991_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1991_< T, U >::transformationParameters[14]
Initial value:
=
{
     27.4,
     15.5,
    -76.8,
     4.49,
     0.00,
     0.00,
    -0.26,
      0.1,
     -0.5,
     -3.3,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1419 of file dnatransformationparameters.hpp.
{
     27.4,      // x translation (millimetres)
     15.5,      // y translation (millimetres)
    -76.8,      // z translation (millimetres)
     4.49,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.26,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.3,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf1990_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::reference_frame = ITRF2014_i
Definition at line 1454 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1990_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::reference_epoch = 2010.0
Definition at line 1457 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1990_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1990_< T, U >::transformationParameters[14]
Initial value:
=
{
     25.4,
     11.5,
    -92.8,
     4.79,
     0.00,
     0.00,
    -0.26,
      0.1,
     -0.5,
     -3.3,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1460 of file dnatransformationparameters.hpp.
{
     25.4,      // x translation (millimetres)
     11.5,      // y translation (millimetres)
    -92.8,      // z translation (millimetres)
     4.79,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.26,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.5,      // y translation rate (millimetres p/yr)
     -3.3,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf1989_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::reference_frame = ITRF2014_i
Definition at line 1495 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1989_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::reference_epoch = 2010.0
Definition at line 1498 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1989_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1989_< T, U >::transformationParameters[14]
Initial value:
=
{
      30.4,
      35.5,
    -130.8,
      8.19,
      0.00,
      0.00,
     -0.26,
       0.1,
      -0.5,
      -3.3,
      0.12,
      0.00,
      0.00,
     -0.02
}
Definition at line 1501 of file dnatransformationparameters.hpp.
{
      30.4,     // x translation (millimetres)
      35.5,     // y translation (millimetres)
    -130.8,     // z translation (millimetres)
      8.19,     // scale (ppb)
      0.00,     // x rotation (milli-arc-seconds)
      0.00,     // y rotation (milli-arc-seconds)
     -0.26,     // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
       0.1,     // x translation rate (millimetres p/yr)
      -0.5,     // y translation rate (millimetres p/yr)
      -3.3,     // z translation rate (millimetres p/yr)
      0.12,     // scale rate (ppb p/yr)
      0.00,     // x rotation rate (milli-arc-seconds p/yr)
      0.00,     // y rotation rate (milli-arc-seconds p/yr)
     -0.02      // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_itrf1988_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_itrf1988_< T, U >::reference_frame = ITRF2014_i
Definition at line 1536 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1988_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1988_< T, U >::reference_epoch = 2010.0
Definition at line 1539 of file dnatransformationparameters.hpp.
_itrf2014_to_itrf1988_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_itrf1988_< T, U >::transformationParameters[14]
Initial value:
=
{
      25.4,
      -0.5,
    -154.8,
     11.29,
     -0.10,
      0.00,
     -0.26,
       0.1,
      -0.5,
      -3.3,
      0.12,
      0.00,
      0.00,
     -0.02
}
Definition at line 1542 of file dnatransformationparameters.hpp.
{
      25.4,     // x translation (millimetres)
      -0.5,     // y translation (millimetres)
    -154.8,     // z translation (millimetres)
     11.29,     // scale (ppb)
     -0.10,     // x rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.00,     // y rotation (milli-arc-seconds)
     -0.26,     // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
       0.1,     // x translation rate (millimetres p/yr)
      -0.5,     // y translation rate (millimetres p/yr)
      -3.3,     // z translation rate (millimetres p/yr)
      0.12,     // scale rate (ppb p/yr)
      0.00,     // x rotation rate (milli-arc-seconds p/yr)
      0.00,     // y rotation rate (milli-arc-seconds p/yr)
     -0.02      // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2014_to_gda2020_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::reference_frame = ITRF2014_i
Definition at line 1586 of file dnatransformationparameters.hpp.
_itrf2014_to_gda2020_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::reference_epoch = 2020.0
Definition at line 1589 of file dnatransformationparameters.hpp.
_itrf2014_to_gda2020_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_gda2020_< T, U >::transformationParameters[14]
Initial value:
=
{
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    1.50379,
    1.18346,
    1.20716
}
Definition at line 1592 of file dnatransformationparameters.hpp.
{
        0.0,    // x translation (millimetres)
        0.0,    // y translation (millimetres)
        0.0,    // z translation (millimetres)
        0.0,    // scale (ppb)
        0.0,    // x rotation (milli-arc-seconds)
        0.0,    // y rotation (milli-arc-seconds)
        0.0,    // z rotation (milli-arc-seconds)
        0.0,    // x translation rate (millimetres p/yr)
        0.0,    // y translation rate (millimetres p/yr)
        0.0,    // z translation rate (millimetres p/yr)
        0.0,    // scale rate (ppb p/yr)
    // Euler parameters:
    //  - pole latitude:  32.2447
    //  - pole longitude: 38.2022
    //  - rotation rate:   0.6285
    1.50379,    // x rotation rate (milli-arc-seconds p/yr)
    1.18346,    // y rotation rate (milli-arc-seconds p/yr)
    1.20716     // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2020_to_itrf2014_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::reference_frame = ITRF2020_i
Definition at line 1636 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf2014_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::reference_epoch = 2015.0
Definition at line 1639 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf2014_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf2014_< T, U >::transformationParameters[14]
Initial value:
=
{
     -1.4,
     -0.9,
      1.4,
    -0.42,
     0.00,
     0.00,
     0.00,
      0.0,
     -0.1,
      0.2,
     0.00,
     0.00,
     0.00,
     0.00
}
Definition at line 1642 of file dnatransformationparameters.hpp.
{
     -1.4,      // x translation (millimetres)
     -0.9,      // y translation (millimetres)
      1.4,      // z translation (millimetres)
    -0.42,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.0,      // x translation rate (millimetres p/yr)
     -0.1,      // y translation rate (millimetres p/yr)
      0.2,      // z translation rate (millimetres p/yr)
     0.00,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2020_to_itrf2008_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::reference_frame = ITRF2020_i
Definition at line 1677 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf2008_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::reference_epoch = 2015.0
Definition at line 1680 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf2008_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf2008_< T, U >::transformationParameters[14]
Initial value:
=
{
      0.2,
      1.0,
      3.3,
    -0.29,
     0.00,
     0.00,
     0.00,
      0.0,
     -0.1,
      0.1,
     0.03,
     0.00,
     0.00,
     0.00
}
Definition at line 1683 of file dnatransformationparameters.hpp.
{
      0.2,      // x translation (millimetres)
      1.0,      // y translation (millimetres)
      3.3,      // z translation (millimetres)
    -0.29,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.0,      // x translation rate (millimetres p/yr)
     -0.1,      // y translation rate (millimetres p/yr)
      0.1,      // z translation rate (millimetres p/yr)
     0.03,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2020_to_itrf2005_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::reference_frame = ITRF2020_i
Definition at line 1718 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf2005_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::reference_epoch = 2015.0
Definition at line 1721 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf2005_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf2005_< T, U >::transformationParameters[14]
Initial value:
=
{
      2.7,
      0.1,
     -1.4,
     0.65,
     0.00,
     0.00,
     0.00,
      0.3,
     -0.1,
      0.1,
     0.03,
     0.00,
     0.00,
     0.00
}
Definition at line 1724 of file dnatransformationparameters.hpp.
{
      2.7,      // x translation (millimetres)
      0.1,      // y translation (millimetres)
     -1.4,      // z translation (millimetres)
     0.65,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.3,      // x translation rate (millimetres p/yr)
     -0.1,      // y translation rate (millimetres p/yr)
      0.1,      // z translation rate (millimetres p/yr)
     0.03,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2020_to_itrf2000_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::reference_frame = ITRF2020_i
Definition at line 1759 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf2000_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::reference_epoch = 2015.0
Definition at line 1762 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf2000_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf2000_< T, U >::transformationParameters[14]
Initial value:
=
{
     -0.2,
      0.8,
    -34.2,
     2.25,
     0.00,
     0.00,
     0.00,
      0.1,
      0.0,
     -1.7,
     0.11,
     0.00,
     0.00,
     0.00
}
Definition at line 1765 of file dnatransformationparameters.hpp.
{
     -0.2,      // x translation (millimetres)
      0.8,      // y translation (millimetres)
    -34.2,      // z translation (millimetres)
     2.25,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
     0.00,      // z rotation (milli-arc-seconds)
      0.1,      // x translation rate (millimetres p/yr)
      0.0,      // y translation rate (millimetres p/yr)
     -1.7,      // z translation rate (millimetres p/yr)
     0.11,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
     0.00       // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2020_to_itrf1997_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::reference_frame = ITRF2020_i
Definition at line 1800 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1997_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::reference_epoch = 2015.0
Definition at line 1803 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1997_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1997_< T, U >::transformationParameters[14]
Initial value:
=
{
      6.5,
     -3.9,
    -77.9,
     3.98,
     0.00,
     0.00,
    -0.36,
      0.1,
     -0.6,
     -3.1,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1806 of file dnatransformationparameters.hpp.
{
      6.5,      // x translation (millimetres)
     -3.9,      // y translation (millimetres)
    -77.9,      // z translation (millimetres)
     3.98,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.36,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr)
     -3.1,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_itrf1996_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::reference_frame = ITRF2020_i
Definition at line 1841 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1996_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::reference_epoch = 2015.0
Definition at line 1844 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1996_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1996_< T, U >::transformationParameters[14]
Initial value:
=
{
      6.5,
     -3.9,
    -77.9,
     3.98,
     0.00,
     0.00,
    -0.36,
      0.1,
     -0.6,
     -3.1,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1847 of file dnatransformationparameters.hpp.
{
      6.5,      // x translation (millimetres)
     -3.9,      // y translation (millimetres)
    -77.9,      // z translation (millimetres)
     3.98,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.36,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr)
     -3.1,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_itrf1994_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::reference_frame = ITRF2020_i
Definition at line 1882 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1994_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::reference_epoch = 2015.0
Definition at line 1885 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1994_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1994_< T, U >::transformationParameters[14]
Initial value:
=
{
      6.5,
     -3.9,
    -77.9,
     3.98,
     0.00,
     0.00,
    -0.36,
      0.1,
     -0.6,
     -3.1,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1888 of file dnatransformationparameters.hpp.
{
      6.5,      // x translation (millimetres)
     -3.9,      // y translation (millimetres)
    -77.9,      // z translation (millimetres)
     3.98,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.36,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr)
     -3.1,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_itrf1993_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::reference_frame = ITRF2014_i
Definition at line 1923 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1993_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::reference_epoch = 2015.0
Definition at line 1926 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1993_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1993_< T, U >::transformationParameters[14]
Initial value:
=
{
    -65.8,
      1.9,
    -71.3,
     4.47,
     3.36,
     4.33,
    -0.75,
     -2.8,
     -0.2,
     -2.3,
     0.12,
     0.11,
     0.19,
    -0.07
}
Definition at line 1929 of file dnatransformationparameters.hpp.
{
    -65.8,      // x translation (millimetres)
      1.9,      // y translation (millimetres)
    -71.3,      // z translation (millimetres)
     4.47,      // scale (ppb)
     3.36,      // x rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     4.33,      // y rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
    -0.75,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
     -2.8,      // x translation rate (millimetres p/yr)
     -0.2,      // y translation rate (millimetres p/yr)
     -2.3,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.11,      // x rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
     0.19,      // y rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
    -0.07       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_itrf1992_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::reference_frame = ITRF2020_i
Definition at line 1964 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1992_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::reference_epoch = 2015.0
Definition at line 1967 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1992_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1992_< T, U >::transformationParameters[14]
Initial value:
=
{
     14.5,
     -1.9,
    -85.9,
     3.27,
     0.00,
     0.00,
    -0.36,
      0.1,
     -0.6,
     -3.1,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 1970 of file dnatransformationparameters.hpp.
{
     14.5,      // x translation (millimetres)
     -1.9,      // y translation (millimetres)
    -85.9,      // z translation (millimetres)
     3.27,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.36,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr)
     -3.1,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_itrf1991_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::reference_frame = ITRF2020_i
Definition at line 2005 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1991_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::reference_epoch = 2015.0
Definition at line 2008 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1991_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1991_< T, U >::transformationParameters[14]
Initial value:
=
{
     26.5,
     12.1,
    -91.9,
     4.67,
     0.00,
     0.00,
    -0.36,
      0.1,
     -0.6,
     -3.1,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 2011 of file dnatransformationparameters.hpp.
{
     26.5,      // x translation (millimetres)
     12.1,      // y translation (millimetres)
    -91.9,      // z translation (millimetres)
     4.67,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.36,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr)
     -3.1,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_itrf1990_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::reference_frame = ITRF2020_i
Definition at line 2046 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1990_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::reference_epoch = 2015.0
Definition at line 2049 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1990_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1990_< T, U >::transformationParameters[14]
Initial value:
=
{
     24.5,
      8.1,
   -107.9,
     4.97,
     0.00,
     0.00,
    -0.36,
      0.1,
     -0.6,
     -3.1,
     0.12,
     0.00,
     0.00,
    -0.02
}
Definition at line 2052 of file dnatransformationparameters.hpp.
{
     24.5,      // x translation (millimetres)
      8.1,      // y translation (millimetres)
   -107.9,      // z translation (millimetres)
     4.97,      // scale (ppb)
     0.00,      // x rotation (milli-arc-seconds)
     0.00,      // y rotation (milli-arc-seconds)
    -0.36,      // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.1,      // x translation rate (millimetres p/yr)
     -0.6,      // y translation rate (millimetres p/yr)
     -3.1,      // z translation rate (millimetres p/yr)
     0.12,      // scale rate (ppb p/yr)
     0.00,      // x rotation rate (milli-arc-seconds p/yr)
     0.00,      // y rotation rate (milli-arc-seconds p/yr)
    -0.02       // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_itrf1989_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::reference_frame = ITRF2020_i
Definition at line 2087 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1989_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::reference_epoch = 2015.0
Definition at line 2090 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1989_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1989_< T, U >::transformationParameters[14]
Initial value:
=
{
      29.5,
      32.1,
    -145.9,
      8.37,
      0.00,
      0.00,
     -0.36,
       0.1,
      -0.6,
      -3.1,
      0.12,
      0.00,
      0.00,
     -0.02
}
Definition at line 2093 of file dnatransformationparameters.hpp.
{
      29.5,     // x translation (millimetres)
      32.1,     // y translation (millimetres)
    -145.9,     // z translation (millimetres)
      8.37,     // scale (ppb)
      0.00,     // x rotation (milli-arc-seconds)
      0.00,     // y rotation (milli-arc-seconds)
     -0.36,     // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
       0.1,     // x translation rate (millimetres p/yr)
      -0.6,     // y translation rate (millimetres p/yr)
      -3.1,     // z translation rate (millimetres p/yr)
      0.12,     // scale rate (ppb p/yr)
      0.00,     // x rotation rate (milli-arc-seconds p/yr)
      0.00,     // y rotation rate (milli-arc-seconds p/yr)
     -0.02      // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_itrf1988_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::reference_frame = ITRF2020_i
Definition at line 2128 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1988_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::reference_epoch = 2015.0
Definition at line 2131 of file dnatransformationparameters.hpp.
_itrf2020_to_itrf1988_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_itrf1988_< T, U >::transformationParameters[14]
Initial value:
=
{
      24.5,
      -3.9,
    -169.9,
     11.47,
     -0.10,
      0.00,
     -0.36,
       0.1,
      -0.6,
      -3.1,
      0.12,
      0.00,
      0.00,
     -0.02
}
Definition at line 2134 of file dnatransformationparameters.hpp.
{
      24.5,     // x translation (millimetres)
      -3.9,     // y translation (millimetres)
    -169.9,     // z translation (millimetres)
     11.47,     // scale (ppb)
     -0.10,     // x rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
      0.00,     // y rotation (milli-arc-seconds)
     -0.36,     // z rotation (milli-arc-seconds) - REVERSED (SEE SPECIAL NOTE ABOVE)
       0.1,     // x translation rate (millimetres p/yr)
      -0.6,     // y translation rate (millimetres p/yr)
      -3.1,     // z translation rate (millimetres p/yr)
      0.12,     // scale rate (ppb p/yr)
      0.00,     // x rotation rate (milli-arc-seconds p/yr)
      0.00,     // y rotation rate (milli-arc-seconds p/yr)
     -0.02      // z rotation rate (milli-arc-seconds p/yr) - REVERSED (SEE SPECIAL NOTE ABOVE)
};
_itrf2020_to_gda2020_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::reference_frame = ITRF2020_i
Definition at line 2179 of file dnatransformationparameters.hpp.
_itrf2020_to_gda2020_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::reference_epoch = 2020.0
Definition at line 2182 of file dnatransformationparameters.hpp.
_itrf2020_to_gda2020_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2020_to_gda2020_< T, U >::transformationParameters[14]
Initial value:
=
{
       -1.4,
       -1.4,
        2.4,
      -0.42,
        0.0,
        0.0,
        0.0,
        0.0,
       -0.1,
        0.2,
        0.0,
        1.50379,
        1.18346,
        1.20716
}
Definition at line 2185 of file dnatransformationparameters.hpp.
{
       -1.4,    // x translation (millimetres)
       -1.4,    // y translation (millimetres)
        2.4,    // z translation (millimetres)
      -0.42,    // scale (ppb)
        0.0,    // x rotation (milli-arc-seconds)
        0.0,    // y rotation (milli-arc-seconds)
        0.0,    // z rotation (milli-arc-seconds)
        // ITRF2020 translation rates:
        0.0,    // x translation rate (millimetres p/yr)
       -0.1,    // y translation rate (millimetres p/yr)
        0.2,    // z translation rate (millimetres p/yr)
        0.0,    // scale rate (ppb p/yr)
        // AU PMM rotation rates:
        1.50379,    // x rotation rate (milli-arc-seconds p/yr)
        1.18346,    // y rotation rate (milli-arc-seconds p/yr)
        1.20716     // z rotation rate (milli-arc-seconds p/yr)
};
_itrf1996_to_gda2020_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::reference_frame = GDA2020_i
Definition at line 2242 of file dnatransformationparameters.hpp.
_itrf1996_to_gda2020_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::reference_epoch = 2020.0
Definition at line 2245 of file dnatransformationparameters.hpp.
_itrf1996_to_gda2020_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf1996_to_gda2020_< T, U >::transformationParameters[14]
Initial value:
=
{
    -480.710,
      75.160,
     574.710,
      6.9950,
     10.2995,
     21.7458,
      9.8292,
     -21.800,
       4.710,
      26.270,
      0.3880,
      2.0203,
      2.1735,
      1.6290
}
Definition at line 2248 of file dnatransformationparameters.hpp.
{
    -480.710,   // x translation (millimetres)
      75.160,   // y translation (millimetres)
     574.710,   // z translation (millimetres)
      6.9950,   // scale (ppb)
     10.2995,   // x rotation (milli-arc-seconds)
     21.7458,   // y rotation (milli-arc-seconds)
      9.8292,   // z rotation (milli-arc-seconds)
     -21.800,   // x translation rate (millimetres p/yr)
       4.710,   // y translation rate (millimetres p/yr)
      26.270,   // z translation rate (millimetres p/yr)
      0.3880,   // scale rate (ppb p/yr)
      2.0203,   // x rotation rate (milli-arc-seconds p/yr)
      2.1735,   // y rotation rate (milli-arc-seconds p/yr)
      1.6290    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf1997_to_gda2020_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::reference_frame = GDA2020_i
Definition at line 2283 of file dnatransformationparameters.hpp.
_itrf1997_to_gda2020_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::reference_epoch = 2020.0
Definition at line 2286 of file dnatransformationparameters.hpp.
_itrf1997_to_gda2020_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf1997_to_gda2020_< T, U >::transformationParameters[14]
Initial value:
=
{
    -176.680,
     -29.130,
     226.990,
     -3.1170,
      1.3427,
      6.1880,
      3.9809,
      -8.600,
       0.360,
      11.250,
      0.0070,
      1.6394,
      1.5198,
      1.3801
}
Definition at line 2289 of file dnatransformationparameters.hpp.
{
    -176.680,   // x translation (millimetres)
     -29.130,   // y translation (millimetres)
     226.990,   // z translation (millimetres)
     -3.1170,   // scale (ppb)
      1.3427,   // x rotation (milli-arc-seconds)
      6.1880,   // y rotation (milli-arc-seconds)
      3.9809,   // z rotation (milli-arc-seconds)
      -8.600,   // x translation rate (millimetres p/yr)
       0.360,   // y translation rate (millimetres p/yr)
      11.250,   // z translation rate (millimetres p/yr)
      0.0070,   // scale rate (ppb p/yr)
      1.6394,   // x rotation rate (milli-arc-seconds p/yr)
      1.5198,   // y rotation rate (milli-arc-seconds p/yr)
      1.3801    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2000_to_gda2020_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::reference_frame = GDA2020_i
Definition at line 2324 of file dnatransformationparameters.hpp.
_itrf2000_to_gda2020_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::reference_epoch = 2020.0
Definition at line 2327 of file dnatransformationparameters.hpp.
_itrf2000_to_gda2020_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_gda2020_< T, U >::transformationParameters[14]
Initial value:
=
{
    -105.520,
      51.580,
     231.680,
      3.5500,
      4.2175,
      6.3941,
      0.8617,
      -4.660,
       3.550,
      11.240,
      0.2490,
      1.7454,
      1.4868,
      1.2240
}
Definition at line 2330 of file dnatransformationparameters.hpp.
{
    -105.520,   // x translation (millimetres)
      51.580,   // y translation (millimetres)
     231.680,   // z translation (millimetres)
      3.5500,   // scale (ppb)
      4.2175,   // x rotation (milli-arc-seconds)
      6.3941,   // y rotation (milli-arc-seconds)
      0.8617,   // z rotation (milli-arc-seconds)
      -4.660,   // x translation rate (millimetres p/yr)
       3.550,   // y translation rate (millimetres p/yr)
      11.240,   // z translation rate (millimetres p/yr)
      0.2490,   // scale rate (ppb p/yr)
      1.7454,   // x rotation rate (milli-arc-seconds p/yr)
      1.4868,   // y rotation rate (milli-arc-seconds p/yr)
      1.2240    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2005_to_gda2020_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::reference_frame = GDA2020_i
Definition at line 2365 of file dnatransformationparameters.hpp.
_itrf2005_to_gda2020_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::reference_epoch = 2020.0
Definition at line 2368 of file dnatransformationparameters.hpp.
_itrf2005_to_gda2020_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2005_to_gda2020_< T, U >::transformationParameters[14]
Initial value:
=
{
      40.320,
     -33.850,
     -16.720,
      4.2860,
     -1.2893,
     -0.8492,
     -0.3342,
       2.250,
      -0.620,
      -0.560,
      0.2940,
      1.4707,
      1.1443,
      1.1701
}
Definition at line 2371 of file dnatransformationparameters.hpp.
{
      40.320,   // x translation (millimetres)
     -33.850,   // y translation (millimetres)
     -16.720,   // z translation (millimetres)
      4.2860,   // scale (ppb)
     -1.2893,   // x rotation (milli-arc-seconds)
     -0.8492,   // y rotation (milli-arc-seconds)
     -0.3342,   // z rotation (milli-arc-seconds)
       2.250,   // x translation rate (millimetres p/yr)
      -0.620,   // y translation rate (millimetres p/yr)
      -0.560,   // z translation rate (millimetres p/yr)
      0.2940,   // scale rate (ppb p/yr)
      1.4707,   // x rotation rate (milli-arc-seconds p/yr)
      1.1443,   // y rotation rate (milli-arc-seconds p/yr)
      1.1701    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2008_to_gda2020_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::reference_frame = GDA2020_i
Definition at line 2406 of file dnatransformationparameters.hpp.
_itrf2008_to_gda2020_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::reference_epoch = 2020.0
Definition at line 2409 of file dnatransformationparameters.hpp.
_itrf2008_to_gda2020_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_gda2020_< T, U >::transformationParameters[14]
Initial value:
=
{
      13.790,
       4.550,
      15.220,
      2.5500,
      0.2808,
      0.2677,
     -0.4638,
       1.420,
       1.340,
       0.900,
      0.1090,
      1.5461,
      1.1820,
      1.1551
}
Definition at line 2412 of file dnatransformationparameters.hpp.
{
      13.790,   // x translation (millimetres)
       4.550,   // y translation (millimetres)
      15.220,   // z translation (millimetres)
      2.5500,   // scale (ppb)
      0.2808,   // x rotation (milli-arc-seconds)
      0.2677,   // y rotation (milli-arc-seconds)
     -0.4638,   // z rotation (milli-arc-seconds)
       1.420,   // x translation rate (millimetres p/yr)
       1.340,   // y translation rate (millimetres p/yr)
       0.900,   // z translation rate (millimetres p/yr)
      0.1090,   // scale rate (ppb p/yr)
      1.5461,   // x rotation rate (milli-arc-seconds p/yr)
      1.1820,   // y rotation rate (milli-arc-seconds p/yr)
      1.1551    // z rotation rate (milli-arc-seconds p/yr)
};
_gda94_to_gda2020_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::reference_frame = GDA2020_i
Definition at line 2458 of file dnatransformationparameters.hpp.
_gda94_to_gda2020_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::reference_epoch = 2020.0
Definition at line 2461 of file dnatransformationparameters.hpp.
_gda94_to_gda2020_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_gda94_to_gda2020_< T, U >::transformationParameters[14]
Initial value:
=
{
       61.55,
      -10.87,
      -40.19,
      -9.994,
    -39.4924,
    -32.7221,
    -32.8979,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0
}
Definition at line 2464 of file dnatransformationparameters.hpp.
{
       61.55,   // x translation (millimetres)
      -10.87,   // y translation (millimetres)
      -40.19,   // z translation (millimetres)
      -9.994,   // scale (ppb)
    -39.4924,   // x rotation (milli-arc-seconds)
    -32.7221,   // y rotation (milli-arc-seconds)
    -32.8979,   // z rotation (milli-arc-seconds)
         0.0,   // x translation rate (millimetres p/yr)
         0.0,   // y translation rate (millimetres p/yr)
         0.0,   // z translation rate (millimetres p/yr)
         0.0,   // scale rate (ppb p/yr)
         0.0,   // x rotation rate (milli-arc-seconds p/yr)
         0.0,   // y rotation rate (milli-arc-seconds p/yr)
         0.0    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2014_to_gda94_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::reference_frame = GDA94_i
Definition at line 2501 of file dnatransformationparameters.hpp.
_itrf2014_to_gda94_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::reference_epoch = 2020.0
Definition at line 2504 of file dnatransformationparameters.hpp.
_itrf2014_to_gda94_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2014_to_gda94_< T, U >::transformationParameters[14]
Initial value:
=
{
      -61.55,
       10.87,
       40.19,
       9.994,
     39.4924,
     32.7221,
     32.8979,
         0.0,
         0.0,
         0.0,
         0.0,
     1.50379,
     1.18346,
     1.20716
}
Definition at line 2507 of file dnatransformationparameters.hpp.
{
      -61.55,   // x translation (millimetres)
       10.87,   // y translation (millimetres)
       40.19,   // z translation (millimetres)
       9.994,   // scale (ppb)
     39.4924,   // x rotation (milli-arc-seconds)
     32.7221,   // y rotation (milli-arc-seconds)
     32.8979,   // z rotation (milli-arc-seconds)
         0.0,   // x translation rate (millimetres p/yr)
         0.0,   // y translation rate (millimetres p/yr)
         0.0,   // z translation rate (millimetres p/yr)
         0.0,   // scale rate (ppb p/yr)
     1.50379,   // x rotation rate (milli-arc-seconds p/yr)
     1.18346,   // y rotation rate (milli-arc-seconds p/yr)
     1.20716    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2008_to_gda94_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::reference_frame = GDA94_i
Definition at line 2548 of file dnatransformationparameters.hpp.
_itrf2008_to_gda94_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::reference_epoch = 1994.0
Definition at line 2551 of file dnatransformationparameters.hpp.
_itrf2008_to_gda94_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2008_to_gda94_< T, U >::transformationParameters[14]
Initial value:
=
{
      -84.68,
      -19.42,
       32.01,
      9.7100,
     -0.4254,
      2.2578,
      2.4015,
       1.420,
       1.340,
       0.900,
      0.1090,
      1.5461,
      1.1820,
      1.1551
}
Definition at line 2554 of file dnatransformationparameters.hpp.
{
      -84.68,   // x translation (millimetres)
      -19.42,   // y translation (millimetres)
       32.01,   // z translation (millimetres)
      9.7100,   // scale (ppb)
     -0.4254,   // x rotation (milli-arc-seconds)
      2.2578,   // y rotation (milli-arc-seconds)
      2.4015,   // z rotation (milli-arc-seconds)
       1.420,   // x translation rate (millimetres p/yr)
       1.340,   // y translation rate (millimetres p/yr)
       0.900,   // z translation rate (millimetres p/yr)
      0.1090,   // scale rate (ppb p/yr)
      1.5461,   // x rotation rate (milli-arc-seconds p/yr)
      1.1820,   // y rotation rate (milli-arc-seconds p/yr)
      1.1551    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2005_to_gda94_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::reference_frame = GDA94_i
Definition at line 2589 of file dnatransformationparameters.hpp.
_itrf2005_to_gda94_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::reference_epoch = 1994.0
Definition at line 2592 of file dnatransformationparameters.hpp.
_itrf2005_to_gda94_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2005_to_gda94_< T, U >::transformationParameters[14]
Initial value:
=
{
      -79.73,
       -6.86,
       38.03,
      6.6360,
     -0.0351,
      2.1211,
      2.1411,
        2.25,
       -0.62,
       -0.56,
      0.2940,
      1.4707,
      1.1443,
      1.1701
}
Definition at line 2595 of file dnatransformationparameters.hpp.
{
      -79.73,   // x translation (millimetres)
       -6.86,   // y translation (millimetres)
       38.03,   // z translation (millimetres)
      6.6360,   // scale (ppb)
     -0.0351,   // x rotation (milli-arc-seconds)
      2.1211,   // y rotation (milli-arc-seconds)
      2.1411,   // z rotation (milli-arc-seconds)
        2.25,   // x translation rate (millimetres p/yr)
       -0.62,   // y translation rate (millimetres p/yr)
       -0.56,   // z translation rate (millimetres p/yr)
      0.2940,   // scale rate (ppb p/yr)
      1.4707,   // x rotation rate (milli-arc-seconds p/yr)
      1.1443,   // y rotation rate (milli-arc-seconds p/yr)
      1.1701    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf2000_to_gda94_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::reference_frame = GDA94_i
Definition at line 2630 of file dnatransformationparameters.hpp.
_itrf2000_to_gda94_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::reference_epoch = 1994.0
Definition at line 2633 of file dnatransformationparameters.hpp.
_itrf2000_to_gda94_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf2000_to_gda94_< T, U >::transformationParameters[14]
Initial value:
=
{
      -45.91,
      -29.85,
      -20.37,
      7.0700,
     -1.6705,
      0.4594,
      1.9356,
       -4.66,
        3.55,
       11.24,
      0.2490,
      1.7454,
      1.4868,
      1.2240
}
Definition at line 2636 of file dnatransformationparameters.hpp.
{
      -45.91,   // x translation (millimetres)
      -29.85,   // y translation (millimetres)
      -20.37,   // z translation (millimetres)
      7.0700,   // scale (ppb)
     -1.6705,   // x rotation (milli-arc-seconds)
      0.4594,   // y rotation (milli-arc-seconds)
      1.9356,   // z rotation (milli-arc-seconds)
       -4.66,   // x translation rate (millimetres p/yr)
        3.55,   // y translation rate (millimetres p/yr)
       11.24,   // z translation rate (millimetres p/yr)
      0.2490,   // scale rate (ppb p/yr)
      1.7454,   // x rotation rate (milli-arc-seconds p/yr)
      1.4868,   // y rotation rate (milli-arc-seconds p/yr)
      1.2240    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf1997_to_gda94_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::reference_frame = GDA94_i
Definition at line 2671 of file dnatransformationparameters.hpp.
_itrf1997_to_gda94_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::reference_epoch = 1994.0
Definition at line 2674 of file dnatransformationparameters.hpp.
_itrf1997_to_gda94_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf1997_to_gda94_< T, U >::transformationParameters[14]
Initial value:
=
{
      -14.63,
      -27.62,
      -25.32,
      6.6950,
     -1.7893,
     -0.6047,
      0.9962,
       -8.60,
        0.36,
       11.25,
      0.0070,
      1.6394,
      1.5198,
      1.3801
}
Definition at line 2677 of file dnatransformationparameters.hpp.
{
      -14.63,   // x translation (millimetres)
      -27.62,   // y translation (millimetres)
      -25.32,   // z translation (millimetres)
      6.6950,   // scale (ppb)
     -1.7893,   // x rotation (milli-arc-seconds)
     -0.6047,   // y rotation (milli-arc-seconds)
      0.9962,   // z rotation (milli-arc-seconds)
       -8.60,   // x translation rate (millimetres p/yr)
        0.36,   // y translation rate (millimetres p/yr)
       11.25,   // z translation rate (millimetres p/yr)
      0.0070,   // scale rate (ppb p/yr)
      1.6394,   // x rotation rate (milli-arc-seconds p/yr)
      1.5198,   // y rotation rate (milli-arc-seconds p/yr)
      1.3801    // z rotation rate (milli-arc-seconds p/yr)
};
_itrf1996_to_gda94_< T, U >::reference_frame
template<class T, class U> const U dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::reference_frame = GDA94_i
Definition at line 2712 of file dnatransformationparameters.hpp.
_itrf1996_to_gda94_< T, U >::reference_epoch
template<class T, class U> const T dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::reference_epoch = 1994.0
Definition at line 2715 of file dnatransformationparameters.hpp.
_itrf1996_to_gda94_< T, U >::transformationParameters
template<class T, class U> const T dynadjust::datum_parameters::_itrf1996_to_gda94_< T, U >::transformationParameters[14]
Initial value:
=
{
       24.54,
      -36.43,
      -68.12,
      6.9010,
     -2.7359,
     -2.0431,
      0.3731,
      -21.80,
        4.71,
       26.27,
      0.3880,
      2.0203,
      2.1735,
      1.6290
}
Definition at line 2718 of file dnatransformationparameters.hpp.
{
       24.54,   // x translation (millimetres)
      -36.43,   // y translation (millimetres)
      -68.12,   // z translation (millimetres)
      6.9010,   // scale (ppb)
     -2.7359,   // x rotation (milli-arc-seconds)
     -2.0431,   // y rotation (milli-arc-seconds)
      0.3731,   // z rotation (milli-arc-seconds)
      -21.80,   // x translation rate (millimetres p/yr)
        4.71,   // y translation rate (millimetres p/yr)
       26.27,   // z translation rate (millimetres p/yr)
      0.3880,   // scale rate (ppb p/yr)
      2.0203,   // x rotation rate (milli-arc-seconds p/yr)
      2.1735,   // y rotation rate (milli-arc-seconds p/yr)
      1.6290    // z rotation rate (milli-arc-seconds p/yr)
};