DynAdjust: dynadjust::epsg Namespace Reference
dynadjust::epsg Namespace Reference
Classes
struct epsg_datum
struct epsg_geogcs
struct epsg_primem
struct epsg_projcs
struct epsg_projection
struct epsg_spheroid
struct epsg_tparams
Typedefs
typedef std::pair< std::string, UINT32 > epsg_string_uint32
typedef std::pair< UINT32, std::string > epsg_uint32_string
typedef std::pair< std::string, double > epsg_unit
typedef std::pair< std::string, std::string > epsg_axis
typedef std::pair< std::string, std::string > epsg_authority
typedef std::pair< std::string, double > epsg_parameter
Functions
template<typename U, typename S>
U epsgCodeFromName (const S &datumName)
template<typename S>
S epsgStringFromName (const S &datumName)
template<typename U>
bool isEpsgDatumStatic (const U &epsgCode)
template<typename U>
void spheroidFromEpsgCode (const U &epsgCode, epsg_spheroid &ellipsoid)
template<typename U>
std::string referenceepochFromEpsgCode (const U &epsgCode)
template<typename S>
S referenceepochFromEpsgString (const S &epsgString)
template<typename S, typename U>
S datumFromEpsgCode (const U &epsgCode)
template<typename S>
S datumFromEpsgString (const S &epsgCode)
template<typename U>
bool validateEpsgCode (const U &epsgCode)
template<typename U>
bool isEpsgWGS84Ensemble (const U &epsgCode)
template<typename U>
bool isEpsgStringWGS84Ensemble (const U &epsgString)
template<typename U>
bool isEpsgWGS84 (const U &epsgCode)
template<typename U>
bool isEpsgStringWGS84 (const U &epsgString)
Typedef Documentation
epsg_string_uint32
typedef std::pair<std::string, UINT32> dynadjust::epsg::epsg_string_uint32
Definition at line 49 of file dnaepsg.hpp.
epsg_uint32_string
typedef std::pair<UINT32, std::string> dynadjust::epsg::epsg_uint32_string
Definition at line 50 of file dnaepsg.hpp.
epsg_unit
typedef std::pair<std::string, double> dynadjust::epsg::epsg_unit
Definition at line 53 of file dnaepsg.hpp.
epsg_axis
typedef std::pair<std::string, std::string> dynadjust::epsg::epsg_axis
Definition at line 54 of file dnaepsg.hpp.
epsg_authority
typedef std::pair<std::string, std::string> dynadjust::epsg::epsg_authority
Definition at line 55 of file dnaepsg.hpp.
epsg_parameter
typedef std::pair<std::string, double> dynadjust::epsg::epsg_parameter
Definition at line 56 of file dnaepsg.hpp.
Function Documentation
epsgCodeFromName()
template<typename U, typename S> U dynadjust::epsg::epsgCodeFromName (const S & datumName)
Definition at line 120 of file dnaepsg.hpp.
{
    if (boost::iequals(datumName, AGD66_s))
        return AGD66_i;
    if (boost::iequals(datumName, AGD84_s))
        return AGD84_i;
    if (boost::iequals(datumName, GDA94_s))
        return GDA94_i_xyz;
    if (boost::iequals(datumName, GDA2020_s))
        return GDA2020_i_xyz;
    // ITRF
    if (boost::iequals(datumName, ITRF2020_s))
        return ITRF2020_i_xyz;
    if (boost::iequals(datumName, ITRF2014_s))
        return ITRF2014_i_xyz;
    if (boost::iequals(datumName, ITRF2008_s))
        return ITRF2008_i_xyz;
    if (boost::iequals(datumName, ITRF2005_s))
        return ITRF2005_i_xyz;
    if (boost::iequals(datumName, ITRF2000_s))
        return ITRF2000_i_xyz;
    if (boost::iequals(datumName, ITRF1997_s) || boost::iequals(datumName, ITRF1997_s_brief))
        return ITRF1997_i_xyz;
    if (boost::iequals(datumName, ITRF1996_s) || boost::iequals(datumName, ITRF1996_s_brief))
        return ITRF1996_i_xyz;
    if (boost::iequals(datumName, ITRF1994_s) || boost::iequals(datumName, ITRF1994_s_brief))
        return ITRF1994_i_xyz;
    if (boost::iequals(datumName, ITRF1993_s) || boost::iequals(datumName, ITRF1993_s_brief))
        return ITRF1993_i_xyz;
    if (boost::iequals(datumName, ITRF1992_s) || boost::iequals(datumName, ITRF1992_s_brief))
        return ITRF1992_i_xyz;
    if (boost::iequals(datumName, ITRF1991_s) || boost::iequals(datumName, ITRF1991_s_brief))
        return ITRF1991_i_xyz;
    if (boost::iequals(datumName, ITRF1990_s) || boost::iequals(datumName, ITRF1990_s_brief))
        return ITRF1990_i_xyz;
    if (boost::iequals(datumName, ITRF1989_s) || boost::iequals(datumName, ITRF1989_s_brief))
        return ITRF1989_i_xyz;
    if (boost::iequals(datumName, ITRF1988_s) || boost::iequals(datumName, ITRF1988_s_brief))
        return ITRF1988_i_xyz;
    // WGS84
    if (boost::iequals(datumName, WGS84_s) ||
        boost::iequals(datumName, WGS84_ensemble_s) ||
        boost::iequals(datumName, WGS84_alias_s))
        return WGS84_i_xyz;
    if (boost::iequals(datumName, WGS84_transit_s) ||
        boost::iequals(datumName, WGS84_transit_alias_s))
        return WGS84_transit_i_xyz;
    if (boost::iequals(datumName, WGS84_G730_s) ||
        boost::iequals(datumName, WGS84_G730_alias_s))
        return WGS84_G730_i_xyz;
    if (boost::iequals(datumName, WGS84_G873_s) ||
        boost::iequals(datumName, WGS84_G873_alias_s))
        return WGS84_G873_i_xyz;
    if (boost::iequals(datumName, WGS84_G1150_s) ||
        boost::iequals(datumName, WGS84_G1150_alias_s))
        return WGS84_G1150_i_xyz;
    if (boost::iequals(datumName, WGS84_G1674_s) ||
        boost::iequals(datumName, WGS84_G1674_alias_s))
        return WGS84_G1674_i_xyz;
    if (boost::iequals(datumName, WGS84_G1762_s) ||
        boost::iequals(datumName, WGS84_G1762_alias_s))
        return WGS84_G1762_i_xyz;
    if (boost::iequals(datumName, WGS84_G2139_s) ||
        boost::iequals(datumName, WGS84_G2139_alias_s))
        return WGS84_G2139_i_xyz;
    std::stringstream ss;
    ss << "  epsgCodeFromName: '" << datumName << "' is not a supported reference frame label." << std::endl;
    throw boost::enable_current_exception(std::runtime_error(ss.str()));
}
References AGD66_i, AGD66_s, AGD84_i, AGD84_s, GDA2020_i_xyz, GDA2020_s, GDA94_i_xyz, GDA94_s, ITRF1988_i_xyz, ITRF1988_s, ITRF1988_s_brief, ITRF1989_i_xyz, ITRF1989_s, ITRF1989_s_brief, ITRF1990_i_xyz, ITRF1990_s, ITRF1990_s_brief, ITRF1991_i_xyz, ITRF1991_s, ITRF1991_s_brief, ITRF1992_i_xyz, ITRF1992_s, ITRF1992_s_brief, ITRF1993_i_xyz, ITRF1993_s, ITRF1993_s_brief, ITRF1994_i_xyz, ITRF1994_s, ITRF1994_s_brief, ITRF1996_i_xyz, ITRF1996_s, ITRF1996_s_brief, ITRF1997_i_xyz, ITRF1997_s, ITRF1997_s_brief, ITRF2000_i_xyz, ITRF2000_s, ITRF2005_i_xyz, ITRF2005_s, ITRF2008_i_xyz, ITRF2008_s, ITRF2014_i_xyz, ITRF2014_s, ITRF2020_i_xyz, ITRF2020_s, WGS84_alias_s, WGS84_ensemble_s, WGS84_G1150_alias_s, WGS84_G1150_i_xyz, WGS84_G1150_s, WGS84_G1674_alias_s, WGS84_G1674_i_xyz, WGS84_G1674_s, WGS84_G1762_alias_s, WGS84_G1762_i_xyz, WGS84_G1762_s, WGS84_G2139_alias_s, WGS84_G2139_i_xyz, WGS84_G2139_s, WGS84_G730_alias_s, WGS84_G730_i_xyz, WGS84_G730_s, WGS84_G873_alias_s, WGS84_G873_i_xyz, WGS84_G873_s, WGS84_i_xyz, WGS84_s, WGS84_transit_alias_s, WGS84_transit_i_xyz, and WGS84_transit_s.
Referenced by epsgStringFromName(), dynadjust::referenceframe::dna_reftran::JoinTransformationParameters(), main(), ParseCommandLineOptions(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRGPSBaselines(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRGPSPoints(), PrintOutputFileHeaderInfo(), dynadjust::datum_parameters::CDnaDatum::SetDatumFromName(), and dynadjust::referenceframe::dna_reftran::TransformFrames_PlateMotionModel().
epsgStringFromName()
template<typename S> S dynadjust::epsg::epsgStringFromName (const S & datumName)
Definition at line 192 of file dnaepsg.hpp.
{
    // Get code and return corresponding string
    // epsgCodeFromname throws on bad datumName
    UINT32 epsgCode = epsgCodeFromName<UINT32, S>(datumName);
    // get string form of epsg code
    // Reduce all forms(2D / 3D geographic and geocentric) to geocentric
    switch (epsgCode)
    {
    case AGD66_i:
        return AGD66_c;
    case AGD84_i:
        return AGD84_c;
    case GDA94_i:
    case GDA94_i_2d:
    case GDA94_i_xyz:
        return GDA94_c_xyz;
    case GDA2020_i:
    case GDA2020_i_2d:
    case GDA2020_i_xyz:
        return GDA2020_c_xyz;
    // ITRF
    case ITRF2020_i:
    case ITRF2020_i_xyz:
        return ITRF2020_c;
    case ITRF2014_i:
    case ITRF2014_i_xyz:
        return ITRF2014_c;
    case ITRF2008_i:
    case ITRF2008_i_xyz:
        return ITRF2008_c;
    case ITRF2005_i:
    case ITRF2005_i_xyz:
        return ITRF2005_c;
    case ITRF2000_i:
    case ITRF2000_i_xyz:
        return ITRF2000_c;
    case ITRF1997_i:
    case ITRF1997_i_xyz:
        return ITRF1997_c;
    case ITRF1996_i:
    case ITRF1996_i_xyz:
        return ITRF1996_c;
    case ITRF1994_i:
    case ITRF1994_i_xyz:
        return ITRF1994_c;
    case ITRF1993_i:
    case ITRF1993_i_xyz:
        return ITRF1993_c;
    case ITRF1992_i:
    case ITRF1992_i_xyz:
        return ITRF1992_c;
    case ITRF1991_i:
    case ITRF1991_i_xyz:
        return ITRF1991_c;
    case ITRF1990_i:
    case ITRF1990_i_xyz:
        return ITRF1990_c;
    case ITRF1989_i:
    case ITRF1989_i_xyz:
        return ITRF1989_c;
    case ITRF1988_i:
    case ITRF1988_i_xyz:
        return ITRF1988_c;
    // WGS84
    case WGS84_i:
    case WGS84_i_xyz:
    case WGS84_ensemble_i:
        return WGS84_c;
    case WGS84_transit_i:
    case WGS84_transit_i_xyz:
        return WGS84_transit_c;
    case WGS84_G730_i:
    case WGS84_G730_i_xyz:
        return WGS84_G730_c;
    case WGS84_G873_i:
    case WGS84_G873_i_xyz:
        return WGS84_G873_c;
    case WGS84_G1150_i:
    case WGS84_G1150_i_xyz:
        return WGS84_G1150_c;
    case WGS84_G1674_i:
    case WGS84_G1674_i_xyz:
        return WGS84_G1674_c;
    case WGS84_G1762_i:
    case WGS84_G1762_i_xyz:
        return WGS84_G1762_c;
    case WGS84_G2139_i:
    case WGS84_G2139_i_xyz:
        return WGS84_G2139_c;
    }
    std::stringstream ss;
    ss << "  epsgStringFromName: '" << datumName << "' is either unknown or not yet supported." << std::endl;
    throw boost::enable_current_exception(std::runtime_error(ss.str()));
}
References AGD66_c, AGD66_i, AGD84_c, AGD84_i, epsgCodeFromName(), GDA2020_c_xyz, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_c_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_c, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_c, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_c, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_c, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_c, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_c, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_c, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_c, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_c, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_c, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_c, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_c, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_c, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_c, ITRF2020_i, ITRF2020_i_xyz, WGS84_c, WGS84_ensemble_i, WGS84_G1150_c, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_c, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_c, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_c, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_c, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_c, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_c, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by dynadjust::measurements::CDnaGpsBaseline::CDnaGpsBaseline(), dynadjust::measurements::CDnaGpsBaselineCluster::CDnaGpsBaselineCluster(), dynadjust::measurements::CDnaGpsBaselineCluster::CDnaGpsBaselineCluster(), dynadjust::measurements::CDnaGpsPoint::CDnaGpsPoint(), dynadjust::measurements::CDnaGpsPointCluster::CDnaGpsPointCluster(), dynadjust::measurements::CDnaGpsPointCluster::CDnaGpsPointCluster(), dynadjust::measurements::CDnaStation::CDnaStation(), ExportStationsandMeasurements(), ImportDataFiles(), dynadjust::referenceframe::dna_reftran::IsolateandApplySubstitute(), referenceframe_pimpl::post_type(), dynadjust::iostreams::dna_io_dna::read_dna_header(), dynadjust::measurements::CDnaGpsBaseline::SetReferenceFrame(), dynadjust::measurements::CDnaGpsBaselineCluster::SetReferenceFrame(), dynadjust::measurements::CDnaGpsPoint::SetReferenceFrame(), and dynadjust::measurements::CDnaGpsPointCluster::SetReferenceFrame().
isEpsgDatumStatic()
template<typename U> bool dynadjust::epsg::isEpsgDatumStatic (const U & epsgCode)
Definition at line 291 of file dnaepsg.hpp.
{
    std::stringstream ss;
    switch (epsgCode)
    {
    // AGD66
    case AGD66_i:
    // AGD84
    case AGD84_i:
    // GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // WGS84 ensemble
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_ensemble_i:
        return true;
    // ITRF....
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    case ITRF2000_i_xyz:
    case ITRF2000_i:
    case ITRF2005_i:
    case ITRF2005_i_xyz:
    case ITRF2008_i:
    case ITRF2008_i_xyz:
    case ITRF2014_i:
    case ITRF2014_i_xyz:
    case ITRF2020_i:
    case ITRF2020_i_xyz:
        // WGS84 @ epoch
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
        return false;
    default:
        ss << "  isEpsgDatumStatic: EPSG code '" << epsgCode << "' is not a supported EPSG code." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return false;
}
References AGD66_i, AGD84_i, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, WGS84_ensemble_i, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by ImportDataFiles(), dynadjust::datum_parameters::CDnaDatum::initialiseDatumFromEpsgCode(), main(), ParseCommandLineOptions(), dynadjust::dynamlinterop::dna_import::ParseDNA(), dynadjust::dynamlinterop::dna_import::ParseXML(), PrintOutputFileHeaderInfo(), and PrintOutputFileHeaderInfo().
spheroidFromEpsgCode()
template<typename U> void dynadjust::epsg::spheroidFromEpsgCode (const U & epsgCode, epsg_spheroid & ellipsoid)
Definition at line 367 of file dnaepsg.hpp.
{
    switch (epsgCode)
    {
    // Unknown datum based on ANS
    case 4003:
    // AGD66
    case AGD66_i:
    // AGD84
    case AGD84_i:
    // Cocos islands
    //case 4708:
        // authority
        ellipsoid.authority_.first = "EPSG";
        ellipsoid.authority_.second = "7003";
        // ellipsoid params
        ellipsoid.inv_flattening_ = ANS_inv_f;
        ellipsoid.name_ = "Australian National Spheroid";
        ellipsoid.semi_major_ = ANS_a;
        break;
    // GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF....
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    case ITRF2000_i_xyz:
    case ITRF2000_i:
    case ITRF2005_i_xyz:
    case ITRF2005_i:
    case ITRF2008_i_xyz:
    case ITRF2008_i:
    case ITRF2014_i_xyz:
    case ITRF2014_i:
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        // authority
        ellipsoid.authority_.first = "EPSG";
        ellipsoid.authority_.second = "7019";
        // ellipsoid params
        ellipsoid.inv_flattening_ = GRS80_inv_f;
        ellipsoid.name_ = "GRS 1980";
        ellipsoid.semi_major_ = GRS80_a;
        break;
    // WGS84
    case WGS84_transit_i:
    case WGS84_transit_i_xyz:
    case WGS84_G730_i:
    case WGS84_G730_i_xyz:
    case WGS84_G873_i:
    case WGS84_G873_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G2139_i:
    case WGS84_G2139_i_xyz:
    case WGS84_ensemble_i:
    case WGS84_i_xyz:
    case WGS84_i:
        // authority
        ellipsoid.authority_.first = "EPSG";
        ellipsoid.authority_.second = "7030";
        // ellipsoid params
        ellipsoid.inv_flattening_ = WGS84_inv_f;
        ellipsoid.name_ = "WGS 84";
        ellipsoid.semi_major_ = WGS84_a;
        break;
    default:
        std::stringstream ss;
        ss << "  spheroidFromEpsgCode: EPSG code '" << epsgCode << "' is not a supported EPSG code." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
}
References AGD66_i, AGD84_i, ANS_a, ANS_inv_f, dynadjust::epsg::epsg_spheroid::authority_, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, GRS80_a, GRS80_inv_f, dynadjust::epsg::epsg_spheroid::inv_flattening_, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, dynadjust::epsg::epsg_spheroid::name_, dynadjust::epsg::epsg_spheroid::semi_major_, WGS84_a, WGS84_ensemble_i, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_inv_f, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by dynadjust::datum_parameters::CDnaEllipsoid::SetEllipsoid().
referenceepochFromEpsgCode()
template<typename U> std::string dynadjust::epsg::referenceepochFromEpsgCode (const U & epsgCode)
Definition at line 466 of file dnaepsg.hpp.
{
    switch (epsgCode)
    {
    // AGD66
    case AGD66_i:
        return AGD66_epoch;
    // AGD84
    case AGD84_i:
        return AGD84_epoch;
    // GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        return GDA94_epoch;
    // GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        return GDA2020_epoch;
    // ITRF....
    case ITRF1988_i_xyz:
    case ITRF1988_i:
        return ITRF1988_epoch;
    case ITRF1989_i_xyz:
    case ITRF1989_i:
        return ITRF1989_epoch;
    case ITRF1990_i_xyz:
    case ITRF1990_i:
        return ITRF1990_epoch;
    case ITRF1991_i_xyz:
    case ITRF1991_i:
        return ITRF1991_epoch;
    case ITRF1992_i_xyz:
    case ITRF1992_i:
        return ITRF1992_epoch;
    case ITRF1993_i_xyz:
    case ITRF1993_i:
        return ITRF1993_epoch;
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        return ITRF1994_epoch;
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        return ITRF1996_epoch;
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        return ITRF1997_epoch;
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        return ITRF2000_epoch;
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        return ITRF2005_epoch;
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        return ITRF2008_epoch;
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        return ITRF2014_epoch;
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        return ITRF2020_epoch;
        // WGS84
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
        return WGS84_transit_epoch;
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
        return WGS84_G730_epoch;
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
        return WGS84_G873_epoch;
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
        return WGS84_G1150_epoch;
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
        return WGS84_G1674_epoch;
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
        return WGS84_G1762_epoch;
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
        return WGS84_G2139_epoch;
    default:
        std::stringstream ss;
        ss << "  referenceepochFromEpsgCode: EPSG code '" << epsgCode << "' is not a supported EPSG code." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return "";
}
References AGD66_epoch, AGD66_i, AGD84_epoch, AGD84_i, GDA2020_epoch, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_epoch, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_epoch, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_epoch, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_epoch, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_epoch, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_epoch, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_epoch, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_epoch, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_epoch, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_epoch, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_epoch, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_epoch, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_epoch, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_epoch, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_epoch, ITRF2020_i, ITRF2020_i_xyz, WGS84_G1150_epoch, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_epoch, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_epoch, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_epoch, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_epoch, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_epoch, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_epoch, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by ImportDataFiles(), main(), ParseCommandLineOptions(), referenceepochFromEpsgString(), dynadjust::referenceframe::dna_reftran::SerialiseDynaMLStn(), dynadjust::datum_parameters::CDnaDatum::SetDatum(), and dynadjust::datum_parameters::CDnaDatum::SetEpoch().
referenceepochFromEpsgString()
template<typename S> S dynadjust::epsg::referenceepochFromEpsgString (const S & epsgString)
Definition at line 562 of file dnaepsg.hpp.
{
    return referenceepochFromEpsgCode<UINT32>(LongFromString<UINT32>(epsgString));
}
References LongFromString(), and referenceepochFromEpsgCode().
Referenced by ImportDataFiles(), dynadjust::dynamlinterop::dna_import::ParseDNA(), dynadjust::dynamlinterop::dna_import::ParseXML(), and dynadjust::iostreams::dna_io_dna::read_dna_header().
datumFromEpsgCode()
template<typename S, typename U> S dynadjust::epsg::datumFromEpsgCode (const U & epsgCode)
Definition at line 568 of file dnaepsg.hpp.
{
    switch (epsgCode)
    {
    // AGD66
    case AGD66_i:
        return AGD66_s;
    // AGD84
    case AGD84_i:
        return AGD84_s;
    // Cocos islands
    //case 4708:
    //  return "CocosIs1965";
    // GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
        return GDA94_s;
    // GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
        return GDA2020_s;
    // ITRF....
    case ITRF1988_i_xyz:
    case ITRF1988_i:
        return ITRF1988_s;
    case ITRF1989_i_xyz:
    case ITRF1989_i:
        return ITRF1989_s;
    case ITRF1990_i_xyz:
    case ITRF1990_i:
        return ITRF1990_s;
    case ITRF1991_i_xyz:
    case ITRF1991_i:
        return ITRF1991_s;
    case ITRF1992_i_xyz:
    case ITRF1992_i:
        return ITRF1992_s;
    case ITRF1993_i_xyz:
    case ITRF1993_i:
        return ITRF1993_s;
    case ITRF1994_i_xyz:
    case ITRF1994_i:
        return ITRF1994_s;
    case ITRF1996_i_xyz:
    case ITRF1996_i:
        return ITRF1996_s;
    case ITRF1997_i_xyz:
    case ITRF1997_i:
        return ITRF1997_s;
    case ITRF2000_i_xyz:
    case ITRF2000_i:
        return ITRF2000_s;
    case ITRF2005_i_xyz:
    case ITRF2005_i:
        return ITRF2005_s;
    case ITRF2008_i_xyz:
    case ITRF2008_i:
        return ITRF2008_s;
    case ITRF2014_i_xyz:
    case ITRF2014_i:
        return ITRF2014_s;
    case ITRF2020_i_xyz:
    case ITRF2020_i:
        return ITRF2020_s;
    case WGS84_i_xyz:
    case WGS84_i:
        return WGS84_s;
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
        return WGS84_transit_s;
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
        return WGS84_G730_s;
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
        return WGS84_G873_s;
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
        return WGS84_G1150_s;
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
        return WGS84_G1674_s;
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
        return WGS84_G1762_s;
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
        return WGS84_G2139_s;
    default:
        std::stringstream ss;
        ss << "  datumFromEpsgCode: EPSG code '" << epsgCode << "' is not a supported EPSG code." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return "";
}
References AGD66_i, AGD66_s, AGD84_i, AGD84_s, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA2020_s, GDA94_i, GDA94_i_2d, GDA94_i_xyz, GDA94_s, ITRF1988_i, ITRF1988_i_xyz, ITRF1988_s, ITRF1989_i, ITRF1989_i_xyz, ITRF1989_s, ITRF1990_i, ITRF1990_i_xyz, ITRF1990_s, ITRF1991_i, ITRF1991_i_xyz, ITRF1991_s, ITRF1992_i, ITRF1992_i_xyz, ITRF1992_s, ITRF1993_i, ITRF1993_i_xyz, ITRF1993_s, ITRF1994_i, ITRF1994_i_xyz, ITRF1994_s, ITRF1996_i, ITRF1996_i_xyz, ITRF1996_s, ITRF1997_i, ITRF1997_i_xyz, ITRF1997_s, ITRF2000_i, ITRF2000_i_xyz, ITRF2000_s, ITRF2005_i, ITRF2005_i_xyz, ITRF2005_s, ITRF2008_i, ITRF2008_i_xyz, ITRF2008_s, ITRF2014_i, ITRF2014_i_xyz, ITRF2014_s, ITRF2020_i, ITRF2020_i_xyz, ITRF2020_s, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1150_s, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1674_s, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G1762_s, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G2139_s, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G730_s, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_G873_s, WGS84_i, WGS84_i_xyz, WGS84_s, WGS84_transit_i, WGS84_transit_i_xyz, and WGS84_transit_s.
Referenced by datumFromEpsgString(), dynadjust::datum_parameters::determineHelmertParameters(), dynadjust::datum_parameters::CDnaDatum::initialiseDatumFromEpsgCode(), dynadjust::referenceframe::dna_reftran::IsolateandApplySubstitute(), dynadjust::datum_parameters::message_parameters_undefined(), dynadjust::referenceframe::dna_reftran::SerialiseDynaMLStn(), dynadjust::measurements::CDnaGpsPoint::SetMeasurementRec(), dynadjust::measurements::CDnaGpsPointCluster::SetMeasurementRec(), and dynadjust::measurements::CDnaStation::SetStationRec().
datumFromEpsgString()
template<typename S> S dynadjust::epsg::datumFromEpsgString (const S & epsgCode)
Definition at line 667 of file dnaepsg.hpp.
{
    return datumFromEpsgCode<S, UINT32>(LongFromString<UINT32>(epsgCode));
}
References datumFromEpsgCode(), and LongFromString().
Referenced by dynadjust::referenceframe::dna_reftran::ApplyMeasurementFrameSubstitutions(), dynadjust::referenceframe::dna_reftran::ApplyStationFrameSubstitutions(), ExportStationsandMeasurements(), ImportDataFiles(), dynadjust::networkplot::dna_plot::LoadBinaryFiles(), dynadjust::dynamlinterop::dna_import::ParseDNA(), dynadjust::dynamlinterop::dna_import::ParseDNAMSR(), dynadjust::dynamlinterop::dna_import::ParseDNASTN(), dynadjust::dynamlinterop::dna_import::ParseXML(), DnaStation_pimpl::pre(), dynadjust::measurements::CDnaGpsBaseline::SetMeasurementRec(), dynadjust::measurements::CDnaGpsBaselineCluster::SetMeasurementRec(), dynadjust::referenceframe::dna_reftran::TransformMeasurementRecords(), dynadjust::referenceframe::dna_reftran::TransformStationRecords(), and DnaMeasurement_pimpl::Type().
validateEpsgCode()
template<typename U> bool dynadjust::epsg::validateEpsgCode (const U & epsgCode)
Definition at line 674 of file dnaepsg.hpp.
{
    switch (epsgCode)
    {
    // AGD66
    case AGD66_i:
    // AGD84
    case AGD84_i:
    // GDA94
    case GDA94_i_xyz:
    case GDA94_i_2d:
    case GDA94_i:
    // GDA2020
    case GDA2020_i_xyz:
    case GDA2020_i_2d:
    case GDA2020_i:
    // ITRF1988
    case ITRF1988_i_xyz:
    case ITRF1988_i:
    // ITRF1989
    case ITRF1989_i_xyz:
    case ITRF1989_i:
    // ITRF1990
    case ITRF1990_i_xyz:
    case ITRF1990_i:
    // ITRF1991
    case ITRF1991_i_xyz:
    case ITRF1991_i:
    // ITRF1992
    case ITRF1992_i_xyz:
    case ITRF1992_i:
    // ITRF1993
    case ITRF1993_i_xyz:
    case ITRF1993_i:
    // ITRF1994
    case ITRF1994_i_xyz:
    case ITRF1994_i:
    // ITRF1996
    case ITRF1996_i_xyz:
    case ITRF1996_i:
    // ITRF1997
    case ITRF1997_i_xyz:
    case ITRF1997_i:
    // ITRF2000
    case ITRF2000_i_xyz:
    case ITRF2000_i:
    // ITRF2005
    case ITRF2005_i_xyz:
    case ITRF2005_i:
    // ITRF2008
    case ITRF2008_i_xyz:
    case ITRF2008_i:
    // ITRF2014
    case ITRF2014_i_xyz:
    case ITRF2014_i:
    // ITRF2020
    case ITRF2020_i_xyz:
    case ITRF2020_i:
    // WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_ensemble_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
        return true;
    default:
        std::stringstream ss;
        ss << "  validateEpsgCode: EPSG code '" << epsgCode << "' is not a supported EPSG code." << std::endl;
        throw boost::enable_current_exception(std::runtime_error(ss.str()));
    }
    return false;
}
References AGD66_i, AGD84_i, GDA2020_i, GDA2020_i_2d, GDA2020_i_xyz, GDA94_i, GDA94_i_2d, GDA94_i_xyz, ITRF1988_i, ITRF1988_i_xyz, ITRF1989_i, ITRF1989_i_xyz, ITRF1990_i, ITRF1990_i_xyz, ITRF1991_i, ITRF1991_i_xyz, ITRF1992_i, ITRF1992_i_xyz, ITRF1993_i, ITRF1993_i_xyz, ITRF1994_i, ITRF1994_i_xyz, ITRF1996_i, ITRF1996_i_xyz, ITRF1997_i, ITRF1997_i_xyz, ITRF2000_i, ITRF2000_i_xyz, ITRF2005_i, ITRF2005_i_xyz, ITRF2008_i, ITRF2008_i_xyz, ITRF2014_i, ITRF2014_i_xyz, ITRF2020_i, ITRF2020_i_xyz, WGS84_ensemble_i, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
Referenced by dynadjust::datum_parameters::CDnaDatum::SetDatumFromEpsg().
isEpsgWGS84Ensemble()
template<typename U> bool dynadjust::epsg::isEpsgWGS84Ensemble (const U & epsgCode)
Definition at line 760 of file dnaepsg.hpp.
{
    switch (epsgCode)
    {
    // WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_ensemble_i:
        return true;
    default:
        return false;
    }
    return false;
}
References WGS84_ensemble_i, WGS84_i, and WGS84_i_xyz.
Referenced by dynadjust::datum_parameters::CDnaDatum::GetEpoch_s(), main(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRGPSBaselines(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRGPSPoints(), and dynadjust::datum_parameters::CDnaDatum::SetEpoch().
isEpsgStringWGS84Ensemble()
template<typename U> bool dynadjust::epsg::isEpsgStringWGS84Ensemble (const U & epsgString)
Definition at line 776 of file dnaepsg.hpp.
{
    if (boost::iequals(epsgString, WGS84_c) ||
        boost::iequals(epsgString, WGS84_ensemble_c))
        return true;
    return false;
}
References WGS84_c, and WGS84_ensemble_c.
Referenced by dynadjust::referenceframe::dna_reftran::IsolateandApplySubstitute().
isEpsgWGS84()
template<typename U> bool dynadjust::epsg::isEpsgWGS84 (const U & epsgCode)
Definition at line 786 of file dnaepsg.hpp.
{
    switch (epsgCode)
    {
        // WGS84
    case WGS84_i_xyz:
    case WGS84_i:
    case WGS84_ensemble_i:
    case WGS84_transit_i_xyz:
    case WGS84_transit_i:
    case WGS84_G730_i_xyz:
    case WGS84_G730_i:
    case WGS84_G873_i_xyz:
    case WGS84_G873_i:
    case WGS84_G1150_i_xyz:
    case WGS84_G1150_i:
    case WGS84_G1674_i_xyz:
    case WGS84_G1674_i:
    case WGS84_G1762_i_xyz:
    case WGS84_G1762_i:
    case WGS84_G2139_i_xyz:
    case WGS84_G2139_i:
        return true;
    default:
        return false;
    }
    return false;
}
References WGS84_ensemble_i, WGS84_G1150_i, WGS84_G1150_i_xyz, WGS84_G1674_i, WGS84_G1674_i_xyz, WGS84_G1762_i, WGS84_G1762_i_xyz, WGS84_G2139_i, WGS84_G2139_i_xyz, WGS84_G730_i, WGS84_G730_i_xyz, WGS84_G873_i, WGS84_G873_i_xyz, WGS84_i, WGS84_i_xyz, WGS84_transit_i, and WGS84_transit_i_xyz.
isEpsgStringWGS84()
template<typename U> bool dynadjust::epsg::isEpsgStringWGS84 (const U & epsgString)
Definition at line 816 of file dnaepsg.hpp.
{
    if (boost::iequals(epsgString, WGS84_c) ||
        boost::iequals(epsgString, WGS84_ensemble_c) ||
        boost::iequals(epsgString, WGS84_transit_c) ||
        boost::iequals(epsgString, WGS84_G730_c) ||
        boost::iequals(epsgString, WGS84_G873_c) ||
        boost::iequals(epsgString, WGS84_G1150_c) ||
        boost::iequals(epsgString, WGS84_G1674_c) ||
        boost::iequals(epsgString, WGS84_G1762_c) ||
        boost::iequals(epsgString, WGS84_G2139_c))
        return true;
    return false;
}
References WGS84_c, WGS84_ensemble_c, WGS84_G1150_c, WGS84_G1674_c, WGS84_G1762_c, WGS84_G2139_c, WGS84_G730_c, WGS84_G873_c, and WGS84_transit_c.