DynAdjust: dynadjust::measurements Namespace Reference
dynadjust::measurements Namespace Reference
Classes
class CAStationList
class CDnaAngle
class CDnaAzimuth
class CDnaCoordinate
class CDnaCovariance
class CDnaDirection
class CDnaDirectionSet
class CDnaDistance
class CDnaGpsBaseline
class CDnaGpsBaselineCluster
class CDnaGpsPoint
class CDnaGpsPointCluster
class CDnaHeight
class CDnaHeightDifference
class CDnaMeasurement
class CDnaStation
struct msr_t
class MsrTally
struct scl_t
class StnTally
Typedefs
typedef boost::shared_ptr< CDnaMeasurement > dnaMsrPtr
typedef std::vector< dnaMsrPtr > vdnaMsrPtr
typedef std::vector< dnaMsrPtr > * pvdnaMsrPtr
typedef vdnaMsrPtr::iterator _it_vdnamsrptr
typedef vdnaMsrPtr::const_iterator _it_vdnamsrptr_const
typedef boost::shared_ptr< CDnaCovariance > dnaCovariancePtr
typedef boost::shared_ptr< std::vector< CDnaCovariance > > vecCovariancePtr
typedef struct dynadjust::measurements::msr_t measurement_t
typedef std::vector< measurement_t > vmsr_t
typedef std::vector< measurement_t > * pvmsr_t
typedef vmsr_t::iterator it_vmsr_t
typedef vmsr_t::iterator * pit_vmsr_t
typedef vmsr_t::const_iterator it_vmsr_t_const
typedef struct dynadjust::measurements::scl_t scalar_t
typedef std::vector< scalar_t > vscl_t
typedef std::vector< scalar_t > * pvscl_t
typedef vscl_t::iterator it_vscl_t
typedef vscl_t::iterator * pit_vscl_t
typedef vscl_t::const_iterator it_vscl_t_const
typedef std::vector< MsrTally > vmsrtally
typedef vmsrtally::iterator _it_vmsrtally
typedef boost::shared_ptr< CDnaStation > dnaStnPtr
typedef std::vector< dnaStnPtr > vdnaStnPtr
typedef std::vector< dnaStnPtr > * pvdnaStnPtr
typedef vdnaStnPtr::iterator _it_vdnastnptr
typedef vdnaStnPtr::const_iterator _it_vdnastnptr_const
typedef std::pair< _it_vdnastnptr, _it_vdnastnptr > it_pair_dnastnptr
typedef std::vector< CAStationList > vASL
typedef std::vector< CAStationList > * pvASL
typedef vASL::iterator _it_vasl
typedef boost::shared_ptr< CAStationList > ASLPtr
typedef std::vector< ASLPtr > vASLPtr
typedef std::vector< ASLPtr > * pvASLPtr
Functions
bool operator< (const CDnaMeasurement &left, const CDnaMeasurement &right)
bool operator< (const dnaMsrPtr &left, const dnaMsrPtr &right)
template<typename C, typename S>
S measurement_name (const C &type)
template<typename T>
void MsrToStnSummaryHeaderLine (T &stream)
template<typename T>
void MsrToStnSummaryHeader (T &stream, std::string &header)
bool operator< (const CDnaStation &left, const CDnaStation &right)
bool operator< (const boost::shared_ptr< CDnaStation > &left, const boost::shared_ptr< CDnaStation > &right)
Typedef Documentation
dnaMsrPtr
typedef boost::shared_ptr<CDnaMeasurement> dynadjust::measurements::dnaMsrPtr
Definition at line 126 of file dnameasurement.hpp.
vdnaMsrPtr
typedef std::vector<dnaMsrPtr> dynadjust::measurements::vdnaMsrPtr
Definition at line 127 of file dnameasurement.hpp.
pvdnaMsrPtr
typedef std::vector<dnaMsrPtr> * dynadjust::measurements::pvdnaMsrPtr
Definition at line 127 of file dnameasurement.hpp.
_it_vdnamsrptr
typedef vdnaMsrPtr::iterator dynadjust::measurements::_it_vdnamsrptr
Definition at line 128 of file dnameasurement.hpp.
_it_vdnamsrptr_const
typedef vdnaMsrPtr::const_iterator dynadjust::measurements::_it_vdnamsrptr_const
Definition at line 129 of file dnameasurement.hpp.
dnaCovariancePtr
typedef boost::shared_ptr<CDnaCovariance> dynadjust::measurements::dnaCovariancePtr
Definition at line 131 of file dnameasurement.hpp.
vecCovariancePtr
typedef boost::shared_ptr< std::vector<CDnaCovariance> > dynadjust::measurements::vecCovariancePtr
Definition at line 132 of file dnameasurement.hpp.
measurement_t
typedef struct dynadjust::measurements::msr_t dynadjust::measurements::measurement_t
vmsr_t
typedef std::vector<measurement_t> dynadjust::measurements::vmsr_t
Definition at line 192 of file dnameasurement.hpp.
pvmsr_t
typedef std::vector<measurement_t> * dynadjust::measurements::pvmsr_t
Definition at line 192 of file dnameasurement.hpp.
it_vmsr_t
typedef vmsr_t::iterator dynadjust::measurements::it_vmsr_t
Definition at line 193 of file dnameasurement.hpp.
pit_vmsr_t
typedef vmsr_t::iterator * dynadjust::measurements::pit_vmsr_t
Definition at line 193 of file dnameasurement.hpp.
it_vmsr_t_const
typedef vmsr_t::const_iterator dynadjust::measurements::it_vmsr_t_const
Definition at line 194 of file dnameasurement.hpp.
scalar_t
typedef struct dynadjust::measurements::scl_t dynadjust::measurements::scalar_t
vscl_t
typedef std::vector<scalar_t> dynadjust::measurements::vscl_t
Definition at line 210 of file dnameasurement.hpp.
pvscl_t
typedef std::vector<scalar_t> * dynadjust::measurements::pvscl_t
Definition at line 210 of file dnameasurement.hpp.
it_vscl_t
typedef vscl_t::iterator dynadjust::measurements::it_vscl_t
Definition at line 211 of file dnameasurement.hpp.
pit_vscl_t
typedef vscl_t::iterator * dynadjust::measurements::pit_vscl_t
Definition at line 211 of file dnameasurement.hpp.
it_vscl_t_const
typedef vscl_t::const_iterator dynadjust::measurements::it_vscl_t_const
Definition at line 212 of file dnameasurement.hpp.
vmsrtally
typedef std::vector<MsrTally> dynadjust::measurements::vmsrtally
Definition at line 552 of file dnameasurement.hpp.
_it_vmsrtally
typedef vmsrtally::iterator dynadjust::measurements::_it_vmsrtally
Definition at line 553 of file dnameasurement.hpp.
dnaStnPtr
typedef boost::shared_ptr<CDnaStation> dynadjust::measurements::dnaStnPtr
Definition at line 74 of file dnastation.hpp.
vdnaStnPtr
typedef std::vector<dnaStnPtr> dynadjust::measurements::vdnaStnPtr
Definition at line 75 of file dnastation.hpp.
pvdnaStnPtr
typedef std::vector<dnaStnPtr> * dynadjust::measurements::pvdnaStnPtr
Definition at line 75 of file dnastation.hpp.
_it_vdnastnptr
typedef vdnaStnPtr::iterator dynadjust::measurements::_it_vdnastnptr
Definition at line 76 of file dnastation.hpp.
_it_vdnastnptr_const
typedef vdnaStnPtr::const_iterator dynadjust::measurements::_it_vdnastnptr_const
Definition at line 77 of file dnastation.hpp.
it_pair_dnastnptr
typedef std::pair<_it_vdnastnptr, _it_vdnastnptr> dynadjust::measurements::it_pair_dnastnptr
Definition at line 78 of file dnastation.hpp.
vASL
typedef std::vector<CAStationList> dynadjust::measurements::vASL
Definition at line 80 of file dnastation.hpp.
pvASL
typedef std::vector<CAStationList> * dynadjust::measurements::pvASL
Definition at line 80 of file dnastation.hpp.
_it_vasl
typedef vASL::iterator dynadjust::measurements::_it_vasl
Definition at line 81 of file dnastation.hpp.
ASLPtr
typedef boost::shared_ptr<CAStationList> dynadjust::measurements::ASLPtr
Definition at line 82 of file dnastation.hpp.
vASLPtr
typedef std::vector<ASLPtr> dynadjust::measurements::vASLPtr
Definition at line 83 of file dnastation.hpp.
pvASLPtr
typedef std::vector<ASLPtr> * dynadjust::measurements::pvASLPtr
Definition at line 83 of file dnastation.hpp.
Function Documentation
operator<() [1/4]
bool dynadjust::measurements::operator< (const CDnaMeasurement & left, const CDnaMeasurement & right)
Definition at line 335 of file dnameasurement.cpp.
{
    return left.m_strFirst < right.m_strFirst;
}
References dynadjust::measurements::CDnaMeasurement::m_strFirst.
operator<() [2/4]
bool dynadjust::measurements::operator< (const dnaMsrPtr & left, const dnaMsrPtr & right)
Definition at line 340 of file dnameasurement.cpp.
{
    return left.get()->m_strFirst < right.get()->m_strFirst;
}
measurement_name()
template<typename C, typename S> S dynadjust::measurements::measurement_name (const C & type)
Definition at line 69 of file dnameasurement.hpp.
{
    switch (type)
    {
    case 'A':
        return "(A) Horizontal angle";
    case 'B':
        return "(B) Geodetic azimuth";
    case 'K':
        return "(K) Astronomic azimuth";
    case 'C':
        return "(C) Chord distance";
    case 'E':
        return "(E) Ellipsoid arc";
    case 'M':
        return "(M) Mean sea level arc";
    case 'S':
        return "(S) Slope distance";
    case 'D':
        return "(D) Direction set";
    case 'G':
        return "(G) GPS baseline";
    case 'X':
        return "(X) GPS baseline cluster";
    case 'H':
        return "(H) Orthometric height";
    case 'I':
        return "(I) Astronomic latitude";
    case 'J':
        return "(J) Astronomic longitude";
    case 'P':
        return "(P) Geodetic latitude";
    case 'Q':
        return "(Q) Geodetic longitude";
    case 'L':
        return "(L) Level difference";
    case 'R':
        return "(R) Ellipsoidal height";
    case 'V':
        return "(V) Zenith distance";
    case 'Z':
        return "(Z) Vertical angle";
    case 'Y':
        return "(Y) GPS point cluster";
    }
    return "";
}
Referenced by dynadjust::referenceframe::dna_reftran::ApplyMeasurementFrameSubstitutions(), dynadjust::networkplot::dna_plot::CreateGMTCommandFile(), dynadjust::measurements::MsrTally::GetMsrName(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRCoordinate(), dynadjust::dynamlinterop::dna_import::ParseDNAMSRLinear(), dynadjust::networkplot::dna_plot::PlotGnuplotDatFileMsrs(), dynadjust::networkplot::dna_plot::PrintGnuplotCommandFileMsrs(), dynadjust::referenceframe::dna_reftran::TransformMeasurementRecords(), dynadjust::measurements::CDnaAngle::WriteDynaMLMsr(), dynadjust::measurements::CDnaCoordinate::WriteDynaMLMsr(), dynadjust::measurements::CDnaDirection::WriteDynaMLMsr(), dynadjust::measurements::CDnaDirectionSet::WriteDynaMLMsr(), dynadjust::measurements::CDnaDistance::WriteDynaMLMsr(), dynadjust::measurements::CDnaGpsBaselineCluster::WriteDynaMLMsr(), dynadjust::measurements::CDnaGpsPointCluster::WriteDynaMLMsr(), dynadjust::measurements::CDnaHeight::WriteDynaMLMsr(), and dynadjust::measurements::CDnaHeightDifference::WriteDynaMLMsr().
MsrToStnSummaryHeaderLine()
template<typename T> void dynadjust::measurements::MsrToStnSummaryHeaderLine (T & stream)
Definition at line 556 of file dnameasurement.hpp.
{
    UINT32 i, j(STATION + (NUMERIC_WIDTH * 20) + STAT);
    for (i=0; i<j; ++i)
        stream << "-";
    stream << std::endl;
}
References NUMERIC_WIDTH(), STAT(), and STATION().
Referenced by MsrToStnSummaryHeader(), dynadjust::networkadjust::dna_adjust::PrintMeasurementsToStation(), and dynadjust::iostreams::dna_io_aml::write_msr_to_stn().
MsrToStnSummaryHeader()
template<typename T> void dynadjust::measurements::MsrToStnSummaryHeader (T & stream, std::string & header)
Definition at line 567 of file dnameasurement.hpp.
{
    stream << std::endl << header << std::endl;
    stream << "------------------------------------------" << std::endl << std::endl;
    stream << std::setw(STATION) << std::left << "Station" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "A" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "B" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "C" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "D" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "E" <<
        std::setw(NUMERIC_WIDTH) << std::right << "G" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "H" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "I" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "J" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "K" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "L" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "M" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "P" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "Q" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "R" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "S" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "V" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "X" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "Y" <<
        std::setw(NUMERIC_WIDTH) << std::right <<  "Z" <<
        // Total
        std::setw(STAT) << std::right <<    "Total" <<
        std::endl;
    MsrToStnSummaryHeaderLine(stream);
}
References MsrToStnSummaryHeaderLine(), NUMERIC_WIDTH(), STAT(), and STATION().
Referenced by dynadjust::networkadjust::dna_adjust::PrintMeasurementsToStation(), and dynadjust::iostreams::dna_io_aml::write_msr_to_stn().
operator<() [3/4]
bool dynadjust::measurements::operator< (const CDnaStation & left, const CDnaStation & right)
Definition at line 36 of file dnastation.cpp.
{
    return left.m_strName < right.m_strName;
}
operator<() [4/4]
bool dynadjust::measurements::operator< (const boost::shared_ptr< CDnaStation > & left, const boost::shared_ptr< CDnaStation > & right)
Definition at line 41 of file dnastation.cpp.
{
    return left.get()->m_strName < right.get()->m_strName;
}