DynAdjust: dynadjust::iostreams Namespace Reference
dynadjust::iostreams Namespace Reference
Classes
struct CompareDiscontinuityOnSite
class CompareSiteTuples
class CompareSiteTuplesByName
class CompareTypeBStationID
struct discontinuity_tuple_t
class dna_io_adj
class dna_io_aml
class dna_io_asl
class dna_io_base
class dna_io_bms
class dna_io_bst
class dna_io_dna
class dna_io_map
class dna_io_pdf
class dna_io_scalar
class dna_io_seg
class dna_io_snx
class dna_io_tbu
class dna_io_tpb
struct plate_motion_cartesian_t
struct plate_motion_euler_t
struct site_id_tuple_t
struct type_b_method_t
struct type_b_uncertainty_t
Typedefs
typedef enum dynadjust::iostreams::_SINEX_WARN_TYPE_ SINEX_WARN_TYPE
typedef site_id_tuple_t< UINT32, std::string, bool > site_id
typedef std::vector< site_id > v_site_id_tuple
typedef std::vector< site_id > * pv_v_site_id_tuple
typedef v_site_id_tuple::iterator _it_vsite_id_tuple
typedef discontinuity_tuple_t< UINT32, std::string, boost::gregorian::date, bool > discontinuity_tuple
typedef std::vector< discontinuity_tuple > v_discontinuity_tuple
typedef std::vector< discontinuity_tuple > * pv_v_discontinuity_tuple
typedef v_discontinuity_tuple::iterator _it_vdiscontinuity_tuple
typedef enum dynadjust::iostreams::_DATE_TERMINAL_TYPE_ DATE_TERMINAL_TYPE
typedef enum dynadjust::iostreams::_DATE_FORMAT_TYPE_ DATE_FORMAT_TYPE
typedef type_b_uncertainty_t< UINT32, double, matrix_2d > type_b_uncertainty
typedef std::vector< type_b_uncertainty > v_type_b_uncertainty
typedef v_type_b_uncertainty::iterator it_type_b_uncertainty
typedef std::pair< it_type_b_uncertainty, it_type_b_uncertainty > it_pair_type_b_uncertainty
typedef enum dynadjust::iostreams::_TYPE_B_METHOD_TYPE_ TYPE_B_METHOD_TYPE
typedef type_b_method_t< UINT32, bool, TYPE_B_METHOD_TYPE > type_b_method
typedef std::vector< type_b_method > v_type_b_method
typedef v_type_b_method::iterator it_type_b_method
typedef plate_motion_euler_t< std::string, double > plate_motion_euler
typedef std::vector< plate_motion_euler > v_plate_motion_eulers
typedef v_plate_motion_eulers::iterator it_plate_motion_euler
typedef plate_motion_cartesian_t< std::string, double > plate_motion_cartesian
typedef std::vector< plate_motion_cartesian > v_plate_motion_cartesians
typedef v_plate_motion_cartesians::iterator it_plate_motion_cartesian
Enumerations
enum _SINEX_WARN_TYPE_ { excessive_name_chars = 0 }
enum _DATE_TERMINAL_TYPE_ { date_from = 0 , date_to = 1 }
enum _DATE_FORMAT_TYPE_ { yy_doy = 0 , yyyy_doy = 1 , doy_yy = 2 , doy_yyyy = 3 }
enum _TYPE_B_METHOD_TYPE_ { type_b_global = 0 , type_b_local = 1 }
Functions
const UINT16 identifier_field_width (10)
template<typename T, typename S, typename D>
bool rename_discont_station (T &begin, S &site_name, D &site_date, S &site_renamed)
template<typename T, typename S>
T binary_search_discontinuity_site (T begin, T end, S value)
Variables
const char *const version_header = "VERSION "
const char *const create_date_header = "CREATED ON"
const char *const create_by_header = "CREATED BY"
Typedef Documentation
SINEX_WARN_TYPE
typedef enum dynadjust::iostreams::_SINEX_WARN_TYPE_ dynadjust::iostreams::SINEX_WARN_TYPE
site_id
typedef site_id_tuple_t<UINT32, std::string, bool> dynadjust::iostreams::site_id
Definition at line 93 of file dnaiosnx.hpp.
v_site_id_tuple
typedef std::vector<site_id> dynadjust::iostreams::v_site_id_tuple
Definition at line 94 of file dnaiosnx.hpp.
pv_v_site_id_tuple
typedef std::vector<site_id> * dynadjust::iostreams::pv_v_site_id_tuple
Definition at line 94 of file dnaiosnx.hpp.
_it_vsite_id_tuple
typedef v_site_id_tuple::iterator dynadjust::iostreams::_it_vsite_id_tuple
Definition at line 95 of file dnaiosnx.hpp.
discontinuity_tuple
typedef discontinuity_tuple_t<UINT32, std::string, boost::gregorian::date, bool> dynadjust::iostreams::discontinuity_tuple
Definition at line 154 of file dnaiosnx.hpp.
v_discontinuity_tuple
typedef std::vector<discontinuity_tuple> dynadjust::iostreams::v_discontinuity_tuple
Definition at line 155 of file dnaiosnx.hpp.
pv_v_discontinuity_tuple
typedef std::vector<discontinuity_tuple> * dynadjust::iostreams::pv_v_discontinuity_tuple
Definition at line 155 of file dnaiosnx.hpp.
_it_vdiscontinuity_tuple
typedef v_discontinuity_tuple::iterator dynadjust::iostreams::_it_vdiscontinuity_tuple
Definition at line 156 of file dnaiosnx.hpp.
DATE_TERMINAL_TYPE
typedef enum dynadjust::iostreams::_DATE_TERMINAL_TYPE_ dynadjust::iostreams::DATE_TERMINAL_TYPE
DATE_FORMAT_TYPE
typedef enum dynadjust::iostreams::_DATE_FORMAT_TYPE_ dynadjust::iostreams::DATE_FORMAT_TYPE
type_b_uncertainty
typedef type_b_uncertainty_t<UINT32, double, matrix_2d> dynadjust::iostreams::type_b_uncertainty
Definition at line 79 of file dnaiotbu.hpp.
v_type_b_uncertainty
typedef std::vector<type_b_uncertainty> dynadjust::iostreams::v_type_b_uncertainty
Definition at line 80 of file dnaiotbu.hpp.
it_type_b_uncertainty
typedef v_type_b_uncertainty::iterator dynadjust::iostreams::it_type_b_uncertainty
Definition at line 81 of file dnaiotbu.hpp.
it_pair_type_b_uncertainty
typedef std::pair<it_type_b_uncertainty, it_type_b_uncertainty> dynadjust::iostreams::it_pair_type_b_uncertainty
Definition at line 82 of file dnaiotbu.hpp.
TYPE_B_METHOD_TYPE
typedef enum dynadjust::iostreams::_TYPE_B_METHOD_TYPE_ dynadjust::iostreams::TYPE_B_METHOD_TYPE
type_b_method
typedef type_b_method_t<UINT32, bool, TYPE_B_METHOD_TYPE> dynadjust::iostreams::type_b_method
Definition at line 133 of file dnaiotbu.hpp.
v_type_b_method
typedef std::vector<type_b_method> dynadjust::iostreams::v_type_b_method
Definition at line 134 of file dnaiotbu.hpp.
it_type_b_method
typedef v_type_b_method::iterator dynadjust::iostreams::it_type_b_method
Definition at line 135 of file dnaiotbu.hpp.
plate_motion_euler
typedef plate_motion_euler_t<std::string, double> dynadjust::iostreams::plate_motion_euler
Definition at line 78 of file dnaiotpb.hpp.
v_plate_motion_eulers
typedef std::vector<plate_motion_euler> dynadjust::iostreams::v_plate_motion_eulers
Definition at line 79 of file dnaiotpb.hpp.
it_plate_motion_euler
typedef v_plate_motion_eulers::iterator dynadjust::iostreams::it_plate_motion_euler
Definition at line 80 of file dnaiotpb.hpp.
plate_motion_cartesian
typedef plate_motion_cartesian_t<std::string, double> dynadjust::iostreams::plate_motion_cartesian
Definition at line 127 of file dnaiotpb.hpp.
v_plate_motion_cartesians
typedef std::vector<plate_motion_cartesian> dynadjust::iostreams::v_plate_motion_cartesians
Definition at line 128 of file dnaiotpb.hpp.
it_plate_motion_cartesian
typedef v_plate_motion_cartesians::iterator dynadjust::iostreams::it_plate_motion_cartesian
Definition at line 129 of file dnaiotpb.hpp.
Enumeration Type Documentation
_SINEX_WARN_TYPE_
enum dynadjust::iostreams::_SINEX_WARN_TYPE_
Enumerator
excessive_name_chars
Definition at line 50 of file dnaiosnx.hpp.
{
    excessive_name_chars = 0
} SINEX_WARN_TYPE;
_DATE_TERMINAL_TYPE_
enum dynadjust::iostreams::_DATE_TERMINAL_TYPE_
Enumerator
date_from
date_to
Definition at line 229 of file dnaiosnx.hpp.
{
    date_from = 0,
    date_to = 1
} DATE_TERMINAL_TYPE;
_DATE_FORMAT_TYPE_
enum dynadjust::iostreams::_DATE_FORMAT_TYPE_
Enumerator
yy_doy
yyyy_doy
doy_yy
doy_yyyy
Definition at line 236 of file dnaiosnx.hpp.
{
    yy_doy = 0,
    yyyy_doy = 1,
    doy_yy = 2,
    doy_yyyy = 3
} DATE_FORMAT_TYPE;
_TYPE_B_METHOD_TYPE_
enum dynadjust::iostreams::_TYPE_B_METHOD_TYPE_
Enumerator
type_b_global
type_b_local
Definition at line 105 of file dnaiotbu.hpp.
{
    type_b_global = 0,
    type_b_local = 1
} TYPE_B_METHOD_TYPE;
Function Documentation
identifier_field_width()
const UINT16 dynadjust::iostreams::identifier_field_width (10)
Referenced by dynadjust::iostreams::dna_io_base::readApp(), dynadjust::iostreams::dna_io_base::readDate(), dynadjust::iostreams::dna_io_base::readVersion(), dynadjust::iostreams::dna_io_base::writeApp(), dynadjust::iostreams::dna_io_base::writeDate(), and dynadjust::iostreams::dna_io_base::writeVersion().
rename_discont_station()
template<typename T, typename S, typename D> bool dynadjust::iostreams::rename_discont_station (T & begin, S & site_name, D & site_date, S & site_renamed)
Definition at line 159 of file dnaiosnx.hpp.
{
    UINT32 doy, year;
    // find the next occurrence of this site
    while (boost::equals(site_name, begin->site_name))
    {
        // Check if discontinuities exist at this site, if not, skip
        if (!begin->discontinuity_exists)
        {
            begin++;
            continue;
        }
        // Test if the start epoch of this site is within this discontinuity window
        if (site_date >= begin->date_start &&
            site_date < begin->date_end)
        {
            std::stringstream ss;
            doy = begin->date_start.day_of_year();
            year = begin->date_start.year();
            ss << site_name << "_";
            ss << year;
            if (doy < 100)
                ss << "0";
            if (doy < 10)
                ss << "0";
            ss << doy;
            site_renamed = ss.str();
            return true;
        }
        begin++;
    }
    return false;
}
Referenced by dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements(), dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements_D(), dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements_GX(), and dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements_Y().
binary_search_discontinuity_site()
template<typename T, typename S> T dynadjust::iostreams::binary_search_discontinuity_site (T begin, T end, S value)
Definition at line 219 of file dnaiosnx.hpp.
{
    T i = lower_bound(begin, end, value, CompareDiscontinuityOnSite<discontinuity_tuple, std::string>());
    if (i != end && i->site_name == value)
        return i;
    else
        return end;
}
Referenced by dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements(), dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements_D(), dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements_GX(), dynadjust::dynamlinterop::dna_import::ApplyDiscontinuitiesMeasurements_Y(), and dynadjust::iostreams::dna_io_snx::format_station_names().
Variable Documentation
version_header
const char* const dynadjust::iostreams::version_header = "VERSION "
Definition at line 60 of file dnaiobase.hpp.
Referenced by dynadjust::iostreams::dna_io_base::writeVersion().
create_date_header
const char* const dynadjust::iostreams::create_date_header = "CREATED ON"
Definition at line 61 of file dnaiobase.hpp.
Referenced by dynadjust::iostreams::dna_io_base::writeDate().
create_by_header
const char* const dynadjust::iostreams::create_by_header = "CREATED BY"
Definition at line 62 of file dnaiobase.hpp.
Referenced by dynadjust::iostreams::dna_io_base::writeApp().