DynAdjust: include/io/pdfdde.cpp File Reference
pdfdde.cpp File Reference
#include <windows.h>
#include <ddeml.h>
#include <dde.h>
#include <stdio.h>
#include <string.h>
#include <shellapi.h>
Macros
#define WIN32_LEAN_AND_MEAN
#define VC_EXTRALEAN
#define MAXPATHLEN 256
#define ACROBAT_EXE "acrobat.exe"
#define ACROBAT "acroview"
#define EVAL_TOPIC "control"
#define RESULT_ITEM "Result"
#define ERROR_ITEM "Error"
#define CONNECT_DELAY 500 /* ms */
#define TRANSACTION_TIMEOUT 5000 /* ms */
#define MAX_INPUT_IDLE_WAIT INFINITE /* ms */
#define ARGUMENT_IS(a)
#define PROGRAM_IS(a)
#define WHITE_DELIM " \t\n"
Functions
char * FindAcrobatModule ()
void CloseConversation (void)
void error (LPCTSTR fmt,...)
void * emalloc (size_t len)
HDDEDATA CALLBACK Callback (UINT uType, UINT uFmt, HCONV hconv, HSZ hsz1, HSZ hsz2, HDDEDATA hdata, DWORD dwData1, DWORD dwData2)
int StartServer (LPCTSTR prog)
HSZ DDEString (LPCTSTR str)
void FreeString (HSZ hsz)
void OpenConversation (LPCTSTR topic_name)
bool __cdecl ExecuteCommand (LPCTSTR command,...)
void StartHotLink (LPCTSTR item_name)
LPTSTR RequestData (LPCTSTR item_name)
char * CheckFileName (char *p)
int pdfopen ()
int pdfclose ()
int pdfserver ()
bool TellReaderToJumpToNamedDestViaDDE (const char *FullFilePath, const char *NamedDest)
Variables
static DWORD DDEsession
static HCONV DDEconversation
static char * argv0 = NULL
static int nPage = 0
static char * sFileName = NULL
static int bAll = 0
static int bBack = 0
static int bServer = 0
static int iDebug = 0
static char * sGoto = NULL
static char sLongFileName [MAXPATHLEN]
const char * pdfdde_version_string = "0.2"
int outstanding_requests
Macro Definition Documentation
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
Definition at line 32 of file pdfdde.cpp.
VC_EXTRALEAN
#define VC_EXTRALEAN
Definition at line 36 of file pdfdde.cpp.
MAXPATHLEN
#define MAXPATHLEN 256
Definition at line 40 of file pdfdde.cpp.
Referenced by CheckFileName().
ACROBAT_EXE
#define ACROBAT_EXE "acrobat.exe"
Definition at line 50 of file pdfdde.cpp.
ACROBAT
#define ACROBAT "acroview"
Definition at line 51 of file pdfdde.cpp.
Referenced by OpenConversation().
EVAL_TOPIC
#define EVAL_TOPIC "control"
Definition at line 52 of file pdfdde.cpp.
Referenced by pdfclose(), pdfopen(), pdfserver(), and TellReaderToJumpToNamedDestViaDDE().
RESULT_ITEM
#define RESULT_ITEM "Result"
Definition at line 53 of file pdfdde.cpp.
ERROR_ITEM
#define ERROR_ITEM "Error"
Definition at line 54 of file pdfdde.cpp.
CONNECT_DELAY
#define CONNECT_DELAY 500 /* ms */
Definition at line 57 of file pdfdde.cpp.
Referenced by OpenConversation().
TRANSACTION_TIMEOUT
#define TRANSACTION_TIMEOUT 5000 /* ms */
Definition at line 58 of file pdfdde.cpp.
Referenced by ExecuteCommand(), RequestData(), and StartHotLink().
MAX_INPUT_IDLE_WAIT
#define MAX_INPUT_IDLE_WAIT INFINITE /* ms */
Definition at line 59 of file pdfdde.cpp.
Referenced by StartServer().
ARGUMENT_IS
#define ARGUMENT_IS (a)
Value:
(_stricmp(long_options[option_index].name, a) == 0)
Definition at line 80 of file pdfdde.cpp.
PROGRAM_IS
#define PROGRAM_IS (a)
Value:
(_stricmp(a, argv0) == 0)
Definition at line 81 of file pdfdde.cpp.
WHITE_DELIM
#define WHITE_DELIM " \t\n"
Referenced by pdfserver().
Function Documentation
FindAcrobatModule()
char * FindAcrobatModule ()
Definition at line 97 of file pdfdde.cpp.
{
    char buf[260];
    char path[260];
    char *program;
    HANDLE hFile;
    HINSTANCE hInst;
    program = (char *)malloc(MAX_PATH*sizeof(char));
    if (program == NULL) goto exit_1;
    buf[0] = path[0] = program[0] = '\0';
    if (GetTempPath(sizeof(path), path) != 0) {
    strcpy(buf, path);
    }
    strcat(buf, "dummy.pdf");
    hFile = CreateFile(buf,
               GENERIC_READ|GENERIC_WRITE,
               FILE_SHARE_READ | FILE_SHARE_WRITE,
               NULL,
               OPEN_ALWAYS,
               FILE_ATTRIBUTE_NORMAL,
               NULL);
    CloseHandle(hFile);
    hInst = FindExecutable("dummy.pdf", path, program);
    DeleteFile(buf);
#if 0
    switch ((int)hInst) {
    case SE_ERR_FNF:
    fprintf(stdout, "File not found: %s\n", argv[1]);
    break;
    case SE_ERR_NOASSOC:
    fprintf(stdout, "No association for %s\n", argv[1]);
    break;
    default:
    fprintf(stdout, "File .pdf is opened by %s\n", program);
    break;
    }
#endif
    if (*program == '\0' || (GetFileAttributes(program) == 0xFFFFFFFF)) {
    program = NULL;
    }
exit_1:
    return program;
}
Referenced by OpenConversation().
CloseConversation()
void CloseConversation (void)
Definition at line 154 of file pdfdde.cpp.
{
    if (DDEconversation)
    DdeDisconnect(DDEconversation);
    if (DDEsession)
    DdeUninitialize(DDEsession);
}
References DDEconversation, and DDEsession.
Referenced by error(), pdfclose(), pdfopen(), pdfserver(), and TellReaderToJumpToNamedDestViaDDE().
error()
void error (LPCTSTR fmt, ...)
Definition at line 162 of file pdfdde.cpp.
{
/*
    va_list ap;
    va_start(ap, fmt);
    vfprintf(stderr, fmt, ap);
    va_end(ap);
    fputc('\n', stderr);
*/
    /* Tidy up */
    CloseConversation();
/*
    exit(1);
*/
}
References CloseConversation().
Referenced by dynadjust::networkadjust::adjust_combine_thread::adjust_combine_thread(), dynadjust::networkadjust::adjust_forward_thread::adjust_forward_thread(), dynadjust::networkadjust::adjust_prepare_thread::adjust_prepare_thread(), dynadjust::networkadjust::adjust_process_combine_thread::adjust_process_combine_thread(), dynadjust::networkadjust::adjust_process_prepare_thread::adjust_process_prepare_thread(), dynadjust::networkadjust::adjust_reverse_thread::adjust_reverse_thread(), DDEString(), emalloc(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ErrorCaption(), dynadjust::geoidinterpolation::dna_geoid_interpolation::ErrorString(), ExecuteCommand(), OpenConversation(), RequestData(), and StartServer().
emalloc()
void * emalloc (size_t len)
Definition at line 178 of file pdfdde.cpp.
{
    void *p = malloc(len);
    if (p == NULL)
    error("Out of memory - cannot allocate %d bytes", len);
    return p;
}
References error().
Referenced by RequestData().
Callback()
HDDEDATA CALLBACK Callback (UINT uType, UINT uFmt, HCONV hconv, HSZ hsz1, HSZ hsz2, HDDEDATA hdata, DWORD dwData1, DWORD dwData2)
Definition at line 191 of file pdfdde.cpp.
{
    if (uType == XTYP_ADVDATA) {
    DWORD len = DdeGetData(hdata, NULL, 0, 0);
    char *buf = (char *)_alloca(len + 1);
    DdeGetData(hdata, (LPBYTE)buf, len + 1, 0);
    if (--outstanding_requests == 0)
        PostQuitMessage(0);
    return (HDDEDATA) DDE_FACK;
    }
    return (HDDEDATA) NULL;
}
References outstanding_requests.
Referenced by OpenConversation().
StartServer()
int StartServer (LPCTSTR prog)
Definition at line 208 of file pdfdde.cpp.
{
    STARTUPINFO si;
    PROCESS_INFORMATION pi;
    /* To be sure ... */
    if (! prog)
    return 1;
    ZeroMemory (&si, sizeof (si));
    si.cb = sizeof (si);
    if (!CreateProcess (NULL, (LPTSTR)prog, NULL, NULL, FALSE, 0,
            NULL, NULL, &si, &pi))
    {
    error("Could not start process %s", prog);
    return 1;
    }
    /* Wait for the process to enter an idle state */
    WaitForInputIdle (pi.hProcess, MAX_INPUT_IDLE_WAIT);
    /* Close the handles */
    CloseHandle (pi.hThread);
    CloseHandle (pi.hProcess);
    return 0;
}
References error(), FALSE, and MAX_INPUT_IDLE_WAIT.
Referenced by OpenConversation().
DDEString()
HSZ DDEString (LPCTSTR str)
Definition at line 235 of file pdfdde.cpp.
{
    HSZ hsz = DdeCreateStringHandle(DDEsession, str, CP_WINANSI);
    if (hsz == 0)
    error("Cannot create string for %s", str);
    return hsz;
}
References DDEsession, and error().
Referenced by OpenConversation(), RequestData(), and StartHotLink().
FreeString()
void FreeString (HSZ hsz)
Definition at line 243 of file pdfdde.cpp.
{
    DdeFreeStringHandle(DDEsession, hsz);
}
References DDEsession.
Referenced by OpenConversation(), RequestData(), and StartHotLink().
OpenConversation()
void OpenConversation (LPCTSTR topic_name)
Definition at line 248 of file pdfdde.cpp.
{
    UINT ret;
    HSZ service;
    HSZ topic;
    int n;
    ret = DdeInitialize(&DDEsession, Callback, APPCLASS_STANDARD| APPCMD_CLIENTONLY, 0);
    if (ret != DMLERR_NO_ERROR)
    error("Cannot start DDE");
    service = DDEString(ACROBAT);
    topic = DDEString(topic_name);
    DDEconversation = DdeConnect(DDEsession, service, topic, 0);
    if (DDEconversation == 0)
    {
    if (StartServer(FindAcrobatModule()) == 0)
    {
        /* Try to connect */
        for (n = 0; n < 5; n++)
        {
        Sleep (CONNECT_DELAY);
        DDEconversation = DdeConnect(DDEsession, service, topic, 0);
        if (DDEconversation)
            break;
        }
        if (DDEconversation == 0)
        error("Cannot contact server %s", ACROBAT);
    }
    }
    FreeString(service);
    FreeString(topic);
}
References ACROBAT, Callback(), CONNECT_DELAY, DDEconversation, DDEsession, DDEString(), error(), FindAcrobatModule(), FreeString(), and StartServer().
Referenced by pdfclose(), pdfopen(), pdfserver(), and TellReaderToJumpToNamedDestViaDDE().
ExecuteCommand()
bool __cdecl ExecuteCommand (LPCTSTR command, ...)
Definition at line 283 of file pdfdde.cpp.
{
    HDDEDATA ret;
    va_list args;
    int len;
    char *buffer;
    va_start( args, command );
    len = _vscprintf(command, args) // _vscprintf doesn't count
      + 1;          // terminating '\0'
    buffer = (char *)malloc( len * sizeof(char) );
    vsprintf( buffer, command, args );
    va_end(args);
    ret = DdeClientTransaction((LPBYTE)buffer, strlen(buffer) + 1,
                   DDEconversation, 0, 0, XTYP_EXECUTE,
                   TRANSACTION_TIMEOUT, 0);
    if (ret == 0)
    {
        UINT DDEErr = DdeGetLastError(DDEsession);
        error("Cannot execute command \"%s\" (error %ld)", command, DDEErr);
        return(false);
    } // if
    return(true);
}
References DDEconversation, DDEsession, error(), and TRANSACTION_TIMEOUT.
Referenced by pdfclose(), pdfopen(), pdfserver(), and TellReaderToJumpToNamedDestViaDDE().
StartHotLink()
void StartHotLink (LPCTSTR item_name)
Definition at line 311 of file pdfdde.cpp.
{
    HSZ item = DDEString(item_name);
    DdeClientTransaction(0, 0, DDEconversation, item, CF_TEXT, XTYP_ADVSTART,
             TRANSACTION_TIMEOUT, 0);
    FreeString(item);
}
References DDEconversation, DDEString(), FreeString(), and TRANSACTION_TIMEOUT.
RequestData()
LPTSTR RequestData (LPCTSTR item_name)
Definition at line 319 of file pdfdde.cpp.
{
    HSZ item = DDEString(item_name);
    DWORD len;
    char *buf;
    HDDEDATA result;
    result = DdeClientTransaction (NULL, 0, DDEconversation, item, CF_TEXT,
                   XTYP_REQUEST, TRANSACTION_TIMEOUT, 0);
    FreeString(item);
    if (result == 0)
    error("Cannot request item %s\n", item_name);
    len = DdeGetData(result, NULL, 0, 0);
    buf = (char *)emalloc(len + 1);
    DdeGetData(result, (LPBYTE)buf, len + 1, 0);
    return buf;
}
References DDEconversation, DDEString(), emalloc(), error(), FreeString(), and TRANSACTION_TIMEOUT.
CheckFileName()
char * CheckFileName (char * p)
Definition at line 357 of file pdfdde.cpp.
{
  char sTmp[MAXPATHLEN];
  char *fp;
  sLongFileName[0] = '\0';
  if (GetFileAttributes(p) == -1) {
    fprintf(stderr, "%s: non existent file %s\n", argv0, p);
    return NULL;
  }
  if (GetFullPathName(p, sizeof(sTmp), sTmp, &fp) == 0) {
    fprintf(stderr, "%s: failed to get full path name for %s (Error %d)\n", argv0, p, GetLastError());
    return NULL;
  }
  if (GetLongPathName(sTmp, sLongFileName, sizeof(sLongFileName)) == 0) {
    fprintf(stderr, "%s: failed to get long path name for %s (Error %d)\n", argv0, sTmp, GetLastError());
    return NULL;
  }
  return sLongFileName;
}
References argv0, MAXPATHLEN, and sLongFileName.
Referenced by pdfserver().
pdfopen()
int pdfopen ()
Definition at line 379 of file pdfdde.cpp.
{
  if (sLongFileName[0] == '\0') {
    fprintf(stderr, "%s: mandatory `--file' argument not found.\n", argv0);
    return EXIT_FAILURE;
  }
  OpenConversation(EVAL_TOPIC);
  ExecuteCommand("[DocOpen(\"%s\")]", sLongFileName);
  ExecuteCommand("[DocOpen(\"%s\")]", sLongFileName); /* acrord32 ver8 bug */
  ExecuteCommand("[FileOpen(\"%s\")]", sLongFileName);
  if (nPage > 0) {
    ExecuteCommand("[DocGoTo(\"%s\", %d)]", sLongFileName, nPage);
  }
  if (sGoto != NULL) {
    ExecuteCommand("[DocGoToNameDest(\"%s\", %s)]", sLongFileName, sGoto);
  }
  if (bBack) {
    ExecuteCommand("[MenuitemExecute(\"GoBack\")]");
  }
  CloseConversation();
#if 0
  /* Problem : it seems that these calls can put AR into a strange state.
     It would have been simpler if Adobe had simply iconified their application. */
  if (stricmp(argv0, "pdfclose") == 0) {
    sprintf(buf, "[AppHide()]");
  }
  else if (stricmp(argv0, "pdfopen") == 0) {
    sprintf(buf, "[AppShow()]");
  }
  bRetVal = DdeClientTransaction((unsigned char *)buf, (DWORD)strlen(buf),
                 (HCONV)hConversation, NULL,
                 (UINT)CF_TEXT, (UINT)XTYP_EXECUTE, (DWORD)1000, &dwResult);
#endif
  return EXIT_SUCCESS;
}
References argv0, bBack, CloseConversation(), EVAL_TOPIC, ExecuteCommand(), nPage, OpenConversation(), sGoto, and sLongFileName.
pdfclose()
int pdfclose ()
Definition at line 422 of file pdfdde.cpp.
{
    if (!bAll && sLongFileName[0] == '\0') {
        fprintf(stderr, "%s: mandatory `--file' argument not found.\n", argv0);
        return EXIT_FAILURE;
    }
    OpenConversation(EVAL_TOPIC);
    if (bAll) {
    ExecuteCommand("[CloseAllDocs()]");
    }
    else if (sLongFileName[0] != '\0') {
    ExecuteCommand("[DocClose(\"%s\")]", sLongFileName);
    }
#if 0
    fprintf(stderr, "cmd : %s\n", buf);
#endif
    CloseConversation();
    return EXIT_SUCCESS;
}
References argv0, bAll, CloseConversation(), EVAL_TOPIC, ExecuteCommand(), OpenConversation(), and sLongFileName.
pdfserver()
int pdfserver ()
Definition at line 447 of file pdfdde.cpp.
{
  char line[1024];
  OpenConversation(EVAL_TOPIC);
  fprintf(stdout, "Type Ctrl-Z to quit.\n");
  while (fgets(line, sizeof(line), stdin)) {
#define WHITE_DELIM " \t\n"
    char *p = strtok(line, WHITE_DELIM);
    if (stricmp(p, "open") == 0) {
      p = strtok(NULL, WHITE_DELIM);
      if (CheckFileName(p) == NULL) goto next;
      ExecuteCommand("[DocOpen(\"%s\")]", sLongFileName);
      ExecuteCommand("[DocOpen(\"%s\")]", sLongFileName); /* acrord32 ver8 bug */
    }
    else if (stricmp(p, "close") == 0) {
      p = strtok(NULL, WHITE_DELIM);
      if (CheckFileName(p) == NULL) goto next;
      ExecuteCommand("[DocClose(\"%s\")]", sLongFileName);
    }
    else if (stricmp(p, "closeall") == 0) {
      ExecuteCommand("[CloseAllDocs()]");
    }
    else if (stricmp(p, "goto") == 0) {
      p = strtok(NULL, WHITE_DELIM);
      if (p == NULL) goto next;
      if (CheckFileName(p) == NULL) goto next;
      p = strtok(NULL, WHITE_DELIM);
      if (p == NULL) goto next;
      nPage = atoi(p) - 1;
      ExecuteCommand("[DocGoTo(\"%s\", %d)]", sLongFileName, nPage);
    }
    else if (stricmp(p, "gotoname") == 0) {
      p = strtok(NULL, WHITE_DELIM);
      if (p == NULL) goto next;
      if (CheckFileName(p) == NULL) goto next;
      p = strtok(NULL, WHITE_DELIM);
      if (p == NULL) goto next;
      sGoto = p;
      ExecuteCommand("[DocGoToNameDest(\"%s\", %s)]", sLongFileName, sGoto);
    }
    else if (stricmp(p, "show") == 0) {
      ExecuteCommand("[AppShow()]");
    }
    else if (stricmp(p, "hide") == 0) {
      ExecuteCommand("[AppHide()]");
    }
    else if (stricmp(p, "exit") == 0) {
      ExecuteCommand("[AppExit()]");
      goto exit;
    }
    else if (stricmp(p, "back") == 0) {
      ExecuteCommand("[MenuitemExecute(\"GoBack\")]");
    }
    else if (stricmp(p, "list") == 0) {
      fprintf(stdout, "open <file>      open the file\n");
      fprintf(stdout, "close <file>     close the file\n");
      fprintf(stdout, "closeall     close all files\n");
      fprintf(stdout, "goto <file> <page>   goto the given <page> in <file>\n");
      fprintf(stdout, "gotoname <file> <dest>   goto the <dest> named destination in <file>\n");
      fprintf(stdout, "back                     goto the previous view\n");
      fprintf(stdout, "show         show acroview\n");
      fprintf(stdout, "hide         hide acroview\n");
      fprintf(stdout, "exit         exit acroview and %s\n", argv0);
    }
  next: ;
  }
#if 0
  fprintf(stderr, "cmd : %s\n", buf);
#endif
exit:
  CloseConversation();
  return EXIT_SUCCESS;
}
References argv0, CheckFileName(), CloseConversation(), EVAL_TOPIC, ExecuteCommand(), nPage, OpenConversation(), sGoto, sLongFileName, and WHITE_DELIM.
TellReaderToJumpToNamedDestViaDDE()
bool TellReaderToJumpToNamedDestViaDDE (const char * FullFilePath, const char * NamedDest)
Definition at line 642 of file pdfdde.cpp.
{
bool Success = false;
// this will start Reader (or whatever PDF host is available) if not started
OpenConversation(EVAL_TOPIC);
// Komrade! Use largest hammer to beat Adobe Reader into submission!
ExecuteCommand("[DocClose(\"%s\")]", FullFilePath);
ExecuteCommand("[DocOpen(\"%s\")]", FullFilePath);
ExecuteCommand("[DocOpen(\"%s\")]", FullFilePath); /* acrord32 ver8 bug */
ExecuteCommand("[FileOpen(\"%s\")]", FullFilePath);
Success = ExecuteCommand("[DocGoToNameDest(\"%s\", %s)]", FullFilePath, NamedDest);
CloseConversation();
return(Success);
} // TellReaderToJumpToNamedDestViaDDE
References CloseConversation(), EVAL_TOPIC, ExecuteCommand(), and OpenConversation().
Variable Documentation
DDEsession
DWORD DDEsession static
Definition at line 61 of file pdfdde.cpp.
Referenced by CloseConversation(), DDEString(), ExecuteCommand(), FreeString(), and OpenConversation().
DDEconversation
HCONV DDEconversation static
Definition at line 62 of file pdfdde.cpp.
Referenced by CloseConversation(), ExecuteCommand(), OpenConversation(), RequestData(), and StartHotLink().
argv0
char* argv0 = NULL static
Definition at line 65 of file pdfdde.cpp.
Referenced by CheckFileName(), pdfclose(), pdfopen(), and pdfserver().
nPage
int nPage = 0 static
Definition at line 66 of file pdfdde.cpp.
Referenced by pdfopen(), and pdfserver().
sFileName
char* sFileName = NULL static
Definition at line 67 of file pdfdde.cpp.
Referenced by CFileProc::ChangeFileName(), and CFileProc::Initialize().
bAll
int bAll = 0 static
Definition at line 68 of file pdfdde.cpp.
Referenced by pdfclose().
bBack
int bBack = 0 static
Definition at line 69 of file pdfdde.cpp.
Referenced by pdfopen().
bServer
int bServer = 0 static
Definition at line 70 of file pdfdde.cpp.
iDebug
int iDebug = 0 static
Definition at line 71 of file pdfdde.cpp.
sGoto
char* sGoto = NULL static
Definition at line 72 of file pdfdde.cpp.
Referenced by pdfopen(), and pdfserver().
sLongFileName
char sLongFileName[MAXPATHLEN] static
Definition at line 73 of file pdfdde.cpp.
Referenced by CheckFileName(), pdfclose(), pdfopen(), and pdfserver().
pdfdde_version_string
const char* pdfdde_version_string = "0.2"
Definition at line 75 of file pdfdde.cpp.
outstanding_requests
int outstanding_requests
Definition at line 188 of file pdfdde.cpp.
Referenced by Callback().