DynAdjust: dynadjust::frame_substitutions::CompareSubstituteOnFrameName< T, S > Struct Template Reference
dynadjust::frame_substitutions::CompareSubstituteOnFrameName< T, S > Struct Template Reference
#include <dnaframesubstitutions.hpp>
Public Member Functions
bool operator() (const boost::shared_ptr< T > &lhs, const boost::shared_ptr< T > &rhs) const
bool operator() (const boost::shared_ptr< T > &lhs, const S &rhs) const
bool operator() (const S &lhs, const boost::shared_ptr< T > &rhs) const
bool pair_firstless (const S &s1, const S &s2) const
Detailed Description
template<typename T, typename S>
struct dynadjust::frame_substitutions::CompareSubstituteOnFrameName< T, S >
Definition at line 403 of file dnaframesubstitutions.hpp.
Member Function Documentation
operator()() [1/3]
template<typename T, typename S> bool dynadjust::frame_substitutions::CompareSubstituteOnFrameName< T, S >::operator() (const boost::shared_ptr< T > & lhs, const boost::shared_ptr< T > & rhs) const inline
Definition at line 406 of file dnaframesubstitutions.hpp.
{
        if (lhs->getFrameName() == rhs->getFrameName())
            return lhs->getFromEpoch() < rhs->getFromEpoch();
        return pair_firstless(lhs->getFrameName(), rhs->getFrameName());
    }
References pair_firstless().
operator()() [2/3]
template<typename T, typename S> bool dynadjust::frame_substitutions::CompareSubstituteOnFrameName< T, S >::operator() (const boost::shared_ptr< T > & lhs, const S & rhs) const inline
Definition at line 411 of file dnaframesubstitutions.hpp.
{
        return pair_firstless(lhs->getFrameName(), rhs);
    }
References pair_firstless().
operator()() [3/3]
template<typename T, typename S> bool dynadjust::frame_substitutions::CompareSubstituteOnFrameName< T, S >::operator() (const S & lhs, const boost::shared_ptr< T > & rhs) const inline
Definition at line 414 of file dnaframesubstitutions.hpp.
{
        return pair_firstless(lhs, rhs->getFrameName());
    }
References pair_firstless().
pair_firstless()
template<typename T, typename S> bool dynadjust::frame_substitutions::CompareSubstituteOnFrameName< T, S >::pair_firstless (const S & s1, const S & s2) const inline
Definition at line 418 of file dnaframesubstitutions.hpp.
{
        return s1 < s2;
    }
Referenced by operator()(), operator()(), and operator()().
The documentation for this struct was generated from the following file:
include/parameters/dnaframesubstitutions.hpp