DynAdjust: dynadjust::iostreams::CompareDiscontinuityOnSite< T, S > Struct Template Reference
dynadjust::iostreams::CompareDiscontinuityOnSite< T, S > Struct Template Reference
#include <dnaiosnx.hpp>
Public Member Functions
bool operator() (const T &lhs, const S &rhs) const
bool operator() (const S &lhs, const T &rhs) const
bool pair_firstless (const S &s1, const S &s2) const
Detailed Description
template<typename T, typename S>
struct dynadjust::iostreams::CompareDiscontinuityOnSite< T, S >
Definition at line 201 of file dnaiosnx.hpp.
Member Function Documentation
operator()() [1/2]
template<typename T, typename S> bool dynadjust::iostreams::CompareDiscontinuityOnSite< T, S >::operator() (const T & lhs, const S & rhs) const inline
Definition at line 204 of file dnaiosnx.hpp.
{
        return pair_firstless(lhs.site_name, rhs);
    }
References pair_firstless().
operator()() [2/2]
template<typename T, typename S> bool dynadjust::iostreams::CompareDiscontinuityOnSite< T, S >::operator() (const S & lhs, const T & rhs) const inline
Definition at line 207 of file dnaiosnx.hpp.
{
        return pair_firstless(lhs, rhs.site_name);
    }
References pair_firstless().
pair_firstless()
template<typename T, typename S> bool dynadjust::iostreams::CompareDiscontinuityOnSite< T, S >::pair_firstless (const S & s1, const S & s2) const inline
Definition at line 211 of file dnaiosnx.hpp.
{
        return s1 < s2;
    }
Referenced by operator()(), and operator()().
The documentation for this struct was generated from the following file:
include/io/dnaiosnx.hpp