DynAdjust: dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 > Struct Template Reference
dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 > Struct Template Reference
#include <dnaiotbu.hpp>
Public Member Functions
type_b_uncertainty_t ()
void set_station_id (const T1 &stn=0)
void set_typeb_values_3d (const T2 &e, const T2 &n, const T2 &u)
bool operator== (const type_b_uncertainty_t< T1, T2, T3 > &rhs)
bool operator< (const type_b_uncertainty_t< T1, T2, T3 > &rhs) const
Public Attributes
T1 station_id
T3 type_b
Detailed Description
template<class T1 = UINT32, class T2 = double, class T3 = matrix_2d>
struct dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >
Definition at line 50 of file dnaiotbu.hpp.
Constructor & Destructor Documentation
type_b_uncertainty_t()
template<class T1 = UINT32, class T2 = double, class T3 = matrix_2d> dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::type_b_uncertainty_t () inline
Definition at line 55 of file dnaiotbu.hpp.
        : station_id(0) {
        type_b.redim(3, 3);
    }
Member Function Documentation
set_station_id()
template<class T1 = UINT32, class T2 = double, class T3 = matrix_2d> void dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::set_station_id (const T1 & stn = 0) inline
Definition at line 60 of file dnaiotbu.hpp.
{ station_id =stn; }
Referenced by dynadjust::iostreams::dna_io_tbu::load_tbu_file().
set_typeb_values_3d()
template<class T1 = UINT32, class T2 = double, class T3 = matrix_2d> void dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::set_typeb_values_3d (const T2 & e, const T2 & n, const T2 & u) inline
Definition at line 62 of file dnaiotbu.hpp.
{
        type_b.put(0, 0, e);
        type_b.put(1, 1, n);
        type_b.put(2, 2, u);
    }
Referenced by dynadjust::iostreams::dna_io_tbu::assign_typeb_values_global(), and dynadjust::iostreams::dna_io_tbu::assign_typeb_values_local().
operator==()
template<class T1 = UINT32, class T2 = double, class T3 = matrix_2d> bool dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::operator== (const type_b_uncertainty_t< T1, T2, T3 > & rhs) inline
Definition at line 68 of file dnaiotbu.hpp.
{
        return equal(station_id, rhs.station_id);
    }
operator<()
template<class T1 = UINT32, class T2 = double, class T3 = matrix_2d> bool dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::operator< (const type_b_uncertainty_t< T1, T2, T3 > & rhs) const inline
Definition at line 72 of file dnaiotbu.hpp.
    {
        return station_id < rhs.station_id;
    }
Member Data Documentation
station_id
template<class T1 = UINT32, class T2 = double, class T3 = matrix_2d> T1 dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::station_id
Definition at line 52 of file dnaiotbu.hpp.
Referenced by dynadjust::iostreams::type_b_uncertainty_t< UINT32, double, matrix_2d >::operator<(), and dynadjust::iostreams::type_b_uncertainty_t< UINT32, double, matrix_2d >::operator==().
type_b
template<class T1 = UINT32, class T2 = double, class T3 = matrix_2d> T3 dynadjust::iostreams::type_b_uncertainty_t< T1, T2, T3 >::type_b
Definition at line 53 of file dnaiotbu.hpp.
Referenced by dynadjust::iostreams::dna_io_tbu::reduce_uncertainties_global().
The documentation for this struct was generated from the following file:
include/io/dnaiotbu.hpp